### ISSUE TITLE
Dart doesn't respect user VSCode tab/indent spacing on "format document"

### ISSUE THREAD

**Issue by AshSimmonds** [Dart-Code/Dart-Code#1015]
Original post: https://groups.google.com/forum/#!topic/flutter-dev/TxdQmK0pj5M

"I've tracked it down specifically to the Dart extension, as when it's enabled it overrides any settings I have. Tried EditorConfig and everything else I can imagine. 

Others have had this issue, but none that are specifically Dart, so none of the solutions I've found fix this.

Anyone know where to look to figure this out?"

**Comment by DanTup** [comment]
Can you clarify the issue you're seeing? Are you saying that Dart Code is changing your indent settings back away from tabs, of that when you Format Document (including with `formatOnSave`) that it ignores this and always uses spaces?

The first would be a bug, but I've just tested and can't reproduce - if I set the indent to tabs then it seems to work fine. However the second is by design - Dart Code uses the standard Dart formatter which only supports spaces - if you'd like to see an alternative formatter please 👍 https://github.com/Dart-Code/Dart-Code/issues/914 (no guarantees it'll happen, but the 👍's on that issue will hopefully give an idea of demand).

Also related: #960.

**Comment by DanTup** [comment]
Oh, also worth noting that we do set the defaults; so if you're trying to set them yourself, you'll need to set it for the `dart` language in your user settings:

```js
"[dart]": {
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
	"editor.detectIndentation": false
}
```

**Comment by AshSimmonds** [comment]
It always uses 2 spaces no matter what you set in VSCode.

Doesn't matter what you put in user settings, dart files ignore it and just use 2 spaces.

This only happens when the Dart extension is enabled.

**Comment by DanTup** [comment]
@AshSimmonds I tested with the settings above and also setting using the status bar but couldn't reproduce this. Can you provide some specific info on what you're set up or how you're setting it and where you're seeing it use spaces?

I presume you're on a recent version of the extension? A very old version *did* force space indenting as you opened a file simply because it was the only way to control it at the time.

**Comment by AshSimmonds** [comment]
Hmm, maybe the title is misleading - I mean on "format code" execution, not physically pressing tab. Sorry if that changes everything.

I can record a demo if needed - but notice in your screenshot you're using tabs, I have mine set to change tabs to spaces, and I want 4 spaces, not 2. 

I reformat my code pretty frequently so I can just get on with writing it, in the mean time I'm using a macro to reformat the reformat - but you get how onerous this can be.

I'm using latest of everything - have just uninstalled and reinstalled pretty much everything to check.

**Comment by AshSimmonds** [comment]
And I must have been drunk when I posted my reply earlier, as I completely missed your link to #914 - sorry about that.

Closing this, thanks for your help.

**Comment by AshSimmonds** [comment]
Hehe, yeah. Thanks for your help.

**Comment by Macromeda** [comment]
This is a really annoying issue.
Thanks DanTup for the help.

**Comment by hardy12994** [comment]
https://github.com/Dart-Code/Dart-Code/issues/1015#issuecomment-397763102
Works for me @DanTup +1

**Comment by nathanfranke** [comment]
Make sure to edit the [dart] config and not the generic vscode config!

![image](https://user-images.githubusercontent.com/14253836/88288574-9d66d680-ccb9-11ea-9993-f8fc9eba61e0.png)

Otherwise, it seems to work!

**Comment by JohnGalt1717** [comment]
When doing format on save, it undoes the tabSize 4 and goes back to 2, even though it respects it while typing as far as I can tell.

**Comment by DanTup** [comment]
> When doing format on save, it undoes the tabSize 4 and goes back to 2

This is expected - the formatter only supports spaces. If you want to use tabs, you'll need to turn off the formatter (you can do this using by adding `"dart.enableSdkFormatter": false` to your VS Code user settings).

**Comment by JohnGalt1717** [comment]
@DanTup Yuk.

**Comment by JohnGalt1717** [comment]
@DanTup To expound on that, here's why:

The reason why Tab are preferred for us is because a tab can be represented on the screen however you wish. It means "indent".  Using editorConfig or vs code's settings, every developer can just specify how they want an "indent" to show up.  I don't have to force my devs to use X number of spaces for indent, they can use whatever they wish while still having compliant code.

Hence forcing spaces is not cool because every dev has to use whatever I set it to, instead of whatever they feel comfortable with and if they change it or override it, their code will look different than everyone else's and we'll have checkin fights that are only different because of the number of spaces.

**Comment by DanTup** [comment]
@JohnGalt1717 I very much understand the desire for tabs - I'm a tab person myself. Formatting is not handled by the VS Code extension, it's done by the language server - so formatting here is restricted by what the server supports (which is only [dart_style](https://pub.dev/packages/dart_style)).

There's an open issue about supporting something customisable (https://github.com/Dart-Code/Dart-Code/issues/914). The decision not to work on it is not because it's not desired, but because time is finite and there have so far always been other things that appear to deliver more value.

I've offered some pointers in that issue if anyone wants to create an alternative formatter that could be shipped as a VS Code extension (and I've ensured it would place nice with the Dart extension). I'm sorry this isn't the answer you'd like, but I hope you understand.

**Comment by Wdestroier** [comment]
Took me some time to find this problem. It would be great to configure vscode to use a 4 spaces long tab width...

**Comment by kubilayakaslan** [comment]
Hi

VSCode Settings>Extensions>Dart&Flutter uncheck Dart:Enable SDK Formatter

**Comment by karimomaya** [comment]
You need to configure dart settings by going to Preferences: Configure Language Specific Settings. 
Press ctrl+p then write ">Preferences: Configure Language Specific Settings" and update dart settings 
`
"[dart]": {
		"editor.tabSize": 4,
		"editor.insertSpaces": false,
		"editor.detectIndentation": false
}
`
For me i made this configuration globally and for dart and everything work as expected
`
"[dart]": {
		"editor.tabSize": 4,
		"editor.insertSpaces": false,
		"editor.detectIndentation": false
},
"editor.tabSize": 4,
"editor.insertSpaces": false,
"editor.detectIndentation": false
`

**Comment by ssatguru** [comment]
@karimomaya  Those settings are ignored if "dart.enableSdkFormatter" is set to true. :(

**Comment by clebemachado** [comment]
> @karimomaya Essas configurações serão ignoradas se "dart.enableSdkFormatter" forem definidas como verdadeiras. :( Por enquanto desliguei o formador para dar um descanso aos olhos :)

Ok, its work

```
"dart.enableSdkFormatter": false,
````

**Comment by aaronjc15128** [comment]
This is what I have and it seems to work fine with 4 spaces.
Only problem is using snippets, since they are all written in 2 spaces :(

```
"[dart]" : {
    "editor.formatOnSave": false,
    "editor.formatOnType": false,
    "editor.tabSize": 4,
    "editor.insertSpaces": false,
    "editor.detectIndentation": false
},
"editor.detectIndentation": false,
"editor.indentSize": "tabSize",
"dart.enableSdkFormatter": false
```

**Comment by RayendraSabandar** [comment]
> Oh, also worth noting that we do set the defaults; so if you're trying to set them yourself, you'll need to set it for the `dart` language in your user settings:
> 
> ```js
> "[dart]": {
> 	"editor.tabSize": 4,
> 	"editor.insertSpaces": false,
> 	"editor.detectIndentation": false
> }
> ```

I think this is the answers that the people in #914 are looking for. Hopefully they get to see this and make this changes

**Comment by Number-3434** [comment]
Add this to your `keybindings.json`:
```
{
		"key": "cmd+s",
		"command": "runCommands",
		"args": {
			"commands": [
				"editor.action.indentationToTabs",
				"workbench.action.files.save",
			]
		},
		"when": "editorLangId == dart"
	},
	{
		"key": "cmd+s",
		"command": "workbench.action.files.save",
		"when": "editorLangId != dart"
	},
```
This manually forces the editor to convert all indentation to tabs. Note that this method may cause a lag, as every time the file's indentation is converted to spaces, then back to tabs.

**Comment by hahnemann** [comment]
As a software engineer for 30 years - this should always always be optional! Do not force formatters on users. Terrible engineering.

**Comment by AshSimmonds** [comment]
LMAO this is still a thing?

**Comment by lucagalantiatwork** [comment]
Hi everyone. I fixed the issue in Neovim by bypassing the LSP formatter entirely. I send the current buffer to dart format through stdin, then post-process the formatter output line by line to adjust the indentation spaces before rewriting the buffer contents. Here is the code. I have no idea whether something similar can also be done in VSCode.

```lua
M.format = function(ev)
   vim.keymap.set('n', "<C-A-f>", function()
         if vim.bo.filetype == "dart" then

            local buf = vim.api.nvim_get_current_buf()
            local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)

            local job = vim.fn.jobstart({ "dart", "format", "-o", "show" }, {
               stdout_buffered = true, -- a true aspetta tutto l'output della shell
               stderr_buffered = true, -- a true aspetta tutto l'output della shell

               on_stdout = function(_, data)
                  if not data or #data == 0 then
                     return
                  end

                  vim.schedule(function()
                     for i, line in ipairs(data) do
                        data[i] = line:gsub("^( +)", function(indent)
                           local livello = math.floor(#indent / 2)
                           return string.rep("   ", livello)
                        end)
                     end

                     vim.api.nvim_buf_set_lines(buf, 0, -1, false, data)
                  end)
               end,
            })

            -- inviamo il buffer allo stdin del formatter
            vim.fn.chansend(job, lines)

            -- chiudiamo lo stdin: come premere Ctrl+D
            vim.fn.chanclose(job, "stdin")
         elseif vim.bo.filetype == "sh" then
            -- formatter per bash sincrono. winsaveview() e
            -- winrestview() servono, di fatto, a ripristinare
            -- la posizione relativa del cursore quando si
            -- formatta. Altrimenti ci si ritroverebbe all'ini_
            -- zio del file tutte le volte.
            local view = vim.fn.winsaveview()
            vim.cmd("%!shfmt -i 3 -ci")
            vim.fn.winrestview(view)
         else
            vim.lsp.buf.format({ async = true })
         end
      end,
      { buffer = ev.buf, desc = "Formatta intero documento" })
end

return M
```
The script also contains other formatter cases (Bash and all the other languages that work normally through the LSP formatter).
Of course, the script could be improved a lot further by adding support for formatting single lines or selected code blocks instead of always formatting the entire buffer.

gpt 5.5 says for VSCode:

VSCode Extension
   ↓
spawn("dart format")
   ↓
stdin.write(documentText)
   ↓
stdout
   ↓
post-process indentation
   ↓
replace editor content

Comments are in Italian ... because I am Italian 👍 .
