### ISSUE TITLE
Ability to extract class into file

### ISSUE THREAD

**Issue by jrote1** [Dart-Code/Dart-Code#102]

**Comment by DanTup** [comment]
I don't think the analyzer supports this, so would need a new feature?

**Comment by DanTup** [comment]
Actually, I'm not sure 1-class-per-file is the Dart way; maybe that's why the analyzer doesn't have it?

https://github.com/dart-lang/site-www/issues/36

I think this will probably have to be wontfixed, I don't think it's something that would be added to the AS.

**Comment by DanTup** [comment]
Based on suggestions that Dart classes shouldn't be in their own file and that this would require support from the Dart Analyzer, I don't believe it will ever be implementable. Sorry!

**Comment by shyndman** [comment]
Hi @DanTup,

Is there a limitation of the assist API that prevents the creation of a file? Is that the specific issue?

**Comment by DanTup** [comment]
@shyndman this quick fix would need to be implemented in the Dart analysis server (this is the language server that ships in the SDK that provides all the language functionality).

So [dart-lang/sdk](https://github.com/dart-lang/sdk) is the correct place for the request - though if the guidelines are to not have a single-file-per-class, I'm not sure if it would make much sense for it to be added there.

**Comment by shyndman** [comment]
Gotcha. My reading on this is that extracting a class into its own file doesn't mean it will stay that way — it could just be a handy starting point during a reorg. I can also imagine that moving a class to an arbitrary, existing file would be useful.

Thanks.

**Comment by DanTup** [comment]
> My reading on this is that extracting a class into its own file doesn't mean it will stay that way — it could just be a handy starting point during a reorg

That's true, but it seems like the most useful part of this would be to automatically create the file and give it a sensible name. If the user needs to specify the name it seems like this wouldn't really save much over pressing Ctrl+X to cut, Ctrl+N to create file, Ctrl+V to paste.

>  I can also imagine that moving a class to an arbitrary, existing file would be useful.

This feels a bit similar to above - you'd have to get the user to pick a file so in the end if wouldn't save much over Ctrl+X to cut, Ctrl+P to jump to file, Ctrl+V to paste (and doing if that way gets the benefits of VS Code's file selector doing smart things like showing recent files at the top).

**Comment by orestesgaolin** [comment]
> If the user needs to specify the name it seems like this wouldn't really save much over pressing Ctrl+X to cut, Ctrl+N to create file, Ctrl+V to paste.

I was looking for a way to extract class to a file and I find that the most "time consuming" part is usually proper selection of the class inside the file, not cutting and pasting it. Ability to just press CMD + . and then [Extract to a new file] would be just so convenient.

**Comment by DanTup** [comment]
> I find that the most "time consuming" part is usually proper selection of the class inside the file

Ah, I see. VS Code has an `Expand Selection`  command (which on Mac has a not-so-friendly keybind of `Ctrl`+`Shift`+`Cmd`+`Right Arrow`) which helps here (as long as your cursor is inside the class, not on the `class Foo` part), though is a little tedious. Collapsing the class also makes it a little easier to select.

What about if we improved the `Expand Selection` behaviour so that using it when the cursor is on the class name, it selected the whole class? I'm sure we can do that with the API, it just doesn't work by default because there's no special character at the start of the class that VS Code recognizes as a "block" (though I'm surprised it doesn't use the outline data to this this better automatically).

**Comment by DanTup** [comment]
Also - I don't know if this is definitely possible yet, but if we could contribute a context menu entry to VS Code's built-in Outline, we may be able to show a "Select class" (or "Copy(/cut) class to clipboard" entry there. I don't know if you could easily keybind that though, since it needs a selected entry in the outline.
