### ISSUE TITLE
Expressions in interpolated strings aren't coloured like simple variables

### ISSUE THREAD

**Issue by jrote1** [Dart-Code/Dart-Code#105]
Would be good to have the variables a different color so that their easier to see

**Comment by DanTup** [comment]
It looks like the [language syntax](https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json#L292) does know about these so this should be possible (I'm surprised it doesn't happen automatically).

TypeScript definitely highlights these differently, so we can review [theirs](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/syntaxes/TypeScript.tmLanguage.json#L931).

**Comment by ikhwanhayat** [comment]
I thought we already have this?

![image](https://cloud.githubusercontent.com/assets/35133/17721832/d82f33aa-645f-11e6-9332-f65952a27736.png)

Expressions inside the ${} aren't highlighted though.

IntelliSense works too! This is cool.

**Comment by jrote1** [comment]
For me they are not highlighted in any scenario

**Comment by ikhwanhayat** [comment]
@jrote1 Might be the color theme you use?  Mine is "Dark+ (default dark)".

**Comment by DanTup** [comment]
Yeah, "Dark (Visual Studio)" doesn't seem to handle this nicely, but "Dark+" does. Not sure if I changed it, or this was default. Maybe worth reporting the inconsistency in the [Code repo](https://github.com/microsoft/vscode/issues)?

Recategorizing this as a bug as that's how it appears to the user; we should try to fix.

(@devoncarew I think we stole this file from you, so this might affect Atom too?)

**Comment by DanTup** [comment]
Oh man, I just saw this sample on the Dart website:

```dart
List names = ['John', 'Sophena', 'Henrietta'];
print("${
  ((names) {
      return names[(new math.Random()).nextInt(names.length)];
  })(names)} is the most valueable member of our team");
```

Probably we'll have to settle with the whole expression being a single colour rather than nesting the colours.

**Comment by DanTup** [comment]
I've made this better, but unfortunately it's not possible to make accurate using regex. We now allow lots of characters inside these expressions and still match (anything except any of `{}"'`), however it breaks down if you include nested braces or strings (the problem with strings is that you can put braces inside them).

Since JS regex (AFAIK) doesn't have support for counting braces to figure out which closing brace actually matches the expression (consider `${something('with a } in a string'){`) I don't think I can properly fix this (though if anyone has ideas, I'm all ears!).

**Comment by jodinathan** [comment]
it is 2022.  
Maybe anything changed so it is able to highlight the interpolated code?

**Comment by jodinathan** [comment]
it is. Was a theme problem.  

thanks for the response tho
