### ISSUE TITLE
Render dark icons when using the light theme

### ISSUE THREAD

**Issue by sandangel** [Dart-Code/Dart-Code#1050]
Hi, I'm using a light theme now and I could not preview the Icon when hovering the Icons class because Icon preview color is white. How could I set the icon theme preview color to black or is there a way to dynamically set the preview icon color based on workbench theme?
![image](https://user-images.githubusercontent.com/22189661/42198611-ef0d44c4-7ec3-11e8-9958-a23599d3747e.png)

**Comment by DanTup** [comment]
Unfortunately VS Code doesn't give us any way to detect when you're using the light theme (see https://github.com/Microsoft/vscode/issues/46940) so the only option we have here is to move the icon to the gutter (where we can provide VS Code both a Dark and Light version). This isn't a quick change because currently we handle this in the tooltip provider, whereas to put in the gutter we'll need to be scanning the open document for icons up-front.

I had apparently forgotten to open an issue to do this though, so thanks for the reminder!

**Comment by DanTup** [comment]
@devoncarew Where is IntelliJ getting the data for this? I found [this code](https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/editor/FlutterEditorAnnotator.java) but it's not clear where the `Elements` are coming from - is this from it parsing its own code?

In order to move the icons from tooltips to the gutter (the only place we can support light/dark) I need to be able to find the Icon references in the code; but I'm not sure if it's exposed from the server (I've dug through Outline/FlutterOutline data and can't see icons for a simple case like `var a = Icons.ac_unit`).

**Comment by devoncarew** [comment]
We are leveraging IntelliJ's built in Dart parser and AST elements; this may not translate easily to VS Code ...

**Comment by DanTup** [comment]
Doh; that complicates this then. Possibly it could make sense for the server to provide this information (colour previews, icon previews) but since you can't directly get the URL from the Flutter source I think it might turn out to be a bit messy (slightly related to https://github.com/flutter/flutter/issues/11073).

I think we'll have to come back to this. If VS Code implements https://github.com/Microsoft/vscode/issues/32813 (which seems unlikely, though it is still open) then we might at least be able to fix the rendering in the tooltip.

**Comment by DanTup** [comment]
If you add the following to your settings:

```"dart.theme": "light"```

Then from vNext, the icons will appear black instead of white. Unfortunately you have to opt-in to the light theme manually, because VS Code doesn't have an API to tell us which theme you use (and seems unlikely to get one).
