### ISSUE TITLE
Test tree not refreshing properly after test file changes

### ISSUE THREAD

**Issue by dzarebski** [Dart-Code/Dart-Code#1097]
When I start VS Code and run tests without any changes to the test file, the test tree is displayed correctly.

![obraz](https://user-images.githubusercontent.com/626132/42932117-c0676386-8b41-11e8-9ff1-164d84757d6d.png)

After making some changes to the tests (e.g. adding new unit test) and running again, the tree is getting messed up (notice missing tests in History group):

![obraz](https://user-images.githubusercontent.com/626132/42932442-8cefda8c-8b42-11e8-8046-b015df896a48.png)

It's getting worse (or at least different) with each change I make to the test file. Example result after adding another unit test:

![obraz](https://user-images.githubusercontent.com/626132/42932518-c4eac7c6-8b42-11e8-9cb8-6d83217347b8.png)

After I restart VS Code it's all back to normal, until I start making changes again. After restart:

![obraz](https://user-images.githubusercontent.com/626132/42932793-8cd70da8-8b43-11e8-9998-e49531d44690.png)

For now I solely rely on the console output to check the test results. Hope you'll manage to reproduce the issue with the test tree.

Environment:
- Flutter 0.5.1
- VS Code: 1.25.1
  - Dart Code 2.16
  - Flutter 2.16
  - Git History 0.4.2
  - vscode-icons 7.24.0

**Comment by DanTup** [comment]
I noticed this yesterday - because we don't get stable identifiers from the test framework across runs we mark results as "stale" when you start a run and then remove anything that's left as stale at the end of the run. However there was a bug that didn't remove the stale groups (but did remove the tests, which is why the groups are all empty).

I have a fix for it, just fixing some CI issues so I can merge it, then it'll be in the next version.

You may still see dupes during a test run if the tests run in a different order, but they should all fix themselves as the test run progresses and then completes.

**Comment by DanTup** [comment]
Btw, I made an alpha build of the next version if you'd like to try it out (see [here](https://github.com/dart-lang/sdk/issues/33610#issuecomment-406308363) for download and instructions).

If you hit any issues with it, you can just uninstall it and re-install from the marketplace. It'll auto-update to the marketplace one next time I push a release automatically too.

**Comment by DanTup** [comment]
Should be fixed by #1108 which now reuses nodes based on their names rather than IDs (which are not stable across runs).
