### ISSUE TITLE
Debug: Long string values are truncated in the Watch view and when hovering over the variables

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#1101]
Hi,

you can see the problem in this screencast 

https://www.screencast.com/users/ThomasBurkhart/folders/Default/media/03c76ae3-bed8-4df6-ba44-bea846332864

Cheers
Thomas

**Comment by DanTup** [comment]
Ah, weird - looks like it's truncated in Watch but not in Locals! These are supposed to behave the same - I will investigate and fix :-)

**Comment by DanTup** [comment]
Seems like this might be a VS Code bug :(

In both the Variables and Watch window, we provide a truncated value to VS Code and give it an expression to evaluate when it wants the full value (it's by design that it's truncated in the tooltip, but Copy Value should get the full value).

I've opened https://github.com/Microsoft/vscode/issues/54853. For now, if you copy from the Variables/Locals list, you should get the value you expect.

**Comment by DanTup** [comment]
There is also possible a Dart Code bug too. In b113533 I've added `evaluateName` to child evaluate expressions. It'll need a Code change too though, which is potentially blocked on the Node extension doing something unexpected.

Btw, the tooltips here I can't reasonably fix - the reason they're truncated here is that we have to go back to the VM for the full value. This is fine for `Copy Value` because there's only one; but the tooltips have to be provided for the full list, so it could result in *lots* of requests if you had an array of, say, 100+ items.

**Comment by escamoteur** [comment]
IMHO truncating in the tool tip is completely fine. Copy value is important. Interestingly the trace breakpoints or how they are called don't truncate

**Comment by DanTup** [comment]
Log points are evaluated and printed from within the VM so they get the raw values (rather than getting the value back and then printing it from the editor, we basically wrap your expression in `print(...)` and then evaluate it, so the VM does the printing). The truncation seen in these tooltips/variables window/etc. is done by the VM service to try and reduce traffic over-the-wire to debuggers when we might not use it.

VS Code could call us when you move the mouse over it to get the tooltip, but they try to avoid anything where a slow-responding extension would make the UI feel sluggish (so the tooltips should be available up-front).

Hopefully if they fix the above it'll all seem good - but if it seems like having full strings would be a significant benefit, we could consider an option to control it (eg. you can choose to take the small perf hit to have the full strings), but we'd need to ensure VS Code isn't going to re-truncate the strings even if we get the full value from the VM.

**Comment by DanTup** [comment]
I've fixed my side of this so considering this fixed - however VS Code also had a fix that is only in Insiders - however I guess they have a release coming in the next week or so.

**Comment by BenjiFarquhar** [comment]
Seeing this 6 years later. All debug variables are truncated.

**Comment by DanTup** [comment]
@BenjiFarquhar it is expected that they'll be truncated in the tooltip. Can you right-click and choose "Copy Value" and confirm whether that's putting the whole value into the clipboard?

**Comment by BenjiFarquhar** [comment]
@DanTup Thanks for having a look. 

https://github.com/Dart-Code/Dart-Code/issues/4986
