### ISSUE TITLE
Extension flutter can't detect in the VS Code

### ISSUE THREAD

**Issue by daffakbar** [Dart-Code/Dart-Code#1103]
I have installed the Flutter and dart extension in VS Code.
but if i run flutter doctor -v 
like this.
![flutter](https://user-images.githubusercontent.com/36661135/43046307-31717646-8df1-11e8-86d9-b5444c433cfd.jpg)

how?
i want to build apk, i need run in the terminal in VScode "flutter build apk" but fail

**Comment by DanTup** [comment]
There was a bug in Flutter with the VS Code extension detection that was fixed in https://github.com/flutter/flutter/pull/18515.

This won't affect any use of Flutter so if you're having issues running `flutter build apk` please open a new issue in the flutter/flutter repo and include the details of the error you're seeing.
