### ISSUE TITLE
Unable to open 'libintegers_patch.dart': Cannot read property 'create' of undefined.

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1105]
I am not sure what caused this as I updated a few things in the mean time, but debugging now gives me a popup saying `Unable to open 'libintegers_patch.dart': Cannot read property 'create' of undefined.` when it hits an exception. I have everything pretty much on the newest version, but I can send version numbers if you want.

Something changed about the debugging interface as well because now I can see some kind of file tree when I start the debugger. However, somehow the debugger no longer pauses on uncaught exceptions. Instead it quits and prints some error the the debug output. I get:

```
loading test/all.dart:

ERROR: Failed to load "test/all.dart":
The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty

{stack trace in my project}
```

This could very well be an error with the test or analyzer package, but I am not sure to track down where it it coming from.

**Comment by DanTup** [comment]
> debugging now gives me a popup saying `Unable to open 'libintegers_patch.dart': Cannot read property 'create' of undefined.` when it hits an exception

Can you provide more info on what you're debugging (Dart VM app, Dart tests, Flutter app, Flutter tests, all of them?).

I presume you're on a v2 SDK?

> Something changed about the debugging interface as well because now I can see some kind of file tree when I start the debugger.

Can you give a screenshot? That sounds weird! Are you on VS Code Stable or Insiders?

Could you use the `Dart: Capture Logs` command from the VS Code palette to get a log of this happening? (You can attach here or email to me at logs@dartcode org).

**Comment by DanTup** [comment]
Also - if you open dev tools (Help -> Toggle Dev Tools) does the `Unable to open 'libintegers_patch.dart'` file have a stack trace?

**Comment by DanTup** [comment]
> Something changed about the debugging interface as well because now I can see some kind of file tree when I start the debugger

Just a thought - is this the test tree you're seeing? https://dartcode.org/releases/v2-16/#dart-test-runner

**Comment by bergwerf** [comment]
Yes, indeed that is the tree I am seeing. I am debugging a Dart VM app (tests for plain Dart code written using the test package with one file test/all.dart as entry point where all tests are `group()`ed).

I am on `Dart VM version: 2.0.0-dev.69.1 (Unknown timestamp) on "linux_x64"`.
I am on VS Code stable.

I now realize what libintegers_patch.dart is. When I check 'All exceptions', it gives a stack trace that points to files that cannot be opened. The top of the stack trace points to libintegers_patch.dart:

![image](https://user-images.githubusercontent.com/4458965/43105109-04302856-8ed4-11e8-820a-54a2917ccb30.png)

When I do not check 'All exceptions' (even though before I didn't arrive at exceptions as exotic as this one), I get this:

![image](https://user-images.githubusercontent.com/4458965/43105168-3bd5cd24-8ed4-11e8-8b4a-f5875a3346c6.png)

At this the debugger has somehow terminated so I am not able to inspect the stack trace and variable scopes. I tried logging, and I don't see much interesting in there. It is too large to upload to pastebin, but at the end of the log I see something that might be interesting:

https://pastebin.com/cB6jz9wx

It looks like the observatory quits gracefully because the process exited. Since it exits with 1 I assume this process is my test/all.dart Isn't the observatory supposed to pause the process instead? Perhaps there is a change to the observatory RPC interface?

**Comment by DanTup** [comment]
Ok, seems like there may be a few things going on here:

1. The test tree - it's correct that you're seeing this if you're running tests so that's nothing to worry about :-)

2. "Unable to open file". For files like this shown in your stack trace, the source code should be downloaded from the VM. I'm not sure why it's not happening here. Can you get an Observatory log where you break on the error and try to navigate up the stack and hit this error? It might include responses where we tried to get the source code from the VM that might help. I don't think I have any integration tests covering downloading the source code so I've opened #1115 to fix that.

Even if you're debugging "just my code" the debugger will break at the location of the exception (I think it shouldn't -> https://github.com/dart-lang/sdk/issues/29156).

3. Why is it crashing?

It seems like there are two different errors in your screenshots. It's hard to say what they are without examining the stack/code. We only recently started running tests with `pub run test` so if this seems like new behaviour in the latest version, that's probably why - maybe your tests don't work correctly with `pub run test`? You should be able to run from the command line in the same way with `pub run test -j1 test/test_all.dart`.

If you're able to provide a small repro showing these issues, I can try to debug here.

**Comment by bergwerf** [comment]
Observatory log with cannot open file: https://pastebin.com/QzuA2nJa (doesn't look very helpful). My tests work fine in `pub run test -j1`. There are a lot of exceptions because I am in the middle of refactoring something. I tried in another project of mine (github.com/bergwerf/euclid, a bit older, not fully Dart 2 yet), and it looks like the debugger terminates when all tests are done even if some failed (for which you might want to inspect the stack trace). However the debugger also halts in between so I guess this is intended behaviour.

The error in the second screenshot originates from my code. So it should already be done loading test/all.dart and started executing one of the tests, but this is not reflected in the tree. Debug log for crash/termination of pubtest: https://pastebin.com/Bg6VC2e6

To me it looks like the debugger is designed to terminate when the observatory terminates which terminates when pub run test terminates. In the log it is shown that pubtest terminates because test/all.dart cannot be loaded. I must confess that I do some stuff outside of `test()` blocks to initialize a kind of test environment for my program. Thinking about that I see that this is also the error breaking the program.

So it looks like exceptions outside test() blocks terminate pubtest. That is a problem for me because I expect to be able to debug all code using the debugger, not just the test code.

**Comment by bergwerf** [comment]
To be more specific, my 'initializing a kind of test environment' only involves configuring some global values (in this case a list of operators for parsing mathematical expression strings, hence the class Operator appearing in the stack trace).

**Comment by bergwerf** [comment]
For now I would also be very happy with a way to bypass the pubtest runner (perhaps in general this is nice because I was quite happy the way that worked for me, I don't have super heavy tests).

**Comment by DanTup** [comment]
> Observatory log with cannot open file: https://pastebin.com/QzuA2nJa (doesn't look very helpful)

Hmmm, maybe it is... You log has things like this:

```
{"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/15","name":"Script"},"size":112,"id":"objects\/186","uri":"dart:core\/runtime\/libintegers_patch.dart","_kind":"kernel","_loadTime":0,"lineOffset":0,"columnOffset":0},"id":"796"}
```

But mine has things like:

```
{"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/15","name":"Script"},"size":112,"fixedId":true,"id":"libraries\/@0150898\/scripts\/dart%3Acore%2Fruntime%2Fliberrors_patch.dart\/164cb944504","uri":"dart:core\/runtime\/liberrors_patch.dart","_kind":"kernel","_loadTime":1532423849220,"library":{"type":"@Library","fixedId":true,"id":"libraries\/@0150898","name":"dart.core","uri":"dart:core"},"lineOffset":0,"columnOffset":0,"source":"\/\/ Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file\n\/\/ for details. All rights reserved. Use of this source code is governed by a\n\/\/ BSD-style license that can be found in the LICENSE file.\n\n\/\/ LOTS OF SOURCE CODE HERE
```

Note mine has the source code of the library, yours does not! :(

Can you try something simpler for me (and that breaks on the exact file I did)? Create a new folder with these two files:

**pubspec.yaml**
```yaml
name: simple_test
version: 0.0.1

dependencies:
  test: '>=1.0.0'
```

**test/test.dart**
```dart
import 'package:test/test.dart';

main() {
  test('test', () {
    assert(1 == 2);
  });
}
```

Open the folder in VS Code, then open `test/test.dart` and hit F5. Run on a recent v2 dev SDK (I'm using 2.0.0-dev.68.0) and see whether you get the source code for the assertion methods when you break. Here's what it looks like for me (macOS), it's downloaded the source from the VM:

<img width="1250" alt="screen shot 2018-07-24 at 10 17 33 am" src="https://user-images.githubusercontent.com/1078012/43128837-db48b802-8f2a-11e8-96c1-5f29ab3e516b.png">

If possible, use the same SDK version, but if not, tell me what you used and I'll do the same. I'm wondering if this might be Linux-specific, so maybe if I can get some integration tests we'll hit this on Travis too.

> it looks like the debugger terminates when all tests are done even if some failed (for which you might want to inspect the stack trace)

It's too late to examine the stack trace after the run is complete; but if you're breaking on unhandled exceptions and run with debugging, you can debug them there. If you're not stopping on exceptions (or not running with the debugger) I'd expect the session to terminate at the end.

> The error in the second screenshot originates from my code. So it should already be done loading test/all.dart and started executing one of the tests, but this is not reflected in the tree.

Do you mean in the test tree? I'm not sure what's wrong there - the test has failed and the tree shows a red failure icon?

> To me it looks like the debugger is designed to terminate when the observatory terminates which terminates when pub run test terminates.

This is correct, though it's really just a side-effect of them all being the same VM process. When pub finishes, the VM terminates, and with it goes Observatory and the debug session. There's a command line flag you can pass to pause-on-exit, but it's generally too late to do much debugging then.

> In the log it is shown that pubtest terminates because test/all.dart cannot be loaded

Ok, so I think this might just be a bit misleading. To load a test suite, the `main` method needs to be executed to collect all of the calls to the `test` function. If this fails, you'll get that message. For example if I change my sample from above it:

```dart
main() {
  assert(1 == 2);
  test('test', () {
    assert(1 == 2);
  });
}
```

This will report "failed to load" even though it was clearly running the file. The issue here is likely that you have code executing outside of the functions passed to `test` (or `setUp`, `tearDown`, etc.) and therefore there're running during the "load" phase.

> I must confess that I do some stuff outside of `test()` blocks to initialize a kind of test environment for my program

Ha, I should've read ahead before replying. So this is exactly it - you should try to avoid this, since the code may run when it's not expected (for ex. if the tests are skipped, this still runs). I don't think it causes any real issues though (other than the slightly confusing error about loading).

> So it looks like exceptions outside test() blocks terminate pubtest. That is a problem for me because I expect to be able to debug all code using the debugger, not just the test code.

My guess is that this is because the test package is catching exceptions here. I think the only options are either enable `Break on all exceptions` (not ideal) or move your code into the test methods (where I think the `test` package must do something special to propagate the exceptions so `Break on unhandled exceptions` works). I don't think Dart Code can do anything to help here.

> For now I would also be very happy with a way to bypass the pubtest runner (perhaps in general this is nice because I was quite happy the way that worked for me, I don't have super heavy tests).

There are 4 debuggers we have (flutter, flutter test, dart vm, pub test) and while it might seem flexible to let the user override the heuristics my concern is that if it's allowed, people will find where the heuristic is bad and just override it and never tell me. I care very much about making it as good as possible so that you can always "just press F5" and it just works, so anywhere it's doing the wrong/a bad thing, I'd like to investigate :-)

Is the only reason you want to do this because of it not breaking correctly? If so, I think that could (should) be fixed in the test package. If they're doing something special to make it break on unhandled exceptions in tests, I don't see why it shouldn't be possible here - I think an issue should be raised in dart-lang/test.

So, to summarise everything here:

1. We may have an issue with source code not downloading from the VM (maybe on Linux?). If you can try the above, I'll also try to progress some integration tests.

2. Exceptions outside of test code when running on `pub run test` do not break the debugger. I think this should be raised as a feature request against test - if it's handled correctly within test methods, I think it can probably be handled here too.

3. You'd like to bypass `pub` for your tests. I'm guessing this is because of (2) but if there are other reasons I'd love to know. If there are substantial reasons to do it, we can do it. But I don't want creating a `launch.json` so you can override the debugger to become the norm - I'm working hard to make `launch.json`-less debugging work well :-)

**Comment by bergwerf** [comment]
Thanks for your reply :)

I tried your test code. It works similar to your case. Even more curious, when I replace the assert with `int.parse('a');` it does load `libintegers_patch.dart`, so this is something to look into.

Indeed I would bypass to solve this issue. I don't have enough experience with the pubtest debugger to dislike it.
In order to move all logic into test blocks, I have to repeat a lot of 'initialization code', which is something I avoid at almost all cost. I do think I used catch all exceptions before, but I never had this integer exception in pub semver.

Some notes, here the stack trace contains a lot of ugly percent encoded stuff, you might want to get rid of that. I am also wondering why there are two snapshots of pubtest running.

![image](https://user-images.githubusercontent.com/4458965/43133774-1183b664-8f40-11e8-8ff1-914700d40e47.png)

Also, it seems from the way you describe it that pressing F5 should start the debugger immediately, but for me it still drops down a list of debuggers, then a launch.json where I specify an entry point, and then repress F5.

**Comment by bergwerf** [comment]
Ok, I managed to reproduce the issue with not being able to load libintegers_patch.dart. I added an SDK constraint that cannot be parsed by pub semver.
You can reproduce it using the same example as yours but using:

```
name: simple_test
version: 0.0.1

environment:
  sdk:         '>=2.0.0-dev <3.0.0'

dependencies:
  test: '>=1.0.0'
```

Likely the pub semantic versioning parser is not expecting such weird version constraints.

**Comment by bergwerf** [comment]
Actually I seem to be wrong about my reason. I don't understand where the pub exception comes from. It randomly pops up.

**Comment by DanTup** [comment]
> In order to move all logic into test blocks, I have to repeat a lot of 'initialization code', which is something I avoid at almost all cost. 

I think it's a reasonable request that unhandled exceptions outside of test methods should break the debugger like they do inside the test methods, so you should raise this at https://github.com/dart-lang/test :-)

>  I do think I used catch all exceptions before

Yeah, probably this was because before v2.16 we'd run on the VM which did not run using the `pkg:test` runner. The runner will be catching those exceptions (hence them not breaking unless you catch all exceptions). However, since they've made this work inside the test methods (I presume with some debugger API or something) I think it can/should work here too.

> Some notes, here the stack trace contains a lot of ugly percent encoded stuff, you might want to get rid of that

That does look weird - though if might be accurate. Can you capture an Observatory log with that in it?

> Also, it seems from the way you describe it that pressing F5 should start the debugger immediately, but for me it still drops down a list of debuggers, then a launch.json where I specify an entry point, and then repress F5.

If you don't have a Dart file open, then VS Code will show you all possible debuggers that are loaded because it doesn't know which to use. I personally think it's bad that NodeJS shows up here, but I raised it at https://github.com/Microsoft/vscode-node-debug/issues/170 and it was declined :( If they fixed that, it'd correctly pick our debugger by default.

If you want the default behaviour but without ever being asked, you could set your `launch.json` to only include the `type:dart` and `request:launch` without a `cwd`/`program` and it'll use our debugger, but still use our logic to "guess" the `cwd`/`program`.

> Ok, I managed to reproduce the issue with not being able to load libintegers_patch.dart. I added an SDK constraint that cannot be parsed by pub semver.

Great, I'll give it a go! :)

**Comment by DanTup** [comment]
Oh, I missed this one:

> I am also wondering why there are two snapshots of pubtest running

The call stacks (etc.) are grouped by isolates, so the screenshot shows three isolates. `pub` has spawned `test` in an isolate and then `test` has spawned your test in another isolate, that's three total.

**Comment by bergwerf** [comment]
The percent encoding stuff also appears in the simple_test when pausing on the assert inside the test block.

If you do manage to reproduce the libintegers_patch.dart issue, perhaps you know how to track down where in pub it is coming from.
Actually, maybe it would be possible to ignore exceptions from the pub isolate even when 'All exceptions' is checked since usually you are still not interested in exceptions from pub (especially if some part is designed to use exceptions with catch). I can open a new issue on this if you think it is a good idea.
