### ISSUE TITLE
Clicking on a test inside a group does not open the test code

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1116]
I suspect the intended behaviour is that clicking on a test inside a group in the pubtest debugging tree brings you to the test code. Clicking on the group name works but not clicking on the test.

**Comment by DanTup** [comment]
Does clicking the test take you anywhere? Can you capture a `Pub Test` log (run the `Dart: Capture Logs` command) and also confirm your version of `test` and whether this is Flutter or Dart?

There was an issue where in Flutter we'd get taken to the `testWidgets` implementation (the fix is https://github.com/dart-lang/test/pull/853) but it doesn't sound like that's what you're hitting.

**Comment by DanTup** [comment]
Is the location shown in that JSON accurate or where it's actually taking you to?

**Comment by bergwerf** [comment]
Yes.
Use plain pubspec.yaml with test as only dependency.

test.dart
```dart
import 'package:test/test.dart';

import 'test1.dart' as test1;

main() {
  group('test', test1.main);
}
```

test1.dart
```dart
import 'package:test/test.dart';

main() {
  test('test', () {
    assert(1 == 2);
  });
}
```

**Comment by DanTup** [comment]
Hmmm, I understand what's happened here but I'm not sure how to fix it.

There was an in Flutter where the tests would jump to the location of the `test()` call that live inside the flutter framework when you called `testWidget()`. As a fix, the test framework no exposes the location of the test inside the suite that you ran and we use that (https://github.com/dart-lang/test/pull/853)

So here, for your test, it walks up the stack looking for a frame that matches the file that you ran (which in this case is `all.dart`).

@jakemac53 any ideas? I think probably what we want is "the highest stack frame that is in the users project" rather than "that matches the suite that was run". I guess `test` knows where the project root is, so maybe it's possible?

**Comment by DanTup** [comment]
@bergwerf It's not perfect, but as a workaround, you can use the `Run All Tests` command to run all tests instead of running a file that includes them all (you won't get your named group wrapped around it, but the tree will show each file separately rather than showing everything underneath `all.dart`).

**Comment by bergwerf** [comment]
It is not really a problem for me currently, but I reported it because I think it would be neat if it is fixed in the future.

**Comment by DanTup** [comment]
@jakemac53 Ping! If you're happy with the [change proposed here](https://github.com/Dart-Code/Dart-Code/issues/1116#issuecomment-407811137) I'm happy to send a PR.

**Comment by jakemac53** [comment]
> @jakemac53 any ideas? I think probably what we want is "the highest stack frame that is in the users project" rather than "that matches the suite that was run". I guess `test` knows where the project root is, so maybe it's possible?

I actually don't think this is what you want most of the time, I think the current behavior is the best strategy. It is pretty common to have testing utilities inside of a package, that really just wrap up a call to `test` with some other logic. We don't want to link to those utilities, we want to link to the line in the original test file that called into that utility (generally).

I don't know that we can ever get anything perfect here but I think what we currently have is probably the best thing.

@bergwerf Now that Dart has an actual test runner I would recommend using that instead of the previous pattern of creating the test_all.dart file which calls the `main` from all your tests.

**Comment by DanTup** [comment]
> Now that Dart has an actual test runner I would recommend using that instead of the previous pattern of creating the test_all.dart file which calls the main from all your tests.

This sounds sensible. @bergwerf let me know if there's a reason this doesn't work for you and we can maybe try to improve it. Otherwise, I think there's probably nothing to do here.

**Comment by DanTup** [comment]
How are you doing this today? From what I can tell, you need to start paused and then run the coverage tool and give it the Observatory URL, but I don't know how you're doing that.

If it's as simple as it appears (famous last words) maybe we can add the ability to run with coverage in VS Code and have it do the pausing and running the coverage tool automatically.

**Comment by bergwerf** [comment]
This is what I use:
```bash
#!/bin/bash

# Copyright (c) 2018, Herman Bergwerf. All rights reserved.

# Fast fail the script on failures.
set -e

# Show some versions.
dart --version
pub --version
dartfmt --version

# Get all dependencies.
pub get

# Check formatting.
dartfmt --dry-run --set-exit-if-changed ./

# Variables
OBSERVATORY_PORT=8000
COVERAGE_OUTPUT=coverage.json
LCOV_OUTPUT=coverage.lcov

# Get coverage package
pub global activate coverage

# Start coverage collector and then run tests.
pub global run coverage:collect_coverage \
--uri=http://127.0.0.1:$OBSERVATORY_PORT/ \
--out $COVERAGE_OUTPUT \
--wait-paused \
--resume-isolates &
dart --enable-asserts --observe=$OBSERVATORY_PORT test/all.dart

# Format coverage as LCOV
pub global run coverage:format_coverage \
--packages=./.packages \
--report-on lib \
--in $COVERAGE_OUTPUT \
--out $LCOV_OUTPUT \
--lcov

# Generate coverage report
curl -L https://rawgit.com/linux-test-project/lcov/master/bin/genhtml > genhtml
chmod +x genhtml
./genhtml --css-file tool/coverage.css -o coverage $LCOV_OUTPUT

rm $COVERAGE_OUTPUT genhtml
mv $LCOV_OUTPUT coverage/coverage.lcov
```

I run this on GitLab CI so the test/all.dart is essential. An 'instant' coverage feature in VS Code could still be interesting. I don't look at the coverage that often though.

**Comment by DanTup** [comment]
I'm a little confused - I thought you were running this locally (the issue is about clicking nodes in the test explorer). Can't you use the test explorer (without the test_all.dart file) for running in VS Code, but still use your script for GitLab?

**Comment by DanTup** [comment]
The supported way is to use the `Dart: Run All Tests` command from the palette, or put a test file in `program` (or `${file}` to substitute the current open file).

If you want to run all tests from a launch config, you can try this (it's unsupported and VS Code will tell you `runner` doesn't exist, but it's essentially what the `Run All Tests` command is doing internally):

```
{
	"name": "Run all Tests",
	"runner": "tests",
	"request": "launch",
	"type": "dart",
}
```

If you think we need a supported way to do this, open an issue and I'll figure something out (even if ti's just making `runner` official and documenting it).

**Comment by DanTup** [comment]
> Of course the bug with clicking inside groups remains

Can you confirm how you're running the tests now? If the issue occurs for anything other than running `all.dart` then I'd definitely like to fix that.

**Comment by bergwerf** [comment]
I think it is a good idea because that is how debugging is supposed to 
work in the VS code UI. Also I like using F5 to start debugging (which 
triggers the selected configuration).

**Comment by DanTup** [comment]
I've opened https://github.com/Dart-Code/Dart-Code/issues/1296 and will aim to take a look for vNext. Thanks!
