### ISSUE TITLE
Make Dart snippets work with editor.tabCompletion

### ISSUE THREAD

**Issue by nealot** [Dart-Code/Dart-Code#1119]
Steps to reproduce issue:
1. Enable tab completion via settings
2. Visit dart file
3. Type 'for' or 'if' and press tab before suggestion widget appears

What should happen after step 3 is the snippet being expanded but what actually happens is a literal tab is inserted.

**Comment by DanTup** [comment]
> Type 'for' or 'if' and press tab before suggestion widget appears
> What should happen after step 3 is the snippet being expanded but what actually happens is a literal tab is inserted.

This isn't something I can control, it would have to be handled by VS Code. Though I'm not sure if this is supposed to work - I just tested in TypeScript (typed `f` and hit `<TAB>` quickly) and got the same results - if I do it before the completion list appears, I get a tab, but otherwise I get the item.

What makes you think this should work - is there any info in the VS Code docs I can look at?

**Comment by nealot** [comment]
Well I believe this is the intended behavior of ```"editor.tabCompletion": true```. I usually work with Golang code and it works fine there so I thought it was a dart issue.

**Comment by DanTup** [comment]
Oh sorry, I misunderstood - I understand now. You don't need to rush to do this before the completion list appears, you can just hit `<ESC>` to close it. Indeed, I can repro this:

- Turn tabCompletion on
- type `for` in TypeScript and press `<ESC>` to close completion
- Hit `<TAB>`
- Snippet expands

Same thing does not work in Dart. My guess it's because our snippets come from a completion provider and not a static list (so that they can be dynamic). @jrieken do you know if `tabComplete` is expected to work for snippets that come from a completion provider? We use a completion provider because static snippets do not support contexts (https://github.com/Microsoft/vscode/issues/26943

**Comment by nealot** [comment]
Ah, alright gotcha. Maybe there should be a feature request to enable tabComplete for completion provider snippets?

**Comment by DanTup** [comment]
Yeah, that probably covers it, though I don't know if it's expected to work for this case already. I'd be interested in @jrieken's opinion.

**Comment by jrieken** [comment]
> @jrieken do you know if tabComplete is expected to work for snippets that come from a completion provider? We use a completion provider because static snippets do not support contexts (Microsoft/vscode#26943

No, tab completion only works for static snippets. The reason for that is that our keybindings need to active/deactivate synchronously, e.g while typing we look at the current prefix, compare it with the (static) list of snippets, and then decide to active/deactivate the tab completion keybinding (our famous context keys).

**Comment by DanTup** [comment]
@jrieken Understood. Would you consider revisiting supporting a `when` context for static snippets then? There seem to be a few drawbacks to having them in the completion provider, but making them project-type-aware is important for me; I don't want to pollute the list with Flutter snippets for users that aren't using Flutter.

**Comment by jrieken** [comment]
Not sure about context keys. My plan is more towards #28215 which would maybe generalise the tab-completion.

**Comment by DanTup** [comment]
Ok, I'm going to move Dart snipets back to a static file since they don't need to be dynamic. The flutter ones will remain dynamic which means they'll still have this issue, but that seems like less of an issue since there are only three.

**Comment by DanTup** [comment]
Please try the fix out in v2.18.0 Beta 1:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.18.0-beta.1

**Comment by nealot** [comment]
Thanks! Tab completion is working as expected now.

**Comment by DanTup** [comment]
Great, thanks for confirming!

**Comment by DanTup** [comment]
FWIW, in the next release, I'm going to move Dart snippets back to a provider. You can still get `tabCompletion` to work for it, but you'll need to set it's value to `on` instead of `onlySnippets`.

This is required to be able to filter the snippets from not popping up in completion when you're typing comments.
