### ISSUE TITLE
Add a settings entry that enables dartfmt style fixes

### ISSUE THREAD

**Issue by pschiffmann** [Dart-Code/Dart-Code#1141]
[style fixes](https://github.com/dart-lang/dart_style#style-fixes) were added to dart_style in [version 1.1.0](https://github.com/dart-lang/dart_style/blob/master/CHANGELOG.md#110). It would be great if I could opt-in to these in VS Code.

**Comment by DanTup** [comment]
This will need some support from the Dart analysis server in the SDK before we can add it here.

@bwilkerson do you know if this is planned?

**Comment by DanTup** [comment]
Fixing all instances of a problem would definitely be a neat help (https://github.com/dart-lang/sdk/issues/32474).

I was thinking maybe we could implement auto-fixing editor-side but I don't think we could currently get all the required fixes in a fast way (I guess it's similar to https://github.com/dart-lang/sdk/issues/32462).

**Comment by DanTup** [comment]
When using the LSP preview with a recent enough SDK (note: this doesn't currently include stable channels, though it will make its way there in the next stable releases) you can now apply many fixes to the whole file:

![Apply-all fixes](https://dartcode.org/images/release_notes/v3.17/apply_all.gif)

https://dartcode.org/releases/v3-17/#lsp-apply-all-fixes

This isn't exactly what was asked for here, though perhaps it satisfies the original requirement. @pschiffmann let me know if you think otherwise. Thanks!
