### ISSUE TITLE
Tries to run tests if I'm in ./lib/test/test.dart

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1165]
This may be expected  behavior but I felt I should report it anyway.

If I am in `./lib/test/test.dart` and I try to run via VSC debugger it tries to run tests that don't exist. `test.dart` is a file that contains a `TestPage()` widget that I am using for a scratch pad.

I have changed the name to `./lib/store/store.dart` and it works fine now.

It's worth mentioning that `./lib/test/store.dart` also failed, it appears to be based on the parent folder name

**Comment by DanTup** [comment]
Currently we assume something is a test if it's inside a `/test/` folder (at any level). I did want to check only the top-level test folder, but it's common for people to open parents of a Flutter app (which has all sorts of other issues, but I'm trying not to make more!).

I think I'll change it to:

- Is in the root test folder
- Or ends with `_test.dart`

I think this will still cover most cases and should solve the issue here.

**Comment by DanTup** [comment]
Please try the fix out in v2.18.0 Beta 1:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.18.0-beta.1
