### ISSUE TITLE
Sometimes >Debug Painter doesn't show up in command palette

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1200]
I have no way to reproduce this but I would say about 10% of the time the `>Flutter: Toggle Debug Painting` command (along with other flutter commands) don't show up in the command palette even if I am connected to my iOS device.

Sorry, I wish I had more information. It seems to be totally random.

The problem seems to temporarily resolve itself if I stop debugging and restart debugging.

**Comment by DanTup** [comment]
Could you try enabling the [Observatory](https://dartcode.org/docs/logging/#observatory) and [Flutter Run](https://dartcode.org/docs/logging/#flutter-run) logs and next time you see it missing, grab a copy of those logs? (they're overwritten on each run, so you'll need to copy them before the next run).

A Hot Restart (`Ctrl`+`F5`) *might* bring them back rather than having to restart the whole session (Hot Restart is very fast with no rebuild), but it'd be good to track down what's going wrong and hopefully the logs will help with that.

It's also worth clicking Help -> Toggle Dev Tools and checking for any errors in the Console when it happens too.

**Comment by lukepighetti** [comment]
I will post again next time it happens. Just as a note, Hot Restart did not solve the problem. Only restarting the debug session did.

**Comment by DanTup** [comment]
Interesting... We enable those commands as the service extensions are loaded - doing a Hot Restart should result in them loading again (which means we'd get the events, and try again). Though I guess it's also possible whatever caused it not to load the first time still applies during the restart.

Any any case, a log and the dev console will hopefully reveal once going on.

**Comment by DanTup** [comment]
@lukepighetti It's been a while since you said you'd post back if it happened again. I'm assuming it hasn't, but if you are still seeing it please let me know and we can do some more digging (a log would definitely help!).

**Comment by lukepighetti** [comment]
Been away from Flutter for a while but if I run into it again I will post. Cheers!
