### ISSUE TITLE
Breakpoints on ternary operators pausing on wrong line

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1215]
To reproduce, create a minimal project with this file:
```dart
import 'package:test/test.dart';

main() {
  test('test', () {
    final b = true;
    final a = b ? true : false;
    print(a);
  });
}
```
Set a breakpoint on the line with `final a = b ? true : false;` and run via the debugger. If the value of b is changed to false, then the debugger does pause, but on the next line...

It seems something is broken ;).

**Comment by DanTup** [comment]
Looks like this may be a VM issue. Given this code:

```dart
void main() {
  final b = false;
  final a = b ? true : false;
  print(a);
}
```

If I load up in Observatory while the script is paused at start, I can add a breakpoint to every line except the last:

<img width="375" alt="screen shot 2018-09-21 at 13 56 27" src="https://user-images.githubusercontent.com/1078012/45882529-569ab380-bda6-11e8-926b-0fee63c538fd.png">

So I did:

<img width="349" alt="screen shot 2018-09-21 at 13 56 39" src="https://user-images.githubusercontent.com/1078012/45882538-5bf7fe00-bda6-11e8-8558-48a990fc8f58.png">

Then I went to the debugger and unpaused, but the breakpoints got resolved on lines 1, 2, 4, 4:

<img width="744" alt="screen shot 2018-09-21 at 13 56 51" src="https://user-images.githubusercontent.com/1078012/45882555-67e3c000-bda6-11e8-8759-6a1c1c6249d4.png">

I thought it might be an optimisation because the values are known at compile time, but changing `b` to something dynamic (eg. `new DateTime.now().day == 21`) seems to have the same behaviour.

I tested with these two versions:

Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
Dart VM version: 2.1.0-dev.0.0.flutter-be6309690f (Fri Aug 10 06:04:10 2018 +0000) on "macos_x64"

That said, I can't repro the behaviour of it not breaking at all, it seems to be on the wrong line in both cases. I've opened https://github.com/dart-lang/sdk/issues/34541 about the wrong-line issue.

**Comment by bergwerf** [comment]
Ok, thanks.
If the wrong-line issue is resolved I'll have another look at the non-breaking behavior. I use `Dart VM version: 2.1.0-dev.4.0 (Unknown timestamp) on "linux_x64"`

**Comment by DanTup** [comment]
I tried with your exact code with a `test` too, but still only get the wrong-line issue regardless of the value of `b`. Can you get an Observatory log for me to review? (include the exact code being run if it's not identical to your original code here).

**Comment by bergwerf** [comment]
I just upgraded to `2.1.0-dev.5.0`, and at least now it does break on that breakpoint regardless of the value of b (but still on the wrong line). So lets change the focus of this issue to the wrong line breaking. Perhaps this issue should remain open until the Dart VM is patched.

**Comment by DanTup** [comment]
Ok cool, flag the behaviour is consistent now. I'll mark this an upstream issue but leave it open as a reminder to chase if it doesn't get looked at.

**Comment by DanTup** [comment]
This was fixed in Dart :-)

https://github.com/dart-lang/sdk/issues/34541
