### ISSUE TITLE
Selector device frequently changes when a device has WiFi debugging enabled

### ISSUE THREAD

**Issue by maxlapides** [Dart-Code/Dart-Code#1218]
As I'm working on a Flutter project, the device selector in the bottom-right corner frequently changes. Typically, I want to work with one device for an extended period of time. I'm often working with a connected device, then I stop debugging for some time, and then I start up the debugger again but the selected device has change without my input, and now it's trying to install on some other device that may or may not even be connected.

My suggestion is that we keep the selected device selected until the user changes it again, or that device becomes disconnected.

**Comment by DanTup** [comment]
You can set `"dart.flutterSelectDeviceWhenConnected": false` in your settings to stop it changing to the most-recently-connected device all the time. I'm not sure whether this is an issue with your device connecting/disconnecting though. I'd be interested to see a [Flutter Daemon](https://dartcode.org/docs/logging/#flutter-daemon) log for a period of time when this is happening if you wouldn't mind capturing one.

**Comment by DanTup** [comment]
> am I supposed to be able to debug with Flutter wirelessly? If not, I don't think these devices should be listed at all.

Honestly, I'm not sure. I've seen people mentioning having issues with it in the tracker, but it's not something I'm totally familiar with. I agree that if it doesn't work over WiFi they probably shouldn't be listed, but I don't know if that's totally the case (this is handled in Flutter, not Dart Code, so I don't know all the details).

> My second question is: why is `flutterSelectDeviceWhenConnected` not disabled by default? It seems like the kind of thing that is more annoying than useful in the majority of cases.

I've only ever seen two complaints about it - one was from the user that contributed that setting (because they had this issue) and you're the other. If it's affecting a lot of people I'd definitely consider changing it but if not (and if it only affects some devices, I suspect it's not) I think the default behaviour makes most sense (if someone connects a new device or boots a new emulator, they probably want to use it).

It's impossible to get the best default for everyone which is why we end up with settings like this - we'll try to default to the thing that works the best for the most people, but we can re-visit if it looks like we picked badly or things have changed.

**Comment by DanTup** [comment]
If it turns out to be flaky for a lot of people and it can't easily be fixed in Flutter, I'm definitely open to changing it. Right now I've only had two reports though (I don't know what percentage of people use iPhones or what portion of iPhones support WiFi debugging), but I'll leave this open for people to put 👍's or comment on, and if you raise an issue in Flutter please post the link back here and/or CC me on it so I can keep an eye on the discussion. Thanks!

**Comment by maxlapides** [comment]
It looks like this is a relevant issue: https://github.com/flutter/flutter/issues/15072

Seems like the summary here is that Flutter doesn't yet support debugging over the network even for devices that have enabled network debugging.

**Comment by DanTup** [comment]
I'm unable to investigate this without more details as mentioned above so I'm going to close it. I'm happy to reopen it if you can provide some additional info though!
