### ISSUE TITLE
Icon suggestion display html code

### ISSUE THREAD

**Issue by shashikantdurge** [Dart-Code/Dart-Code#1222]
Issue Type: <b>Bug</b>

When I try to lookup the Icons in suggestions. it shows html code. you know what I want to see. please look into it.

I am developing Flutter app using Dart language.

Thank you

Extension version: 2.18.0
![screenshot 34](https://user-images.githubusercontent.com/20161204/45989945-61ea2980-c09b-11e8-9300-8cd0c164b62b.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.87GB (8.29GB free)|
|Process Argv|C:\Users\vasan\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DanTup** [comment]
Thanks for the report! There was a change in Flutter recently that changed this HTML and we currently have to parse it out with a regex in Dart Code. It was raised and fixed in #1204 for v2.19.0.

You can install the beta [from here](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.19.0-beta.1) or wait for the release (which will probably be at the end of next week).
