### ISSUE TITLE
2.19.2 (beta) doesn't work

### ISSUE THREAD

**Issue by Rodsevich** [Dart-Code/Dart-Code#1228]
![image](https://user-images.githubusercontent.com/1907844/46285889-7b83e900-c553-11e8-941b-5b1cd26f6217.png)
There's the console log

**Comment by DanTup** [comment]
Aha, I think I know what's happening here. If you open a Flutter project and don't have a valid Dart SDK on your `PATH`, I think this happens... Fix is simple, but want to try and ensure this is covered by tests since it's probably quite common (but not something I'll hit, since I have a standard/web Dart SDK on PATH).
