### ISSUE TITLE
Intellisense confirmation with "." not working in dart

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#1253]
https://github.com/Microsoft/vscode/issues/60985

**Comment by DanTup** [comment]
This feature can be enabled with the `dart. enableCompletionCommitCharacters` setting. It's not enabled by default yet because it still has some issues that need resolving (#1121 is tracking enabling it by default).

You're welcome to try it out, but you may find that it triggers far more often than you'd like right now.
