### ISSUE TITLE
Highlighting blocking intellisense when creating a class

### ISSUE THREAD

**Issue by miyoyo** [Dart-Code/Dart-Code#1255]
As seen in [this reddit post](https://www.reddit.com/r/FlutterDev/comments/9oh0e1/is_anyone_else_having_this_issue_in_vs_code_when/), some kind of highlighting blocks the usage of intellisense until you click somewhere else or press escape.

One solution would be to have the highlighting disappear when pressing the return key, thus allowing intellisense to work once more.

**Comment by DanTup** [comment]
Thanks for the report! This is a weird issue I don't yet have a good fix for. The issue for it is https://github.com/Dart-Code/Dart-Code/issues/1173 (please subscribe there and I'll close this as a dupe).

I think the cause is a VS Code bug not treating "tab stops" differently to "placeholders", but I'm hoping to find a workaround for the next version if there's no response from Code.
