### ISSUE TITLE
Is there an error message for modifying the const list and the const map?

### ISSUE THREAD

**Issue by lizebang** [Dart-Code/Dart-Code#1275]

**Comment by DanTup** [comment]
I'm not sure I understand the question. The code you provided will throw a runtime error. Are you asking for a compile-time error/lint to detect this?

**Comment by lizebang** [comment]
@DanTup You are right, But I am not sure if this is easy to implement.

**Comment by DanTup** [comment]
@lizebang I don't think it'd be possible (at least, in complicated cases) since being `const` isn't part of the type. Imagine this code:

```dart
changeItem(List<int> ints) {
  ints[0] = 1;
}

var list = [0, 1, 2, 3];
const constList = [0, 1, 2, 3];
changeItem(list);
changeItem(constList);
```

The last line here will result in a runtime error, but it's hard to analyze this. You could also add `list = constList;` which makes the variable that was previously mutable not.

If there was any change in this area, it would have to come from the SDK rather than the VS Code plugin (since all analysis in Dart Code is done by an analysis server from the SDK), but based on the discussion at https://github.com/dart-lang/sdk/issues/236 it seems unlikely. I think the closest you can get to what you want is probably:

- https://api.dartlang.org/stable/2.0.0/dart-collection/UnmodifiableListView-class.html
- https://github.com/google/built_collection.dart

Hope this might help!

**Comment by lizebang** [comment]
@DanTup You're right. Thank you.
