### ISSUE TITLE
Cannot use editor.fontLigatures in vscode if Bracket Pair Colorizer 2 is also installed

### ISSUE THREAD

**Issue by efreibe** [Dart-Code/Dart-Code#1290]
I have the parameter editor.fontLigatures enabled, it is working well in other languages I've tested so far, but not in Dart.

Here is a screen shot of fontLigatures when working in Javascript:
![image](https://user-images.githubusercontent.com/1061126/48152468-c3a8d080-e2a2-11e8-9dbd-cbed54af0e5e.png)

And here is how I see it when working in Dart:
![image](https://user-images.githubusercontent.com/1061126/48152525-e804ad00-e2a2-11e8-8f3e-42d19fb34b25.png)

If I disable this plugin in vscode it works as expected.

**Comment by DanTup** [comment]
Weird, we apparently fixed this before in #809!

**Comment by efreibe** [comment]
Digging a little bit more, I enabled and disabled several extensions.
I've found that for any reason the plugin does not work well in conjunction 
with "Bracket Pair Colorizer 2".

Extrange because that plugin works seamlessly when coding in 
javascript, as shown before.

If I enable only Dart Code it works well, enabling these two won't work anymore.
![image](https://user-images.githubusercontent.com/1061126/48154065-7b8bad00-e2a6-11e8-9010-f5c44cf50da7.png)

Enabling only Bracket Pair Colorizer 2 works as expected but obviously I have no syntax coloring.

**Comment by DanTup** [comment]
Thanks for the info - I'll see what I can find.

(cc @CoenraadS in case you can think off any reasons offhand that the two extensions might not play nice together)

**Comment by CoenraadS** [comment]
If a ligature gets a partial decoration applied to it, it breaks. In this case VSCode is seems `=>` and thinks `>` is a bracket. Then my extension colors it red because it can't find an opening `<`. I need to implement a way to ignore types of brackets because VSCode bracket matching is regex based and has many false positives.

**Comment by CoenraadS** [comment]
@efreibe 

It basically means you can't use features like 'jump to bracket' on code such as `List<String> arguments`

**Comment by efreibe** [comment]
I can live with that. 
As not everybody uses the bracket colorizer plugin, one idea could be to create a setting to keep or remove those signs from the configuration and keep any other difficult hacks in the backlog.
Just a thought...

**Comment by DanTup** [comment]
I can't see any real benefit of having `<>` in the brackets list so I've removed it (I don't know if I can easily make the config conditional based on a setting). I may revisit that decision if it turns out to have removed any useful functionality, but it seems unlikely.

@efreibe you can build a local version of the extension with `vsce package` (you'll need to install the `vsce` npm package from MS) if you want to get the fix sooner without having to run from source.

**Comment by efreibe** [comment]
I've edited the json file inside the extension folder and it is working
well.
Luckily I haven't had the need to build the entire extension.

**Comment by DanTup** [comment]
Ah cool, I guess that works since you don't need to recompile the ts for a json change :-)

The next release will overwrite the json file, but includes the fix, so it should just continue working. If it does seem to break, give me a shout.

**Comment by efreibe** [comment]
Thank you very much.
