### ISSUE TITLE
Add a command to write recommended settings to the users User Settings for Dart

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#1302]
Start with the following code:

```dart
class CircularButton extends StatelessWidget {
  final Widget text;
  final VoidCallback onPressed;

  const CircularButton({this.text, this.onPressed});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: RaisedButton(
        shape: CircleBorder(side: BorderSide(color: Colors.blue, width: 2)),
        child: text,
        onPressed: onPressed,
      ),
    );
  }
}
```

Next, place the cursor on `RaisedButton` 
Invoke refactoring (`option-enter`).  
Select 'Wrap with new widget'

=>

The code is oddly formatted; I would expect `child: RaisedButton(` to be indented two positions in from `child: widget(`, but it's 8 positions in.

Second, when I attempt to type a widget name, say `SizedBox`, in the `widget` placeholder text I get no code completion.

**Comment by DanTup** [comment]
> The code is oddly formatted

This appears to be the same issue as https://github.com/Microsoft/vscode/issues/44200. Frustratingly, it seems like this is finally getting a fix (https://github.com/Microsoft/vscode/issues/57093) but only for completions - yet the issue seems to affect general text edits. I'll open an issue in VS Code about this.

> Second, when I attempt to type a widget name, say SizedBox, in the widget placeholder text I get no code completion.

If you press Ctrl+Space does the completion work correctly (it seems to for me)? The snippet mode (where you can tab between placeholders, etc.) is controlled by VS Code and I'm not sure if we can force completion open automatically (but I'll do a little more digging).

**Comment by mit-mit** [comment]
> If you press Ctrl+Space does the completion work correctly (it seems to for me)?

Yes, when I press that I see a 'loading' message for few seconds, and then the completions.

The weird thing is, if I after doing the refactor move the cursor out of `widget`, back into `widget`, delete `widget` and then start typing, then I get the expected immediate completion behavoir...

**Comment by DanTup** [comment]
I've opened https://github.com/Microsoft/vscode/issues/63129 about the indenting - seems to be an issue with `SnippetStrings` rather than general edits.

> The weird thing is, if I after doing the refactor move the cursor out of widget, back into widget, delete widget and then start typing, then I get the expected immediate completion behavoir...

Yeah, that's because it exits snippet mode (when it's in snippet mode, you'll see a box around the word `widget`.

I managed to find this:

https://github.com/Microsoft/vscode/issues/57153

It seems that you can disable this with a VS Code setting:

```js
"editor.suggest.snippetsPreventQuickSuggestions": false
```

In my quick testing, this seems to solve the issue. Give it a test and see what you think. If we think it works well, we could add it to the [Recommended Settings](https://dartcode.org/docs/recommended-settings/) page (which I'm thinking of - at some point -  showing a one-time notification to point people at).

**Comment by mit-mit** [comment]
Yeah, that works a lot better!

Is it not possible to set settings like this programmatically for .dart files?

**Comment by DanTup** [comment]
> Is it not possible to set settings like this programmatically for .dart files?

It is, though I'm not too keen on the idea of changing VS Code defaults just for Dart, since it means people using VS Code for other languages will have inconsistencies they might not understand (it also feels a bit aggressive for us to change their settings, even if it is just for Dart). That's why I started the recommended settings page - to try and draw attention to what I generally consider bad VS Code defaults, and allow users to read the descriptions and pick which ones they want.

I don't feel strongly though, my opinion would be swayed, but I'd want to be fairly sure users wouldn't object. We'd also need to figure out when to set them (since ideally we'd write them into their settings file so they can see what we've done, but we don't want to put them back in if the user deleted them).

**Comment by DanTup** [comment]
This came up again in the context of completion improvements - when we're sorting the most relevant to the top of the list and VS Code jumps halfway down the list to "the last thing you typed" it just looks buggy.

My main concern with changing these in configurationDefaults (where we set indenting, for ex.) is that if the user tries to set their own value in the VS Code settings editor, they appear to just "not work" (because language-specific defaults from an extension are higher priority than user-specified non-language-specific settings).

As a possible workaround, we could prompt the user the first time, asking if they want to use our recommended settings - and if so, write them explicitly into their settings (instead of using defaults). That way it's opt-in, the user has visibility of what we set, and if they decide to change them they're all visible in their settings without having to worry about the "hidden Dart defaults" they'd need to override).

**Comment by DanTup** [comment]
Re-purposing this to add a command so that we can get feedback on the settings before encouraging all users. The command is **Dart: Use Recommended Settings**.

I've opened #1946 to add a show-once prompt that will run the command for you in the next version. I'll try to encourage people to use it and provide feedback in the release notes.

The settings it will write are the ones from https://dartcode.org/docs/recommended-settings/ inside the `"[dart]"` section.

**Comment by DanTup** [comment]
Hmmm, apparently the issue I opened is now a 404 🤷‍♂️ I've re-opened it and it got the same issue number 🤔
