### ISSUE TITLE
Extension fails to activate if a code-workspace file is open containing paths that don't exist

### ISSUE THREAD

**Issue by jimmyff** [Dart-Code/Dart-Code#1303]
I seem to have lost support for Dart v1 in vs code? My Dart2 projects are still working as expected however Dart1 projects don't get the SDK version in the toolbar. I'm not getting the analyzer in the editor and I can now longer cmd+click to follow through to the definition. 

Did you drop support for Dart1 projects?

**Comment by DanTup** [comment]
Not deliberately. The integration tests did stop running on Dart v2 when v2 went stable (because they run on stable + dev channels), but I haven't knowingly done anything to stop it (and I still aim to fix bugs where I can).

Can you enable the [Extension Log](https://dartcode.org/docs/logging/#extension) and [Analyzer Log](https://dartcode.org/docs/logging/#analyzer) and restart VS Code, open your project and attach (or email) the logs? (be sure to remove anything sensitive if posting them here - the analyzer log may contain bits of your source code).

**Comment by DanTup** [comment]
Oh also, when you say "a Dart v1 project", what do you mean? Are you using a v1 SDK for them?

**Comment by jimmyff** [comment]
Hmm wonder why it's not working for me then. 

The extensionLogFile log file contains only this:
```
Wed Nov 14 2018 [15:38:57 GMT+0000 (GMT)] Log file started
[15:38:57 GMT+0000 (GMT)] [General] [Info] Searching for SDKs...
[15:38:57 GMT+0000 (GMT)] [General] [Info] Environment PATH:
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /Users/jimmyff/exec -l /bin/bash/google-cloud-sdk/bin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     //chromium_depot_tools
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /Users/jimmyff/flutter-sdk/bin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /usr/local/sbin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /usr/local/bin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /usr/bin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /bin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /usr/sbin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /sbin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /Applications/VMware Fusion.app/Contents/Public/
[15:38:57 GMT+0000 (GMT)] [General] [Info]     /usr/local/git/bin
[15:38:57 GMT+0000 (GMT)] [General] [Info]     ~/.pub-cache/bin

```

This is what I see at the bottom of my IDE, clicking Dart opens up a menu where I can 'Select Language Mode' choosing Dart doesn't seem to do anything :
![screen shot 2018-11-14 at 15 36 45](https://user-images.githubusercontent.com/298850/48493124-3118ac00-e823-11e8-8791-453e70509ff0.png)

I do see the Dart SDK selector in my Dart2 projects:
![screen shot 2018-11-14 at 15 44 42](https://user-images.githubusercontent.com/298850/48493693-40e4c000-e824-11e8-94de-42ba92de7955.png)


VS Code doesn't create a log file for `analyzerInstrumentationLogFile` when opening only the dart1 project. As soon as I open Dart2 project it creates it and puts stuff in there. If you think the log would be useful I can send it over.

When I say Dart1 project yeah I mean SDK restricted to Dart1:
```
environment:
  sdk: '>=1.9.1 <2.0.0'
```

**Comment by DanTup** [comment]
Can you click Help -> Toggle Developer Tools to open the Chromium console and see if there are any errors listed there?

(btw it seems strange that you can an entry `/Users/jimmyff/exec -l /bin/bash/google-cloud-sdk/bin` in your PATH?)

If you want to try debugging locally, if you clone this repo, open it in VS Code, put a breakpoint in `src/sdk/utils.ts` around line 135 (where it says `log("Environment PATH:");`) you could try stepping to see what's happening.

Based on the log, it seems like it's not getting as far as finding the SDK, which is strange since nothing up until that point should vary based on the pubspec.

Also, FWIW, I don't think putting the `sdk` constraint in your pubspec alone is enough - it'll still run with whichever SDK it finds/is configured. You'll need to keep a v1 SDK and set that project to use it (see https://dartcode.org/docs/quickly-switching-between-sdk-versions/).

**Comment by jimmyff** [comment]
```
console.ts:134 [Extension Host] Activating extension 'Dart-Code.dart-code' failed: ENOENT: no such file or directory, scandir '/Users/jimmyff/Google Drive/Development/dart/stripe_js_facade'.
```
ahh - I moved my Development directory out of Google Drive (along with the workspace file). I checked the `.code-worksapce` file and it mentioned the absolute path. I've just removed this folder from my workspace and it's all working again!

I'm surprised that VSCode itself doesn't handle this to avoid extensions needing to handle it.

Thanks @DanTup!

**Comment by DanTup** [comment]
Oh, so you had a `.code-workspace` file with a bad path? This has come up before - I think VS Code specifically didn't want to filter them out so were leaving it to us - I guess I haven't done it somewhere so my code was blowing up as I enumerated the projects.

I'll fix for vNext - thanks for the report and the investigation!

**Comment by jimmyff** [comment]
> Oh, so you had a .code-workspace file with a bad path?

yes, one of the workspace folders was an absolute path which was no longer valid. Strangely all the other workspace folders were relative. 

Thanks again

**Comment by DanTup** [comment]
Perfect - I could repro locally and have fixed for vNext 👍
