### ISSUE TITLE
Future type result, break in switch statement not working

### ISSUE THREAD

**Issue by ilkintacan** [Dart-Code/Dart-Code#1308]
Issue Type: <b>Bug</b>

  var rs;
  bool init = true;
  void loop() {
    if (init) {
      init = false;
      rs = RawSocket.connect("192.168.1.2", 2222, timeout: Duration(seconds: 3));
    }
    switch (globals.state) {
      case globals.State.connectToIP:
        rs.then((s) {
            if (blabla)
              break; //PROBLEM HERE: [dart] A break statement can't be used outside of a loop or switch statement. [break_outside_of_loop]

            Somecode...
        });
        break;

      case ....

      case ...

      default:
        break;
    }
  }

Extension version: 2.20.0
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II X2 250 Processor (2 x 3013)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (4.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DanTup** [comment]
I guess you figured this out because you closed it, but your `break` can't be inside another function as you have here. The reason for this is that the code inside your function isn't called until *after* the switch statement has already completed (it is asynchronous).

You may be able to fix this by changing to async/await, but it would mean the surrounding code would need to be async and return a `Future`.

**Comment by guvanch07** [comment]
Hello

**Comment by guvanch07** [comment]
Hello
