### ISSUE TITLE
Doc: Keyboard Shortcut for Assists

### ISSUE THREAD

**Issue by sgon00** [Dart-Code/Dart-Code#1317]
In the url https://flutter.io/docs/development/tools/ide/vs-code, it has the following:

```
Assists are code changes related to a certain code identifier....
by using the keyboard shortcut Ctrl+Enter
```

I don't know if this is true in Windows/Linux. So far, it does not work in MacOS. I even tried `Cmd+Enter`. After a long time search, finally, I figured out the actual command is `Cmd+.` in MacOS, and `Ctrl+.` in other system. 

I can not confirm if `Cmd+Enter` will work in win/linux or not. but at least it does not work in MacOS. I think the doc should be updated. 

Thanks.

**Comment by DanTup** [comment]
Yep, the docs look wrong to me, it's definitely `Ctrl`/`Cmd`+`.`:

<img width="731" alt="screen shot 2018-11-21 at 12 59 22 pm" src="https://user-images.githubusercontent.com/1078012/48842911-742bcf80-ed8d-11e8-889d-60d7ebd20ce9.png">

The file is here if you'd like to send a PR to fix, otherwise I'll take a look later :-)

https://github.com/flutter/website/blob/master/src/docs/development/tools/ide/vs-code.md

**Comment by sgon00** [comment]
@DanTup Thanks a lot for the quick reply. I have no plan to send a PR, you can take care of it. Cheers. 😄

**Comment by DanTup** [comment]
I've opened https://github.com/flutter/website/pull/1761. Thanks for the report!
