### ISSUE TITLE
I can't have independent working loops

### ISSUE THREAD

**Issue by ilkintacan** [Dart-Code/Dart-Code#1319]
Issue Type: <b>Feature Request</b>

Hello,
I am trying to achieve seperate loops. While second loop waiting something to finish, first loop not triggering on time till second loop's while is finished. 
How could I have paralel working timer subroutines? Isn't "Future" to achieve this?

In below code because of loop1 shorter, it must print 5 times more but they prints sequentially one by one messages.

Best Regards.

import 'package:flutter/material.dart';
import 'dart:async';

void main() {
    new Timer.periodic(Duration(milliseconds: 100), (Timer t) => loop1());  
    new Timer.periodic(Duration(milliseconds: 500), (Timer t) => loop2());
  runApp(MyApp());
}

Future<void> loop1() async {
  print('loop1');
}

Future<void> loop2() async {
  DateTime time = DateTime.now();

  while(DateTime.now().millisecondsSinceEpoch - time.millisecondsSinceEpoch < 1000) {
    //Waiting somethnig
  }
  print('loop2');
}

Extension version: 2.20.0
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by DanTup** [comment]
The question would be better suited for StackOverflow or the Dart/Flutter lists - this issue tracker is for issues with the Dart/Flutter VS Code plugins.

That said, your issue is likely to be this:

```dart
while(DateTime.now().millisecondsSinceEpoch - time.millisecondsSinceEpoch < 1000) {
//Waiting somethnig
}
```

This code sits in a loop for 1 second consuming the CPU. Since the code is all single-threaded, there's no way for the other code to run while the thread is busy running this loop. (not only that, this is a waste of CPU resources).

If you changed the code to wait in a way that does not tie up the thread, it should give the results you expect:

```dart
// Wait for 1 second
await new Future.delayed(const Duration(seconds: 1));
```

If you really need to run parallel code that is CPU-bound then you should look into Dart's isolates (though they come some restrictions on how you can communicate data between them).

Hope this helps!
