### ISSUE TITLE
Add debug toolbar buttons to jump to major DevTools pages

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#1323]
Flutter's Android Studio plugin allow running a Flutter app, and then selecting a widget in the running app. The tool then selects the corresponding widget in the widget inspector and the corresponding source code file and place in that file.

Flutter Code doesn't have a widget inspector, but this capability would IMHO still be super useful if it just did the source code selection part. cc @DanTup @devoncarew WDYT?

**Comment by DanTup** [comment]
If I understand correctly, we already have this one :-)

https://dartcode.org/releases/v2-20/#return-of-inspect-widget

**Comment by DanTup** [comment]
Great! :-)

VS Code does support toolbars, but they're editor-scoped (for ex. we have package update buttons when you have a pubspec open) so they wouldn't work well for something like this (for ex. they'd vanish if you didn't have a file open, or be duplicated if you had split panes).

Advertising features is definitely an issue though - we do show a Release Notes button on every update to encourage people to click and read through what's new, but of course it doesn't help new users know all the stuff that came before. I do keep meaning to tidy up the website with a better feature list that would at least make it easier for people to discover all the things we support but it hasn't happened yet (and, most people probably won't look outside of the editor).

In the editor, we could potentially show some one-time notifications to point people to more info (eg. on the website(s)) for ex. the first time you run a debug session, we could show a notification with a link to a page that explains all the debugging features - but we'd have to be careful to not feel spammy.

I'll rename this issue and keep it open as somewhere to collect ideas for improving visibility of things like this.

**Comment by devoncarew** [comment]
> for ex. they'd vanish if you didn't have a file open, or be duplicated if you had split panes

This might still be acceptable, if we could scope the toolbar to just displaying for Dart files when a Flutter app was running. Would we have enough content for a toolbar? The Inspector 'select widget' button? Icons to toggle on and off some of the framework debug features (like debug draw)?

**Comment by DanTup** [comment]
> This might still be acceptable, if we could scope the toolbar to just displaying for Dart files when a Flutter app was running

I believe we can do that, my concern is more around the placement since they're "editor scoped":

<img width="777" alt="screen shot 2018-12-03 at 12 44 40 pm" src="https://user-images.githubusercontent.com/1078012/49374465-577e8880-f6f9-11e8-9888-5de615b25866.png">

The two icons on the right of tabs is where they'd appear (the one on the left is our `pub get`, the right one is built-in to split the editor).

> Would we have enough content for a toolbar? The Inspector 'select widget' button? Icons to toggle on and off some of the framework debug features (like debug draw)?

There are quite a few things we could put there, though given the placement, the more we add, the more we eat away at the set of tabs. In some ways I wonder whether they'd be better on the dbeug toolbar, but that's blocked by https://github.com/Microsoft/vscode/issues/45116.

Many people wanting something like custom toolbars (see https://github.com/Microsoft/vscode/issues/41309) seem to be using the system tray. I don't know if it's particularly discoverable but we could have something there that opens a menu of as many things as we want when clicked.

No solution seems ideal :/

**Comment by DanTup** [comment]
We have the ability to add buttons to the debug toolbar now (we added Hot Reload as its own icon). Maybe that's a more appropriate place to put some of the things discussed above?

The only caveat is that we need to set the contexts as the debug session starts due to https://github.com/microsoft/vscode/issues/69398 so we wouldn't be able to wait until we know if they're supported (eg. when the services register).

**Comment by devoncarew** [comment]
Instead of adding several different service buttons, perrhaps just add a devtools button?

**Comment by DanTup** [comment]
I'm not sure if that entirely addresses the problem (since we add features that aren't in DevTools, and when DevTools adds new features, the continued presence of a DevTools button doesn't help advertise there are new things), however I think it's a good idea (we currently show a prompt to open DevTools, but only periodically).

I'll re-title this case for that, but happy to discuss more (or open new issues) if it doesn't address @mit-mit's original concern.

**Comment by DanTup** [comment]
I've added a Dart icon to the debug toolbar to open DevTools (it has a tooltip saying what it is too). 

<img width="355" alt="Screenshot 2019-08-20 at 2 57 43 pm" src="https://user-images.githubusercontent.com/1078012/63353641-f1a36100-c35a-11e9-8c02-420dcd9d2194.png">

<img width="397" alt="Screenshot 2019-08-20 at 2 57 53 pm" src="https://user-images.githubusercontent.com/1078012/63353642-f1a36100-c35a-11e9-84d6-d525bb1b0dd1.png">

Let me know if you think it needs any tweaks!

**Comment by mit-mit** [comment]
Love the button, but wondering if using the Dart logo for this is a little off-brand.

How about something more tools like, like a wrench icon?

**Comment by DanTup** [comment]
Yeah, fair point. DevTools doesn't seem to have its own icon as far as I can tell, I'll see if anyone has any suggestions.

**Comment by mit-mit** [comment]
Lots of icons here:
https://material.io/resources/icons/?icon=build&style=baseline

I like 'build' and 'location_sear'

**Comment by DanTup** [comment]
Bumping this to next release, as after discussing today, we think it'd be better to add a couple of buttons here that hot-link to specific pages in DevTools (for ex. an Inspect button, Memory view, etc. - depending on whether it's Flutter or just Dart). To avoid spawning multiple browsers/tabs for each click though, it would be best to do after DevTools gets a server that lets us communicate with the tabs.

I'll hide the current icon for the upcoming release.

**Comment by DanTup** [comment]
Still needs final icons.
