### ISSUE TITLE
Complains about Dart version 2.1

### ISSUE THREAD

**Issue by nkoroste** [Dart-Code/Dart-Code#1336]
I keep getting the following warring: 
Version 2.1.0 of the Dart SDK is available (you have 2.1.0-edge.bf26f760b1bb3d5fea6bda110f6a17b590364120). Some features of Dart Code may not work correctly with an old SDK.

but I'm already using version 2.1:
/usr/lib/google-dartlang/bin/dart --version
Dart VM version: 2.1.0-dev.9.4+google3-v2.1.0.dev.9.4 (google3) on "linux_x64"

**Comment by DanTup** [comment]
It's a little confusing, but according to semver, 2.1.0-suffix is an older version than 2.1.0 (for example, 2.1.0-beta comes before 2.1.0). So, this notification is somewhat correct.

However, I don't think we should show the notification for Flutter projects (because it builds its own SDKs and there are often overlaps).

Can you confirm where your SDK came from and what type of project you're opening?

**Comment by YevhenKap** [comment]
Currently Flutter 1.0.0 use `2.1.0-dev.9.4` version of Dart language. I don't know why not stable release, but it is so.

**Comment by DanTup** [comment]
Flutter takes its own builds of the Dart SDK far more frequently than Dart updates the stable channel. I don't know the reasoning, but I suspect it's just to allow a faster turnaround. Wether that'll change now Flutter is v1.0, I'm not sure.

I'm closing this issue because there's not enough info to investigate. If anyone is still seeing it, please let me know and attach an [extension log](https://dartcode.org/docs/logging/#extension).
