### ISSUE TITLE
Allow the debugger Restart button to be configured for either Hot Restart or Hot Reload

### ISSUE THREAD

**Issue by alantbarlow** [Dart-Code/Dart-Code#1338]
Allow for support for changing what the refresh button does. Currently it only hot refreshes an action that I do automatically every time I make a change. i would like to change it to hot restart, an action for which I currently have to use hotkeys for. i know not everyone wants that button to do that so that's why it should be an option in settings to change what that button does.

**Comment by DanTup** [comment]
Thanks for the suggestion. I'd prefer to have both buttons on the toolbar than customise this (just because things become a little more complicated if the buttons does different things for different people - or across different projects) but that requires support from VS Code (see https://github.com/Microsoft/vscode/issues/45116).

I'll ping on that issue to see if it's likely we'll see any movement any time soon, and if not, this may make more sense.

**Comment by DanTup** [comment]
I had a response on the VS Code issue suggesting they might look at this in Dec/Jan, so I'll hold off doing anything here until next month since I'd much prefer to add the second button.
