### ISSUE TITLE
Indentation style is changed on file open

### ISSUE THREAD

**Issue by oscarcs** [Dart-Code/Dart-Code#1370]
The extension sets your indentation style to 2 spaces upon opening a file, regardless of what the actual indentation is. It appears this behaviour can't be disabled. Possibly related to #799.

**Comment by DanTup** [comment]
Although we can't provide formatting based on spaces, I think we should try not to force this upon users (it's likely caused by us setting the default).

**Comment by DanTup** [comment]
Ok, I had a quick play around with this and I don't think I can easily make this automatic (the issue is that if we don't set a default, then it won't use 2-space indenting for users creating new files).

However, since we only contribute it as a default, you can just set your own defaults in your User Settings (or if for a single project, Workspace Settings) file:

```
"[dart]": {
		"editor.tabSize": 4,
		"editor.insertSpaces": false
	}
```

Alternatively you can set `editor.detectIndentation: true`, but we've set the default to `false` for Dart because it doesn't work reliably due to Dart's "indent with 4 spaces for wrapped lines" rule.

It's not perfect, but I do now think it's the best we can do without upsetting the common case.

Thanks for bringing it up though!
