### ISSUE TITLE
Many irrelevant suggestions appear, and they may be autoselected by default, when using optional parameters

### ISSUE THREAD

**Issue by gabrc52** [Dart-Code/Dart-Code#1376]
![peek 2019-01-05 17-19](https://user-images.githubusercontent.com/24363938/50730235-508ad180-110e-11e9-9633-d6af3b15da9f.gif)

Here, I created a Flutter stateless widget with the stless snippet, and after typing `appBar: ` the first suggestion is `stless` and I have to scroll all the way up to see the `AppBar()` suggestion.

```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: ,
    );
  }
}
```

**Comment by DanTup** [comment]
I think this is VS Code's bad default behaviour. There's a setting named `editor.suggestSelection` which has three values:

- first
- recentlyUsed
- recentlyUSedByPrefix

The default is the middle one, which will pre-select based on things you've used recently. I would recommend changing to the third or first one and see if that improves things. If so, I'll add it to the [Recommended Setting](https://dartcode.org/docs/recommended-settings/) page.

**Comment by DanTup** [comment]
Also - for me, the snippets (eg. `stless`) appear at the bottom of the list - can you confirm which version of the Dart extension you have installed, and whether you have any other extensions contributing snippets? This may also be a bug.

**Comment by gabrc52** [comment]
The snippets do appear at the bottom, even though using them doesn't make sense in this context. I'm using version 2.21.1.

Thanks for the setting, the issue isn't present after changing it. I didn't know about these recommended settings, are they in the Flutter website?

**Comment by gabrc52** [comment]
The issue seems to be that many of the suggestions are irrelevant. For example:

```dart
Container(
  decoration: 
)
```

Here, the suggestions in order are:

1. Constructors of type Decoration
2. Available variables
3. Keywords const, false, new, null and true
4. All available classes and enums
5. Functions, getters, constants, annotations, etc.
6. Snippets

Suggestions 2-6 shouldn't appear unless they're of type `Decoration` or return a `Decoration`.

As a result of this, VSCode selects an irrelevant suggestion by default because of the default value of `editor.suggestSelection`

**Comment by DanTup** [comment]
> Suggestions 2-6 shouldn't appear unless they're of type Decoration or return a Decoration.

It's often valid to type these items, because you could be writing something like:

```dart
Container(
  decoration: new MyThing().theDecoration,
)
```

or

```dart
Container(
  decoration: SomeClass.myInstance["thing"],
)
```

Snippets are also always valid, because their contents could contain anything (for example you could have a snippet of code that returns a decoration).

The completion options actually from from the SDK so any changes would need to be made there (though based on the above, I don't think the things you want to go away will). They are sorted by a rank, however, so it's possible that could be tuned if there are items that should be at the top that are appearing down the list.

> As a result of this, VSCode selects an irrelevant suggestion by default because of the default value of `editor.suggestSelection`

Unfortunately VS code has many defaults that result in quirks like this (which is why I've started collecting them in the [recommended settings](https://dartcode.org/docs/recommended-settings/) page, which we may point users at in the future). The issue isn't isolated to Dart, TypeScript has exactly the same thing:

<img width="672" alt="screenshot 2019-01-08 at 8 38 51 am" src="https://user-images.githubusercontent.com/1078012/50819103-0463ab00-1321-11e9-9832-5553b049fb8a.png">

If you think the default in VS Code should be changed, you could open an issue in the VS Code repo (I'd certainly 👍 it if you post the link here - it makes me sad that we need to document all the "bad" defaults for reasons like this).

**Comment by DanTup** [comment]
I've added this to the recommended settings page but I don't think there's anything more I can do here. Even [the TypeScript extension has had the same issue reported](https://github.com/Microsoft/vscode/issues/45273), and the fix is to modify the setting. I agree this isn't great, but I don't want to override peoples settings.
