### ISSUE TITLE
Swap build_runner commands for webdev for web projects

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1412]
We'll need to find a way to know when something is a "web" project!

**Comment by alanknight-wk** [comment]
One way to determine this is that if the launch config specifies to launch "web", or something in a "web" directory, then it's a web project. This is probably one of the better ways, because some projects might have both web components and command-line utilities to support, with different launch configs. So you can't really say if the project as a whole is a "web" project, just if a particular launch should be for the web.

**Comment by alanknight-wk** [comment]
It occurs to me that that's harder to use for tests, but one option would be to look at the @TestOn directive in the test file.

**Comment by DanTup** [comment]
This issue is actually very old, and work was already done to use `webdev daemon` for running web apps (and it uses the `launch.config` to identify trying to launch things in the `web` folder).

So I don't think there's anything to do here (this was specifically about running web apps, not tests), but let's file more specific issues if there are things missing (that aren't covered by the other open issues).
