### ISSUE TITLE
Deleted dart.sdkPath in config is loaded

### ISSUE THREAD

**Issue by ikhwanhayat** [Dart-Code/Dart-Code#142]
I have 2 SDK in my machine, version 1.16 and version 1.19. The 1.19 is in the PATH env.

Repro steps:

1) Set `dart.sdkVersion` in `settings.json` to path to 1.16
2) 1.16 is correctly loaded as target SDK (1.16 shown at status bar)
3) Comment out `dart.sdkVersion`.
4) Close VS Code and re-open.
5) 1.16 still loaded as target SDK.

**Comment by DanTup** [comment]
This will be because we stash the last known SDK path and use that as the first search path at startup (to avoid searching `PATH` every time).

We should ensure the last known SDK path is actually in config of `PATH` before using it.

(Or alternatively time how long searching PATH actually takes and drop this... I added it because startup seemed slow, but it's still slow anyway).

**Comment by DanTup** [comment]
In some simple testing, having 100 items in path before the SDK added 2-3ms. I'm on SSDs so it might be more on a spinning rust drive, but it doesn't seem the savings are worth the effort so I'm just gonna remove this code rather than trying to fix this another way (it's complicated because the `lastKnownSdk` value could be a resolved symlink and isn't immediate comparable to the `PATH` list).

**Comment by DanTup** [comment]
Sorted, thanks for reporting!
