### ISSUE TITLE
Allow running non-widget tests

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#1421]
We're supporting widget tests but we should also support `test` besides `testWidgets`

**Comment by DanTup** [comment]
As far as I'm aware, this all already works! :)

<img width="931" alt="screenshot 2019-01-24 at 8 59 06 am" src="https://user-images.githubusercontent.com/1078012/51666665-5578cd80-1fb6-11e9-975e-4b17b7b8764f.png">

If you're seeing issues, can you provide more info on what your project/code looks like and where you're seeing the failure?

**Comment by xster** [comment]
I only reproduced it in this case. https://github.com/flutter/flutter/issues/27002. Which isn't really supported anyway. Closing

**Comment by DanTup** [comment]
If you have a small repro, I'd be interested to know went wrong in the VS Code plugin. Even if the error messages are obscure, that shouldn't cause any bad behaviour in the test runner. Maybe there are edge cases not being handled correctly?

**Comment by xster** [comment]
Actually maybe it doesn't work. Try https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/editable_test.dart. F5 works on that file but they aren't per-method debuggable.

**Comment by DanTup** [comment]
Ok, I think I figured this out... This feature works using the `UNIT_TEST_TEST` items in the `OUTLINE` notification. It seems like in the file above, we only get a `UNIT_TEST_TEST` for one test - the one that uses `testWidgets`, not the others (you can see the outine tree on the left here, and the code on the right):

![screenshot 2019-01-31 at 10 01 06 am](https://user-images.githubusercontent.com/1078012/52046676-355d8700-253f-11e9-8d68-339c198e154a.png)

I did some digging through the server code, and it seems that in order to be considered a test call, the method (being called) needs to:

1. Be called `test` and live inside the `test` package
2. Be annotated with `@isTest`

It seems that `testWidget` is annotated with `@isTest` but `test` from `flutter_test` is not. I think the way to fix this would be to add the `@isTest` annotation to the `test` method inside flutter_test that is being called here. I do not know if there are any side-effects of that though :-)

**Comment by DanTup** [comment]
I think the change may be safe, it seems like it's just a marker annotation that doesn't really do much. @scheglov maybe you can confirm - you added it to `testWidget` (https://github.com/flutter/flutter/pull/17772) - do you expect it's safe to add this to the [`test` function here](https://github.com/flutter/flutter/blame/dbd1b317ff6f39ace51bdd2c92133368017c3a17/packages/flutter_test/lib/src/test_compat.dart#L158)?

**Comment by scheglov** [comment]
It looks like a copy of `package:test`, so yes, I think `test` and `group` functions also should be marked as `@isTest` and `@isTestGroup`.

**Comment by DanTup** [comment]
Fixed in Flutter `master`, thanks for the report!
