### ISSUE TITLE
Add option to manually invoke the anaylzer.

### ISSUE THREAD

**Issue by dcov** [Dart-Code/Dart-Code#1452]
I've been having issues with the analyzer using too much CPU which causes a delay whenever I type. I know this might be an issue with the analyzer, but at this point I would rather manually invoke it whenever I want to run the analysis. Is this possible?

**Comment by DanTup** [comment]
The analysis server supports a huge portion of the functionality of the plugin, it's not possible to just turn it off (analysis, code completion, navigation, code folding, etc. are all analysis-server powered).

Have you confirmed it's the analysis server process using the CPU? You can open VS Code's process explorer to see where the CPU is going. If it is indeed the analyzer, we could do some profiling to find out where it's going.

That said, I wonder if you may be hitting https://github.com/Dart-Code/Dart-Code/issues/1441. You could check if installing this beta -> https://github.com/Dart-Code/Dart-Code/releases/tag/v2.23.0-beta.3 resolves the issue.

**Comment by dcov** [comment]
Yeah I realize it would break a lot of those features happening automatically, but it wouldn't be too much of an inconvenience to manually run an analysis so that I can access those features. Like for code-completion, a lot of times I end up manually typing whatever it is I want to type anyways, and if I do need the help of the analyzer to suggest completions for me then I could manually run the analysis.

Yes whenever I'm actively editing a file, under the VS Code process explorer the `analysis_server.dart.snapshot` process shows CPU usage of around 20-25%, and under the Linux process display the `Dart` process shows usage of around 100%.

I installed the `v2.23.0-beta.3` extension and the usage remained the same.

This is probably just my laptop getting old (nearing 5 years) and not the analyzer itself hogging resources, so I just thought I'd ask if it was possible to have more control over when to run the analysis. Also, I'm not suggesting not running the server, just the option to decide when to pass the code for analysis to the server.

**Comment by DanTup** [comment]
> I'm not suggesting not running the server, just the option to decide when to pass the code for analysis to the server.

The server reads all your files off disk at startup, and then we just notify it of the changes you're making as you type. The analysis errors are just streamed to us from the server automatically (we don't ask for them) and when we want something like code completion we just send it the document offset. I'm not really sure it makes any sense to try and run it empty/cold because then when you wanted something like code-completion you'd be waiting a really long time for the server to read all the files from your project, process all the file buffers from VS Code, analyze it all, etc.

If you're seeing 25% or 100% CPU all the time while typing, that sounds pretty bad and I think we should do some profiling to try and find out where the time is being spent.

If you set the `dart.analyzerObservatoryPort` setting to a number (something in the 8000's is usually good) then open your browser at `localhost:(port)` you'll see the Observatory app for the analysis server process. On the right side there are options for CPU Profiling. If you open one of those pages you should be able to get profiling data that might indicating where the time is being spent.

**Comment by dcov** [comment]
> ...then we just notify it of the changes you're making as you type.

I've probably been wording it wrong, but yes I was referring to manually controlling this aspect. 

I'm not too sure how the analyzer works in detail so I might look like an idiot here, but this is how I imagine it might work:

- The analyzer would be initialized as usual when opening a file/project.
- The user would edit a file, but the analyzer isn't being notified while this is happening.
- The user decides to run an analysis for whatever reason, so they notify the analyzer somehow.

Again I might be misunderstanding how Dart-Code interacts with the analyzer, so I'm not too sure here.

> If you're seeing 25% or 100% CPU...

It's not using all of my CPU all of the time, it mainly ramps up its usage on larger files which is understandable. It mostly sticks to a little under 20%. But yes, on larger files it can be bothersome as it causes a delay when typing.

I'll go ahead and profile it's usage to see what I can come up with. Thanks for the help.

**Comment by dcov** [comment]
I looked at #1433 and tried to see if this might be related to my issue. It turns out that the Window process uses up around 12% which coupled with the analyzers more-or-less 20% usage, might be what's causing me problems.

**Comment by DanTup** [comment]
> this is how I imagine it might work:
> 
> * The analyzer would be initialized as usual when opening a file/project.
> * The user would edit a file, but the analyzer isn't being notified while this is happening.
> * The user decides to run an analysis for whatever reason, so they notify the analyzer somehow.

The problem is, after the user has been typing (but before they have force a sync to the server) there will be loads of functionality that would be unpredictably broken (for example, just hovering your mouse over something or running Go-to-Definition). While it would be possible to make them all silently-do-nothing in this case, this would mean making a lot of changes to a lot of places just to support this scenario - which IMO doesn't make much sense - if performance is bad we should see if it's something we can improve - improved performance would benefit everyone.

> I looked at #1433 and tried to see if this might be related to my issue. It turns out that the Window process uses up around 12% which coupled with the analyzers more-or-less 20% usage, might be what's causing me problems.

Even at 30%, I wouldn't expect to cause significant issues. Could you try installing the beta version linked above to see if it changes anything? I do think that you may be hitting #1441.

**Comment by dcov** [comment]
Yeah if it means making a lot of changes to support it, then I'd rather drop it, especially since, as you said, it would break a lot of functionality.

I installed the beta version but it didn't affect the usage.

I'm okay with waiting on #1433 since it appears related to my issue. I'll go ahead and close this issue now. Thanks.

**Comment by DanTup** [comment]
In #1433 the high CPU usage was from the VS Code render process, do you see that? I'd definitely like to track this down if we can. A CPU profile of the Dart process from Observatory would help, and if the VS Code processes are eating lots of CPU, a CPU profile from the dev tools there would help.

If you can see which you think is using the most resources, I can try and make some notes on how to capture some data.
