### ISSUE TITLE
"Missing implementation" error on consuming class, not implementing mixin

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1479]
```dart
class Foo = Base with Mixin;

abstract class Interface {
  final String a = "a";
}

class Base {}

mixin Mixin on Base implements Interface {}
```

<img width="755" alt="screen shot 2019-02-25 at 12 23 36 pm" src="https://user-images.githubusercontent.com/666539/53355941-342e3880-38f8-11e9-8bac-56b05aabaafa.png">

Is there any way to get the "Missing implementation" error on Mixin instead of the consuming class? It seems fine in this example but if you're building out your mixins simply to be consumed you will never see this error.

eg

```
abstract class Interface {
  final String a = "a";
}

class Base {}

mixin Mixin on Base implements Interface {}
```

<img width="572" alt="screen shot 2019-02-25 at 12 24 54 pm" src="https://user-images.githubusercontent.com/666539/53355995-6049b980-38f8-11e9-921b-0b64242edcaf.png">

Perhaps this is a dart-lang/sdk issue?

**Comment by DanTup** [comment]
> Perhaps this is a dart-lang/sdk issue?

That's correct - the errors all come from the analysis server so we can't influence them from the VS Code plugin. 

That said, I don't know if the request makes sense:

> Is there any way to get the "Missing implementation" error on Mixin instead of the consuming class?

If I understand correctly, it's valid for the Mixin *not* to implement it, since it might deliberately be left to the consuming classes (I did this just recently - I have a mixin where I want to call a method that should be supplied by the implementing class, since it has its own implementation).

> if you're building out your mixins simply to be consumed you will never see this error.

If you add any tests that implement the mixin, then you should see errors pop up? If you don't have any, maybe a private class that implements it just sat alongside the mixin would work (though admittedly it feels a bit like a workaround - I think adding tests, even if really basic, may be better).

**Comment by lukepighetti** [comment]
Ahhhh good point, lets close this!
