### ISSUE TITLE
show the sdk upgrade toast only for major version differences?

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#148]
This toast shows up for minor sdk differences:

<img width="729" alt="screen shot 2016-08-29 at 5 23 35 pm" src="https://cloud.githubusercontent.com/assets/1269969/18071841/90458460-6e0d-11e6-9ba7-8fec806e97f4.png">

Perhaps we should only show if there is a major version difference?

**Comment by DanTup** [comment]
Isn't this valid? You're on an RC and the final version is available - seems like moving from non-stable to stable is something to promote?

I'm not against changing it, I think people using pre-releases will generally know when release versions come out, but this behaviour seemed correct.

We should probably also add an option to disable this; if you need to target an old version (not sure how common this is, but we do it the time with .net since upgrading a server affects all apps; at least pre netcore) you can disable (globally, or within one project).

**Comment by devoncarew** [comment]
Ah, if it's showing that a stable version of a dev is available, that makes sense. I assumed it was showing that there was any change! Sorry for not checking the code.

Adding a pref to disable the check makes sense though - it'll be less noisy for people who choose older versions.

**Comment by DanTup** [comment]
If I've understood correctly, any version suffixed with `-something` is a "pre-release" version of the same version without the suffix (eg. `1.19.0-rc` or `1.19.0-dev` are earlier than `1.19.0` on its own).

But, if you think it's noisier than it should be, we can tweak (it's not a big problem if people don't get notifications in some cases). Though I presume once you deployed `1.19.0` your repo would've been rolled to `1.19.1-dev`? If that doesn't happen quickly, then this could be misleading for you?

**Comment by DanTup** [comment]
@devoncarew I've created #149 to add an option for not showing notifications (this could be useful at a project-level if you having something targeting an old version).

Do you think there's anything to do for this, or are you happy with the notification of a stable version if you're on an earlier dev version?

**Comment by devoncarew** [comment]
> Do you think there's anything to do for this, or are you happy with the notification of a stable version if you're on an earlier dev version?

No, looks great as is. I had misunderstood when the plugin notified about sdk updates (adding a pref still makes sense)

**Comment by DanTup** [comment]
Cool; I'll close this then and we'll add an option to disable in #149.
