### ISSUE TITLE
Analyzer analyzes files in ignored directories/other projects if you open them, and doesn't stop when they're closed

### ISSUE THREAD

**Issue by dnfield** [Dart-Code/Dart-Code#1480]
Repro:

1. Open the Flutter repo in VSCode
2. Navigate to the definition of something in `dart:ui` or the Dart SDK (i.e. a file under the `bin/cache/**` folder)
3. Problems window starts showing analysis issues in that folder based on current analysis options, even though `analysis_options.yaml` excludes it.
4. Close the file (or even VSCode as a whole), but the problems still persist.

It seems to go away if I `rm -rf ~/.dartServer` with VSCode closed and then re-launch.

**Comment by dnfield** [comment]
I suspect the best behavior here would be to respect whatever is excluded/ignored in `analysis_options.yaml`, but at the least it would be nice if this could be made to go away once the buffers are closed.

**Comment by DanTup** [comment]
I think this may be the same as https://github.com/Dart-Code/Dart-Code/issues/1130

> I suspect the best behavior here would be to respect whatever is excluded/ignored in `analysis_options.yaml`

We don't parse the file in the plugin, so this should be handled in the server. Unfortunately I think you're seeing https://github.com/dart-lang/sdk/issues/25551 (I think the title is a bit misleading, I think it's much broader than that).


> but at the least it would be nice if this could be made to go away once the buffers are closed.

There were some changes made to improve this recently, though unfortunately VS Code doesn't give us any event when a document is closed (yep, you read that right - the closed event can come "up to three minutes" after you close a file (which [makes testing things](https://github.com/Microsoft/vscode/issues/68989) really difficult, because close events start diring in the middle of future tests).

I'll do some testing and see why the fixes made to improve this don't seem to be helping here though...

**Comment by DanTup** [comment]
@dnfield I can't repro this - can you give a concrete example of where you navigated to? I do see errors when opening the Flutter repo root (which I tend not to do, and instead open the folders I need as a multi-root workspace, possibly because there were issues around this!) but not inside the embedded SDK - but I don't know if I need to open specific files?

<img width="1545" alt="screenshot 2019-02-27 at 11 57 42 am" src="https://user-images.githubusercontent.com/1078012/53488735-1511e100-3a87-11e9-965b-be87e9ede908.png">

**Comment by dnfield** [comment]
Ahh I see.  It sounds like in current state we can either get semantic highlighting and formatting and errors or neither... 😦 

I'll close this as a duplicate of the linked issues.

**Comment by dnfield** [comment]
BTW to repro it, do a Ctrl/Cmd + Click on `String` in any dart file.  It will open up `string.dart` from the SDK, which doesn't follow Flutter's analysis rules.  Once it's there, it won't disappear until you clear your `.dartServer` and restart VS code.

**Comment by dnfield** [comment]
I can kind of work around this by adding a filter to the problems window like `!bin/cache/**`

**Comment by DanTup** [comment]
> BTW to repro it, do a Ctrl/Cmd + Click on `String` in any dart file. It will open up `string.dart` from the SDK, which doesn't follow Flutter's analysis rules. Once it's there, it won't disappear until you clear your `.dartServer` and restart VS code

Aha, right. I see now. I believe this is the issue described in a comment at https://github.com/dart-lang/sdk/issues/25551#issuecomment-418437599. However I don't think it has its own issue, so I'll open one for better visibility so it doesn't get missed.
