### ISSUE TITLE
cannot create dart project: Unable to execute Stagehand

### ISSUE THREAD

**Issue by iptton** [Dart-Code/Dart-Code#1482]
trying to create a dart project. failed with message:

Unable to execute Stagehand. Stagehand exited with code 65. stagehand 3.1.5 doesn't support Dart 2.1.0-dev.9.4.flutter-f9ebf21297.

**Comment by DanTup** [comment]
This happened because the latest version of Stagehand required a newer Dart SDK than was shipped with the version of Flutter you have.

As luck would have it, there was [a new version of Flutter](https://twitter.com/flutterio/status/1100442350730469376) released today, so if you `flutter upgrade` and try again, you should find it work.

Please let me know if not, and we can do some digging. Thanks!
