### ISSUE TITLE
Debugger treats local packages as "external packages", and doesn't debug by default

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#1497]
When code execution stops to a breakpoint (or to an exception), the source file and line where the breakpoint is located is not activated automatically in the editor window. You have to click the topmost line in the "Call stack" window to see the correct source location in the editor window. Execution point in the editor window is lost again every time you continue debugging with commands like Step Over or Step Into. So you have to continuously click the correct line in the "Call stack" window to see the correct line in the editor window. 

This issue makes the debugging experience terribly bad. There was not this issue earlier, but unfortunately I cannot remember the exact time when this problem occurred.

**Comment by DanTup** [comment]
Can you give a specific example? What frame was shown on the call stack, and what was the top frame?

There were changes made recently in both VS code and the Dart plugin to improve the experience of breaking on exceptions (showing the frame had the users code, rather than framework code that might just say `<source not available>`), so my guess is that's related - I'd need a concrete example to be sure though.

**Comment by kinex** [comment]
I found steps how to reproduce the issue with a sample project:
1. flutter create myapp
2. flutter create -t package mylib
3. In myapp/pubspec.yaml add
```
dependencies:
  mylib:
    path: ..\mylib
```
4. Modify myapp/main.dart:
```dart
import 'package:mylib/mylib.dart';

void main() {
  final calculator = Calculator();
  calculator.addOne(1);
  runApp(MyApp());
}
```
5. Modify mylib/lib/mylib.dart
```dart
library mylib;

/// A Calculator.
class Calculator {
  /// Returns [value] plus 1.
  int addOne(int value) {
    print(value);
    return value + 1;
  }
}
```
6. Set a breakpoint to the first line of Calculator.addOne
7. Start debugging
8. Execution stops to the breakpoint but the file/line is not activated in the editor. Try also Step Over, it is not working as expected (focus in the editor is lost on every step).

Breakpoints in myapp seems to work properly, so I guess the breakpoint (or an exception) must be in a package project to reproduce the issue.

**Comment by DanTup** [comment]
Thanks for the detailed steps - I can repro.

The issue seems related to the `"dart.debugExternalLibraries"` setting. This lets you control whether packages show be debuggable. In this case your library looks like an external library, but you've put a breakpoint in it. The results in the VM breaking, but VS Code thinks that code should not be debugged.

As a workaround, you can set `"dart.debugExternalLibraries": true,`, though I'll see if there's an easy way for me to separate "local" packages from pub ones, so you can still avoid stepping into pub packages without losing the ability to step into your own.

**Comment by kinex** [comment]
Thanks, workaround helped! I think a bigger and well structured app will always consist of an app project + several local packages. For example my app has currently an app project + 11 local packages. Therefore I think it is important that debugging this kind of app works properly. I don't fully understand the idea of the setting `dart.debugExternalLibraries` here. If it stops to a breakpoint or an exception even if `dart.debugExternalLibraries` is false, why not to activate the file/line as well.

**Comment by DanTup** [comment]
> Therefore I think it is important that debugging this kind of app works properly.

I completely agree. I don't think the debugger is used all that thoroughly so there are a lot of edge cases that have slipped through. I'm trying to add tests where they come up to ensure they work going forwards though (I've got a failing test for this and a fix that seems to work, but has broken some others, so just working through).

> I don't fully understand the idea of the setting `dart.debugExternalLibraries` here

By default, we assume people want to treat libraries (that aren't theirs) as "black boxes". So when an exception occurs, we try to put you on the top-most stack frame of *your code* rather than on the line that actually threw. It's more obvious with SDK libraries, imagine you had this:

```dart
assert(foo != null);
```

When this assertion fails, you'd want to be taken to that line of code, but without `dart.debugSdkLibraries` and `dart.debugExternalLibraries` you'd actually end up inside the implementation of `assert` which is confusing (especially right now, when the SDK doesn't include sources so you just see `<source not available>`).

So the bug is that we don't distinguish between "local libraries" (those you probably want to break in the implementation of) versus "external libraries" (those that you probably want to treat as black box, and break on your calls to - on the assumption that the library is bug-free, and you're using it wrong). This isn't always what you want - which is why we have the settings, and #1291 is a request to make it faster to toggle between them, but seems most common. It's intended to work like [Just My Code](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2017) in .NET.

The fix I have will narrow what's considered an "external library" to files inside the Pub Cache folder for pub.dartlang.org, which will hopefully be more like what you'd want (this has the probably-good side effect that if you switch to a path-override for a dependency, it'll be treated as local, as you may be trying to debug/fix something).

**Comment by DanTup** [comment]
Most of what I wrote above was geared around exceptions... I think breakpoints are different and your point is valid - if the user put a breakpoint somewhere, we should never treat it as code we shouldn't break at. I've opened https://github.com/Dart-Code/Dart-Code/issues/1502 to tweak that too. It won't be needed for your case here (since we'll detect your local package as local), but I think if you step into an "external" package and set a breakpoint, it's reasonable to expect that to break in the right place too.

**Comment by kinex** [comment]
Thanks for the details and quick responses!

**Comment by DanTup** [comment]
@kinex I believe I've fixed both issues. If you'd like to try it out, please remove the setting you added, and then install this build:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.25.0-alpha.2

(I've called it an Alpha because it's not feature complete, I believe the quality is good and the [tests are all passing minus some flakes](https://dartcode.org/test-results/?master/21407987d240c5e5001aad60314c04073b8b6262))

There's info on [installing preview builds here](https://dartcode.org/docs/installing-a-preview-release/), it's pretty simple and you'll automatically be moved back to stable releases when the next one goes out.

**Comment by kinex** [comment]
@DanTup I installed the alpha! No issues found so far after a quick test, I continue testing it.

**Comment by DanTup** [comment]
@kinex Great, thanks for confirming. Do open new issues if you do come across anything (related or otherwise). Thanks!

**Comment by kinex** [comment]
@DanTup Yes, sure! And thank you, great work!
