### ISSUE TITLE
Dart: Dev Tools command not showing

### ISSUE THREAD

**Issue by JonasJW** [Dart-Code/Dart-Code#1517]
`Dart: Dev Tools` is not showing for me in VS Code. I have a flutter app running in debug. 

What resources can I share to help track down the issue?

**Comment by DanTup** [comment]
Can you confirm the version of the Dart extension you have installed? In v2.24, the only restriction on whether the command appears in the command palette is `inDebugMode`:

https://github.com/Dart-Code/Dart-Code/blob/v2.24.0/package.json#L484

This is a VS Code-owned context that should be set whenever you're in a debugging session. Are there any warnings or errors in the VS Code Developer Console? (click Help -> Toggle Developer Tools).

**Comment by JonasJW** [comment]
I just found out I'm on `Dart-Code.dart-code@2.12.1`. Shouldn't vs code automatically update extension? However I couldn't find a way to update the extension.

I don't have the `inDebugMode` option (probably because of version) and I don't get any warnings or errors in the developer console

**Comment by DanTup** [comment]
> I just found out I'm on `Dart-Code.dart-code@2.12.1`

I can't find a tag/release for version v2.12.1, did you get that wrong? v2.12.0 is from April last year!

> Shouldn't vs code automatically update extension?

It should, though I think it can be disabled. If your version of VS Code is old, that could also stop it updating (since newer versions of the extension require newer versions of VS Code for hew features).

Can you check your VS Code version, the `extensions.autoCheckUpdates` setting and also double-check your Dart extension version?

> I don't have the `inDebugMode` option

`inDebugMode` is just a context - it's not something you can see. It's essentially an internal flag that we can use in extensions to know whether there's an active debug session or not. The **Open Dev Tools** command uses it so you can't launch Dev Tools without an active debug session.

**Comment by JonasJW** [comment]
`Dart-Code.dart-code@2.12.1` Thats what it says when I run `code --list-extensions --show-versions`

My vs code version is `1.22.2` and `"extensions.autoUpdate"` is enabled.

**Comment by cesarcamps** [comment]
this could be related with #1518

**Comment by DanTup** [comment]
> Dart-Code.dart-code@2.12.1

Did you ever install a pre-release version? I think maybe 2.12.1 was a dev version that was made 2.13 before release. Anyway, ...

> My vs code version is 1.22.2

That's likely the problem - VS Code is on 1.32 now, and we often increase the version we need in order to get new APIs. If you update VS Code to latest, you should get the latest version of the Dart extension. However, be aware of the issue @cesarcamps links above - the latest VS Code (1.32) appears to have changed something that has broken some of our debugging features - 1.31 would be the best version to install for now if you can.

**Comment by JonasJW** [comment]
It was indeed a problem with the vs code version, even though vs code should update automatically as far as I know and the option wasn't disabled.

However now it's showing `Dart: Dev Tools` but when I click on it, it tells me `Dart DevTools requires an active debug session.`. I am running a flutter app in debug mode, and when I'm not, it doesn't show me `Dart: Dev Tools`.

**Comment by DanTup** [comment]
> but when I click on it, it tells me Dart DevTools requires an active debug session.

Yep, that's the issue mentioned above introduced in VS Code 1.32. I would recommend downgrading to VS Code 1.31 (there are download links at the top of [this page](https://code.visualstudio.com/updates/v1_31)) until we have a fix (it's not yet clear if it's a VS Code bug or a bug in the Dart extension that just used to work before, but no longer does).

**Comment by DanTup** [comment]
(I'll close this one, since I think the issue it describes is fixed, and the remaining issue is covered by #1518).

**Comment by JonasJW** [comment]
Thanks for the help! Works great now

**Comment by michaeldwu** [comment]
Hi @DanTup, I'm now experiencing a similar issue on the latest version of VSCode where DevTools won't show up (or will say that I need to be in an active debug session to use) when I'm on profile mode. Any fixes?

**Comment by DanTup** [comment]
@michaeldwu unsure - could you file a new issue and include [a log file you started capturing](https://dartcode.org/docs/logging/#capture-logs-command) (untick analysis server, but keep everything else ticked) before launching the debug session, and stopped after you tried to launch DevTools and got the message (or it didn't appear)?

**Comment by michaeldwu** [comment]
Hey @DanTup, thanks for the response. I believe I solved it by going to the launch.json file in the vscode folder of my project and adding this line `"flutterMode": "profile"` to dependencies, and then running the debugger. That ended up launching it in profile mode for me.

**Comment by DanTup** [comment]
@michaeldwu how were you previously launching profile mode when it didn't work?

**Comment by michaeldwu** [comment]
@DanTup I was attempting to run it through my terminal with `flutter run --profile` !

**Comment by DanTup** [comment]
Ah, yes - that would do it. Unfortunately the built-in terminal is just a terminal, and doesn't interact with the extension (we can't tell that you're running Flutter, nor attach to it). I'd always recommend running using the built-in debugger/Run menu, that way you'll get all of the functionality :-)
