### ISSUE TITLE
Sort Dart imports

### ISSUE THREAD

**Issue by grouma** [Dart-Code/Dart-Code#1520]
`Dart: Sort Members` sorts the imports as well as the methods / variables. It would be nice to have functionality that only sorts the imports and leaves the members as is.

**Comment by DanTup** [comment]
There's an **Organize Imports** command that does this :) It's not prefixed with **Dart:** because it's a "first-class" feature in VS Code. Should you want to, you can make it run automatically on save too (see [here](https://code.visualstudio.com/updates/v1_23#_run-code-actions-on-save)).

Let me know if this doesn't so what you're expecting!

**Comment by grouma** [comment]
Ah perfect! That's why I couldn't find it. Thanks!
