### ISSUE TITLE
Flutter projects nested more than 2 levels deep do not force "Flutter mode", preventing launching/debugging apps

### ISSUE THREAD

**Issue by galki** [Dart-Code/Dart-Code#1549]
**Folder structure**

- /monorepo_root
  - apps
     - app1
       - lib/main.dart
     - app2
       - lib/main.dart

**Works**
1. File > Open Folder (app1)
2. Start Debugging

**Doesn't work**
1. File > Open Folder (monorepo_root)
2. In Explorer right click on app1/lib/main.dart
2. Select Start Debugging

```
lib/main.dart:1: Warning: Interpreting this as package URI, 'package:app1/main.dart'.
file:///C:/src/flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/app.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/bottom_app_bar_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/card_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/chip_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/colors.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show Color;
       ^
file:///C:/src/flutter/packages/flutter/lib/src/material/dialog_theme.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
       ^
Exited (sigint)
```

**Comment by DanTup** [comment]
This is expected right now. When deciding whether to load the Flutter SDK or Dart SDK, we look two levels down to see if there's a Flutter project, and if not, we go into "Dart Mode".

If you can't open a folder closer to the apps, the best current fix is to click File -> Add Folder to Workspace and then select your app1/app2 folders which will show them in the Explorer tree as "Workspace Folders". Unfortunately, this means they will appear in two places in the tree - there is a request to fix that in VS Code at https://github.com/Microsoft/vscode/issues/45470 (please add a 👍 ).

We could scan further down the tree looking for Flutter projects at startup, but it would slow down startup (significantly for those opening large trees) and doing it this way also prevents you from having your own settings/launch configs within each of the apps folders.

**Comment by galki** [comment]
Would be ideal if the level(s) scanned could be a configurable setting.

**Rationale**
- common structure for monorepos (nrwl/nx etc)
- all apps and libs are in the 3rd level down
- monorepos (common root folder) by definition don’t require workspace functionality

**Comment by DanTup** [comment]
I've been trying to avoid encouraging people down this route because there are lots of other drawbacks with this. For example, you can't have per-project launch configs if your project is set up like this, or per-project settings. This means opening a project (`app1`) directly will behave very differently to opening `monorepo_root`.

VS Code supports [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) which allow you to open multiple projects together while still treating them as "projects" and having their own VS Code settings, launch configs, etc. which is what the issue linked above is about trying to improve to handle the case of nested folders better.

I'll try and do some investigation into how other languages are handling this (probably next week now). I did start along this path once but it was not trivial (for example, when you tried to run things like `pub get` it'd run in your root folder, not a project). Some things have been improved since, but I'm sure there are still edge cases. I don't want to encourage people to work this way unless I'm sure it'll seamlessly support everything you'd get from having multi-root workspaces.

**Comment by galki** [comment]
Right, that also makes sense. Guess this is a "better safe than sorry" concern and the sacrifice from a monorepo perspective would be not seeing the actual folder structure. I'm not sure if forcing monorepo-wide settings on purpose would make a strong case where common/shared packaged exist but that's what I had in mind.

**Comment by galki** [comment]
In my case I'm hosting the monorepo apps on Firebase in a single project. After doing some research I came to the conclusion that it's better to separate each app into its own Firebase project. In this light your advice makes much more sense so I'm fine with this issue being closed.

**Comment by DanTup** [comment]
Thanks for the update! I'll keep this open because I think we should do a better job of guiding people here (the error when trying to run a Flutter project on the Dart VM is cryptic for one), even if it's just detecting the failure and linking them to a page/issue that describes the above.

**Comment by DanTup** [comment]
In #1792 we started walking down the tree further (3 levels) when looking for projects. I think this solves the issue above (at least until someone comes along with a structure that has them 4 levels deep 😄).
