### ISSUE TITLE
Allow accessing files outside of "lib" inside Dependencies tree

### ISSUE THREAD

**Issue by Rodsevich** [Dart-Code/Dart-Code#1590]
Ideally, through rightclicking from Dependencies view

**Comment by DanTup** [comment]
I implemented this:

![Screenshot 2019-04-16 at 2 03 51 pm](https://user-images.githubusercontent.com/1078012/56211767-86feb380-6050-11e9-93fc-d477c4fd4584.png)

However I found a problem:

![Screenshot 2019-04-16 at 2 04 01 pm](https://user-images.githubusercontent.com/1078012/56211786-93830c00-6050-11e9-98ca-0c047fcfdce1.png)

If you open it as its own folder (either in a new window, or even as an additional analysis root in for the current window) it doesn't resolve its own dependencies, and therefore everything has squiggles:

![Screenshot 2019-04-16 at 2 04 01 pm](https://user-images.githubusercontent.com/1078012/56211833-ab5a9000-6050-11e9-9617-b2af908e891d.png)

(it also tries to prompt you to run `pub get`, though I could fix that).

I think this is because without a .packages file, it doesn't know where to get these packages from (whereas inside your own project, the .packages file has all transient dependencies).

So maybe the only way to handle this would be to do your original suggestion, which is to allow the tree to render from the root of the package instead of its lib folder. Or, we could add the folder to the VS Code workspace and exclude it as an analysis root.

I'll come back to it after doing #1591 to see if anything better comes to me.

**Comment by Rodsevich** [comment]
Nice! :smile:

> allow the tree to render from the root of the package instead of its lib folder. Or, we could add the folder to the VS Code workspace and exclude it as an analysis root.

Any option would be useful for me, but I think that it would be nice to have both options for the plugin in order to extend the usefulness for the most users possible

**Comment by DanTup** [comment]
The tree now starts one level up from where the package resolves, if the resolved folder is called "lib":

![Screenshot 2020-11-18 at 16 04 03](https://user-images.githubusercontent.com/1078012/99555012-be191180-29b7-11eb-92ec-4f20ba846680.png)
