### ISSUE TITLE
Text is getting overwritten in vscode 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Dart-Code/Dart-Code#1627]
Issue Type: <b>Bug</b>

When using autocomplete to fill in a variable or parameter name,  if there's text next to it, it seems to switch into insert mode for a second and part of the following text is overwritten. So it'll go from  ["|" indicates caret]
`myFunc(samplePa|:);`
to
`myFunc(sampleParam|:` <- notice no closing parenthesis or semicolon. 
this doesn't happen all the time, but it happens enough. May have something to do with the Flutter or Dart plugin

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0 (MacOS Mojave (10.14)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-monokai-seti|adi|0.0.5
flutter-snippets|ale|1.1.0
dart-code|Dar|2.25.0
flutter|Dar|2.25.0
bloc|Fel|0.5.0
code-runner|for|0.9.8
output-colorizer|IBM|0.1.2
intellij-idea-keybindings|k--|0.2.31
chat|kar|0.13.0
vscode-gist|ken|3.0.3
vsliveshare|ms-|1.0.45
vsliveshare-audio|ms-|0.1.48
vsliveshare-pack|ms-|0.2.12
java|red|0.42.1
git-merger|sha|0.4.1
vscodeintellicode|Vis|1.1.5
vscode-java-debug|vsc|0.17.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.6.0
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.1

(1 theme extensions excluded)

</details>

[Edit] Got it on [video](https://streamable.com/nhmp1)

**Comment by DanTup** [comment]
Hmm, this sounds a bit like #1368 that we never got to the bottom of.

If you can reliably repro, could you try capturing a log (run the **Dart: Capture Logs** command, tick only Analyzer, reproduce, then click Stop Logging in the notification - which may have collapsed into the bell icon in the bottom right).

Could you also try with other extensions, just to eliminate the possibility of something conflicting.

Thanks!

**Comment by ThinkDigitalRepair** [comment]
OK, I'll try

**Comment by ThinkDigitalRepair** [comment]
I'm not sure if this'll help, but here it goes. I was able to add it and get it to do it immediately.
[Dart-Code-Log-2019-03-06 15-48-45.txt](https://github.com/Dart-Code/Dart-Code/files/3100670/Dart-Code-Log-2019-03-06.15-48-45.txt)

**Comment by DanTup** [comment]
Aha, thanks! I think I understand what's happening now, and I think it is the same as #1368, but when I tried to reproduce I was looking at a delay in the wrong place...

Here's what the log shows:

- You typed `t` - this was sent to the server
- VS Code requested completion from the server
- You typed `i` and `m` - these were also sent to the server
- Completion results returned from the server, saying that they should replace 3 characters

This doesn't add up. It looks like the server has processed your extra key presses `i` and `m`, but as far as VS Code is concerned, the request was sent before they were typed, and therefore I believe it assumes that the results were based on only the `t` being typed. This means it added 2 characters onto the number of characters it needs to overwrite. You then type some more characters (and VS Code continues to count how many characters it needs to replace) and ultimately, commit the completion, which deletes 2 more characters than it should.

@bwilkerson @scheglov here's the interesting part of the log - note that the completion request was sent before the updateContent's, but its response came after, resulting in its `replacementLength` including additional characters that VS Code is unaware were taken into account.

```
==> {"id":"5085","method":"analysis.updateContent","params":{"files":{"/foo/state.dart":{"edits":[{"id":"","length":9,"offset":78,"replacement":"t"}],"type":"change"}}},"clientRequestTime":1555800538382}
<== {"id":"5085","result":{}}
==> {"id":"5086","method":"completion.getSuggestions","params":{"file":"/foo/state.dart","offset":79},"clientRequestTime":1555800538400}
==> {"id":"5087","method":"analysis.updateContent","params":{"files":{"/foo/state.dart":{"edits":[{"id":"","length":0,"offset":79,"replacement":"i"}],"type":"change"}}},"clientRequestTime":1555800538484}
==> {"id":"5088","method":"analysis.updateContent","params":{"files":{"/foo/state.dart":{"edits":[{"id":"","length":0,"offset":80,"replacement":"m"}],"type":"change"}}},"clientRequestTime":1555800538579}
<== {"id":"5087","result":{}}
<== {"id":"5088","result":{}}
<== {"id":"5086","result":{"id":"127"}}
<== {"event":"completion.results","params":{"id":"127","replacementOffset":78,"replacementLength":3,"results":[ // ...
```

I guess this is because the completion work is async, and the files have changed before the work is complete (or maybe even started). I'm not sure how we can fix this - really we'd want completion to be computed based on a snapshot at the time it was requested, but I don't think it's realistic to have one.

Another option may be to cancel reject completion requests if files are modified, though I'd have to do some testing to see how VS Code handles this.

Any ideas?

**Comment by bwilkerson** [comment]
> Another option may be to cancel reject completion requests if files are modified ...

That's the behavior I would have expected to have seen. Server certainly ought to be able to tell when files have changed, but perhaps it isn't capturing the analysis session at the time the completion request is received and is waiting until it starts trying to compute completions.

I'm not sure of the best solution, but server certainly can't know about additional characters typed after the suggestions were computed, so we need to deal with the fact that the replacement length might be wrong.

How does LSP deal with this?

**Comment by DanTup** [comment]
The [LSP spec](https://microsoft.github.io/language-server-protocol/specification) has a section titled "Request, Notification and Response ordering", which includes (emphasis mine):

> the server may decide to use a parallel execution strategy and may wish to return responses in a different order than the requests were received. The server may do so **as long as this reordering doesn’t affect the correctness of the responses**.

In the example above, we're essentially re-ordering the requests. The results for completion are different than if the server had processed the requests in-order because the completion takes the additional two characters into account.

Usually, clients throw away the results of any request/response that spans an edit because they could be invalid. That doesn't happen here, because the client is capable of taking simple edits into account, however that only works if the results from the server are based on the specific state at the time the request was sent (which in this case, it was not).

I'm no longer sure my earlier suggestion is so good:

> Another option may be to cancel reject completion requests if files are modified, though I'd have to do some testing to see how VS Code handles this.

If the user is typing a key every 100ms and the server is taking 101ms to respond with completions, this means they wouldn't see any completion at all until they stop typing for 101ms. Whereas if we can send the results back as VS Code expects - based on the state at the time of the request, as it we were processing all requests to completion in-order - then it can show completions from the very first keypress even if there have been many more keypresses, because it knows how to filter the list and how to adjust the edit to compensate.

**Comment by DanTup** [comment]
Based on #2480, I believe this issue doesn't occur when using the LSP protocol. I'm not sure if it's because the request order is better, or just because LSP passes version numbers around, but since the plan is to move over to LSP I don't think it's worth specifically trying to fix here (unless we think other editors may be affected, in which case we should move this to the SDK repo).

If you're seeing this issue today in VS Code, you can set `"dart.previewLsp": true` to start using the LSP version right away.

**Comment by ataberkw** [comment]
https://user-images.githubusercontent.com/10375421/134074841-f0ac0ab9-528d-4055-88ac-da17a41eed91.mov

set dart.previewLSP to true but it still occurs on my VSCode. I can't type code rapidly.

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-arm, locale en-TR)
    • Flutter version 2.5.0 at /Users/ataberkw/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (13 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ataberkw/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.56.2)
    • VS Code at /Users/ataberkw/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.
```

**Comment by ataberkw** [comment]
> Based on #2480, I believe this issue doesn't occur when using the LSP protocol. I'm not sure if it's because the request order is better, or just because LSP passes version numbers around, but since the plan is to move over to LSP I don't think it's worth specifically trying to fix here (unless we think other editors may be affected, in which case we should move this to the SDK repo).
> 
> If you're seeing this issue today in VS Code, you can set `"dart.previewLsp": true` to start using the LSP version right away.

https://user-images.githubusercontent.com/10375421/134074841-f0ac0ab9-528d-4055-88ac-da17a41eed91.mov

set dart.previewLSP to true but it still occurs on my VSCode. I can't type code rapidly.

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-arm, locale en-TR)
    • Flutter version 2.5.0 at /Users/ataberkw/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (13 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ataberkw/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.56.2)
    • VS Code at /Users/ataberkw/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 93.0.4577.82

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment]
@ataberkw could you file a new issue for this and include:

- A list of all extensions you have installed in VS Code
- A log file captured with the **Dart: Capture Analysis Server Logs** command (run the command, then type to reproduce the issue, then click **Cancel** on the logging notification to stop logging)

The log file will include parts of your source code, so I would recommend reproducing it on a small sample project (and only capturing a short period around the typing to reproduce the issue). Thanks!
