### ISSUE TITLE
Extract analyzer bindings to separate repo

### ISSUE THREAD

**Issue by Aetet** [Dart-Code/Dart-Code#1641]
Hi.
Is it possible to extract analyzer binding for typescript to separate repo?

I want to make some tooling for my ts project.
https://github.com/Dart-Code/Dart-Code/tree/master/src/analysis is exactly what I need.

Is there any plans for it?

**Comment by DanTup** [comment]
Some of the stuff in there is pretty specific to Dart Code's needs - for example in the analyzer file:

https://github.com/Dart-Code/Dart-Code/blob/master/src/analysis/analyzer.ts#L18

I think extracting all of that to another repo and referencing it from there would tie my hands a little (I'd have to be careful not to make breaking changes, etc.), so I think a better option (assuming you don't want to just copy/paste the required files) might be to share the code-gen scripts for it. The generator for the classes is already here:

https://github.com/Dart-Code/analysis-server-typescript-generator

However the generator for the class that has all the registration methods is in C# on my PC somewhere (I've just been hand-editing it recently since the changes were minor). I really need to tidy that up and port it to Dart into that repo - then I think you could just use them (and you'd be in control of the version of the spec to use, etc.).

**Comment by Aetet** [comment]
Would be great if you share analysis server snippet.

**Comment by Aetet** [comment]
@DanTup I want to integrate dart code analysis with https://about.sourcegraph.com/
Make extension to search all other our codebase with intellisense.

**Comment by DanTup** [comment]
Apologies - this has been sat at top of my inbox for a while, but I just haven't gotten around to it. If it's blocking you, I would recommend just copy/pasting/tweaking the files for now, and you can update them later. The spec doesn't change a lot so I suspect you won't need updates very often.

**Comment by Aetet** [comment]
Ok. That's not a problem. Thanks a lot for all your work. I use Vs Code with Dart a lot and it works really great.

**Comment by DanTup** [comment]
Sorry for leaving this around for so long - these bindings will no longer be maintained as the extension is moving over to [using LSP](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md).

If you still need these, I would recommend taking a copy of them and using http://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html as a reference if you need to update them in the future.

If there's any value in the https://github.com/Dart-Code/analysis-server-typescript-generator repo, you may also wish to fork it - as it may be removed once it's no longer being used/maintained here.
