### ISSUE TITLE
Target of URI doesn't exist

### ISSUE THREAD

**Issue by Yeikel200** [Dart-Code/Dart-Code#1642]
Issue Type: <b>Bug</b>

When adding a new dependency to my pubspec.yaml, it does not give me any error in that task, but the changes do not apply, and therefore when placing the amount of the package it tells me that it does not exist. When closing the editor and opening it, the problem is solved, but it is very annoying to be closing it every time I have to add a dependency to my project.

Extension version: 2.25.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  J1800  @ 2.41GHz (2 x 2417)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.88GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DanTup** [comment]
Thanks for the report! This is an issue in the analysis server and there's an open issue here you can subscribe to for updates:

https://github.com/dart-lang/sdk/issues/30845

Once it's fixed in the analysis server, you'll get the fix once you update to the Dart/Flutter SDK with the fix in it - there's nothing required from the VS Code extension.

Thanks!
