### ISSUE TITLE
Flutter Widget Editor Enhancement: Highlight Widget and Children. Ability to delete.

### ISSUE THREAD

**Issue by wyattbiker** [Dart-Code/Dart-Code#1647]
I would like to be able to delete the widget cursor is on, but also the child code/contents. I cannot find a way to do that.

Is there a way to click on a widget and highlight it and contents, then delete it using Delete key maybe?

Also, why does **Remove Widget** menu choice, sometimes show up and sometimes it not, when on a Widget and I click Show Fixes icon menu. (E.g. Icon or Container)

Thanks!

**Comment by DanTup** [comment]
Thanks for the suggestion! The quick-fixes are actually provided by the SDK, so this request is best raised over at https://github.com/dart-lang/sdk/issues.

As for the conditions for **Remove Widget** to appear, I'm not exactly sure. @scheglov may be best able to answer that.

**Comment by scheglov** [comment]
I would be easier to answer the question about `Remove Widget` if it had been concrete. One example when it is not possible to "remove" widget (actually it might be better to call "inline" or "replace with children") is when the widget being removed has multiple children, but the target it not a list.

```dart
import 'package:flutter/material.dart';
main() {
  Center(
    child: /*caret*/Row(
      children: [
        Text('aaa'),
        Text('bbb'),
      ],
    ),
  );
}
```

+1 to opening feature requests in Dart SDK for quick assists that you would find useful.

**Comment by DanTup** [comment]
> One example when it is not possible to "remove" widget (actually it might be better to call "inline" or "replace with children") 

Aha, got it, I understand now :-)

@wyattbiker does this answer your question? If not, please provide a concrete example of where it doesn't appear but you expected.

Also, please open an issue at https://github.com/dart-lang/sdk/issues with the request for the "remove with children" assist since that's where it'll need to be implemented. VS Code automatically shows all the assists from the server, so there's no additional work here to surface it if it was implemented.

Thanks!

**Comment by wyattbiker** [comment]
Well it seems that if the widget is not a wrapper around another widget it cannot be removed. I can remove `Center(),` but cannot remove `Row()` nor `Text()`. Maybe what I am looking for is a delete widget and everything it wraps around. I will post in the sdk forums. Thanks!

```
Center(
    child: /*caret*/Row(
      children: [
        Text('aaa'),
        Text('bbb'),
      ],
    ),
);
```

**Comment by DanTup** [comment]
Based on @scheglov's comment, I think the reason you can't remove `Row()` is that it has two children, and they don't fit in the single-child of `Center` (the behaviour of remove is to take that widget our of the tree, but keep the children).

Of course, if you want to remove the row and it's children, that's a valid request for another assist to open in the SDK repo as discussed :)

**Comment by wyattbiker** [comment]
Just a curiosity question. Why does this request belong in the dart sdk issues instead of Dart VS Code? Is it because the Dart Server needs to provide a widget/children API to remove it?

Another question: I had noticed that the help tooltip over a widget, showed the complete highlighted widget including the children. Could that similar code be used to instead highlight the text, and then press Delete key to remove a widget/children.

See screenshot below (an older version of the plugin before it was fixed it using a workaround :) )

![Screen Shot 2019-03-27 at 2 07 47 PM](https://user-images.githubusercontent.com/930478/57046252-ddb5e100-6c3d-11e9-804d-15636dfda341.png)

Thanks again.

**Comment by DanTup** [comment]
> Just a curiosity question. Why does this request belong in the dart sdk issues instead of Dart VS Code? Is it because the Dart Server needs to provide a widget/children API to remove it?

It's because the VS Code extension doesn't actually understand the Dart language itself. Instead, it runs a Dart program that's included in the SDK ("the analysis server") in the background and that does all of the language parsing and analysis, and provides the results to VS Code. When we need something like a list of quick fixes/assists, we send that request on to the server and it gives us the options to display, and the edits we should make to the files to apply them.

This way, VS Code doesn't need to track all the different versions of Dart as the language evolves, since the heavy lifting is all done by the same SDK you're running with. It also means that lots of this work is shared across the different tools (VS Code, IntelliJ, Android Studio, the command line analyzer and even DartPad).

It's actually a pretty common model - there's now a common protocol that's been gaining traction named ["the language server protocol"](https://microsoft.github.io/language-server-protocol/) which aims to reduce the effort to wire a language up to an editor by making these things consistent.

> I had noticed that the help tooltip over a widget, showed the complete highlighted widget including the children. Could that similar code be used to instead highlight the text, and then press Delete key to remove a widget/children.

It's possible we could implement it using this data, but it would be more fragile. What's happening here is that when you hover your mouse somewhere, VS Code asks us for a tooltip, and we send a request back to the analysis server asking for the contents. With its response, it returns a range of code that it applies to. We don't really know that this is a widget, so it'd be hard to reliably show a "Remove Widget + Children" assist in the right place, and we might also have to make assumptions about things like the following comma or leading `new`/`const` to leave the code correct. Generally we try  to avoid doing anything of this nature in the editor (things which make change/break with language changes) and do them in the server (which also means all the other editors get them too :-)).

> See screenshot below 

Hah, as I was typing this I was thinking "hangon, this is a bug I fixed?!" Glad you clarified, I was about to start digging through code :-)

Hope this all makes sense!
