### ISSUE TITLE
Dart Dev Tools open in default browser, should open Chrome instead

### ISSUE THREAD

**Issue by lenaschimmel** [Dart-Code/Dart-Code#1681]
Currently, the Dart Dev Tools are opened in the system's default browser.

Since the Dart Dev Tools only work inside the Chrome browser, the Dart extension should always launch Chrome, even if the system's default browser is not Chrome.

Alternatively, there should be a setting to select the browser to open the Dart Dev Tools. This would be useful if a user has multiple compatible browsers (like Chrome and Chromium) or use extensions to show web pages inside vscode (currently, the only known extension, [browser-tab](https://github.com/DizoftTeam/browser-tab), is not suited to display the Dart Dev Tools).

**Comment by DanTup** [comment]
> the Dart extension should always launch Chrome, even if the system's default browser is not Chrome.

This work has been done (see #1505) and was intended to ship in the last version, but was delayed due to a bug. Everything has been resolved now and I expect this to ship in a patch this week. Sorry for the inconvenience!

>  or use extensions to show web pages inside vscode

This is something we've experimented a little with, but there are some restrictions on running arbitrary web pages inside Code (as well as some annoyances, like not being able to drag tabs out into other windows). There's an issue open at #1488 for these investigations.

**Comment by edgarfroes** [comment]
So... DevTools now works in safari, I haven't tested other browsers, but should we reconsiderar reverting this to what it was before?

**Comment by DanTup** [comment]
@edgarfroes there's now a setting to control this (see https://dartcode.org/releases/v3-15/#devtools). Default is still Chrome as that still currently has the best experience, but you can change it to always use the default browser if you'd prefer.

**Comment by yguel** [comment]
On version from: 11/1/2021, 17:30:05, with vscode 1.62.3-1637137107 on linux.
The option: Dart: Dev Tools Browser even set to "chrome" launch the default browser. In my case firefox.

**Comment by DanTup** [comment]
@yguel if something isn't working, please [file a new Issue](https://github.com/Dart-Code/Dart-Code/issues/new?labels=is+bug&template=bug_report.md) rather than commenting on a Closed issue.

When Dart-Code falls back to the default browser, it should show a message "Dart DevTools was unable to launch Chrome so your default browser was launched instead" with a "Show Full Error" button. Please click "Show Full Error" and include that log in the new Issue you open. Thanks!
