### ISSUE TITLE
Allow dart syntax highlighting theming

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#1688]
In IntelliJ, you can theme local variables, instance variables, static variables, function params etc etc all differently. 

May be a dupe or may not be supported at all in vscode.

**Comment by DanTup** [comment]
Our syntax highlighting is all regex-based using a TextMate grammar (https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json) so I don't think this is currently possible (it's also why we have strange quirks like #311) until VS Code gets an API for better colouring (https://github.com/Microsoft/vscode/issues/585).

**Comment by DanTup** [comment]
Fixed by the semantic token work in https://github.com/dart-lang/sdk/commit/cb2ede57b7c91fb61c0cb05971cc1823faee2086.

In order to get the fix you'll need Dart-Code v3.18.0 (a preview release should be available later today/tomorrow), be using LSP Preview, and have a Dart SDK from after yesterday ([the most recent nightly](http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/) works, and of course the next releases of Dart/Flutter SDKs will include this).

You can then use a theme that colours semantic tokens, or set them up in your own settings. For example, this sets static variables/properties to be rendered red:

<img width="1133" alt="Screenshot 2020-12-15 at 12 09 20" src="https://user-images.githubusercontent.com/1078012/102213287-6db9a480-3ece-11eb-899a-36c45a2b0651.png">

**Comment by DanTup** [comment]
Due to some last minute issues, support for LSP 3.16 (which supports semantic tokens) won't be included in v3.18, but hopefully v3.19 next month instead.
