### ISSUE TITLE
Dart plugin enabling itself

### ISSUE THREAD

**Issue by raggi** [Dart-Code/Dart-Code#1695]
I work on Fuchsia and regularly operate in a workspace that has the entire Fuchsia tree in view. This tree is extremely large, as such, it is prohibitive to have the Dart plugin enabled (dart analysis uses 10GB of ram generally before I notice what it's doing as my laptop is grinding to a halt).

I disable the Dart plugin in this workspace.

For some reason, the Dart plugin gets regularly re-enabled - it seems to be related to updates. I also have the Flutter plugin, which is also disabled in this workspace and seems to stay disabled.

I really need for these plugins to stay disabled in this workspace, or have some other mechanism that is more reliable to significantly limit the resources they use in such an environment. For now I've had to uninstall both extensions, as the failure mode is sufficiently damaging that I am better off without them being present - but I'd love to get them back!

**Comment by DanTup** [comment]
I can imagine this is frustrating - though I'm not sure it's a bug in the extension. If the extension is disabled, in theory no code is running, so it shouldn't be able to re-enable itself :/

This came up yesterday in #1690 so I'll close this one as a dupe. I have also opened an issue with VS Code though, since this feels like a bug there:

https://github.com/microsoft/vscode/issues/73484

By the way, you might also want to check out [dart.analysisExcludedFolders](https://dartcode.org/docs/settings/#dartanalysisexcludedfolders) - you may be able to exclude parts of the tree that are eating the most resources without having to entirely disable it for the workspace.

Also, if you can give me instructions on how to get to the point I can repro this (I've cloned Fuchsia before and run some builds, but mostly copy/pasting instructions I was sent, I'm not very familiar with it) I can see if there is any obvious low-hanging-fruit to improving performance. You can email me (dantup@) or grab me on Hangouts/Chat (during UK office hours-ish :-)) if that's easier.

**Comment by raggi** [comment]
Thanks for the prompt response. This all seems super reasonable. I'll follow the vscode bug :)

**Comment by raggi** [comment]
Regarding repro - I'm not quite sure how to do that, as I don't really have a good way to detect when this happens. I can state the following with confidence:
 - I have disabled the plugin repeatedly
 - I am using the same workspace (there are many other settings in the workspace that have obvious side effects if they're missing)
 - I observe the plugin turning on again even without restarting vscode or reopening the workspace
 - I observe the plugin turning on again even without opening a dart file

As far as the source tree, there's not anything particularly special - it's a clone as described here: https://fuchsia.googlesource.com/fuchsia/+/master/docs/development/source_code/README.md and the other settings of relevance are:
 - git.enabled: false - too slow on trees this size
 - files.exclude covers out/ where builds are produced
 - watcherexclude also covers out/
 - I do have dart.sdkPath pointing at ${workspaceFolder}/third_party/dart/tools/sdks/dart-sdk

**Comment by DanTup** [comment]
Sorry, when I said I'd try to repro, I meant the "plugin eats all the resources" issue rather than the re-enabled extension. It'd be nice if you didn't have to lose all functionality for the whole workspace so I wonder if there's anything that might be contributing more than it's fair share to the performance issue (for example, if scanning a build output folder is expensive and provides little value, it could be excluded - though I see you have `out` excluded).

I'll see if I can repro and maybe get some profiling info.

FWIW, you might not need the custom `dart.sdkPath` as that path is already in our search list (though there's a topaz one above it that might be selected first):

https://github.com/Dart-Code/Dart-Code/blob/3557eafd52032fce92b25339c65ebd085e4200c8/src/sdk/utils.ts#L244

**Comment by DanTup** [comment]
FWIW, looks like the VS Code issue is fixed for the next release (which I suspect is this week or next?)

https://github.com/microsoft/vscode/issues/71752

**Comment by DanTup** [comment]
I'm not sure I have all the same build directories etc. (I have 18k+ errors reported!) but analysis was **significantly** faster when I added this to my settings:

```js
"dart.analysisExcludedFolders": [
	"out",
	"prebuilt",
	"third_party",
	"topaz/tools/prebuilt-dart-sdk",
]
```

I deleted `~/.dartServer` then opened the repo without, and after 10 minutes I had to kill it (my mac MacBook was going crazy). Then I deleted `~/.dartServer` again (to ensure no cached results) and added the above to my workspace settings, then tried again. Took 28 seconds to complete analysis. The server was also only using 426MB (according to `code --status`). There are still tons of reported errors though, so I'm not sure I've got everything set up correctly.

I don't know if it's valid to exclude all of those, but you might want to play around with it. You could also add them to your global settings (they'll apply as relative paths to the current workspace) or even commit them to `.vscode/settings.json` in the Fuchsia tree if they make sense for everyone to have.

**Comment by DanTup** [comment]
@bwilkerson I'm working through some of the things that don't work in LSP, and this is one. Looking back, I'm not sure how this setting (which basically passes through to `excluded` in `setAnalysisRoots`) is different to listing `exclude` in `analysis_options` (does that only prevent sending errors, or would it also prevent the folders being scanned)?

We could support this in LSP too (we now have support for settings), but it probably doesn't make sense if it significantly overlaps with existing functionality.

If `exclude` in `analysis_options` *should* do this, but doesn't because of bugs, it might be better for me to try and work through them than implement this.

Otherwise, if that serves a different purpose and you think having a client-side editor setting like this makes sense, I can update the LSP server to support it.

**Comment by bwilkerson** [comment]
> I'm not sure how this setting (which basically passes through to `excluded` in `setAnalysisRoots`) is different to listing `exclude` in `analysis_options` (does that only prevent sending errors, or would it also prevent the folders being scanned)?

The two ways of excluding files should work the same way. We provide a way to exclude files in the analysis options file because that file can be committed to the repository and shared by all developers no matter which client they're using. The field in `setAnalysisRoots` exists to support any kind of client-specific filtering that might already exist (IntelliJ, for example, supports filtering files and directories via their UI, but only other IntelliJ users can share those settings).

I'd guess that providing support in LSP would not make sense. If LSP wanted to support a way for clients to exclude files from analysis they'd likely have included an explicit protocol for doing so.

As for the semantics of excluding a file, it is intended to mean that the file will not be analyzed unless doing so is required in order to analyze a non-excluded file, and that diagnostics will not be sent whether the file is analyzed or not. If an excluded file is ever sent as a priority file (opened in the editor), then server will analyze it in order to provide support in that file (highlighting, outlines, code completion, etc.). At one point we decided to also send diagnostics at that point so that users could see any issues in a file, but a bug caused us to not clear those diagnostics when the file ceased to be a priority file. I don't remember whether that bug still exists, but I do remember that one proposal for how to fix the bug was to never send diagnostics for an excluded file.

**Comment by DanTup** [comment]
Ok cool, sounds like the analysis_options setting should work. My understanding of the original issue here (and that led to the setting being added) was having a lot of Dart buried somewhere in the tree and not wanting to read it (for performance reasons), but the files would *not* be opened in the editor.

I'll do some testing and if it seems to work like that, I'll deprecate this setting (and otherwise, I'll try to track down why it's failing). Thanks!
