### ISSUE TITLE
dart.env isn't applying unless config is reloaded

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1725]
Think I broke this in b2a879611fa0404e1b635138bbd132e7ab7a8f82 because `setupToolEnv` is no longer called automatically (FYI @stuartmorgan - I think you may have mentioned this to me, but somehow I lost the report, and just re-discovered it today!).

**Comment by stuartmorgan** [comment]
I'm actually seeing it not work at all on a second machine. I was going to follow up and see if maybe the reason I was seeing inconsistent behavior (which is why I hadn't filed the issue original; when I retested at the time it worked on three machines I tried and only failed on one) was due to versions, and the working machines weren't quite as up-to-date.

Recently the only way I can seem to make the flow work is to command-line launch VS Code from a terminal that sets the environment variable.

**Comment by DanTup** [comment]
The bug I introduced basically means it'll only work if your trigger a config reload (which usually means changing your config, either directly, or by using something like the SDK switching).

I've pushed a fix - if it's annoying that it's broken, lmk and I'll send you build with it in (or if you have `vsce` installed you can run `vsce package` to build your own).

**Comment by stuartmorgan** [comment]
Oh, I see what you mean by 'reloaded' now. I was thinking 'relaunched', but this would actually be the opposite.

That definitely explains why I couldn't repro it when I specifically went and set it up on a new machine to see if it was really broken :)
