### ISSUE TITLE
Double folder arrow in Dependencies view with some themes

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#1736]
Happens for example with "Monokai Classic Icons":

<img width="270" alt="Screen Shot 2019-05-22 at 11 44 19" src="https://user-images.githubusercontent.com/96958/58164872-f2a6f280-7c86-11e9-9c4e-45167b564381.png">

**Comment by DanTup** [comment]
Thanks for the report! This looks like a bug in the theme - they need to indicate to VS Code that their icons represent the expand/collapse state so that VS Code will no render its own.

Info about this is here:

https://code.visualstudio.com/api/extension-guides/icon-theme#folder-icons-in-file-icon-themes

If you open an issue against the theme repo and include that link, I think it should be a straight forward fix for them.

Thanks!
