### ISSUE TITLE
Code completion doesn't trigger automatically for import snippets

### ISSUE THREAD

**Issue by tensor-programming** [Dart-Code/Dart-Code#1775]
Currently on `Flutter 1.6.7` the dev branch, and working with the dart-code plugin in vscode gives me fairly unresponsive import auto-completions.   What I mean by this prior to the update, I could start to type `import 'material'` and it would suggest `import 'package:flutter/material.dart'` and this would work for most imports.  For core dart libraries, I would type say `convert` and it would suggest `dart:convert` etc.  Now, I have to type in much more of the package to get the auto-completion.  With libraries like `dart:convert` or `dart:isolate`; I am often finding myself having to type in the complete import statement and some times I don't even receive auto-completion suggestions. 

This feels like it is related to #1723 in someways.  Almost like the fix for that issue caused there to be less suggestions.

**Comment by DanTup** [comment]
@tensor-programming Are you able to provide a screenshot of an example where this is happening? And also could you check whether the items might just be further down the list? My guess is that this is https://github.com/Dart-Code/Dart-Code/issues/1742, since the list isn't updating as you type normally (we give the full list to VS Code and it just filters them as you type), so if they show up at all, they're probably in the list somewhere.

**Comment by tensor-programming** [comment]
Its not that the suggestions are out of order because there are no suggestions in most cases.  I have to either manually hit `ctrl+space` or type until I hit some kind of special character like a `/` or a `.`. Where as before, I could start to just type the word `material`, now I have to type `material/` before I see any suggestions.  With core dart libraries like `dart:isolate`, used to be that I could just type `isolate` and get the suggestion.  Now there are none unless I hit `ctrl+space`. 

I made a quick video showing the problem (Ill add a link to the issue once its done rendering).

**Comment by DanTup** [comment]
@tensor-programming thanks for the excellent video (again), I understand what you mean now. The problem doesn't seem to be related to the contents of the completion, but rather then it's being automatically triggered. There are a few moving parts to making this work - we tell VS Code which keys should trigger it, but then we have to filter them (for example typing `import '` should trigger on the apostrophe, but typing `var foo = '` should not). I think we also have special handling for the `import '';` snippet because in that case you didn't type the apostrophe, but you still want it to auto-trigger.

Nothing here should have changed, but since the auto-import-completion changes were quite significant, something may have been lost in that work.

Btw, can you confirm you're on VS Code stable (1.34) and same for Dart/Flutter plugins (v3.1.0)?

Thanks!

**Comment by DanTup** [comment]
Ok, so I can repro this on the Flutter `dev` channel. When it occurs, I see an error in the dev tools which seems to be the same as https://github.com/dart-lang/sdk/issues/37129.

Looks like it's been fixed since, so I'll see whether it's made `master` and if so which version it's in.

**Comment by DanTup** [comment]
Yep, the fix seems to have made it to master (currently `v1.7.1-pre.52`) and I can't reproduce your issue there. For now the options are either to run on `master` until it makes it to `dev`, or try switching to a channel with an older build (like `beta` or `stable`).

If you still have issues on those, let me know and I'll dig further. Thanks!

**Comment by tensor-programming** [comment]
Thank you for clearing this up so quickly.  Yes I am on VS Code stable and on the latest dart code toolset.  As you mentioned also on flutter dev.

**Comment by DanTup** [comment]
Looks like the fix rolled into dev yesterday (v1.7.1), I can't repro on dev anymore :-)
