### ISSUE TITLE
Attempt to auto-complete on Widget type below a method that returns List<Widget> inserts "prefix0.Widget" and creates unnecessary import

### ISSUE THREAD

**Issue by JajaHarris** [Dart-Code/Dart-Code#1782]
[Dart-Code-Log-2019-05-04.11-08-05.txt](https://github.com/Dart-Code/Dart-Code/files/3263111/Dart-Code-Log-2019-05-04.11-08-05.txt)
Appears the auto-complete logic for Widget fails when preceded by a method whose return type is `List<Widget>` and the method attempting to be defined is also followed by a method that returns Widget.

So some examples:

```
class LoginPage extends StatefulWidget {
   //assume you need to define a method with following signature: Widget method1() 
  
  //attempting to define method1 here BEFORE method2 works fine; auto-complete on Widget works as expected
 
  List<Widget> method2() {}

  //attempting to define method1() AFTER method2() but BEFORE method3() will cause auto-complete to fail on Widget type.  
  //prefix0.Widget displays in the auto-complete drop-down and is what gets inserted in the editor.

  prefix0.Widget 
  //Also an import is created that looks like: import 'package:flutter/material.dart' as prefix0;

  Widget method3() {}
}
```

Also noticed that If method3() does not exist then auto-complete on Widget AFTER method2() will work as expected.  Auto-complete only fails when attempting to define method1() between method2() and method3().

Moral of story: never return `List<Widget>` :-)

**Comment by DanTup** [comment]
I believe this is https://github.com/dart-lang/sdk/issues/36890 which has been fixed in Dart (so should be fixed in the next version of Flutter). You could try switching to the `beta` branch temporarily to confirm it's fixed, and if not let me know. Thanks!

**Comment by nbros** [comment]
I have this bug with Flutter v1.7.8+hotfix.4 with Dart 2.4.0 in Visual Studio Code 1.37.1 (these are all the latest stable versions). 
Is it supposed to be fixed in that version?

Use this Dart file to reproduce: on line 28 type "final Set<WordPair" and then Tab :
[main.dart.txt](https://github.com/Dart-Code/Dart-Code/files/3517080/main.dart.txt)
(this is a simple Flutter project with just this Dart file)

![image](https://user-images.githubusercontent.com/141089/63288272-915de200-c2bc-11e9-9367-db3e256d58d6.png)

It adds this duplicated import:
![image](https://user-images.githubusercontent.com/141089/63288323-afc3dd80-c2bc-11e9-8ea8-42e38d0028af.png)

And completes with this "prefix0":
![image](https://user-images.githubusercontent.com/141089/63288301-a0449480-c2bc-11e9-8c78-d3e6c9d92b05.png)
