### ISSUE TITLE
Remove preview flag

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#179]
https://github.com/Dart-Code/Dart-Code/blob/master/package.json#L7

Dart-Code is pretty far along :)

**Comment by DanTup** [comment]
I was gonna remove that for v1. My plan is for v1 to not having anything "obvious" missing - I don't want people to install it and then think "this is good but it's missing {important thing} my current editor supports" and defect back! :D

Some things I'm hoping to include for v1:

- Some sort of web story (F5 to launch a browser)
- Signature Help (this is most likely to slip as required an analysis server dev)
- Support debugging in terminal (or even better, user code between integrated terminal, external terminal, debug output)
- Also wait for all significant SDK/Code bugs I've raised to be available in stable

Things may change; I'll see where we are in next week or so. Dart 1.20 has some important fixes (like AS crash on typing "con" in an import) so will probably wait to that ships at least!

**Comment by DanTup** [comment]
Ok, I've been through the list of cases and changed milestone around as follows:

- No milestone - not a requirement for v1, but may try to do these anyway
- v1 - things that I think are important for v1 (however, many require changes in Dart SDK or Code, so these may change)
- Post-v1 - things I think we shouldn't try to get into v1 (or just won't be able to due to external deps)

Keeping this case around as a reminder to remove the preview tag. I was going to do this for v1, though I'm not really sure if having it marked preview is adding anything.

**Comment by DanTup** [comment]
I still think there's stuff to include for "v1", but since this came up again (someone told me the Preview tag shown against Dart Code vs the other Dart extension showing "Free" made this look non-free) I have removed the preview flag. Even though there are missing features, I think the stability is decent :-)
