### ISSUE TITLE
Same name is visible for all emulators.

### ISSUE THREAD

**Issue by TheHemantKaushik** [Dart-Code/Dart-Code#1812]
Issue Type: <b>Bug</b>

Create 2 Android emulators and tap the emulator name shown in the status bar on right corner to choose emulator. Both emulators are visible with same techincal name.

Extension version: 3.1.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (2.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

![image](https://user-images.githubusercontent.com/28451375/59903007-75090a80-941d-11e9-8aa9-b24ec4a18cd3.png)

**Comment by DanTup** [comment]
Thanks for the report. This is unfortunately an issue that needs solving in Flutter (since the names here come from the same place as the output you see in running `flutter devices`).

There's already an open issue that I think covers it:

https://github.com/flutter/flutter/issues/11850

I've recently made some changes that might be a step towards this (collecting emulator IDs for running devices) so subscribe to that issue for updates.
