### ISSUE TITLE
Be able to switch out of Flutter mode into Dart mode

### ISSUE THREAD

**Issue by dcharkes** [Dart-Code/Dart-Code#1828]
> This is expected right now. When deciding whether to load the Flutter SDK or Dart SDK, we look two levels down to see if there's a Flutter project, and if not, we go into "Dart Mode".
> 
> If you can't open a folder closer to the apps, the best current fix is to click File -> Add Folder to Workspace and then select your app1/app2 folders which will show them in the Explorer tree as "Workspace Folders". Unfortunately, this means they will appear in two places in the tree - there is a request to fix that in VS Code at https://github.com/Microsoft/vscode/issues/45470 (please add a 👍 ).
> 
> We could scan further down the tree looking for Flutter projects at startup, but it would slow down startup (significantly for those opening large trees) and doing it this way also prevents you from having your own settings/launch configs within each of the apps folders.

_Originally posted by @DanTup in https://github.com/Dart-Code/Dart-Code/issues/1549#issuecomment-475143791_

I want it the other way around: I'd like to select "Dart Mode", even if I have a folder with a Flutter project added to the workspace.

P.S. It would also be nice if the settings `sdkPaths` and `flutterSdkPaths` would mention that they don't show up if the editor is in the other mode.

**Comment by DanTup** [comment]
> I want it the other way around: I'd like to select "Dart Mode", even if I have a folder opened if there is a folder with a Flutter project added to the workspace.

What's the reason for this? There are two similar things here, one is whether we show things like the devices in the status bar, and one whether we prefer a Dart SDK from Flutter or not (they're usually the same, but for the forked Flutter web support I think we take the Flutter version of the Dart SDK but don't show things like the device info). It's not clear which it is you need.

I have considered adding a workspace-setting to force a particular mode but I suspect once added, it'll end up used a lot of the time where it would've been better to instead improve our heuristic for deciding which mode to use (and therefore we'll never get this info).


> It would also be nice if the settings `sdkPaths` and `flutterSdkPaths` would mention that they don't show up if the editor is in the other mode.

It's not clear what you mean by "don't show up". They should always show in the settings UI.. Do you mean that they won't be used?

**Comment by dcharkes** [comment]
I'm a Dart VM developer, so usually I want to work with my own locally built version of Dart (dart executable, dartanalyzer executable, etc.) Every once in a while I have fix errors with Dart rolling into Flutter, so I build Flutter engine locally (with a specific version of Dart rolled into it).

```json
    "dart.sdkPaths": [
        "/usr/local/google/home/dacoharkes/dart-sdk/sdk/out/DebugX64/"
    ],
    "dart.flutterSdkPaths": [
        "/usr/local/google/home/dacoharkes/flt/engine/flutter"
    ],
```

> It's not clear what you mean by "don't show up". 

I'd like to be able to click `Dart: 2.5.0-edge.xxxx` in the bottom and switch to `Flutter 1.7.4-pre.87` (I haven't built Flutter recently). But in Dart mode, only the Dart sdk shows up, and in Flutter mode only the Flutter sdk shows up.

> I have considered adding a workspace-setting to force a particular mode but I suspect once added, it'll end up used a lot of the time where it would've been better to instead improve our heuristic for deciding which mode to use (and therefore we'll never get this info).

As a Dart VM dev, my use case is not very common I would think. So, I agree with you that in general a good heuristic might be better. I guess opening and closing the Flutter project folders in my VSCode workspace could be a practical workaround.

**Comment by DanTup** [comment]
> Every once in a while I have fix errors with Dart rolling into Flutter, so I build Flutter engine locally (with a specific version of Dart rolled into it).

I'm not familiar with this workflow so sorry for all the questions (the better I understand, hopefully the better the solution will be!). When you do this, what do you end up with on disk? I'm guessing it's not a full Flutter SDK folder with your specific Dart SDK inside it (otherwise setting `flutterSdkPath` should just work?).

> I'd like to be able to click Dart: 2.5.0-edge.xxxx in the bottom and switch to Flutter 1.7.4-pre.87 (I haven't built Flutter recently). But in Dart mode, only the Dart sdk shows up, and in Flutter mode only the Flutter sdk shows up.

Got it - you mean in the SDK picklist (not many people seem to use that so it doesn't come up much). Right now we assume in Flutter mode you'd want to change the Flutter SDK and that the correct Dart SDK is always inside it. We actually used to support changing the Dart SDK independently, but it was a shared setting with non-Flutter projects, so users would often set the Dart SDK path (to a non-Flutter Dart SDK) when working on a standard Dart project, then switch to Flutter and we'd use the same one (resulting in errors importing `dart:ui`).

We could support this again, but use a flutter-specific setting (like `flutterDartSdkPath`), though it'd be good to understand the layout better in case there's a better way.

> As a Dart VM dev, my use case is not very common I would think.

That maybe true, but it often bugs me when the Dart tooling doesn't work properly for its own devs (for ex. I can't use the test runner/code-lens when working on the analysis server tests!) so if it's simple to support and has no negative side-effects I think it's worth considering.

**Comment by dcharkes** [comment]
>  I'm guessing it's not a full Flutter SDK folder with your specific Dart SDK inside it (otherwise setting flutterSdkPath should just work?).

The Dart SDK I build multiple times a day, so it's always tip of master branch. The Dart version inside the Flutter SDK I build maybe once a month (Fully building Flutter takes quite a bit longer). So the Dart version inside the Flutter SDK is often outdated compared to the Dart SDK.

This means if I just browse Dart programs in the tip of the master branch it will cause analyzer errors with the older version of Dart inside the Flutter SDK. It does not support certain language features or standard library functions, etc.

However, I've also got some folders with Flutter apps in my VSCode workspace. The opened folder structure in my VSCode workspace looks like the following:

* Dart-sdk
* Dart-app1
* Dart-app2
* Dart-lib1
* Dart-lib2
* Flutter-app1
* Flutter-app2

So when I actually browse files in one of the Flutter-app* folders, I would switch the Flutter SDK. But when I browse one of the Dart-* folders I would switch to the Dart SDK. (And then there might be some very rare cases in which there are non-Flutter Dart files in Flutter apps and I want to use the Dart SDK to analyze those.)

My current workaround is that I remove the Flutter-app* folders from my VSCode workspace and restart VSCode to browse in Dart SDK mode. And when I want to browse a Flutter-app* with the Flutter SDK, I add the folder again to the workspace and restart VSCode.

So for my use case, maybe the mode should depend on the folder the file is in I'm currently browsing? (That only excludes the very uncommon use case where there is a small Dart-lib inside a Flutter-app folder that I'm using the newest Dart features with. But then I'll not to update the Dart in the Flutter SDK anyway to be able to build the full Flutter app.)

**Comment by DanTup** [comment]
Ok, I think I got it :-)

Forcing a Dart SDK that's not from a Flutter shouldn't be a big change. The nicest way would probably be to split Dart/Flutter in the status bar so that you can toggle their SDKs independently - though since for normal users this may be confusing, we could make it a setting (by default it'd only show the Flutter one for Flutter projects and the setting would just prevent hiding it). However - it doesn't seem like an ideal solution as you'll get lots of errors in the Problems list for the Flutter projects (and while you can ignore them, it'd be nice to have a less janky solution).

> My current workaround is that I remove the Flutter-app* folders from my VSCode workspace and restart VSCode to browse in Dart SDK mode. And when I want to browse a Flutter-app* with the Flutter SDK, I add the folder again to the workspace and restart VSCode.

Are you doing this by moving folders or using multi-root workspaces? If you use multi-root workspaces, you could have two `.code-workspace` files - one that has all those folders in, and one that has allt he non-Flutter ones. You could very easily swap between them (File -> Open Workspace), and this is how I work on the Flutter SDK and Dart SDK (eg. to only open the packages I'm working on, to reduce the work the analysis server is doing).

**Comment by dcharkes** [comment]
> Are you doing this by moving folders or using multi-root workspaces? If you use multi-root workspaces, you could have two .code-workspace files - one that has all those folders in, and one that has allt he non-Flutter ones. You could very easily swap between them (File -> Open Workspace), and this is how I work on the Flutter SDK and Dart SDK (eg. to only open the packages I'm working on, to reduce the work the analysis server is doing).

Multi-root workspaces. But I'm the kind of guy that likes to have one workspace. (I think my brain got wired that way because I had to use Eclipse for a long time, where the multiple projects open inside the same Eclipse window are completely independent.)

> However - it doesn't seem like an ideal solution as you'll get lots of errors in the Problems list for the Flutter projects (and while you can ignore them, it'd be nice to have a less janky solution).

You are absolutely right, I've got tons of errors, and just ignore them. Using the Flutter-mode/Dart-mode heuristic on a per root basis in a multi-root workspace would solve that.

**Comment by DanTup** [comment]
> Multi-root workspaces. But I'm the kind of guy that likes to have one workspace.

I didn't mean to use two windows, but rather just open a different `.code-workspace` depending on whether you want "with Flutter" or "without Flutter" projects. Eg. instead of using the SDK-switcher when you want to change SDK, you just File -> Open Workspace and choose the other one (or select from the recent list). It doesn't seem like a significantly different flow (and when using the SDK switcher we essentially reload the extension dropping all state and starting analysis from scratch again anyway).

Are you already using a `.code-workspace` file, or just selecting multiple folders in the Open dialog? (if the latter, having `.code-workspace` files will prevent you being prompted to save it every time you unload/close the workspace).

> Using the Flutter-mode/Dart-mode heuristic on a per root basis in a multi-root workspace would solve that.

Unfortunately this isn't really a good option as it'd involve spawning multiple analysis servers (at least one "per SDK") which would eat much more resources (and if your Flutter project referenced one of the Dart projects, the servers would do significantly overlapping/duplicated work).

**Comment by DanTup** [comment]
@dcharkes ping! :)

**Comment by dcharkes** [comment]
> (and if your Flutter project referenced one of the Dart projects, the servers would do significantly overlapping/duplicated work).

Yeah, that is not really what you want.

> Are you already using a `.code-workspace` file, or just selecting multiple folders in the Open dialog?

Selecting multiple folders, and never switching workspaces. Sounds like I should start using workspaces. :smile: 

Let me try the Dart-workspace and Flutter-workspace approach. I think you can close this issue.

**Comment by DanTup** [comment]
Workspaces should simplify things (and presumably when you open multiple folders and quit VS Code, it's prompting you to save the workspace all the time? it'd stop that!). I have a folder on my desktop called "Code Workspaces", and I have a bunch of files in there that selectively open sets of folders (eg. some for Flutter, DevTools, Analysis Server). This makes it really quick to open an exact set of folders (for ex. when working on the analysis server, I just want a subset of what's in the `pkg` folder).

Anyway, try it out and if it seems like it's adding unnecessary friction, do let me know and we can consider alternatives!
