### ISSUE TITLE
VSCode Issue

### ISSUE THREAD

**Issue by Apogee7** [Dart-Code/Dart-Code#1834]
I have been trying for hours to rectify an issue regarding compilation of Dart source code within 
VS Code IDE.  /bin/sh: dart . command not found

Any help in terms of presenting a solution for my problem would be greatly appreciated.  Still learning.

**Comment by DanTup** [comment]
Can you give some more info on what you're doing to see this message? You say compilation - do you mean when trying to run the script? If so, how are you running it? With `F5`?

Does the language support generally work (eg. do you get code completion, etc.)?

**Comment by Apogee7** [comment]
My apologies.  When running the debugger,  I'm receiving an error message:

            set the 'program' value in your launch config (bin/main.dart), exited with code=127

**Comment by DanTup** [comment]
If the active script is not inside `bin` folder or `tool` folder when you'll need to specify the path to it in the `program` value in `launch.json`. This tells the debugger which script to run when you press F5 (we assume if the active script is inside one of those folders its runnable directly, but otherwise you might editing a script that's not intended to be an entry point, so it needs specifying).

If you click on the Debug side bar, then the cog at the top, that'll open/create your `launch.json`. If there's already a Dart entry in it, just fix the `program` value. Otherwise you should get completion in the `configurations` section that will include a sample for launching a Dart script which you can then customise the `program` value for.

Let me know if this doesn't get you up and running!

**Comment by Apogee7** [comment]
I am basically trying to learn the Dart language in order to produce Flutter based applications.  I am using a Mac OS X based computer.  I have read the installation(for VS Code) instructions quite a few times.  Have uninstalled and downloaded VS Code and followed instructions for installing the pertinent plugins.  Now, things get tricky.  Are you telling me that the source files should be placed within the bin directory in order for the debugger to to execute?  I'm all over the place with this thing.  I'm not using any function keys at all.

**Comment by DanTup** [comment]
How to set things up depends a lot on whether you're doing:

- Flutter mobile apps
- Dart command line apps
- Dart web apps

Having things in specific locations (like the `bin` folder for Dart command line apps) is not necessary, but following the common conventions makes things easier (since we can make better assumptions about what to do when you press `F5`).

If you're working on a Dart command line app, I would recommend putting your script inside a folder named `bin`, but you could just put any path you wanted as the `program` value in `launch.json`.

If you're working on a Flutter app, your main entry point is best as `lib/main.dart`.

It's not clear which applies here - can you confirm the type of project you're working on?

Also - if you run the **Dart: Capture Logs** command from the VS Code command palette (Cmd+Shift+P / Ctrl+Shift+P) and then press `F5`, then click **Stop Logging** in the notification (which may have collapsed into the bell icon in the status bar), the log file that was recorded may help track down what's going on.

**Comment by DanTup** [comment]
I can't do anything more here without more info. I'm happy to re-open this if you can provide some :-)
