### ISSUE TITLE
Flutter: New Web Project fails when stagehand is updated via Dart SDK to a version that Flutter's SDK cannot run

### ISSUE THREAD

**Issue by domesticmouse** [Dart-Code/Dart-Code#1842]
I have a report against Stagehand for breaking under VSCode due to Stagehand requiring Dart 2.4 - https://github.com/dart-lang/stagehand/issues/617

Can we run stagehand under the system installed Dart, instead of the Flutter SDK?

**Comment by DanTup** [comment]
I've posted some comments at https://github.com/dart-lang/stagehand/issues/617#issuecomment-509510975 to keep the discussion together. I think a Flutter stable update has just somewhat resolved the issue for now so there's a solution if people see this (upgrade Flutter).

**Comment by DanTup** [comment]
Based on the replies at dart-lang/stagehand#617 I think it's now planned not rev Stagehand past the version of the SDK in the available Flutter stable, so I don't think it's worth trying to come up with a solution here unless that needs to change (at which point we can figure out what the best option is - since I don't think there's a trivial fix).
