### ISSUE TITLE
Extension leaves behind processes after exit on Windows

### ISSUE THREAD

**Issue by levrik** [Dart-Code/Dart-Code#1857]
After closing VS Code the extension leaves behind two processes using up to 1GB of RAM.

![image](https://user-images.githubusercontent.com/9491603/61184489-9ccf4500-a64e-11e9-8906-5f289e8e7a50.png)

**Comment by DanTup** [comment]
This is expected behaviour (and isn't VS Code or even Flutter specific) - the adb process is a server started by ADB the first time you run it ([see here](https://developer.android.com/studio/command-line/adb#howadbworks)). You can repro this by terminating the process then running `adb devices` and you'll see that it hangs around.

The lifetime of the server is managed by adb and we can't terminate it when you close a VS Code because it could be in use by other VS Code windows, Android Studio, or other processes on your machine.

There is [an issue in flutter/flutter](https://github.com/flutter/flutter/issues/4325) about having a single `flutter` command that would terminate it, but it'd have to be run manually.

Hope this makes sense!
