### ISSUE TITLE
DevTools Service failed to register

### ISSUE THREAD

**Issue by prabinbhatta** [Dart-Code/Dart-Code#1882]
Issue Type: <b>Bug</b>

The DevTools service failed to register. Please raise a bug against the Dart extension for VS Code.

Extension version: 3.2.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (3.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
Is there a "Show Log" button on the error? If so, can you click it and provide the log?

Can you also run `pub global list` in a terminal and paste the output? Thanks!

**Comment by shirlin520** [comment]
no ,cant

> Is there a "Show Log" button on the error? If so, can you click it and provide the log?
> 
> Can you also run `pub global list` in a terminal and paste the output? Thanks!

no , cant run 'pub global list ' in a terminal.

**Comment by DanTup** [comment]
I don't understand. What happens when you run `pub global list`? If you don't have a Dart SDK on your `PATH`, you may need to run it with the path of the SDK, like:

```
$ C:\flutter_sdk\bin\cache\dart-sdk\bin\pub.bat global list
```

Could you also try:

- Run the `Dart: Capture Logs` command from the VS Code command palette
- Untick `Analysis Server` but leave everything else ticked and click OK
- Reproduce the issue
- Click **Stop Logging** on the notification (which may have collapsed into the bell icon in the status bar)
- Attach the log or paste it into a [gist](https://gist.github.com/) and post the link here.

**Comment by DanTup** [comment]
Please let me know if you'r still seeing this and can provide a log or more info described above. Thanks!
