### ISSUE TITLE
Need a way to specify --local-engine for locally built engine

### ISSUE THREAD

**Issue by littlesome** [Dart-Code/Dart-Code#1905]
I'm using a locally built engine,  all flutter commands should pass --local-engine argument or we will got an error : "You must specify --local-engine if you are using a locally built engine."

Maybe `globalFlutterArgs` is a good place to do this? [src/extension/utils/processes.ts](https://github.com/Dart-Code/Dart-Code/blob/master/src/extension/utils/processes.ts#L9)

**Comment by littlesome** [comment]
Find some flutter tools code convert environment variable `LOCAL_ENGINE`,  `FLUTTER_ENGINE` into 
`--local-engine`, `--local-engine-src-path`
Should we do the same in setupToolEnv?

**Comment by DanTup** [comment]
I think you should be able to do this by just specifying the `args` in your `launch.json`:

```js
{
	"name": "Flutter",
	"request": "launch",
	"type": "dart",
	"args": ["--local-engine", "foo"]
}
```

I don't have a locally built engine to test this, but if I supply only "--local-engine" it complains about not having the next argument.

Another option if those env settings work, is you could set `dart.env` in your VS Code User Settings (this would apply to all projects instead of just the one you modified `launch.json`), like:

```js
"dart.env": {
  "LOCAL_ENGINE": "foo"
}
```

Do either of these do what you need?

**Comment by littlesome** [comment]
Hi,  I think the `args` in `launch.json` is not passed to some spawn calls, such as:
* `FlutterDaemon` 
* `runFlutterInFolder` in sdk.ts

The second option only works for some flutter tools which convert env `LOCAL_ENGINE` to --local-engine and pass it to flutter. 
All flutter commands need `--local-engine` cmd line argument such as :
```
flutter doctor --local-engine=host_debug_unopt
```

---

And you can test with a simulated locally built engine:
* add a global env var FLUTTER_ENGINE=/some/path/
* create an empty dir named `out/host_debug_unopt` in /some/path/
* copy `gen_snapshot` from `dart-sdk/bin/utils` to `/some/path/out/host_debug_unopt`
* run `flutter doctor` and see if you got an error `You must specify --local-engine if you are using a locally built engine.`
* run `flutter doctor --local-engine=host_debug_unopt`

**Comment by DanTup** [comment]
Ah, I didn't realise it would affect things like the daemon. I don't think `globalFlutterArgs` is the best place for this, as that would make it completely global (eg. you can't override it per-workspace). I think it would be better handled similar to `pubAdditionalArgs` but because we can't read config in the debug adapter (at least, we can't when we move it back out of process) we'll need to pass it in.

I haven't tested it yet, but I think something like this may do?

https://github.com/Dart-Code/Dart-Code/commit/3186d216a7a450d9a21ea3364ea28e9bf11821ad
