### ISSUE TITLE
autocomplete dropdown pops up too often when editing dartdoc

### ISSUE THREAD

**Issue by skybrian** [Dart-Code/Dart-Code#192]
I'm happy to have code completion when typing code, but when editing dartdoc, for each word I type, an autocomplete box appears giving matching English words. When typing a sentence quickly this results in lots of dropdowns flashing by. Might it be possible to add a delay to tone it down a little?

**Comment by DanTup** [comment]
I believe this is "by design" and is VS Code. I raised this as a bug here:

https://github.com/Microsoft/vscode/issues/10098

I have `editor.wordBasedSuggestions` set to false in my config, though it may also be `editor.quickSuggestions`. I think these are bad defaults personally :(

Try changing those settings and see if it resolves your issue (`Ctrl`+`Shift`+`P` and invoke `Open User Settings` then add the option to the panel on the right) and let me know if you still think there's something we should try to improve (I don't think we can easily add a delay or anything without providing stale data for a period, which would suck when editing code, and we can't (easily) tell if you're editing code or not).

**Comment by skybrian** [comment]
Thanks! applied.
