### ISSUE TITLE
When autocompleting for an enum, display the enum options first

### ISSUE THREAD

**Issue by dancojocaru2000** [Dart-Code/Dart-Code#1934]
Not sure how to explain it more than the title.

An example would be using Flutter's `Column`:
```dart
return Column(
    mainAxisSize: min// autocomplete here
);
```

As of 3.3.1-alpha.1, the completion results are these:
![image](https://user-images.githubusercontent.com/9626761/63343897-6f616f80-c34f-11e9-8877-43ebdbd272f1.png)

As you can see, `MainAxisSize.min` is the third from the bottom, instead of being at the top.

**Comment by DanTup** [comment]
Unfortunately this seems to be VS Code magic. We're returning the items ranked correctly (as you can see if you delete `min` and then invoke completion with Ctrl+Space), but when you type `min`, VS Code tries to provide "most relevant" results, ignoring the sort we provided.

I thought there was a setting to disable this, however I cannot find it. I've opened an issue in the VS Code repo here, which I would encourage you to put 👍 on :-)

https://github.com/microsoft/vscode/issues/79516

**Comment by DanTup** [comment]
I don't think there's going to be anything we can do here. VS Code takes over the sorting once you start typing. In the next update, typing `.min` should work better, but we're at the mercy of VS Code here. The sorting is good before you type the `m`.

**Comment by dancojocaru2000** [comment]
Time to try IntelliJ then 🙃
It sucks quite a bunch that they're so stubborn to not understand that VS taking over is a bad thing.

**Comment by DanTup** [comment]
Yeah, I'm with you. I understand it's tricky (because once the user starts typing, they don't go back to the language server, so there is value in them trying to resort what's left if the user types something that closely matches something), but to not consider any other options at all is frustrating (if VS Code wants to rank, we should be able to give it more information so that it can do it better - for example in this case it doesn't know these types match up).

I wish I could offer a solution :(
