### ISSUE TITLE
inconsistent completion for optional argument

### ISSUE THREAD

**Issue by nbros** [Dart-Code/Dart-Code#1940]
Let's say you have the following functions:
```
void fun1() {}
void fun2(int a) {}
void fun3({int a}) {}
```
Now I try to complete the call to each function:
```
  fun1();
  fun2(1);
  fun3();
```
In order to complete the calls we can type:
- fun1 **tab** **semicolon**
- fun2 **tab** 1 **tab** **semicolon**
- fun3 **tab** **right arrow** **semicolon**
For fun3, we need to use the right arrow or end key to move after the closing parenthesis that was automatically added by the completion. 
For fun1 and fun2, we can use the **tab** key to move after the parenthesis, but not for fun3 : if we type **tab** a tab is inserted between the parentheses.

I believe the issue is that Dart-Code does not add an empty completion placeholder after the closing parenthesis when the completed function has an optional named parameter.

**Comment by DanTup** [comment]
Unfortunately this is due to a limitation of VS Code :( It's discussed in #1173 and https://github.com/microsoft/vscode/issues/43270. The reason for the inconsistency with those that have required params is discussed at https://github.com/Dart-Code/Dart-Code/issues/1173#issuecomment-435313971.

I'll leave this issue open because it sucks, but it's blocked on VS Code for a fix ☹️

**Comment by DanTup** [comment]
I've changed this, but because it's a behaviour change and re-introduces an earlier complaint (though VS Code has resolved at least part of that) this is shipping behind a flag initially (`dart.previewNewCompletionPlaceholders`). Depending on feedback, it'll probably become the default in the following release.

I plan to have a beta build with this change in later today or tomorrow.
