### ISSUE TITLE
Whitelist `.dart_tool\build\entrypoint` to run as Dart and not Flutter to make debugging of builders easier

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#1942]
When trying to launch the generated build.dart in `.dart_tool\build\entrypoint it is currently launched as flutter and not as Dart project.

**Comment by DanTup** [comment]
There's a new beta build here if you'd like to try it out:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.4.0-beta.2

Release notes aren't ready yet, but the list of issues here covers what's in it:

https://github.com/Dart-Code/Dart-Code/milestone/97?closed=1

If you try it out, let me know if you hit any issues (I'll probably aim to release it this week - it's not very big due to being off a few weeks this month).
