### ISSUE TITLE
Cannot read property 'searchPaths' of undefined 	

### ISSUE THREAD

**Issue by akosyakov** [Dart-Code/Dart-Code#1948]
```
mainThreadExtensionService.ts:65 TypeError: Cannot read property 'searchPaths' of undefined
at findFlutterSdk (/Users/kosyakov/.vscode/extensions/dart-code.dart-code-3.3.0/out/dist/extension.js:1)
at module.exports.t.SdkUtils.<anonymous> (/Users/kosyakov/.vscode/extensions/dart-code.dart-code-3.3.0/out/dist/extension.js:1)
at Generator.next (<anonymous>)
at o (/Users/kosyakov/.vscode/extensions/dart-code.dart-code-3.3.0/out/dist/extension.js:1)
```

In order to reproduce:
- make sure that you don't have flutter sdk
- create a new flutter project
- use locate sdk
- see that nothing happens afterwards
- check dev tools for an error

**Comment by akosyakov** [comment]
Should not `activate` returns a promise here: https://github.com/Dart-Code/Dart-Code/blob/7bbd80f2ae650e9cab1f461f6cafcfa91851a6e3/src/extension/extension.ts#L160

Which is resolved only when SDKs are properly configured, right now it returns `undefiend` breaking activation flow.

**Comment by DanTup** [comment]
The error at the top looks like #1896. It's been fixed for the next version, and you can get a beta build from here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.4.0-beta.2


> Should not activate returns a promise here:
> 
> Which is resolved only when SDKs are properly configured, right now it returns undefined breaking activation flow.

The code here is a little messy because originally we didn't support reloading the extension "silently", so we just bailed out here and called "reloadWindow" if you located an SDK (which restarted the extension host). Probably this could be tidied up a bit, though I think with the fix about it should just work.

Let me know if you have any issues using the beta above instead (I'm hoping to try and release it at the end of the week).

**Comment by akosyakov** [comment]
@DanTup It works in VS Code, will try to figure out why it does not work in Theia.

I wonder how VS Code get proper extension API, if the call to `activate` does not fail, but returns `undefined`.

**Comment by akosyakov** [comment]
Actually, it works in Theia as well :D

**Comment by DanTup** [comment]
> I wonder how VS Code get proper extension API, if the call to activate does not fail, but returns `undefined`.

I think it's perfectly valid to return undefined from `activate` (VS Code will assume the extension has activated fine), for example an empty activate method would do this. The reason we don't throw (so that VS Code says "failed to activate extension") is so we can show the notification and give the user a button to try and fix it (and then do a silent restart in the background).

> Actually, it works in Theia as well :D

Great! Do shout if you have any other problems with the extensions. I'm often around in [Gitter](https://gitter.im/dart-code/Dart-Code) and [Discord](https://discord.gg/xSTPEqm) during UK office hours (mostly Mon-Thur) for questions that might not be worthy of issues FWIW.

**Comment by akosyakov** [comment]
Yes, the extension will be activated, but dependent extensions can break trying to access apis. Although it does not seem to happen with flutter extension right now.

**Comment by DanTup** [comment]
Ah yes.. the extension API is a bit loose anyway (for example there's no way to depend on specific versions of extensions) so extensions that have dependencies should be prepared for their dependencies to not activate, not provide an API, or provide the wrong API.

It looks like the Flutter extension doesn't handle that well though - if you run the **New Project from Docs** command I think it'll crash here:

https://github.com/Dart-Code/Flutter/blob/master/src/commands/sdk.ts#L8

Since it never checked the API export was defined. I'll fix that for the next version.

**Comment by DanTup** [comment]
Flutter extension vNext will write a clear error to the console now if the Dart extension didn't export an API:

https://github.com/Dart-Code/Flutter/commit/67f519acd0727493afbd6af22dfff5a5b07aeeff
