### ISSUE TITLE
Include "required" parameters in LSP's completeFunctionCalls completions

### ISSUE THREAD

**Issue by atreeon** [Dart-Code/Dart-Code#1960]
```
class Blah {
  final stob;
  Blah({@required this.stob});
}
```

When I type '`Bl`' intellisense suggests '`Blah(...)'`.  When selecting this item it writes `Blah()` in my code file.  Would it be a nice feature to supply my property names where the constructor uses named parameters?  So I think it would be nice if it wrote the following in my code file.
```
Blah(
  stob:
)
```
  For me it would be especially useful where the parameter is decorated with the `@required` metadata because then the named parameter must be defined.  It would just save some keystrokes I guess but it would be nice.
_Many thanks :-)_

**Comment by DanTup** [comment]
This would be nice, however I think it would be a bit awkward to use unless we also put tab stops next to each one:

```dart
Blah(
  arg1: {$1},
  arg2: {$2},
  arg13 {$3},
);${0}
```

However, VS Code doesn't handle this well because you get stuck in snippet-mode when you're in each of the tab stops, and in Flutter it's very common to want to write multiline functions as arguments (see https://github.com/microsoft/vscode/issues/43270). For ex, imagine you wanted to write:

```dart
arg2: () {
  // Handle key press
}
```

When you press `<tab>` to indent that code, it would jump to the next tabstop (`arg3`) which would be frustrating.

We do do something similar for non-named arguments already, but that has the issue described above (see https://github.com/Dart-Code/Dart-Code/issues/1173#issuecomment-435313971) so I'd like to get rid of it when I can (which is probably when commit characters work better).

**Comment by DanTup** [comment]
(I think it's a valid request to do better here though, so I'll keep this open in case a way to do it well comes up.. it'll likely need some analysis server work to get us the right info, but that might be simpler if we move to LSP).

**Comment by twistedinferno** [comment]
ok great, thank you.  I shall keep watching :-)

**Comment by jacoplane** [comment]
Alternatively a quickfix for "Add all required arguments". Right now there are quickfixes for every individualy required arguments, but that's kind of annoying for functions that have a lot of arguments.

**Comment by DanTup** [comment]
@jacoplane that sounds like a reasonable request too. The quick fixes come from the analyzer SDK, so this it would need to be implemented there - would you mind filing an issue at https://github.com/dart-lang/sdk requesting that and post a link back here for people to 👍 ? Thanks!

**Comment by jacoplane** [comment]
@DanTup I've opened an issue there: https://github.com/dart-lang/sdk/issues/38876

**Comment by DanTup** [comment]
This is mostly the same as https://github.com/Dart-Code/Dart-Code/issues/2823 which is now implemented. When using the LSP preview (and an upcoming SDK release - since that change only landed yesterday), the `dart.completeFunctionCalls` setting will insert parens and positional args.

However, it doesn't do `required` parameters, so I'll re-purpose this to support them (note: it's possible we'll only support real `required` params using the new `required` keyword rather than the `@required` annotation).

**Comment by DanTup** [comment]
Fix out for review https://dart-review.googlesource.com/c/sdk/+/174802.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/0fa6674ea94c26e5f4732a44e10e1374c2f795dd.
