### ISSUE TITLE
"Extension causes high cpu load" at startup

### ISSUE THREAD

**Issue by sephirothtbm** [Dart-Code/Dart-Code#1961]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.3.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.37.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/sephirothtbm/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
Is it possible you can attach this file for me to take a look? Thanks!

> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️/Users/sephirothtbm/Dart-Code.dart-code-unresponsive.cpuprofile.txt

**Comment by sephirothtbm** [comment]
Sure, sorry for not attaching it before, and Thanks.

[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/3581219/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment]
Thanks!

Was the folder you had open when you got this quite large? And what sort of disk is it on (spinning HDD or SSD?).

The message from VS Code is very misleading, it isn't high CPU but rather just blocking the thread (on synchronous file system access). I've tried making this async in the past but it made the whole thing slower (though because it didn't block the thread, it would eliminate this message). In this case it was only for prompting to run `pub get` though, so maybe having it take a little longer in the background wouldn't be a big deal.

**Comment by sephirothtbm** [comment]
Hi,

No, the folder was quite small, actually I'm learning flutter so the folder was the very basic tutorial in the site, my disk is an HDD.

**Comment by DanTup** [comment]
Thanks for the info, I'll see if I can make some improvements.

Do you see this message frequently?
