### ISSUE TITLE
dart command not found 

### ISSUE THREAD

**Issue by amitanubha** [Dart-Code/Dart-Code#1966]
Issue Type: <b>Bug</b>

Thugh al PATh settings are correct and i see this has been reported manytimes but no solution is given

Extension version: 3.4.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (0.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by toddabel** [comment]
More specifically, the following fails _dart.startWithoutDebuggingTestFromOutline (also the version that starts with debugging). Rolling the Flutter and Dart extension back to 3.3 solved this for me. Flutter test worked, just not starting individual tests

**Comment by amitanubha** [comment]
how to rol lback to 3.3 pls explain/help

**Comment by DanTup** [comment]
@amitanubha can you please give more details about the issue you're seeing, or links to the other reports?

If you're typing "dart" in the built-in terminal in VS Code and seeing "command not found", that's likely due to `dart` not being in your `PATH` - though that's unrelated to this extension (the built-in terminal is just a terminal, the same as the one outside VS Code).

If you're seeing a popup that says the Dart SDK could not be found, then it should have a **Locate SDK** button that you can click to navigate to the SDK manually (though if you're doing Flutter, you should get a Flutter equivalent when opening a Flutter project, and not need to locate a Dart SDK).

@toddabel I don't know if the issue you mention is the same - could you open a new issue with details of exactly what you're doing when you see this? Thanks!

**Comment by DanTup** [comment]
@toddabel actually, I repro'd your issue - I've opened https://github.com/Dart-Code/Dart-Code/issues/1967.

**Comment by amitanubha** [comment]
Unfortunately still doesn't work for me, strange it is able to create
project but when i run and compile it says dart is not recognized as an
internal or external command'

**Comment by DanTup** [comment]
@toddabel I released v3.4.1 with a fix for your issue.

@amitanubha can you provide a screenshot of what you're seeing and where? Is this a Dart or Flutter project? And how are you trying to run it?

**Comment by amitanubha** [comment]
running a flutter project, sending screenshot look at the terminal window
And yes i updated dart code to 3.4.1
[image: image.png]

**Comment by amitanubha** [comment]
i think i figured it out, i was actually doing ctr+Alt+N ii.e running the
code directly from main.dart window instead of running global project using
debug mode i.e. F5 and i guess to run a specific file i need to setup dart
sdk separately, now i can run my code atleast on an android phone

**Comment by DanTup** [comment]
Your screenshot didn't come through because it was an email attachment (you have to attach it directly in GitHub).

> i was actually doing ctr+Alt+N ii.e running the code directly from main.dart window

I'm not sure what this means. What is Ctrl+Alt+N? It doesn't seem to be mapped to anything for me.

>  instead of running global project using debug mode i.e. F5

`F5` or `Debug -> Start Debugging` is the correct way to launch a Dart or Flutter project in VS Code :-)

>  i guess to run a specific file i need to setup dart sdk separately, now i can run my code atleast on an android phone

When you press `F5`, it will run the current file you have open as long as it's in a folder named `bin` or `tool`. Otherwise it will try to figure out if your project is a Flutter project (in which case, it'll run `lib/main.dart` as a Flutter app) or not (in which case it will look for a `bin/main.dart`). You can customise the startup file by creating a launch config (click the cog icon on the Debug side bar) and use the `program` setting to choose a startup file.

Let me know if any of this doesn't make sense, or you're still having problems trying to do what you need!

**Comment by amitanubha** [comment]
No i understood and everything is working fine now

Thanks for your support and replies
-Amit

**Comment by DanTup** [comment]
Great! 👍

**Comment by y4code** [comment]
> Your screenshot didn't come through because it was an email attachment (you have to attach it directly in GitHub).
> 
> > i was actually doing ctr+Alt+N ii.e running the code directly from main.dart window
> 
> I'm not sure what this means. What is Ctrl+Alt+N? It doesn't seem to be mapped to anything for me.
> 
> > instead of running global project using debug mode i.e. F5
> 
> `F5` or `Debug -> Start Debugging` is the correct way to launch a Dart or Flutter project in VS Code :-)
> 
> > i guess to run a specific file i need to setup dart sdk separately, now i can run my code atleast on an android phone
> 
> When you press `F5`, it will run the current file you have open as long as it's in a folder named `bin` or `tool`. Otherwise it will try to figure out if your project is a Flutter project (in which case, it'll run `lib/main.dart` as a Flutter app) or not (in which case it will look for a `bin/main.dart`). You can customise the startup file by creating a launch config (click the cog icon on the Debug side bar) and use the `program` setting to choose a startup file.
> 
> Let me know if any of this doesn't make sense, or you're still having problems trying to do what you need!


Tried Ctrl + Alt + N(Command + Option + N on Mac), it works. So the reason why `New Window` works but `Current Window` doesn't works here is that

someone write this line of code into .zshrc/ bash_profile
```shell
export PATH="$PWD/flutter/bin:$PATH"
```

AND THIS LINE OF CODE COMES FROM flutter.dev [https://flutter.dev/docs/get-started/install/macos#get-sdk](https://flutter.dev/docs/get-started/install/macos#get-sdk)

someone would directly copy this line and insert it into path conf file, just turn it into 

```shell
export PATH="$HOME/flutter/bin:$PATH"
```

**Comment by riz0n8** [comment]
dart command gives an error when run from the windows terminal or power-shell. Any clue what might be wrong. All PATH env variables are in place. flutter command works as usual but not the dart command.
![Screenshot 2023-03-31 230413](https://user-images.githubusercontent.com/31257929/229221115-158b9bc9-b241-4d0b-b4ce-78e059891fd2.png)
![Screenshot 2023-03-31 231035](https://user-images.githubusercontent.com/31257929/229221119-5e611eff-95db-4be8-8976-03bc7c076215.png)
![Screenshot 2023-03-31 231055](https://user-images.githubusercontent.com/31257929/229221122-16e6a923-f14b-40c3-a600-2f8eeb2ceb7c.png)
![Screenshot 2023-03-31 231206](https://user-images.githubusercontent.com/31257929/229221124-c11dc126-1910-47a9-a477-ef2a9202b309.png)

**Comment by DanTup** [comment]
@riz0n8 This repository is for the VS Code extension, but this problem seems unrelated to VS Code.

That said, I would first try to solve the last problem from your PowerShell screenshot (that is, you don't have `git` available on `PATH`) and see what output you get (in PowerShell) then. I would also run `where dart` to check that it's running the correct Dart that you'd expect (`C:\flutter\dart.bat`).
