### ISSUE TITLE
Launch application doesn't show full emulator names

### ISSUE THREAD

**Issue by audkar** [Dart-Code/Dart-Code#1969]
Current dialog
![image](https://user-images.githubusercontent.com/1947112/64247363-62c84400-cf17-11e9-9957-43a2f53e1733.png)
Emulators in Android Studio:
![image](https://user-images.githubusercontent.com/1947112/64247391-71166000-cf17-11e9-8697-163c093591bf.png)

This is regression after 3.2 version if I remember correctly. Seems that #1904 fix didn't helped.

VS code flutter plugin version: 3.4.1

**Comment by DanTup** [comment]
@audkar the outcome of #1904 was that this is fixed in Flutter, but hasn't made the Stable branch yet. I made a change in Flutter to improve the display, and then forgot it hadn't been released when I made the changes to Dart-Code :(

If you try the beta/dev/master channels of Flutter, you should see the correct names (and after the next stable release, you should see them there too).

If you still see bad names in beta/dev/master please let me know and I will do some more digging.
