### ISSUE TITLE
Not resolving some imports

### ISSUE THREAD

**Issue by kentcb** [Dart-Code/Dart-Code#1978]
Here's an issue that bites me day-to-day. Repro as follows:

1. `flutter create repro_import_issue`
2. `cd repro_import_issue`
3. `code .`
4. Annotate the `MyApp` class with `@experimental` (or anything from the `meta` library)
5. Try to resolve the import via `Ctrl+.`

It does not resolve. Adding the import manually fixes the type resolution issue.

This same problem occurs with types from the `redux` package.

**Comment by DanTup** [comment]
When I follow these instructions, `meta` doesn't show up because it's not added to the `pubspec.yaml`. If I add it there, it runs `pub get` when I save, and then the quick-fix shows the import:

<img width="432" alt="Screenshot 2019-09-09 at 10 10 54 am" src="https://user-images.githubusercontent.com/1078012/64518461-20717f00-d2ea-11e9-921c-d2f32eeb3d08.png">

This seems to be working as expected. Were you adding it to the pubspec and running `pub get`?

(Also, can you confirm your Dart version? There was a bug in the past where running `pub get` to fetch new packages, the analyzer would not pick them up until it's restarted - I think that was fixed a while back though).

**Comment by kentcb** [comment]
_ugh_, that was totally the problem. Once I added `meta` (and `redux`) then things import fine. I think the confusing part is that the imports _do_ work if you add them manually, which led me to believe that it was a problem with the IDE. In fact, I think it would make more sense if the compiler (or a linter) gave you a warning/error if you import a file that isn't explicitly in your `pubspec.yaml`. 

Thanks @DanTup

**Comment by DanTup** [comment]
> I think the confusing part is that the imports do work if you add them manually

Ah, that's interesting - it seems that `meta` is added to the `.packages` file because Flutter depends on it, and that allows you to import it. However the quick-fix only seems to list things that are explicitly referenced in the pubspec (not all the things in the pubspec.yaml).

Seems like this has an open issue about a lint here:

https://github.com/dart-lang/linter/issues/29

**Comment by kentcb** [comment]
Perfect - upvoted. Yeah, the fact that it worked when I added manually prevented me from even _realising_ that meta was in a separate pub. I thought it was just part of the SDK.
