### ISSUE TITLE
Editor should respect global tab size

### ISSUE THREAD

**Issue by thinwire** [Dart-Code/Dart-Code#1986]
UX issue/complaint: I'm working on a Dart codebase with a uniform four-space indentation. Yet the editor insisted on using two spaces for indentation for every file I opened. "Detect Indentation" command fixed the issue on a per-file basis. Setting the global "detect indentation" setting had no effect. I ended up spending quite a bit of time wondering about which setting of mine was wrong, until I finally found issue #1015 with Google.

You should _NOT_ force an indentation size default that overrides a global setting. Yes, Dart code style specifies a two space indentation. Yes, this will cause `dartfmt` to change the indentation if run. If the detected indentation is not two spaces, you should show a _notification_ to alert the user to the issue(s). However, having the _only_ way to get around this issue be to type in
```
    "[dart]": {
        "editor.tabSize": 4,
    },
```
into `settings.json` in order to have the editor respect tab size is extremely bad UX: the setting is not visible in the settings list, and requiring this manual override forces the user to update field manually when moving to another project at some point. 
At the very least respect the `"editor.detectIndentation": true` setting, if set in `settings.json`.

**Comment by DanTup** [comment]
> You should NOT force an indentation size default that overrides a global setting.

Unfortunately there is no simple fix here. This is what VS Code does when an extension contributes settings for a specific language (I dislike it too, but it's what happens). In order to override a language-specific setting provided by an extension, you need to also set the settings for the language. You can do this in your VS Code user settings like this:

```json
"[dart]": {
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
}
```

If we don't explicitly set the formatting for Dart, then the huge majority of users (who use the provided formatter and spaces) the editor will pick tabs for things like new files (which don't have any indenting) and that's really frustrating also.

I do feel your pain - I prefer tabs myself (there's an existing issue around formatting at https://github.com/Dart-Code/Dart-Code/issues/914). Unfortuantely this is just how Dart is geared up. While you can avoid the default formatter, all edits made by the analysis server will be done using spaces, so the experience using tabs will not be ideal.

> At the very least respect the `"editor.detectIndentation": true` setting, if set in settings.json.

We explicitly disable that setting for Dart because it doesn't work reliably (in part because Dart uses 4-space indenting in places, which looks like a tab of 4 stops and in part because when there is no indenting in a file, VS Code will pick tabs, and then stick with them).

If you haven't already, I'd recommend putting a 👍 on https://github.com/Dart-Code/Dart-Code/issues/914. I'll close this as a dupe, as the solution is really the same. I'm sorry for the inconvenience and wish there was a simpler fix!
