### ISSUE TITLE
[Request] Remove default spaces indentation from VS Code Dart-Code extension. It should respect user config.

### ISSUE THREAD

**Issue by IvesDotMe** [Dart-Code/Dart-Code#1989]
I dislike using 2 spaces as default indentation but Dart extension disrespects my IDE settings and forces its configuration. After getting so annoyed I've found the problem.

**Go to the extension folder:**

- Windows %USERPROFILE%\.vscode\extensions
- Mac $HOME/.vscode/extensions
- Linux $HOME/.vscode/extensions

**Find dart-code.dart-code-*****

**Open package.json**

**You have to remove the following lines (around line 892)**

```
		"configurationDefaults": {
			"[dart]": {
				"editor.tabSize": 2,
				"editor.insertSpaces": true,
				"editor.detectIndentation": false
			}
		},
```

It was pissing me off.

![annoying dart](https://user-images.githubusercontent.com/2911019/64860142-9588df80-d66f-11e9-8c65-419b3aa070d2.png)

**Comment by DanTup** [comment]
Please see https://github.com/Dart-Code/Dart-Code/issues/1986 and https://github.com/Dart-Code/Dart-Code/issues/914.

You need to override this in your user settings inside a `"dart"` section, like this:

```
"[dart]": {
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
}
```

Removing the settings from package.json is not viable, because it would affect the significant negatively majority of users that use `dartfmt` and spaces. While `dartfmt` and the code generated by the SDK analyzer are all using spaces, this has to be the default.
