### ISSUE TITLE
Extension  has caused the extension host to freeze

### ISSUE THREAD

**Issue by zgramming** [Dart-Code/Dart-Code#2000]
<img width="925" alt="dart issue" src="https://user-images.githubusercontent.com/38829404/65087946-c9eafb80-d9e1-11e9-935d-2c54eaf23e7e.PNG">

- Flutter 1.9.1+hotfix.2 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision 2d2a1ffec9 (11 days ago) • 2019-09-06 18:39:49 -0700
- Engine • revision b863200c37
- Tools • Dart 2.5.0

[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/3623853/Dart-Code.dart-code-unresponsive.cpuprofile.txt)
Thanks

**Comment by DanTup** [comment]
Thanks for the report! Is this something you've seen more than once? Can you reproduce it? Do you remember what you were doing at the time?

The profile shows that the `handleMessage` function ran for a long time (1.3s):

![Screenshot 2019-09-18 at 8 31 26 am](https://user-images.githubusercontent.com/1078012/65126560-cf9b0e00-d9ee-11e9-8eeb-61376884eb1f.png)

The function doesn't do much except split an incoming message buffer into lines and then process each one as a message. Since the profile doesn't show lots of calls, it seems like maybe the buffer got a *huge* string to process, but it's hard to say - unfortunately the stack doesn't even show which type of service it was that triggered this.

If you can reproduce this, and it does eventually complete, [capturing logs](https://dartcode.org/docs/logging/#capture-logs-command) might show what it is.

**Comment by DanTup** [comment]
Actually, I found in one of the child calls which service it is - it's in processing the analysis servers `completion.availableSuggestions` message (which can be very large - it's pre-loading completion items for auto-imports).

I'll do some timing of those calls here, and see if there are any easy wins to speed it up.

**Comment by DanTup** [comment]
Looking again, I think it may actually be the JSON deserialisation:

```
msg = JSON.parse(message);
```

I'm not sure why it doesn't show up explicitly in the timeline, but it's the only code inside `handleMessage` that could take any time (that wouldn't show up as child function calls).

I think this will be better once https://github.com/dart-lang/sdk/issues/37816 lands, as the JSON size will be reduced significantly.

Out of interest - which version of VS Code are you on?

**Comment by zgramming** [comment]
It's first time i got this warning, if i remember i got this error at i'm create new flutter project . It taking much time debugging first app( FYI, i run with emulator) and i got this warning

**Comment by DanTup** [comment]
Ok, I think it's worth waiting to see if the issue above fixes it - so if you see it again after the next Flutter stable release (or if see it on dev/master that already has that change) please let me know. I'll keep this issue open in the meantime.

**Comment by zgramming** [comment]
Ok, thank's for your fast response

**Comment by DanTup** [comment]
If you're still seeing issues, please let me know.

**Comment by malikshariq1967** [comment]
I am facing te same problem .please advice
