### ISSUE TITLE
Is there any way to speed up the "auto closing brackets comments" updates?

### ISSUE THREAD

**Issue by SrBrahma** [Dart-Code/Dart-Code#2011]
It takes like 1-2 seconds here to update the auto comments, and it really takes my attetion from the code, and quite botters me.

Is there anyway to decrease the delay?

Thanks!

**Comment by DanTup** [comment]
We have a half-second delay when we get updates to the data that renders these, because if you're typing quickly we might get an update that corresponds to an older version of the document - and if we render that, all of the offsets would be incorrect and they'd render in the wrong locations.

It's possible we might be able to improve this, for example:

1. Doing some basic checking on the offsets to see if they correspond to locations that look sensible (eg. parens)
2. If we move to the LSP implementation, we might be able to attach document versions to the data, so we could immediately use or discard the results

2 is long-term, but maybe 1 is more feasible in the sort term. I'll see if I can have a little play with this when time allows.

**Comment by DanTup** [comment]
I've removed the 500ms delay when processing the labels now, but instead check that each one matches up with a `)` or `]` in the document before updating. This should make them update much quicker (and remaining delay is in the round trip to the server, but has been tiny in my testing).

If you want to try it out, there's a build here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.6.0-alpha.2

More info on installing from vsix is here: https://dartcode.org/docs/installing-a-preview-release/

Please let me know how it feels.

**Comment by irahulcse** [comment]
Thanks, @DanTup. This update was really  helpful.

**Comment by DanTup** [comment]
Great, glad to hear it's better! 👍
