### ISSUE TITLE
Can't catch firebase signin exception

### ISSUE THREAD

**Issue by umityayla** [Dart-Code/Dart-Code#2015]
Hello, I believe I don't need to share code about this. When authenticating with Firebase, if user cancels the login, vscode debugger can't catch the exception properly but android studio does with the same code.

**Comment by DanTup** [comment]
> I believe I don't need to share code about this.

A code sample always helps!

The same debugger is used by both editors, so they should have the same behaviour. There are tickboxes in the Debug sidebar of VS Code that let you control which exceptions break though:

<img width="358" alt="Screenshot 2019-09-30 at 5 22 40 pm" src="https://user-images.githubusercontent.com/1078012/65897330-efdfab00-e3a6-11e9-82e0-945749cccbd0.png">

Is it possible the exception is being handled, and Android Studio is set to break on caught exceptions, but VS Code is not? Otherwise, can you provide a code sample that I can run to reproduce? Thanks!

**Comment by DanTup** [comment]
Please let me know if you're still seeing this and can provide some additional info requested above.
