### ISSUE TITLE
Stop telling me the Flutter Extension is required.

### ISSUE THREAD

**Issue by edwnjos** [Dart-Code/Dart-Code#2023]
I keep getting "The Flutter Extension is required to work with Flutter Projects" notification on VS Code. This not true, I cant permanently hide it and it feels like spam.

**Comment by DanTup** [comment]
> This not true

Some Flutter functionality does not work/appear today if you don't have the extension installed. More functionality will move from the Dart extension to the Flutter extension over time, so if you don't have it installed, Flutter things will stop working.

Yes, the prompt is a little premature since the number of features in the Flutter extension is tiny - however migrating more functionality is somewhat blocked on the number of people that don't have the Flutter extension installed.

If you're doing Flutter development and you don't want to see the prompt, you need to install the Flutter extension. In the future it will be the only way, thus the prompt cannot be disabled.

May I ask why you don't want to install the Flutter extension?

**Comment by edwnjos** [comment]
Ok, my assumption was that the dart code extension was just used to provide language specific functionality like auto completion, syntax highlighting, code navigation etc. 
 
> May I ask why you don't want to install the Flutter extension?

Personal preference to just use the least amount of tooling needed.

**Comment by DanTup** [comment]
It also provides things like:

- Flutter commands (create project, open samples, doctor)
- Device features (device selector, emulator launching, etc.)
- Flutter outline
- Flutter UI guides
- Flutter debugger adapters

Currently they're all in the Dart extension, but for people wanting just Dart language support it feels like they're getting unwanted bloat, so long-term we'd like to separate them a little better so you can just have what you need.

If you're doing Flutter development, you should definitely install the Flutter extension. Today it's very light (it has only a tiny set of features), but over time this will change and it will be less disruptive if you already  have it :-)
