### ISSUE TITLE
The "is" keyword is not colored

### ISSUE THREAD

**Issue by nbros** [Dart-Code/Dart-Code#2031]
The "is" keyword is not syntax highlighted:
![image](https://user-images.githubusercontent.com/141089/66214179-87a00a80-e6c1-11e9-9e07-881111d5c7d6.png)

**Comment by DanTup** [comment]
So, it turns out this is actually working correctly. The theme you have selected just happens to colour operators as white, the same colour as variables. Here's how the code looks with a few different VS Code themes:

![Screenshot 2019-10-08 at 1 05 14 pm](https://user-images.githubusercontent.com/1078012/66394235-75c5ac80-e9cc-11e9-925d-80c3864aadde.png)
![Screenshot 2019-10-08 at 1 05 27 pm](https://user-images.githubusercontent.com/1078012/66394236-765e4300-e9cc-11e9-804b-d58856097ad7.png)
![Screenshot 2019-10-08 at 1 05 49 pm](https://user-images.githubusercontent.com/1078012/66394237-765e4300-e9cc-11e9-8a6b-da3d5c0514bd.png)

**Comment by DanTup** [comment]
I don't want to change the categorisation of this, since it's correctly marked as an operator. It would be weird in other themes if we started colouring some operators in different colours. Hope this makes sense!
