### ISSUE TITLE
Unable to debug files in test that are not tests

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#2034]
I think this may be by design, but I just wanted to check. If I create a file in the test folder that does not use test or run tests (but for example a program that generates test data, or that collects a benchmark), then I cannot debug it (the debugger starts but doesn't do anything, it keeps 'loading' forever). If I put the file in bin, then the debugger works fine. I suppose the plugin assumes all files in test should use the test runner, but perhaps that is a bit too constraining? (at least it would be nice if I can put an option in the debug config to not do this).

**Comment by DanTup** [comment]
This is slightly related to https://github.com/Dart-Code/Dart-Code/issues/2021 (and https://github.com/Dart-Code/Dart-Code/issues/1165). The current behaviour is that anything that ends with `_test.dart` or inside the top-level `test` directory is considered a test. The request in https://github.com/Dart-Code/Dart-Code/issues/2021 is to stop assuming everything ending with `_test.dart`, and this one is to not assume anything in `test` - though I'm not sure we can do both (we'd end up categorising nothing as tests).

Poking around inside the source to guess if they're tests seems more error prone (it's possible you don't directly use `package:test` in a test script, since you might have wrappers for groups/tests, like Flutter does). Maybe we could require being inside a test folder *and* end with `_test.dart`?

**Comment by bergwerf** [comment]
I suppose that's what pub run test does so that would make sense (in test
and _test.dart).

Isn't is possible to somehow exit if pub test can't run any tests (instead
of hanging, with a notification "can't find tests or something") or
fallback to normal debugging if pub test doest find any tests? At least now
it's not clear to the uses why it's hanging and how to solve it (feels like
a bug in the debugger).

**Comment by DanTup** [comment]
Yeah, it definitely shouldn't hang - it should fail and be obvious what's up. I'll take a look at that before I change the rules too.

**Comment by DanTup** [comment]
@bergwerf I can't reproduce a hang, it seems to run my non-test script fine:

<img width="876" alt="Screenshot 2019-10-07 at 2 08 04 pm" src="https://user-images.githubusercontent.com/1078012/66314430-ed7fd280-e90b-11e9-9cf4-720772f5a128.png">

Are you doing anything different? Could you capture a log using **Dart: Capture Logs** (leave everything ticked except Analysis Server).

Thanks!
