### ISSUE TITLE
Perfect language

### ISSUE THREAD

**Issue by alex9153** [Dart-Code/Dart-Code#2057]
Guys, you need to add 2 things.
1) Ability to create a class from string, or call a method from string
2) Class extensions. For example I would like to use this construction:  1.myFunc(); or "string".myImpl();

And It can say that Dart is fully completed. Don't need anything else. Just perfect.

**Comment by DanTup** [comment]
Thanks for the feedback! Though this repo is specifically for the VS Code extension rather than the language :-) The language is worked on at https://github.com/dart-lang/sdk and https://github.com/dart-lang/language.

For what it's worth though:

> Ability to create a class from string, or call a method from string

I think this is possible using [dart mirrors](https://api.dartlang.org/stable/2.5.2/dart-mirrors/dart-mirrors-library.html), however mirrors aren't usable in Flutter. The [reflectly](https://pub.dev/packages/reflectable) package may provide some of the functionality of mirrors, but I haven't used it so I couldn't be certain.

> Class extensions. For example I would like to use this construction: 1.myFunc(); or "string".myImpl();

If I understand correctly, these are available in the latest Dev SDKs - see https://github.com/dart-lang/language/issues/41#issuecomment-539251446 :-)

I'll close this since I don't think there's anything to action in the VS Code extension, but feel free to post back if anything isn't clear if you have any questions. Thanks!
