### ISSUE TITLE
widget. should be in blue and not white. 

### ISSUE THREAD

**Issue by jamiethain** [Dart-Code/Dart-Code#2068]
The word widget. should be highlighted in blue not in white in the colorization package. 

widget. represents the passed state to a stateful controller, and is used to access items like variables in state, instead of needing to pass variables forward in some manner. 

widget. in white makes it seem like a locally defined object instead of a language defined class.

**Comment by DanTup** [comment]
Can you provide a code sample of where this is wrong? The colours depend a lot on your theme, but in my testing, the `Widget` class appears the same color as other class names:

<img width="520" alt="Screenshot 2019-10-23 at 8 19 40 am" src="https://user-images.githubusercontent.com/1078012/67367703-eabce880-f56d-11e9-8a63-f8f5f33dc785.png">

**Comment by jamiethain** [comment]
Here is the code, it is a special property of the state class but it has such significant meaning that I believe it should be colourized, as these are very predominate in stateful controllers. 

I hovered over it so you can see the discription it is a property of the state class that is initiated before initState is called.  It's a getter specifically, and it carries all the properties of the Stateful Class that created it. 

widget. is used in the extended state class in the same way to reach back to the StatefulWidget class and this is why I think it is special, it is littered about my code, and I believe that if Dark Blue is not the right color then maybe a lighter blue or something that can be highlighted as a special property. 
 
 

![Screen Shot 2019-10-23 at 10 33 40 AM](https://user-images.githubusercontent.com/52176376/67404204-01b90600-f581-11e9-8049-939e95e53b34.png)

**Comment by DanTup** [comment]
Oh, I see what you mean now. The syntax highlighting is based on the syntax of the Dart language - it's not possible to add exceptions for specific fields of specific classes because the syntax highlighting has no access to type information (at least in its the current form - a TextMate grammar - which is all VS Code supports). Therefore it wouldn't know if `widget` was this specific field on a base class (or even if the base class was a widget) versus just some variable somewhere that's named `widget`.

If we added `widget` to the list of keywords, then write code like `final widget = getWidget()` in any other Dart code, then `widget` would also be coloured, and people would rightly consider this a bug.

It might be possible to overlay a colour using VS Code's decorations API, but it would be difficult to know for sure the field is the one described here (in VS Code we don't have direct access to a resolved AST) and I think it's a bit too specific - it would open the door to requests for all sorts of exceptions (for example framework authors may decide they have special fields with significant meaning they'd want coloured the same way).

I think it it was to be done, it would make sense as its own extension (which could be flexible to allow user to customise it). I'm happy to provide pointers where I can if someone wanted to have a go at building it.

**Comment by jamiethain** [comment]
Dan, 

I understand and was thinking the same -- there are a list of "special variables" that people seem to respect in Flutter and maybe if we colored them people would know that they are special. 

The 4 that I think of are widget, key, context and child. They hold such reverence in flutter that no one seems to ever make 
var widget = or 
var context = 

For 3 months I kept wondering about where did "context" come from, turns out it is a propery of the StatefulWidget but I get that people would want some form of extension. 

Even if there was a simple file somewhere that said widget. = [0xFF039BE5]  in some simple way. 

I know context is hard and the colors are great to work with right now, they provide lots of intuitive information. 

Jamie

**Comment by DanTup** [comment]
> The 4 that I think of are

The list of special cases has gone from 1 to 4 in the space of a few comments :) This is what I meant about it opening the door to more. As things stand today, it's absolutely clear how the colouring should behave. Once you start adding exceptions, it becomes difficult to draw the line. What when someone requests a 5th field, or a 10th? It's wide open to peoples own opinions and coding styles.

For those examples you gave, those variable names are all used pretty commonly in Flutter. For example I just searched for context and widget in Flutter codebase and found lots of matches:

<img width="416" alt="Screenshot 2019-10-23 at 4 51 29 pm" src="https://user-images.githubusercontent.com/1078012/67411412-802f9b00-f5b5-11e9-8ba5-da9a97506f22.png">

<img width="405" alt="Screenshot 2019-10-23 at 4 51 50 pm" src="https://user-images.githubusercontent.com/1078012/67411421-83c32200-f5b5-11e9-9763-4b7711bf1be4.png">

Having these appear in different colours would look very strange indeed. Even in the case where we highlight only the correct ones, I think it would be confusing to users that some field is being treated specially by the syntax highlighting (syntax highlighting is expected to be based on the syntax of the language).

I think the idea is interesting, but it feels like it would be better as its own extension - something users explicitly choose to install and know what they're getting. I don't think it's the case that all users would want this behaviour - especially if it can't be done reliably (which would require type resolution info).

**Comment by jamiethain** [comment]
Dan, 

I totally agree -- that it should be something separate. In your first and second example they are in the source of flutter and they are mapping into those special places. widget and context.  

What I found is it took me 3 months to understand what and how **widget.** is used the "." is not an error, and it took me understanding widget. to understand (**context**)

Key and Child are something separate and way way more common in use so I 100% agree that would be overkill. 

What I guess I want is there was a table or a file somewhere where I could choose to stick in my own colorized words.   

Back in the day I used to use Q-Edit and colorization was a file, and it is handy to colorize projects that have special meaning, I get it as not something everyone wants, I just want a way to colorize keywords when I want to... 

BTW, thanks for the great answers!

**Comment by DanTup** [comment]
> In your first and second example they are in the source of flutter and they are mapping into those special places. widget and context.

Many of the instances of `context` in the Flutter codebase are not related to the `context` on widgets - the `AppContext` class is used as a sort-of dependency injection. It's all over the place and would definitely look weird if they w ere coloured differently.

> What I guess I want is there was a table or a file somewhere where I could choose to stick in my own colorized words.

I've seen this request in VS Code before, but currently there's no way for a user to just override colours (like you can with creating your own snippets and themes etc.). You'd need to wrap it up in an extension. I think there are two routes:

1. Create an extension that "depends on" the Dart one, but provides its own grammar file for Dart (copy the Dart one, make tweaks to support they words you want)
2. Create an extension that uses the decorations API to apply colours over the words (it's possible that you could also do this via [tree-sitter](https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-tree-sitter), though I have no experience with it)

It's possible there are already other extensions out there that might do something similar, but I couldn't find anything with a quick search.

If someone wants to have a go at building an extension, I don't mind answering questions if I can be of any use (though I can't promise that I can :-)). I'll close this since I don't think it makes sense implementing here, but it remains open for comments/discussion 🙂

**Comment by maheshmnj** [comment]
@DanTup can you please point me where does the dart/flutter plugin picks those colors from to highlight the source code? either in vscode or in the dartpad I can't seem to find it I searched in the[ dartpad source code.](https://github.com/dart-lang/dart-pad/)
I  actually want to build a simple dart editor in flutter where user could just add source code to it and get some beautiful dart snippets.

**Comment by DanTup** [comment]
@maheshmnj I'm not sure how Dartpad works, though in VS Code the colours come from two sources:

1. a textMate grammar at https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json
2. [SemanticTokens for LSP](https://dartcode.org/releases/v3-19/#lsp-semantic-tokens) (this is layered on top and implemented in the [Dart language server](https://github.com/dart-lang/sdk/blob/e5ed69d04d3a89a024432ac5174bebcc978622a8/pkg/analysis_server/lib/src/lsp/handlers/handler_semantic_tokens.dart))

The actual colours are controlled by VS Code, we just supply it with tokens/annotations and it matches up with the theme.

If you're planning on building a real editor and want syntax highlighting, code completion, hovers etc. I would recommend looking into using [LSP](https://microsoft.github.io/language-server-protocol/). You can run the Dart language server in LSP mode and use its APIs to get all of that info, and since there are many other languages that support LSP, you could (in theory) also easily support them too.

**Comment by maheshmnj** [comment]
Thanks @DanTup for the quick response this will surely help
