### ISSUE TITLE
Implement method overriding suggestions

### ISSUE THREAD

**Issue by dancojocaru2000** [Dart-Code/Dart-Code#2089]
That's really about it. For example, when typing `initState` inside a `State<...>`, it should suggest and complete the override method for `initState`.

**Comment by DanTup** [comment]
Thanks for the issue! This actually already exists:

<img width="514" alt="Screenshot 2019-11-05 at 4 08 45 pm" src="https://user-images.githubusercontent.com/1078012/68224472-97737d00-ffe6-11e9-9185-e38b68a4d938.png">

<img width="437" alt="Screenshot 2019-11-05 at 4 08 50 pm" src="https://user-images.githubusercontent.com/1078012/68224480-9d695e00-ffe6-11e9-8c1f-5d622d5fd1eb.png">

However, it unfortunately only shows up in some specific places (for example at the end of the class works) because of how the AST is parsed. There are some related SDK issues about this you may wish to subscribe to:

https://github.com/dart-lang/sdk/issues/33084
https://github.com/dart-lang/sdk/issues/32677

I'll close this one since the work is entirely in the server, and once implemented there would just start working in VS Code.
