### ISSUE TITLE
Code intelligence in HTML

### ISSUE THREAD

**Issue by Timmmm** [Dart-Code/Dart-Code#2101]
When using AngularDart, it would be nice if DartCode provided completions and type checking in Angular attributes.

**Comment by DanTup** [comment]
I had a test of this, but it seems to be working as expected:

<img width="932" alt="Screenshot 2019-11-14 at 12 47 19 pm" src="https://user-images.githubusercontent.com/1078012/68858427-ec954a00-06dc-11ea-87c1-d97a6ba09072.png">

Have you enabled the Angular analysis plugin (it's an [analysis_options.yaml flag](https://github.com/dart-lang/angular/tree/master/angular_analyzer_plugin#installing-by-angular-version----for-angular-developers-recommended))? If not, that might fix it. Otherwise, if the analysis from the plugin generally works but isn't picking up something you'd expect it to, it's best to file a bug in the [AngularDart repo](https://github.com/dart-lang/angular) where the analysis plugin lives.

**Comment by Timmmm** [comment]
Hmm I was testing on the tour of heros example which seems to be not kept that up to date (`pub get` doesn't actually work by default). I'll try again with a new project.

**Comment by DanTup** [comment]
Yeah, I struggled a little to get an example. I ended up using the one from the **Dart: New Project** command and then adding a bool field to its component.
