### ISSUE TITLE
Debug Console doesn't seem to flush properly

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#2118]
I'm getting weird behavior when running regular (not flutter) dart programs.

It is easily reproducible when running the following code
```dart
void main() async {
  print("Hello");
  await Future.delayed(Duration(seconds: 1));
  print("World");
  await Future.delayed(Duration(seconds: 10));
}
```

"World" is not printed until the program completes, even though it should be printed one second after "Hello".

```
Version: 1.41.0-insider
Commit: bd8425fa9b6427dca51e882d39b9ae764c55e08c
Date: 2019-11-20T09:15:43.194Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

Dart-Code 3.6.0
```

**Comment by knopp** [comment]
Interestingly, when switching to Terminal and back to Debug Console, the message appears. Which makes me think that maybe the text is being outputted to debug console buffer, but maybe there is some additional flushing necessary?

**Comment by knopp** [comment]
Also, this seems to be regression in 3.6.0. With 3.5.1 it works as expected.

**Comment by DanTup** [comment]
Thanks for the report! This is a VS Code bug that was fixed yesterday and available for testing in insiders today:

https://github.com/microsoft/vscode/issues/83906#issuecomment-556146279

It was triggered by a recent change here (70a2a8ae2847452b4a91449bb1c18b099e95d329) to buffer the output slightly in order to improve detection of paths in stack trace output (before, it was possible that we'd get a path broken into two events and fail to map it). The change resulted in our output events sometimes *starting* with newlines which seemed to trip VS Code up.
