### ISSUE TITLE
Chrome not showing up in Flutter: Select Device

### ISSUE THREAD

**Issue by TaimoorHassan** [Dart-Code/Dart-Code#2124]
i'm on Manjaro. i've install google-chrome from [`AUR`](https://aur.archlinux.org/packages/google-chrome/) and it shows up in flutter doctor , flutter devices when executed from terminal. the problem is when i run flutter doctor from vscode it says

> [✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

**Comment by DanTup** [comment]
If you run `printenv | grep CHROME` in your terminal (where it shows up) do you have `CHROME_EXECUTABLE` set?

If not, if you close all instances of VS Code and re-launch from that terminal (`code`), does that make a difference?

**Comment by TaimoorHassan** [comment]
Actually it was a problem with my vscode. i just uninstalled it and installed from [AUR Binary](https://aur.archlinux.org/packages/visual-studio-code-bin) and that fixed it. i guess there is something wrong Code - OSS package in manjaro community repo. Thank you for responding

**Comment by DanTup** [comment]
I don't think there's much that VS Code can do wrong there. My guess would be that it's due to environment variable differences between your VS Code process and your terminal. If you installed something that set environment variables but you already had VS Code open, it wouldn't have seen those updates until it was next launched (or if they were set in terminal scripts, may only show up if launched from the terminal).

Anyway, glad you got it sorted!

**Comment by smolck** [comment]
@DanTup Not sure if I should open a new issue, but I'm getting this same problem even with `CHROME_EXECUTABLE` set. I'm using codium (code-oss) from the nixos unstable channel. Need more info?

**Comment by DanTup** [comment]
@smolck do you mean you're seeing the `Try setting CHROME_EXECUTABLE to a Chrome executable.` message? Do you see this if you run `flutter doctor` from a terminal?

**Comment by smolck** [comment]
No, I mean the chrome device isn’t listed at all. Chrome *is* listed *in a terminal*, so this only occurs in Codium.

**Comment by DanTup** [comment]
> No, I mean the chrome device isn’t listed at all. Chrome is listed in a terminal, so this only occurs in Codium.

If I understand correctly, you're seeing Chrome when you run `flutter devices` but it's not in the device picker in VS Code? If so, does your project have a `web` folder? VS Code only shows devices that can run your open project, whereas `flutter devices` is showing all devices.

> As a bit of an aside, note also that since I’m on NixOS, I can’t run flutter doctor (or any other flutter commands afaik) using the corresponding VSCode command (e.g. Flutter: Run <foo>): only using the terminal. AFAIK this is because it needs to run an executable from the android sdk folder but can’t since it isn’t executable in NixOS.

Do raise an issue for this and we can debug - in theory it should work fine - VS Code is only running `flutter doctor` the same as you would from a terminal, but capturing the output and showing it in an Output window. If it's not working, it suggests something is different in the environment (for example if you're setting some paths up in a terminal startup script, they might not apply to the VS Code environment if you don't launch it from the terminal?).

**Comment by smolck** [comment]
> If so, does your project have a web folder? VS Code only shows devices that can run your open project, whereas flutter devices is showing all devices.

Yup; `flutter run -d chrome` works fine, and actually now `web-server (web-javascript)` shows up as a device, but still no chrome. And if I try to click the device in the lower right hand corner, the Flutter daemon stops and asks if I want to restart it.

I think these issues are due to using NixOS (my specific NixOS setup), so I’ll open an issue as you said for debugging. Probably will open it later today assuming I have time.

**Comment by DanTup** [comment]
Have you set `CHROME_EXECUTABLE` in a terminal startup script that might not apply to VS Code?

Does it work if you launch VS Code from the terminal (where it works)? 

You could also try setting the `dart.env` VS Code User Setting to apply env variables to all Dart/Flutter processes.

```js
{
  "dart.env": {
    "CHROME_EXECUTABLE": "/foo"
  }
}
```

Also, if you capture the [Daemon Log](https://dartcode.org/docs/logging/#flutter-daemon), that should show whether the device is not showing up at all, or being filtered out because it thinks your project is not a web project.

**Comment by smolck** [comment]
@DanTup Thank you! The dart env part works; I was setting $CHROME_EXECUTABLE in my .zshrc, but that didn't carry over into vscode. However, the Flutter daemon exited on launch with (essentially) this log: https://gist.github.com/smolck/b585125ef88521f6968e21d09042d6f0

I also got this log after having hit F5 (and then the Flutter daemon crashed): https://gist.github.com/smolck/c14f1246d36eccd9cceab2f09a4c6e1a

**Comment by DanTup** [comment]
>  I was setting `$CHROME_EXECUTABLE` in my `.zshrc`, but that didn't carry over into vscode

Yeah, that's a common problem. If VS Code is launched in a way that doesn't inherit these environment variables, then of course it can't find them. It's better if you can set the variables somewhere globally so that all programs inherit them no matter how they're launched, but that may be harder (if even possible) depending on your OS.

> However, now the Flutter daemon exited on launch with (essentially) this log

Can you run `flutter doctor -v` from a terminal, and then also using the **Flutter: Run Flutter Doctor** command in VS Code and attach the outputs of each in a new issue? Also include whether `/home/smolck/Android/Sdk/platform-tools/adb` is the correct location of `adb` for you.

**Comment by smolck** [comment]
> Yeah, that's a common problem. If VS Code is launched in a way that doesn't inherit these environment variables, then of course it can't find them. It's better if you can set the variables somewhere globally so that all programs inherit them no matter how they're launched, but that may be harder (if even possible) depending on your OS.

Thanks for the info! Good to know.

> Can you run `flutter doctor -v` from a terminal, and then also using the **Flutter: Run Flutter Doctor** command in VS Code and attach the outputs of each in a new issue? Also include whether `/home/smolck/Android/Sdk/platform-tools/adb` is the correct location of `adb` for you.

Okay, will do. Do you want me to include the logs I left above as well?

Thanks for all the help!

**Comment by DanTup** [comment]
Yeah, the more included in the issue the better (though you can always link to here too).

**Comment by kanishkdgrt** [comment]
I too have the same issue...flutter doctor gives the error `[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
`

**Comment by MikulasVanousek** [comment]
I had the same issue on NixOS. The variable was set and would launch Google Chrome. I fixed it by rebooting my computer. :smiling_face_with_tear:

**Comment by Musta-Pollo** [comment]
Same here. Worked. Thanks!!

**Comment by paulkastel** [comment]
I stumbled on this yesterday. I had basic installation of Chrome and Flutter from FVM (3.13.1), and for some reason Flutter and VSC stopped detecting chrome (**nothing** regards chrome in flutter doctor). 🤷🏻‍♂️ 
While a lots of people suggests to set PATH to `/usr/bin/chomium` (or something similar) setting variable in PATH to Chrome app worked for me on mac os like so: `export CHROME_EXECUTABLE=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome`

**Comment by DanTup** [comment]
@paulkastel I'm surprised setting it to that value worked, because that's the path that's used by default on MacOS:

https://github.com/flutter/flutter/blob/d58f158a887ec92af482ebc27fdfe197e765fead/packages/flutter_tools/lib/src/web/chrome.dart#L29-L30

And it's returned here:

https://github.com/flutter/flutter/blob/d58f158a887ec92af482ebc27fdfe197e765fead/packages/flutter_tools/lib/src/web/chrome.dart#L55=L64

Is it possible you may have had `CHROME_EXECUTABLE` already set to a different value somewhere/somehow? You could try removing what you added, reboot, then `echo $CHROME_EXECUTABLE` in a terminal to see if that's the case.
