### ISSUE TITLE
"Create missing override" quick fix default template value

### ISSUE THREAD

**Issue by audkar** [Dart-Code/Dart-Code#2127]
We would like to have different code generated when using "Create missing override" auto-fix. 

When using using this fix on `MyClassImpl` for code:
```dart
abstract class MyClass {
  int myMethod();
}

class MyClassImp implements MyClass {
  
}
```
currently we get generated output:
```dart
@override
int myMethod() {
  // TODO: implement myMethod
  return null;
}
```
Expectation would be to have generated code which matches meaning of generated code e.g.:
```dart
@override
int myMethod() {
  // TODO: implement myMethod
  throw UnimplementedError();
}
```

Can we modify default template for this code ourself or this is hardcoded and needs changes in dart refactorings?

**Comment by DanTup** [comment]
Unfortunately this isn't user-editable, it's hard-coded and comes from the SDK:

https://github.com/dart-lang/sdk/blob/cdb9830a54bd8d72ab44d543569c68f9b052b0ca/pkg/analyzer_plugin/lib/src/utilities/change_builder/change_builder_dart.dart#L499-L501

@bwilkerson would this be a reasonable change for the SDK? (not just because it seems like throwing immediately rather than returning null might prevent you forgetting to implement, but this might not be valid in an NNBD world anyway?)

**Comment by bwilkerson** [comment]
Yes, that seems like a reasonable change to me, especially in light of NNBD.

**Comment by bwilkerson** [comment]
I just sent out https://dart-review.googlesource.com/c/sdk/+/126361.

**Comment by DanTup** [comment]
Great - thanks!
