### ISSUE TITLE
promiseToFuture unrecognized in VSCode

### ISSUE THREAD

**Issue by obshksw** [Dart-Code/Dart-Code#2145]
Hello! 
I have a problem since this issue: https://github.com/dart-lang/sdk/issues/38805

promiseToFuture is unrecognized in Visual Code, like this:
![image](https://user-images.githubusercontent.com/45799810/70155925-1826a700-1681-11ea-8e59-fc4d6999d3ed.png)

And the import looks like this:
![image](https://user-images.githubusercontent.com/45799810/70155955-270d5980-1681-11ea-8f08-0b5f3d099ffc.png)

Everything compiles, and if I remove the import, the build fails, so it IS used.

I'm on 3.6.0
Flutter: 1.10.15
Dart: 2.6.0

Thanks!

**Comment by DanTup** [comment]
@natebosch do you understand what's happening here? I opened a web plugin and I can repro this behaviour, but the strange thing is that the code completion shows `promiseToFutureAsMap` and if I do Go-to-Definition on that, I can see this line in the same file:

```
export 'dart:html_common' show promiseToFuture;
```

I'm using latest master for Flutter, which includes Dart v2.7.0 which is newer than your changeset linked above.

(I'm testing by opening the url_launcher project, since as far as I can see, `dart:html` is only allowed in Flutter web plugins, not Flutter web apps?)

**Comment by natebosch** [comment]
We'll need to ask the analyzer team. My guess would be that it has to do with `dart:html_common` being missing from the SDK summary shipped with flutter.

**Comment by DanTup** [comment]
@bwilkerson are you the right person to ask about this? I'm not very familiar with these summaries (I presume they're a way for the server to get resolution info for the SDK without having to parse all the files?)

**Comment by DanTup** [comment]
This seems to work now if I import `import 'dart:js_util';`, which is where the function shows up in the API docs:

![Screenshot 2020-10-21 at 17 50 22](https://user-images.githubusercontent.com/1078012/96752131-f67ffc80-13c5-11eb-9069-0dbe8f93c390.png)

So I think this has been fixed, but please shout if you're still having issues. Thanks!
