### ISSUE TITLE
Need to recognize Windows Emulator as device to deploy to

### ISSUE THREAD

**Issue by jwiese-ms** [Dart-Code/Dart-Code#2152]
With support for Windows desktop in Flutter there is a critical need to have the extension recognize Windows emulators as devices to be deployed to when building a solution with desktop embedding.  Not sure what this will take but would like to discuss and see how we can get it done.

**Comment by DanTup** [comment]
I think this is something that would better supported directly by Flutter (so it could work from the command line and from other editors). I don't know how it would work though (there are many different types of Windows emulators and I'm not sure if they have standard APIs to enumerate them or launch apps in them).

@jonahwilliams @stuartmorgan any thoughts on this? Is this a valid request for the flutter repo or out of scope?

**Comment by stuartmorgan** [comment]
Flutter doesn't support cross-compilation for desktop; there's no concept of the host and target being different. Without that, there's no way for an emulator to be a target. Instead, you'd need to build from within the emulator.

Cross-compilation is a reasonable request for the Flutter repo, but it would be a significant undertaking and isn't currently on the roadmap at all. I don't think filing a request for targeting emulators makes sense until/unless there's a concrete plan in place for cross-compilation, so I think that's the request to start with.

**Comment by jwiese-ms** [comment]
Why would it be anything different than what I have today when I hit F5 on my Windows Desktop and the app is setup for Windows Desktop Embedding?  The only difference would be that it is running it on the emulator and not the desktop.  Perhaps I’m missing something though as this isn’t my area of expertise?

// John Wiese / Principal Architect
// 414-978-5926 / Central US Timezone

**Comment by stuartmorgan** [comment]
I don't understand what you are asking, so maybe we are talking about different things. What exactly are you referring to when you say "Windows emulator"?

**Comment by jwiese-ms** [comment]
Equivalent of an Android device emulator, but a Windows device.

// John Wiese / Partner Technical Architect – Power Platform
// 414-978-5926 / Central US Timezone

**Comment by stuartmorgan** [comment]
I understand the general concept of a Windows emulator, but as @DanTup mentioned, there are lots of things that could be.

Are you talking about [this](https://www.microsoft.com/en-us/download/details.aspx?id=53424)? Wine running on Linux? Something like VMware? Something else? All of the above? What host OS (or OSes) do you want to emulate from?

**Comment by jwiese-ms** [comment]
I have an emulator of a Windows device which runs on a Windows machine.  Today I have a demo app that uses the Windows Desktop Embedding and I can hit F5 and it runs on my local desktop machine running Windows 10.  What I want is for it to run on the emulator on my machine that is also a Windows 10 device.  Think “Windows Phone Emulator” but it’s not phone it’s Windows 10 running in the emulator.

// John Wiese / Partner Technical Architect – Power Platform
// 414-978-5926 / Central US Timezone

**Comment by stuartmorgan** [comment]
I see, that eliminates the cross-compilation aspect. The leaves the issues @DanTup alluded to above though: is there an API or utility to detect that your emulator is running? To install apps on it (assuming it doesn't share the filesystem)? To launch apps in it? To detect that it's installed and run it if it's not already running? To get log messages from an application run in the emulator?

You still haven't said what emulator you're using; that makes it hard to have a concrete discussion about whether what you are asking for is even possible.

And as raised earlier, there's the question of which emulator or emulators to support. iOS and Android have standard emulators. Is what you are talking about widely used, or is it one of N different options, each requiring a completely different approach to all of the questions I listed above? If the latter, I think it would make more sense for people to write custom run actions for VS Code for specific emulators, rather than for Flutter to own all of that logic for a bunch of different emulators.

> there is a critical need to have the extension recognize Windows emulators as devices to be deployed to

It would also be helpful if you could explain why this is a critical need. It's not clear to me what critical problem this would solve; it seems like a small workflow convenience in a niche use case, but maybe I'm missing something.

**Comment by jwiese-ms** [comment]
It’s an emulator for a device that is not yet available. When the emulator goes out it will be the first and only one as will the device.  While it won’t be “mainstream” at the time, being it will be the first.  My hope is that  Flutter devs working on Windows desktop support will want to use it to test/debug/confirm that their applications will work on it.  Sorry, I can’t say much more than that.

// John Wiese / Principal Technical Architect
// 414-978-5926 / Central US Timezone

**Comment by stuartmorgan** [comment]
Ah, this discussion makes a lot more sense to me now, thanks :)

In that case, I think the right thing to do is to wait until this emulator is public, then file a bug in the Flutter repository asking for support for it. I agree with Danny that if this ends up being something we want to officially support, the right place for it would be within the `flutter` tool itself, as with iOS and Android emulators, rather than in Dart Code. I don't think it makes sense to file the issue until that point though, because without being able to answer the questions I posed above I don't see any way to make progress on the discussion. (Unless someone at your end who has access to the emulator wants to start working on adding support in the `flutter` tool themselves, in which case you could get guidance on how to add new device types in the tooling.)

I don't think this will be a blocker for simple testing though. I would imagine that VS will know how to run things on this emulator to allow for development in general, and if that's the case then someone interested in trying out a Flutter application on it can simply open the Runner solution for their Flutter project and run it from within VS. That's not quite as convenient, of course, but should work from day one as a way to test.

**Comment by jwiese-ms** [comment]
Ah, hadn’t thought of the VS route with runner, I’ll give that a try. There are a few here I can leverage to perhaps work on the support now as I’d like to get some demos up and running ASAP. Right now I can deploy, but I have to copy all the files needed via the Windows Device Portal, and there are some limitations there.

// John Wiese / Principal Technical Architect
// 414-978-5926 / Central US Timezone

**Comment by stuartmorgan** [comment]
> Ah, hadn’t thought of the VS route with runner, I’ll give that a try.

Note that you need to `flutter build` or `flutter run` for Windows at least once before opening the solution, otherwise necessary files will be missing.

**Comment by stuartmorgan** [comment]
Hmm, I just realized that the VS approach probably isn't going to work if there's a copy step, unless there's a way to tell VS what installing the build result in the emulator should do, because there's no way for it to know what support files are necessary. (Or unless it happens that the default behavior is to copy everything that's in the build output next to the exe.)

**Comment by clarkezone** [comment]
@jwiese-ms why can’t you just point VS at the emulator.. it’s the same as deploying any other c++ app to said emulator.  If you don’t know how, hit me up at work

**Comment by stuartmorgan** [comment]
@clarkezone Does VS have a generic solution for the need to copy a whole directory rather than the executable? Or should we be looking at adding some kind of packaging/installer in the example app that VS could use to do that?

**Comment by clarkezone** [comment]
If a user wanting to deploy / run in an emulator or remote device adds a packaging project, VS will handle the deployment automatically.  Hence I would say for now no need

On Dec 8, 2019, at 12:07, stuartmorgan <notifications@github.com> wrote:

﻿

@clarkezone<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclarkezone&data=02%7C01%7C%7C0b01388493834fa85cce08d77c1a4331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637114324542181547&sdata=OzJyU%2FBr%2FNf%2FjzJUAKWjy9VfCs1oyQdlGRMR%2F5biEe8%3D&reserved=0> Does VS have a generic solution for the need to copy a whole directory rather than the executable? Or should we be looking at adding some kind of packaging/installer in the example app that VS could use to do that?

**Comment by DanTup** [comment]
Let me know if you manage to get this working, or still need input here. I think once you've got the app running on the device, you should be able to use the

**Comment by DanTup** [comment]
(oops, misclicked 😄)

Let me know if you manage to get this working, or still need input here. I think once you've got the app running on the device, you should be able to use the `Debug: Attach to Flutter Process` command to connect (given the Observatory URI from the desktop app running on the emulator) if  you then want to hack on the Dart/Flutter parts with hot reload etc.

**Comment by jwiese-ms** [comment]
I’ve tried this.  When I open the Runner project in VS it won’t see the emulator.  I can even create a Xamarin project, which sees the emulator, then add the Runner and associated projects to that solution.  But as soon as I make the runner the Start-up project the emulator disappears from the list.

// John Wiese / Principal Technical Architect
// 414-978-5926 / Central US Timezone

**Comment by DanTup** [comment]
I don't know much about how this works in VS, but maybe @clarkezone can assist?

If you can get to the point of running the app on the emulator (and have it print its Observatory URI - and you can expose that port) then I think attaching VS Code should be relatively straight forward, but I can try to help troubleshoot that bit if not.

**Comment by clarkezone** [comment]
send John some mail at work.. this should work 🤞

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DanTup** [comment]
@jwiese-ms just tidying up issues. Did you resolve this? I saw your post at https://devblogs.microsoft.com/surface-duo/get-started-with-flutter-on-surface-duo/ however that looks like Android and you mentioned using the Windows desktop embedding above, so I'm not sure if they're the same thing.

I've had some other questions about deploying into Windows VMs (eg. on macOS, being able to run a Windows VM and deploy a Flutter desktop app into it) which I have some ideas for, and I've also been trying to [make it easier](https://github.com/Dart-Code/Dart-Code/issues/2424) to attach to processes that were not launched directly by VS Code.

**Comment by jwiese-ms** [comment]
Not resolved as of yet.  I know James Clark as been working on some stuff to get Flutter to deploy to Windows easier/better.  This was about using the Surface Neo emulator with VSCode and a Flutter app.  VSCode doesn’t see the emulator and I wasn’t sure if that is a VSCode issue or an extension issue.  You can install the Windows 10X emulator from any Windows 10 machine directly from the store, info here: https://docs.microsoft.com/en-us/dual-screen/windows/get-dev-tools


// John Wiese / Partner Technical Architect – Customer Insights
// 414-978-5926 / Central US Timezone

**Comment by DanTup** [comment]
> This was about using the Surface Neo emulator 

Ah, got it. Do you know if there's any way to spawn processes in the emulator from the host machine? I presume there must be something for Visual Studio to deploy to it and run - I found [remote debugger](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019) but it seems a bit more complicated than I had in mind. I was thinking more like a command line tool or something (similar to how VMs like VirtualBox and VMWare have command line APIs that allow launching a process inside the VM).

I'm not sure if Flutter will support Windows emulators, but if it's possible with a command line it might not be a million miles from the VM case I have. In VS Code we already have the idea of "[custom emulators](https://dartcode.org/releases/v3-10/#custom-emulators)" but they're just for launching right now. I don't think it's a big leap to have something that can run Flutter on the remote machine (via some API) and interact with it just as if it was a local process (we communicate over stdin/stdout + a websocket over to the Dart virtual machine).

**Comment by stuartmorgan** [comment]
I think the next step now is to file a Flutter (not Dart Code) feature request, ideally with details about how a tool can interact with the emulator, per my earlier comments [here](https://github.com/Dart-Code/Dart-Code/issues/2152#issuecomment-562607816) and [here](https://github.com/Dart-Code/Dart-Code/issues/2152#issuecomment-562589393)

**Comment by johnwiese-ms** [comment]
We should see where @clarkezone is with his work as he has been working on the side on some stuff in this area.

**Comment by DanTup** [comment]
@johnwiese-ms @clarkezone I don't think there's much to do here in Dart-Code - as Stuart says, it's be better to implement this in Flutter. If you're able to provide any pointers on how the Flutter tool could interact with the emulator (for instance knowing if there are offline emulators, running emulators, and how to deploy compiled apps and launch them) please file an issue at https://github.com/flutter/flutter/. Thanks!

**Comment by sumitsharansatsangi** [comment]
> > This was about using the Surface Neo emulator
> 
> Ah, got it. Do you know if there's any way to spawn processes in the emulator from the host machine? I presume there must be something for Visual Studio to deploy to it and run - I found [remote debugger](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019) but it seems a bit more complicated than I had in mind. I was thinking more like a command line tool or something (similar to how VMs like VirtualBox and VMWare have command line APIs that allow launching a process inside the VM).
> 
> I'm not sure if Flutter will support Windows emulators, but if it's possible with a command line it might not be a million miles from the VM case I have. In VS Code we already have the idea of "[custom emulators](https://dartcode.org/releases/v3-10/#custom-emulators)" but they're just for launching right now. I don't think it's a big leap to have something that can run Flutter on the remote machine (via some API) and interact with it just as if it was a local process (we communicate over stdin/stdout + a websocket over to the Dart virtual machine).

@DanTup , Here you have said this is possible with virtual box using, I want to do this for virtual box and need your support. Can you please explain me how can I achieve that? Thank you.

**Comment by DanTup** [comment]
@sumitsharansatsangi my comment was just a question about whether there was a command line to launch the emulator _similar to_ how VirtualBox has a command line interface used to start VMs. While you could use the custom emulators setting in VS Code to show your VirtualBox VM and launch it from VS Code, unless Flutter is able to find it (so that it shows up in `"flutter devices"`) then that won't help you run your app inside the VM - you'd only be able to launch the emulator (and then you'd receive an error that after 60 seconds it still wasn't recognised by Flutter).

Separately, I did do some investigation to see if I could proxy a `flutter run` process into a Windows VM in VirtualBox on my Mac (using `vboxmanage` to spawn the Flutter process inside the VM from the host) as a way to make this work without requiring full Flutter support. However I found that `vboxmanage` did not forward `stdin` correctly, so VS Code was not able to interact with the Flutter process spawned inside the VM.

Perhaps it would be possible with some sort of agent running in the VM that runs the Flutter process and can proxy the input/output streams to the host over a WebSocket, but it's not something I'm actively looking into.
