### ISSUE TITLE
Dev container

### ISSUE THREAD

**Issue by bhack** [Dart-Code/Dart-Code#2154]
Can we store here an official dev-container for Vscode remote?
See https://github.com/MFAshby/flutter-devcontainer

**Comment by DanTup** [comment]
I think the best place for dev containers would be https://github.com/microsoft/vscode-dev-containers (there's already a Dart one there that I've contributed to). I believe there they'd show up in the VS Code list so users can easily copy their configs into their own existing projects.

I did start to create some in [a fork of that repo](https://github.com/DanTup/vscode-dev-containers/tree/flutter-container) (I have a few branches with various settings, mostly unpushed though). I was using emulators and it was a bit weird because you needed an Android SDK on the host too - I didn't realise you could run the container in privileged mode to use physical devices. I think using Web should work well with some [upcoming changes](https://github.com/Dart-Code/Dart-Code/tree/remote-port-forwarding) too.

If there's a reason not to put them in the MS repo (or they don't want to accept them), then I think this org would make a reasonable place for them.

**Comment by bhack** [comment]
I think It Is ok if you can push on MS.

**Comment by bhack** [comment]
Is there Android SDK in the MS Dockerfile?

**Comment by bhack** [comment]
Also in the MS I see a dart only container the one I linked Is also flutter.

**Comment by bhack** [comment]
@DanTup I've checked your fork and seems ok. I think that if MS accept privileged mode version of your fork It will be really useful.

**Comment by bhack** [comment]
@DanTup What is the issue you found around the emulator?

**Comment by bhack** [comment]
I'am closing this. The new ticket is on MS repo https://github.com/microsoft/vscode-dev-containers/issues/162
