### ISSUE TITLE
Color swatch preview is shown even if commented out

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#2167]
<img width="814" alt="Screen Shot 2019-12-11 at 8 47 31 AM" src="https://user-images.githubusercontent.com/666539/70626962-5b3dc880-1bf3-11ea-94e9-246d4729ca18.png">

**Comment by DanTup** [comment]
Yeah, I noticed this too. It's because the colour detection we do is pretty naive and just regex's the file. We don't really know (in the editor) what's a comment and what's not.

I think the best fix for this would be to move this to the server (probably as an LSP custom message once we've moved the editor fully over to LSP).

**Comment by DanTup** [comment]
This might not need to be a custom message, as LSP may have support for it already:

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentColor

**Comment by lukepighetti** [comment]
This is definitely a nit. I wouldn't mind at all if you closed it.

**Comment by DanTup** [comment]
I'll keep this issue open as a reminder that I need to implement this in LSP anyway (and can use the API above), whether or not it ends up with the same quirk :-)

**Comment by DanTup** [comment]
If/when moving this to LSP, we should try to make it pick the Colors class more reliably too (see #2857).

**Comment by DanTup** [comment]
The built-in color picker is now supported via the LSP server. It's a change in the SDK so will show up in a future SDK release rather than Dart-Code release. When the SDK you're using supports this, the legacy color previews will be disabled, so this problem will go away (since the server-generated are more reliable and not using regex). 

https://github.com/dart-lang/sdk/commit/3238b2c09c1e2fc023363ea33902d93bcc8b3d79
