### ISSUE TITLE
Consider automatic crash reporting

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#218]
Yesterday's release added Analytics hits for analyzer exceptions. In less than 24 hours there are 17 fatal errors (across three users) and 20 non-fatal errors. These are mostly in the latest (1.20) SDK. This is out of just 65 extension activations!

![Errors](https://cloud.githubusercontent.com/assets/1078012/20454463/8c7b6f18-ae39-11e6-8ac7-2cb9a72ad9ce.png)

![Errors](https://cloud.githubusercontent.com/assets/1078012/20454478/e6f8fcc6-ae39-11e6-8f41-6a9ba4300bff.png)

This is only a small sample so it might not be reflective of how often this really happens, but on the surface this looks really bad and probably gives a bad impression of Dart Code.

Since it doesn't look like any of these were reported, it might be good to investigate a way to automatically report these errors (we can prompt the user for what they were doing to fill in that section). Posting them in a public issue tracker isn't wise (even if this was technically easy) but I'd be happy to review/try to reproduce and raise. We could maybe even collect the users email address if they'd be happy for us to request more info if we can't repro (and it doesn't look like a dupe).

@devoncarew what do you think about this? I think it'd be good to do, though part of me also wonders whether this is stuff that the analysis server should do itself so it gets reports from everywhere, not just us?

**Comment by devoncarew** [comment]
I'm really surprised we've hit this many but none of them have been reported to dart-lang/sdk. That's a much lower submit/error rate than I would have expected. Nice to have this data at least!

Just FYI, the Atom client has been switched over to displaying these exceptions (the same as VSCode), and we're working on doing the same for IntelliJ - VSCode won't be the only client of analysis server showing these exceptions.

It's super valuable for us to get the stack trace data, since that can provide us enough info to fix the issue. Without that, we get hard-to-act-on bug reports that 'the analysis server stopped working' or some such.

I'm not 100% on automatic reporting - it would be valuable, but would need to be clearly messaged to the user, about what was going on. I wouldn't have a clear opinion on it myself w/o more thought :)

**Comment by DanTup** [comment]
I think those numbers were largely coincidence. Over 95% of the errors are from the same user, so probably someone restarting (we prompt when the AS crashes) and just hitting it again.

> It's super valuable for us to get the stack trace data, since that can provide us enough info to fix the issue. 

Yeah, and even more useful would be the analyzer log - though it'd be hard to include any of that and be absolutely certain the user would review it for confidential info first :(

We'll see how it goes - should be easy enough to search for some part of the text in that error report to see if they're being reported and what the ratio is.

> I'm not 100% on automatic reporting - it would be valuable, but would need to be clearly messaged to the user, about what was going on.

I've pushed a change that I think solves this a little - I moved the errors from Analytic "events" to "exceptions" and include the first line of the exception (up to 150 chars) from the analysis server. This won't include any information a user would object to but might at least give us an indication that things might be errors we already know about (eg. for the crash I reported recently, we get `Analyzer: The null object does not have a method '_subFromInteger'.` in the analytics data).

You can see the change here: https://github.com/Dart-Code/Dart-Code/commit/b7d864ff60bf3e296f71b415b7468a02f1e16e0f

I think it'll be complicated to send any more data without having to "negotiate" with the user, so I'm going to consider that enough for this issue for now. If we see lots of crashes going forwards that aren't being reported we can re-visit this.
