### ISSUE TITLE
current test hierarchy and state pane

### ISSUE THREAD

**Issue by bsr203** [Dart-Code/Dart-Code#2180]
Hi. I've been using the plugin for flutter development for sometime and the experience is great. Just starting with testing, and not sure this is a bug or intended, but the behavior is annoying :-)

<img width="719" alt="Screen Shot 2019-12-19 at 11 45 55 AM" src="https://user-images.githubusercontent.com/1966521/71191980-704ed300-2255-11ea-9c8a-936dcfc37834.png">

I only have one test in `state_test.dart` file (initial state). The greyed out group and tests doesn't  exist, but may be it showing execution history (ya, I ran it in that name, had a test group, ..). I prefer to list current tests and last execution state. If it is not possible to just display that, is there a way to clear previous executions so don't have to keep wondering which is current.

thanks.
bsr.

**Comment by bsr203** [comment]
btw. re-opening the vscode window cleared the non existent tests, and now shows only the one I ran after.

**Comment by DanTup** [comment]
Unfortunately there are limitations in the `test` package that mean we can't get a full list of tests - only those that ran. This means we have to keep the "old results" around (which we grey out) when you run a single test, otherwise we could end up removing all results for other tests in the tree (which would look weirder).

However, the state is cleared when you run the whole file (since we know we're getting a full list then), so if you right-click on "state_test.dart" and run the whole file, it should reset itself (alternatively, hitting F5 to run the current file should do the same if your launch config is set up that way).

There's a little related discussion at https://github.com/dart-lang/test/issues/837.

Let me know if this all makes sense (and that running the file works for you).

**Comment by bsr203** [comment]
yup. selecting and running the file cleanup stale tests. I understand your constraints, and once understood, I can live with run through code lens , F5 or terminal if needs to. 

While at it, I didn't see any mentioning of code coverage support other than couple of issues yet to work on. Is there any official support for seeing code coverage markers or reports.

Thanks again for your time and support
bsr

**Comment by DanTup** [comment]
There's nothing built-in here for doing coverage. I think you can use `--coverage` to collect it, and there are lcov viewer extensions for VS Code. There might not be much to do here (except maybe making the process of passing the flags and launching the lcov extension easier).
