### ISSUE TITLE
Improve TODO message ranges

### ISSUE THREAD

**Issue by phanirithvij** [Dart-Code/Dart-Code#2181]
I'm using VsCode
```
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

- The TODO message also includes `*/` in it which should be removed
![image](https://user-images.githubusercontent.com/29627898/71268428-f14fbc80-2372-11ea-9aab-018501ae7605.png)
![image](https://user-images.githubusercontent.com/29627898/71268546-3b38a280-2373-11ea-8f65-158923a60430.png)
- And there's no multi-line TODO (?)
```dart
/*
  TODO: this whole block should be underlined
  Even this line
  Also this line
*/
```
Then in the preview, only the first line can be shown.

>  TODO: this whole block should be underlined ... dart(todo) [67, 10]

or some symbol hinting a new line ↩ ↵ ⏎ ⮰

>  TODO: this whole block should be underlined ↵ dart(todo) [67, 10]

**Comment by DanTup** [comment]
Yeah, this seems like a bug (though the range comes from the analyzer from [the SDK](https://github.com/dart-lang/sdk)). As a workaround until it's fixed you could use `// TODO`

**Comment by DanTup** [comment]
I've fixed the bad range in the SDK (https://dart-review.googlesource.com/c/sdk/+/129440). Handling multi-line TODOs seems less trivial (and I think it's a bit ambiguous whether the user actually intends the TODO to cover all lines). If you think that's important it would be best raised at https://github.com/dart-lang/sdk since that's here the TODOs are parsed. Thanks!
