### ISSUE TITLE
flutter doctor found cocoapods on cli but not in vsc

### ISSUE THREAD

**Issue by eecs441staff** [Dart-Code/Dart-Code#2192]
Hi, attached the output of flutter doctor -v run on the command line and inside Visual Studio Code.  As you can see, flutter doctor can find cocoapods on the cli but not from inside the vsc.  This is on a macOS 10.14.6. Any suggestion on how to fix it?  Thanks.

[cli-doctor.txt](https://github.com/Dart-Code/Dart-Code/files/4008824/cli-doctor.txt)
[vsc-doctor.txt](https://github.com/Dart-Code/Dart-Code/files/4008825/vsc-doctor.txt)

**Comment by DanTup** [comment]
The check for cocoapods is here:

https://github.com/flutter/flutter/blob/a15a81be218f8b2fa2f63d7cd0f8cb0b3a6c2e08/packages/flutter_tools/lib/src/macos/cocoapods.dart#L76

It just runs `which pod`. So my guess is that your `PATH` does not include where cocoapods is installed. For the terminal, possibly it's added in a startup script that is only executed for terminals and does not apply to the VS Code process?

Can you try:

- Run `which pod` from the terminal (that works) to find the location of the binary
- Enable Dart Code's [extension log](https://dartcode.org/docs/logging/#extension) and restart VS Code, then check all of the `PATH`s logged to the file to see whether it includes the location where `pod` is

**Comment by eecs441staff** [comment]
Thanks Dan.  Here's the output of "which pod":

bash-3.2$ which pod
/usr/local/bin/pod

And Dart Code's extension log indeed does NOT record /usr/local/bin in PATH:

Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.1
Platform: mac
HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Jan 02 2020 [11:47:24 GMT-0500 (Eastern Standard Time)] Log file started
[11:47:24 AM] [General] [Info] Searching for SDKs...
[11:47:24 AM] [General] [Info] Environment PATH:
[11:47:24 AM] [General] [Info]     /usr/bin
[11:47:24 AM] [General] [Info]     /bin
[11:47:24 AM] [General] [Info]     /usr/sbin
[11:47:24 AM] [General] [Info]     /sbin
[11:47:24 AM] [General] [Info] Found Flutter project at

The path /usr/local/bin is already in all the usual places:

bash-3.2$ cat ~/.bash_profile
export PATH="/usr/local/bin:$PATH"

bash-3.2$ cat ~/.profile
export PATH="/usr/local/bin:$PATH"

bash-3.2$ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

Searching the web, the only solution I've found that works is:

https://stackoverflow.com/questions/43983718/set-global-path-environment-variable-in-vs-code

to "install code command" in vsc and run it as "code" from cli, not by clicking the icon in the dock.  Unfortunately it sounds like this solution will not survive a future vsc update.

Do you know of a more "permanent" solution? Thanks!

**Comment by DanTup** [comment]
You could add the path to `/etc/paths` or in a file in `/etc/paths.d`. The first is where it's set for me:

```
danny@Dannys-MBP ~ % cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

I'm not sure why it's not there for you (seems to be there on all my MacBooks, but I didn't add it myself). You'll probably need to use `sudo` to modify that file (for ex `sudo nano etc/paths`, make changes then `Ctrl`+`X` to quit and say `Y` to save changes). You may need to reboot after changing it.

Launching `code` from the terminal should always work (even after updates) since it inherits the environment, but it's not an ideal solution because it won't work from the dock. Setting paths in `/etc/paths` or `/etc/paths.d` is the best solution since it applies globally.

Let me know if this doesn't work.

**Comment by eecs441staff** [comment]
My /etc/paths already has /usr/local/bin in it:

bash-3.2$ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

I copied /etc/paths to /etc/paths.d/Code.app, /etc/paths.d/Code, and as suggested in stackoverflow, also to /etc/paths.d/<myusername>.  Also chmod a+r all the files. None of them made any difference in terms of vsc being able to find cocoapods.  I tried re-login and rebooted my mac, no luck.

**Comment by eecs441staff** [comment]
Meant to say, "also to /etc/paths.d/myusername".

**Comment by DanTup** [comment]
Hmm, I'm not sure what could be happening for paths in `/etc/paths`/`/etc.paths.d/` to not show up for VS Code. `/etc/paths.d/` is how I always set up my MacBooks to ensure VS Code can find my Dart/Flutter SDKs.

What happens if you run:

```
cat /etc/profile
```

I have this in the top of mine, which I think is the utility that handles the `paths.d` folder:

```
danny@Dannys-MacBook ~ % cat /etc/profile
# System-wide .profile for sh(1)

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

FWIW, here's the owner/permissions on my files for this machine:

```
danny@Dannys-MacBook ~ % ls -la /etc/paths.d 
total 8
drwxr-xr-x   3 root  wheel    96  2 Jan 18:17 .
drwxr-xr-x  84 root  wheel  2688  2 Jan 18:30 ..
-rw-r--r--   1 root  wheel   110 17 Dec 20:36 dart-flutter
```

**Comment by eecs441staff** [comment]
Dan, no joy.  I have the same call to path_helper in my /etc/profile and same permissions on both /etc/profiles.d and all the files in it as you do.  I even copied /etc/paths to /etc/paths.d/dart-flutter and /etc/paths.d/flutter and rebooted.  By the way, Android Studio works fine, it can find cocoapods, just that it's much slower than vsc.  Thanks for all your help.  I'll live with Android Studio and/or command-line launch for now.  I'm closing this ticket.  Thanks.

**Comment by DanTup** [comment]
What happens if you run `/usr/libexec/path_helper -s` from the terminal? It should return code that sets up `PATH` (which is normally `eval`'d by the code above). Does that include the paths from `/etc/paths`?

**Comment by eecs441staff** [comment]
Yes, it does show that all the paths in /etc/paths are in $PATH, including /usr/local/bin/.

/usr/libexec/path_helper -s
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"; export PATH;
MANPATH="/usr/share/man:/usr/local/share/man"; export MANPATH;

**Comment by DanTup** [comment]
There's an answer on StackOverflow (from 2009 though) suggesting `/etc/launchd.conf` is the only place to set these that will apply globally:

https://stackoverflow.com/a/588442

I don't know if that'll work for you - nor can I explain why this way works for me (it's what I've been doing since 10.12/Sierra). Do you have anything in `/etc/profile.d/` or `~/.profile` that might be overwriting (not appended/prepending) `PATH`? (I'm not familiar with which files are run in which contexts).

**Comment by eecs441staff** [comment]
Dan, thanks for continuing to look into this issue. I created /etc/launchd.conf containing only the single line:

setenv PATH :/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:

and rebooted.  VSC still couldn't find cocoapods.

I've also tried replacing the above with:

setenv PATH ":/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:"

and rebooted.  Then also:

setenv PATH "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

and rebooted.  VSC couldn't find cocoapods in all cases.

**Comment by DanTup** [comment]
Do you have anything in `/etc/profile.d/` or `~/.profile` that might be overwriting (not appended/prepending) `PATH`? I'm not familiar with which files are run in which contexts but it does feel like something is wiping it out. I don't know how much effort you want to put into it, but you could try `echo $PATH > somefile.txt` before and after the `path-helper` call in `/etc/profile` and see whether a) it's being called, b) whether the `PATH` before it runs is the same as the one that you're ultimately ending up with, and c) whether path-helper did it's job correctly.

Otherwise, it might be worth asking on StackOverflow/Apple StackExchange - it's somewhat on the edge of my knowledge of macOS/Linux. We do support overwriting the `PATH` for Dart/Flutter with `dart.env`, but you'd have to hard-code your entire `PATH` in there (which might introduce future confusion if you add something to the system path and it seems to disappear from Dart/Flutter paths).

**Comment by eecs441staff** [comment]
Dan, I got it to work by changing my default shell from /bin/tcsh to /bin/bash (chpass -s /bin/bash myusername).  Thanks again for all your help!

**Comment by DanTup** [comment]
I'm not sure why that fixes it (but I'm a bit of a macOS/Linux newbie), but I'm glad you sorted it! :-)

**Comment by OzzyTheGiant** [comment]
If anyone is using RVM to manage ruby versions, `pod` will be in a user folder like:
`/Users/user/.rvm/rubies/ruby-2.4.1/bin/pod`
Simply use ln to create a symbolic link from `/usr/local/bin/pod` to that path.
Lastly, if using VS Code, restart it so that the Dart extension picks up on this change.
