### ISSUE TITLE
Respect touchbar keyboard ignore list

### ISSUE THREAD

**Issue by jascodes** [Dart-Code/Dart-Code#2195]
Allow to skip render of touch buttons when they are added to ignored list.

e.g
```
"keyboard.touchbar.ignored": [
        "flutter.screenshot",
		"workbench.action.navigateBack",
        "workbench.action.navigateForward",
        "workbench.action.debug.run",
        "workbench.action.debug.pause",
        "workbench.action.debug.stop",
    ],
```

The above shouldn't render screenshot button.
That allows me to have space for my other custom touch buttons which is not possible right now.

Thx

**Comment by DanTup** [comment]
Thanks - I've opened an issue at https://github.com/microsoft/vscode/issues/87980 asking for clarification on how this is intended to work. It feels unnecessary for every extension contributing buttons to implement this check when VS Code could do it itself so I'd like to ensure it's the correct thing before doing it (and if it is the correct thing, I've requested that it's documented).

**Comment by jascodes** [comment]
Cool!!
Meanwhile can you create a simple option `flutter.disableTouchbar` to disable all buttons generated via dartcode extension?

Thx

**Comment by DanTup** [comment]
There's no release planned until towards the end of the month, so I'd prefer to wait for a response on that issue before making any changes. If there's no response before the next release then I'll look at adding something (I've already put this issue into the current milestone so it's not missed).

**Comment by DanTup** [comment]
Turns out this is working as expected, but in order to have shorter text ("Screenshot") on the touchbar than the command palette ("Save Screenshot") we have two have two commands. The ID of the command on the touchbar is `_flutter.screenshot.touchBar`. If you change to that, it works.

It's not ideal that you'd need to know the internal names of hidden commands (I've commented such on the issue above), but you can find them in the [`package.json` file here](https://github.com/Dart-Code/Dart-Code/blob/9751fbf35facb842ae018422f6befbb75d6c8679/package.json#L732-L748).

Hope this helps!
