### ISSUE TITLE
Add a way of running async code in debug console

### ISSUE THREAD

**Issue by Rodsevich** [Dart-Code/Dart-Code#2212]
When running Future returning code in the debug console, only a

> _Future (Instance of 'Future<void>')

instance is returned. And no way of interacting with it.

It doesn't even works the `.then((s){print('funcó: $s');})` call

**Comment by DanTup** [comment]
@Rodsevich it seems like the `.then()` will work, but only once you resume (since the isolate is paused so the async code doesn't actually run until it's resumed).

@bkonyi do you know if it's possible to support this? If the user wants to invoke some async code from the debug console (which calls `evaluate`) and get the value back (without having to unpause, and ideally without adding things like `.then(print)`)?

<img width="727" alt="Screenshot 2020-01-16 at 17 03 30" src="https://user-images.githubusercontent.com/1078012/72546218-499ab100-3882-11ea-9704-01e905d20780.png">

**Comment by bkonyi** [comment]
I have a feeling this isn't possible since awaiting a `Future` requires the event / microtask loops to execute which probably require the isolate to be unpaused. The only thing that _might_ work (I haven't tried it) is wrapping the future in [waitFor](https://github.com/dart-lang/sdk/blob/master/sdk/lib/cli/wait_for.dart#L116) from `dart:cli`, but it's technically experimental and not recommended for general use.

**Comment by DanTup** [comment]
Ah, interesting idea! If it was usable in the debug console directly, then it probably would be fine that it's experimental. Unfortunately it didn't work (at least in my Dart CLI script):

> waitForEventSync is not supported by this embedder

Do you think it's a reasonable feature request to open in the SDK? I can see it could be frustrating when trying to debug code that you can't call anything async.

**Comment by bkonyi** [comment]
> Ah, interesting idea! If it was usable in the debug console directly, then it probably would be fine that it's experimental. Unfortunately it didn't work (at least in my Dart CLI script):
> 
> > waitForEventSync is not supported by this embedder

Was this in Flutter? It might not be setup there.

> Do you think it's a reasonable feature request to open in the SDK? I can see it could be frustrating when trying to debug code that you can't call anything async.

I don't think it will hurt to file an issue, but this is probably something that will require a decent amount of work to support.

**Comment by DanTup** [comment]
That was in a standard Dart VM CLI script.

I'll file an issue - it gives somewhere for people to put 👍 's to at least help gauge demand that might be useful to know when weighing up the cost.

**Comment by DanTup** [comment]
I've opened https://github.com/dart-lang/sdk/issues/40198 as a request to collect 👍 's on, thanks!

**Comment by HerrNiklasRaab** [comment]
I get this, when I click "Evaluate in Debug Console":

> error: org-dartlang-debug:synthetic_debug_expression:1:23: Error: 'await' can only be used in 'async' or 'async*' methods.
> popProfile.userId != (await userService.currentUser()).id
>                       ^^^^^

Just adding this phrase, so that it can be found more easily. I had a hard time finding this issue.
