### ISSUE TITLE
Unable to clear Debug Console

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#2224]
In an earlier version of VS Code / Dart-Code the Debug Console was cleared automatically when I started a new debug session. Now the previous log history is restored to the Debug Console every time I start a new debug session. 

Not sure if this is this a bug or a planned change, but I don't like this new behavior. I want to start each debug session with a new fresh Debug Console without any log history.

Even if I click the "Clear Console" button, it is first cleared but the log history is restored when I start a new debug session.

VS Code Version: 1.41.1 
OS: Windows_NT x64 10.0.18362
Dart Code 3.7.1

**Comment by DanTup** [comment]
Thanks for the report! I don't think the issue here is that VS code isn't clearing the log, but rather a Flutter issue is causing the old logs to be re-printed, see:

- https://github.com/flutter/flutter/issues/45478
- https://github.com/flutter/flutter/issues/47767

I'll close this as a dupe, but let me know if you think it's not the same issue and include a screenshot showing old errors with the Debug Console extended to include both the stale messages and the build/compile output. Thanks!

**Comment by kinex** [comment]
Ok, thanks! Quite annoying small issue..
