### ISSUE TITLE
Dart DevTools with MS Edge instead of Chrome

### ISSUE THREAD

**Issue by brouwer** [Dart-Code/Dart-Code#2226]
Currently Dart DevTools opens in Google Chrome by default (and by design). My default browser is the new Microsoft Edge that is based on Chromium. Dart DevTools work just fine.

Is it an idea to change this into a setting so we can choose what browser should launch?

See also:
https://github.com/Dart-Code/Dart-Code/issues/1681
https://github.com/Dart-Code/Dart-Code/issues/1760

**Comment by DanTup** [comment]
This is handled by the DevTools package itself (we just ask it to launch in a browser), so this would need requesting/implementing in [the DevTools repo](https://github.com/flutter/devtools/).

That said, there are other Chromium-based browsers that DevTools doesn't not work in (for example Brave, because its ad-blocking/anti-fingerprinting interferes with the canvas rendering - see https://github.com/flutter/devtools/issues/367#issuecomment-467788428) so I don't know whether it's as simple as just launching in Edge.

**Comment by AlexDotel** [comment]
Some solution founded?

**Comment by AlexDotel** [comment]
Some solution?

**Comment by DanTup** [comment]
@AlexDotel the comment above is still accurate. Though if you don't have Chrome installed, it should automatically fall back to your default browser.

FWIW, in the next version DevTool will be embedded (see https://dartcode.org/releases/v3-13/#embedded-devtools-improvements) by default.

@jacob314 does DevTools officially support Edge? If so, we could add Edge support to https://github.com/dart-lang/browser_launcher and pass a browser preference to `launchDevTools`?

**Comment by jacob314** [comment]
Now that we are supporting Flutter web our browser compatibility story is a lot better than when we were using raw HTML. FireFox and Safari should also work fine although there may be a noticeable performance hit.

**Comment by DanTup** [comment]
@jacob314 IIRC - the reason we pushed launching the browser to DevTools was so that it could locate Chrome more easily (there was already Dart code to do it). If we're going to support launching in the users default browser, it might make sense for the editor to just launch it directly rather than extending DevTools to handle this - it's what we already do if DevTools reports an error launching Chrome (or you're running in a cloud IDE), so we could just skip that attempt.

WDYT - shall I add a setting in Dart-Code to select between Chrome (which goes through the DevTools service) and Default Browser (which we just launch) in Dart-Code?

**Comment by DanTup** [comment]
I did the latter - there's now an option `dart.devToolsBrowser` that accepts `chrome` or `default` (defaults to `chrome`). If you set it to default, it will just open in your system default browser. The default will remain as launching in Chrome (via DevTools service extension) for the reasons mentioned above.

**Comment by jacob314** [comment]
Sorry I missed this. Having an option to use the default browser now that we support more browsers sounds good.

**Comment by Nalin-2005** [comment]
> I did the latter - there's now an option `dart.devToolsBrowser` that accepts `chrome` or `default` (defaults to `chrome`). If you set it to default, it will just open in your system default browser. The default will remain as launching in Chrome (via DevTools service extension) for the reasons mentioned above.

A Dart noob here, how do I set that option?

**Comment by DanTup** [comment]
Yep, it's in your VS Code settings. Press F1, find **Preferences: Open Settings (UI)** then search for `devtoolsbrowser`.
