### ISSUE TITLE
Not detecting the scope variable

### ISSUE THREAD

**Issue by zmp2000** [Dart-Code/Dart-Code#2237]
After inspecting the scope, the extension did not detected the variable, instead it detected as generic "source.dart" 
I think it should have been detected as "variable.name.source.dart"

![image](https://user-images.githubusercontent.com/1984798/73224834-8059ac80-4149-11ea-9ebd-88c79e06720d.png)

**Comment by DanTup** [comment]
I think this may be solved by https://github.com/Dart-Code/Dart-Code/pull/2203, which is work to move from the TextMate grammar file to using semantic info from the analysis server directly (this will make it more accurate and solve a couple of bugs we have).

Finishing/merging the work requires VS Code finalizing (and shipping) the API which seems to be assigned to the February release.

**Comment by DanTup** [comment]
With the semantic token work in https://github.com/dart-lang/sdk/commit/cb2ede57b7c91fb61c0cb05971cc1823faee2086 you'll now be able to theme using semantic tokens instead, which will produce more reliable tokens. In the example above, there will be a `property` token with the `declaration` modifier for `itemSuggestions`.

In order to get the fix you'll need Dart-Code v3.18.0 (a preview release should be available later today/tomorrow), be using LSP Preview, and have a Dart SDK from after yesterday ([the most recent nightly](http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/) works, and of course the next releases of Dart/Flutter SDKs will include this).

**Comment by DanTup** [comment]
Due to some last minute issues, support for LSP 3.16 (which supports semantic tokens) won't be included in v3.18, but hopefully the next release after that.
