### ISSUE TITLE
Support (as a preview option) using the LSP protocol for analysis server communications

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2238]
In Eclipse L4P4E I see the following log messages:

[t=1580217833406] LSP4E to org.eclipse.dartboard.server:
{"jsonrpc":"2.0","id":"37","method":"textDocument/completion","params":{"textDocument":

The logging in Dartcode seems not to be logging the language server communication but the analysis server:

3:03:38 PM] [Analyzer] [Info] <== {"event":"completion.availableSuggestions",

Is is planned to move the logging to LSP based communication.

**Comment by DanTup** [comment]
Right now the Dart extension doesn't use LSP. What you're seeing logged is the original analysis server protocol (pre-LSP). It should essentially have the same contents, just in a different form (though completions are a bit tricky, since `availableSuggestions` are a way to preload them into the editor for performance reasons).

There is ongoing work to migrate to LSP (currently only on the `lsp` branch here) and as part of that, the logging would show LSP traffic instead of the original JSON protocol. I'm hoping to merge it soon (probably sometime in Feb) so that it would available for testing (though there are still some rough edges or unimplemented functionality).

I don't think there's actually an issue for this work (there is a [project here](https://github.com/orgs/Dart-Code/projects/1)) so I'll rename this one slightly for it.

**Comment by bsutton** [comment]
I don't believe so. I've just uninstalled flutter/dart-code and then re-installed the standard flutter extension from the market place which re-installed dart-code.

The same problem persists.

**Comment by DanTup** [comment]
@bsutton was that comment intended for another issue?

**Comment by bsutton** [comment]
Sorry yes.
