### ISSUE TITLE
Bumping pubspec.yaml build number triggers pub get

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#2245]
I have a build & deploy script that bumps the build number with this line

```
perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml
```

However, when I do this, Dart-Code fetches packages from `pub` right as the script begins the build/compile stage.

1) Are there any issues with `pub get` running simultaneously with `flutter build` ?
2) Is there any way to suppress auto `pub get` temporarily in a shell script?

**Comment by DanTup** [comment]
> Are there any issues with `pub get` running simultaneously with `flutter build` ?

There could be. Flutter puts locks around its operations, but `pub` doesn't and [that could cause issues](https://github.com/dart-lang/pub/issues/1178). VS Code should run `flutter packages get` for Flutter projects though, in which case they'd probably be forced to run sequentially (wasteful, but not dangerous). If it's running `pub get` for a Flutter project, I'd say that's a bug.

> Is there any way to suppress auto `pub get` temporarily in a shell script?

The only way I could think would be to overwrite the setting to disable `runPubGetOnPubspecChanges`. It wouldn't be difficult (it's a JSON file), but it might be messy (and preserving comments in the file may be harder). The reason it's triggering is likely that VS Code sees the file change on disk, and tells us that it changed (which just looks like a user edit to us).

**Comment by lukepighetti** [comment]
It's running `flutter packages get` I think. I'm not sure. The purpose of this issue is just that the normal thing that happens when you modify `pubspec.yaml` is triggering when you bump the build number.

**Comment by DanTup** [comment]
Yeah, but that's really by design. The setting is to fetch packages when the file changes, and the file is being changed.

While we could probably make this cleverer, it would mean leaking details about the contents/structure of pubspec into the VS Code plugin that it doesn't normally care about. My assumption was that `pub get` would be pretty quick when there's nothing to do so this didn't seem worthwhile.

Is your issue just with how long it takes? If so, what sort of times are you seeing?

**Comment by lukepighetti** [comment]
I fooled around a little more. What happens is it hangs during the build process

```
[app] flutter packages get
Waiting for another flutter command to release the startup lock...
```

Here's the complete `deploy.sh` script

```
# Generate icons
flutter pub run flutter_launcher_icons:main

# Bump build number
perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml

# Build iOS for Fastlane
flutter build ios --release --no-codesign

# Trigger Fastlane for iOS
(cd ios && fastlane beta)
```

**Comment by DanTup** [comment]
Does it every complete? My guess here is that your shell script is hitting the `flutter build` before the command kicked off by VS Code has spawned Flutter to aquire a lock. I would expect that once your `flutter build` (in the shell script) completes, it would release the lock and then the VS Code process would complete. Does that happen?

**Comment by lukepighetti** [comment]
I think you are correct. I would say this appears to be a cosmetic issue.

**Comment by DanTup** [comment]
If it's just one project, you could disable `runPubGetOnPubspecChanges` for that one project (using "Workspace Settings" that would be saved at `./.vscode/settings.json`). Otherwise, I don't think there's really a clean way to fix this without starting to parse pubspec (but I'd prefer not to just for this case).

**Comment by lukepighetti** [comment]
I will close this issue, thanks Dan!
