### ISSUE TITLE
Flutter: Vscode Live Share Intellisense and auto-complete is not working on guest 

### ISSUE THREAD

**Issue by chaucaocmg** [Dart-Code/Dart-Code#2269]
Work fine on host but not showing on guest. Everything else works fine on guest, all files are showed in the explorer. Guest showes warning "For full Dart language support, please open a folder containing your Dart files instead of individual loose files"

Host:
![image](https://user-images.githubusercontent.com/25887242/75088596-68850680-5504-11ea-8085-0eb5430495c7.png)

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US) 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (2 available)
vscode 1.42.1

Guest:
![image](https://user-images.githubusercontent.com/25887242/75088578-1e038a00-5504-11ea-812c-8c4a4e373c24.png)
![image](https://user-images.githubusercontent.com/25887242/75088651-0e387580-5505-11ea-824b-7c04c25ddb25.png)

[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\tools\android-sdk
      but Android SDK not found at this location.
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.42.1)
[!] Connected device
    ! No devices available
vscode 1.42.1

**Comment by DanTup** [comment]
@lostintangent how does completion work on a live share client - should it be routed from the host?

The warning shown above is something we show if you open a `.dart` file without a folder (eg. it's outside of the workspace folders). This is because we don't currently support spawning the language server without one or more workspace folders. I don't think it's related to the issue of completion not working (my understanding was that the client doesn't even need the language extension?).

**Comment by artofbeinghuman** [comment]
Having the same issue. Any results?
Vscode recognizes that I am looking at .dart files (as a guest), but it doesn't start the necessary flutter intellisens server such that code completetion works.

**Comment by DanTup** [comment]
> but it doesn't start the necessary flutter intellisens server such that code completetion works

This is expected. Live Share is supposed to run everything on the host - it's not necessary for the client to even have the Dart extension installed. All things like Intellisense should be routed through the host:

https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/extensions#project-specific-extensions

> Host-installed extensions, which support the core editing, building and debugging of an application, and are specific to a language/platform/library/SDK, should be automatically available to guests, without requiring them to install anything.

If my understanding is correct, this feels like a Live Share bug. If the code completion works on the host, it should proxy that to the client.

I would recommend raising an issue at https://github.com/MicrosoftDocs/live-share about this (feel free to CC me so if it turns out we're doing something that isn't supported or is triggering bugs, we can try to work around it).

**Comment by DanTup** [comment]
There's an open issue at https://github.com/MicrosoftDocs/live-share/issues/3509 that is probably the issue described here. We can work through it there, and re-open/file an issue here if it turns out we need to make changes.

**Comment by zahi71** [comment]
I have the best solution 💯 
just open the folder that contains the file.dart like a workspace.

**Comment by LSViana** [comment]
> just open the folder that contains the file.dart like a workspace.

@zahi71 What do you mean? I've joined a live share session and _I think_ I have the folder open as a workspace already:
![image](https://user-images.githubusercontent.com/21217790/104375346-ffcec000-5501-11eb-897d-1e01d4c2315a.png)
