### ISSUE TITLE
add a preference to pass extra command-line arguments to analysis server

### ISSUE THREAD

**Issue by skybrian** [Dart-Code/Dart-Code#229]
This would help for debugging analysis server issues. Some useful flags include
 
```
  --instrumentation-log-file the path of the file to which instrumentation data will be written
  --port  the http diagnostic port on which the server provides status and performance information
```

There are some less generally-useful flags too that we use for internal development.

**Comment by DanTup** [comment]
These already exist (`analyzerDiagnosticsPort`, `analyzerInstrumentationLogFile`) though there's a bugfix for additional args (#225) that hasn't been released yet.

These aren't in the json schema so they're effectively hidden options, since most users won't need them (unless trying to diagnose something, in which case we can tell them). You can see the full list of supported options for the current version [here](https://github.com/Dart-Code/Dart-Code/blob/d04d392cd141ab81c71b557955fb4be03ab4d18a/src/config.ts#L25).

Hope this helps!
