### ISSUE TITLE
CompletionItemProvider#resolveCompletionItem must not change insert behaviour

### ISSUE THREAD

**Issue by jrieken** [Dart-Code/Dart-Code#2290]
The VS Code [telemetry](https://github.com/microsoft/vscode/blob/c2a604a18c5d3696f62267feadfb1d7583bcbccd/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L890-L914) shows that this extension changes the insert behaviour of a completion item during resolve. 

This is bad and [discouraged](https://github.com/microsoft/vscode/blob/1bbce1ce03d60c81d1247edfdf502d1aefe456db/src/vs/vscode.d.ts#L3694-L3696) because there is *no* guarantee that `resolveCompletionItem` is ever called[^1] and therefore the insert behaviour of completion items from this extension is likely to be flaky and unpredictable. 

[1] The resolve-call is meant to load detail and documentation. It is triggered when focusing items in the suggest widget but not when directly selecting an item (e.g mouse click) or when using tab-complete. Also, inserting a completion item *never* awaits the resolving of it. Because of that fast users (and/or a slow extension hosts) can run into this regularly.

**Comment by DanTup** [comment]
@jrieken thanks for the info! Is there a way for me to see the log entries written when this occurs?

The only think I can think off the top of my head is that if you complete something that automatically inserts an import, it may need to add a prefix (alias) to the import if there's already a symbol with the same name imported into the document (for example you have an `Image` class imported, but select `Image` from another library, it may insert `prefix.Image` and add "import foo as prefix" at the top. If that's the only place, I'll see whether we can get that info up-front to set the insert text.

**Comment by jrieken** [comment]
> @jrieken thanks for the info! Is there a way for me to see the log entries written when this occurs?

👇 yes, we append a message to the extension host log, but only for the first violation. At that code point you will also find the checks spelled out (in code)
https://github.com/microsoft/vscode/blob/c2a604a18c5d3696f62267feadfb1d7583bcbccd/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L904

**Comment by DanTup** [comment]
Ah great, I'll take a look - I hadn't seen it in the log before, but if it's only triggered for the case mentioned above that might be why. Thanks!

**Comment by DanTup** [comment]
It turns out this is more complicated than I thought. From the docs above:

> *Note* that accepting a completion item will not wait for it to be resolved. Because of that `insertText`, `additionalTextEdits`, and `command` should not be changed when resolving an item.

This covers all document edits, not just `insertText`. This means we need to know all of the edits for a completion (including how to insert its import statements) up-front when we build the completion list.

Right now, this isn't possible (without sending potentially thousands of request to the server during the initial build - one per item). With a plan to move to LSP, it also doesn't make sense to change this to then migrate away.

So this should just be fixed this in the LSP implementation (it current has the same issue, doing a lot in resolve) and may need to consider using isIncomplete=false to do more filtering on the server (to avoid sending a huge amount of data for the imports for all unimported classes).

**Comment by jrieken** [comment]
Understood - a trick that you can try is to have a command that does the extra edits. It has downsides (async to completion, outside the current undo operation) but if low-hanging for you it could be a workaround.

**Comment by DanTup** [comment]
I'm not sure if it'd work reliably if the request to the server came after the initial edit (I have to include the offset in the request to the server to get the edits - I'm not sure what it does with that internally).

Are there any plans to change the current behaviour in the short-term? Although theoretically flaky, nobody has complained about this yet (so keeping it working this way, and preserving a single undo step etc. might be better than a quick workaround).

I'll also try to start a thread with Dart devs about coming up with a better solution for the LSP server.

By the way - part of the way the Dart server implemented completions for unimported items was to pre-load them into the client (during initial analysis, it sends lists of all symbols, what types they are, etc.) and then when invoking completion it might return a note like "also include all of the constructor completions from libraries x, y, z". This cuts down on sending a lot of the same stuff in every completion invocation (since most completions come from libraries that are fixed, or not being modified much).

I don't know if it's common for languages to have huge numbers of completion items, but if it is, maybe VS Code/LSP might consider an API to support something like this?

**Comment by jrieken** [comment]
> Are there any plans to change the current behaviour in the short-term?

We unfortunately cannot - here is more of the back story: https://github.com/microsoft/vscode/issues/73311#issuecomment-494807568

> By the way - part of the way the Dart server implemented completions for unimported items was to pre-load them into the client 

Funny, same idea is being disucssed currently, e.g with TS https://github.com/microsoft/TypeScript/issues/36265#issuecomment-602461130 and also others. Would be interested to hear from you if that works for dart

**Comment by DanTup** [comment]
> We unfortunately cannot - here is more of the back story: microsoft/vscode#73311 (comment)

Sorry, I meant will it remain as it is (eg. if I don't change anything, it will continue to function as it does today - which in theory is unreliable, but in practice is working alright). Eg. there is no impending break if it took time to come up with a good solution?


> Funny, same idea is being disucssed currently, e.g with TS
> Would be interested to hear from you if that works for dart

It's what the current Dart extension is doing for unimported items (original completions are still mostly provided inline in the initial server response). In my opinion it works fairly well (with some niggles that I think are mostly implementation-specific) but it is quite complex and puts a lot on burden on anyone building a client that interacts with this API. Right now, the server builds the edits (which is the cause of this async request in resolve) though in theory, maybe these could be calculated on the client with a little more info in the original data/server response.

Of course, with LSP there's no opportunity to do this on the client, so currently the only fix would be to build all the edits up front (and that might mean needing to truncate the results and use isIncomplete=true in order to prevent huge JSON packets). This has some drawbacks too (for ex. increased resource usage from lots of requests and extra delay if you want to complete something that was truncated from the original list).

FYI @devoncarew @bwilkerson - this issue is about avoiding generating edits for completions asynchronously - this is currently how it's being done, but it may be unreliable if you type/complete quickly as VS Code won't stall editor typing for an async request. The LSP server is currently doing the same (building edits in the `resolve` call) so will also need some sort of fix.

**Comment by jrieken** [comment]
>  Eg. there is no impending break if it took time to come up with a good solution?

As of today (and tomorrow) we have no plans to break this and we are also aware of the complexity in fixing this. This sometimes comes up as issue and I feel it contributes to an overal "vscode a is strange/random"-feeling but this isn't major pain yet

**Comment by DanTup** [comment]
That's good to know, thanks.

I was thinking a little more about using isIncomplete=true and sending less items from the server (so that they could be fully-populated), but it seems like it has the same issue - if the user is typing quickly, we might not get the completion item to the editor fast enough (the only difference is that the delay is in them seeing the item they want in the list, rather than between them seeing it and it getting the full edits).

Would it feasible to insert the original insertText, but replace the range if it's updated in resolve? In our case, the only time the `insertText` should change is when the import being inserted requires a prefix. Eg. you complete the `Color` class from another library but already had another `Color` in scope. In that case we would insert `somePrefix.Color`. To the user, they would see `Color` inserted and can continue typing, and then `somePrefix.` would be inserted "later" (in reality it would likely be very quickly). Similarly, the additional edits could be applied later (with some caveats to deal with if they overlap where the user is typing).

@bwilkerson @scheglov - I'm curious how this works in IntelliJ now - my understanding is that you don't even call `getSuggestionDetails` until the user commits to that item. Is the editor blocked for the duration of the `getSuggestionDetails` to the server?

**Comment by jrieken** [comment]
> Would it feasible to insert the original insertText, but replace the range if it's updated in resolve? In our case, the only time the insertText should change is when the import being inserted requires a prefix.

Unfortunately not - the range is used select the filter-prefix and that really not change while an item is resolved. It could mean that an item suddenly gets hidden or re-rank when being resolved. In practise we are caching the range and this won't happen. We have two categories of changes that should not happen. Really bad [(`item.label, item.sortText, item.filterText, item.insertText, item.range`)](https://github.com/microsoft/vscode/blob/c833780356295b72f060db71f3c99c49c042c839/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1039) and not so bad but still bad [(item.additionalTextEdits, item.command)](https://github.com/microsoft/vscode/blob/c833780356295b72f060db71f3c99c49c042c839/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1054). The first category has the potential to wreck completions (like describes above) while the latter is a good change for randomness - e.g you will run into a missing import whenever you select a suggestion with the mouse.

**Comment by DanTup** [comment]
> It could mean that an item suddenly gets hidden or re-rank when being resolved

Isn't that only the case if the filterText/sortText/label are updated too? We're only changing `insertText` (since the prefix shouldn't be included in sort/rank/display label).

Alternatively, if updating `additionalTextEdits` is less critical- could you maybe wait for resolve to complete before applying that, allowing us to put the prefix into there? Eg. `insertText` remains as `Color` and we put an `additionalEdit` of `prefix.` (thta's inserted at the right location)?

**Comment by jrieken** [comment]
Right, `insertText` is less critical, only flaky. Waiting for `additionalTextEdits` won't be possible because as soon as one types all indicies are invalid and it cannot be applied anymore. That where `command` can help - when that runs its to find/validate the planned insertion position and perform or discard further edits

**Comment by DanTup** [comment]
> as soon as one types all indicies are invalid and it cannot be applied anymore

I was thinking that if VS Code knew that nothing had changed from the start of the doc to the insertion, any inserts for before then would still be valid (though I admit that feels a bit wonky and could also lead to intermittently strange behaviour).

I think using a command would only work if we could validate the positions easily (or recalculate them). Perhaps that could be done, though since it would add another undo step, I'm not sure it's a better solution than the solution we have today (even if in theory it's a race).

Also, with the plan to move to LSP, that probably wouldn't work there (we couldn't really send a command/args on every item pre-resolve, the JSON would become even bigger).

**Comment by jrieken** [comment]
> I was thinking that if VS Code knew that nothing had changed from the start of the doc to the insertion, any inserts for before then would still be valid (though I admit that feels a bit wonky and could also lead to intermittently strange behaviour).

Just fyi that I am experimenting with such a pragmatic approach. No promises! Actually, format on type is doing this and I don't know how people have noticed. The plans is the following: when a completion is inserted but not yet resolved, proceed with inserting but also resolve. Once resolved compare additional text edits with the edits that have occurred in the meantime. If there is no overlap apply them, otherwise drop them. This is definitely "wonky" at times but I guess yield overall better results than what we have today.

**Comment by DanTup** [comment]
Cool, that sounds great. Let me know how it goes, and if you can make a macOS binary with the changes I'm happy to do some testing with Dart (I can easily rig resolve to be slow to see what the effects are). Thanks!

**Comment by jrieken** [comment]
@DanTup Tomorrows insiders contains the new pragmatic approach. That is: when inserting an item that not yet resolved, we insert it straight wait and when resolving is done we try to apply additional text edits. That should work unless in the meantime edits have occurred before them.

**Comment by DanTup** [comment]
@jrieken seems to work great in my testing! Initially it seemed like it wasn't working, but it turned out to be that the cancellation token still fires. I suspect this is intended and it's up to us to ignore it if we may want to provide additional edits.

It appears to only do `additionalTextEdits` and not changes to `insertText`. I presume that's also intended, and that I should insert any prefix as an additional text edit placed before the insert range?

**Comment by DanTup** [comment]
Something like this seems to work, though if VS Code could do it, it would probably be more reliable :-)

```ts
if (item.range && typeof item.insertText === 'string'
	&& newInsertText !== item.insertText
	&& newInsertText.endsWith(item.insertText)) {
	item.additionalTextEdits.unshift(
		new vscode.TextEdit(
			new vscode.Range(item.range?.start, item.range?.start),
			newInsertText.substring(0, newInsertText.length - item.insertText.length),
		),
	);
}
```

I did try this:

```ts
item.additionalTextEdits.unshift(
	new vscode.TextEdit(
		item.range,
		newInsertText,
	),
);
```

However that fails, because `item.range` is the original range to replace, which is likely shorter than the new range once the original text has been inserted, so the last part of the line is repeated.

**Comment by jrieken** [comment]
> It appears to only do additionalTextEdits and not changes to insertText.

Yes this is ONLY about additionalTextEdits. The insertText MUST be proper when returning completions from provide - additional edits can be done via, well, "additionalTextEdits". Allowing to asynchronously change the insertText would mean that completions mutate after inserting, e.g `foo|` could become `bar|`. So, use additional edits for a prefix and also not that it cannot overlap or be after the insertText-edit or other concurrent edits (which shouldn't be a problem for a prefix)

**Comment by DanTup** [comment]
Ok, I'll handle that here in the provider. Do you know if anything needs doing here for LSP to behave the same or should it all just work the same (since the client is just providing these same methods)?

Thanks!

**Comment by jrieken** [comment]
For LSP it shouldn't matter, it's just the client calling this function now.

**Comment by DanTup** [comment]
Great, thanks!

Turns out prefixed were removed from the auto-import code (https://github.com/dart-lang/sdk/commit/4f8f592b51990612335b66dccd5269aab09b96dd) so I believe there's actually nothing to do here - the telemetry you got is likely from SDK versions before it was removed.

If the number of instances of this coming from Dart-Code doesn't seem to have gone down significantly since you opened this, please let me know and I will do some more digging (I certainly can't repro it running through a large number of completions here).
