### ISSUE TITLE
extension 'flutter' cannot format '.dart'

### ISSUE THREAD

**Issue by Liqiankun** [Dart-Code/Dart-Code#2300]
![屏幕快照 2020-03-15 13 14 09](https://user-images.githubusercontent.com/11532418/76695851-09f41800-66bf-11ea-9350-8f1483f60c0e.png)
## Environment
* vscode: 1.43.0
* flutter extension: 3.8.1
* dart extension: 3.8.1
* settings.json
```
{
  "editor.fontSize": 13.5,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "Dart-Code.flutter"
}
```
## Expectation
![屏幕快照 2020-03-15 13 17 39](https://user-images.githubusercontent.com/11532418/76695873-6a835500-66bf-11ea-989e-e9e46b9d1320.png)

**Comment by DanTup** [comment]
> `"editor.defaultFormatter": "Dart-Code.flutter"`

The formatter for Dart is in the Dart extension (since it should work for non-Flutter users too), so if you're setting the formatter explicitly for Dart you should set it to `Dart-Code.dart-code`.

That said, this formatter can *only format Dart, so you shouldn't set it as the default formatter for all lanuguages, as it will prevent you from being able to format other languages.

Unless you have good reason, you should be able to just delete that line from your settings - VS Code will use the Dart formatter for Dart files automatically without any specific configuration.

**Comment by Liqiankun** [comment]
@DanTup Thanks for the reply! But It doesn't work for me.

**Comment by Liqiankun** [comment]
@DanTup I figured it out. I should add `,` after `LinearGradient()`!

**Comment by DanTup** [comment]
Sorry, it seems like there were two issues described and I only covered the first. The initial error saying Flutter can't format was for the reason I gave above. Trailing commas are the correct way to force the specific formatting you wanted - there's a little more info about this on the Flutter website here:

https://flutter.dev/docs/development/tools/formatting#using-trailing-commas

**Comment by vaibhavcs99** [comment]
> 
> 
> > `"editor.defaultFormatter": "Dart-Code.flutter"`
> 
> The formatter for Dart is in the Dart extension (since it should work for non-Flutter users too), so if you're setting the formatter explicitly for Dart you should set it to `Dart-Code.dart-code`.
> 
> That said, this formatter can *only format Dart, so you shouldn't set it as the default formatter for all lanuguages, as it will prevent you from being able to format other languages.
> 
> Unless you have good reason, you should be able to just delete that line from your settings - VS Code will use the Dart formatter for Dart files automatically without any specific configuration.
> 
> Let me know if this doesn't seem to work for you. Thanks!

Thank You, this is working for me now!
