### ISSUE TITLE
`Create missing override` fails with methods that use @required

### ISSUE THREAD

**Issue by atn832** [Dart-Code/Dart-Code#2307]
For example if I make a class that implements FirebaseAuth, it'll generate:

```dart
  @override
  Future<AuthResult> createUserWithEmailAndPassword({String email, StriStriString pppassword}) {
      // TODO: implement createUserWithEmailAndPassword
      throw UnimplementedError();
    }
  
    @override
    Future<List<String>> fetchSignInMethodsForEmail({String email, Stri   // TODO: implement fetchSignInMethodsForEmail
      throw UnimplementedError();
    }
```

instead of
```dart
  Future<AuthResult> createUserWithEmailAndPassword({
    @required String email,
    @required String password,
  }) {
      // TODO: implement createUserWithEmailAndPassword
      throw UnimplementedError();
  }

  Future<List<String>> fetchSignInMethodsForEmail({
    @required String email,
  }) {
      // TODO: implement fetchSignInMethodsForEmail
      throw UnimplementedError();
  }
```

**Comment by DanTup** [comment]
Thanks for the report! I can repro, and was able to trim down to a smaller repro:

```dart
import 'package:meta/meta.dart';

class MyTestClass {
  void verifyPhoneNumber({
    @required String phoneNumber,
    @required Duration timeout,
  }) {}

  Future<void> signInWithCustomToken({@required String token}) async {}
}

class A implements MyTestClass {}
```

Invoking "create missing overrides" on A results in :

```dart
class A implements MyTestClass {
  @override
  Future<void> signInWithCustomToken({String token}) {
      // TODO: implement signInWithCustomToken
      throw UnimplementedError();
    }
  
    @override
    void verifyPhoneNumber({String token}) {
   , Duration timeout}) {
    // TODO: implement verifyPhoneNumber
  }
}
```

I'll see what I can find!

**Comment by DanTup** [comment]
@bwilkerson I think something might be wrong in the analyzer here. When this happens, the `linkedEditGroups` for the fix include this group:

```
{
	"positions": [
		{
			"file": "/Users/danny/Dev/Google/flutter/examples/flutter_gallery/lib/2307.dart",
			"offset": 321
		},
		{
			"file": "/Users/danny/Dev/Google/flutter/examples/flutter_gallery/lib/2307.dart",
			"offset": 458
		}
	],
	"length": 11,
	"suggestions": []
},
```

These two offsets correspond to the text `token` and `phoneNumber`, which do not have the same length of 11. I think they have incorrectly been lumped together as a linked edit group that they should not (similarly, the "suggestions" for the type `String` are also in a linked edit group, which seems incorrect - since it suggests that both of the `String` types are linked and should be the same, but I don't think that's the case):

![Screenshot 2020-03-23 at 12 01 20](https://user-images.githubusercontent.com/1078012/77314695-0f281700-6cfe-11ea-9dc9-170ba62c96b8.png)

I can only repro in Flutter, but that might be due to SDK version differences.

**Comment by DanTup** [comment]
Weirdly, I tried the latest Dev verison of the Dart SDK, and most recently nightly, but cannot reproduce. However it reproduces with latest Flutter master as well as the master version from around 2 weeks ago I had before pulling. I don't know it this means Flutter is somehow impacting this.

I can also repro in Android Studio though, suggesting the issue is on the server, so I'll raise an issue in the SDK repo.

<img width="455" alt="Screenshot 2020-03-23 at 12 17 02" src="https://user-images.githubusercontent.com/1078012/77315876-3e3f8800-6d00-11ea-82f1-927224b873c5.png">

**Comment by DanTup** [comment]
I've opened https://github.com/dart-lang/sdk/issues/41147 in the SDK repro for this, as it seems like  problem in the analyzer and affects Android Studio too.

**Comment by atn832** [comment]
Thank you for investigating!
