### ISSUE TITLE
Local variables not appearing in VSCode debug panel

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#2317]
Hi,

This isn't generally a problem, but I'm hitting it regularly with with the code I'm debugging right now. 

Here's what it looks like.
<img width="967" alt="Screen Shot 2020-03-26 at 5 33 59 AM" src="https://user-images.githubusercontent.com/42326/77631764-6c50e200-6f23-11ea-88d3-d5142d0e0bb7.png">

Note that I'm breaking on an exception, and that the "Locals" node in the debugger is open, but is not showing anything. I can jump up and down the stack, and the problem persists.

Is there something I can send that would help diagnose?

**Comment by shyndman** [comment]
Ah, here's another potentially relevant detail:

Hovering over a local variable reference displays the appropriate tooltip, and it's correct. I get the full object tree.

**Comment by DanTup** [comment]
Is this when you're on a stack frame that has passed an async gap from the top frame? If so, it could be https://github.com/Dart-Code/Dart-Code/issues/1507 (the issue is that after the async gap, the stack frame is fabricated and not real, so the local variables are not accessible).

Otherwise, if you can repro in a small example so I can test the same thing here, or you can capture a log with **Dart: Capture Logs** and ticking just **Debugger**, that might help track it down. Thanks!

**Comment by shyndman** [comment]
Seems similar, but I am getting tooltips on the locals. 

I'll do some investigating and get you what you need.

**Comment by DanTup** [comment]
The tooltips might still work because they use `evaluateRequest` (so as long as the VM knows how to evaluate them, they'll work). The local variables list is taken from the stack frame given by the VM.

Should be clearer if you can get a log if a repro I can run here - thanks!

**Comment by shyndman** [comment]
Definitely. It's on my list for the next couple days. Thanks @DanTup
