### ISSUE TITLE
Support auto import for extension methods

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2326]
Currently if I want to call a extension method, I can't just auto import with the quick fix.

`numberFormat.formatAllowNull(widget.value)`

In the example the method "formatAllowNull" is a extension method, but clicking on the bulb doesn't provide the option to auto import it. Is this something that will be supported?

**Comment by DanTup** [comment]
Thanks for the suggestion! The quick-fixes come from the analyzer in the SDK, so this would need to be implemented there. It seems like that's already been done (dart-lang/sdk#38894) but it might not have made a stable release yet.

If it's not working for you on latest dev/master branches, let me know. Thanks!

**Comment by nickmeinhold** [comment]
This isn't working for me. If I create a new project and add a file with an extension, eg:

<details><summary>extensions.dart</summary>
<p>

```
import 'package:flutter/material.dart';

extension TestContextExt on BuildContext {
  void blah() {
    print('blah');
  }
}
```
</p>
</details>

I can use the extension function if I manually add `import 'extensions.dart';` but clicking on the bulb or using `Cmd .`, I get no "Import library..." option.

<details><summary>flutter doctor</summary>
[✓] Flutter (Channel master, 1.18.0-11.0.pre.6, on Mac OS X 10.15.4 19E287,
    locale en-AU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (5 available)
</details>

**Comment by DanTup** [comment]
@nickmeinhold thanks, I've comment on https://github.com/dart-lang/sdk/issues/38894 - I suspect that issue will be re-opened.

**Comment by behnam-lum** [comment]
I still experience the same issue with Dart 2.10.1

**Comment by DanTup** [comment]
@behnam-lum the issue linked above is still open, so this hasn't been resolved yet.

This issue was closed as there's nothing to do here, once fixed in the SDK it will show up here automatically.

**Comment by i-show** [comment]
Following

**Comment by xzhorikx** [comment]
Still waiting for it to be implemented

**Comment by joelbrostrom** [comment]
I have the same issue.

**Comment by hienhodeveloper** [comment]
I really need to update this feature soon

**Comment by RakaAlrian** [comment]
It's been over a year, and this issue still exist☹

**Comment by Dohmanlechx** [comment]
I need to add `import 'package:collection/collection.dart';` manually every time I want to use the extension method `firstWhereOrNull()` which was added by the Dart team itself. Come on, this is a real issue.

**Comment by DanTup** [comment]
This is something that needs support from the analysis server, it can't be implemented directly in the VS Code extension. The issue tracking this that you can 👍  or subscribe to is https://github.com/dart-lang/sdk/issues/38894.

It's not trivial to implement because of how the completion currently works (see https://github.com/dart-lang/sdk/issues/38894#issuecomment-823514299) but it's clear there's a lot of demand for this and it's being thought about.

It's always better to just add 👍 s to issues rather than posting "me too" comments. These comments can be quite noisy when you're subscribed to a large number of issues and just scanning through a lot of them can take time that could be better spent. The developers definitely understand the importance of these issues.

I'll lock this issue in favour of https://github.com/dart-lang/sdk/issues/38894 to keep discussions in one place.
