### ISSUE TITLE
Icon previews missing in v3.9.0

### ISSUE THREAD

**Issue by eunseokyang** [Dart-Code/Dart-Code#2333]
![noname](https://user-images.githubusercontent.com/54825838/78502119-5ef4ec80-779a-11ea-9316-dc4989185f3b.png)

It shows an icon preview in other IDE, like android studio or intelliJ,
but doesn't work in VS Code.

**Comment by DanTup** [comment]
Thanks for the report! I've published v3.9.1 which fixes this issue, and also added a pre-publish step that checks the icons have been checked out (they're in a Git submodule that's easy to miss after switching between branches) to prevent this happening again.

**Comment by srinivas-iosdev** [comment]
> Thanks for the report! I've published v3.9.1 which fixes this issue, and also added a pre-publish step that checks the icons have been checked out (they're in a Git submodule that's easy to miss after switching between branches) to prevent this happening again.

HI @DanTup, I can see this issue again in VSCode Dart extension of latest version (v3.22.0). Please fix this issue
<img width="433" alt="Screenshot 2021-06-01 at 9 20 32 PM" src="https://user-images.githubusercontent.com/76642381/120353310-35444080-c31f-11eb-9964-7df98469f1f2.png">

**Comment by DanTup** [comment]
@srinivas-iosdev this was a slightly different issue - that's a new icon that hadn't been included in the extension (previews are shipped inside the extension to avoid needing to fetch them from the web in the editor). I replied in #3376 but it's all fixed in the new release of the Dart extension (you may need to run the **Extensions: Check for updates** command to force VS Code to check for updates before its usual schedule).

**Comment by lemosemanuel** [comment]
I don't understand nothing bro sorry , where i need to change  Icon previews missing in v3.9.0? . What exactly i need to do . Witch command i need to run ?

**Comment by DanTup** [comment]
@lemosemanuel this is an old issue. Icons are currently broken because of a bug in VS Code, see:

- https://github.com/microsoft/vscode/issues/119786
- https://github.com/microsoft/vscode/issues/128315
