### ISSUE TITLE
The casing of the open workspace folder does not match the casing on the underlying disk

### ISSUE THREAD

**Issue by wemersonrv** [Dart-Code/Dart-Code#2342]
Hello. 

I have a folder that when open it in vscode gives me the message below: 

> The casing of the open workspace folder does not match the casing on the underlying disk; please re-open the folder using the File Open dialog. Expected D:\DadosImportantes\dev\Projetos\Pixeldev\sca\mobile but got D:\DadosImportantes\dev\projetos\Pixeldev\sca\mobile

Closed and reopen but not works. Message still there.

Using VSCode on windows 10.

**Comment by DanTup** [comment]
How are you launching VS Code? If you're launching it from a terminal, the issue is likely that the terminal has the wrong casing for its current directory. This is because on Windows if you type `cd MyFoLDER` it will use that casing for the current working directory, even if it's `MyFolder` on disk.

**Comment by wemersonrv** [comment]
> are you launching VS Code and opening the folder? If you're launching it from a terminal, the issue is likely that the terminal has the wrong casing for its current director

This issue happens in both cases:

1. In terminal, go to project folder and rum: `explorer .`
2. Open VS Code from start menu and then open the project folder.

**Comment by DanTup** [comment]
> In terminal, go to project folder and rum: explorer .

It sounds like when you're doing this, you are ending up in the folder with the wrong case. Eg. if you type (assuming PowerShell):

```
write-host $pwd.Path
```

If this casing does not match the actual folder casing on your disk, then when you open explorer/ VS Code, it may also have the incorrect casing. The casing on your disk has a capital P for "Projetos", but when you're opening it in VS Code, it has a lowercase "p".

**Comment by wemersonrv** [comment]
ok. thanks.

I will change my dev machine to a macos soon. So i believe this stuffs will be solved!

**Comment by wrecklass** [comment]
Ya, but other than switching to Linux or macOS, is there a solution to this issue? Or can we just ignore it since Windows doesn't care about file system Cases?

**Comment by DanTup** [comment]
@wrecklass

> Ya, but other than switching to Linux or macOS, is there a solution to this issue?

Yes, you should be able to open the folder as described in the error message to resolve the issue. If this does not work, please file a new issue so I can investigate.

If you're using the terminal, you need to ensure you got to the folder using the correct path. Eg.:

```
mkdir FOO
code foo      // this will fail because VS Code will be using "foo" but the folder is really named FOO
code FOO      // this will work fine 
```

I appreciate this should be unnecessary but case sensitivity is a bit of a mess across all of the involved tools (VS Code, nodejs/npm packages and Dart). Fixing it properly is complicated and needs doing in a lot of places - and VS Code is already doing some questionable things with casing (it's using the platform to decide if the filesystem is case sensitive instead of the filesystem, so if you use the same USB stick on Linux and Windows you'll get very different behaviour).
