### ISSUE TITLE
In widget tests the debugger seems to also debug library code, despite having activated "Debug my code"

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2351]
Does anyone can reproduce this behavior? Only applies when `import 'package:flutter_test/flutter_test.dart';` is used if i change it to `import 'package:test/test.dart';` debugger doesn't step into the library code.

![image](https://user-images.githubusercontent.com/28401593/79204793-64f36900-7e3d-11ea-8c24-8ff7ba0d4544.png)

And:
![image](https://user-images.githubusercontent.com/28401593/79205034-b7348a00-7e3d-11ea-8967-ae291cbe02a8.png)

**Comment by DanTup** [comment]
Thanks for the report! Because Flutter doesn't live in the pub cache, it gets treated as user code and needs specific handling. However `flutter_test` wasn't previously included in that handling. 

With the fix, you'll now end up breaking where you'd expect, on your own code:

![Screenshot 2020-04-14 at 11 54 42](https://user-images.githubusercontent.com/1078012/79217445-c7049c00-7e46-11ea-9b20-d25c782301c0.png)
