### ISSUE TITLE
Ability to run all failed tests

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2357]
Most of the time you don't want to run all the tests, most of the time you only want to rerun test who are failed previously.

Something similar was also mentioned here: https://github.com/dart-lang/test/issues/329

**Comment by DanTup** [comment]
It's not currently possible. In theory we could get a list of tests and run each of them, but I don't think we can run a multiple tests in one go through `package:test`, so it might end up being much slower (as it'd have to run each one in its own debug session).

I'll keep an eye on that issue so if there are changes that would help support this, we can use them.

**Comment by HerrNiklasRaab** [comment]
What exactly is the blocker on this?

**Comment by DanTup** [comment]
The issue was running a subset of tests from a suite in one go (without spawning lots of debug sessions). Running `pub run test --name foo --name bar` would require tests to match both `foo` and `bar` to run.

However, I think I found a way to handle this by combining them into a single regex like `--name ^foo$|^bar$`. I was able to make a command on the context menu for a suite that can re-run the failed tests there.

It won't be ready for the upcoming release, but I'll see if I can finish this off (it needs tests, and a way to run for all suites) for the next release. I'll ping you with a test build once it's done if you want to try it out.
