### ISSUE TITLE
Support running tests on device using launch config flag

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2363]
At the moment I can run widget tests **on a device** by running `flutter run --target=test/widget_test.dart`. But it would be awesome if I actually could debug this widget test while running on the device. So that I am able to stop with breakpoints. At the moment, all those tests are just running through and you have a hard time to follow, what happens on the device screen. 

It would be even more awesome if a code lens would appear above every widget test, which starts debugging the widget test on the device. 

Something like:

> Run | Debug | Debug on device

Is something like this possible? Any thoughts on this feature?

**Comment by DanTup** [comment]
Not currently possible, but I think it may be useful to have some way to force running tests on devices. If it's done with a setting in `launch.json`, you could use the existing code lens templates to add it as you requested, while also supporting when pressing F5 to run the whole file.

**Comment by DanTup** [comment]
Splitting this into two issues:

1. This one - support running tests on devices using a flag in a launch.config
2. #2373 support code lens on main methods for test files (currently they get the same code lens for non-test files, but they should have their own, since you may want different launch configs for tests vs non-tests)

With both of those implemented, you can create a `launch.json` that will run tests on devices and show up as code lens on the test files main method:

![Screenshot 2020-04-21 at 09 33 17](https://user-images.githubusercontent.com/1078012/79844113-274d8d80-83b3-11ea-8732-c41d4925d42c.png)

![Screenshot 2020-04-21 at 09 33 36](https://user-images.githubusercontent.com/1078012/79844145-32a0b900-83b3-11ea-8eea-df9266ebe918.png)
