### ISSUE TITLE
Provide 'Dart Browser launch'

### ISSUE THREAD

**Issue by Meai1** [Dart-Code/Dart-Code#238]
there is a CLI config but also would be cool to start the browser on F5, just let a specific executable (firefox) start with some html or url/path in it.

**Comment by DanTup** [comment]
I think this is somewhat covered by #68, though that's aiming more at Dart->JS compilation too. It's hard to do much currently, the task system is rather limited, but this is being discussed in https://github.com/Microsoft/vscode/issues/15179. This might make it difficult to make this useful - eg. if `F5` opens a new browser instance every time, that would kinda suck. Similarly, if it doesn't launch a browser when there's already one open, but you didn't actually have your app loaded, that would also suck.

Web stuff is one of the highest priorities for me for Dart Code so as soon as I get a chunk of time, I want to have a crack at it. I hoped it would've happened by now, but there seems to be no end of things to consumer my time! ;(

I'll leave this issue open so if I can find a quick way of doing this before Dartium/DDC support, I will.

**Comment by Meai1** [comment]
> if F5 opens a new browser instance every time, that would kinda suck

that's true, i assume that this can only be solved with a browser extension that talks to the vscode extension?

**Comment by DanTup** [comment]
> that's true, i assume that this can only be solved with a browser extension that talks to the vscode extension?

There are a couple of options, but I hope it won't involve something like that. Visual Studio sometimes injects JS into the page to allow it to control automatic refreshing, etc.; so that's an option (though I've had issues with VS's). Depending on how the browser works, maybe it's also possible to restart it (kill the old process, start new; but I suspect due to launching tabs in existing windows this won't work properly).

I'm hoping that if it doesn't already, ASP.NET will want very similar functionality here, so maybe there will be a good solution in the future even if not now :-)

**Comment by Meai1** [comment]
ahh i think i get it, it should be possible to just open a websocket and then on F5 it will ask the webpage to goto its own url aka reload. (http://stackoverflow.com/questions/1226714/how-to-get-browser-to-navigate-to-url-in-javascript)

on first start, you are right: it has to inject some javascript into the html but that should be easy too and wont bother anyone

**Comment by DanTup** [comment]
> ahh i think i get it, it should be possible to just open a websocket and then on F5 it will ask the webpage to goto its own url aka reload

Yep, that's basically how it works in VS, so something I could copy.

> on first start, you are right: it has to inject some javascript into the html but that should be easy too and wont bother anyone.

Not quite nobody! My colleagues and I all had to disable it in VS because it was injecting script tags into some AJAX responses! Possibly they look like web pages, I don't know how it decides. If I went this route, I'd need to make sure the decision about when to try and inject was sane (possibly just ensuring it has `<html>/<head>` tags or similar would work).

> maybe I'll do this, doesnt sound like too much work. I'll open a pull request if i have something

I think it might be tricky to do currently. What you can do on `F5` is limited, Code doesn't let you just do whatever you want.

> my code will look shitty though, I'm doing this just for myself after all

I'm totally open to contributions, but they can't be "shitty". Sometimes people will send PRs and then disappear (sometimes for good or unforeseen reasons) so I'll only merge code I'm comfortable with totally taking ownership of it if required and that I think is stable (quality is very important to me). But, don't be put off - I'm more than happy to help get things into shape or provide feedback on PRs if you want to have a go!

**Comment by DanTup** [comment]
I've opened #386 to collect some requirements for web stuff. Please read there and add comments for things you think it needs to support. I'm hoping to work on it in the coming weeks/next few releases.
