### ISSUE TITLE
Symbol search doesn't list expected items

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#24]
I don't think the method I'm using is the correct one; since it doesn't show all the things inside a class (I guess the clue was in the name, "top level").

**Comment by devoncarew** [comment]
I think this is the best analyzer API to use, to map to the symbol search. We may still want the API extended to show more things (`Foo.ba` would show something like `Foo.bar`).

**Comment by DanTup** [comment]
Do you think it's worthwhile me sending two requests (as mentioned [here](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/conkKX7XiKI)) in the meantime? I think Code users would probably expect class methods/properties to appear in the search and it feels a bit limited as it is.

**Comment by devoncarew** [comment]
I haven't used the other APIs - are they used for searching for a member
given a class? Or for any member in a project?

There's a separate vscode api for symbols within a file. That may make the
most sense to map to the analyzers outline api.

On Aug 6, 2016 7:27 AM, "Danny Tuppeny" <notifications@github.com> wrote:

Do you think it's worthwhile me sending two requests (as mentioned here
<https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/conkKX7XiKI>)
in the meantime? I think Code users would probably expect class
methods/properties to appear in the search and it feels a bit limited as it
is.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/DanTup/Dart-Code/issues/24#issuecomment-238025785>, or mute
the thread

**Comment by DanTup** [comment]
findMemberDeclarations looks very similar to the one I'm currently using; it's just global search for declerations with that name (though it might only do full matches and no pattern). I might have a go at merging results from both and see how it feels; certainly the current behaviour doesn't feel as useful as I would expect. I guess I could also compare results with some sample code on both TS and Dart.

**Comment by DanTup** [comment]
I did also post to [analyzer-discuss](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/conkKX7XiKI) if it's more helpful for others if the discussion happens there.

**Comment by DanTup** [comment]
@devoncarew I've implemented merging of these two for now. Seems to work ok for me (though I discovered a crazy bug in the process - https://github.com/Microsoft/vscode/issues/10446) but if you have a minute to test it I'd be interested in your opinion.

It works more like `Ctrl+T` for TypeScript now (eg. it'll include things from your imported packages, etc.). I think it might be both more and less useful at the same time.

I have not yet put any wildcard characters in (as suggested by @bwilkerson [here](https://github.com/Microsoft/vscode/issues/10446)) because it seems to already return things that *start with* what I pass (and I'm concerned when it gets fixed it'll just break and come less useful).

**Comment by devoncarew** [comment]
Awesome! I'll will give it a shot; I'm set up for development on my machine at home; also looking forward to the next release :)

**Comment by DanTup** [comment]
I'm planning on pushing a release out tomorrow. I might try and get #53 in first; I think it'll help me as a Dart noob (I keep meaning to sit down and actually try to write something real in Dart in it but it hasn't happened yet!).

**Comment by DanTup** [comment]
Going to consider this done for now; I think it's the best we can do. If the AS gets a new API in an upcoming version, I'll switch to it (though need to consider what to do if an old SDK is being used - something I've ignored for now... who knows what this thing does with an old SDK AS)...
