### ISSUE TITLE
Error running organize directives: [object Object].

### ISSUE THREAD

**Issue by eseidel** [Dart-Code/Dart-Code#241]
I attempted to run organize directives just after having "reloaded my project" after having run `killall dart` on the command line (due to the dart analyzer server having crashed, and thus I knew it was gonna get confused).

https://github.com/eseidel/lolsim was the code, I happened to be attempting to organize in lolsim.dart.  I doubt the specific code was related.

I suspect the analyzer server wasn't finished analyzing which caused this, but I'm not sure:

![screen shot 2017-01-05 at 7 57 59 pm](https://cloud.githubusercontent.com/assets/478541/21707119/5d469b1a-d381-11e6-912a-391e7a0e14e7.png)

**Comment by eseidel** [comment]
Actually, I think it may have been caused by there being a syntax error in my program.  I had a function definition without an actual block {}, e.g.

`void foo(int bar)`

dartfmt doesn't work in cases where there are parse errors like that, maybe that was what's going on here?  In any case we should have a better message. :)

**Comment by DanTup** [comment]
I think it does fail when there are syntax errors, but the error should definitely be better!

I suspect it's [this code](https://github.com/Dart-Code/Dart-Code/blob/ccdd222fdbfa7317de8b5573e7fdbeb8549515b5/src/commands/edit.ts#L47) using the `error` object in the message rather than reading the message off it. Should be an easy fix!

**Comment by DanTup** [comment]
Sorry for the delay; this fix has been released!
