### ISSUE TITLE
TextInput.setEditableSizeAndTransform

### ISSUE THREAD

**Issue by Cibeles89** [Dart-Code/Dart-Code#2415]
Issue Type: <b>Bug</b>

I obtain the error described in url https://github.com/flutter/flutter/issues/40427 in a flutter project ("No implementation found for method TextInput.setEditableSizeAndTransform on channel flutter/textinput").

I open this bug because the error does not appear in Android Studio.

The error prevents me from debugging because it does not open the keyboard to enter the text in a TextField widget.

I tried to create a new project and copy the files from the lib folder and it worked correctly, so the error is not in my code. But the same error happened again.

The same project (without changing ANYTHING) opened and debugged in Android Studio does not give an error and opens the keyboard to enter the text and works fine.

Extension version: 3.10.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment]
This is a Flutter issue and can't be fixed by the VS Code issue. I'm not sure why you're not seeing it in Android Studio, but some possible things to check:

- VS Code and Android Studio are finding the same version of the Flutter SDK
- In Android Studio you're "debugging" and not just "running" (I think you need to start with the Bug icon and not the Play Button icon)
- In Android Studio, you have the equivalent of "Break on all exceptions" enabled

Based on https://github.com/flutter/flutter/issues/40427#issuecomment-605645934, this is fixed in Flutter but not hotfixed into Stable. As a workaround you can untick "All exceptions" checkbox in the VS Code Debug side bar to avoid breaking on handled exceptions.

If you still see the behaviour on the beta/dev/master channels in Flutter, please file a new issue at flutter/flutter with details.

Thanks!
