### ISSUE TITLE
Misinterpretation of file names

### ISSUE THREAD

**Issue by owenkealey** [Dart-Code/Dart-Code#2416]
If you name a file `loading.dart` it will show up in the file viewer as `loading...`, not `loading.dart`
<img width="178" alt="Screen Shot 2020-05-03 at 8 11 08 PM" src="https://user-images.githubusercontent.com/26207512/80929600-584a9c80-8d7b-11ea-9795-60e571eb7f31.png">

**Comment by owenkealey** [comment]
This does not occur when the extension is turned off.

**Comment by DanTup** [comment]
The only way I can reproduce this is by shrinking the file explorer so that names are truncated by VS Code:

![Screenshot 2020-05-04 at 10 24 04](https://user-images.githubusercontent.com/1078012/80952352-6fc46c80-8df1-11ea-8f64-a64147f92df1.png)

Your explorer pane looks very narrow based on the position of the `M`, so I think that's what's happening here. The extension has no control over how things appear in the Explorer view.

Can you try increasing the size of the explorer side bar and confirm it goes away?

**Comment by owenkealey** [comment]
It goes away yes
