### ISSUE TITLE
Allow brackets and parens to be coloured differently from general text

### ISSUE THREAD

**Issue by wwmyers** [Dart-Code/Dart-Code#2419]
I looked through all issues, haven't seen any for this, which is surprising lol

Problem:
I've noticed that only Dart code doesn't allow syntax highlighting for brackets such as (), {}, []. From what I've seen using the scope tool, there's no option for it.

Question & Request:
Can we please add syntax highlighting for brackets?

My Setup:
Ubuntu 18.04.4
VSCode(always keep updated)

Screenshot Of Issue:
![bracketissue](https://user-images.githubusercontent.com/8205297/80969487-abf2cf80-8de7-11ea-87f8-a3c1c4a237b9.png)

Screenshot Of Other Languages:
Note: Same theme used in both
![bracketissue2](https://user-images.githubusercontent.com/8205297/80970161-b95c8980-8de8-11ea-8dcf-bec8af3bf389.png)

**Comment by SoKamil** [comment]
Same for the class properties, currently I cannot reproduce Intellij syntax highlighting

**Comment by DanTup** [comment]
VS Code has recently gained support for semantic highlighting which will resolve many of the highlighting issues. There's an open issue about adopting that at https://github.com/Dart-Code/Dart-Code/issues/2202. Since the goal is to move to LSP, this will likely be implemented only in the LSP server - though the API there is currently still provisional so work has not started.

**Comment by beevatsyu** [comment]
@wwmyers 
`coenraads.bracket-pair-colorizer-2`
Have you tried this extension?

**Comment by wwmyers** [comment]
> @wwmyers
> `coenraads.bracket-pair-colorizer-2`
> Have you tried this extension?

Yes I've tried that extension, it works great, but then I'd have to change it's colors every time I change themes. Seems a bit redundant.
Thanks though :)

**Comment by DanTup** [comment]
VS Code now includes a built-in option for bracket colouring:

<img width="869" alt="Screenshot 2021-09-06 at 18 34 30" src="https://user-images.githubusercontent.com/1078012/132249447-582b372b-aa69-4253-a67d-96fc198635c0.png">

<img width="546" alt="Screenshot 2021-09-06 at 18 35 08" src="https://user-images.githubusercontent.com/1078012/132249467-4238668e-fc41-4ace-b9bb-879ee861cc51.png">

The colours can also be customised in the `workbench.colorCustomizations` settings:

<img width="426" alt="Screenshot 2021-09-06 at 18 35 59" src="https://user-images.githubusercontent.com/1078012/132249528-a33579b3-59e1-49c1-b05e-e4cb3b8b815a.png">

So I don't think there's any need for something specific here, unless the VS Code implementation fails to detect the parens correctly (and if that is the case, we should probably request an API so that we can give it more reliably information).

Let me know if you think this doesn't address the whole issue!
