### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by itssidhere** [Dart-Code/Dart-Code#2422]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.10.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/4576275/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
Thanks for the trace! Do you remember when you saw this? Was it when you first opened a project, or during a debug session or something?

**Comment by DanTup** [comment]
Also - how big is the folder that you had open in VS Code?

**Comment by itssidhere** [comment]
@DanTup  I see this whenever I run profile or build app bundle. It usually says ( This is taking an unexpectedly long time ). The folder is about 1.82 GB

**Comment by DanTup** [comment]
@itssidhere can you clarify how you're starting them? The trace here shows a lot of file system access in the extension code, but the Flutter build is its own process and generally shouldn't triggering any extension code while it's running.

**Comment by itssidhere** [comment]
@DanTup I just open vs code normally and have my folder opened by default most of the time.

**Comment by DanTup** [comment]
I mean, if the issue occurs when you run a build, are you running the build from the terminal, or pressing `F5` to start debugging?

**Comment by itssidhere** [comment]
I press F5 to start debugging

**Comment by DanTup** [comment]
Although the warning from VS Code claims high CPU, the issue is actually that the thread is blocked on disk IO. We're checking where files exist and sometimes these are taking 600ms for a single file exists check.

My guess was that this is during SDK detection, though that shouldn't show up only when you run the app.

![Screenshot 2020-05-05 at 08 46 02](https://user-images.githubusercontent.com/1078012/81044855-fc803080-8eac-11ea-9fb1-894571c27d03.png)

What sort of disk does your machine have? Or are you using anything like a remote filesystem that might slow things down?

Capturing an [extension log](https://dartcode.org/docs/logging/#extension) at startup might help confirm the timing of the SDK detection (enable the log, restart VS Code and open the project, then grab a copy of the log).

**Comment by itssidhere** [comment]
My vs code is installed on a SSD and project is on a HDD .

**Comment by DanTup** [comment]
Ok, I managed to figure out the code that's running from the minified stacks! It's the code that tries to locate the roots of your projects:

https://github.com/Dart-Code/Dart-Code/blob/699c291b3f6424753ffde81ba7724e04fcb25c70/src/shared/utils/fs.ts#L69-L82

I'll look at trying to optimise this and changing it to be async so it doesn't block the extension host thread. Thanks!

**Comment by DanTup** [comment]
@itssidhere how reliably can you reproduce this? If I make a build with some changes, could you test it and see if it solves the problem?

**Comment by itssidhere** [comment]
It happens almost everytime . Yes I can surely test that

**Comment by DanTup** [comment]
Great! I've made a build, you can test it out by:

- Go to https://github.com/Dart-Code/Dart-Code/releases/tag/v3.10.1-dev.async-project-scanning
- Download the vsix file from that release to your computer
- In VS Code, run the **Extensions: Install from VSIX** command
- Select the vsix file
- Click the **Reload** button after it's installed

Please let me know whether this seems to help. Thanks!

**Comment by itssidhere** [comment]
@DanTup  Thanks. Also if you don't mind can you tell me what specifically I should be looking for?

**Comment by itssidhere** [comment]
@DanTup Getting an error "Cannot uninstall extension 'Dart'. Extension 'Flutter' depends on this." after I select the vsix

**Comment by DanTup** [comment]
> Also if you don't mind can you tell me what specifically I should be looking for after installing the build?

Well hopefully you should no longer see the error about high CPU, but there should be no other change in behaviour.

> Getting an error "Cannot uninstall extension 'Dart'. Extension 'Flutter' depends on this." after I select the vsix

Ah yes, I accidentally used a lower version number than the previous release and VS Code has this bug when downgrading. I'll rebuild with a newer version number (otherwise VS Code will auto-update to the one in the store). Gimmie few mins!

**Comment by DanTup** [comment]
Ok, try again with the vsix from here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.10.2-dev.async-project-scanning

Thanks!

**Comment by itssidhere** [comment]
@DanTup I didn't get any error this time. Thanks

**Comment by DanTup** [comment]
Great! I'll merge that change in for the next release. You can stick on this version in the meantime - it'll automatically upgrade to the next release when it's published.
