### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by zaymsayd** [Dart-Code/Dart-Code#2429]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.10.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ZAEEM\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️C:\Users\ZAEEM\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!

**Comment by fybwid** [comment]
@DanTup I have a similar issue on my Mac

[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/4693010/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment]
@fybwid thanks for the trace! This looks the same as the one in #2422, so I believe it will be fixed in the upcoming release (hopefully by the end of the week). In the meantime, if you see this a lot you could grab the beta version from here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.11.0-beta.4
