### ISSUE TITLE
VSCode not detecting changes to package reference via path

### ISSUE THREAD

**Issue by chrisjones314** [Dart-Code/Dart-Code#2433]
I have a library dart package I am developing at:

```
/projects/mylibrary
```

I have a flutter project at:

```
/projects/myflutterapp
```

In the myflutterapp, I reference the library using this syntax:

```  
  mylibrary:
    path: /projects/mylibrary
```

This works, until I make a change to code in mylibrary (say, I change a method name).  Then, VSCode/DartCode continues to report the old method name is correct, and the new method name is incorrect.   Auto-complete continues to report the old name.

If I close the VSCode window for myflutterapp, and open a new window, the problem goes away.  I have several VSCode windows open, so whatever cache is the problem seems to exist at the window level.

If I use this github syntax, and carefully update the version number in both places, it works fine.  The compiler/syntax highlighting updates after the automatic pub-get.

```
  mylibrary:
    git: https://github.com/chrisjones314/mylibrary.git
    version: ^0.0.7
```

I tried adding the version number in the problem case, like this:

```
  mylibrary:
    path: /projects/mylibrary
    version: ^0.0.7
```

But it did not resolve the issue.   If I bump the version only in myflutterapp in this case, it will do a pub get and recognize that the version doesn't exist (e.g. myflutterapp asks for 0.0.8, and mylibrary is only 0.0.7).   So, it seems like it is looking at the mylibrary's local pubspec.yaml.   However, when I go and correct mylibrary to have version 0.0.8, it still doesn't seem to pick up the code change.

I also tried using Flutter > Clean Project, but that doesn't seem to reset whatever cache is not updating.

[This issue](https://github.com/Dart-Code/Dart-Code/issues/1334) makes me think maybe this is a problem in the analysis server?   As with that issue, is there any way for me to manually restart the analysis server so that I can work around this issue?

Thanks a lot for your help.   Here is my flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1, on Mac OS X 10.14.6 18G1012, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

**Comment by DanTup** [comment]
I believe the issue is that the analysis server (there's on per VS Code window) doesn't watch package folders for changes (as normally, packages are not expected to be modified).

Whilst that might be fixable, I would not recommend running multiple versions of VS Code to modify files that are being used in another. This results in multiple analyzers analyzing the same files which will impact performance as well as allowing the files to be out of sync (for example if they're modified in each editor).

The preferred way is to open multiple folders in VS Code using "multi-root workspaces". When you have a folder open, you can click **File** -> **Add Folder to Workspace** to add additional folders. You can save this workspace as a `.code-workspace` folder so it can be re-opened easily later, and also have workspace-wide config and launch configurations/compounds if required.

**Comment by chrisjones314** [comment]
That totally fixes it.  Thanks so much for your help.  I had been working with one window per-project for a long time, and I just didn't think of having everything in one window.

I really appreciate the solution!

**Comment by DanTup** [comment]
Great, glad it helped!
