### ISSUE TITLE
How to disable default argument placeholders when completing methods?

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#2451]
Nowadays when I type `.reduce` I get `.reduce((value, element) => null)`. Deleting this again costs me time so I want to disable that and just get parentheses (or nothing). I went through all settings but couldn't find the corresponding setting. What setting should I use?

**Comment by DanTup** [comment]
If you disable `dart.insertArgumentPlaceholders`, that will stop it inserting parens+arguments when completing functions/methods.

This does also mean you'll need to type your own `(` when you want to call the method though. The end goal is to support "commit characters", so you can press `(` instead of `<enter>` and it will both commit the completion, and insert the `(`. However this needs a little work before it works well (it has some frustrating quirks right now - though you can try it out with `dart.enableCompletionCommitCharacters`).

Hope this helps!
