### ISSUE TITLE
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory(). > Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

### ISSUE THREAD

**Issue by steffy2110** [Dart-Code/Dart-Code#2452]
on command flutter run, I get the above error message, the emulator is configured already, what to do kindly guide.

**Comment by DanTup** [comment]
I think this error is coming from Gradle, not the VS Code extension - so it's not something I'm particularly familiar with. Based on some searching, it may be related to the version of Java and/or Gradle being used.

There are some things you can try to resolve this here:

- https://stackoverflow.com/questions/53272230/could-not-create-service-of-type-scriptpluginfactory-using-buildscopeservices-cr

[One answer](https://stackoverflow.com/a/61408647/25124) suggests opening the project in Android Studio caused it to update Gradle and dependencies, which fixed the issue and then it worked in VS Code.

Hope this helps!

**Comment by steffy2110** [comment]
> I think this error is coming from Gradle, not the VS Code extension - so it's not something I'm particularly familiar with. Based on some searching, it may be related to the version of Java and/or Gradle being used.
> 
> There are some things you can try to resolve this here:
> 
> * https://stackoverflow.com/questions/53272230/could-not-create-service-of-type-scriptpluginfactory-using-buildscopeservices-cr
> 
> [One answer](https://stackoverflow.com/a/61408647/25124) suggests opening the project in Android Studio caused it to update Gradle and dependencies, which fixed the issue and then it worked in VS Code.
> 
> Hope this helps!

The link you mentioned I had tried all those things prior to posting here and I also tried running in Android Studio although I work on Vs code but still didn't work, am getting same error there as well.

**Comment by DanTup** [comment]
Unfortunately I'm not sure what else to suggest. It seems like a Gradle issue and not something that can be fixed in the VS Code extension, as it happens with Android Studio too.

There are some issues in the Flutter repo that might be worth reviewing too:

- https://github.com/flutter/flutter/issues/46792
- https://github.com/flutter/flutter/issues/42591

Unfortunately I'm not at all familiar with Gradle so I can't really do much more search the web as no doubt you already have.

If you don't find a solution, please do post back here so if others come across thie issue looking for a fix, they can try whateer worked for you. Thanks!

**Comment by vhmolinar** [comment]
Let me share a situation where this issue occurs:

When using windows/wsl2, avoid launching flutter inside linux folders, that will trigger the mentioned error.
