### ISSUE TITLE
Angular set up

### ISSUE THREAD

**Issue by trimmdavid** [Dart-Code/Dart-Code#2456]
during the set up of connecting the vscode and the command prompt , i need to open the command palette, to type in "install 'code' in  command in PATH" .But I can't find this on my command palette.Anyone can help please?

**Comment by DanTup** [comment]
Are you on macOS? The VS Code docs say this command is only for macOS:

https://code.visualstudio.com/docs/editor/command-line

> *Note*: Users on macOS must first run a command (Shell Command: Install 'code' command in PATH) to add VS Code executable to the PATH environment variable.

It also has some notes on setting this up for other OSes:

> Windows and Linux installations should add the VS Code binaries location to your system path. If this isn't the case, you can manually add the location to the Path environment variable ($PATH on Linux). For example, on Windows, VS Code is installed under AppData\Local\Programs\Microsoft VS Code\bin.
> To review platform specific setup instructions, see [Setup](https://code.visualstudio.com/docs/setup/setup-overview).

Thoe OS-specific guides are at https://code.visualstudio.com/docs/setup/setup-overview#_cross-platform

Hope this helps!

**Comment by trimmdavid** [comment]
thanks ,but i'm on windows

**Comment by DanTup** [comment]
The Windows installer for VS Code should set this up automatically, though the setup page notes:

https://code.visualstudio.com/docs/setup/windows

> Setup will add Visual Studio Code to your %PATH%, so from the console you can type 'code .' to open VS Code on that folder. You will need to restart your console after the installation for the change to the %PATH% environmental variable to take effect.

If that doesn't work, I would try rebooting (I've seen Windows not update PATH properly until a reboot).

Otherwise, you may need to add it to `PATH` manually yourself. There's some info on how to do this for Windows 10 here:

https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by trimmdavid** [comment]
https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/
i just  tried this link,but its not working

**Comment by DanTup** [comment]
It's not clear what the problem is from your message, though it's probably not related to Dart-Code. If you're getting a message about `code` not being a recognised command, it suggests it's not been added to `PATH` correctly (so you should check you added the correct folder to `PATH` and also try rebooting).

If `code` does launch VS Code, but it doesn't load/work correctly, you should raise that at https://github.com/microsoft/vscode.

If you have issues specifically with the Dart or Flutter extensions though, this is the correct place for that. Thanks!

**Comment by trimmdavid** [comment]
okay,thanks

**Comment by dc20433** [comment]
I followed the link above [ https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/ ] step by step and installed my first global PATH on Windows 11. Very exciting!

**Comment by DanTup** [comment]
@blu28 I would suggest filing a request in the VS Code repo, that seems like a reasonable request to me (and the terminal does have ways of setting `PATH` because it's exposed to extensions - although it has some restrictions there).
