### ISSUE TITLE
Widgets' suggestions are not showing up

### ISSUE THREAD

**Issue by abhisheksudhir** [Dart-Code/Dart-Code#2472]
![image](https://user-images.githubusercontent.com/50238399/82318534-a7d0cf80-99ed-11ea-98fd-0490979d7727.png)

**Comment by DanTup** [comment]
If you press `Ctrl`+`Space` do they show up?

**Comment by abhisheksudhir** [comment]
I restarted vs code and it worked. Not sure what the issue was. Before restarting when I tried Ctrl+Space it showed suggestions but not CrossAxisAlignment which is what I wanted.

**Comment by DanTup** [comment]
Strange. If you see it again, check there are no notifications (bell icon in the bottom-right status bar) about the analyzer failing, or check Help -> Toggle Developer Tools to see if there are any errors in the console.

I'll close this since there's not much to investigate, but we can reopen if it comes back.

**Comment by abhisheksudhir** [comment]
Thanks
