### ISSUE TITLE
Improve Outline display in VS Code (add elements preview)

### ISSUE THREAD

**Issue by subzero911** [Dart-Code/Dart-Code#2475]
That's how outline looks in VS Code
![image](https://user-images.githubusercontent.com/12999702/82351386-33098f80-9a05-11ea-8142-ff584cfbf06c.png)
It's really hard to navigate here. You can't figure out: "What's an icon? What's a text?"
Much better how it looks in Android Studio:
![image](https://user-images.githubusercontent.com/12999702/82351423-3b61ca80-9a05-11ea-925e-892ab62242a3.png)
Also with nice round icons for widgets ("R" for Row, "S" for Scaffold etc.)

**Comment by DanTup** [comment]
@jacob314 what's the best way to decide which attributes labels to show here? I noticed in DevTools, it doesn't seem to show the same as in the Android Studio above (it shows the `key` instead of the text):

![Screenshot 2020-05-20 at 13 56 18](https://user-images.githubusercontent.com/1078012/82448587-d27c6000-9aa1-11ea-8036-9a1abe435c75.png)

![Screenshot 2020-05-20 at 13 56 14](https://user-images.githubusercontent.com/1078012/82448585-d14b3300-9aa1-11ea-8087-4250eea58926.png)

**Comment by beevatsyu** [comment]
Why do we have a seperate sidebar for outline, when the explorer outline does the same thing better (e.g. can sort from "More Action")?

![Screenshot from 2020-05-27 09-11-43](https://user-images.githubusercontent.com/14292060/82975482-38b13780-9ffa-11ea-83cd-b2941dfa6275.png)

**Comment by DanTup** [comment]
@beevatsyu 

> Why do we have a seperate sidebar for outline, when the explorer outline does the same thing better (e.g. can sort from "More Action")?

I really wanted to use the built-in Outline view, but there are issues that prevented us, most notable:

- We can't add custom icons to it - https://github.com/microsoft/vscode/issues/50186
- It's tied to the breadcrumb view and symbol list, so adding widgets to the outline view also causes them to appear int he symbol view (and since it's a flat list, it just ends up full of tons od duplicates like `Text(...)`) - https://github.com/microsoft/vscode/issues/51332

**Comment by beevatsyu** [comment]
@DanTup 
Thanks for the clarification. Any plan to incorporate sort functionality on the outline?

**Comment by DanTup** [comment]
@beevatsyu not currently. There's a lot of functionality built in to the built-in outline and reproducing it all in the Flutter Outline would be a lot of effort. It would be nice to have only a single outline, but it doesn't seem likely this will be easy in the near future because of VS Code limitations. Generally I'd suggest to just switch between the outlines depending on your needs.

**Comment by DanTup** [comment]
We'll now show the first attribute that's named `data`, `icon` or `value` alongside nodes in the Outline:

<img width="459" alt="Screenshot 2020-06-01 at 14 43 32" src="https://user-images.githubusercontent.com/1078012/83415528-1747b580-a417-11ea-854b-8579b77e5cf2.png">

We can add other attribute names to the list if there are widgets that are missing significant info, but it looked weird to just always show the first (for example sometimes it'd be `key` which is a bit useless) and it looks really crammed if we show them all.

**Comment by cgilbu** [comment]
How about configuring it to show the first comment within the widget? By doing that, we can establish references to every widget, simplifying the navigation through the widget tree and the outline?
