### ISSUE TITLE
Support running pub get and pub upgrade with the --packages-dir flag

### ISSUE THREAD

**Issue by jacehensley-wf** [Dart-Code/Dart-Code#248]
With Dart 1.20.0 by default when running pub get, pub upgrade, and pub downgrade you no longer get package/ directories. You can still get these by using the --package-dir flag.

Can an option be added to run those commands with this flag?

**Comment by DanTup** [comment]
Does this need to be customisable, or is making it use just `package` (`packages`?) good enough?

I think it would be best as a setting (which can be overriden per-workspace) rather than adding more commands (not only because you're less likely to pick the wrong one for a given project, but also to avoid adding more commands which appear in Code even when you don't have a Dart project loaded!).

**Comment by jacehensley-wf** [comment]
Yeah, I think just adding a config would be good. Maybe even a config for adding arbitrary flags to pub get / pub upgrade.

```json
{
  "dart.pubGetAndUpgradeFlags": ["--packages-dir", "--whatever-else"]
}
```
