### ISSUE TITLE
"method not available" errors when I restart my app

### ISSUE THREAD

**Issue by Reprevise** [Dart-Code/Dart-Code#2493]
Hello! Every time I run my Flutter project in VSCode, I get these six errors when I **restart** my app. When I start my app, I get a blank screen (most likely the Scaffold's background color). This issue **does not** occur when I start my app using `flutter run` or Android Studio, so this has to be an issue with the plugin in VSCode.

```
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
method not available: ext.flutter.platformOverride
method not available: ext.flutter.inspector.setPubRootDirectories
method not available: ext.flutter.inspector.isWidgetCreationTracked
```

**Comment by DanTup** [comment]
Where are you seeing these - in the Debug Console?

Could you capture a log so I can check why they might be failing?

- Run **Dart: Capture Logs** from the VS Code command palette
- Untick Analysis Server but leave everything else ticked and click OK
- Start your debug session, then restart the app so that these messages appear
- Click **Cancel** on the Logging notification to stop logging and open the log
- Attach the log here (after reviewing there's nothing sensitive in there)

Thanks!

**Comment by Reprevise** [comment]
I can't for the life of me reproduce this issue now! Of course, it's after I submit an issue. If it comes back, I'll reopen this with the logs.

**Comment by DanTup** [comment]
Strange. I can imagine it could happen now and then if the app is shut down while these requests are pending/being sent - but I wouldn't expect it generally. Do let me know if it comes back!
