### ISSUE TITLE
VSCode dart code autocomplete don't work almost all the time even for simple code

### ISSUE THREAD

**Issue by dev-xdyang** [Dart-Code/Dart-Code#2499]
when I enter the init parameter, it will not autocomplete for some times, but after I enter the class definition and back, this class autocomplete will work. Android Studio work always well.
![Screen Shot 2020-05-27 at 10 01 03 AM](https://user-images.githubusercontent.com/7471748/82968945-fccda080-a000-11ea-8582-328369289c9b.png)

VSCode info:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

flutter and dart info: 
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (2 weeks ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

**Comment by dev-xdyang** [comment]
![Screen Recording 2020-05-27 at 10 17 08 AM](https://user-images.githubusercontent.com/7471748/82973658-95b4e980-a00a-11ea-9b97-7ebcd1e050ef.gif)

**Comment by DanTup** [comment]
This is caused by the tabstop. VS Code won't invoke completion while you're in a tabstop (in my opinion, this is a bad default setting).

I'll see whether there's a way I can improve this, but in the meantime I'd recommend you set this VS Code setting:

```js
"editor.suggest.snippetsPreventQuickSuggestions": false,
```

This is listed on the recommend settings page (along with some others you my wish to review) here:

https://dartcode.org/docs/recommended-settings/

**Comment by dev-xdyang** [comment]
@DanTup  Thank very much, it's work well.

a little advise:
If can add this message as doc to the [Set up an editor](https://flutter.dev/docs/get-started/editor?tab=vscode), it will be perfect for beginner like me. Thank for you replay again!

**Comment by DanTup** [comment]
@dev-xdyang thanks for the suggestion! I think this would be better handled within the extension, so people who don't use the docs also see it. I have an open issue at https://github.com/Dart-Code/Dart-Code/issues/1946 which will show a one-time prompt to use the recommended settings (or to open the web page) which I will look at implementing for the next version after this one. Thanks!

**Comment by chamartt** [comment]
Hi,

I reopen this ticket because I have the same issue, but tell me if it's better to open another one.

**I don't have any Dart suggestions when I ctrl+space and I cannot use collapse/expand functionnalities as the "brackets" (on the left of codes) are not even present.**

I'm using VSCode 1.60 and Flutter 2.5.0.

When I use Flutter 1.22 with an old project builded with this version, everything it's ok. 
I also can use those functionnalities with this old project on Flutter 2.5.0 ; so the problem seems to come from my new project, which is running perfectly on physical device (except the automatic Hot Reload).

So it seems to be a configuration problem somewhere.

Here there is my user settings, so for all of my projects : 

```
{
    "workbench.startupEditor": "newUntitledFile",
    "update.mode": "none",
    "window.zoomLevel": 0,
    "window.smoothScrollingWorkaround": true,
    "git.autofetch": false,
    "liveshare.featureSet": "insiders",
    "workbench.iconTheme": "vscode-icons",
    "force.allowAnonymousUsageTracking": true,
    "peacock.favoriteColors": [
        {
            "name": "Angular Red",
            "value": "#b52e31"
        },
        {
            "name": "Auth0 Orange",
            "value": "#eb5424"
        },
        {
            "name": "Azure Blue",
            "value": "#007fff"
        },
        {
            "name": "C# Purple",
            "value": "#68217A"
        },
        {
            "name": "Gatsby Purple",
            "value": "#639"
        },
        {
            "name": "Go Cyan",
            "value": "#5dc9e2"
        },
        {
            "name": "Java Blue-Gray",
            "value": "#557c9b"
        },
        {
            "name": "JavaScript Yellow",
            "value": "#f9e64f"
        },
        {
            "name": "Mandalorian Blue",
            "value": "#1857a4"
        },
        {
            "name": "Node Green",
            "value": "#215732"
        },
        {
            "name": "React Blue",
            "value": "#00b3e6"
        },
        {
            "name": "Something Different",
            "value": "#832561"
        },
        {
            "name": "Vue Green",
            "value": "#42b883"
        }
    ],
    "explorer.confirmDelete": false,
    "vsicons.dontShowNewVersionMessage": true,
    "editor.minimap.enabled": false,
    "dart.sdkPath": "C:\\flutter\\bin\\cache\\dart-sdk",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "git.enableSmartCommit": true,
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.debugExternalLibraries": true,
    "dart.debugSdkLibraries": true,
    "files.associations": {
        "*.dart": "dart"
    },
    "dart.lineLength": 200,
    "dart.previewLsp": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.quickSuggestions": true,
}
```

Do you have any idea ?

Thank you in advance.
