### ISSUE TITLE
Extension required for debugging

### ISSUE THREAD

**Issue by grouma** [Dart-Code/Dart-Code#2505]
When I use `Start Debugging` through VS Code I am prompted with
`Waiting for connection from Dart debug extension at http://localhost:63891` in the console. Previously, VS Code would automatically launch a debug enabled session of Chrome for me. Why is the extension now required?

The usability of this workflow is less than ideal as well. The new Chrome tab gains focus but nothing will be displayed until the user enables the Dart Debug Extension. The prompt to do so is in the VS Code console.

**Comment by DanTup** [comment]
The first issue is covered by https://github.com/Dart-Code/Dart-Code/issues/2453. A change in Flutter (@jonahwilliams I think it was https://github.com/flutter/flutter/pull/55160/files#diff-449a3992388169653b58410d2433d301R285-R289) resulted in VS Code selected the Web-Server device over Chrome because of ordering. You can see the selected device in the bottom-right corner (in ths status bar). The version with the fix is expected to release later today.

The second issue with the white screen is covered by https://github.com/flutter/flutter/issues/48803 - a request to show some sort of message in the page about using the extension, though I've also got https://github.com/Dart-Code/Dart-Code/issues/2496 open to improve how it displays in VS Code (eg. updating the progress notification to mention it's waiting for the extension, in case you don't have the Debug Console visible).

I think that addresses the issues, but if you think there's anything additional we could do, let me know!

**Comment by grouma** [comment]
Those issues should cover it. Thanks!
