### ISSUE TITLE
Dart extension doesn't work anymore inside workspaces

### ISSUE THREAD

**Issue by efreibe** [Dart-Code/Dart-Code#2524]
I have several flutter projects inside workspaces, in those projects the analysis, code completion and symbol search doesn't work anymore.
The only thing that works correctly is syntax highlighting.
Every time I open a .dart file I get this error in the console:

```
[Extension Host] No editors associated with document: document.dart @ console.ts:137 
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

If I open the project separately, then the extension works correctly.

I can reproduce this issue opening any flutter project, writing any garbage inside the .dart file, at this point I can view that analysis is working as expected; then I add another project to the workspace and save it.

Then I close and reopen vscode, open the workspace, go to the .dart file with garbage, and that file doesn't get checked anymore.

Is anybody experiencing the same problem? 
I'm using latest vscode, dart and flutter extensions in a macbook.

![image](https://user-images.githubusercontent.com/1061126/83956857-a2baaf80-a838-11ea-947c-ab60f9efa195.png)

**Comment by DanTup** [comment]
Are there any other errors in the dev console (Help -> Toggle Developer Tools -> Console)?

I tried your steps here, but don't see the same issue - I can open workspaces with multiple Flutter apps and they behave as expected.

Capturing a log may help:

- Open the workspace
- Run the **Dart: Capture Logs** command (leave everything ticked and click OK)
- Open a Dart file so that the error is generated
- Click **Cancel** on the logging dialog to stop logging and open the log

The log may contain parts of your source code so please remove anything sensitive before sharing.

**Comment by efreibe** [comment]
Hello, I've uploaded a zip file with a workspace file and two log files, one log is from a project without workspace and another one with a workspace containing two projects.

I've discovered that if I create a workspace with two local projects it works fine, but my projects are stored in a smb mapped folder (smb://192.168.0.4/smb-folder).

When I include this project the Dart analysis stops. 

The typescript analysis over the network project is working well.

Strange enough, I've been working in my workspace for over 8 months and neved had a problem.

[Archive.zip](https://github.com/Dart-Code/Dart-Code/files/4747432/Archive.zip)

![image](https://user-images.githubusercontent.com/1061126/84065638-0fe65600-a99b-11ea-9a68-46ebe3445926.png)

**Comment by DanTup** [comment]
@efreibe from the log it looks like the server just isn't responding. Are you able to log using the [analysis server log](https://dartcode.org/docs/logging/#analyzer), as this will capture the full stdout/stderr for the analysis server process from when it's started. You set it to a path of a log file and then restart VS Code and grab a copy of that file after a a minute or so when it's clear the server isn't working.

Thanks!

**Comment by efreibe** [comment]
Hello, I've enabled the option for the analysis server and closed vscode.

Then I opened a flutter project without workspace and worked for a couple of seconds. Everything was logged fine. (File: analysis.nows.txt)

Then I've closed everything again, moved the file and opened the same project but inside a workspace (the companion project is located under a smb folder), and did the same as before during a couple of seconds (file: analysis.ws.txt), this time the output was different, apparently the server is stopping prematurely.

[analysis.nows.txt](https://github.com/Dart-Code/Dart-Code/files/4867257/analysis.nows.txt)
[analysis.ws.txt](https://github.com/Dart-Code/Dart-Code/files/4867258/analysis.ws.txt)

**Comment by DanTup** [comment]
Thanks! Unfortunately the two logs seem to show the same thing being sent to the server in both cases, because the lines are truncated by default.

Could you instead [capture using the `dart.analyzerInstrumentationLogFile setting`](https://dartcode.org/docs/logging/#analyzer-instrumentation)? That should log the full requests, and will also include some of whats going on in the server.

From the logs you did provide, it seems like the server *started* to send a `registerCapability` request but it never came through (the header is there, including the length - which matches the one in the working log).

Also - can you confirm if this happens with *any* additional folder you have in the workspace, or specifically this one? Thanks!

**Comment by efreibe** [comment]
I enabled that setting, unfortunately nothing relevant is saved inside the file. See below.

About the question, no, the problem doesn't happen with local projects. 
Once I include the smb mapped folder, the flutter project inside the workspace doesn't work anymore, 
but the other projects are not affected, the analysis tools works on them as expected.

I do not want to make you waste time on this because apparently is an isolated case, so maybe if
you could give me a short explanation on how to debug this extension, I could find the problem.

[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/4881074/analyzer.txt)

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1061126/86638357-8764d080-bfad-11ea-9805-ae1558e9e5e2.png">

**Comment by DanTup** [comment]
> Once I include the smb mapped folder

Ah sorry, you'd mentioned that previously and I forgot. If you disable the `dart.previewLsp` setting, does that make any difference?

@bwilkerson are smb shares (`smb://192.168.0.4/smb-folder`) something the server should/does support?

**Comment by bwilkerson** [comment]
I think the short answer is that we're unlikely to support any file system access in server that isn't supported by `dart:io`. That said, I don't know whether `dart:io` does or should support smb.

**Comment by DanTup** [comment]
> I don't know whether `dart:io` does or should support smb.

I couldn't find the answer to that either. There are no results for "smb" in the dart-lang/sdk tracker, though there's a single issue I found at https://github.com/dart-lang/sdk/issues/10002 which seems to suggest it works.

I can see some code in LSP that would reject non-file URIs, so if it seems to work for @efreibe with LSP disabled, I'll see if I can set a share up locally for testing.

**Comment by efreibe** [comment]
@bwilkerson But do not forget that the flutter project is located on my computer. 

The javascript project is what's imported in the workspace from a smb share, and even so, is the flutter project that isn't working. The javascript project that's read over the smb share works correct inside vscode!

I disabled LSP now, and instead of doing nothing, I see a loading... message hanging forever. 

With LSP:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/1061126/86983482-5bd71700-c162-11ea-9de8-df42c007172b.png">

Without LSP:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/1061126/86982876-afe0fc00-c160-11ea-81f5-dbe2cb81385b.png">

Then I try to save the local file, and see a popup that lasts forever:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/1061126/86983010-0c441b80-c161-11ea-9ace-fe90f04b0399.png">

If I delete the smb project from workspace it works again, with or without previewLsp enabled.

With LSP disabled the instrumentation file gets even weirdeir, only this line is logged:

```
1594253927385:Ver:1538003599513396693567:VS-Code:3.12.2:1.27.4:2.8.4
```

In the exact moment that I remove the javascript project from workspace, everything starts to work again!

Maybe the plugin tries to get, in any way, some data for all projects inside the workspace or interact with those? 
Aside that is on a smb folder, in which way a totally unrelated project (javascript project) is modifying the behavior of dart analyzer, is important for the analyzer that the other project is on smb share?

**Comment by DanTup** [comment]
@efreibe thanks for the info - I'll try to get something set up locally so I can debug this. If it's not easy to make SMB work for Dart/Flutter, I think we could at least ignore that folder (rather than crashing/hanging as it seems to now).

**Comment by efreibe** [comment]
FYI, I tried to disable all extensions, even vscode git, except flutter and dart. Did not work. 

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1061126/87084153-2256e800-c204-11ea-8f7c-3fdd09a9d8f4.png">

**Comment by DanTup** [comment]
@efreibe can you clarify how you're opening the folder? I've got a Samba share and I connected by opening Finder, pressing Cmd+K, then entering the smb:// address. This mapped it to `/Volumes/smb_shared/` which I then used in VS Code without any issues (I couldn't find a way to open an `smb://` path directly).

Also - can you confirm if turning off the LSP preview (`"dart.previewLsp": false`) makes any difference? Thanks!

**Comment by DanTup** [comment]
Ok, I actually think this might be https://github.com/dart-lang/sdk/issues/42672 which I hit by coincidence today while trying to reproduce a different issue. When in non-LSP mode, the server crashes and logs the error in that issue, but in LSP mode we log nothing - because the LSP code in Dart-Code was not watching the `stderr` stream.

To confirm this, you can try either:

1. Setting `"dart.previewLsp": false` in your user settings, then reproduce the issue with the analysis server log enabled, and see if it logs the same error in https://github.com/dart-lang/sdk/issues/42672
2. Download [this beta release](https://github.com/Dart-Code/Dart-Code/releases/tag/v3.13.0-beta.2) of Dart-Code which fixes the logging for the LSP server, then reproduce the issue and see if it logs the same error in https://github.com/dart-lang/sdk/issues/42672

I'm not sure why it's only triggering when you use the smb share though, as I hit it just using the latest SDK on a local test project (the log looked identical - it wrote the header for the same response - with the same number of bytes, then just stopped).

Let me know what you find. Thanks!

**Comment by efreibe** [comment]
Here you have two logs files created with `"dart.previewLsp": false`

The instrumentation does not contains some specific. But the analyzer is logging a
`[4:40:21 PM] [Analyzer] [Info] Process terminated! null, SIGTERM` message.

Btw, I've uninstalled vscode from my mac, reinstalled again, but the problem persists.

I didn't have the opportunity to install an old version of dart code. 
Older versions were working for me, but this could be due to an older vscode version and not the extension...

[analyzer-inst.txt](https://github.com/Dart-Code/Dart-Code/files/4933848/analyzer-inst.txt)
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/4933849/analyzer.txt)

**Comment by DanTup** [comment]
Thanks - unfortunately the log doesn't reveal very much - it does show the analyzer terminated, but no error was logged. Could you try running manually to see whether there's any visible error if run from the terminal?

```
/Users/macos/flutter/bin/cache/dart-sdk/bin/dart /Users/macos/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
```

Then paste in (including a newline on the end):

```
{"id":"9","method":"analysis.setAnalysisRoots","params":{"excluded":[],"included":["/System/Volumes/Data/sos-contador","/Users/macos/github/sos2mobile.old"]}}

```

Does this cause the server to terminate?

Some other things to try:

- Does it happen if you open the project on the samba mount directly on its own?
- If not; does it happen if you open two projects, neither of which are on the samba mount?
- Does it happen if you create a brand new project (with **Flutter: New Project**) on the sambda mount and include that instead of the existing one?

**Comment by efreibe** [comment]
Hello I'm a little lost, I can answer your questions but none of them are related to the bug, because all my flutter projects are stored locally on my hard drive. 

The workspace contains apart from my local flutter project, "another" unrelated project, that has nothing to do with flutter, that is mapped via SMB. 

The tests that you asking me to do involves mapping a flutter project through the network, but is not my case.

**Comment by DanTup** [comment]
@efreibe sorry for the confusion! I'm trying to understand whether the issue is related to the SMB at all. When you open a workspace in VS Code that has multiple folders, a single analysis server will be started that will evaluate all of the folders in the workspace.

If you make a copy of the SMB (non-Flutter) project locally and then add that folder to the workspace (instead of the SMB one) and it works, that does suggest the issue may be related to SMB. If it shows the issue, then we can eliminate SMB as a potential cause.

Similarly, if copying the Flutter project to an SMB share and opening only that folder shows the same issue, that also suggests it may be related to SMB.

Hope this makes sense!

**Comment by efreibe** [comment]
When I use a workspace with all local projects the problem goes away, I don't even need to close and reopen workspace, the moment I remove the smb project, the dart extensions begins the analysis, when I put the smb project back, suddenly the analysis stops.

Now I tried a different approach, I've installed a vmware Fusion (tested a windows 7 and a windows 10), put inside all the code, mapped vm's folders via smb, opened vscode but nothing changed. So is not a network or a communication problem.

I will try to copy the flutter project to a network location to check, for now, this is the report of the tests I made.

**Comment by DanTup** [comment]
Thanks - I'm trying to understand whether this is related to smb or just the project you have on your smb share. To tell which, it would be useful to either copy your project from smb locally and open that (so it's the same code), or to put your Flutter project on smb and open that.

I've been unable to reproduce it here, so knowing whether it's happening because of the smb, or just something inside the specific project you have on the smb volume might help me narrow it down. I have access to both Windows and macOS here. My previous tests were done by sharing a folder in one Mac and enabling the SMB option, and then mounting that from the other Mac (I couldn't find a way to share with itself).

**Comment by efreibe** [comment]
Mixing SMB and local projects inside a workspace returned despair results, some workspaces did work, and some others did not. But I figured out that the more bigger the remote workspace the more it took to load the analyzer.

So I did a last test, I loaded the original workspace, opened a .dart file and left it alone, it took 15 mins and finally loaded the analyzer.

I'm not sure anymore if there is any problem with the extension or is a vscode problem, however I know that the javascript linter is working at the very same moment the workspace is loaded but the dart analyzer is taking 15 mins under the same workspace.

**Comment by DanTup** [comment]
@efreibe thanks for the testing! This sounds strange - in some of the comments above there was a log of the analysis server terminating, but if it works after a long period, that sounds like it didn't.

Can you confirm if you see `Analyzing...` in the status bar during that long period?

Also, could you post the output of `code --status` when you have the original workspace open? That'll give some stats on the size of the workspace that might help reproduce it.

Thanks!

**Comment by efreibe** [comment]
Hello, sorry for the delay.

> Can you confirm if you see Analyzing... in the status bar during that long period?

No, I do not see Analyzing..., it shows up after 10 or 15 minutes...

> Also, could you post the output of code --status when you have the original workspace open?

Here you have the result of my `code --status` command after aprox 4 minutes of opening the workspace.
Do not know if it matters but `dart.previewLsp: false`

```
Version:          Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS Version:       Darwin x64 19.6.0
CPUs:             Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)
Memory (System):  16.00GB (0.99GB free)
Load (avg):       2, 2, 2
VM:               25%
Screen Reader:    no
Process Argv:     sos.code-workspace
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off_ok
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off_ok
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	    82	 37904	code main
    0	    49	 37916	   gpu-process
    0	    16	 37918	   utility
    0	   262	 37919	   window (cupertino_locale.dart — sos (Workspace))
    0	   131	 37920	     extensionHost
   36	   147	 37954	       /Users/macos/flutter/bin/cache/dart-sdk/bin/dart /Users/macos/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.13.2
    0	     0	 37955	       bash /Users/macos/flutter/bin/flutter daemon
    0	   131	 37974	         /Users/macos/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/macos/flutter/packages/flutter_tools/.packages /Users/macos/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	 37999	           /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0	    33	 38000	             /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	    33	 37923	     watcherService
    0	    33	 37924	     searchService
    0	    98	 37939	   shared-process
    0	     0	 38138	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (cupertino_locale.dart — sos (Workspace))
|    Folder (sos2mobile.old): 8566 files
|      File types: flat(2417) class(802) xml(693) dex(669) json(323) png(286)
|                  h(224) jar(164) m(128) java(122)
|      Conf files: launch.json(1) settings.json(1) makefile(1) grunt.js(1)
|                  package.json(1)
|      Launch Configs: dart
|    Folder (sos-contador): 3579 files
|      File types: cs(1451) js(385) asp(333) bcmap(168) png(122)
|                  properties(105) css(92) txt(72) json(57) jpg(45)
|      Conf files: package.json(19) csproj(9) sln(7)
```

This is my mount point:
`//ernesto@dev.sos-contador.com/sos-contador on /System/Volumes/Data/sos-contador (smbfs, nodev, nosuid, automounted, noowners, noatime, nobrowse, mounted by macos)`

And this is a screenshot of the Activity Monitor past 8 or 9 minutes.
![image](https://user-images.githubusercontent.com/1061126/90092183-9f431900-dcfe-11ea-81ec-d320e35f539a.png)

When the CPU goes to ~ 0%, I go to vscode, press option+space and can see the code completion window filled in and ready to go.

**Comment by DanTup** [comment]
@efreibe is it possible you can enable the analysis server instrumentation log and grab a copy when everything starts working? When you tried above, it seemed like the server was terminating and there wasn't much in the log - but if it's actually working (but very slow to get started), the log should include something.

If it's all working, but just slow to start up, my guess is that the enumeration of the file system is what's slow (the Dart analysis server needs to walk down the tree looking for projects to analyze). You may be able to reproduce that by just opening the smb folder on its own and forcing the Dart extension to activate by creating a single `.dart` file somewhere near the top of the tree.

There is a setting in the current VS Code extension that allows you to exclude folders from analysis - you could add this to the `settings` section of your `.code-workspace` file:

```js
"dart.analysisExcludedFolders": [
  "path/to/folder-to-exclude"
]
```

However, this setting was removed for the upcoming version of the extension because it seemed like for most uses it could be reproduced by using the `exclude` section of `analysis_options.yaml` and it didn't work for LSP - however now I'm wondering whether there's still value in it. If it fixes the issue here, I'll have a think about what would be involved in supporting it for LSP.

**Comment by efreibe** [comment]
I've kept vscode open over the entire night, and logged some interesting info. But one line took my attention:

Analyzer
```
[3:46:09 AM] [Analyzer] [Info] ==> {"id":"10","method":"analysis.setAnalysisRoots","params":{"excluded":[],"included":["/Users/macos/github/sos2mobile.old","/System/Volumes/Data/sos-contador"]},"clientRequestTime":1598942769615}
```

So I went to workspace and appended ```"dart.analysisExcludedFolders": ["/System/Volumes/Data/sos-contador"]```

It worked after a few seconds of opening the workspace. So you are right, maybe this is caused by a slow enumeration of the remote file system plus some other heavy operation that does the analysis server in background.

I solved the issue, but if you want to see the logs I will keep those for a few days more.

**Comment by DanTup** [comment]
@efreibe great, glad it's sorted. I'm going to revert the change to remove the `dart.analysisExcludedFolders` setting for now, as it would result in this issue coming back (and I think it's fair to want to exclude folders from analysis that don't necessarily have an analysis_options file). I'll try to add support for this to LSP so it's not lost when we entirely switch over to LSP.

**Comment by efreibe** [comment]
With the latest version, it asks for enabling LSP extensions. But when I do that, the issue went back again, apparently dart.analysisExcludedFolders is not working for LSP.

I'm attaching two log files created a few minutes ago.

[analyzer-inst.txt](https://github.com/Dart-Code/Dart-Code/files/5898935/analyzer-inst.txt)
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/5898936/analyzer.txt)

**Comment by DanTup** [comment]
@efreibe the setting is supported in LSP since https://github.com/dart-lang/sdk/commit/f7b1a1ee1f91a9d0e900b1e8f2f5e0b764796018, but that has not reached the Flutter stable channel yet. If you need this setting, you'll need to turn off LSP until you're on an SDK that supports it.

The LSP prompt is just a one-time prompt shown to a random set of people to increase LSP adoption (to help track down any remaining issues) so you shouldn't see it again once you've dismissed it (at least until the next Flutter stable release, when we may re-show it).

Hope that helps!
