### ISSUE TITLE
Implement Type Hierarchy for LSP

### ISSUE THREAD

**Issue by zhengger** [Dart-Code/Dart-Code#2527]
How can I revover this function? Thanks! 
My IDE:
Name: Visual Studio Code
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

My Flutter and Dart SDK :3.11.0

![image](https://user-images.githubusercontent.com/2143234/83995129-2389c080-a98b-11ea-8e8f-c4dbb56bab30.png)

![image](https://user-images.githubusercontent.com/2143234/83995086-f806d600-a98a-11ea-9df5-1213a886042d.png)

**Comment by zhengger** [comment]
@DanTup 
Hi Dan, 
Thank you for your help. I think the extension should have been activated cause all works well except the "showTypeHierarch" function. 
How can I check the errors in the Developer Tools. Here is a sreenshot I took:
![image](https://user-images.githubusercontent.com/2143234/84037173-c9abe980-a9d0-11ea-900d-69ee97fe4efe.png)

**Comment by DanTup** [comment]
Ah, ok - in the original screenshot it didn't show Flutter/Dart versions in the status bar, but your latest one does. Are you using the LSP preview mode (`"dart.previewLsp": true` in your VS Code user settings)?

**Comment by zhengger** [comment]
case "dart.previewLsp": false:

![image](https://user-images.githubusercontent.com/2143234/84053276-44323480-a9e4-11ea-87f7-c0eef9854ca6.png)

case "dart.previewLsp": true:
![image](https://user-images.githubusercontent.com/2143234/84053500-95422880-a9e4-11ea-887a-c9564aa10f67.png)

**Comment by zhengger** [comment]
Update:
After I removed all costumed entries related with Dart/Flutter in settings.json file of VS CODE, the Hierarchy function works now.  So I'll close this post now.
Thanks Dan.

**Comment by DanTup** [comment]
I think this is a bug that it doesn't work for LSP (eg. when you have `"dart.previewLsp": true` in settings). Since the goal is to move everything to LSP, this will need fixing.

**Comment by DanTup** [comment]
@bwilkerson since I can't add screenshots to Gerrit, here's how this looks with https://dart-review.googlesource.com/c/sdk/+/264002.

<img width="1031" alt="Screenshot 2022-10-13 at 17 32 09" src="https://user-images.githubusercontent.com/1078012/195653960-d88b3844-045c-4d49-87e1-06e3a70698e7.png">
<img width="1017" alt="Screenshot 2022-10-13 at 17 32 26" src="https://user-images.githubusercontent.com/1078012/195653964-727430ed-3c2a-4f75-a66e-6b30326e4eb9.png">

I may look at adding the type arguments to the class names on the nodes (I think it'd seem more natural to see `List<T>` instead of `List` even if we don't include the concrete type) but I'll do that in another change (I may need to change how we locate the target when it comes back from the client, since we currently use the name).

**Comment by bwilkerson** [comment]
I like the way that looks.

Actual type arguments might be informative. We should be able to just drop everything after the first `<` in order to get back the name to use to locate the target.

**Comment by DanTup** [comment]
> Actual type arguments might be informative. 

By "actual" do you mean those actually used in the declaration of the "parent" node (eg. `List<String>` and not just `List<T>`)? I originally thought that might be odd (because the node represents the class and not some concrete type), although now it occurs to me that the relationship label means the node isn't "generic" anymore and maybe it does make sense. I'll take a look.

> We should be able to just drop everything after the first `<` in order to get back the name to use to locate the target.

Yeah, that could work - although there are a few places we've talked about "element references" in the past and I wonder if they're a better solution here. I have a somewhat-abandoned CL that made it easier to get to/from elements<->strings and I wonder if it's worth extracting and finishing that to use in places like this (and inlay hints tooltips that I need to work on).

**Comment by bwilkerson** [comment]
By "actual" I meant the arguments from the type. For example, in
```
class A<S> {}
class B extends A<int> {}
```
the actual type arguments for `A` are `<int>`. But for
```
class A<S> {}
class B<T> extends A<T> {}
```
the actual type arguments for `A` are `<T>` (the type parameter from `B`).

> I have a somewhat-abandoned CL that made it easier to get to/from elements<->strings ...

I don't remember that CL exactly; does it make use of `ElementLocation`?

**Comment by bwilkerson** [comment]
If you're storing the `Reference` in the summary, then that's obviously the right class to use.

But for this purpose `ElementLocation` has the advantage that it's a public class. On the other hand, I can't find anywhere to convert an `ElementLocation` back into an element, so it looks like the support is incomplete at this point.

**Comment by DanTup** [comment]
> On the other hand, I can't find anywhere to convert an `ElementLocation` back into an element, so it looks like the support is incomplete at this point.

I'll have a look and see if this is something I can add so I can use this here and in a few other places, thanks!

I've opened #4217 to track including the type arguments and will close this one as the basic functionality is implemented (https://github.com/dart-lang/sdk/commit/6f8d1e4859b4052094f2f492aa596b8f6364a412 - shipping in the SDK rather than Dart-Code).
