### ISSUE TITLE
control-click on 'var' should navigate to the type's libraries.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2535]
If I perform a 'ctrl-click' on a type such as:

Widget aWigglyWidget;

Then dart-code takes me to the library for the Widget type.

If I perform a 'ctrl-click' on a var such as:

var  aWigglyWidget = getAWidget();

Then dart-code opens a code lense.
I both cases I want to be taken to the dart library for Widget.

**Comment by DanTup** [comment]
@bwilkerson interested in your thoughts on this (it would need to be done in the server).

**Comment by bwilkerson** [comment]
Yes. It should be fairly straightforward to extend the `_DartNavigationComputerVisitor` to add regions for the keyword `var`.

If we do that, should we also provide navigation from `const` and `final`? If yes, should we always provide it or only when there is no explicit type?

(And out of curiosity, what's a "code lense"?)

**Comment by DanTup** [comment]
> If we do that, should we also provide navigation from `const` and `final`? If yes, should we always provide it or only when there is no explicit type?

I think if it was supported on them without types, it should also work with types - if a user has it in their mind that it works on `const` and their cursor is already on `const`, they might (reasonably) assume it'll work there and press the keybind for it.

> out of curiosity, what's a "code lense"?

In VS Code (and I think VS), there's a feature called [CodeLens](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup) that allows injecting links into the editor. We use it in the VS Code extensions to provide easy links for things like running/debugging tests:

<img width="462" alt="Screenshot 2020-06-11 at 16 17 39" src="https://user-images.githubusercontent.com/1078012/84404710-1a088e80-abff-11ea-9e51-50dc24e07b9b.png">

(unfortunately it doesn't work in the analysis server repo because it uses the outline data to know where tests are, and things work a bit differently there - something that bugs me and I'd love to find a fix for!).

However, I think in this context Brett was referring to the "peek"-style window that opens when Ctrl+Clicking `var`. It turns out we do actually find class, but we *also* include the location of the variable, and that results in VS Code this opening this to pick between the two definitions:

<img width="1143" alt="Screenshot 2020-06-11 at 16 20 54" src="https://user-images.githubusercontent.com/1078012/84405057-8aafab00-abff-11ea-911a-0c7bafe81e77.png">

So it turns out, we don't need to add the location of the class, rather we need to not include the variable. For non-LSP, this could be done in the VS Code extension code (assuming we can tell which one is which - perhaps when there are multiple we should ignore the one that's on the same line that we searched?), and for LSP this would be done in the server. WDYT?

**Comment by bwilkerson** [comment]
> For non-LSP, this could be done in the VS Code extension code (assuming we can tell which one is which - perhaps when there are multiple we should ignore the one that's on the same line that we searched?), ...

Using the line number seems reasonable. It's highly unlikely that anyone will declare the type on the same line as a variable of that type.

> ... and for LSP this would be done in the server.

Yep, that would be the appropriate place. Then it will work the same for all LSP-based clients.

**Comment by DanTup** [comment]
Great - I pushed a fix here for non-LSP and a CL at https://dart-review.googlesource.com/c/sdk/+/150980/ for LSP.

**Comment by bsutton** [comment]
My vote is to include const and final.

I don't think there is any need for it when there is an explicit type but
it wouldn't do any harm either.
