### ISSUE TITLE
Dowloading issue

### ISSUE THREAD

**Issue by Morsheda** [Dart-Code/Dart-Code#2542]
Issue Type: <b>Bug</b>

I have been continuously receiving the notification- "Flutter Setup: Downloading package sky_engine" and can do nothing. It's been nearly 2 weeks

Extension version: 3.11.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Morsheda** [comment]
@DanTup Thank you for your kind response. Now I'm getting this-
![Screenshot (61)](https://user-images.githubusercontent.com/40772371/84487992-61575380-acc1-11ea-99a6-461198d98ae7.png)

**Comment by Morsheda** [comment]
> @DanTup Thank you for your kind response. Now I'm getting this-
> ![Screenshot (61)](https://user-images.githubusercontent.com/40772371/84487992-61575380-acc1-11ea-99a6-461198d98ae7.png)

**Comment by Morsheda** [comment]
Can you please tell how to solve this problem? I have tried re-installing flutter and dart plugins and everything but as soon as I open the project on editor it can't find the dart-sdk path and keep downloading the file forever.

**Comment by DanTup** [comment]
@Morsheda did you resolve this? The error looks like maybe there are connectivity issues. I know there have been some issues in Bangladesh in the past where the internet providers were blocking some of the Google servers used to host Dart and Flutter components.

Did you install using Git? If so, you may have better luck with the zip file (since this includes all of the components to avoid needing to download them the first time you run Flutter):

https://flutter.dev/docs/get-started/install/windows

There should be a big blue button to download the zip there. If it doesn't show a version number (but instead shows something like `(failed)`) then it seems like the servers hosting the SDKs may be being blocked.
