### ISSUE TITLE
Offer 'Organise Imports' quick fix on directive_ordering lint.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#2552]
When using effective dart it generates the lint:

Sort directive sections alphabetically: directives_ordering.

It would make fixing these issues faster if a quick fix was available to call the existing 'Organise Imports' action.

**Comment by DanTup** [comment]
This seems to exist - though because it comes from the server it's called "Sort Directives":

<img width="614" alt="Screenshot 2020-06-17 at 12 34 25" src="https://user-images.githubusercontent.com/1078012/84893308-edd58d80-b096-11ea-85e5-99c09be41fad.png">

I've opened a change to rename this to "Organize Imports" in the LSP server to match:

https://dart-review.googlesource.com/c/sdk/+/151514/

(note: I'm not going to fix it up in the non-LSP version, as I want to migrate over soon and doing everything in two places takes a lot more time - this means you might not see the fix for a little while, but it will come - and the fix is still there in the meantime).

If you're not seeing Sort Directives though, do let me know!

**Comment by bsutton** [comment]
Actually the quick fix isn't showing for me in either the editor quick fix nor the problem quick fix.

![sort_directive](https://user-images.githubusercontent.com/900408/85352234-cc6a1b00-b548-11ea-9057-71dd3d781a0f.png)

Dart Code :v3.11.0

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-37-generic snap

**Comment by DanTup** [comment]
Oh, I see! Can you confirm the exact Dart/Flutter version you have? Does it repro in a clean project if you just enable that lint and put some incorrectly-sorted imports in?

**Comment by bsutton** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.17.4 at /home/bsutton/apps/flutter
    • Framework revision 1ad9baa8b9 (6 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/bsutton/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/bsutton/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Android Studio (version 4.0)
    • Android Studio at /home/bsutton/apps/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

**Comment by DanTup** [comment]
Ok, turns out this fix was actually quite new (https://github.com/dart-lang/sdk/commit/7fe16ba8125ccaa275dfb29bf029cf5d4566c105) so it isn't in the current Flutter stable version. It should show up in a future update for you though :-)

**Comment by ln613** [comment]
How do I apply "Organize Imports" on save? I added "editor.codeActionsOnSave": { "source.fixAll": "always" } to the settings, but no effect.

**Comment by DanTup** [comment]
@ln613 you want `source.organizeImports`:

```js
"editor.codeActionsOnSave": {
	"source.organizeImports": "explicit",
}
```
