### ISSUE TITLE
Unknown operating system. Cannot install Dart SDK.

### ISSUE THREAD

**Issue by Feiks** [Dart-Code/Dart-Code#2556]
How can i solve this problem? before update it was working perfect but now this problem!

**Comment by DanTup** [comment]
I guess you're hitting this message in Flutter:

https://github.com/flutter/flutter/blob/9f92ec2651e4c2310051fa3ab847dd9bbf72b0f4/bin/internal/update_dart_sdk.sh#L75

So it would be better to raise an issue at https://github.com/flutter/flutter/, since this isn't coming from the VS Code extension. You should include what OS you're using in the report, and also the output of `uname -s` since that's what the script is running that results in the message.

Hope this helps!
