### ISSUE TITLE
Support for Dartdoc > Markdown Tables?

### ISSUE THREAD

**Issue by ened** [Dart-Code/Dart-Code#2559]
Is it possible to show markdown tables in the doc previews?

It seems the feature is generally available in dartdoc https://github.com/dart-lang/dartdoc/issues/1453, yet when I tried to add code like this:

```
  /// Return values:
  /// 
  /// | Component | Symbol | Short Form   | Long Form         | Numeric   | 2-digit   |
  /// |-----------|:------:|--------------|-------------------|-----------|-----------|
  /// | era       |   G    | G (AD)       | GGGG (Anno Domini)| -         | -         |
  /// | year      |   y    | -            | -                 | y (2015)  | yy (15)   |
  /// 
  /// 
```

The area for the return values table stays empty, once hovering the relevant function.

**Comment by DanTup** [comment]
Markdown rendering is done by VS Code. It seems like this was supported, but was recently broken:

https://github.com/microsoft/vscode/issues/99983

It's been fixed in the last few days and I can see the fix works in the Insiders version:

<img width="660" alt="Screenshot 2020-06-16 at 14 49 51" src="https://user-images.githubusercontent.com/1078012/84783108-c45a2a80-afe0-11ea-843c-98cf9c2f12a5.png">

So this should be fixed with the next release of VS Code.

Thanks!

**Comment by ened** [comment]
@DanTup Thank you very much.
