### ISSUE TITLE
`Dart: Run All Tests` does not run all tests after VSCode update to 1.46.0

### ISSUE THREAD

**Issue by sabifa** [Dart-Code/Dart-Code#2565]
## Problem
After VSCode updated to 1.46.0 the command `Dart: Run All Tests` only runs a portion of my tests and not all of them.
As you can see on the screenshot only three test suites are run, although there are nine test files inside my project. 
![Problem Screenshot](https://i.imgur.com/6JyRlkD.png)

It looks like it does not _find every test file_ inside the project, but the tests _inside the found test files_ are all being executed.

## Reproduction
1. Create a new project
2. Copy the existing test inside `widget_test` multiple times
3. Create a few duplicates of `widget_test.dart` (e.g. widget_2_test.dart)
4. Run `Dart: Run All Tests`

## Logs
[Dart-Code-Log-2020-05-03 10-45-37.txt](https://github.com/Dart-Code/Dart-Code/files/4791320/Dart-Code-Log-2020-05-03.10-45-37.txt)

**Comment by DanTup** [comment]
It turns out much more than just this command is broken. They're all losing the `noDebug` flag, which causes them to try and run in debug mode (which isn't supported for `flutter test` with multiple files). I've opened https://github.com/Dart-Code/Dart-Code/issues/2566 to track this, though I believe the issue is a regression in VS Code which I've filed at https://github.com/microsoft/vscode/issues/100364.

However this specific issue is fixed as a result of the fix for #2082, which is now triggered by the*Dart: Run All Tests** command as well as running from launch.json.
