### ISSUE TITLE
Jump to file in `import ... as ..` clause doesn't work

### ISSUE THREAD

**Issue by CareF** [Dart-Code/Dart-Code#2572]
Currently we can jump to the import file with `<cmd> + click`, but if the import clause is `import '...' as ..;` It doesn't recognize the file path correctly. 

![Screen Recording 2020-06-18 at 6 07 43 PM](https://user-images.githubusercontent.com/11715538/85076773-d5489e80-b18e-11ea-885c-33f3f706a0c5.gif)

I'm not sure if it's intended so or if I didn't config it correctly, but I would assume consistent behavior should be better.

**Comment by DanTup** [comment]
Thanks for the report! This issue was fixed in the Dart SDK LSP server as part of #2535. In a future release of the SDK when using LSP (which you can opt in to with the `dart.previewLsp` setting, but will eventually become default) you should see the fix.

In the meantime, when you ctrl+click as sown in your screenshot, VS Code should open a "peek" window that lets you see navigate to the definition (though it requires an extra step to select it). Let me know if that's not working for you. Thanks!

**Comment by CareF** [comment]
It works. Thanks! 
Using LSP the hyperlink-like underline always shows in a keyword like the second case in my screenshot, I would assume it would make more sense if the underline shows on the whole '...' import package name, like the first case in the screenshot.

**Comment by DanTup** [comment]
Yeah, I agree. In order to fix that for LSP we need to adopt a new API that allows us to return which range the definition applies to. I've got a note to fix that, though it's not a priority as it's mostly cosmetic. Thanks!
