### ISSUE TITLE
Ctrl+. is not working in every place

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2588]
Consider the following code:

```dart
class CapillaryScheduleStepPhotos extends ⛔StatefulWidget⛔ {
  CapillaryScheduleStepPhotos({✅Key✅ key}) : super(key: key);

  @override
  _CapillaryScheduleStepPhotosState createState() => _CapillaryScheduleStepPhotosState();
}

class _CapillaryScheduleStepPhotosState extends ⛔State⛔<CapillaryScheduleStepPhotos> {
  @override
  Widget build(✅BuildContext✅ context) {
    return ✅Container✅(
       child: child,
    );
  }
}
```

Parts marked with ✅ shows the correct intellisense (for example):

![image](https://user-images.githubusercontent.com/379339/85871026-3c281200-b7a4-11ea-97aa-9fe3dad7b40c.png)

Parts marked with ⛔ shows nothing (for example):

![image](https://user-images.githubusercontent.com/379339/85871085-4f3ae200-b7a4-11ea-9a34-e3a3e0bd3cf7.png)

To reproduce, create a Flutter project and insert the code above (that was created by a snippet), pressing [Ctrl]+[.] when the cursor is on the highlighted keywords.

**Comment by DanTup** [comment]
Thanks for the report! I fixed this recently (https://github.com/Dart-Code/Dart-Code/issues/2536) - the fix wasn't being shown for extends/implements/with clauses. The fix is in the SDK, so it'll automatically appear once you're on an SDK that includes that change (which should include flutter master, but I'm not sure about the other channels yet).
