### ISSUE TITLE
dart fortmat

### ISSUE THREAD

**Issue by nhatnd9504** [Dart-Code/Dart-Code#2596]
Format not correct. It work good in last version.
detail in video. sorry, my english is bad.
https://drive.google.com/file/d/1GBkNJB9xpeZ29qr-_BbhNxOzTSJIkU7z/view?usp=sharing

**Comment by DanTup** [comment]
Thanks for the report! I think this is due to a missing trailing comma - see https://flutter.dev/docs/development/tools/formatting#using-trailing-commas

Code formats differently without trailing commas (the original Dart way). Trailing commas force formatting to something that works better with Flutter UI/Widget code.

In this case, you need a `,` after the last argument to the `BlocBuilder` constructor, and that should cause the formatting that you're after.

If this doesn't work, please paste the code into this issue here so I can easily copy/paste and test it. Thanks!

**Comment by pluveto** [comment]
My dart formatter also works strange without `,`. It will be great if it can be optional by config.

**Comment by DanTup** [comment]
Right now, the SDK formatter (dartfmt) doesn't have any settings for this. There are some relevant issues here though:

- https://github.com/dart-lang/sdk/issues/41779
- https://github.com/Dart-Code/Dart-Code/issues/914

**Comment by nhatnd9504** [comment]
It worked with `,`. Thanks all!
