### ISSUE TITLE
Bring back larger build/hot reload notifications

### ISSUE THREAD

**Issue by rajeshjeshar** [Dart-Code/Dart-Code#2597]
hotreloading process is not showing in the notification bar,I did not updated the flutter sdk,but a few hours before the issue ive seen a notification about "Dart sdk has been updated".
completely uninstalled and recreated a new project but the issue remains same,Only when the hotlreload is finished its logged in console `"Reloaded 0 of 495 libraries in 167ms."`

Expected Progress indication for hotreload is..
![85929623-1ac64380-b8d4-11ea-8a3f-2db99d40f4b0](https://user-images.githubusercontent.com/39165538/86122200-090fb680-baf5-11ea-910f-1cfda2a252e5.png)

**Comment by DanTup** [comment]
Thanks for the report! There was a bug here, but also we adopted a new API in VS Code which unfortunately doesn't show progress notifications for 500ms, so very short progress notifications would not show at all.

For now, I've reverted to handling the progress notifications ourselves. I'll push out a minor update shortly.

Note - even with this change, the status will now show only in the status bar by default (not in a large notification as in your screenshot). This was [requested by the VS Code team](https://github.com/microsoft/vscode/issues/97900#issuecomment-636287081).

**Comment by rajeshjeshar** [comment]
@DanTup " now show only in the status bar",got it just i need the indication,no matter how it will appear.
But for your reference,some times hotreload is not going to be finished less than **500ms**,its average falls from **800ms to 3000ms** depends upon the configuration,may be it is less than 500ms in mac but not in windows.
atleast give it as an optional choice to enable disable inside the `settings.json` .

**Comment by DanTup** [comment]
@rajeshjeshar the new status notification should appear over on the left, and it should show "Hot reloading.." with a spinner. Once it completes, it should show Hot reload complete!" for a further 150ms.

The goal is still to move to the debug-adapter-protocol status message once it's been improved, which gives us no ability to show a larger progress notification. We can do this with custom messages, but I'd really like to stick to the DAP spec so that the debugger is more portable.

Therefore, if the current notifications are not obvious enough, I think it would be better to improve in DAP/VS Code. I'll add a note on https://github.com/microsoft/vscode/issues/101405 about this.

**Comment by DanTup** [comment]
I've opened https://github.com/microsoft/vscode/issues/101791 specifically for VS Code to consider support this with DAP messages. Please add a 👍  to https://github.com/microsoft/vscode/issues/101791!
