### ISSUE TITLE
Test pane does not show tests results if they are run in the VS Code terminal

### ISSUE THREAD

**Issue by hashemp206** [Dart-Code/Dart-Code#2618]
After I run `flutter test` to run all the tests, the test pane is empty. I had to manually run each test file to be appeared in the test pane!

**Expected Behavior:**
It should display all the tests statuses

<img width="1323" alt="Screen Shot 2020-07-08 at 12 09 34 PM" src="https://user-images.githubusercontent.com/3206748/86891825-ae89e200-c114-11ea-95bf-27c2ace7df8e.png">

**Comment by DanTup** [comment]
In order to see the results in the test tree, you need to run the tests through the editor - as this runs them in a special mode that allows us to capture the results. We can't intercept your commands in the terminal to run in "machine mode" to get the results (it's something I'd like to support but it would require VS Code APIs - FYI @Tyriar - this is what discussed at https://github.com/microsoft/vscode/issues/99874#issuecomment-644115406).

The easiest way to run them is with the Run/Debug links you can see just above like 14 in your editor (these also appear on individual tests/groups if you want to run a subset), though you can also press `F5` if you have no launch config (or you can create a launch config with the `program` set to the test file). You can also use the **Dart: Run All Tests** command to run all files at once.

If any of this doesn't work for you, let me know!

**Comment by hashemp206** [comment]
by opening command palette (command + shift + P) then selecting  **Dart: Run All Tests** helped. 

Thanks
