### ISSUE TITLE
Don't add "const" keyword when using "wrap with padding" if in constant context

### ISSUE THREAD

**Issue by eladcandroid** [Dart-Code/Dart-Code#2622]
Since Dart doesn't need that anymore

**Comment by DanTup** [comment]
@bwilkerson "Wrap with Padding" currently generates code that uses `const` for the `EdgeInsets` (`padding: const EdgeInsets.all(8.0)`).

It does seem like this isn't necessary for the code to work - but I'm not sure if removing it changes the meaning (eg. it may create multiple instances of the class with the same arguments, rather than a single shared instance?).

**Comment by bwilkerson** [comment]
Yes, removing the `const` subtly changes the meaning so that multiple instances of `EdgeInsets` might be created. But I believe that the original motivation for including `const` is because Flutter best practices are to make every widget a `const` when possible. My understanding (based on things I've been told and several articles on the web) is that using `const` whenever possible improves the performance of Flutter apps. Because of that, server will generally insert `const` when possible.

> Since Dart doesn't need that anymore

I'm not sure what you mean by that. The keyword `const` is still required in order to create a constant object unless the instance creation is inside a constant context. The operation isn't currently checking whether the insets are in a constant context, so in that case it might produce an unnecessary keyword. I have a CL out to fix that as a result of this report. If you meant something different, then please let me know.

**Comment by eladcandroid** [comment]
@bwilkerson I thought that it's just an old syntax and we can dismiss it. Thanks for your in-depth explanation!

**Comment by DanTup** [comment]
Great, thanks!
