### ISSUE TITLE
Pubspec.yaml is confused for a dart file while analyzing

### ISSUE THREAD

**Issue by miyoyo** [Dart-Code/Dart-Code#2629]
In some instances,  the pubspec file is considered like a dart file by the analyzer, which results in "noise" errors clogging up the error panel.

From (extremely) simple testing, the issue is only confirmed on Windows.

Dart version: `Dart VM version: 2.9.0-14.1.beta (beta) (Tue Jun 9 10:52:57 2020 +0200) on "windows_x64"`

also confirmed on: `Dart SDK version: 2.9.0-21.1.beta (beta) (Fri Jul 10 10:02:57 2020 +0200) on "windows_x64"`

Windows version: 1909 Build 18363.900

Analysis file of 2.9.0-14:
[analysis.txt](https://github.com/Dart-Code/Dart-Code/files/4904148/analysis.txt)

Analysis file of 2.9.0-21:
[analysis.txt](https://github.com/Dart-Code/Dart-Code/files/4904245/analysis.txt)

Instrumentation log:
[instrument.txt](https://github.com/Dart-Code/Dart-Code/files/4904614/instrument.txt)

Project on which this happens:
[mpk.zip](https://github.com/Dart-Code/Dart-Code/files/4904151/mpk.zip)

![A simple pubspec file, Only a name, description, author and sdk version are specified.](https://cdn.discordapp.com/attachments/615553440969392151/731174399654494239/unknown.png)
![A list of errors generated by the analysis issue](https://cdn.discordapp.com/attachments/615553440969392151/731174371095478282/unknown.png)
![The file is known by vscode to be a Yaml file](https://cdn.discordapp.com/attachments/615553440969392151/731174426535788604/unknown.png)

**Comment by DanTup** [comment]
@bwilkerson I can't repro this on my Mac with the same project. I'll see if I can repro on Windows later, though in case you have any thoughts on what might cause it in the meantime/if I can't!

**Comment by bwilkerson** [comment]
No, sorry, I don't have any ideas. I've never seen this in my own use nor do I remember seeing any user reported issues like this before. I know that server has checks so that only files ending in `.dart` should be analyzed as Dart files, but there must be a bug that causes those tests to fail in this case.

Actually, there's one exception to that rule that I can think of. If analyzer sees an import of a file it assumes that the file is a Dart file without checking the file suffix, so if there were an explicit import of the `pubspec.yaml` file (which there isn't) then it might very well get confused. But that doesn't appear to be the problem here.

**Comment by DanTup** [comment]
@miyoyo I'm not seeing this with the same SDK/project on Windows either. Do you have any files in the project that aren't included in the zip? Is it possible you may have selected the pubspec in an `import` statement (perhaps code-completing it)?

There's nothing revealing in the log - the server initially finds no errors in the pubspec, then after VS Code sends a request for fixes for unpack.dart, it sends the error for pubspec:

```
[18:18:02] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[18:18:07] [Analyzer] [Info] ==> {"id":"85","method":"edit.getFixes","params":{"file":"C:\\Users\\hidden\\Programming\\Dart\\mpk\\lib\\src\\unpack.dart","offset":221},"clientRequestTime":1594397887828}
[18:18:07] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[18:18:07] [Analyzer] [Info] <== {"event":"analysis.errors","params":{"file":"C:\\Users\\hidden\\Programming\\Dart\\mpk\\pubspec.yaml","errors":[{
```

Does this happen on any other projects are only this one? A server [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) may be useful (perhaps it'll show something the traffic log does not). Otherwise, I'm not sure what else to try besides running the server from source (or a custom snapshot) with additional logging.

Maybe also worth trying closing VS Code, deleting/renaming `%APPDATALOCAL%\.dartServer` and then reopening. I'm not entirely familiar with what's cached in there, but it's one place I can think that there may be something old hanging around.

**Comment by DanTup** [comment]
Though FWIW, I tried importing the pubspec.yaml explicitly, and it says it doesn't exist (which isn't technically correct, but does seem to be guarded against).

**Comment by miyoyo** [comment]
> Do you have any files in the project that aren't included in the zip? Is it possible you may have selected the pubspec in an import statement (perhaps code-completing it)?

Unless 7zip can't access them when packing the folder, no, all the files are in the zip.

I'll give the instrumentation log a shot, be right back

**Comment by miyoyo** [comment]
@DanTup Added the instrumentation log to the original post

**Comment by miyoyo** [comment]
@DanTup Same thing when deleting .dartServer

**Comment by miyoyo** [comment]
A wierd thing is that nothing happens for one, two minutes, yet after that time, saving the pubspec (which clears the errors) and then doing anything in the dart file **immediately** respawns the errors.

**Comment by DanTup** [comment]
Ok, nothing revealing in the instrumentation file either - however it did show the same thing - when requesting quick-fixes in unpack.dart, the errors were sent. So - I opened up `unpack.dart` and put the cursor at the same location (on `Stream`) - and the errors appeared!

I'll do some digging and figure out what's going on.

**Comment by DanTup** [comment]
@bwilkerson ok, I think I understand what's happening here, though I don't know what the fix is.

In the code project, this error is generated:

> The class 'Stream' wasn't exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions.
> Try either importing 'dart:async' or updating the SDK constraints.

The request for fixes results in the `UpdateSdkConstraints` fix to be computed, which tries to generate edits for `pubspec.yaml`. That ends up calling `getResolvedUnit`:

<img width="1206" alt="Screenshot 2020-07-13 at 12 37 55" src="https://user-images.githubusercontent.com/1078012/87300442-b6c39200-c505-11ea-8ef5-097d77c655ea.png">

And that ends up queuing a result to analyze that file (which is then picked up in `performWork` and sent to `_computeAnalysisResult` - which seems to only expect Dart files).

I'm not sure exactly which bit of this is wrong though - should DartChangeBuilder be trying to get a resolved result for a Yaml file?

**Comment by DanTup** [comment]
I'm not sure if it's correct that `UpdateSdkConstraints` was even passed a `DartChangeBuilder`? It seems like `DartChangeBuilder` is designed for edits to Dart files only?

**Comment by bwilkerson** [comment]
Yes, `DartChangeBuilder` is designed to build changes for a Dart file, so this fix should not have been passed one. The fix is a little more complicated to explain than it is to implement, so I created a CL to fix the problem: https://dart-review.googlesource.com/c/sdk/+/154240.

**Comment by DanTup** [comment]
@bwilkerson great, thanks!

**Comment by DanTup** [comment]
@miyoyo the fix has landed in the Dart SDK. You could test it out in a [nightly build](http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/) from tomorrow (it might take a little longer to roll into Flutter).

To reproduce it, you need to trigger the request for quick fixes on for the error "The class 'Stream' wasn't exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions.". The easiest way is probably clicking the error in the Problems view or putting your cursor on the type `Stream` in `unpack.dart`.
