### ISSUE TITLE
when vscode formatOnSave, comments include Chinese become garbage characters

### ISSUE THREAD

**Issue by firee** [Dart-Code/Dart-Code#2647]
vscode version: 1.47.1
dart-code version: 3.12.2
flutter version: 1.17.5

before is  // 赛事赛况
after is   // ��事赛况

**Comment by DanTup** [comment]
I think this may have been fixed by 6741ecf76c4645b478e9d2011ec2ac08bf9d782f. Could you try out this beta version and see if the issue is gone?

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.13.0-beta.2

### To install: 

- Downloading the attached `vsix` file from that release
- Run the **Extensions: Install from VSIX** command from the VS Code Command Palette
- Select the `vsix` file
- Click the **Reload** button

Thanks!
