### ISSUE TITLE
Please add layout editor for easy development

### ISSUE THREAD

**Issue by fisforfaheem** [Dart-Code/Dart-Code#2667]
Issue Type: <b>Feature Request</b>

Please add layout editor for easy development we need it

Extension version: 3.12.2
VS Code version: Code - Insiders 1.48.0-insider (0a7364f00514c46c9caceece15e1f82f82e3712f, 2020-07-22T05:49:27.463Z)
OS version: Windows_NT x64 10.0.19041

**Comment by DanTup** [comment]
Can you clarify exactly what you mean by a "layout editor"?

DevTools does have a feature called "Layout Explorer" that is described here:

https://flutter.dev/docs/development/tools/devtools/inspector#using-the-layout-explorer

There's also a preview flag that lets you embed DevTools directly inside VS Code:

https://dartcode.org/releases/v3-12/#preview-embedded-devtools

Let me know if this isn't what you had in mind. Thanks!

**Comment by fisforfaheem** [comment]
No, We want a simple Layout editor like windows forms editor on visual
studio IDE

**Comment by DanTup** [comment]
Got it. This isn't something that's currently planned - though there are some related tools like the layout explorer mentioned above and IntelliJ has a "Hot UI" preview feature (https://github.com/flutter/flutter-intellij/wiki/HotUI-Getting-Started-instructions).

A better place to raise this request would be in the [DevTools repo](https://github.com/flutter/devtools/), since if something like this was built, it would likely be done in DevTools so it could be embedded in multiple editors without each needing their own implementation.

Thanks!

**Comment by fisforfaheem** [comment]
Thanks for the kind reply, I hope you yourself would be excited about this,
as this will make programming easier like we do here in windows form apps,
less code more UI

**Comment by DanTup** [comment]
> I hope you yourself would be excited about this, as this will make programming
> easier like we do here in windows form apps, less code more UI

It's not something I'm personally too excited by - I prefer the idea of building UIs in code - I find it much simpler to do things dynamically, and with Hot Reload the results are visible almost immediately. I do understand why others may prefer it though (especially when getting started), which is why I think it's a reasonable request. It's just not something we should build directly in VS Code, as that would prevent users of other editors from being able to use it.

I'll close this issue, but if you do file an issue in DevTools, feel free to post the link here for others to find if they come across this issue. Thanks!
