### ISSUE TITLE
Not showing Hot restart / reload notifications 

### ISSUE THREAD

**Issue by Caballero75** [Dart-Code/Dart-Code#2726]
After updating to 3.13.2, notifications for hot restart/ reload stopped showing on status bar, as used to be. 
Logs on Debug Console are still showing after task completed 
Reloaded 2 of 526 libraries in 2,575ms.

**Comment by BootBlock** [comment]
I've tried to repro the issue here and it appears to be working for me (VS Code **1.48**, DC **3.13.2**), so could you try the following to help with investigating the issue?

- In the _Help_ menu, select _Toggle Developer Tools_ and see if there are any errors/exceptions listed in the Console.

Run a Capture Logs:

- Build/Run your application as normal.
- Using the Command Palette in VS Code, type/run **Dart: Capture Logs** (ensuring to untick _Analysis Server_).
- Perform the Hot Restart/Reload, and hit Cancel in the "capturing logs" notification when the restart/reload appears to have completed.
- After checking/editing the log for any sensitive information, attach it as a file to your reply.

Thanks!

**Comment by Caballero75** [comment]
After completely reinstall of vs code, deleting settings and extensions folder, now it's working again.  Thanks @BootBlock and Dart Code Team
