### ISSUE TITLE
Invalid syntax highlightning for methods named "get" or "set"

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#2748]
The built-in identifiers `get` and `set` are blue when used in property declarations.

The problem is that they are blue also if they are used as normal method names, The expected behavior is that they have the same color as other normal methods.

This cosmetic issue is now more visible as the latest official Firestore plugin introduced renamed methods `Query.get()` and `DocumentReference.set()`. Also other popular plugin `get_it` uses a method named `get`.

**Comment by DanTup** [comment]
This is a limitation of how we currently do syntax highlighting. The plan is to switch to proper semantic highlighting as part of the LSP migration. There's an issue open about this (which by coincidence I was just working on!) at https://github.com/Dart-Code/Dart-Code/issues/2202

It's not complete yet (the LSP spec has not been finalised), but I just tested with `get` and `set` and they are coloured the same as methods when they're methods, and keywords when they're keywords:

<img width="792" alt="Screenshot 2020-08-27 at 15 34 30" src="https://user-images.githubusercontent.com/1078012/91456129-d24ae800-e87a-11ea-8112-8f6843b8faff.png">

I'll close this as a dupe, but you can subscribe to #2202 for updates on when it ships (though it will require both a Dart-Code and an SDK update since the LSP server lives in the SDK).

Thanks!

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/cb2ede57b7c91fb61c0cb05971cc1823faee2086.

In order to get the fix you'll need Dart-Code v3.18.0 (a preview release should be available later today/tomorrow), be using LSP Preview, and have a Dart SDK from after yesterday ([the most recent nightly](http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/) works, and of course the next releases of Dart/Flutter SDKs will include this).

<img width="1145" alt="semantic_tokens" src="https://user-images.githubusercontent.com/1078012/102212500-3e566800-3ecd-11eb-981e-60cd1be42111.png">

**Comment by DanTup** [comment]
Due to some last minute issues, support for LSP 3.16 (which supports semantic tokens) won't be included in v3.18, but hopefully the next release after that.
