### ISSUE TITLE
vscode randomly reports 1000+ errors in pubspec.yaml

### ISSUE THREAD

**Issue by gkrawiec** [Dart-Code/Dart-Code#2749]
At random times, (i have not been able to replicate it reliably) vscode suddenly reports thousands of errors in pubspec.yaml.
If I recall correctly this started about 1.5 weeks ago.

The issue is temporarily solved by simply opening pubspec.yaml and forcing a save (cmd+s in mac). Instantly the errors all disappear and everything goes back to normal.
Though I cannot replicate it at will, I know I am not the only one with this issue as it has been posted about on reddit
https://www.reddit.com/r/flutterhelp/comments/ih7q4g/many_errors_700_in_pubspecyaml_randomly_showing/

Doctor summary
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
 [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)

Let me know if I can help by providing any other info.
thank you!

**Comment by DanTup** [comment]
I believe you're seeing https://github.com/Dart-Code/Dart-Code/issues/2629 which has recently been fixed but the fix has not reached the stable SDKs yet. It happens when the server tries to produce a quick-fix for the pubspec, for example like the one for this message:

> The class 'Stream' wasn't exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions.
> Try either importing 'dart:async' or updating the SDK constraints.

It incorrectly treats the pubspec as a Dart file and generates a lot of errors.

If you think it'snot the same issue, let me know and we can re-open this and do some more investigation. Thanks!
