### ISSUE TITLE
Add model class snippet

### ISSUE THREAD

**Issue by CodeDoctorDE** [Dart-Code/Dart-Code#2755]
I've created a snippet to have an easier way to create classes: https://gist.github.com/CodeDoctorDE/242b24d35ba1359801bd0df1d548b133.

It will be cool if you add it to the officical extension

**Comment by DanTup** [comment]
Thanks for the idea, though I think this is something better served in user snippets or a separate extension. The current snippet functionality doesn't allow contextual snippets, which mean the show up on completion *everywhere* (not just where it's appropriate) and for all users. For example here's a `main` function definition snippet showing up where it definitely is never wanted:

<img width="821" alt="Screenshot 2020-08-31 at 10 10 33" src="https://user-images.githubusercontent.com/1078012/91703546-44207b80-eb72-11ea-82d2-2e25e4296135.png">

Because of this, I'd prefer to keep the list short and relevant to as many users as possible until there is some way to control these better (for example [moving them to the analysis server](https://github.com/dart-lang/sdk/issues/37831) and providing them contextually).

Hope this makes sense!
