### ISSUE TITLE
Touch Bar buttons don'ts how up during a debug session if control strip is enabled

### ISSUE THREAD

**Issue by AminTebi** [Dart-Code/Dart-Code#2757]
@DanTup I'm using flutter in visual studio code. I saw that you posted some screenshots of the touch bar which they are showing "hot reload", "restart", "open dev tools" buttons on it but for me just showing 2 left and right arrows. 

For you and others:
[![](https://user-images.githubusercontent.com/1078012/56286122-d3a9c380-6110-11e9-8f1a-3784dbd952b6.jpg)
](url)

[![](https://user-images.githubusercontent.com/1078012/54115523-82593680-43e4-11e9-9a36-863e8c2272a5.png)
](url)

For me: 
https://drive.google.com/file/d/19ZGPkuLk8HRawxd129PMTWb_Q4aXaQrj/view?usp=sharing

I would be glad if you help me to make my touchbar more usefull in visual studio code.

**Comment by DanTup** [comment]
@AminTebi I don't seem to have access to that file (though I clicked request).

**Comment by TshineZheng** [comment]
same here

**Comment by TshineZheng** [comment]
![WechatIMG3](https://user-images.githubusercontent.com/8209564/93160159-57bb0d00-f742-11ea-8fff-96d2ecdf7e23.jpeg)
same here
```shell
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by AminTebi** [comment]
> @AminTebi I don't seem to have access to that file (though I clicked request).

@DanTupI would be great if you give access to files. If they are not secret. Or tell me how can I build these buttons.

**Comment by DanTup** [comment]
@AminTebi I'm not sure which files you mean. The file I referred to was your Google Drive link that I couldn't access - though now I can see your picture above.

This seems like a VS Code issue - as the standard debug buttons (resume/pause/step) are also missing, and those are rendered by VS Code. I've sen other reports that if there are too many buttons, they all vanish (rather than being truncated). You could try disabling "Show control strip" (see https://github.com/microsoft/vscode/issues/68214#issuecomment-462025149) to give more space.

Let me know if that works - if so, maybe we should reduce the number of buttons by default so it still renders with that option enabled.

**Comment by AminTebi** [comment]
> @AminTebi I'm not sure which files you mean. The file I referred to was your Google Drive link that I couldn't access - though now I can see your picture above.
> 
> 
> 
> This seems like a VS Code issue - as the standard debug buttons (resume/pause/step) are also missing, and those are rendered by VS Code. I've sen other reports that if there are too many buttons, they all vanish (rather than being truncated). You could try disabling "Show control strip" (see https://github.com/microsoft/vscode/issues/68214#issuecomment-462025149) to give more space.
> 
> 
> 
> Let me know if that works - if so, maybe we should reduce the number of buttons by default so it still renders with that option enabled.

Hey, @DanTup thanks for your attention. Yes, the buttons appear when I hide my control strip.is there any solution to have the vs code touch bar buttons and the control strip at the same time?

**Comment by DanTup** [comment]
Until VS Code supports a scrolling touchbar, the only options are to remove some of the items. I remembered you can do this with a setting in VS Code:

```js
"keyboard.touchbar.ignored": [
        "_flutter.screenshot.touchBar",
    ],
```

This will hide the screenshot button, which should reduce the width and may cause it to come back even with the control script visible. Please let me know if it works for you. Thanks!

**Comment by AminTebi** [comment]
@DanTup I did a search I find that how can I remove the right and left arrow keys on the touch bar and when I removed them flutter buttons appear on the touch bar with control strip.

**Comment by AminTebi** [comment]
@DanTup I have to say really thank you for your help and your attention.

**Comment by DanTup** [comment]
Great, that sounds like a good solution too.

I think VS code will eventually support scrolling (or at least truncating the end rather than rendering nothing), so I'll close this as I don't think there's anything to do in the extension (though this issue will hopefully help people find workarounds if they're having the same issue). Thanks!
