### ISSUE TITLE
Analysis not working in sub-directory of dart SDK

### ISSUE THREAD

**Issue by vsmenon** [Dart-Code/Dart-Code#280]
I'm on a Mac (Sierra 10.12.4) with VS Code Version 1.11.2 (1.11.2), Dart Code 1.1.0, and Dart SDK 1.23.0-dev.11.10.

I used to be able to open VC Code on a sub-directory of the sdk (e.g., pkg/dev_compiler) and have working analysis, code completion, etc.  

This doesn't work since updating to the latest Dart Code extension.  I've tried downgrading VS Code and/or the SDK - that doesn't seem to make a difference.  Not sure if the extension itself can be downgraded.

I *can* open up the SDK root dir - analysis & completion work there.  I've avoided that in the past as it's a lot of files.

**Comment by vsmenon** [comment]
It appears to be related to the search added here:

https://github.com/Dart-Code/Dart-Code/commit/c1b3a2a429e15f9395032757650f0c75e81dc9d2#diff-45327f86d4438556066de133327f4ca2R191

**Comment by vsmenon** [comment]
Ahh, changing this line to remove the `pubspec.yaml` check gets it working for me:

https://github.com/Dart-Code/Dart-Code/commit/c1b3a2a429e15f9395032757650f0c75e81dc9d2#diff-45327f86d4438556066de133327f4ca2R208

**Comment by vsmenon** [comment]
Adding a dummy `pubspec.yaml` to `pkg/dev_compiler` also works.  We don't use one right now as we rely on the top-level SDK `.packages` file instead.

Still, maybe that check is not really necessary?  If `rootPaths` is empty, it seems as analysis is silently disabled.

**Comment by DanTup** [comment]
The change in the latest release was to fix things not working correctly in the Flutter repo (see the original bug report at the top of #275). However there were subsequently comments suggesting that the analyser should handle this internally and I shouldn't need all this code so my plan is to revert and investigate further (I hoped to have done it by now, but I'm struggling to find time lately!).

> Ahh, changing this line to remove the pubspec.yaml check gets it working for me:
> If rootPaths is empty, it seems as analysis is silently disabled.

The purpose of that line is to say if there don't appear to be child packages then assume the workspace folder is a dart project itself, or also if it includes a `pubspec.yaml` assume the same.

If it's valid to nest projects (I don't know, but the `pubspec.yaml` existence check assumes so) then maybe this entire `if` should go and it should always add the root. However, I don't know the implications of sending it for analysis if it's *not* a real dart project (eg. if you open up a folder that contains child dart projects, would you then get loads of errors for the "root" folder because it was sent to the analyser?).

Anyway, solving #275 properly is the best fix (undoing the change in the last release and then understanding why the Flutter repo didn't work properly). I hope to get some time to spend on this on Friday so with any luck I can push a change out to fix it.

In the meantime, adding a dummy pubspec is probably the easiest workaround though I appreciate that's not ideal.

Btw, does this work ok in Atom? I thought I'd copied its behaviour (which is why it seemed reasonable to me!) but it's possible something isn't the same.

**Comment by vsmenon** [comment]
A dummy `pubspec.yaml` seems to be working fine for me.

Not sure about Atom - I had some problems last time I tried it (which was a while ago).  Maybe it was this.  :-)

**Comment by DanTup** [comment]
I've reverted the change made to fix #275 and raised it at https://github.com/dart-lang/sdk/issues/29414 with a small repro.

I'll hold off pushing any update out until I've had a response (since if it's a Dart Code issue, I can probably fix both in the same release rather than fix this and reintroduce the other).

**Comment by DanTup** [comment]
Probably won't get chance to look at this till next Friday now, but I'm going to look at if I can put the workaround that caused this bug behind a flag (or detect when it's needed) until the analyzer is updated to handle it correctly.

**Comment by DanTup** [comment]
v1.2.0 has been published which reverts the workaround made for the Flutter repo (unless `packages\.gitignore` is detected) so this should now be resolved correctly.

Once the Analyzer supports folders named `packages` that aren't from pub, I'll remove the workaround entirely.

Let me know if this fixes your issue properly!

**Comment by vsmenon** [comment]
@DanTup - yes!  Analysis works without the dummy `pubspec.yaml` now.  Thanks!
