### ISSUE TITLE
Could not find Dart in your Flutter SDK

### ISSUE THREAD

**Issue by thatho-blip** [Dart-Code/Dart-Code#2827]
after updating vscode i try to create new project and i got this errors:

1.flutter : The term 'flutter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or   
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ flutter create Myweb
+ ~~~~~~~
    + FullyQualifiedErrorId : CommandNotFoundException
2.Could not find Dart in your Flutter SDK. Please run 'flutter doctor' in the terminal then reload the project once all issues are resolved. We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by DanTup** [comment]
> 1.flutter : The term 'flutter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name

This error happens if you you try to run `flutter` from the terminal if the SDK\bin  folder is not in your `PATH`. This isn't something the VS Code extension has any involvement in, but there are instructions on how to set `PATH` here (assuming you're on Windows):

https://flutter.dev/docs/get-started/install/windows#update-your-path

You may need to restart after changing `PATH` for it to take effect properly.


> 2.Could not find Dart in your Flutter SDK

This usually happens if you have not run `flutter` before so it has not downloaded the required components. I wouldn't expect this to happen anymore, as we should automatically invoke Flutter. Could you click the **Show Log(* button on the message and provide the log file? Thanks!


> We have written the needed data into your clipboard because it was too large to send. Please paste.

It's not clear what this bit relates to. Where did you see this?

**Comment by DanTup** [comment]
Please let me know if you're still having this issue and can try/answer the things above and we can re-open this. Thanks!
