### ISSUE TITLE
Dart from Flutter

### ISSUE THREAD

**Issue by Htet-Wai-Yan** [Dart-Code/Dart-Code#2831]
Issue Type: <b>Bug</b>

Dart form Flutter extension doesn't start automatically when open the program the first time.

1. Open VS Code
2. check the status bar at the bottom.
3. Dart from Flutter is missing
4. Close the VS Code
5. Reopen VS Code
6. check the status bar at the bottom.
7. Dart from Flutter is running this time.

Extension version: 3.14.1
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:26:09.944Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz (2 x 2554)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|1.93GB (0.11GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id ed72bf69-1293-438c-9311-f579f9b77fce|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by DanTup** [comment]
Can you still reproduce this? Could you provide a screenshot showing the status bar when the text is missing?

If Flutter was downloading the Dart SDK (which is may do on first use), then I would expect this text not to show up until it's finished (though you should see some progress indication that this is happening). The text will also only show up when you have a `.dart` file open.

**Comment by Htet-Wai-Yan** [comment]
Thanks for the quick response.

I was not able to reproduce the issue as it seems only happening at the very first time I open VSCode.
But I attached the SS here per your request.

Thanks

![VSCodeSS](https://user-images.githubusercontent.com/35678784/94587980-54c72d00-02a9-11eb-87cd-45fd6f1d3e43.png)

**Comment by DanTup** [comment]
I can reproduce a delay in it appearing by deleting my `flutter/bin/cache` folder, but if I open a Flutter project I'd see this:

<img width="512" alt="Screenshot 2020-09-29 at 17 46 38" src="https://user-images.githubusercontent.com/1078012/94588394-be304700-027b-11eb-85d4-c042a98a9826.png">

If you open a non-Flutter project (just Dart) and don't have any Dart on your `PATH` I would expect to see a message saying the SDK could not be found. If you have another (non-Flutter) Dart SDK on your `PATH` then it should use that (which means the "Dart from Flutter" text might just say "Dart x.y.zzzz").

If you can reproduce an issue where it doesn't do any of these things, please let me know what you did (and send a screenshot showing the problem occurring). Otherwise I don't think there's much to go on here. Opening VS Code for the first time shouldn't really be any different to any other time (except for the case where Flutter hasn't downloaded it's components, which should behave as described above).

I'll keep this open for now in case you're able to reproduce and/or provide instructions. Thanks!

**Comment by Htet-Wai-Yan** [comment]
Hi,

Non of the issue you mentioned above happens and now its working fine.
If this happens again, I will just reopen the app.
I guess we can close this case now.
Thanks a lot.

**Comment by DanTup** [comment]
Ok, do let me know if you see it again. Thanks!
