### ISSUE TITLE
Test tree should scroll to the failed test.

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2835]
When you execute a test, the test tree always scrolls to the currently executed test, which is great. But when the test turns from green to red, the test jumps to the top, but the test tree doesn't scroll to the top. Only after executing the test again, it scrolls to the top.

**Comment by DanTup** [comment]
This might be that we call `reveal()` on the node before the tree is properly updated (re-sorted for statuses). Delaying the reveal until after the data is updated (or at least with a small delay/`setImmediate`) might fix it.

**Comment by DanTup** [comment]
@HerrNiklasRaab actually, I'm struggling to repro this. I had a very long list of green tests in the second suite, an I caused on to fail. This moves the suite to the top of the list, but it also scrolled the tree up so that the newly-failed test (though not the suite - as that was still scrolled off the top) was still visible.

Can you still repro this? Can you capture a recording, or give more detailed that might help me reproduce it? Thanks!

**Comment by HerrNiklasRaab** [comment]
https://imgur.com/a/SZ4Nzlb

**Comment by DanTup** [comment]
Thanks! I think I can repro. Doesn't seem to happen the test is very fast, but does if I add a delay.
