### ISSUE TITLE
Allow hiding DevTools buttons from debug toolbar

### ISSUE THREAD

**Issue by TheMisir** [Dart-Code/Dart-Code#2836]
**Is your feature request related to a problem? Please describe.**
I would like to hide "DevTools Widget Inspector" button from debug toolbar. Because I can access faster to DevTools using command bar.

![image](https://user-images.githubusercontent.com/29130291/94728502-6116bd00-0371-11eb-8f11-38b97c095f44.png)

**Describe the solution you'd like**
Ability to setting visibility of "DevTools Widget Inspector" button on debug toolbar.

**Comment by DanTup** [comment]
Does leaving the button cause any issues? I don't think it's worthwhile introducing a setting to control the visibility of this if it's purely just visual.

**Comment by TheMisir** [comment]
> Does leaving the button cause any issues? I don't think it's worthwhile introducing a setting to control the visibility of this if it's purely just visual.

No it doesn't causes any issue. It's just visual but, I'm using docked toolbar and it takes a bit too much space.

![image](https://user-images.githubusercontent.com/29130291/94740184-3e8d9f80-0383-11eb-9cb9-1c776d1765f5.png)

**Comment by TheMisir** [comment]
Nevermind. Just asked if it's possible to disable. 

> I'm not sure it's worth adding an additional setting only for this.

Anyways adding a setting for enabling/disabling additional feature that modifies editors default behavior (UI in that case) is not unnecessary.

I would contribute this feature if maintainers would allow.

**Comment by DanTup** [comment]
Ok, I think it may be possible to do this entirely in package.json - eg. add a setting and then use it in the `where` context for the `debug/toolbar` contributions - without any code changes/custom context. See [this page](https://code.visualstudio.com/docs/getstarted/keybindings) under "Configuration settings contexts".

If that works, I'd accept a contribution for that. I don't think it's worthwhile if we need to handle the config in code and maintain a context though.

The setting should be named something so that it applies to all DevTools buttons and not just the inspector (if you run in profile mode, you'd see a Timeline button instead) - for ex. `dart.showDevToolsInDebugToolbar`.
