### ISSUE TITLE
Device list stays empty

### ISSUE THREAD

**Issue by ened** [Dart-Code/Dart-Code#2866]
**Describe the bug**
No connected devices appear in the VS Code interface.

**To Reproduce**
1. Open VS Code, click on the "no Device" button in the status bar

**Expected behavior**
Should show the one device connected.

**Versions (please complete the following information):**
 - VS Code version: 1.50.0
 - Dart extension version: v3.15.0
 - Dart/Flutter SDK version: 1.22.0

**Additional info:**

Perhaps this is due to the output of `flutter devices` looking like this:

```
1 connected device:

SM G975F (mobile) • R58M36QGTJM • android-arm64 • Android 10 (API 29)

• Error: aPhoneXr is not connected. Xcode will continue when aPhoneXr is connected. (code -13)
```

**Comment by DanTup** [comment]
Could you post the full output of `flutter doctor -v` and also  `flutter devices -v` (perhaps in a gist since that one may be very long).

Also it may be worth enabling the [Flutter device daemon logging](https://dartcode.org/docs/logging/#flutter-daemon) which will capture the traffic between the VS Code extension and the device daemon.

**Comment by ened** [comment]
I tried to gather the logs and noticed that `flutter doctor -v` was hanging,

It seemingly was waiting for `xcdevice`. Once I `killall xcdevice`'d them all, this started working. 

Will report again when this is showing again.
