### ISSUE TITLE
VS Code Intellisense not showing all the classes in the project in the autocomplete

### ISSUE THREAD

**Issue by akshg05** [Dart-Code/Dart-Code#2867]
**Describe the bug**
There are instances when few classes in my project are not shown in the auto complete of the VS Code intellisense. This happens randomly for some classes and I am unable to figure out why or which kind of classes.
Auto import for those classes do not work as well on pressing Ctrl+I
It doesn't happen for all the classes but few.
If I open the file containing the class, the class is shown in the autocomplete and when the file is closed, it doesn't appear in the autocomplete.

**To Reproduce**
I am not sure how to reproduce this issue exactly as it happens randomly.

**Expected behavior**
I expect the VS Code Intellisense to show me all the classes matching my typed keywords.
I expect the classes to be imported shown on pressing Ctrl+ I and selecting the appropriate class path.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.50.0 (latest)
 - Dart extension version: 3.15.0
 - Dart/Flutter SDK version: 1.20.2

**Comment by DanTup** [comment]
It's going to be very difficult to troubleshoot this without specifics. Are you able to provide a copy of a project in the exact state when you see this that I could reproduce with?

**Comment by akshg05** [comment]
I am afraid I cannot produce a copy of the project :( .
Though I could provide screenshots when the problem occurs but I wonder how well it could help.
My project is quite a bit nested and all of the missed classes in the Intellisense happen at random :/

What else could I help you with in the troubleshooting?

**Comment by DanTup** [comment]
> If I open the file containing the class, the class is shown in the autocomplete and when the file is closed, it doesn't appear in the autocomplete.

Do you have the `dart.previewLsp` setting enabled? This sounds a lot like the issue described at https://github.com/Dart-Code/Dart-Code/issues/2286#issuecomment-658597532 and fixed in https://github.com/dart-lang/sdk/commit/0de2455c02a508efbbf529c7051db1f1eabc7807.

You're currently on an outdated version of Flutter (the current stable is 1.22). Could you try updating to the latest (with `flutter upgrade`), which should include the fix above and might solve this issue? Thanks!

**Comment by akshg05** [comment]
Tbh, It seems my issue is pretty much opposite of what I did see in the gif in the comment you referred here if I understand correct.
In the gif, the person is unable to import when the file is open. My case be I'm able to import/ see in autocomplete when the file is open and not when the file is closed.
Also, I do not know what dart.previewLsp is. I'll check and update here.
I'll try upgrading flutter today and give a check.
I'll update the outcomes soon after testing it up.
Thanks!

**Comment by DanTup** [comment]
If you haven't enabled LSP specifically, it's probably not the same issue. However you can confirm this by hovering over the Dart/Flutter version in the status bad and see whether it says "DAS" or "LSP" in the tooltip:

<img width="376" alt="Screenshot 2020-10-15 at 15 52 44" src="https://user-images.githubusercontent.com/1078012/96146844-a35a0580-0efe-11eb-87be-4fa94529b822.png">

If it says "LSP" it could be the same issue, but if it says "DAS" then it won't be.

Anyway - let me know if it still occurs on the latest version. If it does, I would suggest taking a copy of your project next time it happens to see whether restarting VS Code loading the exact same code still has the problem. If so, you could then try to strip that copy of the project down to something that you can share (that still has the problem) and I can try to debug.

**Comment by akshg05** [comment]
I updated Flutter and VS Code as well lately. Though I cannot confirm the issue has been swept away as it's very random. I'll update here after using some more time if it occurred again. I'm not sure if stripping the code and sharing  would help as I said before it's very random. Though I could provide you the skeleton of the Project to the last leaf. May be it could help.
Also I'm using Ubuntu and Code seems laggy at times. I'm not sure if it has anything to do with it but who knows! lol

**Comment by DanTup** [comment]
If you do start seeing it again, it's worth enabling [the analysis server log](https://dartcode.org/docs/logging/#analyzer). Then when you next see it, I would take a screenshot of the code, grab a copy of that log file, and also a copy of your project - and see if you can reproduce it with exactly that code again. If so, it should be easier to debug - and if not, the log might at least help understand what might have happened.

I'd also suggest enabling the LSP preview (with the `dart.previewLsp` setting) since it'll become default in future and does change how completion works slightly (so if the bug is in the completion handling inside the extension, that might sidestep the issue - since that code will be removed in future anyway). Thanks!

**Comment by akshg05** [comment]
I dud update Flutter, Dart to latest stable releases
I didn't get much time to get back to that project of mine so can't comment
if it has been mitigated completely .
I'll try having the analysis server on when I see the issue next.

Thanks!
