### ISSUE TITLE
Dart-Code could be able to use flutter packages get instead of pub get

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#287]
There's a problem currently between Dart and Flutter, and no one seems to really know whose problem it is, so they're suggesting passing it to the editors. See: flutter/flutter#6284

When a project has `flutter: sdk: flutter` in its pubspec.yaml, `pub get` fails with exit code 69.

My plan of attack for this is to follow the template of f7513f95ef72acf49c8eefae58a077aaf3b177bd and make a new `dart.flutterProject` option, and in sdk.ts inside of the on-save hook for pubspec.yaml, have it check whether `dart.flutterProject` is enabled and run `flutter packages get` instead.

If that sounds correct to you, I'll crank it out today.

**Comment by DanTup** [comment]
> make a new `dart.flutterProject` option

Wouldn't it be better to detect this from the presence of `flutter: sdk: flutter` rather than requiring the user to set an option?

**Comment by DanTup** [comment]
#286 is related - the Dart SDK path should be changed for Flutter projects. They should probably both use the same mechanism for detecting a Flutter project (probably we should also detect if it changes and prompt the user to restart, like changing the SDK path does, so that a clean project which gets turned into a flutter project doesn't fail).

**Comment by Skylled** [comment]
I'm not so sure that's the problem, as I've set `"dart.sdkPath": "C:/flutter/bin/cache/dart-sdk"` and still run into the issue.

As for detecting the line, I thought about that route, but don't know the first thing about how VS Code & Dart-Code actually work. As far as I can understand, in sdk.ts, you have a hook when saving (presumably any) file that checks an option and checks the filename, without ever parsing the file itself.

The other reason for adding an option, I was considering other future areas of Dart-Code that could be optimized for Flutter that should only be enabled for Flutter projects.

I'll follow your lead, either way, if you can point me in the right direction.

**Comment by DanTup** [comment]
> I'm not so sure that's the problem, as I've set `"dart.sdkPath": "C:/flutter/bin/cache/dart-sdk"` and still run into the issue.

Sorry, maybe I confused things. Using that Dart SDK won't resolve this issue (the need to use `flutter` for package restore), it's just an additional problem that needs solving for flutter projects. However we decide to detect flutter packages can be used to solve both of these issues (but they will both need individual fixes based on that detection).

> As for detecting the line, I thought about that route, but don't know the first thing about how VS Code & Dart-Code actually work

The entry point is [`activate` in `extension.ts`](https://github.com/Dart-Code/Dart-Code/blob/85249fd0dc21174ed68ef964a32c559d5a3ae5cc/src/extension.ts#L42). The first thing it does is call `util.findDartSdk()`. Probably before that it should call some code to detect if it's a flutter project and if so use a special path (instead of calling `util.findDartSdk`, but still using that for non-flutter). That would probably be the fix for #286.

[Further down, where we register SDK commands](https://github.com/Dart-Code/Dart-Code/blob/85249fd0dc21174ed68ef964a32c559d5a3ae5cc/src/extension.ts#L157) we could possibly pass in that flag that says it's a flutter project into `SdkCommands` and then it can perform different logic for the commands if flutter.

Finally, the [file watcher on pubspec](https://github.com/Dart-Code/Dart-Code/blob/ad7869e543ccd823a2343e2d7eb50d62d3c7734c/src/commands/sdk.ts#L54) could be tweaked to re-detect flutter SDK and if if the value changes (either it was flutter and now is not, or vice versa) then prompt the user to reload similar to when [analyzer settings change](https://github.com/Dart-Code/Dart-Code/blob/85249fd0dc21174ed68ef964a32c559d5a3ae5cc/src/extension.ts#L242).

What do you think?

**Comment by Skylled** [comment]
I see the possibility of a Flutter project becoming non-Flutter or vice versa as being an extreme edge case, especially considering flutter makes projects into a new folder with a lot of boilerplate. I'll look into doing the rest this afternoon.

**Comment by DanTup** [comment]
Yeah, sure. However if you're starting from scratch, it's possible your pubspec wouldn't have `sdk: flutter` in it when the extension activated so it might be confusing to the user why things aren't working.

Prompting to reload is fairly trivial to add if the code to detect it exists though. I've been hoping to work on #286 this weekend but it's not going to happen, so any progress you make on this should save me some effort there! :-)
