### ISSUE TITLE
VS code dart extension 3.15.1 not working with flutter 1.22.2

### ISSUE THREAD

**Issue by IrateBT** [Dart-Code/Dart-Code#2882]
**Describe the bug**
After upgrading the extension to 3.15.1 in vs code, the project was not recognised as a Flutter project.
As a result, flutter run, flutter doctor, flutter new project, nothing was working anymore

**To Reproduce**

1. Install Dart extension update to 3.15.1
2. Open Folder with existing/working Flutter app
3. Try to Run the app (F5 / ctrl+F5)

**Expected behavior**
The app start running on connected device/emulator

**Screenshots**
with 3.15.1
![image](https://user-images.githubusercontent.com/13303789/96339793-0f6f7180-1097-11eb-9c6f-e07228f619d3.png)
with 3.15.0
![image](https://user-images.githubusercontent.com/13303789/96339830-46458780-1097-11eb-9b68-e316a8287692.png)

**Versions (please complete the following information):**
 - VS Code version: 1.50.1
 - Dart extension version: 3.15.1
 - Dart/Flutter SDK version: Dart SDK version: 2.10.2 / Flutter 1.22.2

**Fix
Downgrade vs code dart extension to 3.15.0 using install from VSIX (file found on https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code)

**Comment by DanTup** [comment]
I think something else must be going on, it's unlikely the change from v3.15.0 to v3.15.1 is the cause since it [only includes changes to the debug adapter functionality](https://github.com/Dart-Code/Dart-Code/compare/v3.15.0...v3.15.1).

Could you reproduce this and then run the **Dart: Open Extension Log** command and provide the log file? This will show what happened during startup when looking for the SDKs.

Thanks!

**Comment by IrateBT** [comment]
Hello DanTup,

I guess I must have hat some problems with caching, I have been searching for hours yesterday and today everything is fine after upgrading to 3.15.1

I'm sorry for the inconvenience, maybe I should have rebooted my desktop first.

B

**Comment by DanTup** [comment]
No worries - if it comes back, please let me know (and try to grab the log mentioned above). Thanks!
