### ISSUE TITLE
Missing Extract Method refactoring

### ISSUE THREAD

**Issue by hevzy86** [Dart-Code/Dart-Code#2884]
Missing Extract Method refactoring

 - VS Code version: 1.50.1
 - Dart extension version: v3.15.1
 - Dart/Flutter SDK version: 1.17.4
  -Dart 2.8.4

Trying to select this block of code and extract it in a separate method but getting only (Wrap with column, Wrap with row, Extract Local variable )  :
`Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Container(
              color: Colors.orange,
              child: SizedBox(
                width: 100,
                height: 100,
              ),
            ),
            Container(
              color: Colors.red,
              child: SizedBox(
                width: 100,
                height: 100,
              ),
            ),
            Container(
              color: Colors.purple,
              child: SizedBox(
                width: 100,
                height: 100,
              ),
            ),
          ],
        ),
      ),`
![extractMethodIssue](https://user-images.githubusercontent.com/23268336/96385953-ac9cd980-116d-11eb-9c45-bcffb6bf048a.png)

**Comment by DanTup** [comment]
This seems to occur when you have the trailing comma included in the selection. Reducing the selection to not include the comma seems to cause the refactors to show up.

@bwilkerson do you think this is something that could/should be handled in the server? It would mean the range of code actually extracted would be slightly smaller than the actual range the user selected (though I don't think that should cause issues?).

**Comment by bwilkerson** [comment]
If we want to attempt to address this, then yes, the server seems like the right place to do so. I can't think of any reason for this to be an IDE specific behavior.

The question I have is whether it's both a good idea for the tool to guess the user's intent and whether this is impacting enough users to make it worth not addressing other issues.

The problem with trying to guess the user's intent is that doing so can lead to very confusing behavior. We currently require that the user select either a single expression or a list of contiguous statements. If the refactoring isn't available it's generally fairly easy to understand why because the rule for what constitutes a valid selection is fairly simple. Server doesn't attempt to either narrow the selection nor to expand the selection in order to get some valid chunk of code. Both approaches seem reasonable under certain circumstances (such as the one in this issue), but as soon as we start doing either (or worse, both), the rules for what is or isn't a valid selection, and consequently what a user needs to do in order to fix the selection, become much harder to remember and understand. I think we'd actually be doing our users a disservice to start going down this road.

And even if I thought that doing so was a good idea, given how simple it is to learn the rule about what needs to be selected I think that there are a lot of much higher priority issues that we should be spending our time fixing.

**Comment by DanTup** [comment]
@bwilkerson thanks for the info! I was in two minds about it too, so if you're also leaning towards it being better not to change the selection, that sounds fair to me.

@hevzy86 to get the refactor, you can either reduce your selection to not include the trailing comma, or - perhaps more conveniently - just don't select anything at all. If you just invoke the lightbulb menu with the cursor on `Container` it'll do exactly that expression anyway:

<img width="445" alt="Screenshot 2020-10-19 at 19 26 05" src="https://user-images.githubusercontent.com/1078012/96496285-f4d8fc00-1240-11eb-8127-f7776cf72a4f.png">

Hope this makes sense!

**Comment by hevzy86** [comment]
> @hevzy86 to get the refactor, you can either reduce your selection to not include the trailing comma, or - perhaps more conveniently - just don't select anything at all. If you just invoke the lightbulb menu with the cursor on `Container` it'll do exactly that expression anyway:
Hello, thank you for reply, indeed selecting without trailing comma seems to be working fine, but if i'm selecting just container i don't have extract method option. 
![justContainer](https://user-images.githubusercontent.com/23268336/96591226-6bb3da80-12bd-11eb-9e13-15440795d735.png)

**Comment by DanTup** [comment]
@hevzy86 I'm struggling to reproduce this. Can you make a small file that has the issue and paste the entire file here for me to try with?

Can you also confirm exactly what position your caret is at when you invoke the list, and also your versions of Flutter?

Thanks!

**Comment by DanTup** [comment]
Oh, I can reproduce this if I highlight the Widget name (eg. `Container`). However that's expected for the same reason - you can't extract just the widget name as a method. But if you have no selection at all, it should work.

In my screenshot it may have looked like I had selected the widget name, but that's just the highlighting, it was't a selection.

Let me know if you still don't see it when you have no selection, and just invoke the menu with the caret somewhere in the widget name. Thanks!
