### ISSUE TITLE
Can't set DISPLAY when running VS Code remotely to a Linux machine

### ISSUE THREAD

**Issue by anaisbetts** [Dart-Code/Dart-Code#2903]
I realize that this is a bit of a Deep Cut, but I'm trying to use VS Code Remote SSH to develop Flutter apps on Linux. So, the app runs remotely and I want to see it via Nomachine / VNC, but edit locally. However, since there's no way for me to set the `DISPLAY` environment variable, running the app means it'll insta-crash.

1. Use VS Code's remote SSH feature to connect to a Linux machine with a Flutter project set up
2. Try to run the app

It'd be cool to be able to set environment variables of any kind for the Flutter child process

**Comment by anaisbetts** [comment]
It looks like as a workaround, Flutter "attach to process" seems to do exactly what I want after some manual URL copy-pasting

**Comment by DanTup** [comment]
I don't have the ability to try these easily, but you could try:

- The `env` field in `launch.json` - https://dartcode.org/docs/launch-configuration/
- The `dart.env` setting - https://dartcode.org/docs/settings/#dartenv

The first would be better since it would only apply to the thing you want (the latter applies to many things). Let me know if this doesn't work - setting env vars should definitely be supported.
