### ISSUE TITLE
Web - VSCode launches on localhost:8080 by default, refused to connect

### ISSUE THREAD

**Issue by awfin** [Dart-Code/Dart-Code#2911]
**Describe the bug**
It is concerning that the default Flutter app created in VSCode has a configuration that prevents a workable launch, following the official doc instructions. There is also no official documentation (and limited online community) coverage on this issue.

**To Reproduce**
1. Install VSCode and Flutter according to https://flutter.dev/docs/get-started/install/macos#web-setup
2. Create a new Flutter app in VSCode
3. Click Run > Run Without Debugging
4. Chrome window opens with localhost:8080, page shows refused to connect error
5. If I launch by terminal, or replace the default "pwa-chrome" config in launch.json by the following
```
        {
            "name": "Flutter for web",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart",
            "args": [
              "-d",
              "chrome"
            ]
        }
```
then it launches as desired

**Expected behavior**
1. Click Run > Run Without Debugging
2. Chrome window launches with the app

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.50.1
 - Dart extension version: 3.15.1
 - Dart/Flutter SDK version: 1.23.0-18.1.pre

**Comment by DanTup** [comment]
I'm not unable to reproduce this, by creating a new project and clicking Run -> Run Without Debugging it ran on a random port:

<img width="354" alt="Screenshot 2020-10-29 at 12 24 20" src="https://user-images.githubusercontent.com/1078012/97573474-bc27e800-19e1-11eb-872b-98797237e7db.png">

Could you capture a log?

- Run the **Dart: Capture Logs** command
- **Un**tick **Analysis Server** but leave everything else ticked and click **OK**
- Reproduce the issue
- Click **Cancel** on the logging notification
- Attach the log here

Thanks!

**Comment by awfin** [comment]
I tried to launch a new project with VSCode Flutter extension, however this time I got the right launch config
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "test2911",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```

instead of the one that caused the error which contained
```
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        },
```

**Comment by DanTup** [comment]
Ah, I see. `pwa-chrome` is not related to this extension, and therefore we can't control what it does. I suspect when you tried to run the project you didn't have a Dart file open, so it should've shown this prompt:

<img width="668" alt="Screenshot 2020-11-02 at 12 07 58" src="https://user-images.githubusercontent.com/1078012/97866610-256e6a80-1d04-11eb-933f-1c1b8ea1228f.png">

Here only the "Dart & Flutter" option will invoke our code. If you run the others, it will invoke their debuggers.

Let me know if you have any further issues/questions!

**Comment by Dusica73** [comment]
I cant find window how to change environment

**Comment by DanTup** [comment]
@Dusica73 you'll have to be more specific for me to help. It would be better to file a new issue than comment on the bottom of closed issues. Thanks!

**Comment by WarmBreezeRising** [comment]
@DanTup Hi,
> @WarmBreezeRising if deleting the `launch.json` file resolves the issue, it suggests there was something incorrect in there. If you're able to share a `launch.json` that prevents things from working, I may be able to explain what.
How to obtain a bogus launch.json:
1. Launch the debug of your project for chrome once
2. Stop the debug
3. Launch another time: This time, vscode ask you for a target (or device, idk how you would call it) which it didn't ask on first run. Amongst the target you have chrome which I selected. VScode then generate a launch.json file:
```
{
    // Utilisez IntelliSense pour en savoir plus sur les attributs possibles.
    // Pointez pour afficher la description des attributs existants.
    // Pour plus d'informations, visitez : https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
This file is the problem.

Another way to have this bogus configuration is going to menu:
`Run > Add a configuration`
and then select `Chome: Launch`
which gives a somehow similar entry which is as bogus as the previous one;
```
        {
            "name": "Launch Chrome",
            "request": "launch",
            "type": "pwa-chrome",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        },
```

Another way to see the problem is searching in google:
`vscode flutter launch.json localhost not working site:stackoverflow.com`

The are so many threads, unfortunatly not anwsering the problem. I suspect sometimes people are having different problems, but you'll find many questions with the auto-generated snippets I mentioned. Deleting it is painful, because you eventually have to delete it many times.

> Generally you shouldn't need a `launch.json` unless you need to customise something, but doing so should not impact this. However if you do create one, it does need to be set to use the `dart` debugger (and not another language/extension like the `pwa-chrome` one noted above).
That maybe an answer which could help a lot of people (even if we just consider questions on stackoverflow). At least it worked for me.

I used `Run > Add a configuration` once again and this time selected `Dart: Launch` and `Flutter: Launch`
Both generate the same entries except for the names of the records:
```
    {
            "name": "Flutter",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart"
        },
        {
            "name": "Dart",
            "type": "dart",
            "request": "launch",
            "program": "bin/main.dart"
        },
```

I'm following the flutter first app tutorial, so, I don't have a real advised look upon all of that. I wonder if this could make a difference in the case you want to specify a launch url (does it make any sense ? I don't know for now). And I don't know why the `Chrome; Launch` option exists and don't work, neither why the others work. They launch chrome probably because I selected it as a target a the bottom right of vscode. All of this is a mistery to me (and apparently, to a lot of people).

But using those `Dart: Launch` and `Flutter: Launch` seems to work (at least for my simple case).

**Comment by DanTup** [comment]
I've opened a VS Code issue to see if this prompt could be made clearer (and not create a `launch.json` unnecessarily). Please add 👍  if you'd like to see some changes there:

https://github.com/microsoft/vscode/issues/146338

**Comment by WarmBreezeRising** [comment]
@DanTup Thanks for your replies and explanations. It helped a lot for me and hope it helps others.
I voted for the issue you opened. Any of the solutions would indeed make more sense and be less confusing (at least for beginners).
Anyway, thanks a lot

**Comment by cryptoyamalab** [comment]
Hi all!


{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "file": "${workspaceRoot}/index.html" // check that this line is added if getting local8080 host error when launching chrome 
        }
    ]
}
