### ISSUE TITLE
Anaysis server crashes frequently on Windows

### ISSUE THREAD

**Issue by abolajimustapha** [Dart-Code/Dart-Code#2913]
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.15.1`
- OS Version: `Windows_NT x64 10.0.10586`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 389,
		"activateCallTime": 1672,
		"activateResolvedTime": 5002,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "onLanguage:dart"
		}
	},
	"runtimeErrors": []
}

please how do i fix this. my dart analyzer crashes too often
```

**Comment by DanTup** [comment]
> please how do i fix this. my dart analyzer crashes too often

There is currently an issue on Windows where running Flutter apps can cause the analyzer to crash (see https://github.com/Dart-Code/Dart-Code/issues/2814). This is caused by two issues in the SDK:

- https://github.com/dart-lang/sdk/issues/40348 (fixed, but not yet in Flutter stable)
- https://github.com/dart-lang/sdk/issues/43941 (not yet fixed)

You can get the first fix (which should make things better) by using a different Flutter branch (for example dev) - however that may come with other issues. You can subscribe to https://github.com/dart-lang/sdk/issues/43941 for updates on the other issue.

Hope this helps!
