### ISSUE TITLE
High CPU usage of dart analysis server

### ISSUE THREAD

**Issue by nikolajjsj** [Dart-Code/Dart-Code#2914]
**Describe the bug**
The analysis server keeps "analyzing" visible in vscode as a notification, and in the text below (screenshot) there is a 94% cpu usage

**To Reproduce**
1. I open vscode and a simulator and within 5 minutes it happens

**Screenshots**
CPU %   Mem MB     PID  Process
    1       98     903  code main
    5       82     908     gpu-process
    0       16     910     utility
    3      279     912     window (create_tweet_bloc.dart — Osprey)
    0        0     917       /usr/local/bin/fish -l
    0        0    3655         bash /usr/local/bin/code --status
   14       33    3665           electron_node cli.js 
   43     1163     922       extensionHost
   94     1049     936         /Users/nikolaj/Dev/sources/flutter/bin/cache/dart-sdk/bin/dart /Users/nikolaj/Dev/sources/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.15.1

**Versions (please complete the following information):**
 - VS Code version: 1.50.1
 - Dart extension version: 3.15.1
 - Dart/Flutter SDK version: 1.22.2 (stable)

**Comment by gyakhoe** [comment]
Facing the same issue. Even small changes are causing the analyser to run and run for very long time. I have attached screen shot for reference. 

![Screenshot 2020-11-02 at 9 58 18 AM](https://user-images.githubusercontent.com/11713403/97829435-239bab80-1cf2-11eb-817d-840bfa61d67f.png)

**Comment by nikolajjsj** [comment]
Adding the following to Settings.json helped me:
    "dart.previewLsp": true.

**Comment by gyakhoe** [comment]
> Adding the following to Settings.json helped me:
> "dart.previewLsp": true.

I have applied the changes you have suggested and for past 15 minutes I was working on my flutter project with applied changes I no longer see my analyser going crazy. I works very well. Care to share what this change actually does?

**Comment by DanTup** [comment]
`dart.previewLsp` switches communication between VS Code and the Dart Language Server from a proprietary protocol to [the Language Server Protocol](https://microsoft.github.io/language-server-protocol/).

Mostly this should make no difference to users, as it's just an internal API being migrated, however it comes with some performance improvements because:

1. We don't need to shop as much data from the server into the client in order to support auto-import completions (most of this work exists in the server using the new protocol)
2. With less work in the client (extension), there's less contention for the single thread that all VS Code extensions have to share

The issues probably can be solved in the original protocol, but since the goal is to fully migrate to LSP fairly soon anyway (and remove the ld protocol code) my recommendation for anyone with perf issues is to just switch to LSP early.

Is anyone still seeing perf issues *after* enabling the LSP preview?

**Comment by DanTup** [comment]
Since it seems like LSP has improved performance for both of you, I'm going to close this. Please let me know if you do see issues with LSP enabled in future though!

**Comment by gyakhoe** [comment]
> Since it seems like LSP has improved performance for both of you, I'm going to close this. Please let me know if you do see issues with LSP enabled in future though!

Thank you for taking your time to reply in such a elaborate manner.

**Comment by easazade** [comment]
I still have this problem. it's really annoying

**Comment by DanTup** [comment]
@easazade if you're having issues and there are no open issues covering your problem, please file a new issue. It's hard to track problems tagged onto the end of closed issues. Thanks!

**Comment by gorkemalgan** [comment]
I was tired of dart analyzer consuming 150% cpu and taking up to 15 minutes to load. What resolved my problem was changing in vs code settings Extensions->Dart->Other->Project Search Depth from 5 to 1. Now it loads almost instantly and no more high CPU usage
