### ISSUE TITLE
Make most flutter command be runnable without read/write permission to sdk location

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#2918]
I have two users on my Linux system, and both would like to use a shared flutter sdk instead of duplicate sdks.

When putting flutter sdk in /usr/local, I get the following error when trying to build...

```
Flutter failed to open a file at "/usr/local/flutter-sdk/bin/cache/lockfile". The flutter tool cannot access the file.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
```

I would be nice it most flutter command like "flutter build" did not require read/write access to the sdk location, so shared sdk's would be possible.

**Comment by DanTup** [comment]
Thanks for the suggestion! These commands (and the use of the lock file) are from Flutter itself rather than the VS Code extension, so this would need to be implemented there and should be raised at https://github.com/flutter/flutter/. There may be reasons it has to work that way, but that's something the Flutter team would be better to decide/advise on.

(Another possible option might be to have a shared folder that both users have write permissions to?)

**Comment by safield** [comment]
I 100% thought I was on the Flutter repo lol. Woops.
