### ISSUE TITLE
Auto Hot Reload Flutter on VSCode

### ISSUE THREAD

**Issue by callmejm** [Dart-Code/Dart-Code#2940]
**Describe the bug**
it just suddenly wont work , not sure it is about the auto update of vscode from `1.50.1` to `1.51.0`

**Versions (please complete the following information):**
 - VS Code version: 1.51.0
 - Dart/Flutter extension version: 3.16.0
 - Flutter SDK version: 1.22.1

**Update (after question posted 10min)**
I downgrade vscode version to `1.50.1` , hot reload back to normal , so not sure why vscode `1.51.0` not compatible to current version of Dart/Flutter vscode extension 

**Out of topic**
vscode `1.51.0` seem not auto reveal "jumping" to my flutter project file (vscode sidebar), downgrade to `1.50.1` back to normal again . weird.

**Comment by DanTup** [comment]
Thanks for the report! I'm unable to reproduce this - hot reload on-save seems to work as expected. Are you able to capture a log?

- Run your application as normal
- Run the **Dart: Capture Debugger Logs** command from the command palette
- Make a change to your app and click Save
- Click **Cancel** on the logging notification to open the log file
- Attach the log file here

> vscode `1.51.0` seem not auto reveal "jumping" to my flutter project file (vscode sidebar)

Someone else has mentioned this - though I believe this is a VS Code issue. I can reproduce it even with `explorer.autoReveal: true` so I think it should be raised at https://github.com/microsoft/vscode. Thanks!

**Comment by callmejm** [comment]
@DanTup I not dare to upgrade `1.51.0`  version to capture the log

**Comment by DanTup** [comment]
@callmejm you can always downgrade if you still have issues afterwards. It's hard for me to investigate if I can't reproduce and you're unable to capture a log, as it's not clear what's happening.

Thanks!

**Comment by callmejm** [comment]
I closing this issue , just now upgrade to `1.51.1` work fine. Not sure is the analysis server terminate randomly (even happen when I downgrade). Hope the hot reload issue not happen again, it might drag our working progress. Thank you @DanTup

**Comment by DanTup** [comment]
> Not sure is the analysis server terminate randomly

If you're on Windows and find the analysis server terminates after you run a Flutter app, ensure you're on the latest stable version of Flutter (v1.22.4) as it has some fixes for that very issue.

**Comment by callmejm** [comment]
@DanTup I will try it out, thx

**Comment by callmejm** [comment]
@DanTup updated to 1.22.4 , still exist analysis server terminate randomly, every time need to manually restart, suddenly terminated again

**Comment by DanTup** [comment]
@callmejm does this happen only when you run (or `clean`) a Flutter app? Can you click the "Show Log" button to get the log file?

If it's the same issue, we'll need to open an issue in the Flutter or Dart repos for it to be looked at, as the previous issues are VM issues rather than VS Code extension issues. Thanks!

**Comment by sanalkv** [comment]
vscode auto save not working for me

**Comment by DanTup** [comment]
@sanalkv if you mean just auto-save is not working, that sounds like a VS Code issue. If you mean auto-save is not triggering reload, that's a known change (see https://github.com/Dart-Code/Dart-Code/issues/3110), but an option for this will be available in the next release.

**Comment by sanalkv** [comment]
I just figured out that vscode auto-save is working fine. The issue is with the hot reload which is not being called during auto save. I completely reinstalled vscode thinking its vscode related issue. Thanks for letting me know @DanTup, I'm really not sure why that feature was taken down. Hope it will be added to the next release soon.

**Comment by DanTup** [comment]
> I'm really not sure why that feature was taken down. Hope it will be added to the next release soon.

The hot-reload-on-save feature was always only intended to occur when you explicitly pressed save (the intention was to avoid having to perform two actions, a save, and a reload). It was somewhat accidental that it triggered on auto-save and caused some users issues. However, since removing it it's become clear that it actually worked well for many people, so it will return as [an option](https://github.com/Dart-Code/Dart-Code/issues/3110#issuecomment-771561427). Hope this makes sense!

**Comment by sanalkv** [comment]
Thanks for the information. Hope you will mention here when the new update is released. Thanks again.

**Comment by DanTup** [comment]
You should see a toast notification in VS Code whenever the extension updates, though they're also announced [on Twitter](https://twitter.com/DartCode) and in the [Discord announcement channel](https://discord.gg/DVDjc7MuNe).

**Comment by sanalkv** [comment]
Sure, i will look into that.

**Comment by alx-xlx** [comment]
is there anything working ? I can't get to auto hot reload my flutter in vsc

**Comment by DanTup** [comment]
@alx-xlx it's difficult to provide a good answer without more details. I'm not aware of any current issues relating to hot reload. If you're having problems, please file a new issue and include a detailed description of what you're doing, what you're seeing, and what you expect to see.

Comments on closed issues can be easily overlooked, whereas open bugs are much more visible.

Thanks!
