### ISSUE TITLE
With VSCode 1.51 IntelliSense does not work properly

### ISSUE THREAD

**Issue by Wikiwix** [Dart-Code/Dart-Code#2948]
Since the update to VSCode 1.51 ([which brought many changes to IntelliSense](https://code.visualstudio.com/updates/v1_51#_intellisense)), the code completion does no longer work as expected for me:

When I hit insert at that point:

![image](https://user-images.githubusercontent.com/5161388/98649769-43f1e880-2338-11eb-9677-11597af37874.png)

I expect `Icon()` to be inserted instead the result is:

![image](https://user-images.githubusercontent.com/5161388/98649820-553af500-2338-11eb-8a03-b1b1fb09a2bc.png)

This happens for `dart.previewLsp` enabled **and** disabled

For Python it still works as expected which is why I suspect it has to do with DartCode in combination with the IntelliSense changes.

**Comment by DanTup** [comment]
Did you reload VS Code after disabling the LSP preview? I believe this is a dupe of https://github.com/Dart-Code/Dart-Code/issues/2823 but should only affect LSP.

**Comment by Wikiwix** [comment]
I just double checked and you are right. When I tested both settings for `dart.previewLsp` I might have only restarted the extensions host which apparently is not sufficient…
Thanks for the "fix"!

**Comment by Wikiwix** [comment]
I just ran into the issue again and I am now able to reproduce it:
If the setting `"dart.enableCompletionCommitCharacters": true` is set I get the un-intended behaviour. If it is turned off it works again.

**Comment by DanTup** [comment]
@Wikiwix if you enable commit characters, it's ended that you would press `(` to commit the code completion if you want to insert `()`. If you commit the completion with tab or enter, it will *not* include them. The goal of using commit characters is to let you decide whether to insert this based on the key you press to commit (this makes it easier to both call functions, and pass the function instead of calling it).

If you want the parens to be inserted always, even when completing with tab/enter, you should not enable `enableCompletionCommitCharacters`.

(Note: for LSP we don't yet support insert parens still - but that's being tracked in https://github.com/Dart-Code/Dart-Code/issues/2823).

**Comment by Wikiwix** [comment]
Ah, ok.
I expected something else from the setting's description 🙈 
As there is no unknown issue I raised, I am sorry for the hassle.
But thanks for the great tools and the support :)

**Comment by DanTup** [comment]
No worries! You can subscribe to #2823, though I believe I'm close to landing an implementation for that (though it's in the analysis server so will ship within a Dart/Flutter SDK update rather than a VS Code extension update).

> I expected something else from the setting's description 🙈

Feel free to raise additional issues if there are other features you'd like to see!
