### ISSUE TITLE
"Deprecated" warning is not reported always

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#2966]
"Deprecated" warning is not reported for this code:

```dart
final c = MyClass(data: "a", data2: "b");

class MyClass {
  MyClass({this.data, this.data2});
  final String data;
  @Deprecated("this member is deprecated")
  final String data2;
}
```
I noticed this while using deprecated `child` parameter of  `showDialog` by accident. It is not reported as warning either.

Dart Code v3.16.0

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.51.1)
[√] Connected device (1 available)

**Comment by DanTup** [comment]
I made a fix for the code sample here, however it turned out to be correct (see [here](https://github.com/dart-lang/sdk/issues/44373#issuecomment-737776172)). You may deprecate a field to prevent it being used externally (as a field) without wanting to deprecate the argument (for example you may make the field private in future, and leave the constructor in-tact).

However, I don't think this is the same issue you're seeing with `showDialog`, as that's a function and not a constructor.

Are you able to provide a code sample where you see this for `showDialog`? I tried to reproduce, but it correctly triggered a warning (and was also stuck through in the editor).

Thanks!

**Comment by kinex** [comment]
Thank you for investigating this. Maybe a slightly unexpected behavior to me, but I try to understand it :)

This simple code does not give a warning in my environment:

```dart
showDialog(context: context, child: Text("Hello"));
```

With this code I get a warning for a deprecated member `title` (so I do get some deprecated warnings):

```dart
showDialog(
    context: context,
    child: Text("Hello", style: Theme.of(context).textTheme.title));
```
Another test:

```dart
void foo({int a, @Deprecated("deprecated") int b}) {
  //
}

void foo2(int a, @Deprecated("deprecated") int b) {
  //
}

foo(a: 1, b: 2); // I get a warning for using b
foo2(1, 2); // no warnings here
```
Call to `foo` is quite similar as call to `showDialog`.... strange.

**Comment by DanTup** [comment]
I can reproduce your issue with `child` in `showDialog` in Flutter `stable` channel, but not `master`. So I think this may be an issue that's already fixed.

The reason your `foo2` sample doesn't generate a warning is that it's a require parameter - deprecation warnings are not shown for required parameters as there's no way you can avoid calling them (arguably there should be a hint that you've deprecated a required parameter, although that's slightly different).

**Comment by kinex** [comment]
Ok. I don't want to switch to master channel right now, but I guess we can assume the fix will be available in the stable channel later. Thanks!
