### ISSUE TITLE
Issue completing static members

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#2982]
VsCode Info
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-56-generic

Dart Extension Version: 3.17.0

Observe the following code...

```
class TestClass2 {

}

enum TestEnum {

}

class TestClass {
  static Test
}
```

When typing "static Te...", no completion options are proposed.

Expected behaviour is take the class and enum starting with Test would be offered as suggestions.

**Comment by DanTup** [comment]
@bwilkerson I had a look at this and can repro like this:

```dart
class MyClass1 {}

class MyClass2 {
  static MyCl^
}
```

If I insert the word `final` after `static` then the type names show up.

The difference seems to be that the [`targetNode` here](https://github.com/dart-lang/sdk/blob/f1e8b702689cb40e4b98749b6602087db9ef76b1/pkg/analyzer_plugin/lib/src/utilities/completion/optype.dart#L95) is a `VariableDeclarationListImpl` in the case that works (it gets `includeTypeNameSuggestions` set to `true` [here](https://github.com/dart-lang/sdk/blob/f1e8b702689cb40e4b98749b6602087db9ef76b1/pkg/analyzer_plugin/lib/src/utilities/completion/optype.dart#L1328)) but it's a `FieldDeclarationImpl` in the case that doesn't (which skips setting `includeTypeNameSuggestions` [here](https://github.com/dart-lang/sdk/blob/f1e8b702689cb40e4b98749b6602087db9ef76b1/pkg/analyzer_plugin/lib/src/utilities/completion/optype.dart#L635) because the check `offset <= node.fields.offset` fails - the caret `offset` is `49` and `node.fields.offset` is `45`).

If I understand correctly, it may be interpreting `MyCl` as the field name and not a type? Although I'm not sure whether it's valid to just write `static foo` without a type (it seems to produce missing_const_final_var_or_type). Any ideas?

**Comment by bwilkerson** [comment]
Interesting. I suspect that it is related to recovery. I don't know what's going on specifically, but you might be right that the parser is inserting a synthetic `var` after `static` and taking `MyCl` to be the name of the field.

We should probably change the completion engine to set `includeTypeNameSuggestions` in cases where the `FieldDeclaration` has neither a type nor a keyword, but we'll want to ensure that this situation can only occur when there's an error in user code.

**Comment by DanTup** [comment]
@bwilkerson I think I have a fix here:

https://dart-review.googlesource.com/c/sdk/+/179771/

Although I'm not sure if there's anything specific needed for this:

> we'll want to ensure that this situation can only occur when there's an error in user code

There were some existing tests that cover some similar situations - for example [this test](https://github.com/dart-lang/sdk/blob/0fa6674ea94c26e5f4732a44e10e1374c2f795dd/pkg/analysis_server/test/services/completion/dart/imported_reference_contributor_test.dart#L1988-L1998) seems to ensure we don't suggest the type name when it's already there, and also goes through the `FieldDeclaration` path.

If you can think of anything that might be tripped up by this, let me know. I think all the tests pass, though when I try to run all of the tests I'm hitting a VM crash (I'll file a separate issue about that) so I'm not completely positive just yet.

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/d9012130611400d15cc0d9a10b9ab5fd0c638f5b. The change is in the analysis server so will show up in an SDK update rather than a Dart-Code update.
