### ISSUE TITLE
Code completion doesn't update during completion of arguments

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#299]
given a constructor `A(this.b)` where b is of type B, typing  `A(b:` via autocomplete currently gives something like `A(b: b` where the second b is highlighted. Would be nice for the autocomplete dropdown to still be open and show either
1. instances of B that are accessible in the current scope and
2. an autocompletable option to paste in `new B(...` directly (or list literals or wtv)

**Comment by DanTup** [comment]
I don't have much control over this (Dart Code doesn't parse Dart itself, it relies on the Dart Analyzer from the SDK) so I don't think *2* will be possible, but I would've expected *1* to already work. I'll dig into it when next working on this.

**Comment by DanTup** [comment]
Ok, I think *1* is a combination of two issues:

1. Completion items aren't sorted, so even when the correct list shows, `b` is way down the list. I've corrected this in #301
2. Code doesn't re-request completion when typing, so we don't update the list

I'll use this case for *2* since I think *2* in the original report is unfixable here and should be raised at https://github.com/dart-lang/sdk


## Repro

```dart
class B {}

class A {
  B b;
  A({this.b}) {}
}

main() {
  B c;
  var a = new A();
}
```

Put your cursor inside the call to `A`'s constructor and invoke completion. You'll see `b: ` but if you type those characters, you end up with no completion for the value like this:

![Bad completion](https://cloud.githubusercontent.com/assets/1078012/26219010/14650b74-3c05-11e7-9200-e0ab2649beaf.png)

If you hit `Escape` to close completion and re-invoke it with `Ctrl+Space` then you get sensible results:

![Good completion](https://cloud.githubusercontent.com/assets/1078012/26219032/2ccbc32e-3c05-11e7-837f-028b364b4d54.png)

Need to see if there's a way to cause Code to re-invoke completion, otherwise raise with Code team.

**Comment by DanTup** [comment]
Ok, this should work better now; the completion list will be refreshed when typing more characters (this includes `(` and spaces, so it'll trigger much more often and should be much more useful). It'll be in the next release.

However, there's still on minor issue which I've raised #302 for, which I suspect will either be a VS Code or Dart change. I'll do some testing and raise a request for whichever soon.

**Comment by DanTup** [comment]
@xster I've pushed a couple of changes out in 1.4. Please check if it seems better, though be aware #302 is not fixed yet.

**Comment by xster** [comment]
\o/
Trying it now
