### ISSUE TITLE
Reformat function call to one argument per line

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#300]
Consider function call:
```dart
new A(a: a, b: b, c: c, d: d);
```
offer a simple way to reformat it into
```dart
new A(
\ta: a,
\tb: b,
\tc: c,
\td: d,
);
```

**Comment by DanTup** [comment]
Unfortunately Dart Code doesn't directly parse Dart Code so in order to achieve this it would need to be implemented in the Dart Analyzer. You could raise this at https://github.com/dart-lang/sdk, but since the only formatting from the analyzer is the equivalent of `dartfmt` I'm not sure it's something they'd consider implementing.

I guess you already know that `Ctrl+Alt+F` will reformat, and may end up like this depending on the lengths of variables (though most likely, it'll just be an unreadable mess... I am not a big fan of `dartfmt` 😞).

**Comment by DanTup** [comment]
For some time now, the Dart formatter has placed arguments on individual lines if there is a trailing comma, see:

https://github.com/dart-lang/dart_style/commit/ad69e8a8a31776a33bbcb0cd9bb9c0afeeede09e
