### ISSUE TITLE
auto complete for annotations

### ISSUE THREAD

**Issue by KaungZawHtet** [Dart-Code/Dart-Code#3011]
It is better if there is auto completion for annotations such as `@required `

**Comment by DanTup** [comment]
In my testing, there is completion for annotations:

<img width="348" alt="Screenshot 2020-12-16 at 14 36 23" src="https://user-images.githubusercontent.com/1078012/102362273-1984f200-3fac-11eb-9400-ef238336e0ca.png">

Can you give a specific code example where this isn't showing up for you?

Could you also confirm your SDK version and whether you have the LSP Preview setting enabled? Thanks!

**Comment by KaungZawHtet** [comment]
It is shown when there is `import meta.dart` . Yes, in widgets class, the annotations are shown because flutter classes depends on `meta.dart` . My feature request is to display annotations by adding the line `import meta.dart` on plain dart classes.

**Comment by DanTup** [comment]
@KaungZawHtet that seems to work here too - and it auto-imports `meta`:

![Dec-16-2020 15-02-36](https://user-images.githubusercontent.com/1078012/102365732-c7de6680-3faf-11eb-823b-2b9466d0a6c0.gif)

Can you provide a concrete example of where this isn't working for you, and also confirm your SDK version and whether you have the LSP Preview setting enabled? Thanks!

**Comment by KaungZawHtet** [comment]
<img width="712" alt="Screen Shot 2020-12-16 at 21 38 07" src="https://user-images.githubusercontent.com/15225530/102366423-05aab180-3fe7-11eb-9c20-167b92f501fb.png">
It is shown now but one thing there should be `import 'meta.dart'` but not. It depends on the rest: `import flutter/material.dart, widget.dart, foundation.dart, cupertino.dart`.

SDK is 
```
Flutter 1.24.0-10.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 022b333a08 (4 weeks ago) • 2020-11-18 11:35:09 -0800
Engine • revision 07c1eed46b
Tools • Dart 2.12.0 (build 2.12.0-29.10.beta)
```

**Comment by DanTup** [comment]
Can you try the following:

- Type `@req` in the right position in the editor
- Run the **Dart: Capture Analysis Server Logs** command
- Press Cmd+Space to trigger completion, then select `required` and press `<enter>`
- Click **Cancel** on the logging notification to stop logging and open the log file

Make sure there's nothing sensitive in the log file (it may contain parts of your open source files) and attach the log of paste into a [gist](https://gist.github.com/) and provide the link here. Thanks!

**Comment by KaungZawHtet** [comment]
gist done

**Comment by KaungZawHtet** [comment]
[gist](https://gist.github.com/KaungZawHtet/121da2f8742089134bf4fa49ac167716) done

**Comment by DanTup** [comment]
@KaungZawHtet Just to confirm - is the issue that it's not inserting the `import` statement, or that the `auto-import` does not show up for `package:meta`?

If the issue is that it just doesn't show up for `meta`, then you may need to add `meta` to your `dependencies` in `pubspec.yaml`. Transient dependencies won't be auto-imported, you need an explicit dependency to use them.

If that's not the issue, and it's not adding the imports that it shows in the text, are you able to zip up your whole project and provide it so I can try to repro with the exact same code? It may also be worth enabling the "Preview LSP" setting and restarting to VS Code and seeing if that makes any difference. Thanks!

**Comment by KaungZawHtet** [comment]
Yes, as you said, it's because of meta package dependency. If you don't see much deal on feature request, this can be closed now

**Comment by DanTup** [comment]
It's by design that annotations from packages not listed in `dependencies` don't show up.

Automatically adding the package to `pubspec.yaml` would be an option, but really that would mean listing all symbols from transient dependencies in the code completion and I generally think that would be a bad idea (the list is already very long with just symbols from direct dependencies). Hope this makes sense!
