### ISSUE TITLE
dart.updateImportsOnRename does not work with vscode 1.52 and dart-code v3.18.1

### ISSUE THREAD

**Issue by iulian0512** [Dart-Code/Dart-Code#3083]
I created the dart project using dart stagehand.

![vscode](https://user-images.githubusercontent.com/16035099/105185916-cae1ef00-5b39-11eb-86ad-f5d52d463b92.gif)

**Comment by DanTup** [comment]
@iulian0512 can you confirm if you have the LSP Preview turned on? You can find out by hovering over the Dart version number in the status bar and seeing whether it says "DAS" or "LSP". Can you also confirm the exact version number of Dart/Flutter shown in the status bar? Thanks!

<img width="342" alt="Screenshot 2021-01-20 at 14 22 03" src="https://user-images.githubusercontent.com/1078012/105187623-e5609c00-5b2a-11eb-9d36-3d83261457ed.png">

**Comment by iulian0512** [comment]
flutter (LSP)1.22.5
![image](https://user-images.githubusercontent.com/16035099/105189383-95d79b80-5b3d-11eb-9d18-837b6aef8a02.png)

**Comment by DanTup** [comment]
Got it - in that case this is the same as #2761. The version of Dart that's in the current stable Flutter does not include the support for this, and the live version of Dart-Code also does not support LSP 3.16 (which contains the required APIs for this).

So in order to get this in LSP you'll need both v3.19 of Dart-Code (not yet released) and the next stable version of the Flutter SDK.

If you really need this feature in the short-term, you can disable the LSP Preview in your VS Code user settings (although in future the LSP version will become the default and only option). Hope this helps!
