### ISSUE TITLE
Import quick fixes should be inserted below @TestOn

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3104]
Quick fixes for imports are inserting the code at the wrong place. 

Consider this example:

```dart
@TestOn('windows')

import 'package:test/test.dart';
import 'package:win32/win32.dart';

void main() {
  test('Allocate Bluetooth PIN', () {
    final pin = calloc<BLUETOOTH_PIN_INFO>();
    pin.ref.pin = Uint8List.fromList([1, 2, 5, 0]);
    pin.ref.pinLength = 4;
    expect(pin.ref.pin.sublist(0, 4), equals(Uint8List.fromList([1, 2, 5, 0])));
    expect(pin.ref.pinLength, equals(4));
  });
}
```

Note that `Uint8List` has a squiggly under it, representing that it is not understood. If I hit Ctrl+. DartCode offers me the library import I need:
![image](https://user-images.githubusercontent.com/2319867/105932566-e51c4100-6001-11eb-954d-fec817f9f960.png)

If I accept that recommendation, it inserts the new import at the top of the file: 
```dart
import 'dart:typed_data';

@TestOn('windows')

import 'package:test/test.dart';
import 'package:win32/win32.dart';
```

However, the `@TestOn` platform selector [**only works if it is the first thing in the file**](https://pub.dev/packages/test#restricting-tests-to-certain-platforms):

> Just put it at the top of your file, before any library or import declarations

Unfortunately, this issue is quite insidious, because you only notice it if you happen to run the test on a platform that doesn't support it. Not sure where the fix is, but figured DartCode was a good place to start! 

## Dart Version
```
Dart SDK version: 2.12.0-262.0.dev (dev) (Tue Jan 26 06:57:59 2021 -0800) on "windows_x64"
```

Dart Code extension is 3.18.1.

**Comment by DanTup** [comment]
@bwilkerson my guess is that this is because the annotation is attached to the first `import` and this new `import` needs to go before it. The same issue occurs if you put the new import second, then run "Organize Imports".

Would the correct fix be to use the presence of a blank line between the annotation and import keyword as an indicator to insert directly before the import keyword instead of the whole node? I suspect it'd need doing in both the import sorter and the edit builder (used for fixes).

The import sorter already has some special handling for comments (the first comment in the file is considered a library comment even if attached to an import and remains at the top - it doesn't require a blank line), although the edit builder doesn't seem to do the same so fix-inserted imports will still go above those.

**Comment by bwilkerson** [comment]
I'm sure you're right. The annotations are children of the directives in the AST structure, so the offset of the directive is the offset of the left-most annotation or documentation comment. The blank line doesn't prevent the `TestOn` annotation from being associated with the following directive or declaration.

I don't know whether a blank line between them is a common style to indicate that the annotation is for the file rather than the directive / declaration. I do expect that it's uncommon to have a blank line after annotations when they are intended to be associated. I _can_ tell you that `dartfmt` respects this convention (it will leave a blank line between an annotation and the first directive, but will remove the blank line for any other than the first directive, including between the annotation and the first declaration). So it seems reasonable to me that analyzer also respect the convention.

**Comment by DanTup** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/a6c14e8848ab1d750fcb9c0e260d391815b5b52a. Since the fix is in the server, it'll show up with an SDK update rather than Dart-Code update.
