### ISSUE TITLE
Autocomplete issue on LSP/DAS

### ISSUE THREAD

**Issue by iulian0512** [Dart-Code/Dart-Code#3114]
**Describe the bug**
Autocomplete issue, does not complete a class and its methods.

**To Reproduce**
The complete source code in the example can be found here: https://github.com/rekab-app/background_locator (open the example folder with vscode).

**Expected behavior**
Autocomplete should complete a class from an imported package.

**Screenshots**

![480p](https://user-images.githubusercontent.com/16035099/106484902-bcd88a80-64b8-11eb-86f0-1931f41779df.gif)

**Versions (please complete the following information):**
 - VS Code version:1.52.1
 - Dart extension version: 3.19.1
 - Dart/Flutter SDK version: Fluttter 12.22.6 LSP

**Comment by DanTup** [comment]
Are you reproduce this in a small project that you can share?

**Comment by iulian0512** [comment]
yes full source code is available at https://github.com/rekab-app/background_locator  open the example folder then open example/lib/main.dart go to line 79 and try to autocomplete BackgroundLocator.  i cannot reproduce the issue elsewhere, i tried creating a small proj then referencing background_locator from pub.dev.

**Comment by DanTup** [comment]
Ah sorry, I missed that in the original issue.

I can reproduce the issue. It's because you've listed the dependency under `dev_dependencies` in your Example's pubspec:

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter

  background_locator:
    path: ../
```

`dev_dependencies` are not intended to be used in your code, so the code completion will not suggest types from them. It should probably generate warnings for your use of the class in that file - there's a related open issue at https://github.com/dart-lang/sdk/issues/42873.

In the meantime, you should move the dependency to `dependencies` though, as it's a runtime requirement of the app.

Hope this makes sense!

**Comment by iulian0512** [comment]
thanks so much for the detailed explanation.

**Comment by DanTup** [comment]
No problem, glad it was an easy fix!
