### ISSUE TITLE
Refactor menu not showing

### ISSUE THREAD

**Issue by kashishkhullar** [Dart-Code/Dart-Code#3121]
**Describe the bug**

The refactor menu button after right clicking on a widget is not visible since I have upgraded to flutter 1.22.4. I also updated the dart version.

**To Reproduce**

1. Right clicked on a widget

**Expected behavior**

Refactor widget option in the opened menu.

 
**Screenshots**

![image](https://user-images.githubusercontent.com/22838528/106883488-09fd6c00-6706-11eb-8b83-a9892ee3e4a4.png)

**Versions (please complete the following information):**
 - VS Code version: 1.52.0
 - Dart extension version: v3.19.1
 - Flutter extension version: v3.19.0
 - Dart/Flutter SDK version: v 1.22.6

**Comment by DanTup** [comment]
This issue likely occurred if you recently enabled the LSP Preview rather than the Flutter upgrade. There's an original issue at https://github.com/Dart-Code/Dart-Code/issues/2885.

It's been fixed in the SDK, but won't show up until the next stable release. In the meantime, you could either disable the LSP preview or use the Lightbulb (`Ctrl+.`) menu to access the refactors.

Sorry for the inconvenience!
