### ISSUE TITLE
Test tree doesn't update to reflect renamed test

### ISSUE THREAD

**Issue by haashem** [Dart-Code/Dart-Code#3129]
**Describe the bug**
Rename any of your tests, then run that individual test or their parent test group by clicking on run button, you will see the Test tree add another test node with updated name!
but if you click run above the main function, test tree gets refreshed!

**To Reproduce**
so if you have one test,  rename and run that test by clicking run above the test method, you will see now you have two test nodes!

**Expected behavior**
Test tree should reflect test name changes without adding updated test node.

**Screenshots**
<img width="518" alt="Screen Shot 2021-02-08 at 15 43 22" src="https://user-images.githubusercontent.com/3206748/107215191-6c1ae180-6a24-11eb-8db0-bcb37ab1ebda.png">

**Versions (please complete the following information):**
 - VS Code version: 1.53.0
 - Dart extension version: 3.19.2
 - Dart/Flutter SDK version:1.25.0-8.3.pre

**Comment by DanTup** [comment]
This is expected (although not ideal) behaviour. When you run a subset of tests, we don't know whether the "old" tests have been removed, or just aren't included in that test run (since we mostly just collect the results from running `package:test` and don't try to track the tests during editing).

Tests nodes with a faded icon are considered "stale" which means they weren't in the last test run and could be incorrect or even no longer exist. When you re-run an _entire file_ we will clear out the stale test nodes at the end, since it's clear they no longer exist.

So, you should run the whole file when you want to remove any stale tests. If in future there's a reliable way we could detect removed tests without running them all, I'd love to improve this. Hope this makes sense!
