### ISSUE TITLE
Expose Dart's "why not promoted" information in VS Code

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#3136]
As of https://github.com/dart-lang/sdk/commit/a42244f73b27256eca44def4daa552e91c2dbc55, the analyzer now generates context messages in some circumstances explaining why type promotion failed. We would like these messages to show up in VS Code in a way that's easily discoverable.

See also https://github.com/dart-lang/sdk/issues/44897.

(Danny, I'll give you some context on this when we sync up next)

**Comment by devoncarew** [comment]
Ah, this work might already have been done?

<img width="1037" alt="Screen Shot 2021-02-09 at 4 49 59 PM" src="https://user-images.githubusercontent.com/1269969/107448660-f5024d80-6af6-11eb-9ead-5a98ede38ea3.png">

@DanTup, I'll close this issue (but please re-open if you think there's something to do here).

**Comment by DanTup** [comment]
If the info is in the `correction` or `contextMessages` then yep, it shows up here. The `correction` is appended to the main message, and the context messages are `relatedInformation`.

Non-LSP:
https://github.com/Dart-Code/Dart-Code/blob/6966fba1175d7dfc0bd11a208d16faadacc956e8/src/extension/providers/dart_diagnostic_provider.ts#L52-L55

LSP:
https://github.com/dart-lang/sdk/blob/f306f4c4d41c8f2af2a3f3f30880703d43a8c5af/pkg/analysis_server/lib/src/lsp/mapping.dart#L935-L945

I'm not totally familiar with the "why not promoted" info (your screenshot doesn't look like it's that?) but if there's an example I can use to trigger it I can test in both LSP/non-LSP.

**Comment by stereotype441** [comment]
@DanTup 
> I'm not totally familiar with the "why not promoted" info (your screenshot doesn't look like it's that?) but if there's an example I can use to trigger it I can test in both LSP/non-LSP.

You should be able to test using this example (it works with the command-line analyzer as of https://github.com/dart-lang/sdk/commit/a42244f73b27256eca44def4daa552e91c2dbc55):
```dart
f(int? i, int? j) {
  if (i == null) return; // (1)
  i = j;                 // (2)
  i.isEven;              // (3)
}
```
On the line marked (3) there should be an error message saying `The property 'isEven' can't be unconditionally accessed because the receiver can be 'null'.`  There should be an associated context message for the line marked (2) saying `Variable 'i' could be null due to a write occurring here.`

Two minor notes:
- We're contemplating changing the context message to just `Variable 'i' could be null due to a write.` (rationale [here](https://github.com/dart-lang/sdk/issues/44904#issuecomment-776286501))
- In the future we may also add a context message for the line marked (1) to tell the user the location of the promotion that failed (see https://github.com/dart-lang/sdk/issues/44899)

**Comment by DanTup** [comment]
@stereotype441 thanks! In that case, it appears to be working as expected (both under LSP and the original protocol):

<img width="995" alt="Screenshot 2021-02-10 at 15 40 11" src="https://user-images.githubusercontent.com/1078012/107532923-4a516400-6bb6-11eb-8818-10e8af7f4b4b.png">

Clicking on the main error (`"The property 'isEven'"`) navigates to line `(3)` were the red squiggle is, and clicking the nested message `"Variable 'i' could be null..."` navigates to line `(2)`.

**Comment by stereotype441** [comment]
@DanTup Great!  Thanks for checking.
