### ISSUE TITLE
Repeated test runs leave old results in terminal

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#3137]
**Is your feature request related to a problem? Please describe.**
When debugging using a test, I tend to run it repeatedly. The test's results appear in the terminal, but I've discovered that the terminal is reused between test runs, and the results of multiple test runs accumulate.

This can be time consuming, as I first have to determine what it is I'm looking at, then find the piece of information I need to continue debugging. I've even made mistakes with it.

**Describe the solution you'd like**
I'd love if the terminal could be cleared out between runs, or at the very least, a separator could be drawn between the runs.

Alternatively, I seem to recall that the Debug Console was used previously to display test failures, and I don't recall having this issue then. Why the change?

**Describe alternatives you've considered**
I have been killing terminals between test runs, but it's just one more thing I have to remember to do.

**Additional context**
I'm on macOS, Dart Code v3.19.2

--------

If you agree that this is an issue, I'd be interested in contributing.

**Comment by DanTup** [comment]
> Alternatively, I seem to recall that the Debug Console was used previously to display test failures, and I don't recall having this issue then. Why the change?

Are you able to show a screenshot of exactly what you're seeing? The Debug Console should still be used for debug sessions (unless you've explicitly set it to terminal in your launch config).

However, clicking on a test node in the tree to see the _historical_ results of just that test will use the terminal, and this was done so that stack traces (etc.) can be clickable links, which was not possible in the Output pane that was used before (it was Output and not the Debug Console - we can't write to the debug console except from a debug adapter). When I tested this, it does create a clean session and only include the output from the test for the last run though.

**Comment by shyndman** [comment]
> However, clicking on a test node in the tree to see the historical results of just that test will use the terminal, and this was done so that stack traces (etc.) can be clickable links, which was not possible in the Output pane that was used before (it was Output and not the Debug Console - we can't write to the debug console except from a debug adapter). When I tested this, it does create a clean session and only include the output from the test for the last run though.

Ahh, I see. This may be what's happening. Let me play around a bit more and I'll post back.

**Comment by shyndman** [comment]
You are correct. Not sure what put me into that particular flow. Thank you @DanTup.

**Comment by DanTup** [comment]
Even if you are looking at the "historical" results in the fake Terminal, you should only see one. If you're seeing repeated (or otherwise incorrect) output there, please let me know as that will need fixing. Thanks!
