### ISSUE TITLE
Hot reload not working in vs code

### ISSUE THREAD

**Issue by Shreemanarjun** [Dart-Code/Dart-Code#3140]
On latest flutter beta ,automatic save and hot reload not working on latest vs code.

![image](https://user-images.githubusercontent.com/24736211/107703043-1f176380-6ce1-11eb-8cd3-36afbafa12f4.png)

**Comment by DanTup** [comment]
Sorry for the inconvenience. That behaviour was never intended and was "fixed" as a bug in the last release. However, it turned out that it worked well for some people, so it will be restored as an option in the next version. See [this pinned issue](https://github.com/Dart-Code/Dart-Code/issues/3110) for more details. Thanks!
