### ISSUE TITLE
Automatic import suddenly stops working in vs code

### ISSUE THREAD

**Issue by baku-apps** [Dart-Code/Dart-Code#3163]
**Describe the bug**
Automatic import is will suddenly stop working when running the app. Restarting the Dart analyzer helps, but that will break the hot reload. Restarting whole of vs code works temporarily until the import feature breaks again.

It seems to me the dart analyzer is breaking (had also hot reloading and auto complete issue with flutter 1.22.3.

**Screenshots**
when running the flutter app:
![image](https://user-images.githubusercontent.com/51446562/109066102-d7370a00-76ec-11eb-86f0-8140b83f2904.png)

after stopping the app and restarted the dart analyzer
![image](https://user-images.githubusercontent.com/51446562/109066233-11a0a700-76ed-11eb-9dfa-47f8d8898c75.png)

**To Reproduce**
1. Type StreamController
2. hit ctrl+. 
3. dont' see the 'import dart:async' option in the refactor menu in vs code

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.52.2
 - Dart extension version:  2.10.5
 - Dart/Flutter SDK version: 1.22.6

**Comment by baku-apps** [comment]
flutter doctor -v output:

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale en-GB)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\bart_\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\bart_\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\bart_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • Nexus 6 (mobile) • ZX1G325TXF • android-arm • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.
```

**Comment by baku-apps** [comment]
I have the previewLSP disabled (enabling the previeLSP makes sure that code completion does not work anymore). I'm kind of having problems keeping up my productivity with flutter lately.

**Comment by DanTup** [comment]
> Automatic import is will suddenly stop working when running the app.

I don't supposed you've noticed any pattern to this? If you add the import manually, does the red squiggle under the class name disappear, or remain? (If it remains, it sounds like the state of the analyzer might be out of sync). Is the class/file something you've recently created when you see this?

> I have the previewLSP disabled (enabling the previeLSP makes sure that code completion does not work anymore).

Is there any issue open about the completion not working correctly? LSP is going to become default soon (and eventually the only option), so if there are unresolved bugs in it they need to be fixed. There have been some improvements made since the last Flutter release though, so it's possible if you try out the beta branch things may be improved.

> I'm kind of having problems keeping up my productivity with flutter lately.

I'm sorry to hear that. I'd very much like to get to the bottom of any of these issues, so the more information you can give that might help me track down (or reproduce here) would be very much appreciated!

**Comment by baku-apps** [comment]
> I don't supposed you've noticed any pattern to this? If you add the import manually, does the red squiggle under the class name disappear, or remain? (If it remains, it sounds like the state of the analyzer might be out of sync). Is the class/file something you've recently created when you see this?

I don't see a pattern, an manually importing works just fine.

> Is there any issue open about the completion not working correctly? LSP is going to become default soon (and eventually the only option), so if there are unresolved bugs in it they need to be fixed. There have been some improvements made since the 
last Flutter release though, so it's possible if you try out the beta branch things may be improved.

I will try the beta branch and let you know the result.

> I'm sorry to hear that. I'd very much like to get to the bottom of any of these issues, so the more information you can give that might help me track down (or reproduce here) would be very much appreciated!

Sorry for the rant. Been a bit frustrating working with the Dart-Code lately.

**Comment by baku-apps** [comment]
in debug channel I get the following error:

```
/flutter/.pub-cache/hosted/pub.dartlang.org/load-0.1.6/lib/src/theme.dart:16:17: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        context.inheritFromWidgetOfExactType(LoadingTheme);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.1/lib/src/picture_provider.dart:52:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^

FAILURE: Build failed with an exception.
```

**Comment by baku-apps** [comment]
If I downgrade to version 1.22.3 I don't have this issue. However, with 1.22.3 i have the following issue https://github.com/Dart-Code/Dart-Code/issues/2990#event-4251348885

**Comment by DanTup** [comment]
> in debug channel I get the following error:
> 
> The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.

It looks like this may be coming from the [load package](https://pub.dev/packages/load), which is calling [a method that was deprecated](https://api.flutter.dev/flutter/widgets/BuildContext/inheritFromWidgetOfExactType.html). It doesn't look like that package has been updated in a while, so that might be something you'll need to resolve at some point in order to move to newer Flutter SDKs.

The second issue (relating to `nullOk` in `flutter_svg`) appears to be null-safe related. That parameter is removed from the latest versions of Flutter, so when using them you'd likely need to upgrade `fluter_svg` to a new version too.

Both of these changes are probably not backwards-compatible, so you might want to make them on a temporary branch or something if trying out a non-stable Flutter build. Otherwise you could wait for the next stable Flutter release (at which point you'll need to fix them to upgrade anyway).

Given that LSP is going to become default soon, I think rather than trying to track down the non-LSP issue, it would be better to enable LSP and focus on the issues you have when using that (which sound completion-related).

I would recommend using 1.22.6 instead of 1.22.3 while you remain on the stable release, as it has fixes for the issue you linked above.
