### ISSUE TITLE
Analyzer frozen on plugin projects that use all 6 platforms

### ISSUE THREAD

**Issue by jifalops** [Dart-Code/Dart-Code#3165]
**Describe the bug**
The analyzer hangs up when saving a file, ctrl+click, never catches misspelled references, etc. after opening a plugin project created with the following command:

```sh
flutter create --org my.org --template=plugin --platforms=android,ios,web,linux,macos,windows flutter_platforms_test
```

**To Reproduce**
1.

    
    flutter channel dev
    flutter upgrade
    flutter config --enable-windows-desktop
    flutter config --enable-macos-desktop
    flutter config --enable-linux-desktop
    flutter create --org my.org --template=plugin --platforms=android,ios,web,linux,macos,windows flutter_platforms_test
    

2. Open the project in VS code and the analyzer should fail in the ways described above.

**Versions (please complete the following information):**
 - VS Code version: `1.53.2`, also checked with the previous release (1.52).
 - Dart extension version: `3.19.2`, but I also checked with the last `2.x.0`
 - Dart/Flutter SDK version:  
    ```
    Flutter 1.27.0-8.0.pre • channel dev • https://github.com/flutter/flutter.git
    Framework • revision b7d4806243 (6 days ago) • 2021-02-19 09:22:45 -0800
    Engine • revision 6993cb229b
    Tools • Dart 2.13.0 (build 2.13.0-30.0.dev)
   ```
I'm on Ubuntu 20.04. If you keep the project open and edit files, `dart` processes will build up and slowly overtake the CPU.

**Comment by jifalops** [comment]
Should this be on the sdk repo?

**Comment by DanTup** [comment]
This seems to be caused by symlinks that point back up the tree:

```
49873423        0 lrwxr-xr-x    1 danny            wheel                  36  1 Mar 10:58 ./example/linux/flutter/ephemeral/.plugin_symlinks/flutter_platforms_test -> /private/tmp/flutter_platforms_test/
49873420        0 lrwxr-xr-x    1 danny            wheel                  36  1 Mar 10:58 ./example/windows/flutter/ephemeral/.plugin_symlinks/flutter_platforms_test -> /private/tmp/flutter_platforms_test/
```

@devoncarew @bwilkerson I think this came up before, but the circular symlinks were caused by some third party tool (I think a nodejs project inside the same folder with a package manager that was using symlinks).

This one happens entirely using Flutter commands. I'm not sure whether Flutter shouldn't be created these circular symlinks, or whether the analyzer should be able to handle them (or what "handling them" looks like - if they're skipped that means it wouldn't be possible to import code from within them - although that's probably not a concern here).

Perhaps skipping any `.plugin_symlinks` folder is an option, though I don't know if it'd come back with another folder in future. Any thoughts?

**Comment by bwilkerson** [comment]
@schglov recently made some changes to improve the way symlinks are handled. It's my understanding that this work impacted both the analysis server and the `dart analyze` and `flutter analyze` commands, and that his next arc of work will apply the changes to the `dartanalyzer` command. Is this reproducible on master?

**Comment by devoncarew** [comment]
> This one happens entirely using Flutter commands.

Circular symlinks are generally not a good idea. We had been creating them in Dart very early on but moved away from that. Do you know where in the flutter ecosystem we're creating them? We likely want to reconsider that.

**Comment by DanTup** [comment]
> Is this reproducible on master?

Ah, I actually can't reproduce this on master. @jifalops can you check it also seems fixed for you there?

> Do you know where in the flutter ecosystem we're creating them? We likely want to reconsider that.

I think it's [around here](https://github.com/flutter/flutter/blob/354bd53f62ed6dd31c9addc4cce521f412c6b1aa/packages/flutter_tools/lib/src/plugins.dart#L1361). Specifically, in the repro above it's the `example` project linking back to the real project. I'm not familiar enough to understand if there's another way or not though (although if the server handles these better now, it might be less important).

**Comment by jifalops** [comment]
It doesn't happen on master. In fact just switching to master fixes it without regenerating any project files. Here's the version just in case:

```sh
Flutter 1.27.0-9.0.pre.147 • channel master • https://github.com/flutter/flutter.git
Framework • revision fc99e7c0d7 (46 minutes ago) • 2021-03-01 18:30:17 -0800
Engine • revision 17f6bfc480
Tools • Dart 2.13.0 (build 2.13.0-90.0.dev)
```

**Comment by DanTup** [comment]
> It doesn't happen on master. In fact just switching to master fixes it without regenerating any project files.

I think that's expected given the changes were in the analysis server (presumably to not walk down the symlinks), rather than removing the symlinks.

So I believe this is fixed and there's nothing to do here (although it'll take a little time to propagate through all of Flutter's channels). If you do see the issue again on a version newer than the current master, feel free to re-open for investigation. Thanks!
