### ISSUE TITLE
Syntax highlighting broken with LSP

### ISSUE THREAD

**Issue by grouma** [Dart-Code/Dart-Code#3168]
I use the VIM plugin which has a known performance [issue](https://github.com/Dart-Code/Dart-Code/issues/1800) with dart-code. The suggested solution is to enable the LSP feature. Doing so solves most of my performance issues but it breaks syntax highlighting. See this screenshot:

<img width="1068" alt="Screen Shot 2021-02-26 at 3 13 06 PM" src="https://user-images.githubusercontent.com/1840773/109365303-b59d6600-7845-11eb-907f-533a7686edd7.png">

Notice that most everything is blue. Analysis and errors works as expected.

Environment:
VS Code: `1.53.1`
Dart plugin:  `3.19.2`
Flutter plugin:  `3.19.0` 
Flutter SDK: `1.27.0-5.0.pre.116`

**Comment by DanTup** [comment]
> Doing so solves most of my performance issues but it breaks syntax highlighting

I think this is working as expected. Before Semantic Tokens, a lot of things were left uncoloured and appeared white. With Semantic Tokens, many of these things (like variables) are now coloured according to the theme (if you open another language that supports semantic tokens like TypeScript, you'll see a sea of blue there too).

There's some info about the semantic tokens update here:

https://dartcode.org/releases/v3-19/#lsp-semantic-tokens

If you preferred things white however, you could override the theme to also show variables in white like this in your VS Code user settings:

```js
"editor.tokenColorCustomizations": {
	"[Default Dark+]": {
		"variables": "#d4d4d4",
	}
}
```

Let me know if you think there's still something not right though. Thanks!

**Comment by grouma** [comment]
Thanks for the details. That does seem like my issue. Also thanks for the override tip as I think white on a dark background is easier to read.

**Comment by robertpiosik** [comment]
I also cannot work with a theme so uniformly colored and I don't see how it creates any value to a user, to say it's an intended behavior of LSP.

For sure Typescript isn't this much blue and looks rather like when you have LSP disabled. 

Some custom themes; say "super one dark" aren't affected by enabling LSP and in my opinion, the default theme shouldn't be neither. 

Thanks for looking into it.

**Comment by DanTup** [comment]
@robertpiosik the colours are provided by the theme, the extension only attaches semantic tokens to them. You didn't include the TypeScript example you're using, but here's the first TS file I had open in the Dart-Code repo and it looks the same to me - all the variables are blue and there's hardly any white:

<img width="878" alt="Screenshot 2021-06-01 at 10 43 51" src="https://user-images.githubusercontent.com/1078012/120303196-8247f880-c2c6-11eb-8dae-1a73b24d3930.png">

This is how the theme colours variables. It's certainly different to what Dart did before, but that was just because it was not applying all of the tokens and therefore wasn't applying the theme correctly.

If you have some specific examples of where you think Dart is attaching the wrong semantic tokens (you can see the tokens using the **Inspect Editor Tokens and Scopes** command) I can take a look - but it doesn't make sense to change the tokens to try and change the colours - themes handle the colours and if we associated the wrong tokens, themes will not be able to colour things correctly. If the issue is only that you don't like some colours in your theme, there's an example above of how to override them.

Hope this makes sense!

**Comment by robertpiosik** [comment]
Oh, I apologise, you're totally right.

Although I found something to bring up here. Factory method's default yellowish colour is somewhat lost with LSP and I'm not sure it's all good.

LSP:
![image](https://user-images.githubusercontent.com/7120725/120309144-3486bc80-c2d5-11eb-8cd2-bd3124acd55d.png)
Without LSP:
![image](https://user-images.githubusercontent.com/7120725/120309261-541de500-c2d5-11eb-9fc1-af33a8c691b3.png)

With LSP:
![image](https://user-images.githubusercontent.com/7120725/120309458-8cbdbe80-c2d5-11eb-843b-fa6327cc9747.png)
Without LSP:
![image](https://user-images.githubusercontent.com/7120725/120309500-97785380-c2d5-11eb-883b-bb5e5451dd5f.png)

Once more, apologise for wasting your time with these variables.

**Comment by robertpiosik** [comment]
```dart
@injectable
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final IAuthFacade _authFacade;

  AuthBloc(
    this._authFacade,
  ) : super(const AuthState.initial());

  @override
  Stream<AuthState> mapEventToState(
    AuthEvent event,
  ) async* {
    yield* event.map(
      authCheckRequested: (e) async* {
        final userOption = _authFacade.getSignedUser();
        yield userOption.fold(
          () => const AuthState.unauthenticated(),
          (_) => const AuthState.authenticated(),
        );
      },
      signedOut: (e) async* {
        await _authFacade.signOut();
        yield const AuthState.unauthenticated();
      },
    );
  }
}
```

**Comment by robertpiosik** [comment]
Here is how GitHub colours tokens:

```dart
@injectable
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final IAuthFacade _authFacade;

  AuthBloc(
    this._authFacade,
  ) : super(const AuthState.initial());

  @override
  Stream<AuthState> mapEventToState(
    AuthEvent event,
  ) async* {
    yield* event.map(
      authCheckRequested: (e) async* {
        final userOption = _authFacade.getSignedUser();
        yield userOption.fold(
          () => const AuthState.unauthenticated(),
          (_) => const AuthState.authenticated(),
        );
      },
      signedOut: (e) async* {
        await _authFacade.signOut();
        yield const AuthState.unauthenticated();
      },
    );
  }
}
```
It looks less broken imho.

**Comment by DanTup** [comment]
@robertpiosik yeah, that one does seem questionable. Would you mind filing a specific issue for that and I'll have a look. Thanks!

**Comment by robertpiosik** [comment]
@DanTup Sure, will do.
