### ISSUE TITLE
Intellisense for nullable types does not display the null postfix operator

### ISSUE THREAD

**Issue by acoutts** [Dart-Code/Dart-Code#3174]
**Describe the bug**
While working in a null safe dart project, if you start to type out a member from a class like `fooClass.`, the intellisense popup does not display the null postfix operator:
<img width="621" alt="Screen Shot 2021-03-03 at 7 13 09 AM" src="https://user-images.githubusercontent.com/9597207/109804364-28b12e80-7bf0-11eb-8842-a610a558dbd6.png">
Notice the type is `LiveForexQuote`.

But hovering over the member, then the correct type (nullable) is shown:
<img width="553" alt="Screen Shot 2021-03-03 at 7 13 30 AM" src="https://user-images.githubusercontent.com/9597207/109804447-3ff01c00-7bf0-11eb-8ece-303fd9ab0439.png">

**To Reproduce**
1. Create a nullable variable in a class
2. Start typing to dereference that nullable class member
3. Intellisense won't show the null postfix operator.

**Expected behavior**
Should show the null postfix operator like when you hover over it after typing it in.

**Versions (please complete the following information):**
```
Version: 1.53.0-exploration
Commit: 0c9e2dadd986d0bc085f1c5352245531eef65e84
Date: 2021-01-07T06:28:46.730Z (1 mo ago)
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin arm64 20.2.0
```
```
Dart code: 3.20.0
```

**Comment by DanTup** [comment]
@bwilkerson this appears to be because `DartType.getDisplayString` calls that assume non-null here:

https://github.com/dart-lang/sdk/blob/b10a592341bec4a00379d5c674a417b6b8c781a6/pkg/analysis_server/lib/src/protocol_server.dart#L57-L75

If I change them to something like:

```dart
final withNullability = element.returnType.element?.declaration?.library?.isNonNullableByDefault ?? false;
return element.returnType.getDisplayString(withNullability: withNullability);
```

It seems to handle this, but it leaves me with some questions:

1. Which library should be used to determine whether to show it (here I'm using the library that declares the return type - I don't know if that's correct (I think [hovers](https://github.com/dart-lang/sdk/blob/b10a592341bec4a00379d5c674a417b6b8c781a6/pkg/analysis_server/lib/src/computer/computer_hover.dart#L26) might be always using the source library?)
2. If the library declaring the type works, could it be handled inside `getDisplayString` since it can access `element?.declaration?.library?.isNonNullableByDefault` directly?

**Comment by bwilkerson** [comment]
> Which library should be used to determine whether to show it ...

Good question. I'm not sure what users want to see, but we've been using the principle that we should show the type that something has in the location at which it is referenced. If a top-level variable `int? x;` is declared in an opted in library, but is referenced from an opted out library, then we don't show the nullability marker. This matches what the spec says, and in the absence of evidence that that's wrong, it seems like a reasonable default.

**Comment by DanTup** [comment]
Sounds good to me - I've opened https://dart-review.googlesource.com/c/sdk/+/197042/.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/115a758d87648e0dab51727af883e7e1fb4b2ba0.
