### ISSUE TITLE
Image.network fails in VSCode debug, works with flutter run --debug

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#3176]
I'm cross-posting this here because it looks like a Dart-Code bug, not a flutter/flutter bug.

https://github.com/flutter/flutter/issues/73109

Possibly related to https://github.com/Dart-Code/Dart-Code/issues/3072 since it is divergent behavior based on running with VSCode debug or `flutter run --debug`

I do not have a reproduction available, unfortunately.

**Comment by DanTup** [comment]
I don't think this is a Dart-Code issue, but I'm happy to try and help debug.

On the surface this sounds a lot like https://github.com/flutter/flutter/issues/73327. This is a CORS issue that's dependant on the web rendered being used. VS Code passes `--web-renderer=auto`, which may be different to when you're running from the command line (see https://github.com/flutter/flutter/issues/73327#issuecomment-764908135).

**Comment by lukepighetti** [comment]
I have no skin in the game on that issue, but it's the second time I've seen an issue that is based on running with VSCode debug or not.

**Comment by DanTup** [comment]
The [comment here](https://github.com/flutter/flutter/issues/73327#issuecomment-764908135) confirmed that a user that saw this issue only from VS Code was able to repro from the CLI when passing `--web-renderer=auto` too, so I'm fairly sure this is the same issue. There's not really much else in Dart-Code that could change the behaviour of things running in the browser (it has no involvement in compilation or execution).

If anyone can repro this problem, and confirm it doesn't also happen from the CLI with `--web-renderer=auto` (or that it happens in VS Code if the renderer is set to HTML) we can re-open this and debug (I'll also keep an eye on any responses to my comment on the original issue you linked). Otherwise, I don't think there's anything actionable here. Fetching images from scripts will be subject to CORS rules and I'm not sure if there's a way around that (if there is, it's something Flutter would need to implement).

If you see anything else that might be specific to VS Code, do ping me or raise issues here though - I'd rather have additional issues here that turn out not to be issues here than potentially miss things. Thanks!

**Comment by lukepighetti** [comment]
Cool Dan, really appreciate the thorough triage on this. Is there any way to set the renderer being used at the project level?

**Comment by DanTup** [comment]
Yeah, you should be able to just set it in the Workspace Settings:

<img width="695" alt="Screenshot 2021-03-04 at 18 49 13" src="https://user-images.githubusercontent.com/1078012/110014141-5d210980-7d1a-11eb-9f2f-bc225fec399f.png">

**Comment by lukepighetti** [comment]
Thanks for the blazing fast support and bringing this issue to a close. Really appreciate it.
