### ISSUE TITLE
Null-checks on class fields do not promote types to non-null

### ISSUE THREAD

**Issue by CoenB95** [Dart-Code/Dart-Code#3178]
**Describe the bug**
In nullsafety-mode (Dart 2.12), Visual Studio Code complains about variables not being checked whether they are `null` before accessing members, even though they (clearly) are.

**To Reproduce**
1. Create a new Dart project in VSC
2. Write the following as its main logic:
```
class Test {
  List<String>? nullableList;

  void testMethod() {
    if (nullableList != null && nullableList.isNotEmpty) {
      print('This should be fine, right?');
    }
  }
}

void main() {
  Test().testMethod();
}
```
3. Observe the unexpected errors.

**Expected behavior**
There should be no compiler issues, since `nullableList` is null-checked before accessing member `isNotEmpty`.

**Observed behavior**
A compiler error is given stating that _"The property 'isNotEmpty' can't be unconditionally accessed because the receiver can be 'null'."_
NOTE 1: This also applies when trying to access members from inside the if-block.
NOTE 2: This does _not_ happen when `testMethod()` is NOT inside `class Test`. Toplevel = no error.

**Screenshots**
![Screencapture 2021-03-04 232925](https://user-images.githubusercontent.com/17980596/110039466-8acd7900-7d41-11eb-8ec0-d8cc88c3a3fa.jpg)

**Versions**
 - VS Code version: 1.54 (February 2021)
 - Dart extension version: v3.20.1
 - Dart/Flutter SDK version: Flutter 2.0.0 (stable) -> Dart >=2.12.0 <3.0.0

**Comment by DanTup** [comment]
This is working as expected, though it's an unfortunate gotcha. There's some info about this here:

https://dart.dev/guides/language/effective-dart/usage#consider-copying-a-nullable-field-to-a-local-variable-to-enable-type-promotion

The issue is that fields can be overriden in subclasses, so the null check does not guarantee that the subsequent access is not-null. You'll need to assign the field to a local variable to get the type promotion.

Hope this makes sense!

**Comment by CoenB95** [comment]
Ouch, yeah that deserves a facepalm. Well, that goes to show Dart is even more sound than I could understand. Alright thanks for the help and sorry for this issue.. perhaps it can help others in the future reading this :)
