### ISSUE TITLE
Completion list looks like something is missing when trailing commas are added to arguments

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#319]
First off, awesome work on the Flutter support!

I noticed that we don't show the type of what the parameter expects, when trying to complete a named parameter in constructors. Notice the blank space and then comma after "onTap":
![capture](https://user-images.githubusercontent.com/5479/27113621-c0fe6872-5072-11e7-95fb-ba869d3e6aa8.PNG)

Can we show something like: `onTap: void Function(),` which is more helpful than showing `onTap: GestureTapCallback` because, what is a GestureTapCallback? :)

Thanks!

**Comment by sethladd** [comment]
BTW do you have a label for "code completion" ?

**Comment by DanTup** [comment]
@sethladd What do you mean by label? In GH? Not really; I only have some basic labels; there aren't really enough cases that they need breaking into small categories.

**Comment by DanTup** [comment]
This text is actually how we get it from the analyzer:

![onTapUp](https://user-images.githubusercontent.com/1078012/27222983-6c2ba678-5286-11e7-98ab-730c81afed0f.png)

However there is a bug in Dart Code that we normally put a placeholder into the completion, but it's only triggered when the completion ends with `: ` (it doesn't consider the trailing comma). I'll fix this, which will add the placeholder but as far as I can see, it still seems I don't have the info you want (for example for `onTapUp` I know it's a `GestureTapUpCallback` but not what that is).

I'll make this fix and then post a screenshot of how it works, and then maybe it's worth raising an issue @ sdk for surfacing the actual type of the function required.

**Comment by DanTup** [comment]
@bwilkerson While testing some changes for this, I noticed that in a Dart project I only ever get completions back that end with `: ` but in a Flutter project I get them back with `: ,` on the end. The SDKs are *very* slightly different versions.

Is this a deliberate change made between `1.24.0-dev.6.7` and `1.24.0-dev.6.8` or could this be a bug?

**Comment by DanTup** [comment]
Ok, I was a little confused by this. I think there are two issues, however I don't think the type is missing.. In your screenshot you've opened the "details" pane (`Ctrl`+`Space`) which moves the type from the completion list to where it is in yours. Here's what it would normally look like:

![Completion with type](https://user-images.githubusercontent.com/1078012/27226815-a4e92640-5298-11e7-85f8-3019a509513f.png)

So I think there are two issues:

1. There's a weird comma appearing when completing arguments on GestureDetector (I can't repro this by copy/pasting the definition!) which I think should not be there.
2. Showing the name of the type-def is less useful than showing the underlying type.

I think both of these things may be Analyzer issues, but I'm gonna do some more investigation.

However, as a result of this case I did make a bunch of other minor improvements to the completion (#323, #324).

**Comment by DanTup** [comment]
It seems like both of the problems described here would require analyzer changes. I've raised two cases over at the SDK repo:

https://github.com/dart-lang/sdk/issues/29909 - Unexpected commas on the end of argument completion for GestureDetector
https://github.com/dart-lang/sdk/issues/29910 - Provide more information for TypeDefs in completions from analyzer

I can't really explain the first one (I can't repro the commas with my own classes, but do see them for `GestureDetector` in same project!).

**Comment by sethladd** [comment]
Thanks for taking a look!

**Comment by DanTup** [comment]
Seems like the commas being inserted are by-design - see https://github.com/dart-lang/sdk/issues/29909. I don't really agree with this though, I think it's wonky for many reasons and really don't understand the advantages. I'm tempted to strip them out client-side :/

**Comment by sethladd** [comment]
Ah, yeah. Interesting that the AS is inserting the comma.

The commas are basically required, because they are the signal to the formatter: "format this with more tree-like indention", which is very helpful for Flutter developers.

**Comment by DanTup** [comment]
@sethladd Since you raised this originally; what are your thoughts on me hiding the trailing comma in the completion list (it would still be inserted into the document)? IMO it totally looks like a bug in your screenshot even though I'm come around (somewhat) to the behaviour (I still think it's inconsistent, but there's discussion about that in the sdk issue!).

The pro of hiding the comma is that it doesn't look buggy, but the con is that the completion items don't perfectly show you what would be inserted (it's hard to know if that'd be a big deal to people).

**Comment by DanTup** [comment]
Due to no responses, I've made a call on this! I've trimmed the commas from the *display text* so everything looks normal:

![Trimmed](https://user-images.githubusercontent.com/1078012/27953918-8e8d6c08-6305-11e7-8c2b-16b3e2b49483.png)

But when you insert, you still get the original text including the comma (and the placeholder I injected):

![Inserted](https://user-images.githubusercontent.com/1078012/27953956-af0cb600-6305-11e7-94f8-8ca26d20c7e2.png)

I haven't used it much, but in a quick test this looks and feels really natural.
