### ISSUE TITLE
"dart.previewLsp": true slows down VSCode Intellisense

### ISSUE THREAD

**Issue by nemoryoliver** [Dart-Code/Dart-Code#3193]
**Describe the bug**
The latest update caused my **VSCode's Intellisense** to slow down. Disabling the new setting `"dart.previewLsp": false` fixes the issue.

**To Reproduce**
set `"dart.previewLsp": true`

**Versions:**

```
✓] Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale en-PH)
    • Flutter version 2.0.1 at /Users/nemoryoliver/fvm/versions/stable
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/nemoryoliver/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/nemoryoliver/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • IN2010 (mobile) • 022666eb • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 89.0.4389.72 beta

• No issues found!
```

**Comment by DanTup** [comment]
> The latest update caused my VSCode's Intellisense to slow down

Can you be specific about what you're seeing? Do you mean specifically the code completion suggestions? What sort of slowdown are you seeing? Does it happen every time, or intermittently?

There is a known issue in current Flutter stable where after opening a new file or holding Cmd/Ctrl while hovering a symbol, it can trigger some work that will slow things down for a short period. That's been fixed in Flutter dev/master but didn't make the stable release. I'm unsure if it's the same issue you're seeing though.

**Comment by nemoryoliver** [comment]
> > The latest update caused my VSCode's Intellisense to slow down
> 
> Can you be specific about what you're seeing? Do you mean specifically the code completion suggestions? What sort of slowdown are you seeing? Does it happen every time, or intermittently?
> 
> There is a known issue in current Flutter stable where after opening a new file or holding Cmd/Ctrl while hovering a symbol, it can trigger some work that will slow things down for a short period. That's been fixed in Flutter dev/master but didn't make the stable release. I'm unsure if it's the same issue you're seeing though.

It happens actually everytime VSCode tries to give suggestions. As well as saving a file, renaming a file is super slow.

I'm using Flutter stable and actually used to press (CMD + .) to tell VSCode to give me suggestions. So maybe it does relate to Flutter's issue you mentioned. But saving and renaming a file doesn't involve that but still super slow.

**Comment by Ali-Fadaei** [comment]
@nemoryoliver exactly! I have same issue and working in this situation is very difficult.

**Comment by kika** [comment]
With `previewLsp: true` the status bar shows "Analysing" spinner for tens of seconds up to a minute for every change. Project has 17Kloc of Dart code, it's not that big. So you click on a warning, wait 30-40 seconds, apply the suggestion (or make the change manually), wait 20-40 seconds more, rinse, repeat.

**Comment by DanTup** [comment]
> with `previewLsp`: true the status bar shows "Analysing" spinner for tens of seconds up to a minute for every change.
> 
> So you click on a warning, wait 30-40 seconds, apply the suggestion (or make the change manually), wait 20-40 seconds more, rinse, repeat.

Are you able to capture a log of these happening using the **Dart: Capture Analysis Server Logs** command? ​Note: It will include parts of your source code/edits, so if doing this on a private project you may want to trim down the log. You can share logs with me via email (logs@dartcode.org) but don't send anything sensitive.

I'm also curious if anyone seeing these issues is able to easily switch to the dev/master branch temporarily and see whether it changes anything? (note: the first load after changing Flutter branch will take longer for the initial analysis as the SDK is parsed). dev/master include the perf fix I mentioned above, however it should not be triggered just be changing a file - it was only triggered when opening new files (including where you cmd/ctrl+hover a symbol - which triggers VS Code's "document opened" API because it shows a preview).
