### ISSUE TITLE
Suggestions on the "Import library" lightbulb actions

### ISSUE THREAD

**Issue by yyoon** [Dart-Code/Dart-Code#320]
First of all, this feature is really great. I have a few more suggestions.

* If the import declarations are already sorted, insert the new import in the right place. For now I have to import and then sort as a two step process.
* If the file being imported is in the current package, please consider offering the relative path import as an option. (This may not be a desired option for some projects, so enabling this could be a settings flag.)
* Also please consider offering an option to import the desired library with `show Foo` at the end. For instance, we do `import 'dart:convert' show JSON;` a lot in our project.

**Comment by DanTup** [comment]
These are great suggestions, but the code fixes shown (and the edits that they make) actually come from the Dart Analyzer directly so these would need to be implemented there. Would you mind raising at [dart-lang/sdk](https://github.com/dart-lang/sdk/issues) and posting a link back here?

Thanks!

**Comment by yyoon** [comment]
Done. You should see it right above this comment.

**Comment by DanTup** [comment]
Thanks!

**Comment by pulyaevskiy** [comment]
@DanTup 

If I'd like for import suggestions to trigger without having to type `package:` would it also be SDK dependent? E.g. 

```dart
// pipe is where the caret is
import 'http|'; // < suggests 'package:http/http.dart'
```

(Folks at intellij somehow got it working in idea)

**Comment by DanTup** [comment]
@pulyaevskiy I don't totally understand the request. Do you mean that you get the correct results if you manually invoke completion, but you want it to trigger automatically? Or do you mean if you type `http` and then invoke completion it doesn't give you the `package:` results?

**Comment by pulyaevskiy** [comment]
@DanTup 

Oh, ok, I just learned about `^Space` and it seems to be doing what I need so this is probably less critical.

In my above example if I hit `^Space` it actually shows all the packages with `http` so that's great.

The remaining issue now is for completion to automatically pop up when I change something inside an import, so that I don't have to use the hot key. But again it is more of a nice-to-have.

**Comment by DanTup** [comment]
@pulyaevskiy It's worth raising a case for, though it may be complicated to fix - we don't have any context (in Dart Code) so we need to be careful where we automatically trigger completion (#504 is a bug caused by us doing it too eagerly). We do have some other info we might be able to use though, it'd need some investigation (I think the idea of popping it open for import strings is a good one).

**Comment by pulyaevskiy** [comment]
> (I think the idea of popping it open for import strings is a good one)
@DanTup wondering if you could point me at a file/line in the source code which would be a good starting point to research this, I'd take a look when I have free time.

**Comment by DanTup** [comment]
@pulyaevskiy I've created #512 to track this (to avoid confusing this issue) and added some notes there on where to start and what I think might be a reasonable fix :-)

**Comment by DanTup** [comment]
Tidying up the issue tracker a little. There's an SDK case linked above for this; I believe the issue is entirely upstream and if/when things are changed there, Dart Code will get them for free. The linked request about automatically opening completion during imports has been done, and today there were further improves made (like refreshing completion lists when typing path separators in import paths).
