### ISSUE TITLE
How to change my pub source?

### ISSUE THREAD

**Issue by Wbqqqq** [Dart-Code/Dart-Code#3207]
I'm sure I have no problem with my environmental variables and private sources I use .
but when plugin auto update my yaml file , I found that my pubspec.lock The URLs of each library of are replaced with official sources.
how to settting the default of the plugin's PUB_HOSTED_URL?
thanks.

**Comment by Wbqqqq** [comment]
![image](https://user-images.githubusercontent.com/17332298/111174671-955dfd00-85e2-11eb-81f4-4d1337452810.png)

like this.

**Comment by DanTup** [comment]
The `PUB_HOSTED_URL` environment variable will be inherited from the VS Code process, so if you've set it in your system, it should apply.

If you're unable to set the environment variable system-wide, you can set it in your VS Code settings (or even workspace/folder settings) with the `dart.env` setting:

```js
"dart.env": {
	"PUB_HOSTED_URL": "http://foo/"
}
```

Let me know if this doesn't work for you!

**Comment by Wbqqqq** [comment]
thanks , my dear bro.  It's done . 🎉 🎉

![image](https://user-images.githubusercontent.com/17332298/111245092-07fcc600-863f-11eb-9690-4e745203e2b9.png)

but I have two question . 

first , you said  'environment variable will be inherited from the VS Code process' , but  I'm sure I have no problem with my environment variable , when I use the terminal to execute commands, everything is OK. Does this have anything to do with Bash and Zsh? I wrote environment variable in '. Bash_ Profile ', executed 'source ~ /. Bash' in'. Zshrc ' . The terminal uses Zsh by default. 

The second problem is that I see that this looks like a global variable. Can I set it up according to the project? Because my own project may use official sources.

**Comment by DanTup** [comment]
> first , you said 'environment variable will be inherited from the VS Code process' , but I'm sure I have no problem with my environment variable , when I use the terminal to execute commands, everything is OK. Does this have anything to do with Bash and Zsh? I wrote environment variable in '. Bash_ Profile ', executed 'source ~ /. Bash' in'. Zshrc ' . The terminal uses Zsh by default.

The bash profile scripts run when you start a terminal, so any environment variables you set in there are scoped to the terminal. If you launch VS Code outside of the terminal, that means it does not inherit them (although if you launch Code from the terminal, it will).

On some platforms, setting environment variables _globally_ seems tricky, which is why I added the `dart.env` setting as an easier way.

> The second problem is that I see that this looks like a global variable. Can I set it up according to the project? Because my own project may use official sources.

In VS Code there are both "User Settings" and "Workspace Settings". If you add this to "Workspace Settings" it will go inside `.vscode/settings.json` in your project, and will be scoped only to that project:

<img width="369" alt="Screenshot 2021-03-16 at 07 21 29" src="https://user-images.githubusercontent.com/1078012/111270876-52267d00-8628-11eb-956c-d204ba5f72a7.png">

If you're using a `.code-workspace` file instead of a single folder, "Workspace Settings" will instead go inside that file.

Hope this helps!

**Comment by Wbqqqq** [comment]
Thanks bro for sparing no effort to answer such silly questions for me.

Now that everything is done, I can finally play happily.

Best wishes for you 🎉

**Comment by DanTup** [comment]
Nothing silly about the questions! Happy to help :-)

**Comment by mx1up** [comment]
is there an option/configuration similar to dart.env for Intellij?

**Comment by DanTup** [comment]
I'm afraid I don't know the answer to that, I don't use IntelliJ. If you _always_ want it set (for all projects) and you're using Windows, you could easily set it in the Windows environment variables.

**Comment by mx1up** [comment]
thanks for your feedback. I need a project dependent setting but I'm afraid it's not possible with the intellij plugin. I'll use a shell script then (and close all running intellij instances first)
