### ISSUE TITLE
The Flutter Daemon Has Terminated 

### ISSUE THREAD

**Issue by chrisgford** [Dart-Code/Dart-Code#3218]
**Describe the bug**
When selecting a device in VS Code, I am receiving the 'Fluter Daemon has terminated' error.

I am receiving this error:
[10:37:57 PM] [General] [Info] Activating Flutter extension for Flutter project...
[10:37:57 PM] [General] [Info] Extension:Startup timing: 37ms
[10:37:57 PM] [FlutterDaemon] [Error] env: bash: No such file or directory

All paths are set correctly for Flutter.

**To Reproduce**
1. Open VSCode
2. Click on 'No Device' 
3. The Flutter Daemon has Terminated error pops up.

**Expected behavior**
Able to select a device for Flutter app to run on.

**Versions (please complete the following information):**
Dart Code extension: 3.6.0
Flutter extension: 3.7.1
VS Code: 1.39.2

**Comment by DanTup** [comment]
> [10:37:57 PM] [FlutterDaemon] [Error] env: bash: No such file or directory

The previous times I've seen this issue are when the environment `PATH` is broken. In one case, it had been accidentally wiped out and replaced with just the Flutter SDK path (which meant `bash` could not be found) and in the other case, the wrong quotes in the bash profile had resulted in it having the literal string `$PATH` instead of the previous path (see https://github.com/flutter/flutter/issues/76555).

Can you check these? The message should have an "Open Log" button or similar that should provide the last few hundred log events, though whether that includes `PATH` may depend on how much stuff has happened since you hit the error. You could enable the [extension logfile](https://dartcode.org/docs/logging/#extension) to get a complete log that would definitely include the `PATH` when searching for SDKs.
