### ISSUE TITLE
Auto Semi Colon

### ISSUE THREAD

**Issue by Fanqish** [Dart-Code/Dart-Code#3220]
Even Css Have Auto Semi Colon Completion With Auto Save

**Comment by DanTup** [comment]
@bwilkerson has this come up before? I couldn't find any issues in the SDK repo specifically about inserting semicolons (although I found [an issue about them being optional](https://github.com/dart-lang/language/issues/72)). Is it worth moving this request to the SDK, or is it more likely the solution would be to make them optional than trying to insert them? (it has also been raised in [dart_style](https://github.com/dart-lang/dart_style/issues/948) though reasonable rejected as not being formatting).

**Comment by bwilkerson** [comment]
I don't remember ever seeing the request before. The possibility of optional semicolons is interesting, but it's been 2.5 years since we started discussing it and I'm not confident that it will happen quickly, if at all, so I wouldn't necessarily postpone this kind of support in the meantime. What I don't know is what kind of support IDEs actually have for this kind of feature. For example, does LSP support a way for language servers to auto insert semicolons (or other code)?

**Comment by DanTup** [comment]
> What I don't know is what kind of support IDEs actually have for this kind of feature. For example, does LSP support a way for language servers to auto insert semicolons (or other code)?

There's nothing built in to LSP that I know of. The request here was to do it on-save which I think would mean it would have to be done as part of the format request (not necessarily by the formatter, but at least in the LSP formatting handler - presumably before the formatting, since the formatter wouldn't format invalid code). This would make it actually "insert semicolons during format", which I don't think would be a bad thing (although it may need to be limited to certain types of formatting - I'm not sure format-on-type should be trying to add semicolons).

Presumably this would rely on the parser doing a reasonable job of parsing the code without semicolons, then the server could build edits to insert them for nodes that should have semicolon tokens but don't?

If you think it's a fair request (and makes sense to implement in the server), should we move this to the SDK repo and allow people to 👍  on it to gauge interest?

**Comment by bwilkerson** [comment]
> Presumably this would rely on the parser doing a reasonable job of parsing the code without semicolons ...

Yes, it would. I don't know how reasonable a job it does. We could test it by taking some representative samples of code, and for each file remove varying numbers of semicolons, parse the file, and record the number of times a missing semicolon diagnostic was reported in the correct location and the number of times it was either not reported or reported in the wrong location.

> If you think it's a fair request ...

I don't think there are very many requests from users that aren't fair. :-) Unfortunately we don't have the resources to implement every fair request, and I don't know whether this one would pass the bar in terms of being helpful enough to enough people to get resources applied to it.

But either way I agree that this isn't an issue that should be solved in Dart-Code, so it would probably be a good idea to move it. Even if it's closed there other users are more likely to find it if it's there.

**Comment by DanTup** [comment]
Makes sense - I've moved it to https://github.com/dart-lang/sdk/issues/45427. Thanks!

**Comment by hxyong** [comment]
Does it still not support automatic semicolon insertion?
