### ISSUE TITLE
vscode cannot import

### ISSUE THREAD

**Issue by nurulazizah0903** [Dart-Code/Dart-Code#3229]

**Comment by DanTup** [comment]
Can you provide some more details about the problem? Thanks!

**Comment by tomasbaran** [comment]
duplicate: https://github.com/Dart-Code/Dart-Code/issues/3211?

**Comment by tomasbaran** [comment]
@nurulazizah0903 if you want the issue to resolve faster, only +1 thumb it up. @DanTup says it's not a priority only an enhancement. From my perspective it's NOT an enhancement but a necessity. Autocompletion is something developers count on.

**Comment by DanTup** [comment]
> @DanTup says it's not a priority only an enhancement. From my perspective it's NOT an enhancement but a necessity. Autocompletion is something developers count on.

I definitely agree that code completion is a requirement, though #3211 is specifically about "automatically opening the code completion" rather than making it actually work. You can (at any position in the document) invoke completion yourself.

I definitely want to address it soon - it's a very convenient feature and a gap in LSP.

That said, it's not clear if that's what @nurulazizah0903 was raising. I'll leave this open a little longer for a response before assuming it's the same. Thanks!

**Comment by nurulazizah0903** [comment]
Ok wait a minute please

Pada tanggal Jum, 26 Mar 2021 23.20, Tomas Baran ***@***.***>
menulis:

**Comment by nurulazizah0903** [comment]
When i run the program
The debug show this
And when i make a new modul project and i add import package this always
cannot add, always error
Although i just run flutter put get, but the final is always error
I dont know what to do again

Pada tanggal Jum, 26 Mar 2021 23.29, Nurul Azizah ***@***.***>
menulis:

**Comment by tomasbaran** [comment]
@nurulazizah0903 it seems you sent me a private message (I have no idea how :)) it's better to just reply to everyone. To your message, I don't understand your issue to be honest. You need to provide code examples to understand it.

**Comment by nurulazizah0903** [comment]
can you help me again :)

Pada tanggal Jum, 26 Mar 2021 pukul 23.39 Tomas Baran <
***@***.***> menulis:

**Comment by nurulazizah0903** [comment]
and i cant import this import
'package:cached_network_image/cached_network_image.dart';

Pada tanggal Sen, 29 Mar 2021 pukul 11.49 Nurul Azizah <
***@***.***> menulis:

**Comment by DanTup** [comment]
@nurulazizah0903 it's not clear from the description what the issue is. If you intended to include a screenshot in your previous message, it didn't come through - perhaps because you replied to the email. If you want to include screenshots, you need to attach them through the GitHub web app at https://github.com/Dart-Code/Dart-Code/issues/3229. Thanks!
