### ISSUE TITLE
Debugging a test, and "Stopping" marks test as successful

### ISSUE THREAD

**Issue by jepperaskdk** [Dart-Code/Dart-Code#3251]
**Describe the bug**
A test is marked as successful, if debugging is cancelled during the test.

**To Reproduce**
1. Right-click a test and select "Start debugging"
2. Set a breakpoint somewhere branched by the test
3. Press the red square ("Stop" - or Shift F5 I believe is the default shortcut)
4. Notice the test being marked with a green check-mark

**Expected behavior**
The test is marked as failed, cancelled, etc. (anything but success).

**Versions (please complete the following information):**
 - VS Code version: 1.55.0
 - Dart extension version: 3.21.1 (Flutter 3.21.0)
 - Dart/Flutter SDK version: Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "linux_x64"

**Comment by DanTup** [comment]
Thanks for the report! This seems like it may be an issue with the `json` reported in `package:test`. I've filed an issue at https://github.com/dart-lang/test/issues/1485 about this.

I'll close this on the assumption there's nothing to do in Dart-Code once that's fixed, but will re-open it if that turns out not to be the case. Thanks!
