### ISSUE TITLE
intellisense doesn't show compile time type error

### ISSUE THREAD

**Issue by jeiea** [Dart-Code/Dart-Code#3279]
**Describe the bug**
It seems dart intellisense has type check issue with yield statement.

**To Reproduce**
1. `dart create example`
2. `code example`
3. Modify `bin/example.dart` like the following.
```
void streamer(Stream<bool> Function() generator) {}

void main() {
  streamer(() async* {
    yield 3;
  });
}
```

**Expected behavior**
`yield 3;` statement should have error squiggle. It really generates compile time error when build.

**Screenshots**
![image](https://user-images.githubusercontent.com/4188984/114659634-f0445a80-9d2e-11eb-8a6b-35baf75b1c51.png)

**Versions (please complete the following information):**
 - VS Code version
```
Version: 1.55.1
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z (6 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```
 - Dart extension version: 3.21.1
 - Dart/Flutter SDK version: 3.21.0

**Comment by DanTup** [comment]
Thanks for the report! I can repro this in v2.12.0 of the SDK, but it appears fixed in a recent nightly build:

<img width="885" alt="Screenshot 2021-04-15 at 11 16 49" src="https://user-images.githubusercontent.com/1078012/114853815-170c9a80-9ddc-11eb-8f52-d5e008ac1eca.png">

I couldn't locate a change that seems to claim to fix it, but it looks like it has been fixed recently and should show up in a future SDK release.
