### ISSUE TITLE
Support debug as console project in flutter project

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3283]
I have a flutter project, and now I want to test some dart grammar. I configure the launch.json but extension launch the code on web browser. It would be better to provider an option to let me debug code in dart console application environment.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "dart",
            "type": "dart",
            "request": "launch",
            "program": "${file}",
        }
   ]
}
```

**Comment by DanTup** [comment]
@tjx666 where are you creating your Dart script? If it's inside the `bin` or `tool` folder, when it should run using `dart` instead of `flutter` If that doesn't work, please give details as that sounds like a bug. If the file is outside of `bin` or `tool` then this is expected - those are the only places that Dart scripts are supported for a Flutter project.

**Comment by tjx666** [comment]
You are right. It works fine when I the script to bin folder.

**Comment by tjx666** [comment]
But I think it would be better to let user control the behavior with launch.json option.

**Comment by DanTup** [comment]
> But I think it would be better to let user control the behavior with launch.json option.

It's certainly a possibility, however I have some reservations about doing this. There are currently 4 different debug adapters (Dart, Dart test, Flutter, Flutter test) and we have some rules about how to select the correct one. Those rules have improved over time and support some flexibility (for example test files outside of the test folder). I'm concerned that allowing the user to select the debugger explicitly will result in lots of people copy/pasting samples that do this rather than raising issues when the rules seem to get it wrong.

If there is a compelling use case to put Dart scripts outside of `bin`/`tool` I'm open to it. Where are you currently putting your scripts, and is there a reason that `bin`/`tool` don't seem appropriate?

**Comment by tjx666** [comment]
Recently I am studying flutter in depth through some code test, and I both want to study dart grammar in both project. like bellow:

<img src="https://user-images.githubusercontent.com/41773861/115442346-7b988100-a244-11eb-9a70-1753ca303913.png" alt="stateless widget life cycle" style="zoom:20%;" />

**Comment by DanTup** [comment]
Thanks for the clarification. I think using the `bin` folder makes most sense here - I don't think it's common to put executable scripts inside the `lib` folder of a Flutter project so I don't think it's worthwhile to change how the debugger is selected only for this purpose.

Another option is to create a sibling project alongside your Flutter app and open them both in VS Code together - scripts in a non-Flutter app would always run with the Dart VM.

Hope this makes sense!
