### ISSUE TITLE
Support jump to implementation of an external method

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3284]
It would be very helpful to support jump to the external method implementation when read source code.

![image](https://user-images.githubusercontent.com/41773861/115109033-20496300-9fa6-11eb-91e3-424f0e88ea08.png)

**Comment by DanTup** [comment]
@bwilkerson would this be possible? My assumption was that these `external` methods were native code, but poking around in the SDK I found what looks like Dart implementations for them:

https://github.com/dart-lang/sdk/blob/b802aadf7150af606b8cc5ba87d7a8b39c102292/sdk/lib/_internal/vm/lib/integers_patch.dart#L51

Based on the folder structure (there's `js_runtime` as well as `vm`) I guess the implementations differ per-runtime, but the code for each does exist in the shipped SDKs (eg. at `{sdkRoot}/lib/_internal/vm/lib/integers_patch.dart`).

Go-to-Definition does support multiple results, so it could be nice if invoking it on int.parse would list the results in each runtime folder. I don't know whether there's a way to get from these `external` definitions to the implementations in the runtime folders though?

**Comment by bwilkerson** [comment]
@DanTup 

Yes, I believe that it would (at least theoretically) be possible.

I don't know of any pattern for going from a `external` definition to the implementation. My understanding is that the runtime platforms load their patch files and use the information in the patch files to locate the `external` definition, not the other way around.

So I believe that the analysis server could read the patch files for the various runtime systems and build a map from `external` declarations to implementations. There isn't currently any support in the analysis server for reading the patch files, so that would have to be added.

It sounds like a lot of work, so there would need to be a significant benefit to the user.

@tjx666 

> It would be very helpful to support jump to the external method implementation when read source code.

What information would you get from doing this that you can't currently get? I'm wondering whether there might be another way to satisfy your requirements, but to answer that I need to better understand what your requirements are.

**Comment by tjx666** [comment]
I just want to see the implementation of `external`  for current platform so that I can understand more about dart underlying principle.

**Comment by bwilkerson** [comment]
While that's a perfectly reasonable use case, I suspect that it isn't one that's shared by a lot of users. Given the amount of work that would be required to support it, I suspect that we aren't likely to dedicate resources to it. But I'm not the one who makes such decisions, so if you'd like to open an issue at https://github.com/dart-lang/sdk/issues/new, we can gauge user interest and get a more definitive answer.

In either case, thanks for asking. We really do appreciate all user feedback.

**Comment by DanTup** [comment]
I'll close this one in favour of the SDK issue at https://github.com/dart-lang/sdk/issues/45761. Thanks!
