### ISSUE TITLE
Flutter medical image/file view DICOM File and doc,docx,pdf view/open in flutter app

### ISSUE THREAD

**Issue by Navnath83** [Dart-Code/Dart-Code#3288]
Hello,
I am new to flutter there is an requirement for me to view medical image (DICOM file /image) how to view/open in my flutter app and

View PDF and doc,docx (especially) in android and ios application without using or opening any other document viewer apps. I need to show PDF and doc,docx file in my app not in third party apps. I use some dart package but not working like file_open, file_picker, file_reader only works pdf_viewer for pdf file but other extension not working please give any solutions

Thank you.

 - VS Code version:1.55.2
 - Dart extension version:3.21.1
 - Dart/Flutter SDK version:2.12.2

**Comment by DanTup** [comment]
Hi!

This tracker is for issues with the Dart/Flutter VS Code extensions. It's not a great place for asking general questions about building Flutter apps (in part because it's only really monitored by me, and I don't know the answers to most of these types of questions 🙂).

I'd recommend trying [StackOverflow](https://stackoverflow.com/questions/tagged/flutter), [Reddit](https://www.reddit.com/r/FlutterDev/) or some of [the other resources listed on the Flutter site](https://flutter.dev/community#q:~:text=Get%20answers%20to%20your%20questions%20and,by%20checking%20out%20the%20links%20below.).

Thanks!
