### ISSUE TITLE
initState snippet implies code should be added before call to super.iniState()

### ISSUE THREAD

**Issue by nickmeinhold** [Dart-Code/Dart-Code#3291]
**Describe the bug**

The snippet for initState puts a comment line with `TODO: implement...` above the line `super.initState();`

<img width="353" alt="Screen Shot 2021-04-21 at 7 36 10 pm" src="https://user-images.githubusercontent.com/1059276/115532231-f14e2c80-a2d8-11eb-9d91-82858e037ed4.png">

This seems to imply that the `super.initState();` line should be last. 

**Expected behavior**

The `super.initState();` line should come first.

There is some discussion  in StackOverflow [here](https://stackoverflow.com/questions/58400001/should-i-call-super-initstate-at-the-end-or-at-the-beginning) and [here](https://stackoverflow.com/questions/60254613/should-codes-be-written-before-super-initstate-or-after-in-flutter) 

And the [State classes initState](https://github.com/flutter/flutter/blob/12a2e682b47e16818cc7cd9ca5fe8ea09fd38992/packages/flutter/lib/src/widgets/framework.dart#L960) says:  

```Dart
  /// Implementations of this method should start with a call to the inherited
  /// method, as in `super.initState()`.
  @protected
  @mustCallSuper
  void initState() {
    assert(_debugLifecycleState == _StateLifecycle.created);
  }
```

**Comment by DanTup** [comment]
Thanks for the report! I presume this refers to the code-completion entry here?

<img width="904" alt="Screenshot 2021-04-21 at 11 35 32" src="https://user-images.githubusercontent.com/1078012/115540183-bd054c80-a295-11eb-99d8-8af45d54fa72.png">

If so, this is coming from the language server in the Dart SDK rather than the extension:

https://github.com/dart-lang/sdk/blob/60a53afc5e5b54caf50cfaab93c3b0899c8ce34e/pkg/analyzer_plugin/lib/src/utilities/change_builder/change_builder_dart.dart#L453

The code is fairly generic so I'm not sure whether it would be best to special-case if it's reasonable to swap the order for all overrides, but if you file an issue at https://github.com/dart-lang/sdk that would be the best place for that discussion.

Thanks!

**Comment by nickmeinhold** [comment]
Thanks @DanTup! I filed https://github.com/dart-lang/sdk/issues/45783
