### ISSUE TITLE
The Flutter Daemon Has Terminated

### ISSUE THREAD

**Issue by rmargolinross** [Dart-Code/Dart-Code#3298]
**Describe the bug**
I am getting an error in vsCode that the flutter daemon has terminated every time that I try to open a device.

**To Reproduce**
1. Open up VS Code
2. Click No Device button on bottom right corner

**Expected behavior**
Expect to see a list of devices show up

**Versions (please complete the following information):**
 - VS Code version: 1.55.2
 - Dart extension version: 3.21.1
 - Dart/Flutter SDK version: 2.0.5

**Comment by rmargolinross** [comment]
[daemon.txt](https://github.com/Dart-Code/Dart-Code/files/6367344/daemon.txt)
I am attaching my deamon log if that helps.

**Comment by kjones** [comment]
Same is happening to me. Was working last night but not today.

**Comment by kjones** [comment]
Wait - found out the change. I added the following last night to `.vscode/.settings`
```
{
  "dart.vmAdditionalArgs": ["--no-sound-null-safety"],
  "dart.flutterAdditionalArgs": ["--no-sound-null-safety"]
}
```
Deleting that "fixes" it for me. But then can't run/debug my app since not all libraries I'm using can be converted to to null safety yet.

**Comment by DanTup** [comment]
Sorry for not responding here, I somehow overlooked this. Adding `--no-sound-null-safety` to `flutterAdditionalArgs` is not correct, as it will be passed to all Flutter commands. You should really add it to the `args` field in the `launch.json` of the apps that require it. If you really want to set it globally (but I'd recommend against this, since it'll run that way for all projects even if you have migrated them), use `dart.flutterRunAdditionalArgs` (note the `Run` in the name).
