### ISSUE TITLE
Provide a key binding to prevent auto-insertion of `//` and `///`

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3299]
Please Consider providing a key combination to escape auto insertion of comments or dart-doc comments when inserting a new line.   

I would suggest <kbd>shift</kbd>+<kbd>enter</kbd> as an option.

**Comment by DanTup** [comment]
This unfortunately isn't possible because this behaviour is controlled by VS Code (we declare some rules for it, but we can't handle things like keypresses).

However, there are some improvements coming in the next releases:

- #3248
- https://github.com/Dart-Code/Dart-Code/issues/3203#issuecomment-817959179

Would these solve your issues? It would allow you to disable this functionality, or set it to only occur for triple-slash (the original behaviour - although always inserting them if breaking up existing comments).

**Comment by osaxma** [comment]
the comment in 3203 sounds like a good option. Thanks Dan!
