### ISSUE TITLE
Allow void to be coloured like a type

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3308]
![image](https://user-images.githubusercontent.com/41773861/116456669-191f3080-a895-11eb-8c33-b80d1bf3575e.png)

**Comment by UmairJibran** [comment]
according to the latest version of the file, `void` and `var` are categorized as `preemptive type`, const has been moved to `modifier` and the `String` is highlighted as a normal class.

**Comment by UmairJibran** [comment]
However, I have created a pull request with the requested changes, let's see if they accept it or not.

**Comment by DanTup** [comment]
Sorry for the delay! I think `void` is is a little different to a normal type (for example there are places where you cannot put `void` but could put a type). I'm not sure if colouring it like a type is more correct than as a keyword, and some people may prefer it as is (I do - I like being able to see `void` at a glance and know whether a function is returning a value or not).

If there's demand for being able to colour it like a type, perhaps it would be better to add a modifier to the semantic token so that it can be customised?

@UmairJibran I'll comment on the PR about your change - I'm not sure I entirely understand the goal - although I will note that if we do make changes here, they should also be reflected in LSP semantic tokens, otherwise you'll see them load as one colour, and then change to another colour once the semantic tokens arrive.

**Comment by nbros** [comment]
I know `void` is a type in Dart but I still see it as the _absence_ of a type, so I like it colored this way too (like a keyword).

**Comment by tjx666** [comment]
I see that `void` is colorized as type in typescript file.

**Comment by DanTup** [comment]
@tjx666 I think there are valid arguments for colouring it both ways. Given at least _some_ people prefer it to be coloured like a keyword and that's what people are already used to, I think any change should be opt-in.

Adding a semantic token modifier will allow anyone who wants it to be coloured like a type to change its colour, and the default would remain as-is.

**Comment by DanTup** [comment]
I landed a change in the SDK in https://github.com/dart-lang/sdk/commit/3690f549b02f11787358ed6e12df96b55dcceaf7 that adds a `void` modifier to the `keyword` token, so it's now possible to customise the colour of the `void` keyword in your VS Code settings:

```js
"editor.semanticTokenColorCustomizations": {
	"rules": {
		"keyword.void": {
			"foreground": "#ffff99",
			"fontStyle": "underline"
		}
	}
},
```

<img width="278" alt="Screenshot 2021-06-10 at 09 52 11" src="https://user-images.githubusercontent.com/1078012/121495465-8b754b80-c9d1-11eb-9d4b-c7f3f4202ff1.png">

By default `void `will remain coloured as a keyword, but you're now able to reliably customise it. Unfortunately I don't know a way with VS Code's customisations to map it to another colour so you'll have to put the colour in explicitly. You can find out what your class colour is with the **Inspect Editor Tokens and Scopes** command and then selected an existing class name and it should show the hex value:

<img width="362" alt="Screenshot 2021-06-10 at 09 53 26" src="https://user-images.githubusercontent.com/1078012/121495686-bc558080-c9d1-11eb-97e9-bf6b201652af.png">

Note: This change is in the SDK, so you may not see it until a future Dart/SDK update (although for testing, it's already in the [bleeding-edge Dart builds](https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/) - ofc they're not recommended for production).
