### ISSUE TITLE
Type Hierarchy should be display in sidebar and provide editor context menu

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3313]
![image](https://user-images.githubusercontent.com/41773861/116789409-39dbc600-aae1-11eb-9399-dd354b317388.png)

**Comment by tjx666** [comment]
It would be better to show the Type Hierarchy using visual graphic like Java class inheritance in IDEA.

![image](https://user-images.githubusercontent.com/41773861/116789591-22e9a380-aae2-11eb-9efd-67457e4bdfe4.png)

**Comment by DanTup** [comment]
Is this request related to the _Type_ Hierarchy or _Call_ Hierarchy?

There's an open issue at #612 for call hierarchy. I'd agree it makes sense to move the Type Hierarchy to a tree than where it is, although it would probably be better to try and get a standard LSP feature for this rather than custom messages - it looks like there's a PR in-progress at https://github.com/microsoft/language-server-protocol/pull/1231. Doing it that way would allow VS Code to render this however it chooses (including visually) and be consistent for all languages.

**Comment by tjx666** [comment]
@DanTup Related to Type Hierarchy, and It seems that call Hierarchy not ready to use.

**Comment by DanTup** [comment]
This is implemented by https://github.com/dart-lang/sdk/commit/6f8d1e4859b4052094f2f492aa596b8f6364a412. It ships in the Dart language server so will show up with a future SDK release (not a Dart-Code release).
