### ISSUE TITLE
Hot restart never completes

### ISSUE THREAD

**Issue by matthewchung74** [Dart-Code/Dart-Code#3323]
**Describe the bug**

Hot restart never finishes

**To Reproduce**
1. clone https://github.com/matthewchung74/inference_app
2. install pubspec
3.  run in debugger (via launch.json) with no breakpoints
4. go to api.dart and on line 95, change seconds: to another time duration. 
(this seems to reproduce the bug)

see video, where first attempts to hot reload are fine.

https://user-images.githubusercontent.com/1685700/117346364-823a1180-ae5c-11eb-98c4-dd507ef02f90.mov

**Expected behavior**
i would expect reload to reload

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version:1.56.0
 - Dart extension version:3.22.0
 - Dart/Flutter SDK version:2.0.5 stable

**Comment by DanTup** [comment]
I can reproduce this on current Flutter stable (though also from the command line, so it seems like a Flutter or dwds issue rather than something wrong in the VS Code extension).

When it occurs, the verbose logs end like this:

```
[ +103 ms] Waiting for connection from debug service on Chrome... (completed in 104ms)
[        ] Synced 0.2MB.
[        ] <- accept
[        ] DwdsVmClient: Attempting a hot restart
[        ] DwdsVmClient: Attempting to disabling breakpoints and resume the isolate
[   +2 ms] DwdsVmClient: Successfully disabled breakpoints and resumed the isolate
[        ] DwdsVmClient: Attempting to get execution context ID.
[        ] DwdsVmClient: Got execution context ID.
[        ] DwdsVmClient: Issuing $dartHotRestart request.
[  +18 ms] DwdsVmClient: $dartHotRestart request complete.
[        ] DwdsVmClient: Waiting for Isolate Start event.
```

However, I'm not able to reproduce on Flutter beta or master channels, so it seems likely it's been fixed since the last stable release and should show up in the next one :-)

**Comment by matthewchung74** [comment]
awesome, thanks.
