### ISSUE TITLE
Unusable in Large Monorepo

### ISSUE THREAD

**Issue by chgibb** [Dart-Code/Dart-Code#3331]
We operate a large (~230k lines) monorepo consisting of several Flutter teams, several apps and several dozens of packages all using various Dart versions (null-safe and non-null-safe, though the entire monorepo uses Flutter 2.0.5). As the monorepo has continued to grow, intellisense, auto-complete, auto-import etc performance in VSCode has continued to degrade.

We're very heavy users of Git sparse-checkout to remove apps and packages that aren't relevant for people working on specific teams. For awhile this actually solved all of our performance problems in VSCode. Now however, even the smallest team's sparse-checkout is ~18% of the monorepo and performance is as bad as ever. 

**To Reproduce**
Have a big monorepo.

**Expected behavior**
Intellisense, auto-complete, auto-import should work.

**Versions (please complete the following information):**
 - VS Code version: 1.56.0
 - Dart extension version: 3.22.0
 - Dart/Flutter SDK version: 2.0.6

Is there a way to capture a performance trace that can be submitted somewhere?

**Comment by DanTup** [comment]
If you set a port number in `dart.analyzerVmServicePort` setting, you should be able to access the Observatory app for the analyzer (by visiting `localhost:{port}`) where you could capture a CPU profile (or you could point [DevTools](https://dart.dev/tools/dart-devtools) at it and use its CPU profiler).

It may also be worth using the [dart.analyzerInstrumentationLogFile](https://dartcode.org/docs/logging/#analyzer-instrumentation) log to log the traffic (note: the file will get quite large as it logs all traffic to the analyzer) - it may be useful to see the requests and their durations when this occurs.

Do you know if you're using LSP or not? (if you hover over the Dart version number in the status bar it will show either "DAS" or "LSP"). If you are, I'd be interested to know whether you see any differences using Flutter's beta channel. There was a bug in the stable release (that's since been fixed) that caused some unnecessary work to be performed when new files were opened (which included pressing Ctrl while hovering over symbols, as VS Code "opens" the file to get a preview of the code for the related symbol). It's possible on a huge codebase that that work takes longer than the projects I'd tested with.

(cc @bwilkerson)

**Comment by chgibb** [comment]
Hi @DanTup thanks for the speedy reply!

It looks like I'm personally using DAS. I switched to LSP and managed to crash the extension once (as seen in VSCode's "OUTPUT" panel). Other than the one crash, jump to definition has appeared to come back to life and I don't see "Analyzing" constantly in the status bar.

On Monday, I'll ask our other VSCode users to make sure they're on LSP. Failing that I'll see if running Flutter beta locally and Flutter stable on CI will help.

**Comment by DanTup** [comment]
I wouldn't have expected LSP to change how often anlaysis occurs (or how long it takes), although more of the completion work is done in the server so there's less blocking of the VS Code extension host thread during completion (which has improved things for some, especially those using extensions like Vim where keystrokes also go through the extension host).

LSP is gradually rolling out as the default, so I'd generally recommend using that unless the perf issue I mentioned above is causing issues (after the next stable release I'm hopeful there are no issues significant enough to prevent the default being LSP for everyone).

If you do see errors in the Output pane when using LSP, please do file issues for them. There have been quite a few fixes since the last Flutter stable (most are probably also in beta, though there have been a few more recently than that too), but it's better to get a report for something that's already fixed than possibly miss issues.

Please let me know if you do still see any issues on LSP and/or the beta branch (and if you can capture logs/profile traces noted above, that might help understand what's happening). Thanks!

**Comment by chgibb** [comment]
Switched over to LSP on stable. Intellisense, jump to definition and formatting work far more reliably now (though still with frequent issues). Auto-import is still completely unresponsive. 

I'll count this as an improvement. Looking forward to next stable release with the aforementioned bug fixes.

**Comment by DanTup** [comment]
@chgibb glad it's improved. I'm not sure exactly what you mean by "Auto-import is still completely unresponsive", but if it's not resolved by the next stable release, please do let me know. Thanks!

**Comment by chgibb** [comment]
To clarify, I mean auto-import will either never trigger when hitting "Ctrl+Space" while typing a symbol or, intellisense will offer auto-completions (including documentation and library name) but will not include auto-import as well when accepting the completion.

**Comment by DanTup** [comment]
@chgibb if that's happening shortly after opening a file or hovering over a symbol and holding `Ctrl`, I suspect it's related to the issue that's been fixed (and should be included in the next stable release). Please do let me know if you're still seeing issues after then though. Thanks!

**Comment by irvine5k** [comment]
Hello, people. I’m facing a scenario that my VSCode is unusable, we also operate in a large monorepo.

I can’t see the preview from a class, navigate to a code, autocomplete, auto import, and etc.

When I open only one package, everything works well, but I’m unable to debug the app via VSC since `main.dart` it’s not there. 

I’m currently using 2 instances of VSC, one for the mono repo and the other for the package that I'm working on. All of this is to achieve extension features and debug mode at the same time.

Dart Extension Version: 3.26.0
VSCode Version: 1.59.1
Flutter: 2.2.1

**Comment by DanTup** [comment]
@irvine5k can you reproduce this in a public project that I could try with?

If not, perhaps you can enable the [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) and review what's happening in the log when the language functionality seems unresponsive (note: the file will contain parts of your source code so don't share it if it that is sensitive).

**Comment by irvine5k** [comment]
@DanTup  I’ll review the logs, as soon that I have the results, I’ll send here.
