### ISSUE TITLE
[quick fix]: ignore for file

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3335]
dart code:

![image](https://user-images.githubusercontent.com/41773861/117830555-537dca00-b2a6-11eb-9b5d-faa5e8f97b55.png)

eslint:

![image](https://user-images.githubusercontent.com/41773861/117830787-8cb63a00-b2a6-11eb-96db-53c75b6cc125.png)

### REF:

[How to ignore a lint rule for entire file in Flutter?](https://stackoverflow.com/questions/61889572/how-to-ignore-a-lint-rule-for-entire-file-in-flutter)

**Comment by DanTup** [comment]
@bwilkerson this "ignore" quick-fix is currently inserted in the client, but I think it probably makes sense to move to the server (and support both line + file together) - I use this a lot in both Dart and TypeScript so suspect others would find it useful.

Do you think it makes sense done outside or LSP and if so, using the same fix API or something separate (eg. should they show up in `edit.getFixes`)?

**Comment by bwilkerson** [comment]
Yes, I think it makes sense to generate it in server. That way we can control which codes it gets generated for (it doesn't make sense, for example, to ignore compiler errors that will prevent code from being run).

If it's going to be in server, then I think it makes sense for them to be returned from `edit.getFixes`, but we should probably coordinate with the IntelliJ plugin authors to avoid having duplicate fixes. If we/they don't have time for that effort right now, then I'm fine with it going into LSP short term in order to make progress.

**Comment by DanTup** [comment]
@alexander-doroshko @jwren I'm not sure who is best placed to answer this - does IntelliJ have its own way to insert `// ignore`s for lint errors? I'm currently injecting them client-side in VS Code, but would like to move to the server (but don't want dupes showing up). For VS Code I'll probably suppress injecting them if they same things appear in the results from the server, though I'm less sure what to do for IntelliJ (we could just exclude them from `edit.getFixes` initially, though might want a plan for how they'd be enabled - if appropriate - in future).

**Comment by alexander-doroshko** [comment]
@bwilkerson @DanTup @jwren Yes, IntelliJ itself adds 'Suppress warning' quick fixes. I'm ok with moving them to server. I hope existing API (`edit.getFixes`) is sufficient.

There should be some way for the IDE to distinguish 'Suppress...' quick fixes from regular ones. The reason is that IntelliJ's approach is to add 'Suppress...' quick fixes to the secondary menu if a standard quick fix is available. So IDE needs info to tie 'Suppress...' quick fixes to a regular quick fix.
![image](https://user-images.githubusercontent.com/4499789/121367201-c8463180-c942-11eb-9fcd-3a51246acbed.png)

I'm happy to coordinate any time to make sure that the Dart plugin stops adding own 'Suppress...' quick fixes starting form the SDK version that adds them itself.

**Comment by DanTup** [comment]
I think `edit.getFixes` should work, although there might not be many options for indicating it's an ignore-fix. `AnalysisErrorFixes` contains a `List<SourceChange> fixes`. We could perhaps prefix the `id` on the `SourceChange` with `ignore.` or similar. Otherwise it might need a tweak to the API. @bwilkerson any thoughts/preferences?

**Comment by bwilkerson** [comment]
If using a well known prefix in the id is sufficient for all our clients then that would be the fastest path forward.

**Comment by alexander-doroshko** [comment]
Yes, id prefix will work for me.

**Comment by DanTup** [comment]
@bwilkerson @alexander-doroshko I've made a start at this here:

https://dart-review.googlesource.com/c/sdk/+/203760/

Although having the name prefixes doesn't seem simple, as the IDs currently come from the FixKind (and we won't have one of these for every error code). Currently it's generating fixed IDs of `dart.fix.ignore.file` and `dart.fix.ignore.line`. Do fixed IDs seem reasonable? (the specific values are easily changed ofc, and I have no preference for the specifics).

@alexander-doroshko if that's ok, how are you planning to disable the built-in ones - can you check for the presence of these, or will you use the version (either SDK or protocol version)? I haven't bumped the protocol version, but could.. the SDK version may be simpler but you may get some overlap with pre-release builds that might/might not have it.

For VS Code, I think I'll check the list of fixes and ensure there are no existing ignore fixes before injecting locally (and sometime after it ships in stable, just remove the code that injects them locally).

**Comment by alexander-doroshko** [comment]
> how are you planning to disable the built-in ones - can you check for the presence of these

Yes, this should work for me. Thank you for this work!

**Comment by DanTup** [comment]
@alexander-doroshko great - let me know if/when you're happy for it land in the SDK. I'll sort the VS Code side this week. Thanks!

**Comment by alexander-doroshko** [comment]
Any time, it won't break things. I'll update the Dart plugin shortly.

**Comment by DanTup** [comment]
This work has landed in the SDK:

https://github.com/dart-lang/sdk/commit/2e411e5957654a4754046798e2ec512d2d6a7037

In a future SDK release, there will be "ignore for line" and "ignore for file" fixes for lints and hints. VS Code's own local versions of those fixes will automatically be hidden when the server provides them.
