### ISSUE TITLE
Convert to StatefulWidget adds an extra underscore to private widgets

### ISSUE THREAD

**Issue by jorgecoca** [Dart-Code/Dart-Code#3343]
**Describe the bug**
If you have a private `StatelessWidget` that you'd like to turn into a `StatefulWidget`, when you using the VS Code helper to do so your new `State` class will be prefixed with an extra underscore:

For example, if your class name was `_MyCustomWidget`, when using *Convert to StatefulWidget* the new state generated will be`__MyCustomWidgetState` (notice the two underscores at the beginning)

**To Reproduce**
1. Create a private `StatelessWidget`
2. Click on `Convert to StatefulWidget` and see the new state being prefixed by 2 underscores.
![Screen Shot 2021-05-14 at 9 13 37 AM](https://user-images.githubusercontent.com/3237451/118283196-b765e580-b494-11eb-8abb-309211068b26.png)

**Expected behavior**
The new state generated only has one underscore.

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Dart extension version: 3.22.0
 - Dart/Flutter SDK version: Flutter (Channel beta, 2.2.0-10.3.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-US)

**Comment by jorgecoca** [comment]
I will fork the project and try to provide a fix for this.

**Comment by DanTup** [comment]
Thanks for the report! This fix actually comes from the Dart analysis server, so the fix will need to be made there.

If you'd like to contribute this, I believe the relevant code is here:

https://github.com/dart-lang/sdk/blob/bee609fd6b09d3e122ab279d58d9154a7f5f1263/pkg/analysis_server/lib/src/services/correction/dart/flutter_convert_to_stateful_widget.dart#L60

And tests for this functionality are at:

https://github.com/dart-lang/sdk/blob/bee609fd6b09d3e122ab279d58d9154a7f5f1263/pkg/analysis_server/test/src/services/correction/assist/flutter_convert_to_stateful_widget_test.dart

You'd need to clone and set up the Dart SDK, instructions for which are here:

- https://github.com/dart-lang/sdk/blob/master/CONTRIBUTING.md
- https://github.com/dart-lang/sdk/wiki/Building#getting-the-source

Otherwise, if that's more involved than you'd expected and you'd prefer someone else to fix it, I'm happy to have a look - just let me know. Thanks!

**Comment by jorgecoca** [comment]
Oh thank you for pointing me in the right direction! This is super helpful! I will make the changes there ;)

**Comment by MrBirb** [comment]
I have a PR submitted https://dart-review.googlesource.com/c/sdk/+/200720

**Comment by DanTup** [comment]
@MrBirb great! You'll need to run "Dart: Sort Members" in the `analysis_server/test/src/services/correction/assist/flutter_convert_to_stateful_widget_test.dart` file to fix the test failure.

**Comment by MrBirb** [comment]
@DanTup Done :D

**Comment by DanTup** [comment]
Awesome - thanks! I'll close this once that change is merged :-)

**Comment by jorgecoca** [comment]
Wohooo! Thank you @MrBirb !!!

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/5051d4b99167c8188903b7c8f29e196b0d160410 which will be included in a future SDK update.

**Comment by Mayb3Nots** [comment]
Hi, I am not seeing this is the lastest updated SDK. Am I missing something?
```
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (7 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

**Comment by DanTup** [comment]
@Mayb3Nots the hotfix releases only include very specific fixes for critical issues, so this will only show up with the next normal release (eg. 2.3 or later, not 2.2.x releases). Sorry for the confusion!

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots the hotfix releases only include very specific fixes for critical issues, so this will only show up with the next normal release (eg. 2.3 or later, not 2.2.x releases). Sorry for the confusion!

Thanks for the clarification, was wondering why some of the fixes wasnt working.
