### ISSUE TITLE
Wrap with widget menu option

### ISSUE THREAD

**Issue by josejmoran** [Dart-Code/Dart-Code#3345]
**Describe the bug**
When you select this option to wrap an existing Widget it works fine. But if the widget you add lets say had a child property and by mistake you add children, then the Remove this Widget option disappear and is hard to track the ending parenthesis added.
It only happens if you make a mistake by adding a property that is not part of the widget.

**To Reproduce**
Try to wrap a widget. Make the mistake of typing let's say title to a widget that does not have title. If you decide to take out the new widget you just add by using the Remove this Widget.. The option is not there.

**Expected behavior**
Remove this widget should be available, even if there is an error.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version: 2.0.6

**Comment by DanTup** [comment]
Are you able to provide a code sample in the state where you would expect `Remote this Widget` to appear but does not? I tried following your instructions and used `children` instead of `child`, but it still shows up:

<img width="586" alt="Screenshot 2021-05-17 at 11 21 40" src="https://user-images.githubusercontent.com/1078012/118473602-11b7ae00-b702-11eb-8551-cc573b5939a2.png">

<img width="438" alt="Screenshot 2021-05-17 at 11 21 53" src="https://user-images.githubusercontent.com/1078012/118473631-19775280-b702-11eb-9306-aa93917d9bbf.png">
