### ISSUE TITLE
Flutter autocomplete, please add the ; automatically

### ISSUE THREAD

**Issue by josejmoran** [Dart-Code/Dart-Code#3346]
Issue Type: <b>Feature Request</b>

When I type print(, the closing parenthesis is added automatically. Which is good. I suggest to add the ; so I don't have to move the cursor to the end to just type the semicolon. This will be great if it is added to everything that you add automatically that ends with a semicolon.

Extension version: 3.22.0
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by DanTup** [comment]
It would be very difficult to do this well - there are lots of situations where you type parens that are not following by parentheses:

```dart
print(min(x, y)); // There are two ) here but only one semicolon
var xs = [
  someFoo(x),
  someFoo(y),
];
var a = (1 + 2) * 3;
```

The parentheses here need to be inserted by the editor _immediately_ without a delay, because otherwise if you're typing quickly they may end up in the wrong place, and that means there's no time to wait for the file to be parsed (to try and work out whether a semicolon would be correct at that location).

So, I don't think this is something that should be done, however there are some related issues that have similar goals that I think may work better (you can subscribe to them n GitHub for updates):

- Optional Semicolons https://github.com/dart-lang/language/issues/69
- Auto-insert semi-colons during format https://github.com/dart-lang/sdk/issues/45427

Hope this makes sense!
