### ISSUE TITLE
Tab completion doesn't work right

### ISSUE THREAD

**Issue by bartekpacia** [Dart-Code/Dart-Code#3362]
**Describe the bug**
I have a very irritating problem that I think has been occurring since I enabled the new Dart LSP.

**Bad behavior** (`"dart.previewLsp": true`)

https://user-images.githubusercontent.com/40357511/119528287-5afea200-bd81-11eb-89db-642ff80d25ba.mov

I enter `.se`, then I click `tab` to accept completion for the `set(bool)` method, it completes the right variable, so I click `tab` again to accept that completion, but it gets deleted and a tab is inserted

**Expected behavior** (works when `"dart.previewLsp": true`)
I want to be able to click `tab` to accept the suggestion.

https://user-images.githubusercontent.com/40357511/119528339-6651cd80-bd81-11eb-9ed0-970133cbd2f9.mov

**Versions (please complete the following information):**
 - VS Code version: 1.56.2 x86
 - Dart extension version: 3.22.0
 - Dart/Flutter SDK version: Flutter 2.2.0, Dart 2.13.0
    ```
    $ flutter --version
    Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
    Framework • revision b22742018b (11 days ago) • 2021-05-14 19:12:57 -0700
    Engine • revision a9d88a4d18
    Tools • Dart 2.13.0
    ```

**Comment by DanTup** [comment]
I believe this is working as expected (although I understand why it seems incorrect given non-LSP behaviour).

The text `newValue` you see here is not code completion, it's a snippet placeholder. Pressing `tab` does not "accept" snippet placeholders, it tabs between them. When there is only one (and therefore nothing else to tab to), VS Code assumes by pressing `<tab>` you wanted to insert a tab.

The reason this worked with non-LSP was because we (accidentally) not setting a 0'th tabstop so VS Code was adding it at the end of the completion.

```
set(${1:newValue})$0
```

Because there are two placeholders here, pressing `<tab>` would just jump to the second one making it seem like you were accepting `newValue` but really you were just skipping over it to move to `$0`.

The reason this changed for LSP, is that the above behaviour has some drawbacks. By default VS Code disables code completion in snippet mode (the `editor.suggest.snippetsPreventQuickSuggestions` setting defaults to true) and that caused a lot of complaints. By not inserting the additional tab-stop at the end, simple method calls like this one would support code completion without needing to know about this VS Code behaviour/setting.

**Comment by bartekpacia** [comment]
thank you for a detailed explanation.

I really really don't like this behavior but I guess I'll have to get used to it.

**Comment by DanTup** [comment]
I appreciate it's not ideal, although unfortunately I don't think either option is. Whichever we pick will have some drawbacks, but I think this is probably the least-worse way.

I'm happy to reopen and review this if it seems like the majority of people prefer the opposite though (they can add comments and/or add 👍 's to this issue). Thanks for understanding!
