### ISSUE TITLE
debug console should output the flutter command when debug and run

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3375]
As following situation:

>
> When I config the 'dart.env' and "dart.flutterAdditionalArgs" setting, I can't make sure these settings  whether be applied.
>

**Comment by DanTup** [comment]
You can capture the full command being run by running the **Dart: Capture Debugging Logs** command before starting the session. I don't think it's worth printing all the time because it's pretty verbose and seems like unnecessary noise for the 99% of the time you're probably not trying to figure out if the args are being applied.

FWIW, if you want to inject arguments when running `flutter run` you should use the `launch.json` file (`args` field) or `dart.flutterRunAdditionalArgs` as `dart.flutterAdditionalArgs` will also be sent to `flutter doctor`, `flutter daemon` etc. and can cause unexpected issues (eg. if you're sending things like `--no-sound-null-safety`).
