### ISSUE TITLE
"Wrap with widget..." Quick fix doesn't select generated widget anymore

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#3383]
**Describe the bug**
When quick fix "Wrap with widget..." is selected, the newly generated widget is not selected anymore.

**To Reproduce**
1. Install Dart Code version 3.23.0
2. Put cursor on a widget
3. Do quick fix "Wrap with widget..."
4. Generated widget is not selected

**Expected behavior**
Generated widget should be selected to edit it to widget we want to use.

**Screenshots**
Version 3.22.0 (Previous behavior)
![7Wg1C0tLAE](https://user-images.githubusercontent.com/11155424/120763525-82076180-c541-11eb-992c-0e7bcc3012c2.gif)

Version 3.23.0 (Current behavior)
![LXbUyTBZfg](https://user-images.githubusercontent.com/11155424/120763562-8b90c980-c541-11eb-8a38-eb9819888ee6.gif)

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Dart extension version: 3.23.0
 - Dart/Flutter SDK version: 2.0.4

**Comment by DanTup** [comment]
Thanks for the report! This was fixed by #3143/#3215 but requires that you're using an SDK that includes https://github.com/dart-lang/sdk/commit/44275c6001837550d4a6b7339237ae1c27bdbc19. I think that should be in Flutter 2.2 if you upgrade.

If it's still not working after upgrading to the latest Flutter and restarting VS Code, please let me know!

**Comment by viszu** [comment]
This is still a bug if I use Vim vscode Extension (tested in vscode 1.58.2, Dart Code 3.24.2, Dart 2.13.4 and Flutter 2.2.1)

**Comment by DanTup** [comment]
@viszu I tried with the Vim extension and is still seems to work for me. Could you try capturing a log?

- Run the **Dart: Capture Analysis Server Logs** command from the command palette
- Invoke the quick-fix (note: move your cursor to the location _after_ starting the logs, as the quick-fixes are fetched when the cursor moves rather than when you invoke the list)
- Click **Cancel** on the logging notification to stop logging and open the log

The log should contain a bunch of JSON where the client requests the fixes from the server and the servers response.

Thanks!

**Comment by viszu** [comment]
[Dart-Code-Log-2021-06-05 14-30-11.txt](https://github.com/Dart-Code/Dart-Code/files/6830629/Dart-Code-Log-2021-06-05.14-30-11.txt)

**Comment by DanTup** [comment]
@viszu it looks like you're using the older analysis integration (not LSP). I don't know why it wouldn't work there, but that code is going away and everyone moved to LSP in the next release so I would recommend enabling LSP (with the `dart.prevuewLsp` setting) and that may solve your problem (the fix described above was for LSP).

You can tell check whether you're using DAS (the old integration) or LSP (the new) by hovering over the Dart/Flutter SDK version number in the status bar:

<img width="175" alt="Screenshot 2021-07-19 at 14 52 19" src="https://user-images.githubusercontent.com/1078012/126172797-8fd7a475-adb8-4078-aebb-df0c17794033.png">

If you still see this issue with LSP, please capture a log the same as above and let me know. Thanks!

**Comment by viszu** [comment]
@DanTup Changing to LSP didn't helped. Something weird happens with a cursor, there are two after wrapping with a widget: One from vim (block type), and its not where it should be - it's like 2 lines below, and two line above are visually selected, and second one where it should be, at "widget" word end (this one looks like normal cursor, like when I type here, but it's only visual), the real cursor is the vim block type one. Maybe it's a vim plugin weird behavior idk...

[Dart-Code-Log-2021-06-01 17-00-52.txt](https://github.com/Dart-Code/Dart-Code/files/6842084/Dart-Code-Log-2021-06-01.17-00-52.txt)

**Comment by DanTup** [comment]
@viszu I think you're right. Since it happens both in LSP and DAS mode, I think it's likely a Vim extension issue. I checked your log and the edits look good to me:

```js
"edits": [
	{
		"insertTextFormat": 2,
		"range": {
			"start": {
				"line": 20,
				"character": 14
			},
			"end": {
				"line": 22,
				"character": 9
			}
		},
		"newText": "${0:widget}(\r\n          child: Image(\r\n            image: AssetImage('images/diamond.png'),\r\n          ),\r\n        )"
	}
]
```

I did find some issues in their tracker about snippets not behaving correctly, so it's possible this is the same as one of them. Unfortunately I don't think there's anything we can do here to fix it.

https://github.com/VSCodeVim/Vim/issues/6772
https://github.com/VSCodeVim/Vim/issues/6465
https://github.com/VSCodeVim/Vim/issues/5969

**Comment by viszu** [comment]
@DanTup This is how it looks, the white block is the real cursor

![Animation](https://user-images.githubusercontent.com/2279762/126186832-34660b18-ae9d-4f63-bcee-4f3ace627d8f.gif)

**Comment by DanTup** [comment]
@viszu yeah, I suspect that's related to the issues linked above which mention going into multi-cursor mode when using snippets. I think the discussions in https://github.com/VSCodeVim/Vim/issues/5131 are also related to that (since normally you'd use `tab` to move between the snippet placeholders).

I don't think there's anything we can do in the Dart extension, it would need resolving by the Vim extension.

**Comment by viszu** [comment]
@DanTup Ok, thank You

**Comment by curiouslaw** [comment]
just want to share a quick hack here for the VSCode Vim extension issue. I use these 3 key presses to put back the cursor :
1. `esc` -- quit visual mode 
2. `cmd` + `z` -- vscode undo, won't work with vim undo
3. `cmd` + `shift` + `z` -- vscode redo
