### ISSUE TITLE
move outline sidebar to explore section and hide built in outline

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3388]
I know we can drag the flutter outline sidebar to explore sidebar, but the builtin outline and flutter outline will exists the same time. 

First, I think the flutter outline should be a section of explore, not a sidebar.
Second, I think the built in outline is useless when we have the flutter outline. The builtin outline should be hide when open a dart file.

![image](https://user-images.githubusercontent.com/41773861/120968013-dfe2b600-c79a-11eb-9a8d-43efacc7d4b5.png)

**Comment by DanTup** [comment]
I don't think it's possible/simple for an extension to dynamically change the visibility of the built-in Outline. Though also the Flutter Outline doesn't contain all of the functionality of the built-in Outline so I'm not sure everyone would agree that's a good trade.

Ideally I'd prefer to extend the built-in Outline rather than have a separate one, but that's not currently possible because it's quite limited (for example we can't add new icons and anything we add will [show up in the document symbol list](https://github.com/microsoft/vscode/issues/51332)).

I think what we have is probably a reasonable default for now, though I'm open to tweaking if there are clear improvements to be made (or we can extend the built-in Outline in future).

**Comment by DanTup** [comment]
Closing this because I don't think there's anything to do right now. Will revisit if we get a better way to extend (or replace) the built-in Outline, but in the meantime it'll stay where it is (and ofc, users can manually hide the built-in Outline and drag the Flutter one into its place if preferred). Thanks!
