### ISSUE TITLE
Hot reload with save do not work after use command dart.restartAnalysisServer

### ISSUE THREAD

**Issue by Pyft** [Dart-Code/Dart-Code#3394]
**Describe the bug**
Hot reload with save does not work after using dart.restartAnalysisServer command

**To Reproduce**

0. Enable the "Flutter hot reload on save" function in the VS Code settings 
1. Open your project in VS Code.
2. Start debugging the project
3. Click "View"
4. Click on "Command Palette"
5. Use the dart.restartAnalysisServer command
6. Wait for the end of the analysis
7. Try to change something in the project and save (Command + S)
(changes must be made not in "main" (changes must be made where the hot reload function should initially work))
8. Hot reload do not work.

**Expected behavior**
After the above steps, a Hot reload should take place.
The changes written in the code should occur on the emulator. 
A hot reload notification should appear.

The problem disappears if you restart the extensions Flutter and Dart on VS Code.

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Dart extension version: 3.23.0
 - Dart/Flutter SDK version: Flutter (Channel stable, 2.0.6, on macOS 11.2.2)

**Comment by DanTup** [comment]
This happens because the "Restart Analysis Server" command is really "Reload the Dart extension". It throws away all state and rebuilds it. This includes the state of running debug sessions, and therefore we lose track of whether they support hot-reload or not.

The "Restart Analysis Server" command is not intended for frequent use, it's really there as a fallback for when you've hit some significant bug that's broken the server to avoid using VS Code's **Reload Window** command (which is a little more expensive since it restarts all extensions and the extension host).

As such I'm not sure it's really worth trying to handle this. I'd rather eliminate the reason for needing to use the command in the first place. Do you know why you need to use it frequently? I notice you're on Flutter v2.0.6 - there is an issue with circular symlinks in that version that's solved in v2.2, although there's another issue that might cause analyzer issues that will hopefully be hotfixed (see https://github.com/dart-lang/sdk/issues/46249).

To avoid this feeling so much like a bug, we could rename the command to "Restart Analysis Server / Dart Extension" and have it terminate the debug sessions when run. I'm not sure if that's really better though.
