### ISSUE TITLE
Intellisense adding unnecessary snippet on existing parentheses

### ISSUE THREAD

**Issue by DwiYI** [Dart-Code/Dart-Code#3418]
In image below, '(request)' snippet added when parentheses already there,
I feel it behaves not like this before,
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/19425248/122625768-ff4ddd00-d0d0-11eb-8010-ae8f4da953bb.gif)

i would love to see like this
(this picture in a different language)
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/19425248/122625746-e7765900-d0d0-11eb-9270-2f19e62885fc.gif)

**Comment by DanTup** [comment]
Thanks for the report! This was fixed by https://github.com/dart-lang/sdk/commit/8f2c0e9bb8076225923e86c19fbdf4117dc5d0bb in the Dart SDK (raised in https://github.com/Dart-Code/Dart-Code/issues/3303) but that change has not made it into a stable SDK release yet (it should be in dev builds though).

If you're on the stable channels, you'll get the fix in the next (non-hotfix) SDK release.
