### ISSUE TITLE
Cannot activate Devtools if your PC's username has a space in between

### ISSUE THREAD

**Issue by MBCX** [Dart-Code/Dart-Code#3435]
**Describe the bug**
If you have a space in your PC's username (Like "User Name"), if you trying to activate Devtools via CMD, it gives you a "Invalid radix-10 number (at character 1)" error that doesn't let it activate.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Control Panel, and add a space to your PC's username.
2. Go to CMD.
3. Go to where the "dart-sdk\bin" directory is.
4. Try to deactivate and activate Devtools using the pub commands.

**Expected behaviour**
Even if you have a space in your PC's username, that should not stop Devtools to activate.

**Screenshots**
![CMD screenshot](https://user-images.githubusercontent.com/63003002/123651529-8bf74a00-d7f9-11eb-9651-76f1eb198644.PNG)

**Versions (please complete the following information):**
 - VS Code (version 1.57.1):
 - Dart version 2.14.0 (build 2.14.0-250.0.dev):
 - Dart version (2.14.0) / Flutter 2.3.0-17.0.pre.531 (channel master):

**Comment by DanTup** [comment]
The screenshot here shows activating from the terminal, so I don't think this can be related to the VS Code extension. I'm not certain where it is failing though - I would recommend filing an issue at https://github.com/dart-lang/pub initially, and if turns out to be somewhere else (like the SDK) hopefully someone there can give some pointers.

Thanks!

**Comment by MBCX** [comment]
OK, thanks.
