### ISSUE TITLE
Organize Imports sorts `./` before `../`and `../aaa.bbb/` above `../aaa/`

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3453]
**Describe the bug**

After using command `Organize Imports`, `../../` is before `../`, why `./` is before `../../` ? Should not `./` is in the last ?

![image](https://user-images.githubusercontent.com/41773861/124218277-861ca400-db2c-11eb-9fb7-e554d94ee070.png)

I think the right result should be following:

![image](https://user-images.githubusercontent.com/41773861/124218584-165ae900-db2d-11eb-9df3-53c451b37f3f.png)

**Versions (please complete the following information):**
 - VS Code version:1.58.0
 - Dart extension version:v3.24.0
 - Dart/Flutter SDK version: v2.2.2

**Comment by DanTup** [comment]
@tjx666 is there a reason you're prefixing the URIs with `./`? I think if you remove the `./` it'll sort as you'd like without changing anything else.

@bwilkerson @scheglov I think this happens because the sorting splits the URI into two parts (around the first slash):

https://github.com/dart-lang/sdk/blob/82ea8416ed2a22e40c5c67252cb37bebec3a57e8/pkg/analysis_server/lib/src/services/correction/organize_imports.dart#L336-L353

This means URIs starting `./` and `../` are sorted differently to if they were just sorted by the exact strings themselves:

```dart
(['.', '..', './', '../']..sort()).forEach(print);
```

```
.
..
../
./
```

I'm not certain if the splitting was specifically to do this, or something else (so I'm not sure if this is an accidental bug or the intended behaviour). Do either of you know/remember?

**Comment by bwilkerson** [comment]
The behavior around `.` and `..` is probably accidental; I don't remember any intentional decision related to them. I don't remember even discussing `.`; we probably assumed that URIs would be normalized.

The splitting, however, was intentional. The sorting doesn't work well without the splitting when there are package names containing dots. It probably also doesn't work well when there are directory names containing dots, so the better solution is probably to split the whole path and compare component by component with some special handling for `.` and `..`.

**Comment by tjx666** [comment]
I prefix the `./` because I usually use like that in other language.  Seems that behavior is because:

![image](https://user-images.githubusercontent.com/41773861/124354792-5e1e6500-dc40-11eb-8f34-b2d49bd38ee0.png)

**Comment by DanTup** [comment]
> The sorting doesn't work well without the splitting when there are package names containing dots

Ah, I understand now.

I made a change that I think addresses this, but it raises some questions:

1. This will affect existing code (it re-sorts things in the analysis server itself depending on the answer to _3_) - is that considered a breaking change and if so does it need announcing in advance?
2. Do we need to make some similar change in the linter? (I noticed some related discussion in https://github.com/dart-lang/linter/pull/2688 @pq)
3. How would we prefer this to be sorted?
    ````
    import 'package:analysis_server/src/services/correction/fix.dart';
    import 'package:analysis_server/src/services/correction/fix/dart/top_level_declarations.dart';
    ```

Before my change, it was sorted like that (because a pure text sort on the path is that), but with my change `"fix"` comes before "fix.dart" (which is exactly what we wanted for folders). Do we expect this, or should we special case the last segment to always be compared against a last segment rather than the segment with the same index?

My attempted change (which currently fails the verify_sorted test because of _3_ above, but passes the new/amended tests) currently looks like this:

https://github.com/DanTup/sdk/commit/5084e5575bc1c8237b7c3bad2f270970c9a08905

**Comment by bwilkerson** [comment]
> 1. This will affect existing code (it re-sorts things in the analysis server itself depending on the answer to 3) - is that considered a breaking change and if so does it need announcing in advance?

It will potentially be a breaking change in any code base that enforces a lint related to the order of imports (such as `directives_ordering`). Whether it requires an announcement I can't answer. @devoncarew is out this week, but he's who I would normally ask.

> 2. Do we need to make some similar change in the linter?

Yes, the lint rule and this operation need to match. We probably need to update the lint to use the operation (guaranteeing that they'll always be in sync) before we change the order of the sort.

> 3. How would we prefer this to be sorted?

Personally I think the way your change works is the desired behavior. I'd rather see us comparing corresponding components than do some last-to-last work-around to preserve the current behavior. The last-to-last has some very unfortunate implications. Consider for example:
```
import 'package:p/x/a.dart';
import 'package:p/x/y/z/b.dart';
import 'package:p/x/c.dart';
import 'package:p/x/y/z/d.dart';
```
I think we want a sort order that will guarantee that all of the files in a given directory will always be contiguous.

**Comment by pq** [comment]
> It will potentially be a breaking change in any code base that enforces a lint related to the order of imports 

Having been through this recently (https://github.com/dart-lang/linter/issues/2609 is only the tip of the iceberg), I think for practical reasons we want to tread very lightly and assess impact before we push on.  (I don't object to the fix, just want to weigh the cost.)  (fyi @davidmorgan.)


> We probably need to update the lint to use the operation (guaranteeing that they'll always be in sync) before we change the order of the sort.

I'm in favor of this.  Maybe the easiest thing would be to pull that bit into analyzer so we can consume it in the linter and server?

**Comment by DanTup** [comment]
> I think for practical reasons we want to tread very lightly and assess impact before we push on. (I don't object to the fix, just want to weigh the cost.)

Yeah, it does seem like the impact may be bigger than I expected given the fairly minor issue intended to fix. I'm not sure I'm best placed to weight that up though and it sounds like you have experience meddling here so I'm happy to defer to you 😄 

(I'm happy to try and makes the changes if deemed worth making though).

**Comment by davidmorgan** [comment]
My two cents: it probably makes sense to aim for exactly zero or one changes to the analyzer sort order ;) while keeping in sync with the linter. By that I mean: I'm not 100% sure it's worth a "breaking" change, but if it is, then we should also do all other breaking changes we can come up with.

Thanks.

**Comment by DanTup** [comment]
I've opened this to the SDK repo since that seems like the proper place for a discussion about the trade-off for fixing this. I've tried to include the important info from this thread, but if I've missed anything, feel free to add to it:

https://github.com/dart-lang/sdk/issues/46632
