### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by athapong** [Dart-Code/Dart-Code#3480]
[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/6835505/Dart-Code.dart-code-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.24.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\athap\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️c:\Users\athap\AppData\Local\Temp\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!

**Comment by athapong** [comment]
Yes, file already attached in early post

**Comment by DanTup** [comment]
Apologies - I missed that. I'll take a look, thanks!

**Comment by DanTup** [comment]
It looks like the visible text editors kept changing while this happened, but it's not clear why. However, the code this occurred in is old code that will soon be removed as part of the migration to LSP.

Can you try enabling LSP with the `dart.previewLsp` setting in VS Code? This will force you on to LSP today (otherwise, it will happen automatically with the next release of the extension, where it will be the default for everybody).

You can check you're in LSP mode by hovering over the Dart/Flutter version number in the status bar (if it says DAS, that is not LSP mode):

<img width="175" alt="Screenshot 2021-07-19 at 14 52 19" src="https://user-images.githubusercontent.com/1078012/126170821-d1fd4835-ed6e-4dfa-94ae-f144063b45df.png">

If you still see issues like this when using LSP mode, please let me know (or file a new issue with the profile trace). Thanks!

**Comment by athapong** [comment]
The issue has gone after enabling LSP in VS Code :)

![image](https://user-images.githubusercontent.com/3634696/126251095-2b878f49-1dd4-4a7f-ab25-f8bebca6d7e0.png)

I greatly appreciate it. Thanks!!

**Comment by DanTup** [comment]
Great! Thanks for confirming :-)
