### ISSUE TITLE
Automatically import does not work for the dart package which is a transitive dependency

### ISSUE THREAD

**Issue by wtus** [Dart-Code/Dart-Code#3485]
facing the [same ](https://github.com/flutter/flutter/issues/57193) problem 

Problem
'->' means ‘depend on', A,B,C all are the dart package.

dependency case: App -> A, A -> B, B->C

When I developed in App module, I found the IDE doesn't auto import the classes in B or C, but the classes in A is ok. If I let App depend on B immediately, then auto import B is ok.

I tried on Android Studio & VS Code.

---------

λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale zh-CN)[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code, 64-bit edition (version 1.58.2)
[√] Connected device (4 available)

! Doctor found issues in 2 categories.

**Comment by wtus** [comment]
![1.gif](http://ww1.sinaimg.cn/large/006rV8gJgy1gsokq6eoykg30qo0nghdu.gif)

**Comment by wtus** [comment]
![1.gif](http://ww1.sinaimg.cn/large/006rV8gJgy1gsokq6eoykg30qo0nghdu.gif)

**Comment by DanTup** [comment]
This is expected behaviour. It's discouraged to rely on transitive dependencies because packages may change them (or the version they use) and not consider that a breaking change. If something is a dependency, it should be listed explicitly in your pubspec:

https://github.com/dart-lang/linter/issues/29#issuecomment-529609734

There's also now a lint you can enable to ensure you don't do this accidentally:

https://github.com/dart-lang/linter/pull/2659

Hope this makes sense!
