### ISSUE TITLE
Workspace folders ignoring nested `.vscode/settings.json`

### ISSUE THREAD

**Issue by matuella** [Dart-Code/Dart-Code#3489]
**Describe the bug**
Whenever I save a dart file that is inside a workspace folder, it does not respect the local `.vscode/settings.json` overriding properties, like `dart.lineLength` or `dart.extensionLogFile`.

**To Reproduce**
I've created an [example repository](https://github.com/matuella/dart-vscode-workspace) for this.

You can straight open the workspace and save the `test/lib/test.dart` file. You'll see that it doesn't respect that particular folder's `dart.lineLength` of 120 (if your global configuration is set to `80`, as an example).

**Expected behavior**
In this particular case, I expected that `lineLength` to respect the value of `120` characters per line, instead of using my default values - from the extension itself.

The same occurs to any other property of the `settings.json`, like `dart.extensionLogFile`. You can open the individual folder (`/test`) and see that it correctly respects the overridden `settings.json`, though not when opened through the workspace.

**Screenshots**
N/A.

**Versions (please complete the following information):**
 - VS Code version: 1.58.2
 - Dart extension version: v3.24.2
 - Dart/Flutter SDK version: 2.13.4 / 2.2.3

**Comment by DanTup** [comment]
For settings like `dart.extensionLogFile`, this is expected. These can only be set at the workspace level, so when you open a `.code-workspace`, the settings will be read from the `.code-workspace` file and not from the local `.vscode/settings.json` (this is because you could have multiple folders with their own `.vscode/settings.json`, but these settings can only have one value per-workspace).

Some other settings like `dart.lineLength` _should_ be supported per-project and that has been addressed in #3124 - although since it's an SDK fix (for LSP, this is handled on the server) it won't show up until a future Dart/Flutter SDK release.

Hope this makes sense!

**Comment by matuella** [comment]
Sure it does. Thanks a lot @DanTup, will keep an eye on this next Flutter release.
