### ISSUE TITLE
Create page snippet for navigation API

### ISSUE THREAD

**Issue by sno2** [Dart-Code/Dart-Code#3493]
**Is your feature request related to a problem? Please describe.**
I've been working with Flutter 2.0 and the navigator API and I think it would be really great if we could have a snippet for creating pages.  This will definitely reduce waste of time by people manually typing out a page widget every time they need to create a new page.

**Describe the solution you'd like**
I would like a snippet that can create a page widget setup.

**Describe alternatives you've considered**
I have created my own snippets for doing this as shown in my PR.

**Comment by sno2** [comment]
I have a possible solution at #3492

**Comment by DanTup** [comment]
See discussion in https://github.com/Dart-Code/Dart-Code/pull/3492#issuecomment-886593105. The goal is to reduce/remove the snippets from the extension where because they're not context-sensitive and show up in the wrong places frequently (see https://github.com/Dart-Code/Dart-Code/issues/2059). Instead, I'd like them to come from the language server which can provide snippets only in the correct contexts (https://github.com/dart-lang/sdk/issues/37831).

In the meantime, these could be included in a snippets extension or in local snippets. Thanks!
