### ISSUE TITLE
Running flutter apps in vscode using dart-code extensions

### ISSUE THREAD

**Issue by surya0180** [Dart-Code/Dart-Code#3498]
I recently observed a bug in vscode while working with flutter.

When I use vscode run button to run my flutter app, the root widget is building twice, which is completely against the workflow.

When i run the same code using terminal commands [ flutter run ] everything goes fine with no extra builds.

Please solve this issue

**Comment by DanTup** [comment]
Thanks for the report! I can reproduce this on the released version, but not in the latest code. I believe it was fixed by e6a7149c which no longer sends service extension values at startup that have not been overridden (it seems like they could trigger rebuilds).

So this will be fixed in the next release, but if you need the fix sooner you could try use [a nightly build](https://dartcode.org/docs/installing-a-preview-release/). Sorry for the inconvenience!
