### ISSUE TITLE
Constantly need to restart Dart analysis server when using WSL

### ISSUE THREAD

**Issue by jimmyff** [Dart-Code/Dart-Code#3508]
I have certaitain projects that I need to build in Linux so I use WSL2.

I find that I contstnatly need to restart the Dart analysis server in order for changes to take effect. For instance if I copy a project folder and open it, I have thousands of errors as I need to run pub get, after running this command I then need to restart the analysis server so VS Code will realise the change and remove all the errors.

I've been living with this workflow for about a year and just wondered if there is a way to fix this?

 - VS Code version:
```
Version: 1.58.2 (system setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```
 - Dart extension version:
```
v3.24.2
```
 - Dart/Flutter SDK version:
```
Dart SDK version: 2.12.1 (stable) (Unknown timestamp) on "linux_x64"
```

**Comment by 2shrestha22** [comment]
Is your problem same as this? https://github.com/Dart-Code/Dart-Code/issues/3440

**Comment by DanTup** [comment]
I was wondering the same. I haven't had chance to try to repro this yet as my Windows machine is a bit messed up, but I'm hoping to address that this week and will post back.

**Comment by jimmyff** [comment]
> Is your problem same as this? #3440

It could be, but I don't have this issue when on Windows (without WSL) or on MacOS. It seems specific to WSL workspaces.

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this - I added some `import`s for new packages then added the to `pubspec.yaml` and the errors quickly go away after `pub get` completes when I save the file.

Would you be able to enable the server [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) and reproduce this? Note: The log will include parts of your source files so please reproduce using a small sample project.

Could you also confirm:

- whether the files are stored in the Linux or Windows file systems
- how large the project is you see this on (if it doesn't repro on a small one)
- which Linux distro you're using (I tested with Ubuntu)

> > Is your problem same as this? #3440
>
> It could be, but I don't have this issue when on Windows (without WSL) or on MacOS. It seems specific to WSL workspaces.

The last comments in that issue suggest it could be Linux-specific, so that might explain why you only see it in WSL (although again, I can't repro that in WSL - I don't have a full Linux install to hand to test there).

**Comment by DanTup** [comment]
I suspect this may be related to #3440 and/or #3438.
