### ISSUE TITLE
Syntax highlighting inconsistency

### ISSUE THREAD

**Issue by SuporteSysrs01** [Dart-Code/Dart-Code#3510]
**Describe the bug**
After the update, some functions, like `EdgeInsets.all` got a green class-like highlighting color, which is different from the one in intellisense.

I also notice that, when I launch VSCode, for a second, the syntax highlighting is yellow like before.

**To Reproduce**
1. Type `EdgeInsets.all`. Notice the `all` is green just like `EdgeInsets`.
2. Hover over. Notice `all` in the popup is yellow, just like before the update.

**Expected behavior**
Both yellow (which I think was better) or both green.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/87761804/127919619-98193f9d-16fd-4a9a-b4bf-47af96edc442.png)

**Versions (please complete the following information):**
 - VS Code version: 1.57.1
 - Dart extension version: 3.25.0
 - Dart/Flutter SDK version: Dart 2.13.4/Flutter 2.2.3

**Comment by DanTup** [comment]
This specific issue is covered by #3374 which was fixed in https://github.com/dart-lang/sdk/commit/10b83a48827429f30f8848e19ba46e528128818a (since the fix is in the SDK, it will show up in a future SDK release rather than a Dart-Code release).

That said, there will still be some differences between the editor and the tooltips because we're now using semantic highlighting in the editor (this should be more accurate), whereas the tooltips are only using a simple textmate grammar (which is regex-based). Hopefully the differences won't be significant, but there are some places where the textmate grammar falls down (for example if you name a method `set` or `get` it will be coloured like a keyword, whereas the semantic highlighting will colour them accurately).

Hope this makes sense!
