### ISSUE TITLE
"add type annotation" grabs src reference instead of public reference

### ISSUE THREAD

**Issue by gaaclarke** [Dart-Code/Dart-Code#3513]
I was getting an `always_specify_types` linter error in the following code:

```dart
import 'package:analyzer/dart/ast/ast.dart' as dart_ast;
...
    final dart_ast.TypeName typeName = parameter.childEntities.firstWhere(
        (e) =>  // <-- Here is the always_specify_types error
            e is dart_ast.TypeName) as dart_ast.TypeName;
```

I hit the "add type annotation" "quick fix" and it imported `import 'package:_fe_analyzer_shared/src/base/syntactic_entity.dart';`  which is a linter error since it is in src.  I expected it to grab `import 'package:analyzer/dart/ast/syntactic_entity.dart';` since that import wouldn't create another linter error.

Here is the source code for `package:analyzer/dart/ast/syntactic_entity.dart`:
```dart
export 'package:_fe_analyzer_shared/src/base/syntactic_entity.dart'
    show SyntacticEntity;
```

**Comment by DanTup** [comment]
Thanks for the report! This code is generated by the Dart analysis server in the SDK so should be raised at https://github.com/dart-lang/sdk. Unfortunately it's not code I'm familiar with so I'm unsure how complex the fix is (I guess it's just looking for where the type is declared, and not at any libraries that export it - of which I guess there could be multiple and it may need to somehow rank them).

If you file an SDK issue, please post the link back here for anyone that stumbles across this issue with the same problem. Thanks!
