### ISSUE TITLE
Vscode expand selection on dart/flutter code is kinda messed up

### ISSUE THREAD

**Issue by lucasriondel** [Dart-Code/Dart-Code#3521]
https://user-images.githubusercontent.com/7773454/128728879-ec554f65-173d-4216-a02e-e9bceb0da1f0.mov

Expanding or shrinking selection in vscode on dart code kinda feels weird sometimes, when you come from javascript/typescript code. You can see it on the linked video, when setting the cursor between the singlequotes and try to expand selection, it does not select the singlequotes, it does not select the ternary condition, it selects the whole arguments of the Widget. 

https://user-images.githubusercontent.com/7773454/128729730-c4632c98-ad5c-41a7-92c2-8328ba6c0bb0.mov

Also, it's never possible to select a widget and its arguments: in the video above, I cannot select the `Company(...)`, it automatically selects the `return` with it. 

Is there a way to fix this ? 

Also, I wasn't able to find the best place for this request...

**Comment by DanTup** [comment]
Here or dart-lang/sdk is fine for this. The new implementation for this lives in the SDK now (as part of the LSP protocol of the language server) but it's not always obvious what's implemented here and what's in the SDK so either place is fine (we can move things around as required - although I tend to contribute a lot of the LSP work anyway).

This issue has actually been fixed as part of #3332 but because it's in the SDK, you wont have the fix until a future SDK release (unless you're using a dev build or something). On the latest code this looks like:

![Aug-09-2021 16-18-33](https://user-images.githubusercontent.com/1078012/128731059-1312a480-bf4b-4408-9069-2eb1cffc50b6.gif)

So as long as you haven't disabled LSP (with the `dart.previewLsp: false` setting), it should just start working after a future SDK release when you update :-)

**Comment by lucasriondel** [comment]
@DanTup awesome ! ❤️ 
thanks a lot for the fast answer.
