### ISSUE TITLE
Emulator command is not found

### ISSUE THREAD

**Issue by amalalzuhair** [Dart-Code/Dart-Code#3526]
When I try to run the android emulator on visual studio 2019 editor for a react native app I receive an error after running the (emulator -avd pixel_2_api_29) command

This is the error that I'm receiving:
emulator : The term 'emulator' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

![image](https://user-images.githubusercontent.com/38395257/128992934-c304a355-097d-4a38-96c9-cc111b1e0960.png)

 - VS Code version: 2019

**Comment by DanTup** [comment]
This isn't something related to the VS Code extensions since they have no influence over the terminal. The issue here is that the `emulator` command isn't in your `PATH` environment variable so you can't execute it directly.

That said, you can see and launch your emulators directly through the VS Code extension by clicking on the device select in the bottom right status bar and then selecting an emulator to launch:

https://dartcode.org/releases/v2-13/#emulator-launching

Hope this helps!
