### ISSUE TITLE
(LSP) Dart function coloring issue

### ISSUE THREAD

**Issue by iulian0512** [Dart-Code/Dart-Code#3535]
**Describe the bug**
When using custom code coloring settings (see my gist below) in LSP mode the code coloring does not work correctly. 
See the below image illustrating differences between DAS and LSP.
![lspissue](https://user-images.githubusercontent.com/16035099/130449424-c0bd735f-de6d-4343-8ade-936ba7ad2998.png)

**To Reproduce**
1. apply my  "editor.tokenColorCustomizations" setting from https://gist.github.com/iulian0512/b3f7e1524da10f81061fa9de932c60e8 or load my custom coloring scheme from https://gist.github.com/iulian0512/ac8a8f74e2f8485f8e17c58e149dd457
3. turn on LSP (reload vscode)
2. define a factory constructor on a class

**Expected behavior**
Follow my code coloring settings.

**Versions (please complete the following information):**
 - VS Code version:
        Version: 1.59.1 (user setup)
        Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
        Date: 2021-08-19T11:56:46.957Z (4 days ago)
        Electron: 13.1.7
        Chrome: 91.0.4472.124
        Node.js: 14.16.0
        V8: 9.1.269.36-electron.0
        OS: Windows_NT x64 10.0.19043

 - Dart code extension version:
        v3.25.1
 - Dart/Flutter SDK version:
        Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
        Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "windows_x64"

**Comment by DanTup** [comment]
Thanks for the report! This was fixed by https://github.com/dart-lang/sdk/commit/10b83a48827429f30f8848e19ba46e528128818a but since the change is in the server, it will show up in a future SDK release rather than a Dart-Code release.

When running from a nightly build/master, the constructors are tagged like this:

<img width="747" alt="Screenshot 2021-08-23 at 14 25 31" src="https://user-images.githubusercontent.com/1078012/130455460-7576b77d-0b9a-42c4-ad5b-e6f88103f60e.png">

The reason for the strikeout in your screenshot is that the colour is being overridden by the semantic tokens.
