### ISSUE TITLE
Fix All command doesn't show on the command palette, fixAll doesn't work

### ISSUE THREAD

**Issue by sgehrman** [Dart-Code/Dart-Code#3558]
I've been waiting for the fixAll command for years, but it doesn't work for me.

I'm on Linux if that matters.  I have the latest dart/flutter.  I was on dev channel, also tried stable.

Dart Fix doesn't show in in the command pallette.

[✓] Flutter (Channel stable, 2.5.0, on Debian GNU/Linux 10 (buster) 4.19.0-17-amd64, locale en_US.UTF-8)
    • Flutter version 2.5.0 at /home/steve/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (4 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/steve/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.15.2
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 4.2)
    • Android Studio at /home/steve/android-studio
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.60.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 10 (buster) 4.19.0-17-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

• No issues found!

**Comment by sgehrman** [comment]
I added this, but fixAll doesn't work on save.

{
  "editor.codeActionsOnSave": [
    "source.fixAll",
    "source.organizeImports",
  ],
}

Organize imports works fine.

**Comment by ManuLpz4** [comment]
@sgehrman it doesnt seem to work fine :/
I cant separate the external packages from the flutter sdk packages

<img width="422" alt="Captura de Pantalla 2021-09-11 a la(s) 17 20 40" src="https://user-images.githubusercontent.com/17878459/132960651-c09dd34b-89b4-4c12-aed6-6d4983441928.png">

**Comment by sgehrman** [comment]
@ManuLpz4 Yeah, I noticed that too.

**Comment by sgehrman** [comment]
I fixed it.  I don't have FLUTTER_ROOT set and I didn't have   "dart.flutterSdkPath": "/path/to/flutter" set.  I set the sdkpath and it works now.  Strange that everything else has been working fine.

**Comment by DanTup** [comment]
> I fixed it. I don't have FLUTTER_ROOT set and I didn't have "dart.flutterSdkPath": "/path/to/flutter" set. I set the sdkpath and it works now. Strange that everything else has been working fine.

This shouldn't matter unless we were picking up an older version of Flutter from your `PATH`. You can see the Flutter version in the bottom right corner in the status bar. If you can reproduce this by removing that setting/env var but the status bar is showing the latest version, then I'd be interested in a log file.

If it does show an old version on the status bar, when you can use the **Dart: Open Extension Log** command to see where it's being found and remove it.

> I cant separate the external packages from the flutter sdk packages

This sounds unrelated to the fix all command but as far as I know, the import sorting in Dart does not distinguish between Flutter and non-Flutter packages, it always sort by Dart SDK (`dart:`), then packages (`package:`) then paths. This is something controlled by the SDK - there's a related issue at https://github.com/dart-lang/sdk/issues/46597 but it sounds like the behaviour is based on the style guide (so the style guide might be the place to start a discussion about this). Otherwise, you can ofc remove `"source.organizeImports",` from your `"editor.codeActionsOnSave"` setting and just sort them manually.
