### ISSUE TITLE
Keyword token color customization isn't applied for default dark+ theme

### ISSUE THREAD

**Issue by robertpiosik** [Dart-Code/Dart-Code#3563]
**Describe the bug**
Keyword token color customization isn't applied for default dark+ theme

**To Reproduce**
1. Add `editor.tokenColorCustomizations` for default theme `Default Dark+` on keyword tokens

**Expected behavior**
Defined color should be applied as it is in case of non default themes.

**Versions (please complete the following information):**
 - VS Code version: 1.60.0
 - Dart extension version: v3.26.0
 - Dart/Flutter SDK version: 2.5.0

**Comment by DanTup** [comment]
This is because Semantic Tokens are enabled which override the basic token highlighting. You'd need to apply your customisation to the semantic tokens instead:

```js
"editor.semanticTokenColorCustomizations": {
	"rules": {
		"keyword": "#00ff00"
	}
},
```

You can use VS Code's "Inspect Editor Tokens and Scopes" command to see which customisations are being applied like this:

<img width="1251" alt="Screenshot 2021-09-15 at 14 35 34" src="https://user-images.githubusercontent.com/1078012/133443719-8407558e-4ca5-4a30-aecc-dfdc602ef1d9.png">

Let me know if this isn't clear or you have any issues making it work. Thanks!

**Comment by robertpiosik** [comment]
Thanks Danny!
