### ISSUE TITLE
Inspected variable not keeping the old variable values until expanded in VSCode

### ISSUE THREAD

**Issue by pinguluk** [Dart-Code/Dart-Code#3570]
## Steps to Reproduce

1. Have an object (a list for example with 10 items)
2. Use ```inspect(list)```
3. Remove some items from the list (6 for example)
4. Expand the ```inspected variable``` from the VSCode

**Expected results:**
```
<inspected variable>
  ...
  _value:List (10 items)
  ...
  length: 10
  ...
```

**Actual results:**
```
<inspected variable>
  ...
  _value:List (4 items)
  ...
  length: 4
  ...
```

After expanding the inspected variable and you remove another items from the list, the expanded inspected variable is remaining the same (even if you shrink back and expand again the inspected variable in the debug console).

If you do ```inspect(list.length)``` instead before you remove any items and then you remove some, you'll see that the list.length is keeping the original value, which is correct.

Basically if you inspect an **object**, the data from it will be reflected and keeped in the debug console, **only** when you expand it for the first time. Until you expand for the first time, the _inspected variable_ (object) will keep changing, until you expand it at least once.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale ro-RO)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pinguluk\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\pinguluk\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\pinguluk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

</details>

**Versions (please complete the following information):**
 - VS Code version: 1.60.1
 - Dart extension version: v3.26.0
 - Dart/Flutter SDK version: 2.13.4 and 2.2.3

**Comment by DanTup** [comment]
Calling `inspect` is essentially the same as adding the item to the Watch window. We just keep a reference to the value you inspected, and as you expand, we will fetch the next level of data through the live VM. This means you'll always get the "current" values of the object.

The reason that `inspect(list.length)` seems to work differently, is that the length is being resolved at the time that `inspect` is called, so you're not really inspecting "the length of the list" but rather inspecting the number that `.length` returned before `inspect` was called.

It's not really possible to "snapshot" an object when you inspect it because the VM may still be running (if you're not paused) and the values may be changing. It could also be very expensive to walk the entire tree of objects/getters (or there could be cycles). By expanding manually, these issues are avoided.

If you need to snapshot data for inspecting/debugging, it would be better to use something like a `toJson()` (`inspect(myFoo.toJson()`) method to make your own snapshot of the data that is limited in scope to exactly what you want to see (and since it's flattened into nested Maps, their values won't change after inspecting), or pause the debugger when inspecting and expand the object before allowing the code to continue.

Hope this makes sense!

**Comment by DanTup** [comment]
One possible change that could be made is to remove the `<inspected variable>` wrapper. This would result in the top-level being evaluated immediately:

![Screenshot 2021-09-29 at 11 48 28](https://user-images.githubusercontent.com/1078012/135254504-22d2e1e3-44d9-4a96-b706-438cc576205a.png)

This works a little better if you're inspecting a list, however it makes it lots less clear where the boundaries are (eg. if I didn't inspect the length, these items would all merge together) and it only affects the top level - if you expand the inner lists, they would still show the "current" values and not the values at inspection time.

**Comment by DanTup** [comment]
I did some testing of the above, but there's no way to group the results up such that it's clear where the start/end of each inspected list is. DAP does have support for groups, but they don't apply to Variables, so they are ignored here.

As a sort-of workaround if you just want to flatten the top level, you can add `.toList()` when inspecting lists, and that will make a copy of the list so the inspected variable only contains those contents. Of course, it will still show the _current_ state of any objects inside it, but it might be closer to what you'd like:

![Screenshot 2021-09-29 at 12 02 28](https://user-images.githubusercontent.com/1078012/135256384-6a10ee60-8083-407d-b2c8-a60097864f02.png)
