### ISSUE TITLE
No Flutter snippets in the VS code extension

### ISSUE THREAD

**Issue by ajsb85** [Dart-Code/Dart-Code#3573]
Dear @DanTup 

The documentation explain the usage of the snippets.
But no source code nor snippets in the VS code extension.

VS Code v3.26.0

https://flutter.dev/docs/development/tools/vs-code#snippets

**Comment by DanTup** [comment]
Can you confirm which version of the Dart and Flutter extensions you have installed, and check that this setting is enabled?

<img width="705" alt="Screenshot 2021-09-21 at 09 28 21" src="https://user-images.githubusercontent.com/1078012/134138038-c7aa6a3b-83f6-4312-9c30-7e11199ef32f.png">

Can you also clarify exactly where you're not seeing the snippets - do you mean in the code completion in the editor?

<img width="684" alt="Screenshot 2021-09-21 at 09 29 41" src="https://user-images.githubusercontent.com/1078012/134138276-605fcac7-dd72-47f7-9d41-631e64159d35.png">

**Comment by ajsb85** [comment]
![image](https://user-images.githubusercontent.com/663460/134141103-378e46d5-5b96-4d01-8ca1-e2768a297550.png)

If I follow the official VS Code Flutter extension it does not show the snippet.
And I searched in the source code of the extension and there are not prefix nor snippets related to the documentation.

![image](https://user-images.githubusercontent.com/663460/134141399-e7dfa049-a82d-4d97-94af-a65019757475.png)

**Comment by DanTup** [comment]
The snippets are in the source code here:

https://github.com/Dart-Code/Dart-Code/blob/master/snippets/flutter.json

I think the problem is that the file you have open is Untitled-1 and has not been saved, but the Snippets only show for `file://` editors. Please try saving the file (and ensure you have opened the project folder in VS Code - loose open files are not fully supported) and try again.
