### ISSUE TITLE
Better no folder debugging

### ISSUE THREAD

**Issue by isidorn** [Dart-Code/Dart-Code#3576]
Hi VS Code PM here 👋 

1. Purple no folder VS Code -> create a new `dart` file
2. Press `F5` -> notice how we offer the user to download your extension 👏 
3. Now the user presses `F5` again and wants to debug, but nothing happens since `dart` is not supporting no folder debugging

Easiest to do this is to have a dynamic `resolveDebugConfiguartion` that will provide a launch configuration on the fly. [Example](https://github.com/microsoft/vscode-mock-debug/blob/main/src/activateMockDebug.ts#L161)

Apart from that consider contributing to the Editor title area menu, such that a Play button would appear in the Editor Title area (picture below). Example how to do this https://github.com/microsoft/vscode-mock-debug/blob/main/package.json#L80

I think both of these are super important and would really love that we improve this experience 💯  
I see how you are currently relying on being in a folder and generating a `launch.json`, but hopefully we should be able to simplify that even further.

Let me know if I can help somehow. I am also open to a quick 30 min meeting where we can discuss about the new cool VS Code debug features that `dart` could potentially adopt.

fyi @dantup

**Comment by DanTup** [comment]
Thanks for the ping! I think we already do much of the above, although there are [some conventions](https://dart.dev/tools/pub/package-layout) in Dart we look for when trying to decide if the current file is runnable (for example whether it's in a `bin`, `lib` folder or `tool` folder).

This is done so if you're in a Flutter project (whose entry point is at `lib/main.dart`) and you press `F5` with another file open (`lib/src/some_implementation_file.dart`) we will still run `lib/main.dart` rather than trying (and failing) to run `lib/src/some_implementation_file.dart`.

There may be some room to improve things though, such as treating all files as runnable when there's no open workspace, or the open folder doesn't contain a pubspec, or the file is in the root. I'll try some of these out and ensure they don't conflict with any existing behaviour that tries to locate the right entry point.

> I am also open to a quick 30 min meeting where we can discuss about the new cool VS Code debug features that `dart` could potentially adopt.

Sure, if there are new things I might not be aware of I'm interested to hear. I'm on UK time and my calendar is usually fairly clear. You can email me at/send invites to danny@codedconsultants.com.

**Comment by DanTup** [comment]
I added some special cases for no-folder workspace now, so that all Dart files in a no-folder workspace are considered runnable (that is, the Run/Debug button will now show, and `resolveDebugConfiguration` will treat them as an entry file rather than asking the user to explicitly list one in a `launch.json`).

Debugging without a folder open won't always give the best experience (for example if `main.dart` imports `foo.dart` and you press `F5` with `foo.dart` open it will run that, but perhaps you wanted `main.dart`) and the recommendation is to follow the normal Pub layout (eg. have an open folder with your entry point at `bin/main.dart` or `lib/main.dart`). However, this definitely simplifies getting new users to a run/debug session without needing to initially learn that.

Thanks!

**Comment by isidorn** [comment]
Awesome, thanks a lot for this fast improvement 👏 
As for the meeting I will follow up in email.
