### ISSUE TITLE
Ui Guides overlap indent guides

### ISSUE THREAD

**Issue by robertpiosik** [Dart-Code/Dart-Code#3585]
**Describe the bug**
Ui Guides overlap indent guides so their usability is vastly decreased.

**Expected behavior**
Ui Guides are one pixel off the way the original guides. It will play nicely with the upcoming feature of adjustable Ui Guies color.

**Screenshots**
![image](https://user-images.githubusercontent.com/7120725/135269444-f26c4b8e-ea88-4708-934b-f51bc456accd.png)

**Comment by DanTup** [comment]
This was intended. When the guides don't overlap, it looks like a bug that they're out of alignment:

![Screenshot 2021-09-29 at 14 02 45](https://user-images.githubusercontent.com/1078012/135273726-470c3e1c-e88c-4740-88cd-6635ffd1103a.png)

Personally I tend to turn off Indent Guides because they're quite busy with 2-space indenting.

The ideal solution would be to be able to render thicker lines over the top so it's more clear where they are. This requires new APIs from VS Code though - I would encourage adding 👍  to https://github.com/microsoft/vscode/issues/73780. Until that issue (or something similar) is available, the UI Guidelines are likely to remain a little quirky (due to the way we have to render them) and behind a preview flag, because I don't really consider them of sufficient quality to ship enabled.

Hope this makes sense! If/when there are better APIs, I'll review how we render these and ensure they work better with the indent guides.

Thanks!

**Comment by robertpiosik** [comment]
It might look broken indeed but after 5 minutes everyone will realize why they are ever so slightly moved :)

Ui guides serve different purpose and the solution is great to still be able to click around and see the code blocks what, when indentation is so tight, is critical, I'm very sure, for many.

**Comment by DanTup** [comment]
Ok, I've updated them to be 2px more to the right (as shown above). If we get better APIs for this we might want to try to do something that doesn't look so messy, but also doesn't obscure them - but that's a future problem.

I'll include this in the upcoming release (although it's not in Beta 2 released yesterday, and there may not be another beta before release).

**Comment by robertpiosik** [comment]
Thank you! I really appreciate this change.

**Comment by robertpiosik** [comment]
The updated Ui Guides feels amazing. Thank you Danny.
![image](https://user-images.githubusercontent.com/7120725/136473157-28c186ac-f44b-4865-8b45-b760d5497984.png)
