### ISSUE TITLE
Add support for Inlay Hints﻿ for (unnamed) parameter names

### ISSUE THREAD

**Issue by 4dfe-9dac** [Dart-Code/Dart-Code#3609]
Hello,
We would all like to see the support for inlay hints.
There isn't much to say here, everything is more or less self explanatory.

**Comment by RedyAu** [comment]
I would like to second this issue, would be very useful. VSCode has an inlay hints setting now; maybe the situation has changed since?
![image](https://user-images.githubusercontent.com/12989935/151815946-b2a518f5-270c-49db-a595-230d12f8a572.png)
Enabling this has no effect for .dart files.

**Comment by DanTup** [comment]
@RedyAu Dart uses LSP, so nothing could be started on this until it's been available in LSP:

https://github.com/microsoft/language-server-protocol/issues/956

**Comment by sanathusk** [comment]
I would love to see the feature implement in vscode.Vscode alreayd supports it for JS &  typescript.

**Comment by DanTup** [comment]
Start working on this at https://dart-review.googlesource.com/c/sdk/+/259181/.

![Sep-14-2022 10-42-24](https://user-images.githubusercontent.com/1078012/190120344-375ca564-9f53-48a4-941c-b45b2aeac166.gif)

It's in the language server, so will become part of a future Dart/Flutter SDK release rather than a Dart-Code release.

**Comment by DanTup** [comment]
Landed in https://github.com/dart-lang/sdk/commit/15dfda917ae15ed40f6f9575625a5b0cf3ec4d0a.
