### ISSUE TITLE
Debug console doesn't show dart:developer log() output when "running" (not "debugging") unit tests

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#3653]
**Describe the bug**

Per #1849 I would expect to have the output from `dart:developer` `log()` to be output to the Debug Console.

**To Reproduce**
I have a unit test with dart:developer logging:
```
import 'package:flutter_test/flutter_test.dart';
import 'dart:developer' as dev;

void main() {
  test('testing something here', () async {
  dev.log("A DEV LOG TEST", name: 'my.test.category');
...
```

and then run tests inside VSC using cmd palette "Dart: Run All Tests"

**Expected behavior**
The log output to appear in the Debug Console window in VSC.

Instead I only see output in the Debug console listing name of each test run with a leading check-mark.

**Screenshots**

I have the setting turned on:
![image](https://user-images.githubusercontent.com/71999/140437563-4bb6bc18-832b-48d5-843b-87eb8b0ec43e.png)

**Versions (please complete the following information):**
 - VS Code version: 1.61.2
 - Dart extension version: 3.28.0
 - Dart/Flutter SDK version: 
 ```
 flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.579, on Ubuntu 21.04 5.11.0-38-generic, locale en_AU.UTF-8)
    • Flutter version 2.6.0-12.0.pre.579 at /home/maks/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4327b15b10 (25 hours ago), 2021-11-03 19:11:31 -0400
    • Engine revision fd0f83359d
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)
 ```

**Comment by DanTup** [comment]
`dart:developer` logging only works when Debugging, not when "Running". This is because we can only receive these logs when connected to the VM Service. This is the same if you use the Run/Debug links above a test - you'll only see the output in debug mode.

If you run the tests in Debug mode (you can use the built-in test commands from VS Code now, the **Dart: Run All Tests** command will eventually go away, as it's superseded by the new VS Code runner) then it should show up:

<img width="397" alt="Screenshot 2021-11-08 at 11 35 12" src="https://user-images.githubusercontent.com/1078012/140735276-6ec17fca-c689-47f6-ab06-b939b16e0f94.png">

Although it's worth noting that in Debug mode, the tests will be slower because we can only run one-file-per-process when debugging (and things are a little slower anyway, just because of the debugger).

Hope this makes sense!
