### ISSUE TITLE
Allow configuration of the tool used to run programs/tests

### ISSUE THREAD

**Issue by alanknight-wk** [Dart-Code/Dart-Code#3656]
**Is your feature request related to a problem? Please describe.**
For web programs, the launch is hard-coded to run using build_runner (I think, it's hard to tell) and tests are hard-coded to run using test. This causes various problems. For example tests that use builders would like to be run using build_runner test. It would be better to use webdev, and then options like --enable-expression-evaluation could be used. Many organizations have other tools they use. For example, we normally use [dart_dev,](https://github.com/workiva/dart_dev) which provides extra options and can be configured to be aware of organization or project-specific extra options, e.g. [webdev_proxy](https://github.com/workiva/webdev_proxy). These issues could be fixed individually, but it can be hard to detect the right options, e.g. [this PR](https://github.com/flutter/devtools/pull/140). This could all be addressed by letting users indicate the tool. Configuration could be made easier by adding pre-defined configurations for the most common options.

**Describe the solution you'd like**
Add a launch.json option like "tool" to indicate the tool to be used. This would probably need to provide some kind of printf-style or $args-style substitution for arguments, because there's not much consistency between how tools that wrap others pass down arguments. e.g. build_runner test uses `--` to indicate the end of build_runner args and the start of test args. dart_dev uses `--build-args=` and `--test-args=.` I'm sure there are other fun variations.

**Describe alternatives you've considered**
The obvious alternative is to handle the normal Dart ecosystem options directly, but this puts more burden on the extension to get the configuration right, and doesn't support custom tools. But it does make the configuration simpler for users.

**Additional context**

**Comment by DanTup** [comment]
The debug adapter is moving into the SDK (see https://github.com/dart-lang/sdk/tree/main/pkg/dds/tool/dap#readme), so supporting this would need to ultimately be done there (and as such, it's probably not worth doing it in the legacy DAP here that will soon be phased out).

The other tools would need to act as drop-in replacements for the commands they're replacing for things to work (spawning the process is only part of the job - they also need to supply the VM Service URI back to us, and in the case of tests, support running with the JSON reporter so we can get the results).

Are you able to provide a small sample project (or instructions for me to create one) and the exact commands you currently need to run so I can do some testing and see if they can be made to do everything required to work with the debug adapters?

**Comment by alanknight-wk** [comment]
I wouldn't expect any of these to affect/be affected by the debug adapter.

Generally, these commands do act as drop-in replacements as far as functionality - as opposed to how they're invoked, which have gratuitous differences. This is because they all pretty much wrap the same underlying thing. So `webdev` wraps `build_runner serve` for apps, `build_runner test` wraps the runner from `test`. With non-Dart team tools that I've encountered, dart_dev just spawns one or the other of those two, and webdev_proxy I think runs a server in front of webdev, but takes all the same arguments. They differ in odd details (e.g. build_runner builds the tests by default using DDC, and test always builds them with dart2js) but that shouldn't affect this. I'm not sure how webdev and build_runner expose the VM Service URI, but I'm pretty sure it's compatible. I see --chrome-debug-port on webdev, but nothing similar on build_runner serve.

For the trivial repo at https://github.com/alanknight-wk/web_tests_with_vscode the commands would be, e.g.

- dart run build_runner test -- -p chrome (and any other test args)
- webdev serve --enable-expression-evaluation (the argument is optional, but it's very convenient for debugging)
- webdev serve -- <build_runner_options>
- webdev_proxy serve -- <webdev-options> -- <build_runner_options>
- dart_dev just spawns a webdev with some extra options, e.g. 
     pub global run webdev serve web:8082 -- --delete-conflicting-outputs
It's controlled by a config file - I added one to that repo.

If you don't want to make it configurable, it would still be better to upgrade them. webdev is better than plain build_runner, and running tests without build_runner makes them not runnable for a significant number of projects.

**Comment by DanTup** [comment]
> I wouldn't expect any of these to affect/be affected by the debug adapter.

The debug adapter is what spawns these tools so this is where the changes need to be to spawn custom tools instead.

> webdev is better than plain build_runner

To be clear - we're already using `webdev serve` to run web apps. Although there's some integration with `build_runner` via Tasks, those are just just simple tasks that start processes in the terminal but have no proper integration (you can't debug/etc. using them and they'll have no interactions with the test runner).

I'm thinking that maybe we need a new field `customTool` that replaces the tool that's usually invoked. The rest can be done with `toolArgs` and `args`. We'd need to define exactly what gets replaced though. For example, for a cli script if you set `customTool` to `dart_wrapper` then we would just replace `dart` with `dart_wrapper`.

However for tests, we'd likely need to replace some arguments too, for example replacing the whole of `dart run test:test` with just `customTool`.

We do already have some similar code that replaces `flutter` for some Bazel workspaces. It might make sense to do these the same way (that's not yet been ported to the new SDK debug adapters, so it may make sense to do so by passing it through as `customTool`.

**Comment by DanTup** [comment]
I think my plan here is going to be to have two fields in `launch.json`:

- `customTool` - the tool to invoke instead of `dart`/`dart run test:test`/`flutter run`/`flutter test`
- `customToolReplacesArgs` - the number of arguments to the tool that should be removed (because the custom tool does not expect them)

This supports the existing Bazel workspace setup without needing very specific code in the debug adapter. For example, passing:

```
"customTool": "my_fake_flutter",
"customToolReplacesArgs": 1,
```

For a Flutter project would result in `my_fake_flutter --machine -t lib/main.dart` being run instead of `flutter run --machine -t lib/main.dart` (the `replacesArgs` value has caused `"run"` to be removed from the tool).

`customToolReplacesArgs` only handles the args that are part of the tool invocation itself (and not things in `toolArgs`). Right now the expectation is that `customTool` is otherwise a drop-in replacement and accepts all the same args we pass to the underlying tool. I don't know if that's going to be good enough for the request here, but it's a start. It may be better to try and make those tools command-line-compatible rather than trying to come up with some elaborate way of rewriting args, but I haven't gotten as far as trying this yet, as my initial goal is to preserve the existing Bazel support through to the SDK DAPs.

**Comment by alanknight-wk** [comment]
I think this could be made to work, though it puts the burden on the person specifying the launch config and would make documenting or providing defaults for those more important.

My biggest question is how people are to know what to do. It seems like to run a program it's always customToolReplacesArgs=1. To run tests in dart it's 2, and to run tests in flutter it's 1. That's assuming that the test:test is not what the other tool expects. Will that just be in documentation somewhere, or is there a way for someone configuring a launch to see what the normal tool/arguments are and/or what it would be in their config?  I didn't see such a thing when trying to figure this out earlier.

So, if I'm understanding this, if I wanted to use build_runner for tests I think I would specify it as
```
"customTool": "dart",  // Or can I just omit that?
"customToolReplacesArgs": 2,
"toolArgs": ["run", "--define=\"DARTARG=SOMETHING\"", "build_runner", "test", "--config=test_config", "--release", "--" "-p=chrome"],
```
and similarly if I wanted to use dart_dev, it would be 
```
"customTool": "dart",  // Or can I just omit that?
"customToolReplacesArgs": 2,
"toolArgs": ["run", "--define=\"DARTARG=SOMETHING\"", "dart_dev", "test", "--build_args=\"--config=test_config, --release\"", "--test-args=\"-p=chrome\""],
```
So with that, how do the test args that VS Code wants to pass get handled? Would it just put VM args at the beginning and test args at the end? I assume it wants to pass a --observe or something similar to the VM for VM tests, and for the CodeLens configs it would need to pass a -N test_name and/or file to test. With build_runner it could just add that on the end, but not with dart_dev. Or is there another scheme that's used for that?

**Comment by alanknight-wk** [comment]
But I suspect we could change dart_dev to treat unknown command-line arguments as part of test-args if that made this work.

**Comment by DanTup** [comment]
> I think this could be made to work, though it puts the burden on the person specifying the launch config and would make documenting or providing defaults for those more important.

Perhaps we could add something in the Dart-Code side that handles well-known tools that have reasonably consistent args. I was trying to make something very flexible though rather than just supporting one specific tools (this also came up in #3674, plus there's the existing flutter.json functionality, so it seems like a generic solution is required).

> It seems like to run a program it's always customToolReplacesArgs=1. To run tests in dart it's 2, and to run tests in flutter it's 1.

It depends on the tool. For example if you have a custom script that replaces "flutter run" then you might want to replace the "run" arg. But if you're using a tool that just wraps "flutter", you might still need "run" to be passed. Hard-coding these would be less flexible.

> Will that just be in documentation somewhere, or

Yes, I think it would have to just be documented. I don't think there's a great way within VS Code to provide a lot of guidance, but the documentation could include examples for some common tools.

> So, if I'm understanding this, if I wanted to use build_runner for tests I think I would specify it as
> ...
> how do the test args that VS Code wants to pass get handled? Would it just put VM args at the beginning and test args at the end?

The tools are always invoked like:

```
[tool] [built-in-args] [tool-args] [target-file] [args]
```

So in your case, `tool` would be replaced by your `customTool`, then the built-in args we normally add would be added (subtracting the number from `customToolReplacesArgs`), then your `toolArgs`, etc.

>  I assume it wants to pass a --observe or something similar to the VM for VM tests, and for the CodeLens configs it would need to pass a -N test_name and/or file to test.

Correct

> but not with dart_dev. Or is there another scheme that's used for that?

I'm not really sure of a solution if the custom tool can't accept the normal arguments. I don't want to make this too complicated because it will rarely be used and needs to be maintained. I think it's better if tools can be complete stand-ins for the tools they want to replace. If that's not possible, they could be wrapped by a thing wrapper/script that massages the arguments and then defers to the tool?

**Comment by alanknight-wk** [comment]
Yeah, this could end up on a slippery slope of complication. And people have the liberty to make tool a script that can do whatever munging is needed.

And I was thinking it's important to know what the normal arguments are, but then it occurred to me that you could always write
`  "tool": "echo"`
or an equivalent script and find out. But that might not occur to people, so good to document as well.

**Comment by alanknight-wk** [comment]
Trying to think this through for the specific case of build_runner... And by the way, I don't think this will be rarely used. At least, I think it would be almost universally used for Dart/web outside google3. Even with Flutter there's a lot of build_runner usage, though I'm not sure how it's invoked or how you'd specify arguments to it in tests. In our organization we just don't run tests from the IDE because it's not supported.

So for build_runner, the tool would still need to be `dart`, because [built-in-args] are VM arguments? So the simple case would look like this?
```
"customTool": "dart",
"customToolReplacesArgs": 2,
"toolArgs": ["run", "build_runner", "test", "--"],
```

But if we're ever going to get to a point where debugging tests works, it seems like the way we ask for the debug protocol URL would have to change.

**Comment by DanTup** [comment]
> by the way, I don't think this will be rarely used

Sorry, I meant - "if we make it too complicated/specific" it would be rarely used. I'd like to keep it generic and simple so it _is_ used.

 
> So the simple case would look like this?

I think something like that yep. I need to set up an example and try it out with some commands from above to be certain.

> if we're ever going to get to a point where debugging tests works, it seems like the way we ask for the debug protocol URL would have to change.

Yeah, the replacement script would need to be compatible with what we normally get - but isn't that already the case? If `run build_runner test` is ultimately running the underlying test package, then `-r json` should also be passed along, and we'd get a VM Service URL through the normal JSON produced by `package:test`?

**Comment by DanTup** [comment]
@alanknight-wk I'm trying to run the tests from your example repro above, but hitting an issue. Initially I got this error:

```
[WARNING] json_serializable:json_serializable on test/foo_test.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `pub upgrade`.

Analyzer language version: 2.12.0
SDK language version: 2.14.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.14.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.

[SEVERE] json_serializable:json_serializable on test/foo_test.dart:

Bad state: Unexpected diagnostics:
/Users/danny/Dev/Dart SDKs/stable/lib/core/int.dart:117:18 - Operator declarations must be preceded by the keyword 'operator'.
/Users/danny/Dev/Dart SDKs/stable/lib/core/int.dart:117:16 - Methods must have an explicit list of parameters.
/Users/danny/Dev/Dart SDKs/stable/lib/core/int.dart:117:18 - A function body must be provided.
```

I tried `pub upgrade`, but now it seems to just sit forever printing every 15s that it still hasn't completed:

<img width="607" alt="Screenshot 2021-11-24 at 13 59 11" src="https://user-images.githubusercontent.com/1078012/143252105-2c0e9678-7338-41f5-9207-e2baae8a0ba9.png">

I tried with both stable and nightly SDK builds. Have you seen this? Do I need a specific version of anything?

**Comment by DanTup** [comment]
I was able to get further by updating all deps to latest, making things null-safe and removing `dart_dev`. However, running `dart run build_runner test -- -p chrome` seems to spawn Chrome for a fraction of a second, then the test never completes until it times out:

```
00:30 +0 -1: loading test/foo_test.dart [E]                                                                                                                                                 
  Failed to load "test/foo_test.dart": Timed out waiting for Chrome to connect.
  package:test/src/runner/browser/browser_manager.dart 132:7  BrowserManager.start.<fn>
  dart:async/zone.dart 1420:47                                _rootRun
  dart:async/zone.dart 1328:19                                _CustomZone.run
  dart:async/future_impl.dart 865:34                          Future.timeout.<fn>
  dart:async/zone.dart 1420:47                                _rootRun
  dart:async/zone.dart 1328:19                                _CustomZone.run
  dart:async/zone.dart 1236:7                                 _CustomZone.runGuarded
  dart:async/zone.dart 1276:23                                _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1428:13                                _rootRun
  dart:async/zone.dart 1328:19                                _CustomZone.run
  dart:async/zone.dart 1260:23                                _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 18:15                     Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 395:19                   _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 426:5                    _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12                _RawReceivePortImpl._handleMessage
  
00:30 +0 -1: Some tests failed.                                                          
```

**Comment by DanTup** [comment]
Adding support for `customTool` to `dart run test:test` seems to work. Although I can't get the tests running, I can see it's running build_runner as expected.

![Nov-24-2021 14-25-16](https://user-images.githubusercontent.com/1078012/143256266-ba6d6c99-5101-496f-a962-b5371fd756e3.gif)

Since I already need this for Flutter, I think it makes sense to go ahead landing this here, and then also in the SDK DAPs.

This doesn't address debugging, but we have #3659 open for that (I'm still waiting for some feedback.. I'm not currently sure whether `package:test` supports this or not).

**Comment by DanTup** [comment]
With support for `customTool` etc., perhaps we can handle the really common cases (build_runner) in the extension. Eg. you set a setting (or we detect build_runner) and we inject the correct values. I've opened #3688 to look into this. There are some complications around knowing the number of args (when this lives inside the SDK and isn't necessarily in-sync like the extensions own DAP is), but I want to at least look into it.

**Comment by DanTup** [comment]
There's a beta with the `customTool` changes at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.29.0-beta.1

**Comment by alanknight-wk** [comment]
Sorry, you'll have to use 2.13.4 or earlier, or else delete the dart_dev dependency and just use it to verify build_runner. It's difficult to make a version of that which can work with 2.14.

We're using 2.13.4 internally, because upgrading to 2.14 is a complicated process. So that's what I tested against. There's no version of dart_dev that can use analyzer 2.0.0, and analyzer 2.0.0 is required for 2.14.0 so it can parse the SDK.  2.14 really should have been 3.0.0 because they changed the grammar, so it needs major versions of every package. Older versions of things like build_runner and json_serializable don't know that they can't work with 2.14, so they fail at build_time, as you saw.

**Comment by alanknight-wk** [comment]
Sweet. I got it working. The launch.json is pretty messy. I ended up with the below. And it works if I launch it from the source code actions, but if I try to run a test from within the test runner UI it fails, seems like it's not getting this. Maybe there's a different way to intercept that?

```
       {
            "name": "Run tests",
            "request": "launch",
            "type": "dart",
            "customTool": "dart",
            "customToolReplacesArgs": 2,
            "codeLens": {
              "for": [
               "run-test",
               "run-test-file",
               "run-file",
              ],
            "title": "Run", 
            },
             "toolArgs": ["run", "build_runner", "test", "--", "-pchrome"],
            },
            {
                "name": "Debug Tests",
                "request": "launch",
                "type": "dart",
                "customTool": "dart",
                "customToolReplacesArgs": 4,
                "codeLens": {
                  "for": [
                   "debug-test",
                   "debug-test-file",
                   "debug-file",
                  ],
                "title": "Debug",  
                },
                // The '-pchrome' part is required, otherwise it will try to run on the VM.
                // The --pause-after-load is useful for tests in that it will open a visible Chrome that we can use to debug.
                "toolArgs": ["run", "build_runner", "test", "--", "-pchrome", "--pause-after-load"],
                },
```

**Comment by DanTup** [comment]
Sorry for the delay. Glad you made progress!

> it works if I launch it from the source code actions, but if I try to run a test from within the test runner UI it fails, seems like it's not getting this

Hmm yeah, unfortunately the customisations above are currently for CodeLens only. I thought I might be able to handle the custom CodeLens using profiles (#3607) however they are global so it won't work (you might have different customisations per-file) and the UI is a bit janky.

That said, this case is a little simpler because you're not adding new run configs, you're just _replacing_ the Run/Debug ones. Perhaps we can handle that, even if it's slightly limited (for example if we only support these configs that have no `path` filter).

I've filed #3705 specifically about doing that.

**Comment by point-source** [comment]
This is not working as I expect based on the prior information in this issue. I have created a brand new dart project, a simple cli app. For my launch config, I first tried this:

```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
        }
```

Output:
`--enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-7630.json -DSILENT_OBSERVATORY=true bin/main.dart`

So far so good. I then tried to see if I could remove args:

```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
            "customToolReplacesArgs": 2,
        }
````

Output:
`--enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-6a28.json -DSILENT_OBSERVATORY=true bin/main.dart`

Hmm, that's odd. Nothing got removed. Maybe it need tool args to replace them?
```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
            "customToolReplacesArgs": 2,
            "toolArgs": [
                "test",
                "arg"
            ]
        }
```

Output:
`test arg --enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-6280.json -DSILENT_OBSERVATORY=true bin/main.dart`

So it appears that "echo" replaces "dart" as the tool but customToolReplacesArgs maybe does nothing?

```
        {
            "name": "toolTest",
            "request": "launch",
            "type": "dart",
            "program": "bin/main.dart",
            "customTool": "echo",
            "toolArgs": [
                "test",
                "arg"
            ]
        }
```

Output:
`test arg --enable-asserts --enable-vm-service=0 --pause_isolates_on_start=true --no-serve-devtools --write-service-info=file:///var/folders/h0/y0mhxm317slfr5k149cfxvfr0000gn/T/dart-vm-service-19d2.json -DSILENT_OBSERVATORY=true bin/main.dart`

Same thing. How do I get the arg replacement to work?

Additionally, if I try this with a flutter project, it completely ignores "customTool" and continues running as normal even though I'm using the exact same launch config. How does the extension determine whether it's a flutter project or not and why does it ignore the customTool arg?

**Comment by DanTup** [comment]
FWIW, the setup for using custom config for CodeLens and Test Runner is being simplified in the upcoming release (#3705 and #3802). The existing stuff (using `"codeLens"` in the launch template) still works, but there's a simpler way now that lets you just specify a path without the other fluff (as long as you want it for the default Run/Debug actions):

```js
		{
			"name": "Dart with Env Var",
			"type": "dart",
			"request": "launch",
			"env": {
				"LAUNCH_ENV_VAR": "true"
			},
			"templateFor": "test", // set a path here, or use empty string to apply to all
		}
```

Now when you run from Run/Debug links on CodeLens, _or_ tests from the Test Runner, this config will be used. Note: It does _not_ apply to the Run/Debug entries on the menu (or pressing `F5`) because there's a UI to select which config to use for them and I think it would be unexpected to ignore that and use a different one. CodeLens and Test Runner can't access that selection though, so this works there.

I'll publish a pre-release with these changes shortly if you'd like to try them out before the stable release.

**Comment by evanweible-wf** [comment]
Hey @DanTup, thanks for the update! I just have a couple of questions:

1. Previously we only needed to use `"customToolReplacesArgs": 2` to swap out the `run test:test` part for our own args like `run dart_dev test` and then the rest of the args would be appended to our custom args, but now I'm seeing that some of the args get inserted before our custom `toolArgs`. In particular, `-r json -j1`. This means that we have to increase the number of args we replace and then duplicate them in our own custom `toolArgs`; the previous approach seemed more robust since whatever the IDE needed for it to work (like `-r json`) would be automatically included.

2. With `templateFor` is there a way to differentiate between running tests and debugging tests? I suspect that this may be related to point no. 1 above because it seems likes the launch config just passes in a different set of args based on whether its debugging or not, but again unfortunately it's not possible to integrate our custom tool with the way those args are passed in right now.

**Comment by evanweible-wf** [comment]
^ I'm not sure I explained that very well. It seems like there are two sets of args now: those associated with the `dart` command and those specific to whichever test(s) are being run:

```
# running tests:
dart run test:test -r json -j1 --name ^Foo test/foo_test.dart
|--- command --| |---------------- test args -------------------|

# debugging tests:
dart --enable-vm-service=0 --pause_isolates_on_start=true run test:test -r json -j1 --name ^Foo test/foo_test.dart
|--- command ----------------------------------------------------------| |------------- test args ------------------|
```

The normal test running scenario is simpler, and replacing `run test:test` with `run dart_dev test --` should be straightforward, but right now the following config:

```json
            "customTool": "dart",
            "customToolReplacesArgs": 2,
            "toolArgs": [
                "run",
                "dart_dev",
                "test",
                "--",
            ]
```

gives us:
```
dart -r json -j1 run dart_dev test -- --name ^Foo test/foo_test.dart
```

instead of:
```
dart run dart_dev test -- -r json -j1 --name ^Foo test/foo_test.dart
```

For debugging, the default dart launch config passes two args to the `dart` command itself, which makes sense and it would probably be overly complex to come up with a way to retain those args but then remove some following args. That's fine, though, it seems reasonable for us to include those args in our custom args since we know we'll be using the `dart` CLI still. But we would still end up with the same problem where some of the test args (`-r json -j1`) are inserted before our custom args.

Additionally, I'm not sure how to specify a separate config using `templateFor` that applies only to debug test runs, which would be necessary since we need to replace two additional args (`--enable-vm-service=0 --pause_isolates_on_start=true`) and specify them as our first two custom args.

**Comment by DanTup** [comment]
> but now I'm seeing that some of the args get inserted before our custom `toolArgs`

Do you have an example of a config and what it's doing, and what you'd expect?

I think there are some conflicting requirements:

- `customToolReplacesArgs` should be able to replace built-in args (eg. `-r json`) - requires custom args are added to the list before `customTool`/`customToolReplacesArgs` are processed
- built-in args should come after the replacement

I think the way it's currently implemented is probably better as it supports both - although for your case you'll need to duplicate the args (or, set `customTool` to a wrapper script that provides the full command - I think the issue here is that your custom "tool" is actually a command and some args, so the ordering between built-in args and `toolArgs` is significant). The old way prevented you from replacing built-in args (eg. if your tool didn't support `-r json` but had the same behaviour).

> Additionally, I'm not sure how to specify a separate config using `templateFor` that applies only to debug test runs

This isn't currently possible - `templateFor` is intended for very simple cases where you don't need to vary the arguments for different types of runs. You can still use the `codeLens` field for more advanced cases (although I'd like to rename that since it's not really specific to CodeLens now).

**Comment by evanweible-wf** [comment]
> This isn't currently possible - templateFor is intended for very simple cases where you don't need to vary the arguments for different types of runs. You can still use the codeLens field for more advanced cases (although I'd like to rename that since it's not really specific to CodeLens now).

Ah okay, I see. Does `codeLens` now integrate with the VSCode Test Explorer panel? I thought that was one limitation previously, but it sounds like maybe that is fixed? I was able to get the Text Explorer working when using `templateFor`, but the following `codeLens` configs are still only working for the CodeLens links in the editors:

```json
            // For our "Run Dart Tests" config:
            "codeLens": {
                "for": [
                    "run-test",
                    "run-test-file",
                ],
                "title": "Run",
            },

            // For our "Debug Dart Tests" config:
            "codeLens": {
                "for": [
                    "debug-test",
                    "debug-test-file",
                ],
                "title": "Debug",
            },
```

**Comment by DanTup** [comment]
hmm, good question. I thought that was supported too (and `templateFor` was only to simplify configuration, rather than the only way to do it), I'll do some digging..

**Comment by DanTup** [comment]
Looks like I stoped this from working in bac9c3d5fa35a6879fb96acaf2bf25d0ec8eb45b, but I'm not sure if the reasons are sound.

One complication is that we run multiple test suites within a single invocation of the tool (for better performance) and configs could overlap/mismatch... however, since `templateFor` now takes a path (it was originally planned as just a boolean) we already have that confusion.

I've opened #3854 to revisit this.
