### ISSUE TITLE
Changelog is not searchable

### ISSUE THREAD

**Issue by alanknight-wk** [Dart-Code/Dart-Code#3657]
**Is your feature request related to a problem? Please describe.**
The changelog is now via the web page at https://dartcode.org/releases/. However, there doesn't seem to be a way to see the thing as an entire change log, to search for something in particular. It seems like you have to click on each release and look through the notes for each one individually.

**Describe the solution you'd like**
Have a link on that page that gives the concatenation of the notes for every release.

**Describe alternatives you've considered**
Provide a search box, but that seems like much more work.

**Additional context**

**Comment by DanTup** [comment]
The page at https://dartcode.org/releases/ is now the full set of releases rather than just a list of links (which are in the nav).

It's quite a large page because of all the animated GIFs, but I suspect most people browsing will be linked directly to a specific releases page from the toast notification in VS Code so I'm not too concerned about that.

The site is completely static (via GH Pages/Jekyll) so having a real search box would indeed be more complicated.
