### ISSUE TITLE
Entering opening brace causes code snippet suggestions to appear

### ISSUE THREAD

**Issue by acoutts** [Dart-Code/Dart-Code#3670]
**Describe the bug**
When typing out a `{`, instead of just auto-completing the other `}`, it also pops up the dart code snippets so if you just hit enter you'll insert the first code snippet instead of simply entering a new line to start typing inside your new set of braces.

**To Reproduce**
1. Open any dart file.
2. Enter a `{`
3. Hit enter

**Expected behavior**
It should not show any snippet suggestions.

**Screenshots**
![Screen Shot 2021-11-15 at 3 08 24 PM](https://user-images.githubusercontent.com/9597207/141846942-781a5b29-a808-4c57-b532-146aba7204ce.png)

**Versions (please complete the following information):**
 - VS Code version:
```
Version: 1.63.0-insider
Commit: 035eaab2cb31798c6ae90a35928c62117cb52fcd
Date: 2021-11-15T05:26:27.466Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0
```
 - Dart extension version: `3.28.0`
 - Dart/Flutter SDK version: `2.5.3`

**Comment by acoutts** [comment]
Appears the same thing happens if you enter a `'` in the middle of a string (trying to terminate it)

![Screen Shot 2021-11-15 at 3 13 44 PM](https://user-images.githubusercontent.com/9597207/141847556-decb0a45-ac49-4f6f-bca2-80cc5fba7e3e.png)

**Comment by DanTup** [comment]
@acoutts the snippets in this screenshot don't look like they're from Dart-Code?

**Comment by acoutts** [comment]
These are the snippets I have defined in my `.vscode/dart.code-snippets` file

**Comment by DanTup** [comment]
I don't think there's anything Dart-Code can do here. It seems like the `triggerCharacters` set up for Dart's completion are causing VS Code to also show user snippets. Since `triggerCharacters` don't have any context, they always fire unconditionally and any context must be handled by the server/completion provider. In this case, that is VS Code's snippet handler.

There's a similar issue at https://github.com/microsoft/vscode/issues/65200 and the suggestion is to set `"editor.snippetSuggestions": "none"`. I suspect `"editor.suggestOnTriggerCharacters": false,` will also work, although both may disable functionality you might want.

**Comment by acoutts** [comment]
Nice! `"editor.suggestOnTriggerCharacters": false,` fixed it for me while retaining my dart snippets functionality.

The first one broke it though and disabled everything.

**Comment by DanTup** [comment]
I suspect that setting will also prevent the completion opening automatically for identifiers when you press trigger characters (eg. when you type `import '` it might no longer open completion automatically), but without a VS Code change, I think your only options at to pick between those.

**Comment by acoutts** [comment]
Ahh you're right that broke the normal auto complete such as typing `class.` and then the class members show.

**Comment by DanTup** [comment]
Yeah, in this case the `.` is a trigger character and is triggering suggest.

If that's no good, perhaps it's worth filing a VS Code issue about this. Since the trigger characters defined by a language are not context-aware and it's up to the provider to "return nothing" if it was triggered in a case that doesn't make sense (for example [here](https://github.com/dart-lang/sdk/blob/3238b2c09c1e2fc023363ea33902d93bcc8b3d79/pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart#L535-L538) is where the Dart server will drop any completion requests when the trigger character is `{` if you're not starting an interpolation expression), it seems like user snippets should have some way of doing the same.

This this case, the simplest fix is probably a setting in VS Code for "don't include snippets in completion when triggered by a trigger character" but being able to attach some context to your snippets might be more flexible (for example, if you have snippets that create classes, it never makes sense for them to appear in the completion list inside a string - but VS Code doesn't currently have any options for this).

It's possible the answer will be "make your own extension and put your snippets in that where you can return them programmatically) though (as it was the answer when I asked for something similar - https://github.com/microsoft/vscode/issues/26943).

**Comment by acoutts** [comment]
Thanks Dan, it must be something they changed recently because those dart snippets only ever used to show if you typed out the specific snippet name.

**Comment by DanTup** [comment]
Hmm, odd - I can't think of what may have changed. I wondered if maybe it was LSP-related (in the last Dart-Code you may have been moved over to LSP if you'd previously disabled it), but for non-LSP we also had `{` as a trigger character:

https://github.com/Dart-Code/Dart-Code/blob/434b509dd5ae9ad8fa535591d70e4f2e768019bf/src/extension/extension.ts#L359

Seems like there is a similar report about this in TypeScript recently:

https://github.com/microsoft/vscode/issues/136611

But the issue it links to as the cause is very old, so I'm not sure what's happened.

**Comment by DanTup** [comment]
Looks like there was a VS Code change that caused this - see https://github.com/microsoft/vscode/issues/136611#issuecomment-975769359. It's planned to be fixed in the next release.
