### ISSUE TITLE
Support passing args to Dart VM when running tests

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#3685]
**Describe the bug**
I am attempting to run tests in a project that uses the `constructor-tearoffs` experiment, and I'm getting errors while running the test from inside VSCode.

I have attempted to use both `vmAdditionalArgs` in the launch config for that test, as well as `dart.vmAdditionalArgs` at the workspace level, but neither are passed along to the test.

Example of launch.json:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "server",
      "program": "test/server_test.dart",
      "request": "launch",
      "type": "dart",
      "vmAdditionalArgs": [
        "--enable-experiment=constructor-tearoffs",
      ]
    }
  ]
}
```

Example of my .code-workspace:

```json
{
  "folders": [],
  "settings": {
    "dart.vmAdditionalArgs": [
      "--enable-experiment=constructor-tearoffs"
    ],
  }
}
```

I have verified that the VM args _do_ work as expected launching something other than a test.

I have also verified that `dart test --enable-experiment=constructor-tearoffs` works fine from the commandline.

**To Reproduce**
1. Create a project that uses constructor tear-offs
2. Write a test file that references the library containing tear-offs
3. Attempt to run using methods described above

**Expected behavior**
That the tests run without analysis failure.

**Versions (please complete the following information):**
 - VS Code version: v1.62.3
 - Dart extension version: v3.28.0
 - Dart/Flutter SDK version: v2.15.0-42.0.dev

**Comment by DanTup** [comment]
`vmAdditionalArgs` are intended only for running command line apps, not tests. I think we should have something like a `dartTestAdditionalArgs` though (we already have a Flutter equiv). I'll tweak this issue to be for that.

In the meantime, you might be able to use `toolArgs` in your `launch.json` instead of `vmAdditionalArgs` to get the same effect.

FWIW, the `xxxAdditionalArgs` options are all _settings_ so can only go in User or Workspace settings, not directly in launch configurations.. in launch configurations, setting `toolArgs` and `args` directly is the right way. The settings are intended for when you want to set this for _all_ instances, without needing to add it to lots of launch configurations (or when you're not using `launch.json`).

**Comment by shyndman** [comment]
`toolArgs` does not have the desired effect.

**Comment by DanTup** [comment]
@shyndman can you be more specific? What happens?

FWIW, I'm about to make a beta build of the next release which includes `dart.testAdditionalArgs` - although if `toolArgs` isn't behaving correctly I'd still like to look at that.

**Comment by DanTup** [comment]
Beta is here -> https://github.com/Dart-Code/Dart-Code/releases/tag/v3.29.0-beta.1

**Comment by shyndman** [comment]
I don't have the work in front of me, but as I recall `toolArgs` are being provided to the sub-command, not the Dart binary, so the experiment was not enabled.

I can verify in a bit.

**Comment by DanTup** [comment]
Oh, I see - I presume the flag you're passing needs to go before `run test:test`, but currently we assume `toolArgs` are to be passed to the test package.

In that case, it's possible `dart.testAdditionalArgs` also won't help you, since they'll also be passed to test.

I'm wondering if using `vmAdditionalArgs` here may cause issues (for anyone wanting it only passed to running scripts) or if it makes more sense that another setting for vm flags for test. Perhaps the former makes sense, and if thre are flags that need to be passed only to CLI scripts, there should be a specific `dart.cliAdditionalArgs` or similar.

**Comment by shyndman** [comment]
> I'm wondering if using vmAdditionalArgs here may cause issues (for anyone wanting it only passed to running scripts) or if it makes more sense that another setting for vm flags for test

Yup, could be problematic. I don't think you can go wrong adding another a test vm flags option.

**Comment by DanTup** [comment]
This turns out to be a little more complicated, as we currently only have two ways to pass args into the DAP:

- args - these are for your script
- toolArgs - these are args passed to the tool running your script (`dart`, `dart run test:test`, `flutter`, `flutter test`)

The `xxxAdditionalArgs` settings are all just handled in the editor, and are mapped onto `toolArgs` depending on the session we're launching. It seems like we may need a `vmAdditionalArgs` supported by the DAP (and for normal CLI scripts it will just happen to function the same as `toolArgs`).

**Comment by DanTup** [comment]
Ok, I've got this working, although I noticed something odd (but not really related to Dart-Code)... Running with the stable release with this flag is fine, but using the flag on a nightly build (where I presume the feature is already enabled), it acts as if it's been disabled:

```
danny@Dannys-MacBook-Pro dart_sample % /Users/danny/Dev/Dart\ SDKs/nightly/bin/dart --enable-experiment=constructor-tearoffs run test:test test/one_test.dart 
00:00 +0 -1: loading test/one_test.dart [E]                                                                                                                    
  Failed to load "test/one_test.dart":
  test/one_test.dart:15:17: Error: Member not found: 'new'.
  final a = Danny.new;
                  ^^^
00:00 +0 -1: Some tests failed.                                                                                                                                
danny@Dannys-MacBook-Pro dart_sample % /Users/danny/Dev/Dart\ SDKs/stable/bin/dart --enable-experiment=constructor-tearoffs run test:test test/one_test.dart
00:01 +0 -1: my group my test 1 [E]                                                                                                                            
  Expected: <2>
    Actual: <1>
  
  package:test_api        expect
  test/one_test.dart 8:7  main.<fn>.<fn>
  
00:01 +0 -1: loading test/one_test.dart                                                                                                                        
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
00:01 +0 -1: Some tests failed.                 
```

So if you see things stop working after an SDK update when you've been using this, it might be that. I'll still land this work as-is though, as it's doing what's expected.

**Comment by DanTup** [comment]
I'll make another beta build with the latest changes tomorrow assuming nothing breaks on the bots.

**Comment by shyndman** [comment]
Thanks Dan. :)

**Comment by shyndman** [comment]
> So if you see things stop working after an SDK update when you've been using this, it might be that. I'll still land this work as-is though, as it's doing what's expected.

Oh wow, bizarre. Thanks for the head's up.

**Comment by DanTup** [comment]
Actually, scratch that bit - it was user error. In the nightly (eg. v2.15) it is enabled by default, but only when your pubspec's environment setting is >= 2.15. This makes sense, since you generally need to opt in to language changes with the version.

So it might still catch you out, but the fix is to update your SDK constraint :-)

**Comment by shyndman** [comment]
I just read over all your comments. Thanks for your help. Quick turnaround. :)

**Comment by DanTup** [comment]
New beta release here -> https://github.com/Dart-Code/Dart-Code/releases/tag/v3.29.0-beta.2

- cliAdditionalArgs - passed to `dart` only for CLI scripts
- testAdditionalArgs - passed to `test` in `dart run test:test` for test scripts
- vmAdditionalArgs - passed to `dart` in both CLI and test scripts

**Comment by gspencergoog** [comment]
@DanTup Is there a way to pass the `--local-engine=host_debug_unopt ` arg to a flutter test run in VSCode, ideally by just hitting the "Run" button in the code?  I've tried all three of the settings above, and `toolArgs` in the configuration, and it doesn't appear to be passed, or isn't passed in the right place.  I can run it on the command line with something like the line below, but I'd like to be able to set breakpoints and use the debugger:

```shell
flutter test --local-engine=host_debug_unopt test/services/lifecycle_test.dart
```

And how does it know that something is a test?  Just if it ends in "_test.dart", or if it's in the "test" dir?

**Comment by DanTup** [comment]
@gspencergoog using `toolArgs` should work fine. You can use `"templateFor": "test"` to have it apply to the Run/Debug links in tests (you can set it to an empty string to apply to the whole project).

Eg.:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "dartcode_flutter_3985",
			"request": "launch",
			"type": "dart"
		},
		{
			"name": "dartcode_flutter_3985 --local-engine=host_debug_unopt",
			"request": "launch",
			"type": "dart",
			"toolArgs": [
				"--local-engine=host_debug_unopt",
			],
			"templateFor": "test",
		},
	]
}
```

This creates an additional launch config that passes that flag, and sets it as the template for anything in the `test` project (this means the Run/Debug links and the Test Runner will use it when running tests). If I do this and hit the Run/Debug links, I get this output (which matches what I see in a terminal using that command, I guess because I haven't set the engine up locally):

<img width="608" alt="Screenshot 2023-04-17 at 11 14 13" src="https://user-images.githubusercontent.com/1078012/232455680-21521f3e-8c51-450a-b574-e10b631d7d0e.png">

Let me know if this doesn't seem to work for you.

> And how does it know that something is a test? Just if it ends in "_test.dart", or if it's in the "test" dir?
> Just if it ends in "_test.dart", or if it's in the "test" dir?

To be considered a test file, it must end with `_test.dart` and _either_ be:

- inside a folder named `test`, `integration_test` or `test_driver
- or, you have set the `dart.allowTestsOutsideTestFolder` setting to `true`

If those conditions are met, we'll use `flutter test` instead of `flutter run`.

**Comment by DanTup** [comment]
> It shows up in my list of "Run and Debug" configurations, but when I run it, it (unsurprisingly) gives the popup message "Set the 'program' value in your launch config (eg 'lib/main.dart') then launch again".

If you don't have an explicit `program` in a launch config, it will try to infer it from your open files/workspace. If you had a test file open when you did this, it suggests we're not detecting it correctly.

Could you file a new issue and include steps for me to reproduce this, including exactly what codebase you have open, and how you have it open (eg. what folder(s) you have open, or if a `.code-workspace` what folders are in it)?

**Comment by DanTup** [comment]
FWIW, I opened `flutter/packages/flutter` in VS Code, created a `launch.json` from your code above, and clicked the "Run" CodeLens, and it did what you wanted 😞

So if you file a new issue, please also include a log file captured by:

- Open the `flutter/packages/flutter` folder
- Running the **Dart: Capture Debugging Logs** command from the palette (`F1`)
- Click the `Run` CodeLens above `test('Tasks are executed in the right order', () {` in `test/scheduler/scheduler_test.dart`
- Wait for the debug session to start (or fail, or whatever)
- Click **Cancel** on the logging notification to stop logging and open the log

Attach the log, or send to me at logs@dartcode.org.

**Comment by gspencergoog** [comment]
I think I found a config that works:

```json
    {
      "name": "Local Engine Test",
      "type": "dart",
      "request": "launch",
      "toolArgs": ["--local-engine=host_debug_unopt"],
      "cwd": "${workspaceRoot}/packages/flutter",
      "program": "test/scheduler/scheduler_test.dart",
    },
```

Although why it works and the other didn't, I'm not sure (I'm pretty sure I tried this already and it didn't work).

I'll try and repro exactly what happened before and file an issue if I can. I wasn't aware that which file I have open would affect it the arguments a configuration runs with, so maybe that's what was confusing things.

One thing I *think* I've observed (but can't repro right now) is that the `--local-engine` flag may be caching itself, so that running from the command line might cache the local engine setting for the next run from the IDE, which would definitely be confusing. I'll file that too if I can repro it.

**Comment by DanTup** [comment]
> "cwd": "${workspaceRoot}/packages/flutter",

I just noticed that based on this you probably have the Flutter repo root open. This means in my original example, this was wrong:

```
"templateFor": "test",
```

It would have had to be:

```
"templateFor": "packages/flutter/test",
```

Since it's a relative path from the workspace root. With just `"test"` it wouldn't have applied as the template for the CodeLens links inside the folder you wanted.

**Comment by gspencergoog** [comment]
Yes, you're correct, I have the Flutter root repo open.

>It would have had to be:
> `"templateFor": "packages/flutter/test",`

Yes! that seems to fix things, and clicking "Run" with that change causes the test to run with the local engine. Thanks!

I'm assuming that was what the issue was before so I'm not going to try and repro and file, unless you'd like a documentation issue to document it.

**Comment by gspencergoog** [comment]
> The extension doesn't have any visibility of what you're doing at the command line, so if this is happening it could be happening in Flutter?

Yes, my assumption is that it's in the flutter tool somehow, or maybe even specific to Linux builds. But maybe I've just been confused by not understanding exactly how the command arguments are determined when I click "Run".
