### ISSUE TITLE
Enable developer to turn off analysis

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3692]
I'm currently working on a code generator that spits out a ton of Dart files. Right now there are thousands of compile errors as I'm making changes to the code generator and improving things. It's useful to have visibility into those errors, but the analysis server is aggressive at reanalyzing my code with every change I make, and that makes VSCode almost unusable. 

**Describe the solution you'd like**
I'd like to be able to disable automatic analysis for this project, and use a command to manually trigger it when I want updates.

If this is available in the tool, I couldn't find it, which either makes it a user failure (quite likely!) or perhaps a usability failure.

**Comment by DanTup** [comment]
There is an option to exclude files in the analysis_options. Would commenting/uncommenting an exclude entry do what you're looking for?

![Nov-24-2021 18-22-50](https://user-images.githubusercontent.com/1078012/143294008-a85666b6-0a0c-4663-93b7-eb3b3965331f.gif)

It's perhaps not as discoverable as a native feature would be, but it supports paths (rather than globally turning things off) so would allow you to ignore just generated code and get help for your other files if needed.

(You can also filter things out of the Problems window, though I suspect that's not what you're after since the server will still be analyzing them and doing a lot of work)

**Comment by timsneath** [comment]
Thank you, Danny! 

For my own scenario (which might not be common), that's a good workaround, I think, but probably slightly imperfect, because I assume it will immediately remove all the problems whenever I exclude these files. I really want to see the errors, so I can figure out what needs fixing; but the analyzer is so CPU-intensive when there are 10k+ errors that it makes it hard for me to make progress.

**Comment by DanTup** [comment]
> I assume it will immediately remove all the problems whenever I exclude these files

You assume correctly - I didn't realise you still wanted to see the previous errors. I'm not sure there's an easy way to do what you want, as the CPU probably isn't just from producing the diagnostics, but also the work required to support things like code completion (and presumably you still want that while you're editing files?).

Out of interest, how often are you triggering changes that cause analysis, and how long is the analysis taking? If you can give me some instructions to trigger the worst of it (I presume it's running some generation in package:win32?), it's worth doing some CPU profiling to see if there's any optimisations that might help (for example if a large number of files are being modified, I wonder if some work is being duplicated as re-analyzing one file might result in reading others that are about to change).

I don't know if's also contributing to this, but we've also seen some VS Code perf issues when there are lots of errors being updated (updating the Problems tab was once very expensive, and caused the editor to stall when there were lots of updates). If VS Code is also using lots of CPU when this happens, there might be room for some improvements there too (if I can repro this, I can profiling the VS Code UI too and file an issue there if it seems to be performing badly).

**Comment by jellynoone** [comment]
Perhaps an answer here would be limiting a number of reported errors per file? Or have an option to only show errors for the currently opened file?

**Comment by DanTup** [comment]
If the main issue is the cPU consumption analyzing the files, I don't think capping those that make it to VS Code would really help (the CPU would still be consumed). If the issue is with VS Code's handling of a large number of problems, it could help (although I suspect that's not the case - although we've seen perf issues with it before, it seems like the server is doing significantly more work here).

I'd like to reproduce and measure things to see what's going on. I could imagine that lots of files being modified might result in duplicate work (for example modifying one file might cause other dependent files to be reanalyzed, and if those files are modified soon after, perhaps they'd be analyzed multiple times?). If that is the case, perhaps some debouncing of file watch events would help (I'm not certain whether there already are any). Whether it'd be enough that it doesn't still seem worthwhile to "pause" analysis, I'm not sure though.

**Comment by timsneath** [comment]
This is certainly a great torture test for the analyzer. Clone as follows:
`git clone -b v3 git@github.com:timsneath/win32.git` 

From a Windows machine, after doing `dart pub get` you should be able to run 
`dart tool\v3\generate_all_from_winmd.dart` to regenerate all the Dart files (about 10,000 of them). 

You'll see how sluggish things can be. Turning off analysis definitely helps a ton, but it does mean I have to sacrifice error messages, obviously.

**Comment by DanTup** [comment]
Thanks! The performance does seem much worse than I was expected. After running your script I cleared my `~/.dartServer` folder (so nothing is cached) and opened VS Code. It took approx 4m 19s on my (old) PC to perform the initial analysis.

I then ran `Get-ChildItem -recurse | ForEach-Object{$_.LastWriteTime = Get-Date}` in the folder to update the timestamps on all files (without actually changing the contents) and it took 15m 18s to re-analyze.

This seems to suggest that modifying a large number of files may be doing much more work than a single full analysis would (and perhaps work is occurring on files that haven't really been modified that could be skipped). I'll do some more digging and see if I can come up with any ideas. I'm not sure if it'll ever be fast enough on this project to not suck, but it may make sense to try and optimise what's happening here before trying anything more complicated.

**Comment by DanTup** [comment]
It seems like most of the time is spent in the same thing - the declarations tracking (used for code completion of un-imported symbols). If I comment that out, re-analysing seems to only take a few seconds (instead of the 15 minutes it takes when it runs).

I've opened https://github.com/dart-lang/sdk/issues/47804 to get some input and will see if there are things that can be improved there.

**Comment by DanTup** [comment]
So the perf issue noted above was related to the declarations tracking which is used to provide completions for un-imported files. It needs to know all of the symbols in each file to work. Some of the files in win32 have a large number of `exports` and when any of those exports change, the declarations for the file including them need to be updated. The repeated modifying of the exported files meant the exporting files declarations were constantly being rebuilt by each modified file.

Konstantin has [landed a change](https://github.com/dart-lang/sdk/commit/6091533c6e3f70969acdc65ac422298c05fa7567) where if multiple files are modified together (eg. they get into the queue at the same time, before processing is done) then they can all be rebuilt once (instead of once per file).

In my contrived example (where I just modify every file immediately), the 15 minute of processing has become < 1 minute.

With the real codegen script, I no longer see a permanent "Analyzing..." for the whole time the script runs, and instead see it flickering periodically (because it's able to run faster than the files are being queued up), and once the generation script finishes, there's < 1 second before the final analysis completes.

There are probably also some small tweaks you could make to the generation script that would reduce the total CPU usage spent in the server more, but trying to write the files as closely together as possible. I think right now the writing of files is done in-between the generation of their contents (eg. generate file contents, write file contents, generate file contents, write file contents). If you instead built the content of a number of files (or if RAM allows, all of them) into a `Map` or something, then dumped them all to disk at once, that would likely mean more of the servers updates are batched and its overall resource usage would be lower.

Whether it's worth doing that though, I don't know. For me, the server's resource usage is now much lower than the generation script (whereas it used to be _significantly_ more).

@timsneath interested to hear your experiences once you're on an SDK with the change above.

**Comment by DanTup** [comment]
@timsneath are you on an SDK with the change above? Are things any better?

**Comment by timsneath** [comment]
I think so. It's a little hard to be sure -- I've overhauled my own build process to use 16 parallel isolates, so it's not directly comparable. I'm seeing some weird stuff where I think the analysis server is crashing, because the problems drop to 0 and then slowly build up. That might be unrelated though. Filing bugs when I see them, obviously.

**Comment by timsneath** [comment]
`git clone -b namespace git@github.com:timsneath/win32.git` for the parallelized code generator, just in case you're interested...

**Comment by DanTup** [comment]
> I've overhauled my own build process to use 16 parallel isolates

heh, I was thinking about this when I saw the Isolate changes in the latest release notes :-)

I'll do some testing with that branch soon and see if I can reproduce anything like what you've described here. Interesting that it seems like it might be crashing, as the other issue you raised recently seemed like that too. I think if the server quits and is restarted by the VS Code LSP client it gets written somewhere (maybe the Output pane somewhere), but I don't recall off the top of my head. I'll let you know what I find anyway. Thanks!

**Comment by DanTup** [comment]
Running on my PC, I haven't seen the errors disappear and come back, although it does still trigger quite a lot of individual analysis because towards the end (it takes 10-12 mins on my machine), each namespace finishes separately and each one will trigger analysis (and rebuilds of some things like the declarations).

One thing that might reduce this further, is to generate the file contents first (collecting them for all libraries), and then synchronising writing to disk (to keep them as close together as possible). This will likely remove more overlap of the declarations being re-computed due to changes in the files with lots of exports.

I'd be interested in the instrumentation log (`"dart.analyzerInstrumentationLogFile": "logs/instrum.txt"` in the workspace settings) of a rebuild where you see the errors disappearing and coming back. Using the current code I see 27 errors - I presume that's correct? (previously there were thousands, but I presume they're resolved rather than I've got something wrong).

**Comment by timsneath** [comment]
Yup -- the 27 errors, instead of thousands is the result of my hard labor over the last month :) Just dealing with some edge cases (e.g. where the Win32 identifier is the same name as the type, since `final GUID GUID = GUID();` isn't legitimate Dart :) 

I agree -- there are likely further optimizations around the timing of file generation. I'll try to do some experimentation here when I've finished experimenting with Isolates. Having multiple isolates processing partitions of the metadata has greatly reduced the time by 3-5X, but I'm now experiencing some intermittent errors where the group doesn't finish even though all the individual isolates have completed. 

Since you've kindly enabled some big improvements on analysis, and we're now looking at other forms of optimization, it's fine if you want to close this bug out for the time being.

**Comment by DanTup** [comment]
> but I'm now experiencing some intermittent errors where the group doesn't finish even though all the individual isolates have completed.

I actually saw that behaviour today.. I didn't investigate it, but at a glance I assumed it was because of this:

https://github.com/timsneath/win32/blob/3ee0f38e597f688f6b1c9e7a27e39df285f155a0/tool/v3/generate.dart#L236-L237

I was running less namespaces than `concurrentIsolates` so I think it's creating more `ReceivePort`s than it will run isolates for, and perhaps it should be:

```dart
final ports = List.generate(partitions.length, (i) => ReceivePort());
```

? If you're seeing it when running a subset of them, it's worth checking that.

I'll leave this open for now, as while working on that codebase I definitely saw some slow analyzer behaviour (even without running the script) that I'd like to do some more digging into (at one point I did have the script running in the background I hadn't noticed, so I'm not certain it's not that yet, but will test).

**Comment by timsneath** [comment]
You beauty! That seemed to be it. I'm not running a subset of namespaces, but it's possible that there's some other reason why this was the case.

**Comment by DanTup** [comment]
> but it's possible that there's some other reason why this was the case.

Ah yes, it looks like `partitionList` can return a different number to what you asked for, even if there are more values than partitions. For ex.:

```
import 'dart:math';

/// Partition a list into the given number of sublists.
List<List<T>> partitionList<T>(List<T> list, int partitions) {
  final chunkSize = (list.length / partitions).ceil();
  return [
    for (var i = 0; i < list.length; i += chunkSize)
      list.sublist(i, min(i + chunkSize, list.length))
  ];
}

void main() {
  print(partitionList([1, 2, 3, 4, 5], 4));
}
```

This prints:

```
[[1, 2], [3, 4], [5]]
```

I asked for 4 partitions (and thus would've created 4 `SendPort`s), but only got 3. This is because it computes the ideal number per partition and rounds up, and that rounding up might consume enough extra items that it doesn't complete the list. This leaves an unused `SendPort` so never completes.

Given the fix above handles when there are less items than partitions, it's probably worth doing even if you did tweak this.

There may be some additional gains to have a queue that workers take from instead of pre-partitioning (since you might end up with some partitions that contain larger work items and running longer than the others, meaning you have free unused cores while a few partitions are still running towards the end). Maybe I'll try it out and send a PR if it makes much difference.

**Comment by timsneath** [comment]
:( I'm actually still it stall after completing all partitions, even after this change. I'm starting to wonder if there's some other problem either on my side or even in Dart that is preventing the Completer from working. Will experiment a bit more. 

One interesting thing that I've noticed is that Dart doesn't seem to schedule all the isolates simultaneously: it seems to only spin up a maximum of one isolate per core. When I set it to use 32 isolates, it spins up the first 16 isolates and then the 17th doesn't begin until the first one has completed. So very different to threads or processes. I might experiment with just spinning up an isolate for each namespace and let Dart take care of how many to simultaneously start.

**Comment by DanTup** [comment]
> I might experiment with just spinning up an isolate for each namespace and let Dart take care of how many to simultaneously start.

Yeah, if Dart is throttling them already that could be much simpler (I couldn't find any docs specifying that behaviour though). There is a [LoadBalancer](https://pub.dev/documentation/isolate/latest/isolate.load_balancer/LoadBalancer-class.html) class in `package:isolate` (and [IsolateRunner](https://pub.dev/documentation/isolate/latest/isolate.isolate_runner/IsolateRunner-class.html)) that may have been useful otherwise, although it looks like that package has been discontinued.

**Comment by DanTup** [comment]
btw, I ran the CPU profiler again today and noticed most of the remaining time is spent in formatting. If I skip the formatter, it goes from around 4:30 to about 20 seconds.

I believe the time is being spent with the formatter trying to figure out where to wrap the lines, and you have a lot of very long generated lines (I hit something very similar with generated code in the SDK - see https://github.com/dart-lang/dart_style/issues/1022).

I don't have any good ideas for a fix yet (besides turning off the formatter, increasing the line length for these files, or using strategically placed comments to try and force your own wrapping so the formatter has less to do), though I was trying to do some fiddling.

These are the slowest formatting files logged when I ran it, though curiously the few I tried were much faster when I did some in isolation (I haven't figured out why yet).

```
Took 0:00:11.113044 to format lib\src\devices\tapi\ITLegacyAddressMediaControl2.dart
Took 0:00:11.122603 to format lib\src\system\diagnostics\debug\IDebugSymbols3.dart
Took 0:00:11.415544 to format lib\src\system\contacts\IContactProperties.dart
Took 0:00:11.724381 to format lib\src\graphics\printing\IPrintOemUI2.dart
Took 0:00:11.795778 to format lib\src\ui\input\ime\IActiveIMMApp.dart
Took 0:00:11.891276 to format lib\src\graphics\directwrite\IDWriteTextAnalyzer1.dart
Took 0:00:12.085652 to format lib\src\system\diagnostics\debug\IDebugControl7.dart
Took 0:00:12.285743 to format lib\src\system\diagnostics\debug\IDebugSymbols4.dart
Took 0:00:12.286022 to format lib\src\system\diagnostics\debug\IDebugControl5.dart
Took 0:00:12.849460 to format lib\src\graphics\printing\IPrintCoreHelperPS.dart
Took 0:00:12.903048 to format lib\src\devices\webservicesondevices\IWSDiscoveryPublisher.dart
Took 0:00:12.960262 to format lib\src\graphics\printing\IPrintOemUI.dart
Took 0:00:13.220402 to format lib\src\graphics\direct3d11\ID3D11VideoContext.dart
Took 0:00:14.070188 to format lib\src\globalization\IMLangString.dart
Took 0:00:14.383735 to format lib\src\media\speech\ISpEnginePronunciation.dart
Took 0:00:14.534525 to format lib\src\system\diagnostics\debug\IDebugControl4.dart
Took 0:00:14.548985 to format lib\src\data\htmlhelp\IITResultSet.dart
Took 0:00:14.720748 to format lib\src\devices\sensors\ISensorManager.dart
Took 0:00:15.658683 to format lib\src\devices\tapi\ITTAPI.dart
Took 0:00:16.500488 to format lib\src\devices\enumeration\pnp\IUPnPServiceAsync.dart
Took 0:00:16.519045 to format lib\src\globalization\IMLangStringAStr.dart
Took 0:00:16.543855 to format lib\src\devices\enumeration\pnp\IUPnPRegistrar.dart
Took 0:00:16.817703 to format lib\src\system\diagnostics\debug\IDebugControl6.dart
Took 0:00:17.408012 to format lib\src\globalization\IMLangStringWStr.dart
Took 0:00:17.537560 to format lib\src\graphics\directwrite\IDWriteFontFace.dart
Took 0:00:18.135135 to format lib\src\storage\xps\IXpsOMObjectFactory.dart
Took 0:00:21.240190 to format lib\src\globalization\IMultiLanguage2.dart
Took 0:00:21.822872 to format lib\src\graphics\printing\IPrintCoreHelper.dart
Took 0:00:30.854109 to format lib\src\graphics\direct3d11\ID3D11DeviceContext.dart
Took 0:00:40.847763 to format lib/src/globalization/functions.g.dart
Took 0:00:41.106204 to format lib\src\graphics\directwrite\IDWriteTextAnalyzer.dart
Took 0:01:07.879362 to format lib\src\graphics\direct3d10\ID3D10Device.dart
```

**Comment by DanTup** [comment]
With a little more testing, I think the times shown above for formatting are hugely skewed because of the CPU contention. If I run with 32 isolates (as is coded) then it takes 5:10 total, and many files take a very long time to format (times above). However if I change it to run with only 4 isolates (which is how many cores I have), it takes 5:40 but no file takes more than a second to format.

From the log I can see that it's starting 16 isolates even though I only have 4 cores (this is the same number you see, so maybe it's fixed and not because of your 16 cores?), which I guess is why it's contended and some isolates are starving others. So there aren't any files taking huge amounts of time, just a large number of files taking a small chunk of time that adds up.

Perhaps its worth having a flag for formatting that you can disable (or increase line length) when debugging the generaiopn scripts (if formatting isn't hugely important) for iterating quicker.

Haven't dug into the analyzer performance yet, but planning to soon.

**Comment by DanTup** [comment]
@timsneath how has performance been for you on this lately (assuming you're using a version that includes the fix for https://github.com/dart-lang/sdk/issues/47804)? When working on some of the changes above I recall seeing the server being quite sluggish (for example syntax highlighting updating slowly) and I thought the script wasn't running. However, I can't reproduce this today (everything feels relatively snappy) and I wonder if I was mistaken and the generation script had been running at the time (before all of the optimisations).

If you're still seeing bad performance anywhere and might know how to trigger it, please let me know as I'd be interested in doing some more digging.

**Comment by DanTup** [comment]
@timsneath how have things been here lately? Are there are any specific things that still feel slow?

**Comment by timsneath** [comment]
Confession -- I've been working at the other end of the pipeline from this, building higher-level stuff that sits on top of this for the Windows launch, along with refactoring the projection code. I put this side down for a while, and it might be a few weeks before I pick it up again. You're welcome to leave this issue closed for now -- I know where to find it to reopen it (or create a new one) as needed...

**Comment by DanTup** [comment]
sure, nor rush. I'll leave it closed to avoid the bot spam, but do ping if/when it still seems like there's room for improvement. Thanks!
