### ISSUE TITLE
Wrong test get's executed after copying and changing the description of a test

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#3707]
I copied and changed the description of the text, but still the original test get's executed. Seems like a bug?

https://user-images.githubusercontent.com/28401593/144635311-79395802-c98d-4e8c-8e51-422294ba6c1e.mov

**Comment by DanTup** [comment]
Like #3709, I can't repro this. I suspect they may be related though.

Interestingly, for you to have had the icon here suggests that #3709 didn't occur this time? Is it intermittent?

**Comment by DanTup** [comment]
@HerrNiklasRaab can you repro this?

**Comment by HerrNiklasRaab** [comment]
Yes!

1. Copy a test
2. Run it using CodeLens
3. Change the name of the copied test
4. Run it using the vs code test icon (green tick)

=> The old copy of the test get's executed.

**Comment by DanTup** [comment]
Aha, thanks! I think I was missing running it in between. I think I have an idea of what's going on.

**Comment by DanTup** [comment]
I did some digging and this looked like a VS Code issue so I filed https://github.com/microsoft/vscode/issues/140155. Then I discovered it's not happening in Insiders, so think it was fixed by https://github.com/microsoft/vscode/commit/25d0e27e292fad4454151b85521014d4c92a3aa7.

If you're able to test in VS Code Insiders, it'd be good to know that it seems fixed for you there too. Thanks!
