### ISSUE TITLE
Remove hotkeys from README since they may differ per OS

### ISSUE THREAD

**Issue by shamrin** [Dart-Code/Dart-Code#371]
Many of the hotkeys mentioned in README are wrong on Mac. Some examples:

| Command | Windows | Mac |
| --- | --- | --- |
| Restart | Ctrl+Shift+F5 | Cmd+Shift+F5 (or really Cmd+Shift+Fn+F5) |
| Problems window | Ctrl+Shift+M | Cmd+Shift+M |
| Symbol search | Ctrl+T | Cmd+T |
| … | … | … |

I haven't used VSCode debugger before, so I was confused that Ctrl+Shift+F5 or Ctrl+Shift+Fn+F5 did nothing for me on Mac.

**Comment by DanTup** [comment]
Yeah; this confused me when I switched to Mac too (and the `Fn` thing confuses it even more - I toggled the option so the F keys behave as F keys by default, and use `Fn` for volume/etc.).

I think probably the best thing is just to remove the shortcut keys listed and let the user find them - it's easy enough to find things in the command palette and see the keys and they can be rebound (and I actually plan to remove some that we added ourselves, since they're raising warnings in Code that we shouldn't use them!).
