### ISSUE TITLE
Restart Frame greyed out when debugging cli apps.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#3721]
dart-code 3.29.0

When debugging a cli app the 'Restart Frame' option in the debugger is always greyed out.

![Screenshot from 2021-12-10 07-54-25](https://user-images.githubusercontent.com/900408/145474164-f9b7a716-1a64-4ba9-8717-531fea940161.png)
.

**Comment by DanTup** [comment]
@bsutton I can't see in the screenshot where your mouse/the button is - can you clarify? Is it on the top frame?

For reasons I don't completely understand, Dart doesn't allow restarting the top frame:

> https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md
> The frameIndex parameter is only used when the step parameter is Rewind. It specifies the stack frame to rewind to. Stack frame 0 is the currently executing function, so frameIndex must be at least 1.

You also won't be able to use it on any frame paste an async boundary (because the async call stack you see is not the "real" stack). It should work on anything else though.

**Comment by bsutton** [comment]
OK, that changes things.
It doesn't make sense that they don't allow the top frame to rewind but I
assume thats a dart limitation.

I've submitted an issue:
https://github.com/dart-lang/sdk/issues/47885
