### ISSUE TITLE
"Run All Tests" fails with "Integration tests and unit tests cannot be run in a single invocation"

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3727]
As part of migrating to the VS Code runner, "Run All Tests" will run integration tests too (unless the user hides them), but `flutter test` doesn't support both so we end up with:

> Integration tests and unit tests cannot be run in a single invocation. Use separate invocations of `flutter test` to run integration tests and unit tests.

We should split these into two runs, like we would with different projects tests.

**Comment by maks** [comment]
@DanTup apologies for digging up a closed issue, but I'd like to be able to do what you mentioned in this issues description and  "hide" my integration tests so that they aren't run when I do `Test: Run All Tests` in VSCode but I can't seem to find how to do that in any of the docs, would you know how to do that?

**Comment by DanTup** [comment]
You can right-click on tests in the VS Code test tree and choose "hide". This will hide them from the tree, and IIRC, prevent them from being run when you do Run All Tests.

If this doesn't seem to work right (or you think there are improvements to be made in this area), please do open new issues with details.
