### ISSUE TITLE
Formatting doc comments as Markdown

### ISSUE THREAD

**Issue by blaugold** [Dart-Code/Dart-Code#3743]
**Is your feature request related to a problem? Please describe.**
I'd love to have doc comments of Dart code be formatted by a Markdown formatter.
This would be especially helpful for tables, or when updating doc comments to reflow paragraphs.  

**Describe the solution you'd like**
If possible, I'd like to be able to select one of the installed formatting extensions and configure it 
to be used for doc comments in Dart files.

Maybe it would make sense to extend the Dart formatter to allow for formatting of doc comments,
through third-party tools.

I'd be open to working on this feature, with a few pointers into the right direction.

**Comment by DanTup** [comment]
Thanks for the issue! Formatting in the extension is delegated to the Dart Analysis Server (which ships in the SDK). Internally it uses the `dart_style` package.

I previously filed an issue at https://github.com/dart-lang/dart_style/issues/982 about having `dart_style` wrap comments, although it's not clear if that's the right place to do it. If not, it would likely be done in the Dart Analysis Server by parsing the Markdown and then re-wrapping text/paragraphs (while not touching anything in code blocks etc.). That's currently blocked on some extensions to the Markdown parser (https://github.com/dart-lang/markdown/issues/369).

Based on this issue and the request at https://github.com/dart-lang/dart_style/issues/655, it seems like maybe there's value in more than just wrapping comments, although I think the implementation would still need to be done in the Dart analysis server (or its dependencies).

It may be worth raising this issue in the SDK repo (both for discussion about exactly what should be formatter, and because the implementation is likely to be there). Some things (like formatting the code inside comments) might be a little subjective, so it might need to be done in a way that a user can toggle it on/off - this would also avoid potentially re-wrapping a ton of users code the next time they format.

**Comment by blaugold** [comment]
Thanks for this wonderful extension and the helpful information!
The mentioned issues already cover the features I'm most interested in, so I'm going to close this issue here.
