### ISSUE TITLE
default flutter project doesn't load

### ISSUE THREAD

**Issue by pleabargain** [Dart-Code/Dart-Code#3744]
Issue Type: <b>Bug</b>

new flutter project
name it
start it F5

chrome browser is empty
web server is empty

here's the video
https://youtu.be/lB7kLAv11Xk

and confirming the bug again
https://www.youtube.com/watch?v=59a3EP7rrw4

Extension version: 3.29.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.13.0-22-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (4 x 3951)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.32GB (0.94GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 160c9033-de95-4a63-98de-dcf785a4471d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30416614
vscexrecpromp3c:30407761

```

</details>

**Comment by DanTup** [comment]
Thanks for the great video showing the problem! It looks like you're using a relatively old non-stable build of Flutter:

![Screenshot 2021-12-29 at 12 22 26](https://user-images.githubusercontent.com/1078012/147661685-1e948697-fa9f-4550-b1da-92a5c01232d1.png)

There have been many fixes and improvements in web support for Flutter since then. Could you try [upgrading Flutter](https://docs.flutter.dev/development/tools/sdk/upgrading) (the current stable version is v2.8.1) and see if that resolves the issue? Thanks!
