### ISSUE TITLE
VSCode Intellisense can't recognise a removal of a part of directive

### ISSUE THREAD

**Issue by witchdrash** [Dart-Code/Dart-Code#3752]
Create a multi-part file with several classes each separated out into their own files e.g.

a.dart
```dart
part "./b.dart";
part "./c.dart";

class AClass {}
```

b.dart
```dart
part of "./a.dart";

class BClass {
CClass? cReference;
}
```

c.dart
```dart
part of "./a.dart";

class CClass {
AClass? aReference;
}
```

someother.dart
```dart
import '/a.dart';

class SomeThing {
AClass? aReference;
BClass? bReference;
CClass? cReference;
}
```

Intellisense works just fine for importing into each file, remove the part and part of and intellisense wont see AClass, BClass or CClass anymore even if you restart VSCode, to import them you have to add it manually, renaming the files to a2.dart, b2.dart, c2.dart fixes it and intellisense once again shows them on the import menu, but naming them back to a.dart, b.dart and c.dart causes the problem to re-emerge.

**Comment by DanTup** [comment]
I've moved this to https://github.com/dart-lang/sdk/issues/48027 since this seems like an analysis server issue (and one deep enough that I'm not familiar with its workings).

As a quick-fix to get your project back to a working state, if you close VS Code, delete the `~/.dartServer` folder from your machine and then restart VS Code, it should re-analyze things and be back to normal (note: the first analysis of each project and SDK may be slower after you clear that folder, as it's where some information is cached to make the server faster on subsequent loads).

**Comment by DanTup** [comment]
Seems like this has already been fixed in the latest code, so should show up in a future SDK release:

https://github.com/dart-lang/sdk/issues/48027#issuecomment-1004999148
