### ISSUE TITLE
Receiving 'Dart DevTools exited with code 255.'

### ISSUE THREAD

**Issue by komape** [Dart-Code/Dart-Code#3762]
**Describe the bug**
After opening VS Code I constantly receive the error message 'Dart DevTools exited with code 255. Would you like to try reactivating DevTools?' 

Reactivating just returns the same error.

Reinstalling the extension didn't help.

**To Reproduce**
1. Start VS Code
2. Wait a couple of seconds

**Screenshots**

![image](https://user-images.githubusercontent.com/25869589/147911710-26a8803a-18ea-4c7a-9fd6-7494d2de484e.png)

**Versions (please complete the following information):**
 - VS Code version: 1.63.2
 - Dart extension version: 3.32.0
 - Dart/Flutter SDK version: Flutter 2.5.3

**Comment by DanTup** [comment]
There was a bad version of DevTools published to Pub that was later retracted. However only the latest stable SDKs understand the retraction, so older SDKs are still resolving to the problematic version.

Until a new DevTools is published to fix this, the best options are:

- Upgrade to the latest stable Flutter (which ships its own version of DevTools and the one from Pub is no longer used)
- Run `dart pub global activate devtools 2.8.0` to downgrade to the working version and then set the `dart.updateDevTools` setting to `false` so that DevTools is not automatically updated

**Comment by DanTup** [comment]
A new version of DevTools has been published that fixes this, so it's no longer necessary to disable updates in the VS Code settings. Just run `dart pub global activate devtools` and leave the setting ticked and everything should be good.
