### ISSUE TITLE
can not trigger breakpoints when launch cwd start with lowercase disk label on Windows

### ISSUE THREAD

**Issue by xhcoding** [Dart-Code/Dart-Code#3796]
**Describe the bug**

When launch args 's cwd start with lowercase disk label, breakpoints can not be trigger

![image](https://user-images.githubusercontent.com/30917129/150509680-f75cca58-c85d-407c-bc3e-72b5f4d74681.png)

`cwd` is `d:\\Code\\Dart\\hello_world` can not trigger breakpoints, but `D:\\Code\\Dart\\hello_world` work well
`

**Comment by DanTup** [comment]
@xhcoding how did you trigger this? There is code that normalises the drive letter to avoid this:

https://github.com/Dart-Code/Dart-Code/blob/b0dab817e6cbe7915354c14fb759d8143fef07c7/src/extension/providers/debug_config_provider.ts#L212

I'm not sure how you got to the debug adapter with a lowercase drive letter - I would expect it to have been normalised by the code above.

**Comment by xhcoding** [comment]
Actually, I use  [lsp-dart](https://github.com/emacs-lsp/lsp-dart)  in emacs to debug dart. 

Should I  make a workaround at emacs client?

**Comment by DanTup** [comment]
Ah, I see. The underlying issue is that the VM currently handles things case-sensitive:

https://github.com/dart-lang/sdk/issues/32222

We could workaround it in the debug adapter, but I'm nervous about doing it there in case for some clients it works badly. I think it may be better to workaround in the clients for now, and reference that issue above?

**Comment by xhcoding** [comment]
Ok, I will do it. Thank you very much.
