### ISSUE TITLE
"Use Recommended Settings" docs don't explain that the extension must be activated

### ISSUE THREAD

**Issue by johnaaronrose** [Dart-Code/Dart-Code#3798]
I found an issue on http://dartcode.org/docs/recommended-settings/ for VS Code 1.63.2
I was not able to change to these settings using the methods described in that web page.

**Comment by DanTup** [comment]
@johnaaronrose can you describe exactly what the problem is? Did you run the **Dart: User Recommended Settings** command? This will add settings to your user settings JSON file which you can see by running the **Preferences: Configure Language Specific Settings** command and selecting **Dart**.

You can then just edit the settings in the JSON.

**Comment by johnaaronrose** [comment]
@DanTup When I do View->Command Palette, there is no option (in the drop down menu) for Dart: User Recommended Settings. The only option starting with "Dart:" is "Dart: New Project". Alternatively, when I do Preferences->Settings, there seems to be no way of copying the code (presumably that's the json code) in [https://dartcode.org/docs/recommended-settings/](url) to the User Settings.

**Comment by DanTup** [comment]
@johnaaronrose ah, gotcha. The extension needs to be activated for them to show up (to avoid cluttering the command palette with too much stuff when you might be working on non-Dart projects). If you open a Dart project/file, then they'll show up.

I'll keep this issue open to make it clearer in the docs. Thanks!
