### ISSUE TITLE
Dart syntax colors member variables with incorrect textmate scope.

### ISSUE THREAD

**Issue by Scott-Tenera** [Dart-Code/Dart-Code#3804]
Observe the following screenshot.
![dart_syntax](https://user-images.githubusercontent.com/85245614/151644028-c6c3eb77-a72a-438a-a7b2-18ff2f393041.jpg)

Member variables are given semantic coloring of function declaration.

This is reproducible with the following theme...

https://github.com/safield/ubuntu-monokai

**Comment by DanTup** [comment]
This seems to be a bad interaction between an original change for https://github.com/Dart-Code/Dart-Code/issues/3012 and the fix for https://github.com/Dart-Code/Dart-Code/issues/3618. The format was making property declarations coloured like methods to match the textmate grammar. However the latter had class fields marked as Properties to distinguish them from local variables.

I've removed the first, which means getter/setters will no longer be coloured like methods either (which is different to the textmate grammar, so they will change colour as semantic tokens become available), but considering the requirements I think it makes the most sense.

Before/After (the differences are on line 11-13):

![Screenshot 2022-01-31 at 10 28 28](https://user-images.githubusercontent.com/1078012/151777700-6d4d8a6a-b1e7-49ff-9f7d-4c3b2bb8bcaf.png)
