### ISSUE TITLE
Dart extension for VS Code causes "root hub lost power or was reset" error

### ISSUE THREAD

**Issue by palsivertsen** [Dart-Code/Dart-Code#3839]
**Describe the bug**
Launching a Flutter project in VS Code causes "root hub lost power or was reset" every 10 to 20 seconds. Monitors connected over usb-c will blank for some seconds, then return to normal. Issue persists until reboot.

**To Reproduce**
* Running on Arch Linux.
* Opening any Flutter project triggers the bug.
* Disabling the Flutter extension makes no difference.
* Disabling the Dart extension avoids triggering the bug.
* After the monitors comes back the message "root hub lost power or was reset" is printed in dmesg.

**Expected behavior**
Monitors should not blank. No "root hub lost power or was reset" errors in dmesg.

**Screenshots**

Dmesg:
```
[  312.279159] usb usb3: root hub lost power or was reset
[  312.279174] usb usb4: root hub lost power or was reset
[  334.625834] usb usb3: root hub lost power or was reset
[  334.625849] usb usb4: root hub lost power or was reset
[  357.185110] usb usb3: root hub lost power or was reset
[  357.185113] usb usb4: root hub lost power or was reset
[  379.852468] usb usb3: root hub lost power or was reset
[  379.852484] usb usb4: root hub lost power or was reset
[  401.825560] usb usb3: root hub lost power or was reset
[  401.825575] usb usb4: root hub lost power or was reset
[  424.492169] usb usb3: root hub lost power or was reset
[  424.492176] usb usb4: root hub lost power or was reset
[  446.198920] usb usb3: root hub lost power or was reset
[  446.198933] usb usb4: root hub lost power or was reset
[  468.385272] usb usb3: root hub lost power or was reset
[  468.385285] usb usb4: root hub lost power or was reset
[  490.838462] usb usb3: root hub lost power or was reset
[  490.838473] usb usb4: root hub lost power or was reset
[  513.428330] usb usb3: root hub lost power or was reset
[  513.428344] usb usb4: root hub lost power or was reset
[  536.065282] usb usb3: root hub lost power or was reset
[  536.065292] usb usb4: root hub lost power or was reset
[  557.318931] usb usb3: root hub lost power or was reset
[  557.318947] usb usb4: root hub lost power or was reset
```

**Versions (please complete the following information):**
 - VS Code version:
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-10T19:07:05.314Z
Electron: 13.6.9
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.40-electron.0
OS: Linux x64 5.16.10-arch1-1
 - Dart extension version: v3.34.0
 - Dart/Flutter SDK version:
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (12 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2

**Comment by DanTup** [comment]
Can you confirm whether it's _opening_ a Flutter project or _launching_ the Flutter app that's triggering this?

Are you able to check if the same thing happens in Android Studio opening the same project(s)?

The extension code here is some fairly simple TypeScript that runs in a VS Code node process (the extension host). I'm not sure there's going to be much scope to fix something like this here.

**Comment by palsivertsen** [comment]
> Can you confirm whether it's opening a Flutter project or launching the Flutter app that's triggering this?

It happens as soon as I _open_ a Flutter project.

> Are you able to check if the same thing happens in Android Studio opening the same project(s)?

Same thing happens when I open Android Studio.

I made weird observation. Closing Android Studio ends the crash loop, while closing VS Code does not.

**Comment by palsivertsen** [comment]
Filed a bug report in Android Studio issue tracker:
https://issuetracker.google.com/issues/220618419

**Comment by DanTup** [comment]
> Same thing happens when I open Android Studio.

If it's happening in both editors, I suspect the issue is not directly related to the editors, but perhaps something they're both spawning. There are a few things that both editors spawn in order to work with Dart/Flutter projects. Some things to try:

1. Check if it occurs if you open a non-Flutter Dart project (eg. use **Dart: New Project**). If it does not, it might be something specific to the tools spawned for Flutter.

2. If it's only Flutter, check whether running the device daemon triggers the issue:
  - Run `flutter daemon` from a terminal
  - Paste in `[{"id":"1","method":"emulator.getEmulators"}]` and then press `<enter>`
  - This should start the Flutter daemon running (which the editors use to get a realtime updated device list)
  - After confirming if this triggers it (or not), use `Ctrl`+`C` to close

3. If it's only Flutter, but the above doesn't trigger it, try running DevTools
  - Run `dart devtools --machine` from the terminal
  - After confirming if this triggers it (or not), use `Ctrl`+`C` to close

Please let me know the results. Thanks!
