### ISSUE TITLE
Wrap with widget seems broken

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3889]
**Describe the bug**
Substitution for 'Wrap with widget' doesn't occur properly.

**To Reproduce**
1. Click lightbulb when cursor is on a widget 
2. Click on 'Wrap with widget'

**Screenshots**
<img width="175" alt="Screen Shot 2022-03-25 at 23 59 50" src="https://user-images.githubusercontent.com/6655696/160236438-c3f97a6c-01f3-4aff-8eb3-706cb0279416.png">

<img width="178" alt="Screen Shot 2022-03-25 at 23 59 46" src="https://user-images.githubusercontent.com/6655696/160236451-652129d8-552b-4c8a-bef5-c786c5a798e1.png">

**Versions (please complete the following information):**
 - VS Code version:  1.65.2 
 - Dart extension version: v3.37.20220310
 - Dart/Flutter SDK version: 2.13.0-0.0.pre.252

**Comment by DanTup** [comment]
I made some improvements to snippets in the langauge server recently but it exposed a bug in the extension here. It only affects non-stable channels of Flutter so I haven't shipped a hotfix, but I have published pre-release versions of the extensions with the fix, see:

https://github.com/Dart-Code/Dart-Code/issues/3877#issuecomment-1072252207

I expect to do a stable extension release in the next week or so that will fix it there. Sorry for the bother!
