### ISSUE TITLE
Auto import for list firstWhereOrNull method throws a warning.

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3900]
When using the list extension method firstWhereOrNull, the dart-code extension only suggests the import statement..

`import 'package:collection/src/iterable_extensions.dart';`

When selecting this option, the extension gives the warning for the resulting import line...

`Don't import implementation files from another package.`

The correct import `import 'package:collection/collection.dart';` is not suggested.

**Comment by DanTup** [comment]
@safield can you confirm the version of the SDK you're using? This looks like https://github.com/dart-lang/sdk/issues/47842 which seems to have been fixed, although I'm not certain if it's in the SDK you're using yet.

**Comment by safield** [comment]
I did update version a day ago and now there is no incorrect recommendation. But there is also no correct recommended code action either.

**Comment by DanTup** [comment]
@safield can you confirm your SDK version and perhaps provide a small repro? In a simple test, it does seem to show up for me:

<img width="568" alt="Screenshot 2022-04-05 at 09 17 12" src="https://user-images.githubusercontent.com/1078012/161710238-a44e1107-c981-4461-90bd-1da4544be44c.png">

**Comment by safield** [comment]
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (2 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

Running on Ubuntu 21.10 with flutter install through the official snap package.

![firstWhereOrnull](https://user-images.githubusercontent.com/12876404/162332321-c4e79ced-023f-4e57-b6f5-b65e15a2aabb.jpg)

**Comment by DanTup** [comment]
Is `package:collection` definitely listed in your `pubspec.yaml` and you've fetch packages since adding it?

If so, are you able to share a small sample project this definitely occurs for you in that I can test with?

**Comment by safield** [comment]
It is not added to my pubspec.yaml.

I assumed it was a package that was part of the default SDK packages. I do not have it in my pubspec.yaml, but adding the following line to a dart file compiles and runs without error or warning...

`import 'package:collection/collection.dart';`

**Comment by DanTup** [comment]
Ah, that will be the issue. `package:collection` is just a Pub package, it's not included in the SDK.

The reason it works at runtime is that the package is being referenced by some other dependency, so the runtime is able to resolve it and find the source. However the analysis server (which provides the language features) will not suggest imports for packages you have not _explicitly_ listed in `pubspec.yaml`, because it would add additional (undeclared) dependencies to your code.

If you depend on a package, it should always be listed explicitly in your `pubspec.yaml`.

If you want to get a warning when you depend on something not in your pubspec (such as if you `import 'package:collection/...';`), you can enable the [depend_on_referenced_packages](https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html) lint.

Hope this helps!
