### ISSUE TITLE
Missing out dir in Flutter Extension 3.38

### ISSUE THREAD

**Issue by Avejack** [Dart-Code/Dart-Code#3907]
**Describe the bug**
The Flutter Extension for VSCode can not be activated in 3.38 because the out/src dir is missing.

**To Reproduce**
Install newest Version (3.38) and check console output of extensionhost.

**Expected behavior**
Extension gets activated.

**Versions (please complete the following information):**
 - VS Code version: 1.66.0
 - Dart extension version: 3.38
 - Dart/Flutter SDK version: 3.38

**Comment by DanTup** [comment]
Thanks for the report, I can repro. Looks like this broke when I was syncing some things between the extensions (https://github.com/Dart-Code/Flutter/commit/3f5d861048f8c1f1eec8e21fdffcd255d65e1da1). The Dart extensions compiled layout is slightly different and I didn't account for that.

I don't think the issue could cause any real problems (because the Flutter extension doesn't contain much implementation directly, everything is in the Dart one), but I'll push a fix first thing in the morning. Thanks!

**Comment by DanTup** [comment]
New Flutter extensions (v3.38.1 stable and v3.29.20220405 pre-release) have been published with this fixed. There was no update to the Dart extensions. Thanks for report!
