### ISSUE TITLE
Colons in named parameters get replaced with equal signs occasioanally

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#3917]
While editing code, the editor sometimes brakes previously valid code below the code being edited by replacing colons in parameter lists with equal signs. The editor also adds curly braces { ... } automatically when it should not (there should not be curly braces in a conditional statement inside an array definition).

Sample result (the code defines widgets inside  `Column.children`):

![image](https://user-images.githubusercontent.com/11364599/162400025-ef94de7a-f2c8-4f03-b84d-bec4f077ac09.png)

I don't know how to reproduce this exactly, but most probably you have to make some heavy editing into an initially valid code which brakes the code on purpose temporarily. Then you will see also some unexpected automatic "fixes". In this specific case I just copy/pasted a block of new code into the middle of an existing code and started editing it. This was expected to brake the existing code temporarily, but braking the parameter lists and adding invalid curly braces is of course not correct.

[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19043.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.66.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

Dart extension v3.36.0

**Comment by DanTup** [comment]
Edits made by the extension should onyl be in respond to some action - either explicitly (like invoking a Code Action or a Refactor), or by having them set to run automatically (for example `editor.codeActionsOnSave`).

Do you have any code actions set to run on-save, or do you know if you may have invoked any actions just before this happened?

If you're able to reproduce this, it may be useful to enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) and grab a copy of it next time you see this (note: the log will get very large and will contain parts of your source code).

Can you also check whether you have a default formatter selected that is not Dart?

<img width="477" alt="Screenshot 2022-04-08 at 12 18 53" src="https://user-images.githubusercontent.com/1078012/162425694-5fa637e0-db3b-411f-a5e3-1d4dbf10542b.png">

**Comment by kinex** [comment]
Yes I forgot to mention that I did save the file which triggered the "fixes". Here are my related settings:

```
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
  
    "source.fixAll": true
  },
  // Draw a guide line at 80 characters, where Dart's formatting will wrap code.
  "[dart]": {
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.rulers": [
      80
    ],
    "editor.selectionHighlight": true,
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.suggestSelection": "recentlyUsed",
    "editor.tabCompletion": "onlySnippets",
    "editor.wordBasedSuggestions": false
  },

```
The default formatter is set to "None". I have seen this same issue happening few times during last few months. Most of the time it works normally and I have not changed any VS Code settings for a long time.

It is easier to understand the bug causing invalid adding of curly braces (as that would be a valid refactoring in a normal if-statement outside an array declaration). On the other hand the bug causing to replace ":" with "=" in named parameters does not make any sense to me. Looks like some Kotlin formatter tries to format my Dart code.

**Comment by DanTup** [comment]
> Looks like some Kotlin formatter tries to format my Dart code.

Do you happen to have Kotlin (or other) formatters installed? Could you list all the extensions you have? (You can run `code --list-extensions` to get an easy list). There have been issues reported before that were caused by other extensions formatters being used (for example [Prettier encourages being set as the default formatter](https://github.com/prettier/prettier-vscode#default-formatter), though cannot format some languages properly like Dart), although I would expect that would be clear from the default formatter setting you checked.

If you're able to get a good repro, or capture a log file noted above, that might help understand what's happening.

**Comment by kinex** [comment]
I have at least Typescript formatter installed. 

Here is the list of extensions I have:
```
angelomollame.batch-replacer
Dart-Code.dart-code
Dart-Code.flutter  
dbaeumer.vscode-eslint
formulahendry.code-runner
mathiasfrohlich.Kotlin
ms-dotnettools.csharp
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode.cpptools
ramyaraoa.show-offset
redhat.java
ryanluker.vscode-coverage-gutters
toba.vsfire
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
```

**Comment by DanTup** [comment]
Thanks - I don't see anything obvious. I presume in the status bar you see "Dart" as the language for Dart files, and it hasn't selected something else?

The best thing is to try and get a log (see comment https://github.com/Dart-Code/Dart-Code/issues/3917#issuecomment-1092756841 above). If you take a copy of the file right after you next see it, there might be some indication of what happened in there.

Also - perhaps if next time you see it you hit Undo right after it happens, perhaps you'll have some exact code that triggers the issue that may also help.

**Comment by DanTup** [comment]
Ok, I think I may have reproduced this. There is a lint [`prefer_equal_for_default_values`](https://dart-lang.github.io/linter/lints/prefer_equal_for_default_values.html) which has a fix that can replace colons with equals. If this lint is enabled and you write some code that is intended to be a constructor call but is followed by curly braces so that it looks like a function definition, it will produce this lint warning. For example:

```dart
  Widget build(BuildContext context) {
    return ActionChip(
          avatar: const Icon(Icons.add),
          label: const Text('Danny'),
          onPressed: () async {},
        ){}; // these braces are bogus
  }
```

This code triggers `prefer_equal_for_default_values` and if you have `source.fixAll` in your `editor.codeActionsOnSave` then saving the file will cause the colons to be replaced, resulting in:

```dart
  @override
  Widget build(BuildContext context) {
    return ActionChip(
          avatar = const Icon(Icons.add),
          label = const Text('Danny'),
          onPressed = () async {},
        ){};
  }
```

I was only able to reproduce it in this specific case where there are extra braces though - do you think it's possible that might be what's triggering it for you (they don't need to be on the same line)?

@bwilkerson FYI - I don't know if this occurs enough to be worth trying to detect, though I noticed that the cases where this is an expression (eg. being returned, or in a list literal), you also get the `named_function_expression` error. If the lint (or fix) didn't appear in that case, that might prevent/reduce this (I don't know if there's a precedent for anything like that though).

**Comment by bwilkerson** [comment]
I agree that at first glance this seems like a fairly unlikely situation, but we do have an existence proof.

The first question I had to ask was why we're recovering that way. It took me a while to realize that it's because the code might have been:
```
@override
  Widget build(BuildContext context) {
    return ^
    ActionChip(
          avatar = const Icon(Icons.add),
          label = const Text('Danny'),
          onPressed = () async {},
        ){};
  }
```
That is, we ignore whitespace, so we don't want to assume that the code starting at `ActionChip` is part of the return statement. In most cases (imagine the `return` replaced by an `if`), I think that's the right recovery. It's less clear to me that it's valid after `return`.

So the first question is whether we can improve recovery in this case without damaging other cases.

If not, then can we detect this case in the lint rule so that the lint isn't reported here? Not reporting it when there's a syntax error would be reasonable. If the lint is valid then we can report it after the syntax errors have been fixed. And I'd rather special-case the lint than the fix.

**Comment by DanTup** [comment]
I'm not sure I understand what recovery is happening here, although I don't think the issue is restricted to being part of a `return` as long as there are the unwanted braces. For example:

```dart
  @override
  Widget build(BuildContext context) {
    ActionChip(
      avatar: const Icon(Icons.add),
      label: const Text('Danny'),
      onPressed: () async {},
    ){}
  }
```

Or perhaps more realistically:

```dart
  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        ActionChip(
          avatar: const Icon(Icons.add),
          label: const Text('Danny'),
          onPressed: () async {},
        ){}
      ],
    );
  }
```

Both of these will replace the `:` with `=` if you run Fix All. Both cases do also trigger `named_function_expression` and `named_parameter_outside_group` though. If suppressing the lint makes most sense, would it makes sense to do so based on the presence of either of those? (Is suppressing lints based on errors a pattern that already exists?).

**Comment by kinex** [comment]
@DanTup Ok, I'll try to do it next time I see it. I’m working on a variety of projects and I’ve only been able to use Dart occasionally lately, but nonetheless, I’ve seen the problem a few times in the last few months.
