### ISSUE TITLE
Generated constructors should appear at top of class

### ISSUE THREAD

**Issue by gskinner** [Dart-Code/Dart-Code#3977]
**Is your feature request related to a problem? Please describe.**
The Flutter style guide specifies that constructors should be the first thing in a class:
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#constructors-come-first-in-a-class

Currently if you "create constructor for final fields", it adds the constructor after the class fields.

**Describe the solution you'd like**
The constructor should be added at the top of the class.

![image](https://user-images.githubusercontent.com/157128/169567030-d7a51e56-a8ce-4720-8cbf-300a101b3066.png)
![image](https://user-images.githubusercontent.com/157128/169567064-c037d0c1-d737-4334-bfe4-6b8a88e03ffd.png)

**Comment by DanTup** [comment]
The style guide above is actually about the Flutter repo itself rather than guidelines for all Flutter projects.

However, if you want to follow this in your own projects you can enable the `sort_constructors_first` lint, which will cause any generated constructors to be inserted where you'd like:

![May-26-2022 12-20-10](https://user-images.githubusercontent.com/1078012/170478145-39079d16-2414-453a-ba90-2c888041b369.gif)

There was a suggestion to enable this lint in `flutter_lints`, but based on [this comment](https://github.com/dart-lang/lints/issues/76#issuecomment-1116733421) it seems like it may be left for users to decide on themselves.

Hope this makes sense!
