### ISSUE TITLE
"Add curly braces" does not appear as a Quick-fix for always_put_control_body_on_new_line

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3981]
**Describe the bug**

Single quick fixes don't always appear. In this case, for `always_put_control_body_on_new_line`. 

✅ Inline lightbulb
✅ <kbd>cmd</kbd><kbd>.</kbd>
❌ Hovercard ⇒ click "Quick fix"
  
  https://user-images.githubusercontent.com/6655696/169700652-c421d922-da30-47fe-a2e1-61cd0ef09cb7.mp4

❌ lightbulb in Problems panel
  <img width="458" alt="Screen Shot 2022-05-22 at 16 32 14 1" src="https://user-images.githubusercontent.com/6655696/169700661-0a807a53-b758-4ae9-b3cc-57dffea7ece0.png">

 - VS Code version: Version: 1.67.2 (Universal)
- Dart Code extension: 3.40.0
- Flutter extension: 3.41.20220516 (activated)

There seems to be a separate issue for multi-fixes ("everywhere in this file") that also applies to Android Studio, so filed https://github.com/dart-lang/sdk/issues/49079.

**Comment by DanTup** [comment]
I suspect this is because "Add curly braces" seen in the menu here is an Assist (and not a Fix) - eg. it'll show up even without the lint warning. The other menus you're opening are filtered to only show Fixes.

I think it should be possible to wire it up as a fix for that lint that would solve this.

**Comment by DanTup** [comment]
Re-reading this lint, I'm now wondering whether the "Add curly braces" fix is the obvious fix here. The lint isn't about using curly braces, but rather about having the code on a new line.

If you're using the formatter, then these things are quite tied together, but if you're not using the formatter you might expect a fix for "move the body to a new line" rather than adding curly braces.

There is another lint named `curly_braces_in_flow_control_structures` that I believe does what you want - it generates a similar warning but it _does_ provide "add curly braces" as a fix.

Does it make more sense for you to enable `curly_braces_in_flow_control_structures` is curly braces is what you really want?

(cc @bwilkerson for his thoughts on whether "Use curly braces" is a reasonable fix also for "always_put_control_body_on_new_line")

**Comment by guidezpl** [comment]
Ah thanks, using `curly_braces_in_flow_control_structures` works. 

IMO I still think the issue is valid, and both options should be shown as fixes in all places.

**Comment by DanTup** [comment]
@bwilkerson is there a way to mark "Add curly braces" as a fix for `always_put_control_body_on_new_line` _without_ it applying as an automatic fix for `dart fix` (and related commands)?

I think it would be reasonable to show in the fix list in VS Code (it does already show in the "Code Actions" list from being an assist, but not in places where the list is filtered to just fixes), however I'm less sure it makes sense to apply automatically for this lint because it doesn't exactly match the reported problem and there is a more specific lint for enforcing braces (`curly_braces_in_flow_control_structures`).

Personally, I think wanting to have control bodies on a new line _without_ braces is a reasonable choice. Outside of Dart, it's actually what I'd do.. I use braces in Dart only because the formatter doesn't support spanning two lines without braces.

**Comment by DanTup** [comment]
With https://github.com/dart-lang/sdk/commit/20b7de7b570afd582f8c7d3a58d182acfb01bda6, the "Add Curly Braces" fix will now show up as a fix for this lint:

<img width="889" alt="Screenshot 2022-05-30 at 13 51 41" src="https://user-images.githubusercontent.com/1078012/170996482-47c941c7-f68d-4947-9aeb-088eba35e870.png">

It won't be applied by `dart fix` (because I don't think it's clearly the correct fix for this lint, which is about newlines and not braces).

Although, while testing this I realised that `curly_braces_in_flow_control_structures` doesn't cover things on a single line, so if your code is:

```
if (true) print('');
```

Then enabling both lints still won't get `dart fix` to do what you want. I think the solution to that is probably a new fix for `always_put_control_body_on_new_line` that inserts a newline, then the example above could be `dart fix`able, without conflating the lints (eg. not assuming people with `always_put_control_body_on_new_line` want braces, or people with `curly_braces_in_flow_control_structures` want everything split across lines).

There's already an issue covering this at https://github.com/dart-lang/sdk/issues/47956, although there's a slight complication because of conflicts with the formatter.
