### ISSUE TITLE
Run tests using line/col to support groups/test with dynamic names

### ISSUE THREAD

**Issue by MiniSuperDev** [Dart-Code/Dart-Code#4021]
Added by @DanTup:

Some test cases to ensure are handled:

- [x] #4021
- [x] #4150
- [x] #4168
- [x] #4099
- [x] #4250

----

**Describe the bug**
I have some functions to give a specific format to the descriptions of the groups and tests, like indentation, in this way it is easier to read them in the console, but when I execute a specific test, giving run in that group or test it tells me:

```
No tests match regular expression "^groupDescriptionFormatted\('group 1'\)".
```

**To Reproduce**
this is a minimal example:
```dart
import 'package:test/test.dart';

String groupDescriptionFormatted(String description) {
  return description;
}

String subGroupDescriptionFormatted(String description) {
  return '\n    $description';
}

void main() {
  group(
    groupDescriptionFormatted('group 1'),
    () {
      group(subGroupDescriptionFormatted('sub group 1'), () {
        test('test', () {
          expect(true, isTrue);
        });
      });
    },
  );
  group(
    groupDescriptionFormatted('group 2'),
    () {
      group(subGroupDescriptionFormatted('sub group 1'), () {
        test('test', () {
          expect(true, isTrue);
        });
      });
    },
  );
}

```
If you press run or debug on a specific group or test, you can see the error, an also in the testing tab you can see that the names are the function instead of the real test name.
![image](https://user-images.githubusercontent.com/105388540/173844714-e5192e16-6fa2-4b6a-8f13-625708892c2e.png)

If you press run or debug on main, or use the command run all tests,  it runs normal but also in the testing tab keep the names are the function instead of the real test name, and now also the real tests names.

![image](https://user-images.githubusercontent.com/105388540/173848236-24ecdad3-bd02-458f-bdcf-2625a95b797b.png)

Thank you.

**Please complete the following information:**
Operating System and version: Windows 10
VS Code version: 1.68.0
Dart extension version: 3.42.0
Dart/Flutter SDK version: flutter 3.0.1

**Comment by DanTup** [comment]
Currently there are some limitations because of how tests are run individually (by name). Without executing the tests, it's impossible for the extension to know what `groupDescriptionFormatted('group 1')` returns, so it's not possible to build a dart test` command that has the correct test name to run.

However, once you've run the test file, you should be able to run the tests from the explorer, or from the test icons in the gutter, because the previous runs names would have been captured.

`package:test` does now have some other ways we can run tests (such as by line number/column) which may allow us to handle this better, but it'll need some work to move over (and ensure we don't try to do it for older versions of `package:test`).

I'll keep this issue open to track that, as it looks like there isn't an existing issue tracking it right now.

**Comment by jtdLab** [comment]
Will dynamic test/group descriptions be possible with this?

**Comment by DanTup** [comment]
@jtdLab I'm hoping so, but I haven't done much testing yet (and it may depend on the exact configuration of the test). If you have some specific tests in mind, you can try running them from the terminal using the line/col like:

```
dart test "path/to/test.dart?line=10&col=2"
```

Where line/col are where your test definitions are. If that runs them, then it should work here. If it doesn't work, please post an example and I can do some digging.

**Comment by jtdLab** [comment]
@DanTup im thinking about a scenario like this

foo_test.dart
```dart
// I want to run this test via the vs code Run | Debug (even though it has no description)
rendersText(MyWidget(), text: 'Foo');
```

my_shared_testing_library.dart

```dart
@isTest
void rendersText(Widget widget, {required String text}) {
  testWidgets('renders $text, (tester) async {
    // Some testing here
  }
}
```

Is this possible via line/col and not description?

**Comment by jtdLab** [comment]
When running via the clickable Run | Debug above the test on `v3.50.0` i get `No tests match regular expression "^const MyWidget\(\)( \(variant: .*\))?$".`

**Comment by DanTup** [comment]
@jtdLab that's expected right now, using line/col has not been implemented in the extension yet.

You can use `dart test foo_test.dart?line=1` from the terminal to verify where `package:tests`'s support for line/cols works for this example. If it does, then once I update the extension to use this (implementing this issue), then it should also work from the Run/Debug CodeLens links.

**Comment by jtdLab** [comment]
Perfect thank you a lot

**Comment by jtdLab** [comment]
@DanTup when running `dart test foo_test.dart?line=<LINE>` i get  `no matches found: foo_test.dart?line=<LINE>` on `test: ^1.21.6` so looks like this case is not covered there

**Comment by DanTup** [comment]
I tested this using latest Flutter master (I missed you were using Flutter, so it should've been `flutter test`) and it seems to work as you'd like:

<img width="780" alt="Screenshot 2022-10-04 at 12 31 16" src="https://user-images.githubusercontent.com/1078012/193809175-23cf3ef7-1410-4060-be99-b4686ec326f9.png">

So at least for a future version of Flutter, once this is implemented I believe what you're after works. (I tested it with `rendersText` in another file too, same result - I just inlined it here for the screenshot).

**Comment by DanTup** [comment]
In the next release (and the pre-release version just pushed today - v3.63.20240419), you can choose to have tests executed using their line numbers rather than their names. This fixes a number of issues including this one, caused by not always being able to statically compute the exact name of a test. 

![Test Invocation settings](https://user-images.githubusercontent.com/1078012/233161136-294c72e9-5a28-489b-bfc0-cd786636233c.png)

Please let me know if you find any issues with this functionality!
