### ISSUE TITLE
Flutter snippets use "const MyWidget({super.key});" instead of "const MyWidget({Key? key}) : super(key: key);"

### ISSUE THREAD

**Issue by CodeYimin** [Dart-Code/Dart-Code#4041]
**Is your feature request related to a problem? Please describe.**
It seems like unnecessary code when there is syntactic sugar available and a lot of the documentation writes it the syntactic sugar way.

**Describe the solution you'd like**
All snippets and other code actions that generate a widget class should use "const MyWidget({super.key});" instead of "const MyWidget({Key? key}) : super(key: key);".

**Comment by DanTup** [comment]
This has been done (via #3899 / https://github.com/dart-lang/sdk/commit/fa024be728cc0f7c5053d1ceb79f72cbd9746dbb), although it missed the branch for the last Flutter stable release, so will be included in the next (non-hotfix) SDK release.

The reason it's in an SDK release is that snippets now come from the language server so that they can be contextual. We can't just generate this code for all projects, as super params are only available if your Dart SDK constraint is >= 2.17.
