### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lemillioncorp** [Dart-Code/Dart-Code#4045]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.44.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Kozan/AppData/Local/Temp/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️file:///c%3A/Users/Kozan/AppData/Local/Temp/Dart-Code.dart-code-unresponsive.cpuprofile.txt

Are you able to attach this file? Thanks!

**Comment by larssn** [comment]
Also seeing high CPU loads from this plugin; but that has been going on for years, so I've just come to accept it. 😅

**Comment by DanTup** [comment]
@larssn if there are performance issues I'd very much like to resolve them, but I can only do so with reports and the information noted in the report. VS Code generates a CPU profile and includes the path in the message it generates so that it can be attached. Without it, it's very difficult to know what the issue is.

**Comment by larssn** [comment]
I'd very much like to help!

I don't get that notification though. I just notice that the plugin is often analyzing (constantly). Just got a new MacBook Pro, and it eats the entire battery fairly quickly. It IS a somewhat large project with close to 1000 classes and 140k lines of code.

Compared to a somewhat smaller typescript project of about 110k lines of code, which preserves my battery nicely.

I haven't been very vocal about it - figured nothing could done, and it was just the way it was put together. 🙂

**Comment by DanTup** [comment]
@larssn ah, that sounds like a different issue to this. The one that triggers VS Code's warning is when the extensions blocks the extension host (it's a bit misleading, since this doesn't actually mean high CPU, it could simple be doing sync filesystem work, blocking the thread but not consuming CPU).

Your issue sounds different so I would file a new issue with details. I would first check whether the issue occurs only in that specific project, or if you can repro in other projects (for example `flutter_gallery` is a little larger than the `flutter create` sample - does it occur there?).

You can enable the [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) to get detailed logs of all server traffic (and some info about what it's going internally). I wouldn't recommend leaving that log on permanently (it can generate large files), but it may be useful to enable and then work for a little to trigger the issue to get some timings on analysis. (note: it will contain parts of your source code, so don't blindly share the log if the projects is not public).

**Comment by larssn** [comment]
Alright, if I find anything (not sure what I'm looking for 😅), I'll create a new issue.

**Comment by lemillioncorp** [comment]
Não sabia... Então pode se referir a um destes problemas acima. Eu pensando
que é por causa de não aceitar o Upgrade do Flutter 3.0.5. Obrigado😁😁😁👌

Lars Støttrup Nielsen ***@***.***> escreveu no dia quinta,
28/07/2022 à(s) 12:51:
