### ISSUE TITLE
Extension error / Error that should not happen

### ISSUE THREAD

**Issue by Agut14** [Dart-Code/Dart-Code#4063]
**Describe the bug**
Everything seems to be correct in the project. But the vsCode gives me an error in the following file (Screenshot1). Gives me the following error (Screenshot 2): A value of type 'Null' can't be assigned to a parameter of type 'String' in a const constructor.
Try using a subtype, or removing the keyword 'const'.

**If I simply change the first element that gives an error, one line up, everything is solved** (Screenshot3)

**Screenshots**
Screenshot 1
![image](https://user-images.githubusercontent.com/86887600/179730016-0dd97c94-c17a-4e41-b4bc-c2343ef3eb98.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/86887600/179730218-d5ae41db-c864-4d98-8450-c40d12ed829f.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/86887600/179730554-2cf10b59-80e8-4e7a-93c2-bacfbae51dfb.png)
 
Screenshot 4 (Assets)
![image](https://user-images.githubusercontent.com/86887600/179732894-d14aa556-8ec3-48ec-b544-eb97217403d8.png)

**Please complete the following information:**
 - Operating System and version: Windows 10 Pro 21H1
 - VS Code version: 1.69
 - Dart extension version: 2.17.3
 - Dart/Flutter SDK version: Flutter 3.0.2 • Dart 2.17.3 • DevTools 2.12.2
 - Target device (if the issue relates to Flutter debugging):

cc: @minombrekeff

**Comment by DanTup** [comment]
I think the problem here is that `Assets.paraula` is not `const` and therefore is not valid to use in a `const` declaration here (see the second error at the bottom of the popup in screenshot 2). It's possible the first error is occurring because of the second (there is no constant string, so it is substituted with a null).

Please check `asserts.dart` and ensure `Assets.paraula` is `const`, or if it's not possible to make const you may need to replace `const` with `final` inside these declarations.

**Comment by Agut14** [comment]
@DanTup Sorry for not giving all the info, all the assets are const, look: 
![image](https://user-images.githubusercontent.com/86887600/179733000-859accc3-23bb-4388-b33f-2ca930ee7bcd.png)

**Comment by DanTup** [comment]
Could you try closing VS Code, then looking for a folder at `C:\Users\{username}\AppData\Local\.dartServer`. Delete the `.dartServer` folder, and then restart VS Code.

It may take a little longer to analyze your projects the first time you open them after doing this (since `.dartServer` contains some cached info to make analysis faster), but it may resolve the problem.

If it doesn't solve the issue (or the problem comes back in future), please let me know.

**Comment by Agut14** [comment]
@DanTup The truth is that the issue resolved itself, I don't know why or what caused it, but thanks for the answers!
