### ISSUE TITLE
Problem when running flutter app with isolates on disconnected android phone

### ISSUE THREAD

**Issue by jlabeit** [Dart-Code/Dart-Code#4066]
**Describe the bug**
When using the VSCode extension to start flutter applications on android devices without debugging and then disconnecting the android device it seems that isolates are not started properly anymore. 

The following line of code in the provided example app is not being executed anymore:
```dart
    await compute(mockJob, null);
```
When running the same app simply with `flutter run` everything works as expected.

**To Reproduce**
1. Checkout [this example flutter app](https://github.com/jlabeit/generator_isolate_bug).
2. Connect an android device via USB.
3. Run the example app with VSCode Flutter + Dart extension in mode "Run without debugging".
4. After the app starts disconnect the USB.
5. Click on the button "press" in the app and see nothing happens.

Note, providing logs is a bit hard because when the device stays connected to USB and attached then the problem doesn't occur.

**Expected behavior**
When pressing the "press" button the text should change. 
Note, the behavior works as expected when running the app with the command `flutter run` in debug or not debug mode. 

**Screenshots**
Running the app with:
![Peek 2022-07-21 22-42](https://user-images.githubusercontent.com/2670732/180311482-135b86c8-c919-4c85-80d1-977e8d5184b3.gif)

The expected output of the app after pressing the button:
![image](https://user-images.githubusercontent.com/2670732/180311704-eb74573b-d1bf-4984-a84d-567142bc113d.png)

**Please complete the following information:**
 - Operating System and version: Arch Linux
 - VS Code version: 1.68.0
 - Dart extension version: 3.44.0
 - Dart/Flutter SDK version: 2.10.5
 - Target device (if the issue relates to Flutter debugging): Pixel 4a (Android API 32)

**Flutter doctor**
```
[✓] Flutter (Channel unknown, 2.10.5, on ArchLabs Linux 5.18.7-arch1-1, locale en_US.utf8)
    • Flutter version 2.10.5 at /opt/flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/julian/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (1 available)
    • Pixel 4a (mobile) • 18101JEC203597 • android-arm64 • Android 12 (API 32)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by DanTup** [comment]
Thanks - I can reproduce this. The reason for this is that in the current debug adapters we connect the VM Service even when not debugging, so that service extensions can be used. This results in new isolates being paused, so if you've disconnected the debugger they will remain paused.

This is a decision that I changed my mind on recently. However, the debug adapters shipped in Dart-Code are being replaced by [debug adapters shipped in the SDK](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md) so I'm avoiding making any significant changes to them. The new SDK debug adapters do not have this behaviour (they do not connect to the VM Service at all when not debugging).

The SDK debug adapters will become default in a future release of Dart-Code, although you can opt-in to them sooner with the `dart.previewSdkDaps` setting. There are a few issues with them in the current stable SDKs I would generally recommend not using this flag unless you're using a version of Flutter of 3.3 or higher (currently this means master/dev/beta channel since stable is only 3.0).

It's not ideal, but in the meantime, running from the terminal is likely the best option if you need to keep running with the phone disconnected.

**Comment by jlabeit** [comment]
Hi @DanTup,

thanks for the quick response. Just knowing that this is an issue that can be reproduced and doesn't have a root cause in our development or built setup helps. I am fine with running from the terminal in the meantime.

**Comment by DanTup** [comment]
In the upcoming release, we will start enabling new SDK debug adapters (which resolve this issue) for all users gradually. You can opt-in immediately using the `dart.previewSdkDaps` setting, but otherwise you'll be moved to the new adapters automatically at some point in the coming months.

**Comment by husainazkas** [comment]
> In the upcoming release, we will start enabling new SDK debug adapters (which resolve this issue) for all users gradually. You can opt-in immediately using the `dart.previewSdkDaps` setting, but otherwise you'll be moved to the new adapters automatically at some point in the coming months.

Why this setting is enabled, and what advantages we will get? I just confuse why my flutter app suddenly cannot run with debugger vscode after all the time it work correctly. If run without debugger it works correctly, please give me explains and what I have to do for best result. I was set it false for a while until I get recommended action. Thanks!

**Comment by DanTup** [comment]
@husainazkas the new debug adapters should not be enabled by default for Flutter stable yet because there were some blocking issues. If you're seeing them being used on Flutter stable without having `"dart.previewSdkDaps": true` in your settings, please file an issue so I can take a look.

The advantages of the new debug adapters that that development will be much easier because they are written in Dart (which can directly use existing Dart SDK packages like DDS/vm_service) rather than lots needing to be re-implemented in TypeScript. Because they ship with the SDK, they will also always be a fixed version (matching the SDK) so we won't need to handle many different versions of SDKs in the debuggers.

There are already some new features that have only been built in the new adapters (such as breakpoint resolution and format specifiers). Hopefully they will be solid enough for the next stable release that they will start being enabled by default.

**Comment by husainazkas** [comment]
> @husainazkas the new debug adapters should not be enabled by default for Flutter stable yet because there were some blocking issues. If you're seeing them being used on Flutter stable without having `"dart.previewSdkDaps": true` in your settings, please file an issue so I can take a look.
> 
> The advantages of the new debug adapters that that development will be much easier because they are written in Dart (which can directly use existing Dart SDK packages like DDS/vm_service) rather than lots needing to be re-implemented in TypeScript. Because they ship with the SDK, they will also always be a fixed version (matching the SDK) so we won't need to handle many different versions of SDKs in the debuggers.
> 
> There are already some new features that have only been built in the new adapters (such as breakpoint resolution and format specifiers). Hopefully they will be solid enough for the next stable release that they will start being enabled by default.

I didn't change any settings for dart or flutter on vscode settings (in Default Settings `dart.previewSdkDaps` shows null, and there is no `dart.previewSdkDaps` in User Settings). How it could be run with new debug adapters even I just run debug as usual?

After I set `dart.previewSdkDaps` to false in User Settings, I able to run flutter app with debugger.

**Comment by DanTup** [comment]
> I didn't change any settings for dart or flutter on vscode settings (in Default Settings dart.previewSdkDaps shows null, and there is no `dart.previewSdkDaps` in User Settings). How it could be run with new debug adapters even I just run debug as usual?

I'm not sure. Could you open a new issue about this? Please include a log file, captured from a new counter app:

- Remove `"dart.previewSdkDaps": false` from your user settings (temporarily, to debug this issue)
- Create a new counter app with the **Flutter: New Project** command
- Run the **Dart: Capture Debugging Logs** command to start logging
- Press `F5` to start debugging the app and wait for the app to start
- Click **Cancel** on the logging notification to stop logging and open the log file
- Attach the log file to a new issue

Thanks!
