### ISSUE TITLE
Breakpoints not working in flutter source code.

### ISSUE THREAD

**Issue by Stitch-Taotao** [Dart-Code/Dart-Code#4071]
First , Thanks @DanTup's explain in #3194  .
Now my project can't add berakpoint either , it always show invalid breakpoints,I strugled long time but not resolve ,please help me , Thanks.
I do a smallest demo , it's just a office counter demo , I just add a brekpoint and one-line print code in Flutter Source Code ,print code executed but breakpoint not work.
Here is the video : [Video](https://youtu.be/sBRJuq6NF4k)
Here is the Dart: Capture Debugging Logs :
[Dart-Code-Log-2022-06-02 14-39-12.txt](https://github.com/Dart-Code/Dart-Code/files/9187267/Dart-Code-Log-2022-06-02.14-39-12.txt)

**Comment by Stitch-Taotao** [comment]
After I set "dart.maxLogLineLength": 99999999 in User settings.json
And I run add breakpoint and run code as previous video's order.
 
Dart: Capture Debugging Logs :
[Dart-Code-Log-2022-06-02 17-25-38.txt](https://github.com/Dart-Code/Dart-Code/files/9188484/Dart-Code-Log-2022-06-02.17-25-38.txt)
one little problem: weird wrong time file filename,

**Comment by DanTup** [comment]
I don't know if it's the issue, but it looks like we're setting this library as not-debuggable:

```
{
	"type": "@Library",
	"fixedId": true,
	"id": "libraries/@147125171",
	"name": "",
	"uri": "package:flutter/src/material/app.dart"
}


{
	"id": "158",
	"jsonrpc": "2.0",
	"method": "setLibraryDebuggable",
	"params": {
		"isolateId": "isolates/2151887024807295",
		"libraryId": "libraries/@147125171",
		"isDebuggable": false // not debuggable
	}
}
```

I think this is because your debugging settings are set to "My Code + SDK". What this really means is "My Code + Dart SDK". Flutter is treated as a "package". If you click on the status bar here:

![Screenshot 2022-07-26 at 11 19 30](https://user-images.githubusercontent.com/1078012/180983447-4ca4fc3f-8629-4e4d-ab72-cc8bf3ae979e.png)

and change it to "My Code + SDK + Packages", does that resolve the issue?

**Comment by Stitch-Taotao** [comment]
Thank you , It work!!!

**Comment by DanTup** [comment]
Great, thanks for confirming. We do have a prompt to try and detect this ("You have a breakpoint outside of your workspace but debug settings are set to 'my code'") but it doesn't catch the case where you have SDK included and not packages.

I've filed https://github.com/Dart-Code/Dart-Code/issues/4074 to improve this, so you would have been prompted to change your debug settings automatically in this situation.
