### ISSUE TITLE
VScode error message "Socket error: FileSystemException: Directory watcher closed unexpectedly, path = ....."

### ISSUE THREAD

**Issue by ehabelnahas** [Dart-Code/Dart-Code#4077]
Hello,
When I start debugging a flutter mobile (no windows/web) app on vscode, the error message "Socket error: FileSystemException: Directory watcher closed unexpectedly, path = 'd:\....'" appears and the console log don't show all logs while debugging the app.

flutter doctor -v shows no issues.

I found similar old posts by others but I couldn't find a solution on it, also they suggested to post the issue into dart-code issues page.

Appreciate your support to solve the issue.

**Comment by DanTup** [comment]
Thanks for the report - I believe this is the same issue as https://github.com/dart-lang/sdk/issues/49286 which has recently been fixed (but hasn't made a stable release). It's likely triggered by projects that modify a lot of files in the `build` folder during a Flutter build.

**Comment by ehabelnahas** [comment]
Hello, sorry but you have closed the issue and mentioned [dart-lang/sdk#49286](https://github.com/dart-lang/sdk/issues/49286) where I can't find an actual solution to this !!

**Comment by DanTup** [comment]
@ehabelnahas sorry, I should have been clearer.

There is a bug in the current Dart/Flutter stable releases that can trigger this error during a build. This issue was previously reported at https://github.com/dart-lang/sdk/issues/49286. I have recently fixed the issue in the Dart SDK (https://github.com/dart-lang/sdk/commit/019cfb998d493dd1b776439998eef32b0fa1e18b), but it has not been released yet. The fix will show up in a future release of the Dart/Flutter SDK.

Unfortunately I don't know of a temporary workaround.

**Comment by ehabelnahas** [comment]
It's ok, thanks for making that clear :)
