### ISSUE TITLE
Flutter Daemon is Failed to Work after Upgrading Dart Code Extension to 3.46.1

### ISSUE THREAD

**Issue by deavega** [Dart-Code/Dart-Code#4091]
Yesterday morning my Visual Code Studio automatically upgraded dart code extension to 3.46.1, and after that Flutter Daemon suddenly stopped working. I tried to open my project in Android Studio but somehow got the same problem (the android emulator could be opened in Android Studio but could'nt be connected to flutter project). I opened my other projects to check if errors come from my code but the daemon still not run.
I tried all posible solutions from internet (i.e. deleting .gradle and reinstall flutter and editing its PATH) but with no luck.

The error log report as in the attachment:
[daemon failed log.txt](https://github.com/Dart-Code/Dart-Code/files/9274391/daemon.failed.log.txt)

Expected behavior
Flutter daemon can be run again to start debugging.

Other information:
 - Operating System and version: Windows 11 Home version 10.0.22000 Build 22000
 - VS Code version: 1.70.0 
 - Dart extension version: 3.46.1
 - Dart/Flutter SDK version: 3.0.5-stable

**Comment by DanTup** [comment]
From the log, I think your Flutter installation may be corrupt. The log contains:

```
[11:27:33 AM] [FlutterDaemon] [Error] Checking Dart SDK version... 
<< was unexpected at this time.
```

I suspect if you run `flutter doctor` you'll get a similar error. The problem is likely that there are git conflict markers in one of the internal files in the `bin` folder in your Flutter SDK. I would suggest trying the steps here to repair it:

https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by deavega** [comment]
Yes you are right. I suspect the git conflict. I reinstalled flutter sdk, extension, create new project and just relocated all libraries. Now all is good thanks
