### ISSUE TITLE
"No tests match regular expression...", customize regex

### ISSUE THREAD

**Issue by jibbers42** [Dart-Code/Dart-Code#4099]
I get the "No tests match regular expression..." error when using [Glados](https://github.com/MarcelGarus/glados) (property-based testing) and attempting to run a test via test code lens.

It seems they modify the name of the test [here](https://github.com/MarcelGarus/glados/blob/503180fc8c1051b7c9bdccb3bd14d7d95135722d/glados/lib/src/glados.dart#L167).

Is there a way for me to modify the regex used to account for their modification, or another solution?
(I'm using Dart SDK without Flutter)

Thanks!

**Comment by DanTup** [comment]
Sorry for the delay, I somehow missed this issue. I think the best solution is probably #4021, which avoids us having to "predict" the names of tests when running (instead, we will run them based on the line number they're on). I haven't had chance to try this out yet, but I'll keep this issue open as a reminder to test this once that work is done.

**Comment by DanTup** [comment]
In the next release (and the pre-release version just pushed today - v3.63.20240419), you can choose to have tests executed using their line numbers rather than their names. This fixes a number of issues including this one, caused by not always being able to statically compute the exact name of a test. 

![Test Invocation settings](https://user-images.githubusercontent.com/1078012/233161136-294c72e9-5a28-489b-bfc0-cd786636233c.png)

Please let me know if you find any issues with this functionality!

**Comment by jibbers42** [comment]
Thank you!
