### ISSUE TITLE
VSCode extension: refactor options not shown in custom code action menu

### ISSUE THREAD

**Issue by lowski** [Dart-Code/Dart-Code#4104]
**Describe the bug**
The refactor options like "Wrap with...", "Remove this widget", etc. do not show up in the new code action menu.

**To Reproduce**
1. Enable `editor.experimental.useCustomCodeActionMenu`
2. Open the refactor menu somewhere

**Expected behavior**
The refactor options should appear in the new menu.

**Screenshots**
`"editor.experimental.useCustomCodeActionMenu": false`
<img width="216" alt="image" src="https://user-images.githubusercontent.com/37808546/184534385-a3e83d84-7ac7-4d93-beb9-c0cc5223593b.png">

`"editor.experimental.useCustomCodeActionMenu": true` 
<img width="195" alt="image" src="https://user-images.githubusercontent.com/37808546/184534411-0f824fb9-584a-4483-95af-f6e80b2688e2.png">

**Please complete the following information:**
 - Operating System and version: macOS 12.5
 - VS Code version: 1.71.0-insider
 - Dart extension version: 3.46.0

**Comment by DanTup** [comment]
Since the item shows up when the new setting is disabled, it's likely this is a VS Code bug in the new rendering. My guess it's that this code here is not handling the "other" group (items that don't match one of VS Code's known refactoring prefixes):

https://github.com/microsoft/vscode/blob/4b6ab496d0f8cad1ff1b7335a2adcdd452c18bd2/src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts#L408

Please file an issue with VS Code, and post the link back here. Thanks!

**Comment by Andrehlb** [comment]
The SliverGridDelegateWithMaxCrossAxisExtent is not displayed in the VSCode autocomplation.

**Comment by DanTup** [comment]
@Andrehlb that sounds like a different issue to this, please file a new issue including a screenshot and SDK version(s). Thanks!

**Comment by DanTup** [comment]
This issue was fixed in VS Code via https://github.com/microsoft/vscode/issues/158129
