### ISSUE TITLE
Hot Restart doesnt save file anymore

### ISSUE THREAD

**Issue by Mayb3Nots** [Dart-Code/Dart-Code#4105]
**Describe the bug**
I used to be able to save all opened dart files when a hot restart is called. But now I can't, I'm not sure if it's regression or a setting I changed.

**To Reproduce**
1. Open a flutter project.
2. Make changes to file
3. Click hot restart
4. File wont be saved

**Expected behavior**
All file with unsaved changes should save when hot restart is pressed. Or a setting to enable this behavior/

**Please complete the following information:**
 - Operating System and version: Windows 11
 - VS Code version: 1.70.1
 - Dart extension version: v3.46.1
 - Dart/Flutter SDK version:  3.0.5

**Comment by Astonished2see** [comment]
its happening to me too, any solution?

**Comment by DanTup** [comment]
I can't reproduce this. Can you confirm whether the issue is that your changes are just not visible in the running app, or whether the dirty indicator on the tab is not disappearing?

Can you also check this setting in VS Code, which seems designed to control this behaviour (as far as I know, the value I have selected is the default, and seems to work as expected):

<img width="734" alt="Screenshot 2022-08-22 at 18 43 48" src="https://user-images.githubusercontent.com/1078012/185985507-f9700ac6-a5f6-4e9b-9b3b-e2c8ffa42fde.png">

Thanks!

**Comment by Mayb3Nots** [comment]
Hi @DanTup It seems like the issue is fixed and I cant reproduce it anymore. Not sure if it was a edge case or what. Im going to close this but if anyone has the same issue you can add a reproduction step and I'll open it back.
