### ISSUE TITLE
Test files main is run even when specific launch config is selected and invoked via menu

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#4124]
If you have a Dart unit test file open with a `main` function, even if you click the "green arrow" in the Runs and Debug (as in screenshot below) to try to run a specific Flutter launch config, it will still run the tests in the tests files `main()` instead of the selected launch config.

![image](https://user-images.githubusercontent.com/71999/187132552-5025e044-b53f-46e1-a6d3-50d298dbf4c5.png)

**Comment by DanTup** [comment]
@maks can you post the contents of your `launch.json`? Does this config have an explicit `program`? It's intended that if the launch config being run does not have a `program` we will try to infer one. If you have an explicit one, we should definitely use it though - in which case can you capture a log:

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Try running from the green play button and wait for the session to start
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

Thanks!

**Comment by maks** [comment]
@DanTup sorry to not get back to you on this sooner.

I do have explicit `program` set for some but not all launch targets. Is it the case if I have some targets set with a `program` I shouldn't rely on the default behaviour of `lib/main.dart` being used?

Here are contents of the launch.json (redacted to remove proprietary names)
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "YYYY_app",
      "request": "launch",
      "type": "dart",
      "toolArgs": [
      ]
    },
    {
      "name": "LOCAL Firebase iOS YYYYApp",
      "request": "launch",
      "type": "dart",
      "toolArgs": [
        "--dart-define",
        "USE_FIREBASE_EMULATOR=true",
        "--dart-define",
        "USE_FIREBASE_EMULATOR_HOST=localhost"
      ]
    },
    {
      "name": "LOCAL Firebase Android YYYYApp",
      "request": "launch",
      "type": "dart",
      "toolArgs": [
        "--dart-define",
        "USE_FIREBASE_EMULATOR=true",
        "--dart-define",
        "USE_FIREBASE_EMULATOR_HOST=10.0.2.2"
      ]
    },
    {
      "name": "YYYY_app (profile mode)",
      "request": "launch",
      "type": "dart",
      "flutterMode": "profile"
    },
    {
      "name": "YYY_app (release mode)",
      "request": "launch",
      "type": "dart",
      "flutterMode": "release"
    },
    {
      "name": "YYYYYYY Web",
      "request": "launch",
      "type": "dart",
      "deviceId": "chrome",
      "program": "lib/main_yyyy.dart",
      "toolArgs": [
        "--dart-define",
        "YYYYYYYY_MODE=true",
        "--web-port=42424"
      ]
    },
    {
      "name": "YYYYY Web (release mode)",
      "request": "launch",
      "type": "dart",
      "deviceId": "chrome",
      "program": "lib/main_yyyy.dart",
      "flutterMode": "release",
      "toolArgs": [
        "--dart-define",
        "YYYYY_MODE=true",
        "--web-port=42424"
      ]
    },
    {
      "name": "Storyboard",
      "request": "launch",
      "type": "dart",
      "program": "lib/main_storyboard.dart"
    },
  ]
}
```
I'll try to get the capture logs to you in the next day or 2.

**Comment by DanTup** [comment]
> Is it the case if I have some targets set with a `program` I shouldn't rely on the default behaviour of `lib/main.dart` being used?

Do you mean for targets _without_ a `program`? If you have an explicit `program` it should always run that. However if you don't have one set, the default behaviour is not to run `lib/main.dart`, there are a set of rules. It's something like this:

- If the open file is a test file, run that (being a test file usually means inside `test` or `integration_test` and ends with `_test`, although there are some settings to support tests outside of the test folders etc.)
- If the open file is in `bin/` or `tool/`, run that
- Otherwise, locate the best project root (which may start from the open file), and then look in some default locations (`bin/main.dart`, `lib/main.dart`)

So generally, if you want to always run a specific file, you should add an explicit `program`. Otherwise, you'll get our best guess at what you want to run.

**Comment by maks** [comment]
Thanks for the explanation @DanTup , that all makes sense!
I think my issue is that my "main" `YYYY_app` config didn't specify a `program`. Although for some reason now, I can't seem to replicate the behaviour I was seeing without it, I'll just make sure to always have an explicit `program` as that's really what I want anyways given I use a number of different "main_yyyy" Dart files.

**Comment by DanTup** [comment]
Yep, you should always specify a `program` if you don't want us to try to infer one from the open file/project. Generally I'd only suggest a launch config without a `program` if you want to be able to use `F5` and have the entry point inferred, but need to set some additional args/env/etc. that wouldn't otherwise be set by default.

Let me know if anything still doesn't seem to work as expected!
