### ISSUE TITLE
Customized snippets aren't showing up

### ISSUE THREAD

**Issue by warcayac** [Dart-Code/Dart-Code#4151]
**Describe the bug**
Customized snippets aren't showing up
![Screenshot_20220908_112058](https://user-images.githubusercontent.com/7342885/189175924-7a077238-6e48-4d52-be51-26fc277754e1.png)

![Screenshot_20220908_112717](https://user-images.githubusercontent.com/7342885/189176014-4dcff978-5bdb-46ba-8a4e-92280a929923.png)

**To Reproduce**
1. Open `~/.vscode/extensions/dart-code.dart-code-3.48.3/snippets/dart.json`
2. Modify snippet for **Class** and save the file
```
"class": {
	"prefix": "class",
	"description": "Insert a class definition.",
	"body": [
		"class ${1:Name} {",
		"  $0",
		"  /* ---------------------------------------------------------------------------- */",
		"  $1();",
		"  /* ---------------------------------------------------------------------------- */",
		"}"
	]
},
```
3. Reopen VSCode 
4. Try to create a Dart class by using snippet from contextual menu
5. Structure for the class created is the default and not is reading the customized one.

**Expected behavior**
Something _similar_ to this:
![Screenshot_20220908_112437](https://user-images.githubusercontent.com/7342885/189176297-d2507dc8-49ba-4594-8646-92e52b28ad5c.png)

**Please complete the following information:**
 - Operating System and version: EndeavourOS Linux x86_64, kernel: 5.19.7-zen2-1-zen
 - VS Code version: 1.71.0
 - Dart extension version: 3.48.3
 - Dart/Flutter SDK version:  Dart 2.18.0 / Flutter 3.3.1

**Comment by DanTup** [comment]
This is expected behaviour. Modifying the extension source is not a support way to have custom snippets. You can create your own snippets following the instructions here:

https://code.visualstudio.com/docs/editor/userdefinedsnippets

If you want to disable the built-in snippets, you can do that using the following settings:

<img width="1206" alt="Screenshot 2022-09-08 at 18 40 09" src="https://user-images.githubusercontent.com/1078012/189189899-67ab876e-bbc0-4d2b-8eb3-7fc3a173add6.png">

Note that snippets contributed in these JSON files are not context-aware. That means that the `class` snippet will show up in places where it is not valid to insert classes. This is solved by using the server snippets, but they are not customisable (outside of a few differences affected by lints, such as using `var` vs `final` etc.).

Hope this makes sense!
