### ISSUE TITLE
TO-DOs should be weighted below everything else.

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#417]
I love that I can pull up my Todos in the Problems Panel, and in most circumstances they show up below more pressing things like Warnings and Errors. However, between a Lint and a Todo, they have equal weight and that can sometimes make finding lints difficult. I actually can't tell any distinguishable order that files and lints are given in. [See Screenshot.](http://i.imgur.com/Xuul0kg.png)

**Comment by DanTup** [comment]
Possibly we can set these as HINT instead of INFORMATION based on `.type` ([see here](https://github.com/Dart-Code/Dart-Code/blob/2e97351481fd9f4aa51ef1504ba877daf6d48672/src/providers/dart_diagnostic_provider.ts#L42)).

I'm back home soon, so I'll try and test it out over the next few days (if you don't beat me to it!).

**Comment by DanTup** [comment]
I've made TODOs appear below all others:

![Demoted TODOs](https://user-images.githubusercontent.com/1078012/30173426-84a9f448-93ef-11e7-84cc-bdb789b5c31d.png)

There's another type called "HINT" in the analysis server (separate from LINT) but I can't find info on what returns that type so I don't know whether to also demote it from INFO to HINT. In VS Code we have Error, Warning, Info, Hint and TODOs are the only thing mapped to Hint. @bwilkerson - do you know what HINT is used for?

**Comment by bwilkerson** [comment]
Yep. The Dart Language Specification specifies errors and warnings. The analyzer does additional error checking beyond what's required by the spec, but to keep from conflating the two we called our checks "hints" rather than "warnings".

Server has several "types" of errors: error, warning, hint, lint, and todo. It also has a notion of severity for historic reasons, but I'd recommend using the type for sorting purposes.

I'm not sure how I'd map these five types into VS Code's four categories, but I'm also not familiar with how those categories impact the UX. (For example, if they only control the icon, then the mapping isn't very important, but if they control the sorting then it's much more important.)

**Comment by DanTup** [comment]
@bwilkerson Ok, I'll move off the severity to types, though looks like errors and warnings are split up (so severity would actually make for simpler code):

```ts
export type AnalysisErrorType =
	"CHECKED_MODE_COMPILE_TIME_ERROR"
	| "COMPILE_TIME_ERROR"
	| "HINT"
	| "LINT"
	| "STATIC_TYPE_WARNING"
	| "STATIC_WARNING"
	| "SYNTACTIC_ERROR"
	| "TODO";
```

Code has for levels (error, warning, info, hint) which are used for sorting as well as icon (though info/hint have same info icon).

The change I made here drops TODOs down below Lints (I'm making the assumption lints are considered more important than TODOs, which I presume is what @Skylled thinks; though I don't know how common that idea is). Are Hints things that people will likely fix before committing, or that might hang around for a long time like TODOs (I'm assuming they're more short-lived from your description - just warnings that aren't spec'd and probably targets for fixing before committing)?

**Comment by bwilkerson** [comment]
Hints are generally warnings based on addition type information that analyzer computes that the spec doesn't allow for, but also includes things like pointing out dead code. We've tried to only include things that are not reasonable for devs to leave in their code indefinitely.

As for lints, given that they're opt-in, I'd guess that devs will either fix them or disable the generation of them if they don't care enough to fix them.

**Comment by Skylled** [comment]
Every hint/lint I've seen has been something that would be helpful for usability/readability/cleanliness.
TODOs vary from something I need to change ASAP to something that I may not get to for a few months but don't want to forget about.
If I've done something to trigger a hint or lint, I want to know about it, thus higher priority to float to the top.

But if there are varying opinions or better ideas on it, I'm open to them.

**Comment by DanTup** [comment]
It sounds to me like we all have the same opinions (and that hints from the analyzer should stay as info in Code), so I think this change is good as-is :-)

**Comment by Skylled** [comment]
Side effect of this change: To-Dos no longer add to your Problems count.

I'm good with this, but thought I'd make a note of it, in case someone is confused and goes in search of a reason.

**Comment by DanTup** [comment]
Thanks for the info! Seems like a reasonable change to me anyway :-)
