### ISSUE TITLE
[windows] lost connection to device 

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [Dart-Code/Dart-Code#4222]
**Describe the bug**
i get 
"Lost connection to device.
Exited (sigterm)"
but the app don't crash 

**To Reproduce**
when ever I use flutter with vscode "developing a windows app" and push a third page to navigator and try to update any page component like color, after hot reload i get this message but if i used android studio it works with no problems

**Please complete the following information:**
 - Operating System and version: win 11
 - VS Code version: VSCodeUserSetup-x64-1.72.2
 - Dart extension version: v3.50.0
 - Dart/Flutter SDK version:  3.3.4 • channel stable
 - Target device (if the issue relates to Flutter debugging): windows

**Comment by DanTup** [comment]
Could you try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

ThanksCan you also confirm whether you can reproduce this in a new project created with the **Flutter: New Project** command, or if it's specific to this project?

**Comment by Ahmed-elshorbagy** [comment]
@DanTup 
[Dart-Code-Log-2022-09-01 21-34-07.txt](https://github.com/Dart-Code/Dart-Code/files/9803923/Dart-Code-Log-2022-09-01.21-34-07.txt)
the problem doesn't occur with new projects
if you need the long log version i can send it

**Comment by DanTup** [comment]
@Ahmed-elshorbagy thanks for the log. Unfortunately there's nothing obvious around the time it disconnects.

Since this doesn't happen with new projects it may be difficult for me to track down without a repro. Are you able to make a copy of your project that experiences this issue and trim it down to something small you can share that still triggers the issue?

**Comment by Ahmed-elshorbagy** [comment]
@DanTup 
I was able to reproduce the problem in a new project and track it to a single line in `1stpage.dart` file
the line is 
`(await PlatformDeviceId.getDeviceId)`
it is from another library it works fine in android studio but not in vscode
these are the project files

[lib.zip](https://github.com/Dart-Code/Dart-Code/files/9816656/lib.zip)

**Comment by DanTup** [comment]
Thanks - I was able to reproduce this, although it doesn't seem specific to using VS Code, I can also reproduce it from the terminal:

- run the app with `flutter run -d win`
- click the buttons to navigate through the pages
- press `r` in the terminal to hot reload (no need to modify a file)
- wait a minute

I'm not sure what's causing it, but it doesn't seem like it is fixable here in the VS Code extension. I see there's an open issue at https://github.com/BestBurning/platform_device_id/issues/21 so I would follow up there. There may be issues with the native Windows code used by the plugin that are causing this that are best debugged by the author of that package (or, if they deem it to be a Flutter bug they may be able to produce a small repro that can be used to file a Flutter issue).

That said, I can't explain why it doesn't occur from Android Studio. @stevemessick is there any way I can get AS to log the full output from the `flutter run` process (ideally with `-v`) to see if there's anything obviously difference when running from there?

**Comment by DanTup** [comment]
>  @stevemessick is there any way I can get AS to log the full output from the flutter run process (ideally with `-v`)

Oh, and the VM service traffic, since there might be stuff happening in there that's affecting this too.

**Comment by stevemessick** [comment]
@DanTup Oops, I missed this. You can find the `flutter run` command in the IDE log file. Search for `flutter [--no-color, run`. I believe all the output from that command is printed to the IDE console. But it does not include -v. (The plugin does have a verbose logging option, but I don't remember if enabling it adds -v.) I have previously identified problems in flutter_tools that were caused by IDE-only flags, so you might see if any of the flags differ.

The only way to get the VM service traffic is to run from sources and add print statements.
