### ISSUE TITLE
Analyzer plugin doesn't work correctly in LSP mode

### ISSUE THREAD

**Issue by alexisbg** [Dart-Code/Dart-Code#4223]
**Is your feature request related to a problem? Please describe.**
I write some custom lint rules. To achieve this, I use the [analyzer_plugin](https://pub.dev/packages/analyzer_plugin) package. But the JSON generated by this package use Dart server Legacy protocol. Fortunately Dart Code offers a setting to start the Dart analysis server with the Legacy protocol instead of default/recommended LSP:
`"dart.useLegacyAnalyzerProtocol": true`

But this setting description advises to use LSP because the Legacy protocol will eventually be removed some day.

**Describe the solution you'd like**
How long time Legacy protocol will be still supported?
Will I lose a lot of features by not using LSP?

**Describe alternatives you've considered**
Did I maybe miss something? Can analyzer_plugin generate LSP JSON?

**Comment by DanTup** [comment]
> But the JSON generated by this package use Dart server Legacy protocol. Fortunately Dart Code offers a setting to start the Dart analysis server with the Legacy protocol instead of default/recommended LSP:

It should not be necessary to have the Dart extension communicate with the analysis server using the legacy protocol for plugins to work. The LSP layer in the analysis server is expected to still communicate with plugins using the legacy protocol (which happens to be the only protocol supported for plugins) and then translate its results into LSP objects.

If you've found that your plugin does not work without setting `"dart.useLegacyAnalyzerProtocol": true`, please provide some steps for how I can reproduce this and I will take a look.


> How long time Legacy protocol will be still supported?

No timeline has been decided for ending support for the legacy protocol yet, but the goal is that when this happens it should be seamless without any less of functionality. For those that need to use old Dart/Flutter SDK versions that do not include the LSP server, there will be the option of installing older Dart/Flutter extensions in VS Code that still contains this support.


> Will I lose a lot of features by not using LSP?

New features (such as Call Hierarchy, Type Hierarchy, Inlay Hints) are only being added to LSP, so over time you'll be missing out on more and more features. I'm hopeful that this won't matter because you'll be able to use LSP with no loss of plugin functionality though :-)

**Comment by alexisbg** [comment]
@DanTup thank you for your help.

But it still doesn't work if I switch back to LSP with `"dart.useLegacyAnalyzerProtocol": false`.

Here is my config:
- VS Code on remote WSL
- Dart Code 3.50
- Dart SDK 2.18.2
- analyzer 5.1.0
- analyzer_plugin 0.11.2

Below the relevant excerpts of code.

tools/analyzer_plugin/bin/plugin.dart:
```dart
void main(List<String> args, SendPort sendPort) {

  start(args, sendPort);
}
```

lib/src/lint_analyzer_plugin_start.dart:
```dart
void start(List<String> args, SendPort sendPort) {

  ServerPluginStarter(
    LintAnalyzerPlugin(resourceProvider: PhysicalResourceProvider.INSTANCE),
  ).start(sendPort);
}
```

lib/src/lint_analyzer_plugin.dart:
```dart
class LintAnalyzerPlugin extends ServerPlugin {

  @override
  Future<void> analyzeFile({required AnalysisContext analysisContext, required String path}) async {

    // Filters dart files
    final isValidPath = fileGlobsToAnalyze.fold<bool>(false,
      (previousValue, element) => previousValue || Glob(element).matches(path),
    );
    if (!isValidPath) return;

    _logger.info('[analyzeFile] $path');

    channel.sendNotification(
      AnalysisErrorsParams(path, [
        AnalysisError(
          AnalysisErrorSeverity.INFO,
          AnalysisErrorType.LINT,
          Location(path, 0, 10, 1, 1, endLine: 1, endColumn: 11),
          'This is the description of our lint',
          'my_lint_code',
          correction: 'A correction message',
          hasFix: false,
        ),
      ]).toNotification(),
    );
  }
}
```

And finally [here is a link to a gist containing the analysis server logs](https://gist.github.com/alexisbg/2bace86df0a7390873cdd41b24b9f334) enabled with Dart Code `"dart.analyzerLogFile"` setting.
As you can see at the very bottom with my custom logs, analyzeFile method is called as expected. And there are above some `"textDocument/publishDiagnostics"` notications. But their `"diagnostics"` parameter is an empty list instead of containing the error.

I guess this is the issue. But I don't how to fix it.

**Comment by DanTup** [comment]
Thanks for the info - I'll take a look at this shortly. If the behaviour is different, it does sound like a bug I need to fix. I'll let you know what I find!

**Comment by DanTup** [comment]
@alexisbg I don't seem to be able to reproduce this issue. I created a simple plugin using your code above here:

https://github.com/DanTup/dart-analyzer-plugin-sample

If I open this in VS Code (after fetching packages etc), then the lint shows up fine:

<img width="474" alt="Screenshot 2022-10-20 at 15 46 22" src="https://user-images.githubusercontent.com/1078012/196981520-138a5f95-4773-429b-956c-95899f83eb61.png">

And in the logs I can see it's all using LSP:

```
[3:47:01 PM] [Analyzer] [Info] <== Content-Length: 378
Content-Type: application/vscode-jsonrpc; charset=utf-8
[3:47:01 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"my_lint_code","message":"This is the description of our lint\nA correction message","range":{"end":{"character":10,"line":0},"start":{"character":0,"line":0}},"severity":3,"source":"dart"}],"uri":"file:///Users/danny/Desktop/dart_samples/dart-analyzer-plugin-sample/target/foo.dart"}}
```

Could you try using my sample to see if that works for you? You'll likely need to fix the absolute path at the end of `target/pubspec.yaml` (I wasn't sure if relative paths would work because of how plugins are loaded).

If this works, are you able to either track down what's different in your sample, or provide a complete code sample I can use to debug?

Thanks!

**Comment by alexisbg** [comment]
@DanTup: I apologize for this late reply. Thank you very much for the sample project, it helped me a lot.

I found the origin of the issue. Since it is impossible to debug, I added some `stdout.writeln(...)` in my source code. They print [Info] level lines to [the very bottom of the Analyser log file](https://gist.github.com/alexisbg/2bace86df0a7390873cdd41b24b9f334). But they are why the `"diagnostics"` parameters of `"textDocument/publishDiagnostics"` are empty.

If I replace them by `stderr.writeln(...)`, there are still printed lines in the Analyser log file but with [Error] level. And the `"diagnostics"` of `"textDocument/publishDiagnostics"` finally contain their AnalysisError.

**Comment by alexisbg** [comment]
@DanTup Thank you for the advice.

But I think the [instrumentation log](https://dartcode.org/docs/settings/#dartanalyzerinstrumentationlogfile) is too verbose and will be confusing.

So I write the debugging info to my own log file at the root of the project that uses my analyzer plugin by getting the ContextRoot with:
```dart
@override
Future<AnalysisSetContextRootsResult> handleAnalysisSetContextRoots(
  AnalysisSetContextRootsParams parameters,
) async {

  logFiles.clear();

  for (ContextRoot contextRoot in parameters.roots) {
    logFiles.add(File(join(contextRoot.root, 'lint_analyzer.log')));
  }

  return super.handleAnalysisSetContextRoots(parameters);
}
```

**Comment by DanTup** [comment]
That seems like a reasonable workaround too. FWIW, I sometimes attach the debugger to the analysis server for debugging. I've never tried it for a plugin, but in theory I think it should work (by setting the `"dart.analyzerVmServicePort"` setting to a port number, then using the **Debug: Attach to Dart Process** command from another instance of VS Code that has the plugin code opened, and enter `http://localhost:{x}` (where `{x}` is the port number you used) as the VM Service URL.

(and if it doesn't work, it's probably something that needs fixing)
