### ISSUE TITLE
Prompt user for bundle identifier when creating a Flutter app that targets iOS

### ISSUE THREAD

**Issue by leighajarett** [Dart-Code/Dart-Code#4228]
The `flutter create` command already uses the `org` parameter to get the bundle identifier for an iOS app. However, this isn't exposed when a user creates a Flutter app using the VSCode command prompt.

The bundle identifier may be needed during various stages of the development process, and without it the developer may have additional steps that require troubleshooting. When iOS developers are using XCode, they are prompted to enter the bundle identifier from the beginning, which likely provides for a better developer experience. 

One option for solving this in the `Create Flutter App` command in VSCode might be to prompt the developer to enter the bundle identifier.

**Comment by DanTup** [comment]
Do you just mean the `org` value, or something more? You can set the organisation in VS Code user settings:

<img width="536" alt="Screenshot 2022-10-20 at 12 26 11" src="https://user-images.githubusercontent.com/1078012/196936264-63e3d618-370b-41ca-b10b-7cc84ec4212e.png">

And it's also accessible from the cog icon when entering a name for your project:

<img width="650" alt="Screenshot 2022-10-20 at 12 28 09" src="https://user-images.githubusercontent.com/1078012/196936664-4662a3f6-163b-475d-9f8a-de5d7907c1e8.png">

<img width="615" alt="Screenshot 2022-10-20 at 12 28 53" src="https://user-images.githubusercontent.com/1078012/196936711-dfa4deb5-531d-4081-846f-91e0306c8c87.png">

There isn't an explicit prompt because I'd like to keep the number of steps when creating a project small and not prompt for things that are unlikely to change.

Let me know if this doesn't address what you're asking for. Thanks!
