### ISSUE TITLE
Devices pop up not opening

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4230]
**Describe the bug**
In this example, I cannot change my target device because the selector will not come up:
![devices-vs-code](https://user-images.githubusercontent.com/43759233/197043713-b4e2d0ad-ad84-4054-a05e-72733f06d18c.gif)

**To Reproduce**
I am developing devtools - my vs code project is opened up to the devtools_app directory

**Expected behavior**
devices selector shows up and I can change target devices

**Please complete the following information:**
 - Operating System and version:
 - VS Code version: see below
 - Dart extension version: v3.51.20221010
 - Dart/Flutter SDK version: flutter 3.5.0-9.0.pre

VS Code:
Version: 1.72.0 (Universal)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:21:58.256Z (2 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

**Comment by DanTup** [comment]
Hmm, that's odd. I can't repro this. Just to be clear - the picklist appears at the top of the screen and not next to the status bar? (I suspect you'd notice it if it was opening there, but I know it's not the most obvious thing.. the APIs are limited but we may have some new things to improve this in future).

Otherwise, could you try:

- Reproduce the issue
- Click Help -> Toggle Developer Tools
- Go to the Console tab
- See if there are any unhandled errors reported there

And/or:

- Reproduce the issue
- Press `F1` to open the command palette
- Search for and run the **Dart: Open Extension Log** command
- See if there are any errors logged at the bottom around the time you repro'd the issue

And/or finally, enable the Daemon log:

- Press `F1` to open the command palette
- Search for and run the **Preferences: Open User Settings (JSON)** command
- Add `"dart.flutterDaemonLogFile": "logs/flutter_daemon.txt",` to the JSON
- Restart VS Code (or run the **Developer: Reload Window** command from the command palette)
- Wait for the daemon to re-initialize
- Reproduce the issue
- Review/send me the log

Thanks!

**Comment by DanTup** [comment]
@kenzieschmoll are you still seeing this? If so, can you grab the log above (or ping me if may be easier to screenshare and figure out what's up).

**Comment by kenzieschmoll** [comment]
If I see it again I will ping you. Thanks.
