### ISSUE TITLE
Keyboard shortcuts for QuickFix menu items

### ISSUE THREAD

**Issue by GotJimmy** [Dart-Code/Dart-Code#4246]
I would love to see keyboard shortcuts in the quick fix menu for faster access. This used to work for some items months ago before the quick fix icon started appearing infront of each menu item (i.e.: once the menu popped up I simply would press "R" to remove this widget. 

It would be even better to have the individual items of the menu (i.e.: "wrap with column", "remove widget", etc.) as separate items in the command palette where I could assign keyboard shortcuts to each item (i.e.: ctrl-shift-r for "remove widget").

**Comment by DanTup** [comment]
Unfortunately this menu is controlled entirely by VS Code and not something extensions can alter. There's an open issue about navigating by typing the items names no longer working here:

https://github.com/microsoft/vscode/issues/157719

Please add 👍 's to that issue!


> It would be even better to have the individual items of the menu (i.e.: "wrap with column", "remove widget", etc.) as separate items in the command palette

I don't think it's a great idea to duplicate them all there. We also have to pre-declare all commands in the palette in the extensions manifest, but these quick-fixes are dynamic (coming from the Dart language server) so it would rely on hard-coding a bunch of things that could change in future (or vary depending on your SDK version).

If you just want to assign shortcuts to specific items you can already do this by invoking the `editor.action.codeAction` command and passing the correct `kind`:

```js
  {
    "key": "cmd+r cmd+r",
    "command": "editor.action.codeAction",
    "args": {
      "kind": "refactor.flutter.removeWidget"
    },
    "when": "editorTextFocus"
  },
```

There's more info, including a list of all the kinds here:

https://dartcode.org/docs/refactorings-and-code-fixes/

And some more docs here:

https://code.visualstudio.com/updates/v1_20#_keybindings-for-quick-fixes-and-code-actions

You can use the `"apply"` field to control what happens if there are multiple items matching your `kind` (since you can enter a partial `kind`) - either apply the first one, or show the menu.

Please let me know if between these it doesn't address your issue. Thanks!

**Comment by GotJimmy** [comment]
The`editor.action.codeAction` works perfectly for me! Just didn't know about this option.
Thank you so much for your help! :)

**Comment by DanTup** [comment]
Great, thanks for confirming! Hopefully VS Code will address the other issue in time too.
