### ISSUE TITLE
Improve how relationships are shown in Type Hierarchy

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4254]
**1:** Current Subtypes:

![Screenshot 2022-11-08 at 17 00 27](https://user-images.githubusercontent.com/1078012/200628442-16dc8bf1-5bb6-4e5f-bcba-ca9f44dea5ad.png)

**2:** Current Supertypes:

![Screenshot 2022-11-08 at 16 59 58](https://user-images.githubusercontent.com/1078012/200628347-36ecff8f-76d0-4848-819c-d6a576ad7e09.png)

**3:** Subtypes with expanded details including parent node name

![Screenshot 2022-11-08 at 17 11 18](https://user-images.githubusercontent.com/1078012/200630895-45727d91-6bb4-4307-bda3-e9b1ef382cc1.png)

**4:** Supertypes with expanded details including parent node name

![Screenshot 2022-11-08 at 17 16 37](https://user-images.githubusercontent.com/1078012/200631791-d45efb58-bdaa-4e5e-a344-deca03a0b4cd.png)

**5:** Subtypes without details

![Screenshot 2022-11-08 at 17 39 58](https://user-images.githubusercontent.com/1078012/200636695-6c8e95bc-5215-4521-ac2b-f5823af09018.png)

**6:** Supertypes without details

![Screenshot 2022-11-08 at 17 39 21](https://user-images.githubusercontent.com/1078012/200636566-07e7859b-9bab-4f99-b07b-f071038e4edb.png)

**Comment by scheglov** [comment]
I worry that repeating names of parent classes in children looks acceptable in mocks, when they are short, but not always works in actual packages, e.g. for `class _DraggableScrollableSheetScrollPosition extends ScrollPositionWithSingleContext`.

**Comment by bwilkerson** [comment]
I agree, 4 is quite verbose, at least in part because we have to make it clear that the relationship is reversed from how it's normally presented in code.

It's also fairly hard to read, probably because of it being a combination of text and code.

The latter is why I suggested (in the CL) printing the whole code-based description. I'm not convinced that it would look good.

> I worry that repeating names of parent classes ...

That's valid. Some class names are very long and would require horizontal scrolling to become visible.

Which prompts me to ask a question that was previously (in the CL) touched on: are we having problems because we're trying to put too much information in the view? Would the UX be better if we just displayed the names of the classes without type parameters / arguments and without the kind of subtyping relationship? Or is this information valuable enough to the user to make it a problem that we need to solve?

**Comment by DanTup** [comment]
> Which prompts me to ask a question that was previously (in the CL) touched on: are we having problems because we're trying to put too much information in the view? Would the UX be better if we just displayed the names of the classes without type parameters / arguments and without the kind of subtyping relationship? Or is this information valuable enough to the user to make it a problem that we need to solve?

Good question. I thought it was valuable info, but if we can't present it well maybe it's better not to have. I've added screenshots 5+6 above to show what it looks like without.

**Comment by bwilkerson** [comment]
Those are definitely less cluttered. I'm not sure knowing which keyword was used to introduce the relationship is something I'd miss. I suspect I'd be OK navigating to the class to answer that question, but what we really need in order to answer the question is a set of use cases we're trying to solve.

I don't happen to know what those are, other than finding out what the type graph looks like.

**Comment by DanTup** [comment]
Yeah, I think I'm also leaning towards dropping them now. I've filed https://github.com/microsoft/vscode/issues/165840 about tooltips and we could add it into there if that's implemented. We can also review if requests come up to show more.

I'll file a CL to remove it for now. This means many of the changes in https://github.com/dart-lang/sdk/commit/197344ba22f126cac1287705d90c14fc7dd5f789 may have been unnecessary (at least for now), but perhaps it's still better to have the more specific information in the index (and we may make use of it in future).

**Comment by DanTup** [comment]
https://dart-review.googlesource.com/c/sdk/+/268760
