### ISSUE TITLE
Shell commands in launch.json args are escaped

### ISSUE THREAD

**Issue by sbatezat** [Dart-Code/Dart-Code#4260]
I'm trying to execute this launch configuration in VSCode (launch.json)

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "application",
            "request": "launch",
            "type": "dart",
            "program": "lib/main.dart",
            "args": ["--web-port", "8000", "$(flutter pub run define_env)"]
        }
    ]
}
```

Command (flutter pub run ...) is escaped on args (and so not executed). It seems to be defined here: https://github.com/Dart-Code/Dart-Code/blob/f4088253d0d01203de1145315cc31743d808bd3a/src/shared/processes.ts#L11
It's a similar issue than https://github.com/microsoft/vscode/issues/149910

We should be able to define if args have to be escaped or not.

This feature is already available for:
- JS https://github.com/microsoft/vscode-js-debug/issues/1335
- Python https://github.com/microsoft/debugpy/issues/1001

**Comment by DanTup** [comment]
It's true that we don't currently support `argsCanBeInterpretedByShell`, however that setting is specific to the `runInTermal` request:

https://microsoft.github.io/debug-adapter-protocol/specification#arrow_right_hook-runinterminal-request

`runInTerminal` is not supported for Flutter because the debug adapter needs to be in full control of the process (because [it communicates with Flutter over `stdin`/`stdout`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md)).

So, while we could add support for `argsCanBeInterpretedByShell` it would only work for Dart apps, when you set `"console": "terminal"` in your launch configuration.

There's some discussion in #3189 about using `.env` files (including mention of https://pub.dev/packages/envify although I can't vouch for it) that might help achieve what you're trying to do if you don't want to put your environment variables inside your VS Code settings or launch configuration.

**Comment by DanTup** [comment]
Oh, that's great to know - thanks for the pointer. I'll direct people there if this comes up again. Thanks!
