### ISSUE TITLE
Dart Devtools error with code 127

### ISSUE THREAD

**Issue by Faamica** [Dart-Code/Dart-Code#4278]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

If I open VS Code, then the error occurs
I did extension bisect.
but except Dart, other extension is ok..

Extension version: 3.25.1
VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin arm64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|8.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 75a68472-790b-47a9-acf8-8ab270842f23|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381

```

</details>

**Comment by DanTup** [comment]
Can you post a screenshot of exactly what you're seeing? Thanks!

**Comment by DanTup** [comment]
@Faamica thanks - I see the problem. You're on an old (around 1 year old) version of the Dart extension. This extension tries to run DevTools using `pub`, but the `pub` command was removed from the Dart SDK since.

If you upgrade to the latest version of the Dart (and Flutter) VS Code extensions, I expect the problem will go away. It's possible you first need to update VS Code (since that's also out of date) and the latest versions of the Dart/Flutter extensions require a more recent version of VS Code (because they need new APIs from VS Code).

Please let me know if you still see this issue on the latest versions. Thanks!

**Comment by DanTup** [comment]
Great, glad it was a simple fix :-)
