### ISSUE TITLE
The Line Length indicator in the editor is not respecting my custom line length

### ISSUE THREAD

**Issue by clovett** [Dart-Code/Dart-Code#4288]
**Describe the bug**
I set my `Dart: Line Length` to 120, but the editor has a vertical line indicator and it is not moving to 120, even though lines are formatted to 120 when I hit save.

**To Reproduce**
1. Change your  `Dart: Line Length` to 120.
2. Open a Dart file and check the vertical line length indicator position.

**Expected behavior**
The line should move to reflect my custom  `Dart: Line Length`  setting.

**Screenshots**
![image](https://user-images.githubusercontent.com/3336415/204667820-1617c2cb-df9f-42fd-ad1f-b99661f34c94.png)

**Please complete the following information:**
 - Operating System and version:  Windows 11, Version 21H2, build 22000.1219
 - VS Code version: 1.73.1
 - Dart extension version: v3.54.0
 - Dart/Flutter SDK version: Dart SDK version: 2.18.3 (stable) (Mon Oct 17 13:23:20 2022 +0000) on "windows_x64"
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
The line in the screenshot is unrelated to the formatter, it's a VS Code "ruler". We set the default to show this at the same location that the formatter wraps by default, but since it's a VS Code setting we can't update it if you change the Dart formatting settings.

You can change this with the VS Code `editor.rulers` setting (nested in `[dart]` so that it applies only to Dart - and overrides our defaults) in your VS Code user settings:

- Open the command palette (`F1`)
- Run the **Preferences: Open User Settings (JSON)** command
- Add the following
    ```js
    "[dart]": {
    	"editor.rulers": [ 120 ]
    },
    ```

If you already have a `"[dart]"` section in the JSON, then just add `"editor.rulers": [ 120 ]` (and any necessary trailing commas to keep it valid JSON) to that.

Please let me know if this doesn't resolve the issue for you. Thanks!

**Comment by clovett** [comment]
Hmm, interesting, I haven't used that feature before, you set the ruler when your extension got installed, perhaps you should "sync" the ruler with the dart line length when it is changed by the user.

**Comment by DanTup** [comment]
> perhaps you should "sync" the ruler with the dart line length when it is changed by the user.

We don't set the ruler specifically, we just have it in our [recommended settings](https://dartcode.org/docs/recommended-settings/) to set it to 80 because that's where the formatter wraps by default (and we provide a simple way to copy our default settings into your own settings the first time you run the extension).

I think modifying the ruler settings would be a little odd. If we were to do something, I think it would be better to detect when lineLength is changed, and ask whether you want us to update the rulers. Given how few people customise this though, I'm not sure if it's worth the extra complexity for that.

Although, adding a note to the description of `dart.lineLength` to make it clearer what the ruler is might at least be helpful.

**Comment by DanTup** [comment]
I've added a note about this here:

<img width="1030" alt="Screenshot 2022-12-01 at 15 17 12" src="https://user-images.githubusercontent.com/1078012/205089945-422c5dc4-647c-4a58-801d-e3b5784785ea.png">
