### ISSUE TITLE
Running flutter app on mac fails from VS code but succeeds from CLI

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4305]
When running from VS code:
```
Launching lib/main.dart on macOS in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

Exception: CocoaPods not installed or not in valid state.

Exited (1).
```

When running from CLI (`flutter run -d macos`), run succeeds.

**Comment by DanTup** [comment]
@kenzieschmoll if you launch VS Code from a terminal (with `code`), do you see the same problem?

If there are any env variables set in your terminal profile scripts that (including changes to `PATH`), they won't be visible to VS Code and this often causes issues like this (the simplest solution is to use the `dart.env` setting in VS Code to also set them).

If it doesn't seem like that, running `flutter doctor -v` from the terminal and then also the **Flutter: Run Flutter Doctor** command from the VS Code command palette might be useful (since the latter will run in the same context as `flutter run` spawned by VS Code).

**Comment by kenzieschmoll** [comment]
strange. closing VS code and reopening via `code .` fixed it. I did try the "Developer: Reload window" option before closing VS code and reopening from terminal, but this didn't work.

**Comment by DanTup** [comment]
Does the issue still occur if you restart VS Code from outside of the terminal (eg. using dock/launcher/spotlight)? My guess is that starting Code with `code .` has only fixed it for that instance (since env variables are inherited, Code is getting all env variables as the Terminal has, but launching it outside the terminal will not get anything from terminal startup scripts).

You can see the `PATH` that VS Code is inherited by opening a Dart project then running **Dart: Open Extension Log**. We dump `PATH` at the top of that log because this is a common issue:

```
[7:44:13 PM] [General] [Info] Environment PATH:
[7:44:13 PM] [General] [Info]     /usr/local/bin
[7:44:13 PM] [General] [Info]     /System/Cryptexes/App/usr/bin
[7:44:13 PM] [General] [Info]     /usr/bin
[7:44:13 PM] [General] [Info]     /bin
[7:44:13 PM] [General] [Info]     /usr/sbin
[7:44:13 PM] [General] [Info]     /sbin
[7:44:13 PM] [General] [Info]     /Library/Apple/usr/bin
[7:44:13 PM] [General] [Info]     /Users/danny/.gem/ruby/2.6.0/bin
```

That said, on this machine I have the `ruby/bin` folder in my `PATH`, but I can't actually find where this comes from. It's not in any terminal startup scripts, and I don't have it in `/etc/path` or `/etc/path.d/`. I also see it in the output of `/usr/libexec/path_helper` but it's not clear to me where it's coming from 🤔

**Comment by DanTup** [comment]
Oh, I found it. I do have `export PATH=$PATH:$GEM_HOME/ruby/2.6.0/bin` in `~/.zprofile`.

Based on some reading online, it looks like some scripts (`.zprofile`, `.bash_profile`) are executed for all logins, and others (`.bashrc`) only for terminals. So if you have the `ruby/bin` path added in something like a `.bashrc` maybe that will cause this, and moving it to `.bash_profile` (or `.zprofile` depending on your OS/version) will fix it?
