### ISSUE TITLE
Use stack_trace Chain for showing call stack

### ISSUE THREAD

**Issue by jeiea** [Dart-Code/Dart-Code#4308]
**Is your feature request related to a problem? Please describe.**
If we use stream stacktrace is cut at every yielded/listened position. The following is the one. That is all, I can know no information about context.
<img src="https://user-images.githubusercontent.com/4188984/208342236-fb33d080-d6ca-4008-be3e-a354cd13d803.png" width=400 />

The below is `Chain.current().terse` in the same context. I think this is more useful.
![image](https://user-images.githubusercontent.com/4188984/208342971-64ecb55b-c4e8-4563-9c45-46775dcbf859.png)

I think stream is not easy to use, and this is one factor.

**Describe the solution you'd like**
Described in the title.

**Describe alternatives you've considered**
Nothing.

**Comment by jeiea** [comment]
Then it seems to be not direct stream problem but issue about asynchronicity. The above source is closed so it is difficult 
 to provide intact. I can't sure it is same problem but how about the following?

```dart
// Environment: Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64)
   test('aasdf', () async {
      await FlutterReactiveBle().initialize();
      await Future.delayed(Duration(seconds: 1));
      print('asdf');
    });
```

`FlutterReactiveBle` is from `flutter_reactive_ble` package. I could catch an exception with setting breakpoints on All Exceptions.
<img width="137" alt="image" src="https://user-images.githubusercontent.com/4188984/208589580-b4e71123-5b2c-4ef2-850d-dd03ee480e49.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/4188984/208589670-2d8e9fa9-c9c1-45f7-b4fd-d60b76175c1b.png">

**Comment by grico95** [comment]
> **Is your feature request related to a problem? Please describe.** If we use stream stacktrace is cut at every yielded/listened position. The following is the one. That is all, I can know no information about context. <img alt="" width="400" src="https://user-images.githubusercontent.com/4188984/208342236-fb33d080-d6ca-4008-be3e-a354cd13d803.png">
> 
> The below is `Chain.current().terse` in the same context. I think this is more useful. ![image](https://user-images.githubusercontent.com/4188984/208342971-64ecb55b-c4e8-4563-9c45-46775dcbf859.png)
> 
> I think stream is not easy to use, and this is one factor.
> 
> **Describe the solution you'd like** Described in the title.
> 
> **Describe alternatives you've considered** Nothing.

**Comment by DanTup** [comment]
@jeiea thanks - if I understand correctly, you want something similar to is described here:

https://pub.dev/packages/stack_trace#stack-chains

In their example, the original stack looks like this:

```
Unhandled exception:
oh no!
#0      _runAsync (file:///Users/kevmoo/github/stack_trace/example/example.dart:12:3)
#1      _scheduleAsync.<anonymous closure> (file:///Users/kevmoo/github/stack_trace/example/example.dart:8:52)
<asynchronous suspension>
```

But when using `Chain.capture`, and look at the `terse` stack, it looks like:

```
test.dart 17:3       runAsync
test.dart 13:28      scheduleAsync.<fn>
===== asynchronous gap ===========================
dart:async           _Future.then
test.dart 13:12      scheduleAsync
test.dart 7:18       main.<fn>
package:stack_trace  Chain.capture
test.dart 6:16       main
```

The stack trace we show in the debugger comes from the Dart VM so I'm not sure if it's possible to do something like this here. That said, we currently show something called the "async casual frames" which seemed like they are intended to provide some of the same benefit.

@bkonyi are you familiar with how `asyncCausalFrames` work and how they're different to what `package:stack_trace` does for stack chains? Is it possible we could get the same frames shown above into the VM stack trace (see [here](https://pub.dev/packages/stack_trace#stack-chains) for details - in particular, how `main` appears in one and not the other). Some of the debugger functionality already doesn't work if we move up the stack past the first async boundary (since from there, `asyncCausalFrames` aren't the real frames) so I don't think them not being real frames would matter, but being able to use it to navigate to the code could be useful. I don't know enough to know if this is feasible or not though (and from reading the source I can't tell exactly how `Chain.capture` is doing its magic).

**Comment by DanTup** [comment]
@bkonyi any thoughts on the above?

**Comment by bkonyi** [comment]
I'm still not familiar with the different stack trace formats, unfortunately.

**Comment by DanTup** [comment]
@natebosch @jakemac53 do either of you know the answer to the above (or who might)?

**Comment by DanTup** [comment]
Sorry for the delay in responding here. I wasn't sure who could answer my questions.

On an issue related to stack traces (https://github.com/dart-lang/sdk/issues/51763) I asked about this, and the response was:

> It is very expensive to produce the type of stack trace that `package:stack_trace` can produce because it requires eagerly capturing stack traces at various points of the execution. In general we are aiming to be as close to that as possible without adding considerable overhead. Stack trace should follow through any explicit `await` and through some of the built-in methods (like `Future.then`), but it will not reach initial synchronous part of the stack. In other words: if you compare stack traces produced by the VM and `package:stack_trace` and there is more than just the last part (after the last async gap) missing - it is worth filing an issue with a reproduction. 

My guess is that this explains the differences in your examples - it's just the initial part of the stack that's different. So it sounds like there's unfortunately not a way to achieve this (without impacting performance). Although if you see differences other than those noted above, you should file an issue at https://github.com/dart-lang/sdk with examples to be looked at.

Hope this makes sense!
