### ISSUE TITLE
Flutter: ! Doctor found issues in 1 category.

### ISSUE THREAD

**Issue by sameulyung2025** [Dart-Code/Dart-Code#4310]
Everything is downloaded, and I don't know what to do. I have tried the cmdline-tools command, but it doesn't seem to fix the problem.

<img width="562" alt="Screen Shot 2022-12-20 at 3 38 06 PM" src="https://user-images.githubusercontent.com/113876575/208610417-50071cc8-cd26-436d-a4b3-e563ba7f9fbc.png">

<img width="706" alt="Screen Shot 2022-12-20 at 3 38 15 PM" src="https://user-images.githubusercontent.com/113876575/208610436-ba294016-8a49-4c86-824c-bfeb6057b8b3.png">

**Comment by DanTup** [comment]
@sameulyung2025 do you see the same thing if you run `flutter doctor` in an external terminal outside of VS Code?

Can you post the full output of `flutter doctor -v`?

**Comment by sameulyung2025** [comment]
> @sameulyung2025 do you see the same thing if you run `flutter doctor` in an external terminal outside of VS Code?
> 
> Can you post the full output of `flutter doctor -v`?
<img width="560" alt="Screen Shot 2022-12-20 at 8 56 21 PM" src="https://user-images.githubusercontent.com/113876575/208672638-2fb664c8-d9f1-4505-a2ff-72e8537a8b6a.png">

Here is what shows up when I use "flutter doctor -v".

**Comment by DanTup** [comment]
@sameulyung2025 to be clear - are you seeing this outside of VS Code, or only inside VS Code?

This extension is for the VS Code extension, so if the issue is happening outside of VS Code in a normal terminal, then I don't think it's something wrong (or that can be fixed) in the VS Code extension.

That said, in your screenshot above it looks like the Android SDK is being read from `/opt/homebrew`, so my guess is that you have two different SDKs - one installed via Homebrew, and one that Android Studio has installed. If so, you should either remove the Homebrew one and just use the Android Studio one, or run the `sdkmanager` command from the message _using_ the version of `sdkmanager` from inside that homebrew version of the SDK.

**Comment by sameulyung2025** [comment]
> 

It is only inside the terminal. How do I go about deleting one of the Android SDKs?

**Comment by DanTup** [comment]
> How do I go about deleting one of the Android SDKs?

From your screenshot, I think you have installed an Android SDK via `homebrew` (since it's at `/opt/homebrew/`) so I suspect you could `brew list` to verify this and `brew uninstall` to remove it, however I'm not very familiar with homebrew so can't offer much help with that (their docs are at https://docs.brew.sh/Manpage).

**Comment by sameulyung2025** [comment]
> > How do I go about deleting one of the Android SDKs?
> 
> From your screenshot, I think you have installed an Android SDK via `homebrew` (since it's at `/opt/homebrew/`) so I suspect you could `brew list` to verify this and `brew uninstall` to remove it, however I'm not very familiar with homebrew so can't offer much help with that (their docs are at https://docs.brew.sh/Manpage).

Thanks

**Comment by DanTup** [comment]
@sameulyung2025 did this solve the issue?
