### ISSUE TITLE
Please remove usages of `setExceptionPauseMode`

### ISSUE THREAD

**Issue by derekxu16** [Dart-Code/Dart-Code#4318]
That VM Service procedure is deprecated and we intend to remove it in v4.0 of the VM Service spec. Please use `setIsolatePauseMode` instead.

**Comment by hefzym-Qagtaf-vamci0** [comment]
> That VM Service procedure is deprecated and we intend to remove it in v4.0 of the VM Service spec. Please use `setIsolatePauseMode` instead.

[Uploading ScarletAlpha.ipa.zip…]()

**Comment by DanTup** [comment]
@derekxu16 is this blocking something? I noticed https://github.com/flutter/flutter/issues/117526 / https://dart-review.googlesource.com/c/sdk/+/277181 that seem related.

I had planned to fix this and ship it in the next VS Code release (~1mo from now) but if it's blocking things using master, I'll aim to fix this in a patch sooner.

**Comment by derekxu16** [comment]
No, it's not urgent. That issue is related but I can just hold off on making the problematic changes until your fix is ready.

**Comment by DanTup** [comment]
@derekxu16 thanks! I've landed a change to use this API when it's available. It will ship in the next extension update towards the end of the month. I'd suggest giving it at least a few weeks after then before landing the change (so that users of master/dev SDKs would likely have had the extension updated).
