### ISSUE TITLE
very slow test execution when there are many (~thousands) of tests defined in a file

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#4325]
I'm working on a project where most of the tests are generated from a specification. There are tens of thousands of tests, and depending on the granularity of the source spec (the WASM specification) there can be several thousands tests in a single dart source file.

I see very slow test execution (from VS Code) when there are thousands of tests in a single dart source file. This is in comparison to running `dart test` for the same project from the command line - test execution there is on the order of a few seconds (`6.90s` for 7,590 tests). From VS code, just the tests in one file may take a few minutes to run.

I assume there's a quadratic / polynomial algorithm in there somewhere. I'm not sure if its in `dart test` (finding the locations for tess in the files?), in VS Code (displaying the locations?) or in the communication between the two (discovering tests and communicating it back to VS Code?). Or perhaps in the xml reporter for dart test - generally only used by IDEs?

In any case, I'm opening this issue to track the performance problem. The repo for the project demonstrating the issue is https://github.com/devoncarew/wasmd. The tests w/ perf issues are `test/spec/f32/f32_test.dart` and `test/spec/f64/f64_test.dart`. Let me know if there's any more digging you'd like me to do on my end.

**Comment by DanTup** [comment]
Thanks, I can repro this. The extension host seems to be eating a lot of CPU when this happens, so my guess is that it's in the extension and perhaps where we're trying to match up the tests in the results to those we already know about (we maintain an in-memory model of tests, merging those discovered at analysis time and runtime).

I'll d some profiling when back properly and see where the time is going.

While testing this, I also saw #4326 which seems to be something else eating a lot of CPU in the extension host for this project (before running any tests, so I think unrelated, but likely a similar thing - either slow and adds up, or scales badly).

**Comment by DanTup** [comment]
This shows up in the console while running that test file too. Seems we're blocking the extension host enough to start triggering an automatic profile, but then respond soon after such that it's cancelled. This would makes sense if it's the location of tests in the model as noted above.. it'll run on each test result and is probably just slow enough to trigger the profile, and then this happens repeatedly for each test.

<img width="612" alt="Screenshot 2022-12-28 at 11 41 09" src="https://user-images.githubusercontent.com/1078012/209806738-cc9834f4-d875-4d93-b304-f577a91d218b.png">

**Comment by devoncarew** [comment]
Thanks for taking a look - much appreciated!

**Comment by DanTup** [comment]
I've made some reasonable improvements to this in #4328 (`f32_test.dart` is somewhere around 10s I think), but there are a few test failures and the "x/y Passed" labels aren't being updated correctly. I think that should all be fixable without adding much time back on though.

I did find an issue that might be in VS Code too - the editor seems to hang a bit when moving around that file - I've filed https://github.com/microsoft/vscode/issues/170493 for investigation. I also found that the tests run are slower when the Test tree is visible, although I don't entirely understand why yet (the VS Code UI is in a different process to ours so I wouldn't expect it to be holding up the extension host). I'll dig more into that once the other issues are resolved.

**Comment by devoncarew** [comment]
Thanks again for taking a look!

I have some other large files now - some I'm not checking in - that show up perf issues in other places (general analysis, ...). I think these will be good for shaking out slow slowdowns in normal sized files.

**Comment by DanTup** [comment]
If you have any examples you can share (either by committing on a branch somewhere, or sending to me) I'd definitely be interested in taking a look after this. Performance is something that comes up now and then but often in private projects that can't be shared and profiling/optimising "remotely" can be tricky.

I have been thinking abut how maybe we could have something similar to **Dart: Capture Logs** for profiling information. It'd be neat if you could start profiling the analyzer by just running a command in VS Code, then reproduce your slow thing, then click a button to stop profiling and write a file that could be shared/examined.

Along similar lines, it'd be nice if users could maybe trigger profiling stop/starting from their code, similar to [console.profile](https://code.visualstudio.com/updates/v1_74#_javascript-debugging).

**Comment by DanTup** [comment]
I took some timings before/after the changes in #4328, and I'm quite surprised this hadn't come up sooner. With a small set of tests, rebuilding the whole tree was so fast that it was the easy thing to do, and it scaled incredibly badly (especially in the case of a large number of very small/fast tests).

Using current stable extension, running `f32_test.dart` with the file _closed_ and the test tree visible but collapsed:

- Till "Exited" in Debug Console: 5:50 (350s)
- Till debug toolbar disappears: 5:50 (350s)

With the changes, timings are:

- Till "Exited" in Debug Console: 7s
- Till debug toolbar disappears: 8s

This is much better, however there are still some issues when the file is open and the tree is expanded:

- Till "Exited" in Debug Console: 15s
- Till debug toolbar disappears: 30s

I ran the profiler on both the extension host and VS Code for this case, and there's almost nothing happening in the extension host and lots of blocking in the VS Code UI, so I think once https://github.com/microsoft/vscode/issues/170493 is resolved that will be better (but I'll re-test to be sure once it has).

I'm gonna do some more testing with your project to check for any other obvious perf issues in the extension, but otherwise I'll publish a pre-release version soon so you can update and confirm it's working (and hopefully give some more real world testing coverage before the next release 😄).

**Comment by DanTup** [comment]
@devoncarew I've pushed a pre-release version of the extension (v3.57.20230104) you can opt-in to if you aren't already on pre-releases:

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />

It still has the caveat above (things are slower with the test file open), but otherwise should be much better. Please let me know if you see any other perf issues (or find any bugs in these changes).

**Comment by devoncarew** [comment]
> however there are still some issues when the file is open and the tree is expanded

I do see the perf difference you describe, but the overall perf is nigh-and-day improved (unusable after for very large test files, and fine - if a little laggy - for the same w/ the updated extension).
