### ISSUE TITLE
Remember last selected debug device.

### ISSUE THREAD

**Issue by twoco** [Dart-Code/Dart-Code#4332]
It would be great if the last selected device is remembered. Currently, you have to select the device every time after launching VS Code. It's annoying when you don't think about it after pressing F5 (run debug). In my case it always switches back to Windows desktop. But I want Chrome web.

![screenshot](https://user-images.githubusercontent.com/53160891/210932663-9b95a395-6f9b-43b1-b9b3-8f9fedcef039.png)

**Comment by DanTup** [comment]
Is this something you'd prefer was per-project, or global? Eg. if you select Chrome in one project and then start another one, would you expect it to also default to Chrome? (the flipside, is if you change that one project to Windows, it would change for the other one too).

**Comment by twoco** [comment]
Good question. I would say per project. But I could also live with a global setting. I wonder where this setting would be stored. Is this still a user setting or workspace setting (like VSCode setting). If this is a VSCode setting, the dev can decide where to store this parameter. Global as user setting or per project in workspace scope. Implementation: After devices list loaded, try to select the user stored list entry and fallback to the current behavior if setting not set or not possible (e.g. device not available anymore).

**Comment by DanTup** [comment]
I've done the above and it seems to work well in my testing. I'm going to ship this on by default, but it can be opted-out with the `dart.flutterRememberSelectedDevice` setting. I will likely publish a new pre-release build before the end of the week if you want to try this out before it ships to stable. You can switch to pre-release versions using the button here:

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />

**Comment by twoco** [comment]
Great 👍 Thanks. I'll try it when it's out. Is it possible to see if this particular feature is in the pre-release?

**Comment by DanTup** [comment]
Pre-release versions have a date in the format YYYYMMDD in the last part of the version number (the current version is 3.57.20230104, release on 04 Jan 2023) so one with a newer date than today will include it.

I'd been holding off doing the release because I was trying to land #4337 first, but it's held up a little on some Flutter changes so I'll likely publish a pre-release tomorrow that includes this. I'll ping here when I have as a reminder if you'd like to try it out. Thanks!

**Comment by DanTup** [comment]
v3.57.20230119 has been published and includes this change. Please let me know if it works as you'd expect (`flutterRememberSelectedDevice` is enabled by default, so you shouldn't need to do anything). Thanks!

**Comment by twoco** [comment]
It seems to work. Good job. 👍

**Comment by DanTup** [comment]
Great, thanks for testing!

**Comment by jonmountjoy** [comment]
Thank you so much for this - it was incredibly frustrating.  👏

**Comment by DanTup** [comment]
Glad it's useful! If anything else is frustrating, please do file issues and don't suffer in silence! While I can't promise to address all frustrations quickly, sometimes there are simple fixes to things that have frustrated people for some time that I wasn't aware of (often because my testing is often quite contrived, and I don't work on any significant Flutter applications).

Thanks!
