### ISSUE TITLE
How to connect to Flutter web app in remote SSH session

### ISSUE THREAD

**Issue by devgony** [Dart-Code/Dart-Code#4339]
**Is your feature request related to a problem? Please describe.**

There could be some users wanting to use Dart-Code extension with remote VSC-server but it looks like Debug uses dymanic port.
Especially In my case, i use port forwarding on remote server so that i need to know fixed port.
![image](https://user-images.githubusercontent.com/51254761/211733588-54ae427f-7680-4b20-938b-fd1b5fc2f22d.png)

**Describe the solution you'd like**

There should be some feature to fix the port of Debug (browser)
Is there any feature like that?

➕ I also tried
```json
"dart.flutterRunAdditionalArgs": [
      "--web-hostname=0.0.0.0",
      "--web-port=53000",
]
```
and it seemed like able to connect but it gets blank screen and shows some debug error at browser console

**Comment by DanTup** [comment]
Can you describe your setup in more detail? We already use APIs built into VS Code to automatically handle port forwarding when using remote workspaces (this should cover things like SSH, WSL, Docker, Codespaces).

**Comment by devgony** [comment]
@DanTup 
I'm using VSC remote ssh extension from local MacBook to MacMini to use MacMini's resources.
But whenever I start debug mode with `Dart-Code` on my local MacBook, the dart app window (browser) is opened on MacMini.

How can i see the dart app window on my local MacBook?

**Comment by DanTup** [comment]
@devgony are you using the Chrome device to run the app on? That's expected behaviour with that device, as the `flutter` tool (which is running on your Mac Mini) is launching Chrome.

If you want to debug from a remote machine, you need to use the web-service device and the [Dart Debug extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm). The reason for this is that VS Code needs to be able to control the debugger in Chrome, and it can only do that if it launched Chrome (which it can't do on your MacBook when `flutter` is running on the Mac Mini), or if you use the Dart Debug extension (which essentially proxies those requests between the machines).

The experience with the Dart Debug extension isn't quite as polished as using Chrome yet, but it should be relatively straight forward:

- Install Dart Debug extension
- Select web-server device in VS Code from the status bar
- Run your app as normal
- Wait for Chrome to launch (note: this might only work if Chrome is your default browser)
- Click on the Dart Debug extension button in Chrome

At this point your app should begin running, and the experience should be largely the same as if running locally.

Out of interest, why are you running remotely on the Mac Mini in this way? While everything should generally work, usually people use remote sessions to access other platforms (and generally non-web). It's useful for me to understand all of the use cases people have.

Thanks!

**Comment by devgony** [comment]
@DanTup 
Thanks you for kind instructions.
But one thing that i should do more was adding
```json
"dart.flutterRunAdditionalArgs": [
      "--web-hostname=0.0.0.0",
]
```
at `setting.json` and now it works!

This issue stemed from my old 2017 intel macbookPro which burns whenever I launch IOS simulator.
Therefore, i needed some remote server to compile and launch simulator.
The reason why i chose Macmini (even though i have another Ubuntu server) is that i was trying to develop with VSC remote ssh + watching IOS simulator through chrome remote desktop to Macmini.
But chrome remote desktop has some delay to render so that i came here to use Dart-code + Web debug.

Is there any way to use IOS or Android simulator with remote server as well? if there is, it would be best development experience!

**Comment by DanTup** [comment]
> at `setting.json` and now it works!

Great, glad it's working. I'm not sure why that flag is necessary, as I would've expected the port-forwarding in VS Code to work when the web server is only bound to 127.0.0.1. I'll try and do some testing of this.


> This issue stemed from my old 2017 intel macbookPro which burns whenever I launch IOS simulator.
> Therefore, i needed some remote server to compile and launch simulator.

Gotcha, thanks for the explanation!

> Is there any way to use IOS or Android simulator with remote server as well? if there is, it would be best development experience!

Do you mean have the simulator run on the remote server (MacMini) but be visible on the local MacBook? If so, unfortunately I don't know a way to do this. It works fairly easily with web, because the browser can run in the MacBook and connect to the web server on the other machine. For simulators, there would need to be some way for the rendering to be carried back to the MacBook (and any interactions sent back).

I think I've seen in the past people doing something similar to this with Linux (using X over SSH?) so maybe it's possible, but it's not something I know much about. Of course, another simple way could be to use something like VNC or other remote-desktop software. I don't think the experience would be great, but perhaps it's good enough for your needs.

**Comment by DanTup** [comment]
@devgony happy for me to close this, or is there anything utstanding/unanswered?
