### ISSUE TITLE
Debug (and log) a terminal app inside Visual Studio Code?

### ISSUE THREAD

**Issue by erf** [Dart-Code/Dart-Code#4342]
**Is your feature request related to a problem? Please describe.**

I'm trying to write a terminal app and would like to debug and print logs inside Visual Studio Code. If i just press run `stdin.hasTerminal` always returns `false` and methods like: `stdin.echoMode`, `stdin.lineMode`, `stdout.terminalLines` throws:

```
Exception has occurred.
StdinException (StdinException: Error setting terminal line mode, OS Error: Operation not supported on socket, errno = 102)
```

I guess `stdout` writes to OUTPUT and is not connected to the built in terminal in any way.

**Describe the solution you'd like**

Is there a way to run the app using the built in terminal (or an external terminal?) and be able to debug inside VSCode and log output to the DEBUG CONSOLE?

**Describe alternatives you've considered**

Write code in VSCode and run it manually from the terminal, printing logs to a specific part of the terminal screen (or to a file).

**Additional context**

**Comment by DanTup** [comment]
You can set your apps to run in the Terminal instead of using the Debug Console, which should do what you want:

https://dartcode.org/docs/running-in-terminal/

This can be done per-launch config (by adding `"console": "terminal",` to your `launch.json` launch config), or for the whole project/workspace by adding `"dart.cliConsole": "terminal"` to your VS Code Workspace Settings (you could also set it in User Settings but I wouldn't recommend that since it seems project-specific).

When set this way, pressing `F5` will run the app in the Terminal where you can then use `stdin`. There are some differences when running in this mode (and it's not supported at all for Flutter) because of how it works, so you might find some things don't work or work slightly differently.

Please let me know if this doesn't solve the issue. Thanks!

**Comment by DanTup** [comment]
Yep! I think you can use the **Terminal: Select Default Profile** command to set the default terminal, which is what VS Code should use when a debugger asks it to start a process in a terminal.
