### ISSUE TITLE
 Error: Not found: 'dart:ui' import 'dart:ui' as ui show Paint, Path, Canvas;

### ISSUE THREAD

**Issue by Shubham123498765** [Dart-Code/Dart-Code#4343]
When trying to run the program it gives this error
I am following this tutorial https://codelabs.developers.google.com/codelabs/flutter-codelab-first#3
![image](https://user-images.githubusercontent.com/82265932/212477053-011413cc-a52b-4532-8306-0be5821ed92c.png)
![image](https://user-images.githubusercontent.com/82265932/212477304-bbb8054e-a3e1-4278-9c5d-c74374a26a2f.png)

I tried all the solutions available on StackOverflow but still getting the error.
Stackover flow site https://stackoverflow.com/questions/52483773/dartui1-error-not-found-dartui-flutter-dart/52813358#52813358

I even tried import 'dart:ui' but it also didn't solve the problem.

**Comment by DanTup** [comment]
@Shubham123498765 how are you running the application? I can think of a few reasons why this might occur. From least likely, to most likely:

1. **You're manually typing `"dart d:\...\main.dart"` in the terminal**
  I don't think it's this, but if you are, you need to use `flutter run` if you want to run a Flutter app from the terminal. However, I wouldn't recommend this because you won't get a lot of functionality from the Dart/Flutter extensions (such as debugging).
2. **Your `pubspec.yaml` file does not select the Flutter SDK**
  You should have `flutter:\nsdk: flutter` somewhere in your `pubspec.yaml`. If you've accidentally removed this, then the extension will try to run the application using the Dart SDK.
3. **You're trying to run the program using an extension like Code Runner, which does not support Flutter.**
  I think this is most common. If you're a "Run" button that is provided by the Coder Runner extension (and not one of those provided by the Dart extension) it will always try to run the app using `dart`. There's some more info about this here:
    - https://github.com/Dart-Code/Dart-Code/issues/4323
    - https://github.com/formulahendry/vscode-code-runner/issues/674

Please let me know if none of these seem to be correct. Thanks!

**Comment by Shubham123498765** [comment]
Thanks a lot 
3rd option solved the issue

By the way can you suggest some resources to learn flutter

**Comment by DanTup** [comment]
Great, thanks for confirming.

I'd recommend starting at https://docs.flutter.dev/ if you haven't already - there's lots of content there:

<img width="652" alt="Screenshot 2023-01-14 at 23 39 14" src="https://user-images.githubusercontent.com/1078012/212501799-9bdc9042-aaae-4ebd-b0eb-aafc34365348.png">

There's also lots of video resources linked here:

https://docs.flutter.dev/resources/videos

And there are lots of other places to ask questions and find info listed here:

https://flutter.dev/community#:~:text=Get%20involved%20and%20ask%20questions

Hope this helps!
