### ISSUE TITLE
Dart Define variables defined in launch.json not showing up

### ISSUE THREAD

**Issue by muddi900** [Dart-Code/Dart-Code#4345]
**Describe the bug**
I am defining a `--dart-define` in my launch config that is not showing up in my app.

The config:
```json
{
            "name": "front_tpw_fam",
            "request": "launch",
            "type": "dart",
            "args": ["--dart-define,FIREBASE_CONFIG=${input:FIREBASE_CONFIG}"]
}
```

The input field is working.

```json
 {
            "id": "FIREBASE_CONFIG",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "bash -c 'jq . -cM assets/firebase_config.json'",
                // "useFirstResult": "true",
                "env":{
                    "WORKSPACE": "${workspaceFolder}"
                }
            }
}
```

**To Reproduce**
1. Use an `args` property in your `launch.json`.

**Expected behavior**
`bool.hasEnvironment('FIREBASE_CONFIG')` should return `true`

**Please complete the following information:**
 - Operating System and version: Windows 11 Pro Build 22621.963
 - VS Code version: 1.74.3
 - Dart extension version: 3.56.0
 - Dart/Flutter SDK version: 2.18.6/3.3.10
 - Target device (if the issue relates to Flutter debugging): Web

**Comment by DanTup** [comment]
> ```
> "args": ["--dart-define,FIREBASE_CONFIG=${input:FIREBASE_CONFIG}"]
> ```

You can't use comma-separated arguments like this, `args` is an array and should be structured like:

```
"args": [
  "--dart-define",
  "FOO=BAR"
]
```

I would recommend putting these in `toolArgs` though, since it's a bit more consistent with doing a similar thing for Dart (non-Flutter) apps. There's a more complete example available here:

https://dartcode.org/docs/using-dart-define-in-flutter/

Please let me know if this doesn't work for you. Thanks!
