### ISSUE TITLE
Not clear how to get from one DevTools feature to another

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4386]
Quoting feedback from @loic-sharma:

> I opened DevTools using the blue magnifier glass icon:
> 
>  ![image](https://user-images.githubusercontent.com/43759233/218571555-9fa2b709-2ac2-48b6-9559-69ce4d8f54cd.png)
> 
> That opens the Widget Inspector. From this screen, it's not clear how I can switch to the performance tool. Could the Widget inspector link to other DevTools? Could all the DevTools be tabs within a single screen, similar to Chrome's dev tools?

**Comment by DanTup** [comment]
> Could the Widget inspector link to other DevTools? Could all the DevTools be tabs within a single screen, similar to Chrome's dev tools?

I'd tried to make the parts of DevTools feel more integrated with VS Code than just being DevTools in an iframe. Each tool can be used in its own panel, so you can have multiple open, switch between them, put them side-by-side.

So I guess my question is whether this was the right call.. Is the request here to bundle them back together (meaning you'd just have one "DevTools" panel with some navigation), or is the request just about making it easier to find/get to the other tools?

The button on the debug toolbar is specifically the Inspector (not "DevTools"). We didn't want to add too many icons (and at the time, we were limited with how we could dynamically show/hide them) and the other tools were only accessible via the command palette / status bar (although the status bar is an extra click now it's in the "language status" area).

Should we add more icons for the different DevTools tools to this toolbar now? Or should we just have a single embedded DevTools?

#4387 is slightly related - it's a request to have some tools always open in the browser (not embedded). I think that works better if we keep things separate (otherwise you'd only see a subset of the tools in the nav in the embedded view, or some of the buttons would unexpectedly trigger new browser windows).

Thoughts/opinions? (cc @jacob314 @InMatrix)

**Comment by InMatrix** [comment]
There seems to be two possible problems the user might have ran into:
1. The user had trouble getting to the rest of DevTools from VS Code.
2. The user used the standalone DevTools before and knew how to get to it using the command palette. Nonetheless, the user was wondering why the tabs for the rest of DevTools were not present in the Inspector embedded in VS Code. It could've been convenient to be able to jump from the inspector to other DevTools tabs.

@loic-sharma could you clarify which of the above best characterizes the situation you ran into? 

> https://github.com/Dart-Code/Dart-Code/issues/4387 is slightly related - it's a request to have some tools always open in the browser (not embedded).

I generally agree with this. Most of the perf tools is infrequently used and requires large screen real estate to support analytical tasks. However, there could be a subset of perf tools for app performance monitoring, and it can be useful to show them in a sidebar.

**Comment by loic-sharma** [comment]
> 2. The user used the standalone DevTools before and knew how to get to it using the command palette. Nonetheless, the user was wondering why the tabs for the rest of DevTools were not present in the Inspector embedded in VS Code. It could've been convenient to be able to jump from the inspector to other DevTools tabs.

@InMatrix, this best characterizes my experience.

> Is the request here to bundle them back together (meaning you'd just have one "DevTools" panel with some navigation), or is the request just about making it easier to find/get to the other tools?

Either solution seems good to me, but I lean towards the former. I'm a huge fan of Chrome's Developer Tools, and those are in a single panel with some navigation.

> > #4387 is slightly related - it's a request to have some tools always open in the browser (not embedded).
> 
> I generally agree with this. Most of the perf tools is infrequently used and requires large screen real estate to support analytical tasks. However, there could be a subset of perf tools for app performance monitoring, and it can be useful to show them in a sidebar.

I'm on the Flutter team and I didn't know you could open the DevTools in a browser. I've used the command palette countless times, but the WebView option is hard to spot given how:

1. There are many options
2. Options appear to be repeated with `Flutter:` and `Dart:` prefixes. I assumed the second half of the list was a repeat of the first half

![image](https://user-images.githubusercontent.com/737941/218886774-56406d2a-23c0-4240-87ca-e8c12b4d6e91.png)

We should advertise the webview option a little more to help raise awareness.

**Comment by InMatrix** [comment]
The first option "Flutter: Open DevTools" opened DevTools in a web browser when I tried. However, I agree the list of options is not super clear. I guess the "Developer: Open Webview Developer Tools" option is not actually related to Flutter/Dart. Is there a way to filter that out when the user is in a Flutter project? 

![](https://user-images.githubusercontent.com/737941/218886774-56406d2a-23c0-4240-87ca-e8c12b4d6e91.png)

Another small change that could be helpful is adding an "Open in separate window" button to each DevTools screen when it's opened in the sidebar. There's a similar UI element in Chrome DevTools: 

<img width="288" alt="image" src="https://user-images.githubusercontent.com/348942/218888269-d285229c-59b3-48ef-afde-14487889a308.png">

**Comment by jacob314** [comment]
+1 to adding a link to "undock in a separate window" or maybe even just "open all of DevTools in a separate window". We handle multiple simultaneous devtools instances gracefully so we can just support that flow.

We should also consider moving DevTools to its own VSCode sidebar as VSCode has gotten much better providing more options for users to move sidebars. That sidebar would most naturally be "All of DevTools" although of course defaulting to the most commonly used inspector tab.

**Comment by DanTup** [comment]
@InMatrix is correct, the "Open Webview Developer Tools" entry in the screenshot above is not related t Dart/Flutter, it's a VS Code command. There's no way for us to hide VS Code commands from the palette (and I'm not sure we should if we could).

There's an issue at https://github.com/Dart-Code/Dart-Code/issues/4389 for a "pop-out" button. The popped out version will be full DevTools (with the ability to change tabs), the hidden nav is only for the embedded view.

There's a setting that controls whether you get embedded or external DevTools in VS Code:

<img width="480" alt="Screenshot 2023-02-16 at 12 16 12" src="https://user-images.githubusercontent.com/1078012/219362374-9d875cc8-d3b5-43d4-bbbc-28c3a72244de.png">

And when you use the "Open DevTools" command (with a running app), you're asked which section to open, but also have a browser option at the bottom:

<img width="670" alt="Screenshot 2023-02-16 at 12 18 49" src="https://user-images.githubusercontent.com/1078012/219362815-b343756f-556e-48e4-8199-c218909a08c7.png">

However, if there's no running session then we cannot open an embedded version, so running the "Open DevTools" command will automatically just launch the external browser version.

I'm not sure going back to embedding the whole of DevTools is better - it feels very much like "an app embedded inside another app" and not very integrated, and it makes things a bit odd if you have multiple panes open (they both have navs). Though if we're going to try out moving DevTools into a sidebar (instead of the current editor), it may make sense to hold off until then anyway, as we might end up wanting to tweak how the navigation works there anyway, so that may supersede other changes here?
