### ISSUE TITLE
Flutter Daemon failed to start

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4403]
**Describe the bug**
Flutter Daemon failed to start
![Screenshot 2023-02-23 at 9 52 10 AM](https://user-images.githubusercontent.com/43759233/220989400-13c63126-e503-45e3-8629-7b416a8d4231.png)

I have tried reloading the VS code window and this continues to happen..

**Please complete the following information:**
 - Operating System and version: `MacOS 13.2.1 (22D68)`
 - VS Code version:
```
Version: 1.75.1 (Universal)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (2 wks ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No
```
 - Dart extension version: `v3.59.20230214`
 - Dart/Flutter SDK version:
```
Flutter 3.8.0-15.0.pre.1 • channel flutter-3.8-candidate.14 •
git@github.com:flutter/flutter.git
Framework • revision 1690e0454a (20 hours ago) • 2023-02-22 13:44:39
-0800
Engine • revision 3aa112c75c
Tools • Dart 3.0.0 (build 3.0.0-261.0.dev) • DevTools 2.21.1
```
 - Target device (if the issue relates to Flutter debugging):

**Comment by kenzieschmoll** [comment]
This appears to be related to having an experiment enabled. I had `--enable-experiments=records` specified in both of these. This worked last week. Removing them allowed the daemon to start correctly.
![Screenshot 2023-02-23 at 9 58 23 AM](https://user-images.githubusercontent.com/43759233/220990933-e9af91ae-77a0-4c57-9e75-11ef4f6cf0b0.png)

**Comment by DanTup** [comment]
Odd, it's definitely not valid to put things in `dart.flutterAdditionalArgs` that aren't valid for all invocations of `flutter` (inc. `flutter daemon`).

I can't explain why it worked last week (do you know when you added them? could it have been after the daemon had already started, and you hadn't restarted since?), though I don't think there's anything to fix here. Those settings are specifically to pass extra args like this. As long as the "Show Logs" button in the first screenshot includes both the arguments it used to launch `flutter daemon` and the output (stating that the flag is invalid), I think that's probably the best we can do. The description is fairly explicit now, as there were a few StackOverflow answers encouraging people to use this flag in this way.
