### ISSUE TITLE
Opening the SDK's "sdk" folder reports "The library dart:_internal can't be imported" even when `--dart-sdk` is set

### ISSUE THREAD

**Issue by Zekfad** [Dart-Code/Dart-Code#4423]
**Is your feature request related to a problem? Please describe.**
Right now I'm trying to develop patch for Dart SDK, but can't properly setup dart-code for SDK development.

**Describe the solution you'd like**
Detect that provided SDK is local build and correct internal imports.

**Describe alternatives you've considered**
\-

**Additional context**

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/8970959/222966790-7031295d-65d7-4118-b1bc-321594fcdb0a.png)

</details>

**Comment by bwilkerson** [comment]
> ... if you are working on files like in sdk/, do you know the correct way to work open these files without getting "The library 'x' is internal and can't be imported"?

It's been several years since I last tried to do that, but I believe that the only thing you need to do is set the SDK against which the code will be analyzed to be the checked out version of the SDK (rather than a downloaded and built SDK).

The reason this is necessary is that `analyzer` uses the file paths of the files to determine the URI. If the file containing the import from internal isn't inside the SDK against which the code is being analyzed, then the URI won't have a `dart` scheme and the import will be an error.

> ... which part of the SDK are you trying to contribute to? If it's something inside the pkg folder, you may be able to open just that package and avoid analysing the whole SDK folder.

Just one extra note here: if you're working on a package (or packages) in the `pkg` folder, do **NOT** run `dart pub`. Doing so will break the analysis. If you forget and do that, then you can delete the `.dart_tool` directory in the root of the package where you ran `dart pub`, and that will undo the damage.

**Comment by DanTup** [comment]
> I believe that the only thing you need to do is set the SDK against which the code will be analyzed to be the checked out version of the SDK

Do you just mean use an SDK that you have built yourself from local sources, or something else? (I tried the former and it didn't work, although I think I've also had it build into different locations in the past - `out/` vs `xcodebuild/out` or something, so maybe I used the wrong one.. I think maybe it varies based on which type of build I do.. I'll build both and test them).


> Just one extra note here: if you're working on a package (or packages) in the `pkg` folder, do NOT run `dart pub`.

Also - I think `dart run` and `dart test` also implicitly do this. The VS Code extension should detect when you're in the SDK and disable things like test running and automatic `pub get` to try and avoid this.

**Comment by bwilkerson** [comment]
> Do you just mean use an SDK that you have built yourself from local sources, or something else?

No. I mean, if you used `gclient` to checkout the sdk repo in `/users/me/sdk/sdk` (yes, it's weird to have two levels of `sdk`), then tell the analysis server that your sdk is in `/users/me/sdk/sdk/sdk`. That directory used to (hopefully still does) contain all of the files that the analyzer needs from a built version of an SDK.

> The VS Code extension should detect when you're in the SDK and disable things like test running and automatic pub get to try and avoid this.

IMO it would be better if those tools knew about the SDK and did the right things so that even if users use them from the command line everything works as expected.

**Comment by bwilkerson** [comment]
> Oh, I see - but I'm not sure what "tell the analysis server" means here.

I believe that you can pass a `--dart-sdk` option on the command-line when invoking server. It's likely that Dart-Code does that automatically, so it's likely that it isn't possible for users to set it.

You _can_ set it from the `dart analyze` command-line tool, which will pass it along to the analysis server, but `dart fix` doesn't support the flag.

In other words, our support for editing non-pkg files in the sdk repo is spotty at best. This is something that Leaf has been interested in for a while, but as it impacts very few users it's never been a high priority.

**Comment by DanTup** [comment]
> I believe that you can pass a `--dart-sdk` option on the command-line when invoking server. It's likely that Dart-Code does that automatically, so it's likely that it isn't possible for users to set it.

Oh, I see! We don't pass it automatically, but there's a `dart.analyzerAdditionalArgs` setting. I tried this:

```
"dart.analyzerAdditionalArgs": [
	"--dart-sdk=/Users/danny/Dev/Google/dart-sdk/sdk/sdk"
]
```

Although it didn't seem to make a difference. If I remove the last `/sdk` off the end, the server throws that it can't find the `version` file, so I think it is at least reading the flag. Will need some more debugging (although like you say, probably the audience is rather small).

**Comment by Zekfad** [comment]
Thanks for fast reply, my change was in internal patch (sdk directory) and in pkg directory:
I was using sdk from built artifacts:
```json
"dart.sdkPath": "D:\\Users\\vorob\\Desktop\\Projects\\dart_sdk\\dart-sdk\\sdk\\out\\ReleaseX64\\dart-sdk",
````

**Comment by DanTup** [comment]
@Zekfad ah, understood. In that case I think you need to be able to use `"dart.analyzerAdditionalArgs"` as described above, but for me it wasn't working and wil require some debugging.

**Comment by Zekfad** [comment]
@DanTup, just tried to use
```json
		"dart.analyzerAdditionalArgs": [
			"--dart-sdk=D:\\Users\\vorob\\Desktop\\Projects\\dart_sdk\\dart-sdk\\sdk\\sdk"
		]
```
No success, still marks internal library and whole workspace is red.

**Comment by DanTup** [comment]
Thanks for testing - that's what I'm seeing too. I'll try and have a step through later this week and see if there's any obvious/simple reason it's not working.

**Comment by DanTup** [comment]
I had a quick look again, and I see that this is working correctly in many cases. For example in `lib/_internal/js_runtime/lib/typed_data_patch.dart` there is an import for `dart:_internal` that does not produce a diagnostic.

I looked up where the mapping comes from, and it seems to be done by `AbstractDartSdk._getPath()` and that seems to read data from this file:

https://github.com/dart-lang/sdk/blob/main/sdk/lib/libraries.json

In all of the cases I checked, the files that aren't mapping correctly appear to be listed in that file under `patches`. I couldn't find if the code reading the file knows about patches (I think this file is being handled by `SdkLibrariesReader_LibraryBuilder` but I don't see any mentions of `'patches'`), so perhaps that's causing it not to map these `file:///` URIs into `dart:` URIs, which prevents them from being allowed to import internal libraries.

I don't know enough about this code to be sure that's the issue, or know whether it would be a simple fix (perhaps that could be contributed) or not. Perhaps @bwilkerson knows a little more about this than I?

**Comment by bwilkerson** [comment]
It's been years since I even thought about patch files, so things might have changed, but it used to be the case that the analyzer ignored patch files and knew nothing about their structure. If the only thing the analyzer can't do is analyze a patch file, then I'd call that working-as-intended.

**Comment by DanTup** [comment]
@bwilkerson not sure if by "can't analyze a patch file" you mean it should be ignored (not produce diagnostics, not provide language support) or that it may produce unexpected diagnostics. It appears to do the latter.

If there's something to do here (whether it's fix a bug that's causing them to be analyzed, or a request for improved support in this area) probably it should be filed at https://github.com/dart-lang/sdk/issues. I think the behaviour of the VS Code extension (that is, you can pass `--dart-sdk` using `dart.analyzerAdditionalArgs`) is probably the way this should work (although if it seems like we should be able to infer this accurately, we could do that).

**Comment by bwilkerson** [comment]
By "can't analyze a patch file", I meant that it doesn't understand the extended syntax of the patch files.

Under "normal" use, that isn't a problem because we never need to read patch files in order to understand the API provided by the `dart:` libraries.

> ... whether it's fix a bug that's causing them to be analyzed ...

I assumed (possibly incorrectly) that they were being analyzed because they were included in the analysis context created by opening the root of the sdk checkout. They should probably be added to the 'excluded' list in the sdk's analysis options file, but I'd want to talk to the language team first to see what they thought about that approach.

**Comment by DanTup** [comment]
> I meant that it doesn't understand the extended syntax of the patch files.

Ah, I didn't realise they were different - I though they were just platform-specific.

> I assumed (possibly incorrectly) that they were being analyzed because they were included in the analysis context created by opening the root of the sdk checkout.

Yup, I believe that's the case (and I don't think this issue shows up if you're just stepping into SDK sources while debugging, for example, because they're not in the analysis roots).

**Comment by mateusfccp** [comment]
I am also having this issue.

I am trying to contribute with a file that's within `sdk/lib` folder and the analyzer ignores the imports to `dart:_internal`, and by extension many errors are returned.

I can simply ignore them, but this problem really hinders contributing to the SDK.

**Comment by DanTup** [comment]
@mateusfccp which folder(s) are you trying to contribute to? Using the setting above (adding `dart.analyzerAdditionalArgs` to `dart.analyzerAdditionalArgs`) I can open some of the _sub-folders_ of `sdk/lib` without analysis errors, but I'm not sure whether that works for you.

I think it makes sense to move this to the SDK because it's something that's likely going to need changes there to improve (and will likely need input from many others). I've filed https://github.com/dart-lang/sdk/issues/53986 with some notes about this (feel free to add specifics about what you're trying to do) and will close this to keep any discussions/workarounds in the SDK repo where it's more visible/discoverable. Thanks!

**Comment by DanTup** [comment]
> How exactly I do this in Android Studio?

Ah sorry, I don't know how to do it there - the setting I gave was for VS Code. Perhaps @bwilkerson or @jwren can advise how to pass analysis server arguments from Android Studio.

**Comment by bwilkerson** [comment]
From IntelliJ, use Help > Find Action... to open the Find Action dialog. Search for "Registry", and click on "Registry..." to open the Registry dialog. Look for 'dart.server.additional.arguments', click on the pencil icon at the top left above the list and type the `--dart-sdk` option with it's argument, just as you would on the command line (without quotes but with space between the option and value).

**Comment by mateusfccp** [comment]
Thanks, @bwilkerson! It would be nice to have this documented in the CONTRIBUTOR.md (both for IntelliJ and VSCode), but I think this is in the scope of https://github.com/dart-lang/sdk/issues/53986.
