### ISSUE TITLE
Provide telemetry.json and document what's collected on the website

### ISSUE THREAD

**Issue by aitor-gomila** [Dart-Code/Dart-Code#4424]
~~**Is your feature request related to a problem? Please describe.**
Users currently *sometimes* know there *is* telemetry, but they do not know which kind of telemetry.~~

~~**Describe the solution you'd like**
A clear message saying VSCode uses telemetry, what is sent, a consent button and a do not consent button. An optional panel in the titlebar showing the user what information is being sent, when and how. 
E.G: a panel in the Help titlebar button, that when clicked, opens a pane, with a table, showing all the requests and what exactly they send, and how much requests have been sent the last week.~~

~~**Describe alternatives you've considered**
Show the user a summary of all the information they've sent, put together.~~

~~**Additional context**
I understand why telemetry can be useful for something as big as VSCode, but I believe there's 2 keys here missing: consent and clarification.~~

EDIT: use vscode's built-in telemetry API.

**Comment by DanTup** [comment]
We used to have our own flag for enabling analytics, but VS Code requested that we switch to using their flag. My understanding was that they wanted a single opt-in for the whole of VS Code (which you should get the first time you run Code) instead of extensions all popping up their own consent notifications.

The discussion was offline, but there is some info about how extensions handle this here:

- https://code.visualstudio.com/api/extension-guides/telemetry
- https://code.visualstudio.com/api/references/vscode-api#env.isTelemetryEnabled

VS Code updated the telemetry settings to be more explicit that this includes extensions:

<img width="1023" alt="Screenshot 2023-03-06 at 16 45 40" src="https://user-images.githubusercontent.com/1078012/223175660-599bdc13-760c-4260-9f00-9eb0e55b2d79.png">

I'm not sure what is best to do here. We could add our own prompt for Dart, but I feel this is not what VS Code wants. @isidorn do you have any advice here? I certainly don't want to appear to collect data without consent - but if it's not clear from VS Code's prompt that it's enabling for extensions maybe we should?

@aitor-gomila I agree it should be much clearer what is collected (probably a page on dartcode.org and clear links from the readme/etc.). In the meantime you can see anything that's collected in https://github.com/Dart-Code/Dart-Code/blob/5e550c1fda028b951c14aa46f9a4b1c16937c777/src/extension/analytics.ts#L108-L145. It's mostly version numbers and some info about which features are used (or which versions of features you use, such as new DAP vs Legacy). The data is sent to an account that only _I_ have access to.

**Comment by aitor-gomila** [comment]
My bad!!! Oh my god. I wanted to create this issue in the vscode repo :p

**Comment by isidorn** [comment]
@DanTup I suggest to keep the current behavior and keep this issue open to collect more user feedback. Thanks

**Comment by DanTup** [comment]
> My bad!!! Oh my god. I wanted to create this issue in the vscode repo :p

Ah, maybe that makes a little more sense :-)

I think it's fair to say it should be clearer for this extension in particular though. I do also have an open issue (https://github.com/Dart-Code/Dart-Code/issues/4377) to switch to VS Code's new telemetry classes. Perhaps VS Code could record what's being sent through that and make it accessible to the user. That way a user could see all data sent by all extensions (as long as they adopted these APIs) which I think would be nice and transparent.

**Comment by aitor-gomila** [comment]
Can I work on #4377?

**Comment by DanTup** [comment]
@aitor-gomila absolutely! There's info in https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md about how to set up to run/dev the extension (it's mostly just clone, `npm install`, open in VS Code and press `F5`).

Feel free to ping me there if you get stuck or have any questions. Thanks!

**Comment by aitor-gomila** [comment]
It appears there's a [flag](https://code.visualstudio.com/api/extension-guides/telemetry#telemetry.json) that lets users see which telemetry is being sent. Still, without reading the docs or the --help menu, most people won't see this option, as there's not even a "consent to telemetry" dialog.

This is not your problem, this is about VSCode, just wanted to mention it :)
![image](https://user-images.githubusercontent.com/46191980/223185011-dfce3cc0-b985-49d0-bdf4-cccc57ce077f.png)

**Comment by DanTup** [comment]
> It appears there's a [flag](https://code.visualstudio.com/api/extension-guides/telemetry#telemetry.json)

Ah, nice - I'd missed that. Although it says "that VS Code produces" and mentions extensions creating their own `telemetry.json`. @isidorn if an extension uses `TelemetryLogger`, will it automatically be included in VS Code's generated file?

**Comment by isidorn** [comment]
Yes, I think it will. @lramos15 can confirm.

**Comment by lramos15** [comment]
> > It appears there's a [flag](https://code.visualstudio.com/api/extension-guides/telemetry#telemetry.json)
> 
> Ah, nice - I'd missed that. Although it says "that VS Code produces" and mentions extensions creating their own `telemetry.json`. @isidorn if an extension uses `TelemetryLogger`, will it automatically be included in VS Code's generated file?

You would have to manually generate your own. The new API will allow users to see live flowing telemetry via the `Extension Telemetry` output channel when their log level is trace, but we have no way of knowing a static list of every telemetry event you're sending as you could be using runtime calculated names.

**Comment by DanTup** [comment]
Oh, I see. From the description I thought it meant VS Code would log all telemetry it is sending in that session, but actually it's just a file describing what's collected.

It sounds like the Extension Telemetry output channel noted above is more like what I was expecting, thanks!

**Comment by DanTup** [comment]
@aitor-gomila since we already have #4377 about adopting the new APIs, I'm going to rename this issue back to be for providing a `telemetry.json` and documenting what's sent on the website. I'll do this after #4377 is complete, since I might see if we generate this automatically somehow to avoid it getting out-of-date with the actual code.

**Comment by aitor-gomila** [comment]
> @aitor-gomila since we already have #4377 about adopting the new APIs, I'm going to rename this issue back to be for providing a `telemetry.json` and documenting what's sent on the website. I'll do this after #4377 is complete, since I might see if we generate this automatically somehow to avoid it getting out-of-date with the actual code.

Okay! Afterwards, I want to work on a visual tool that lets you see what data is collected visually. But I need to work on this PR first.

**Comment by aitor-gomila** [comment]
Taking a bit to compile, should I wait?
![image](https://user-images.githubusercontent.com/46191980/223502872-3ec076d4-11e6-4163-af70-da5bfbc5434f.png)

**Comment by DanTup** [comment]
The extension now includes [telemetry.json](https://github.com/Dart-Code/Dart-Code/blob/master/telemetry.json) and there's a page on the website containing info derived from that file (and some additional notes on opting out, etc.):

https://dartcode.org/docs/analytics/
