### ISSUE TITLE
Add setting for Android emulator minimum logcat filter level

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4435]
**Is your feature request related to a problem? Please describe.**

Some versions of Android report lines like the following, up to once per second, and they are picked up by VSCode when running in the Android emulator:

```
D/EGL_emulation( 4571): app_time_stats: avg=39.67ms min=0.97ms max=650.57ms count=26
```

This really pollutes the log.

The prefix gives the log level: `D/` is debug, `W/` is warning, `E/` is error.

**Describe the solution you'd like**

Please provide a way to set the minimal log level for information relayed from logcat to the VSCode debug console, and please set the default minimum level to warning, not debug.

**Describe alternatives you've considered**

You can type "!D/" into the VSCode debug console filter, but that's not a permanent solution.

**Comment by DanTup** [comment]
We have an existing issue open at #4391 and https://github.com/flutter/flutter/issues/120711.

It's difficult for us to provide much in the way of UI here (because the UI is all owed by VS Code), but if the Flutter issue is implemented we could have a simple setting here that you can use to pass along to Flutter to filter there. I think it's better filtered in Flutter which knows which output is from ADB than us have to make assumptions about which lines are ADB here or in the debug adapter.

That said, in https://github.com/flutter/flutter/issues/120711#issue-1584709095 @christopherfujino says the output is filtered to things that include `"flutter"`, so I'm curious why this line is showing up at all. Any ideas @christopherfujino?

**Comment by lukehutch** [comment]
Got it, thanks for the pointers. I commented on the Flutter bug.
