### ISSUE TITLE
Automatic toJson and fromJson generation

### ISSUE THREAD

**Issue by oliverjanik** [Dart-Code/Dart-Code#444]
Useful for data classes that get created when stuff is read from web services.

**Comment by DanTup** [comment]
This isn't something I can easily provide within Dart Code as it delegates all the real work to the analysis server from the Dart SDK. It would make more sense implemented in the analysis server, however I'm not sure if it's something that the Dart Team would want to do since there may be (or should be(!)) better ways of handling this (such as transformers/code-gen/etc.).

That said, in my opinion JSON/serialisation support is something that is seriously lacking in Dart (and no doubt the Dart Team are sick of hearing this 😁).

I started a discussion about JSON [3.5+ years ago](https://groups.google.com/a/dartlang.org/forum/#!searchin/misc/json/misc/0pv-Uaq8FGI/Xv-ySWDpaDcJ) but really not a lot has changed. Here are some links that might be worth a read though:

- https://github.com/matanlurey/dart_serialize_proposal @matanlurey is/was trying to collect ideas on how to improve serialisation (my thoughts are [here](https://github.com/matanlurey/dart_serialize_proposal/issues/8))
- https://github.com/dart-lang/json_serializable seems to be recently active, though I don't know useable/useful it is (maybe @kevmoo can confirm)
- https://pub.dartlang.org/packages/built_value provides a way of doing json-serialisable immutable classes (this seemed promising to me but turned out to be rather complicated and require a lot of code changes because of the desire to be immutable) - [blog post](https://medium.com/dartlang/darts-built-value-for-serialization-f5db9d0f4159) by the author (@davidmorgan) is worth reading

I secretly hope that one day either serialisation will get first-class support in Dart or that the code-gen story will get better (eg. real-time when editing code, not scripts manually or even on save of a file) though I'm not sure how likely either is (both are somewhat complicated).

**Comment by oliverjanik** [comment]
Too bad.

Thanks for all the info. I understand a bit of the background here. Since Flutter AOT does not allow dart:mirrors I thought a bit of support from tooling would be better than nothing.

**Comment by DanTup** [comment]
Even for web, mirror's aren't a reasonable option so the request for something is (IMO) reasonable. Maybe one of the guys mentioned above can add some more info about what the current best option might be - unfortunately I've not been keeping up with recent developments as well as I ought to due to time constraints.
