### ISSUE TITLE
Aliases for `Fix all` and `Organize imports` with `Dart:` prefix

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4446]
**Is your feature request related to a problem? Please describe.**
I was going through the features that the Dart VS Code extension provides and was really surprised that the command to "Fix all" is actually available. The problem for me as for the user is that I'd expect all the features that come from a specific extension to be prefixed to help to discover them. Also one confusing thing is that the "Sort members" command has a prefix.

**Describe the solution you'd like**
I understand that "Fix all" and "Organize imports" are build-in `source.` actions, but how about creating an alias command for each of them that will just redirect to the original command under the hood?
I'm also not sure how often these commands are used, but it could be a chicken-egg problem exactly coz to discover them you need some additional knowledge about how VS Code / LSP work.

**Comment by incendial** [comment]
> there are already built-in commands for these and they also show up as source-level code actions.

Do you have any analytics on how often they are used via the command palette / source action menu?

> doing the same thing

The problem is again if you look at the available commands: 1) ones that come from extensions are prefixed 2) not everyone know how VS Code works (and probably should not care much), but if you try to check existing commands when a non-Dart file is open, you won't even see that there is a "Fix all" command and might never double check in a Dart file.

> I also think it could be slightly confusing to type "fix all" in the command palette and see two entries, without it being clear whether there's a difference between them

Why would you care at all? At worst you will try both and use whatever is more convenient. Currently if you search with `dart:` prefix you won't see it at all. But it comes from the Dart extension.

> That said, one thing I'd really like to implement (and would show if you typed "dart fix" into the palette) would be aDart: Fix All in Workspace. It would work like the existing Fix All, but for all files in the open folders rather than just the active file.

Looks like the same argument about the confusion applies here then: since "Fix all" is not scoped I can imagine that people might wonder what's the difference, but this kinda opens a way to rename my initial suggestion from `dart: fix all` to `dart: fix all in current file` (or similar).

**Comment by incendial** [comment]
Actually, considering the number of commands VS Code provides and that some of them are prefixed while other are not might also look like a VS Code issue.

**Comment by incendial** [comment]
> We couldn't actually capture this any way, as the command is owned by VS Code and it just invoked the source CodeAction.

Sad to hear that 😞.

> Dart, because if every language decided to do this, then when you type "fix all" in the command palette, you would see a huge list of "Language: Fix All" commands in the palette, and that seems really confusing.

I'd respectfully argue with this generalisation, coz for that to happen 1) the language files should be in the opened workspace in order for the extension to activate and provide its commands / other features 2) even if the user has multiple extensions, after they use one of the commands it will be marked as recently used and displayed first
<img width="603" alt="Screenshot 2023-03-20 at 15 38 58" src="https://user-images.githubusercontent.com/21116742/226328779-30ea22da-1fe9-4b03-802e-59ac2109ad38.png">
but on the other hand it helps to discover this command no matter what file is open.

> For example, should we have Dart: Format Document, Dart: Format Selection, Dart: Rename Symbol? I feel like they're all in the same category - they are commands that VS Code provides the "UI" for, but the Dart extension provides the implementation.

I'd also avoid this comparison since the initial point was about the command palette and discoverability / awareness. I don't see neither of these commands in the command palette.

> One possibility could be for VS Code to prefix the command based on the current language. Eg. if you're in a Dart file and Dart has provided an implementation for Fix All, show it as "Dart: Fix All". I don't know if they have the means to do that (dynamic prefixes, or knowing what prefix the Dart extension would like to use), but perhaps its worth opening an issue in the VS Code repo for some discussion?

This sounds good, but considering that multiple LSP servers are allowed to run simultaneously, I'm not sure how this feature should behave then.

> Perhaps another option is that if that the language name is implicitly included in the command filter text for the source-level commands. Eg. typing "dart fix" will match the built-in "fix all" command, because it's filterText is "dart fix all" when you're in a Dart project? 🤔

This one also sounds great.

**Comment by DanTup** [comment]
> I'd respectfully argue with this generalisation, coz for that to happen 1) the language files should be in the opened workspace in order for the extension to activate and provide its commands / other features 2) even if the user has multiple extensions, after they use one of the commands it will be marked as recently used and displayed first

Unfortunately extensions are frequently activated when their projects are not open. Some of the functionality we provide requires that we contribute debug configurations dynamically, and this means whenever you start any debug session, we may be activated. See https://github.com/microsoft/vscode/issues/175202 / https://github.com/microsoft/vscode/issues/88617.

Moving the last used one to the top may help if you're working mostly on one type of project, but I still think it's adding a lot of unnecessary noise to the command list. While it might not mater too much if all the commands just do the same thing, when there are variations (like "Fix All in Workspace") I think that would become more of an issue.


> I'd also avoid this comparison since the initial point was about the command palette and discoverability / awareness. I don't see any of these commands in the command palette.

That's odd - they're definitely there for me:

<img width="273" alt="Screenshot 2023-03-20 at 11 57 13" src="https://user-images.githubusercontent.com/1078012/226332577-42b9b3bf-ef4c-4ae9-a5be-6116ac16f78d.png">

<img width="256" alt="Screenshot 2023-03-20 at 11 57 20" src="https://user-images.githubusercontent.com/1078012/226332580-7be80b40-178b-4d2f-949d-43b6a8518e31.png">


> This sounds good, but considering that multiple LSP servers are allowed to run simultaneously, I'm not sure how this feature should behave then.

Multiple servers shouldn't matter here. The same is true for the built-in "Fix All" command. VS Code calls all providers and merges their results. Although, you raise another niggle. If I run "Dart: Fix All" do I expect _only_ the Dart server to run, or everything? If the user has installed other extensions providing fixes to Dart files, should they be included? I feel like both answers could lead to some kind of confusion.

**Comment by incendial** [comment]
> That's odd - they're definitely there for me:

Ah, of course. They require a dart file to be open, my bad 😅

**Comment by DanTup** [comment]
> Ah, of course. They require a dart file to be open, my bad 😅

Not specifically Dart, just any file that has a formatter / rename provider / etc. registered :-)

**Comment by incendial** [comment]
>  If I run "Dart: Fix All" do I expect only the Dart server to run

IMO, only dart. That's actually another good point. I added support for the custom `source.dcm.fixAll` in order to avoid running simultaneously with the Dart extension avoiding potential collisions. I'd say it's a higher chance that 2 extensions will create conflicts if both trigger on `source.fixAll`. ESLint also has a separate `source.fixAll.eslint` to manage fixes while also supporting `source.fixAll`.

**Comment by incendial** [comment]
> just any file that has a formatter / rename provider / etc. registered

That's confusing, tbh 😞

**Comment by DanTup** [comment]
> IMO, only dart.

This would mean the command is no longer just an alias and behaves differently to the built-in "Fix All". I feel like this is going to lead to more confusion without providing much benefit.


> I'd say it's a higher chance that 2 extensions will create conflicts if both trigger on `source.fixAll`.

I thought VS Code called them sequentially (applying changes to the first set before requesting the second) in order to support this, though I could be wrong.


> That's confusing, tbh 😞

I prefer it this way. When I want to run a command that's valid for my current context, I shouldn't have commands that just can't work showing up in the list that might mean I need to type more characters or navigate through the results.

I do agree things in VS Code aren't often discoverable, but I'm not sure showing everything in the command palette all the time is the best way to solve it.

**Comment by incendial** [comment]
> I feel like this is going to lead to more confusion without providing much benefit.

The only question is how many other Dart extensions contribute to `source.fixAll`? 🙂

> I thought VS Code called them sequentially (applying changes to the first set before requesting the second) in order to support this, though I could be wrong.

Don't know how this part works tbh, it's mostly my assumption (but I don't know which one will be called first and why if that's how it work).

**Comment by DanTup** [comment]
> The only question is how many other Dart extensions contribute to `source.fixAll`? 🙂

I don't know. It could be zero, it could be non-zero. It sounds like your extension would be a candidate for doing so though? I think we should try to avoid making decisions that rely on the answer to that question being one specific way or the other.

Perhaps I've lost track of what we're trying to fix here. Originally the request was that "Dart: Fix All" was just an alias to the built-in "Fix All", but then it was suggested that "Dart: Fix All" should only run things specifically from the built-in Dart extension/analysis server.

I think we should agree exactly what we're trying to solve here before deciding the solution. Is it discoverability (eg. because "Fix All" isn't prefixed with Dart, it wasn't obvious it was there), or is it having the ability to run only the Dart fixes?

**Comment by incendial** [comment]
> I don't know. It could be zero, it could be non-zero. It sounds like your extension would be a candidate for doing so though?

There is a high chance I'll keep a separate `source.` just to let the users easily disable this behaviour if something goes wrong.
I asked the quantity question to suggest that there is really only one extension in the Dart ecosystem and there doesn't seem to be many willing to recreate the full Server + VS Code + IntelliJ set 😁

> Is it discoverability or is it having the ability to run only the Dart fixes?

I created this issue to rise the discoverability issue.

**Comment by DanTup** [comment]
> I created this issue to rise the discoverability issue.

Thanks - in that case I wonder if it's better to raise with VS Code for discussion. If the issue is "when in a Dart file, some of the commands that are known to be handled by the Dart extension like "Organize Imports" do not show up when searching "Dart" in the command palette" I feel like it's better addressed globally by VS Code than every language adding duplicate commands.

WDYT?

**Comment by incendial** [comment]
Sorry, but considering how fast VS Code team implements requests like that, it gives me "let's do this never" kind of vibes. But if you think that waiting for a VS Code team answer / implementation is the right direction to go, I have nothing else to add.

**Comment by DanTup** [comment]
I think if we think the issue is better solved in VS Code that we should raise it there first rather than make assumptions and implement a less optimal solution here.

There are several points about that aren't really addressed by the proposed fix here (around the confusion of having two commands, and whether users would expect them to be the same or not) that are non-issues if handled in VS Code.

If it helps, I've opened an issue in VS Code here. I don't know how receptive they'll be (or how quickly any changes would be made), but I feel like it's better to at least try if the result might be a better experience. Please add your 👍  and we can review this again in future depending on the response.

https://github.com/microsoft/vscode/issues/178875

Thanks!

**Comment by DanTup** [comment]
My VS code issue was unfortunately rejected. They also suggested:

> and I also advise against introducing aliases for the existing built-in commands in the Dart extension

While I do agree discoverability is a weakness in VS Code, I'm inclined to agree we shouldn't do this. We should try to improve visibility of commands like this where possible though.

**Comment by incendial** [comment]
> and I also advise against introducing aliases for the existing built-in commands in the Dart extension

Sure, then we take a look at ESLint language server (made by the same company) and they have an alias. So, makes me wonder whether this advice should be taken seriously at all.

**Comment by DanTup** [comment]
> And can you share how you want to approach this?

I don't have any current ideas for this, but I know it's a general theme. VS Code's UI is quite minimal and there's lots of functionality that isn't obvious if you don't know where to look for it. I'm always open to suggestions and ideas to improve this (although I would also like them to "fit in" with the VS Code way of doing things and other languages).


> Sure, then we take a look at ESLint language server (made by the same company) and they have an alias. So, makes me wonder whether this advice should be taken seriously at all.

That's a fair point. I've noted this at https://github.com/microsoft/vscode/issues/178875#issuecomment-1520023559, it does seem quite contradictory.

**Comment by incendial** [comment]
> although I would also like them to "fit in" with the VS Code way of doing things and other languages

My concern here is that people who need the most to be able to discover things are usually either newcomers (Dart is their first language) or people who just started to use VS Code. First group does not know how "other languages" approach this, the latter does not know what is the "VS Code way".

So, while I understand the idea behind "stick to what others do", feels that it negatively affects the very people that IMO should be considered in the first place (because their productivity features onboarding affects their overall experience).

Does this make sense?

**Comment by DanTup** [comment]
I understand, but I don't think users not necessarily knowing how other languages (or VS Code) work is a reason itself to something _different_. It would be good if users discovered things while using Dart that also transferred to other languages.

It would be good to at least try to engage VS Code to have general improvement in this area rather than doing something different - especially when that thing could be confusing. If there are two commands that do the same, users will wonder why.. if they do something different, that might not be clear to users. It's still not clear to me which of those you're suggesting - the title of the issue is about adding an alias (suggesting they'd be the same) but in [a comment above](https://github.com/Dart-Code/Dart-Code/issues/4446#issuecomment-1476108000) you suggested it should only be things from the Dart analysis server.

On a slightly related note, there's some discussion in https://github.com/dart-lang/sdk/issues/52046#issuecomment-1520499744 about a "simple" version of "Fix All" that fixes less (designed to be more suitable for running on-save), which might lead to us needing to think more about this anyway. If you search for "dart fix", would it be even more unfortunate if "Dart: Fix Simple Issues" shows up but not the general "Fix All"? Or should we even add a command for it at all, or leave it only for the Source menu indenting to be used on-save? 🤔

**Comment by incendial** [comment]
> It would be good to at least try to engage VS Code to have general improvement in this area rather than doing something different - especially when that thing could be confusing.

I understand your point here, maybe this one is a good way to go. If we had any analytics on how users interact with these commands, I'd prefer sticking to the "it's better to do something and see how it affects the numbers than do nothing", since we both agree that the problems exists.

> If there are two commands that do the same, users will wonder why...

IMO, developers do not have a lot of time to continuously wonder why it works that way, so my hypothesis is that they will just pick one and stick with it. That is if all the options behave the same way, of course.

>  It's still not clear to me which of those you're suggesting

As I mentioned here https://github.com/Dart-Code/Dart-Code/issues/4446#issuecomment-1491505543, the discoverability issues is the one I try to discuss here. What exact changes should be made to address it is up to you.

> On a slightly related note, there's some discussion

Yeah, I'm following it. Really curious how the end decision will look like.

>  If you search for "dart fix", would it be even more unfortunate if "Dart: Fix Simple Issues" shows up but not the general "Fix All"?

IMO, yes.

> Or should we even add a command for it at all, or leave it only for the Source menu indenting to be used on-save?

Commands allow you to bind a shortcut to them (for example, if you don't want to call fixes on save) + again, discoverability since you can occasionally find it in the command palette.

**Comment by DanTup** [comment]
> Commands allow you to bind a shortcut to them 

FWIW, you can bind fixes to code actions without commands, see https://code.visualstudio.com/updates/v1_20#_keybindings-for-quick-fixes-and-code-actions

**Comment by incendial** [comment]
Yeah, did I mention the discoverability problem? 😅😂
Didn't know it's even possible! And I'm not even sure how one can find out (with commands it's more straightforward).
