### ISSUE TITLE
Android Studio Emulator is not running

### ISSUE THREAD

**Issue by jisungparkson** [Dart-Code/Dart-Code#4466]
![image](https://user-images.githubusercontent.com/129138706/228129106-796f431d-5961-42b5-ab1b-5c605b286912.png)

When I run the emulator inside the Android studio, it works well as in the picture above.

![image](https://user-images.githubusercontent.com/129138706/228129204-dd8a19e9-b7bf-45f4-a0af-7b095113fc3f.png)
but, When running an emulator in vs code or running an emulator independently in an Android studio, the emulator does not run. 
So I pressed the power button on the emulator. But it doesn't work. how can i solve this problem?

i try to search the google. but there is not a solution

**Comment by DanTup** [comment]
I'm afraid I don't have any suggestions here. This seems like an issue with the Android SDK/emulator, but this repository is only for the VS Code extension. Since the issue exists outside of VS Code (launching the standalone emulator from Android Studio), it's not something that can be fixed here.

I would suggest trying to "Wipe User Data" on the emulator, or "Cold Boot". If neither of those work, I would try deleting and re-creating the emulator.

There are some additional suggestions for a similar issue at https://stackoverflow.com/a/46561953/25124 that may be worth reviewing.

Hope this helps!

**Comment by jisungparkson** [comment]
thank you for your advice :)

**Comment by thalya-codes** [comment]
"Wipe User Data" works for me. Thank you so much.

**Comment by thalya-codes** [comment]
"Wipe User Data" works for me. Thank you so much.
