### ISSUE TITLE
error in gradle

### ISSUE THREAD

**Issue by prince-0702** [Dart-Code/Dart-Code#4476]
unable to resolve class GradleException
 @ line 11, column 15.

it's showing this error any solution for this.

Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' show lerpDouble;

this error also not solved yet

**Comment by DanTup** [comment]
It's hard to say without more context. Do you have the Code Runner extension installed? If so, I would guess you're trying to run using that instead of the Dart/Flutter extensions.

See https://github.com/formulahendry/vscode-code-runner/issues/674.

You can run using the Dart/Flutter extensions with `F5`, the `Run` menu, the Run/Debug links above your `main` function, or by selecting the buttons added by the Dart/Flutter extension here (and not the Code Runner buttons):

<img width="246" alt="Screenshot 2023-04-03 at 11 38 59" src="https://user-images.githubusercontent.com/1078012/229486545-fa77ef14-acb9-4f54-aa45-47d79fab01cc.png">

If you don't have the Code Runner extension, then please let me know exactly how you're trying to start the application that leads to this error.
