### ISSUE TITLE
Support for binding keyboard shortcuts to refactor commands

### ISSUE THREAD

**Issue by zbarbuto** [Dart-Code/Dart-Code#4490]
I use the `_flutter.outline.refactor.*` shortcuts (like "Remove Widget", "Wrap with..." etc) a lot. However, from what I gather from the extension's `package.json`, they are private / not exposed to the keyboard shortcuts:

```
{
	"when": "false",
	"command": "_flutter.outline.refactor.flutter.removeWidget"
},
```

They do not show up in the autocompletes for my `keybindings.json` and even if I manually bind them:

```
  {
    "key": "cmd+'",
    "command": "_flutter.outline.refactor.flutter.removeWidget"
  }
```

the bindings do not work.

**Describe the solution you'd like**

Expose these commands in the command palette so they can be bound to keyboard shortcuts, if not the full list then at least a small selection of the more useful ones. My suggestions would be:

- Wrap with widget
- Remove widget
- Swap with parent
- Wrap with widget...

**Comment by DanTup** [comment]
What you you want to is bind the Code Actions (things that appear on the lightbulb menu) rather than commands. Those commands are specific to some Outline functionality and not the correct way to invoke the refactors.

You can key-bind refactors using with the `editor.action.codeAction` command and a `kind`:

https://code.visualstudio.com/updates/v1_20#_keybindings-for-quick-fixes-and-code-actions

```js
{
  "key": "ctrl+shift+r ctrl+e",
  "command": "editor.action.codeAction",
  "args": {
    "kind": "refactor.extract.function"
  }
}
```

This would create a keybind for the "refactor.extract.function" action (which doesn't exist for Dart, but is what the VS Code example uses). You can find a full list of the refactor and fix IDs for Dart here:

https://dartcode.org/docs/refactorings-and-code-fixes/

So for example, to "Wrap with widget...":

```js
{
  "key": "ctrl+shift+r ctrl+e",
  "command": "editor.action.codeAction",
  "args": {
    "kind": "refactor.flutter.wrap.generic"
  }
}
```

As well as `kind`, you can also add `apply` to control the behaviour if there's more than one match (for example if you set `kind` to just `"refactor.flutter.wrap"`), see https://code.visualstudio.com/updates/v1_20#_keybindings-for-quick-fixes-and-code-actions:~:text=Valid%20values%20for%20%22apply%22%3A for details.

Let me know if you have any issues making this work. Thanks!

**Comment by zbarbuto** [comment]
Perfect, that did the trick, thanks.

I think I got tripped up because the `refactor.flutter` ones don't appear in the autocomplete suggestions for `kind`:
 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/9100419/231114519-5c952552-a078-4650-b496-44af44fe5aa0.png">

even though ones for `command` do:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/9100419/231114602-3a50aba8-de39-4c2b-87f9-1a4d7336f24b.png">

and when I went hunting in this repo for the declarations I just found the ones in the [package.json](https://github.com/Dart-Code/Dart-Code/blob/master/package.json#L579-L613).

That [refactorings-and-code-fixes/](https://dartcode.org/docs/refactorings-and-code-fixes/) doc is really useful.

Thanks again for the quick help.
