### ISSUE TITLE
Make file references in Debug Output (from hot reload, flutter test, exceptions) clickable

### ISSUE THREAD

**Issue by matanlurey** [Dart-Code/Dart-Code#451]
See https://github.com/flutter/flutter/issues/13188 for some background.

It would be really sweet to see:

> • Food (lib/src/data.dart:6)
> • starchesRanked (lib/src/data.dart:33)

Become clickable links to the source code (just an example):

> • [Food (lib/src/data.dart:6)](#)
> • [starchesRanked (lib/src/data.dart:33)](#)

If this is better done through the flutter CLI, let me know. I'd be happy to try and contribute too!

**Comment by DanTup** [comment]
Parsing the output probably isn't hard, but I'll need to figure out whether we can actually get clickable links into the Debug Console in Code.

**Comment by DanTup** [comment]
Based on https://github.com/Microsoft/vscode/issues/15760 it seems like this should just work. I'll need to do some testing and see if I can figure out why it's not working for us.

**Comment by matanlurey** [comment]
Great. I'm happy to try and help out if you can point me in the right direction.

**Comment by DanTup** [comment]
I think this is the original implementation in Code:

https://github.com/Microsoft/vscode/pull/24451

I can't see why it should work :(

I tried sending output in a few different formats to see if any worked... I fudged this code into `dart_debug_impl.ts` in the `log` method:

```ts
this.sendEvent(new OutputEvent(`Danny3 (lib/test.dart:1:1)\n`, "stdout"));
this.sendEvent(new OutputEvent(`Danny3 (lib/test.dart:1:1)\n`, "console"));
this.sendEvent(new OutputEvent(`Danny3 (lib/test.dart:1:1)\n`, "stderr"));
this.sendEvent(new OutputEvent(`Danny3 lib/test.dart:1:1\n`, "stdout"));
this.sendEvent(new OutputEvent(`Danny3 lib/test.dart:1:1\n`, "console"));
this.sendEvent(new OutputEvent(`Danny3 lib/test.dart:1:1\n`, "stderr"));
this.sendEvent(new OutputEvent(`Danny3 ./lib/test.dart:1:1\n`, "stdout"));
this.sendEvent(new OutputEvent(`Danny3 ./lib/test.dart:1:1\n`, "console"));
this.sendEvent(new OutputEvent(`Danny3 ./lib/test.dart:1:1\n`, "stderr"));
```

But still none of the output is linked:

<img width="479" alt="screen shot 2017-11-23 at 22 11 41" src="https://user-images.githubusercontent.com/1078012/33189539-83653af0-d09b-11e7-9986-de7854e9be84.png">

I'm gonna raise an issue against Code to see if they can advise. I can't find any docs on how it should work, but have found many screenshots showing it working for others!

**Comment by matanlurey** [comment]
Sounds great, thanks for taking a look!

**Comment by DanTup** [comment]
I've raised https://github.com/Microsoft/vscode/issues/39063 to see if someone on the Code team can clarify the rules (or suggest why it might not be working).

**Comment by matanlurey** [comment]
It would be swell for this to work for stack traces too :)

```
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      HotRunner.validateReloadReport (package:flutter_tools/src/run_hot.dart:407)
#3      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:528)
```

**Comment by DanTup** [comment]
That one might be trickier because of `dart:`.. The current functionality in Code (when it works) just detects the paths and links them. Here we'd probably need to rewrite them in the output to relative (or in the case of the SDK, absolute) paths.

Once we've figured out the easy case, I'll do some digging though. We do have some handles in code to open certain schemes (we use them to make the package files read-only), so maybe we can convince it that the `dart:` links are valid.

**Comment by DanTup** [comment]
Had a response in https://github.com/Microsoft/vscode/issues/39063, seems like there are still issues with it. There's info about where the detection is done in Code, so if running Code from source is easy, it might be fairly simple to track down why it's not working for us yet.

Interestingly there's also this comment in the [related case](https://github.com/Microsoft/vscode/issues/34026):

> Also consider a way for extensions to contribute link detection rules

This would probably handle the `dart:` issue mentioned above :-)

**Comment by DanTup** [comment]
Looking at this again.. however need some help from MS because to me it looks like the link detection code never executes (in fact, I think the minifier strips it out because it can never execute). However, I can see screenshots of people showing it working (and presumably they have tests) so ¯\_(ツ)_/¯

Will come back to this once I get a response to:

https://github.com/Microsoft/vscode/issues/34026#issuecomment-377204242

**Comment by DanTup** [comment]
So, seems like this indeed a big whoopsie in Code:

https://github.com/Microsoft/vscode/issues/34026#issuecomment-380829194

If I can get some info on how to work on Code I might see if I can contribute a fix.

**Comment by DanTup** [comment]
This is fixed for vNext in a slightly different way to the original plan (due to the VS Code issues). We detect the links in the lines and strip them out, and attach some metadata to the log event (splitting it up into a log-per-line) that displays a clickable link on the right:

<img width="700" alt="clickable_stack_traces" src="https://user-images.githubusercontent.com/1078012/51551908-68c95300-1e67-11e9-872e-03ca6624d9b0.png">

There are beta builds here:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.22.0-beta.2

(I accidentally duplicated this at #1380 where I tagged the fix)
