### ISSUE TITLE
Conditional imports not checked

### ISSUE THREAD

**Issue by mosuem** [Dart-Code/Dart-Code#4525]
**Describe the bug**
When importing libraries, there is a check if this library actually exists `dart(uri_does_not_exist)`. This is not called on conditional imports, such as 
```
import 'something.dart' if(dart.library.js) import 'somethingelse.dart'
```

**To Reproduce**
Write
```
import 'something.dart' if(dart.library.js) import 'somethingelse.dart'
```
where 'something.dart' exists, but 'somethingelse.dart' doesn't.

**Expected behavior**
Should trigger on both.

**Screenshots**
![image](https://user-images.githubusercontent.com/27859082/236786655-f9d8c7f7-e6b4-4746-9723-99279987709a.png)

**Please complete the following information:**
 - Operating System and version: Linux
 - VS Code version: 1.76.2
 - Dart extension version: v3.63.20230502
 - Dart/Flutter SDK version: `Dart SDK version: 3.1.0-39.0.dev (dev) (Mon Apr 24 18:53:55 2023 -0700) on "linux_x64"`

**Comment by DanTup** [comment]
This is available as an opt-in lint:

https://dart-lang.github.io/linter/lints/conditional_uri_does_not_exist.html

It wasn't built into the server by default because it turned out to be quite noisy because some codebases import generated files conditionally, but those files are not generated at dev time (some discussion in https://github.com/dart-lang/linter/pull/3080).

**Comment by mosuem** [comment]
Interesting! Wouldn't it be nicer to have a lint to disable this optionally though, if the problem is noise for certain projects?

Also, there seems to be no code completion for the file paths on these conditional imports - should I open a new bug for that?

**Comment by DanTup** [comment]
> Interesting! Wouldn't it be nicer to have a lint to disable this optionally though, if the problem is noise for certain projects?

There was some discussion about this at the time (some in https://dart-review.googlesource.com/c/sdk/+/202924 and some via email). I think the concern was that enabling it by default could cause new warnings on otherwise clean projects (it caused issues internally and we don't know how many other projects might have similar setups).

Originally the implementation was in the SDK, but it was moved to the lint. In theory the lint could be added to the base/recommended set, but I don't know how much less breaking that is (if everyone uses it, it might not be much different).

@bwilkerson @devoncarew FYI

**Comment by mosuem** [comment]
That would be nice.

Regarding the code completion, @DanTup filed a new issue at https://github.com/Dart-Code/Dart-Code/issues/4530.
