### ISSUE TITLE
Auto-completion not working when legacy analyzer is unchecked in VSCode

### ISSUE THREAD

**Issue by rirjkl19** [Dart-Code/Dart-Code#4534]
**Describe the bug**
Auto completion is not working as expected when using LSP. Whenever I try to use the auto complete feature, it suggests irrelevant or incomplete options. This issue makes it difficult to work with the codebase effectively.

**To Reproduce**
Unfortunately I can't reproduce the issue in new projects and my assumption would be the tenth/thousands of classes is globally accessible due to graphql generated queries and mutation by apollo package. But here is the gist of it: 

1. Create a deeply nested custom widget in the file structure: `Lib/path/deeply/nested/down/my_custom_widget.dart`
2. Call the `MyCustomWidget` class from a different file without importing it for now.
3. When typing the "MyCusto" or even "MyCus", the expected behavior is for the "MyCustomWidget" class to be suggested in the auto-completion and auto-import.

**Expected behavior**
The "MyCustomWidget" class should be suggested in the auto-completion and auto-import when typing "MyCusto" or even "MyCus".

**Screenshots**
Due to privacy policy of the files. I can't provide some screenshot. (Need to still check if I can reproduce the issue without the production application)

 - Flutter doctor -v
```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.0 22A380 darwin-arm64, locale en-PH)
    • Flutter version 3.7.7 on channel stable at /Users/$user/fvm/versions/3.7.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode_14.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

 - VSCode Flutter v3.63.20230303 (pre-release)
 - VSCode dart v3.63.20230502 (pre-release)
 - Legacy Analyzer Protocol (checked)

**Comment by DanTup** [comment]
@rirjkl19 could you reproduce this issue and then do the following:

- Run the **Dart: Open Analyzer Diagnostics** command from the command palette (`F1`)
- Click on "Code Completion" on the left nav
- Take a screenshot of the page that shows the timings for the recent completion requests
- Click on the time (the blue link) next to the recent completion request that was missing the items you expected
- Take a screenshot of that page showing the detailed timings

Thanks!

**Comment by rirjkl19** [comment]
@DanTup I'm having hard time to replicating this because I'm replicating this in production project we were working on. Seems to only happen in our project (tried doing this in a fresh project but everything seems ok).


Before using `cmd + .`:
![image](https://github.com/Dart-Code/Dart-Code/assets/20448341/501536b1-26eb-43ca-a5ff-388ab96339ac)

After using `cmd + .`:
![image](https://github.com/Dart-Code/Dart-Code/assets/20448341/7b31a249-db14-408c-9651-ebef25676f48)


Before using `cmd + .`:
![image](https://github.com/Dart-Code/Dart-Code/assets/20448341/03abe9fe-0185-4f84-baf6-d33d29dd98d0)

After using `cmd + .`:
![image](https://github.com/Dart-Code/Dart-Code/assets/20448341/f9f1fdbb-29ff-45c7-bf7f-5aa09cd2f729)


Sorry took me awhile because I'm replicating the issue without disclosing of the actual file names of the project.

**Comment by DanTup** [comment]
@rirjkl19 thanks for the info. Just to clarify, is the issue that the class does not show up in completion before it's imported, but once you have imported it (using the quick-fix), it then does appear?

Since all your requests are > 100ms, my suspicion is that the budget imposed for finding "not imported" symbols is being exhausted (it's 100ms). The reason there is a limit on this, is that on very large projects it could take a long time to collect all not-imported symbols, and since we can only provide code completion once, if we keep waiting it could make code completion slow even when you don't want those symbols.

Instead, we signal to VS Code that the results we provided are not complete, and it will ask us again when you have typed more characters. The theory is that the next time it asks (and you have typed more characters), the search will be faster and more likely to complete. However, it might be that in your case it's still too long.

Are you able to give some idea of the size of your workspace (how many projects, and how many dependencies they have), and what sort of machine you're developing on? Thanks!

**Comment by rirjkl19** [comment]
> @rirjkl19 thanks for the info. Just to clarify, is the issue that the class does not show up in completion before it's imported, but once you have imported it (using the quick-fix), it then does appear?

Yes this is case. Everything works ok once the file is already imported.

> Are you able to give some idea of the size of your workspace (how many projects, and how many dependencies they have), and what sort of machine you're developing on? Thanks!

We only have 1 flutter project. I counted the `pubspec.yaml` and the package count is atleast 80 dependencies 🤣 .
My other suspicion would be a lot of global classes generated by graphql code generation which would at least be more than 10,000 class names, high chance it could be higher.

Based on your explanation. How come using the legacy protocol keeps suggesting the correct class under the 100ms? I find it weird.

**Comment by DanTup** [comment]
> Based on your explanation. How come using the legacy protocol keeps suggesting the correct class under the 100ms? I find it weird.

The legacy protocol works in a different way which involves pushing the entire symbol list to VS Code up-front, and then telling it about all changes (essentially having a giant cache in the editor). This is more complex (and might take a while to populate after you open the project) and is very specific to Dart whereas the new protocol (LSP) is a general protocol used by many languages and many editors (the goal of LSP is to reduce the amount of specific per-client-per-language work to have many languages supported by many editors).

Right now I don't have a way to increase or disable this budget in a release build for testing, but it would be useful if we could determine how long it would take (without the budget). I don't know whether it's close (for example 110ms), or way off (for example 1 second). Being able to temporarily disable it might give an idea of how far off it is, and also allow collecting some timings for the full search.

Let me think a little more about this and get back to you soon.

Could you also confirm what sort of specs the machine you're running on are? The closer I can get to your setup, the easier it'll be able to for me to measure the impact of changes by running the server from source.

Thanks!

**Comment by rirjkl19** [comment]
Here it is @DanTup .

```
14-inch Macbook Pro
Chip Apple M1 Pro
Memory 16GB
macOS 13.0 (22A380)
```


Thank you for the explanation. Will check on what specific cases I could do so it can be avoided and what other things could have caused this. 👍🏻

**Comment by DanTup** [comment]
@rirjkl19 are you able to share the full list of dependencies you have, and if possible check how many classes your generated code has (and whether they're all in a small number of files or a large number might help too). It would be helpful if I can set up a similar project to better measure where the time is going.


I've also pushed a pre-release extension that allows overriding the completion budget so that we can capture some numbers. Could you please try the following?

1. Switch to the pre-release version of the Dart extension in VS Code (it should be v3.65.20230518)
    <img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">
2. Open your VS Code user settings with `Cmd`+`,`
3. Add `"dart.completionBudgetMilliseconds": 10000,` to the settings file
    (VS Code may say that this isn't a recognised setting, you can ignore that)
4. Run the **Developer: Reload Window** command from the command palette (`F1`)
5. Trigger the situation where the completion would not normally show up.. hopefully now it will, but the completion will take longer (the setting above increases the budget to 10 seconds)
6. Run the **Dart: Open Analyzer Diagnostics** command to get copies of the timings for the completion as you did above

You will want to remove the setting after testing (or at least, set it to a much lower value - because otherwise completion may always be very slow). But this should at least give us an idea of how long the completion is taking if there was no budget.

Thanks!

**Comment by rirjkl19** [comment]
Hi @DanTup sorry it took me awhile to get back on this issue as I've broken my laptop and I've lost the reproducible code (in our project) that I was able to replicate before. 

Though one thing I remember is that I've updated the Vscode, flutter extension (including dart) and flutter version we use (3.10.1). I practically setup a new working environment (station) for new laptop. I also have considered disabling the `Legacy Analyzer Protocol` and everything seems to be working ok now. I might close this issue without having to follow your instructions for some reason.

Will get back to this once the issue arise again. Thank you again!

**Comment by DanTup** [comment]
>  I also have considered disabling the Legacy Analyzer Protocol and everything seems to be working ok now

Do you mean you didn't _enable_ the legacy protocol and everything is working with the default/non-legacy protocol?

If so, that's great. There have definitely been improvements with each release so the recent Flutter could have fixes that weren't in previous versions.

Anyway, if you do hit issues with the LSP protocol, please do let me know. The legacy protocol will be dropped at some point so if there are remaining issues with it, they need identifying and fixing.

Thanks!
