### ISSUE TITLE
Function autocomplete does not work for function overrides

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4538]
**Describe the bug**

In Dart-Code, if I create a `StatefulWidget`, and then hit Ctrl+Space and type "init", I do not get the autocomplete `@overrides initState() { ... }` .

**Expected behavior**

I would expect (as with Eclipse) that superclass functions that can be overridden should be able to be autocompleted, complete with `@overrides` being added automatically.

**Please complete the following information:**
 - Operating System and version: Fedora Linux latest
 - VS Code version: 1.78.1
 - Dart extension version: latest
 - Dart/Flutter SDK version: 2.19.4

**Comment by DanTup** [comment]
@lukehutch can you give an example of the code where you're triggering this? I don't get `initState` in the `StatefulWidget` class, but that's because it appears to be in the `State` class. It does seem to work for me there (although I'm using Dart 3):

<img width="487" alt="Screenshot 2023-05-15 at 12 46 46" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/59939486-06e7-46e0-83a1-4417506ac683">

**Comment by DanTup** [comment]
Oh, nevermind - I can repro:

![May-15-2023 12-48-55](https://github.com/Dart-Code/Dart-Code/assets/1078012/a81220cf-98cd-4407-b0c7-c7b1fc1d9b80)

Strangely if I close completion and then press Ctrl+Space again, it's there. I would expect those things to be equivalent. I'll do some digging. Thanks!

**Comment by DanTup** [comment]
A minimal repro:

```dart
class Base {
  void method() {}
}
```

```dart
class Derived extends Base {
  ^ // Ctrl+Space here does not include method
}
```

```dart
class Derived extends Base {
  i^ // Ctrl+Space here does include it
}
```

My guess is that when there are no characters typed the AST/completion target is different in a way that prevents this.

**Comment by DanTup** [comment]
@bwilkerson this happens because the override contributor currently only works if there is a target to replace:

https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/lib/src/services/completion/dart/override_contributor.dart#L23-L25

This means in cases where you've not typed any prefix and just hit Ctrl+Space such as at the end of a class:

```dart
class Derived extends Base {
  ^
}
```

Or before a member:

```dart
class Derived extends Base {
  ^

  void f() {}
}
```

Then you won't see the results. Since we can't be sure the client will re-request completions on the next keypress, this can lead to the situation above (you start typing a method name and it's just not in the completion list because it's filtered client side, but if you close completion and re-invoke it, it is).

I created a fix that handles these two cases here:

https://dart-review.googlesource.com/c/sdk/+/323660

However, the way it detects the second case above (it checks if the target is a class member that starts _after_ the requests offset) is too greedy and includes cases like this (which exist in some tests and fail because of extra completions):

```dart
class A0 {
  final ^
  A0() {}
}
```

I'm not sure there's enough information in the current completion target to detect this (I can't find an obvious way to tell that we're in the middle of a possible variable declaration). I'm also aware you wanted to change how completion (targets?) worked slightly, so I'm interested if you a) have a suggestion about how to handle this or b) if it's better left until after those changes are done.

**Comment by bwilkerson** [comment]
> ... I can't find an obvious way to tell that we're in the middle of a possible variable declaration ...

Yeah, the completion target by itself quite likely doesn't have enough information. What we end up doing in most such cases is using the `containingNode` getter to get a pointer into the AST and then start looking at the AST and/or token stream to find out what's really there. That has less to do with `CompletionTarget` and more to do with the way the parser recovers in the face of an error.

I don't know, off hand, how the parser recovers from the test case, so I don't know exactly what you'd need to look for.

> I'm also aware you wanted to change how completion (targets?) worked slightly ...

Yep. The computation used by completion targets to find the `containingNode` is, IMO, hard to understand. It's also the only place where this computation is used. Everywhere else in server we use the notion of a _covering node_ as the basis. I find the covering node to be much easier to understand. Part, though not the biggest part, of what I'm trying to accomplish is to convert code completion to use the covering node.

> ... or b) if it's better left until after those changes are done.

I'd kind of prefer that any work on code completion be done in the new framework so that we aren't adding to the list of code that needs to be migrated over, but that's more of a nice to have than a necessity.

The new framework is almost far enough along that I think we could do this work there. I'm in the middle of a change that will impact such an effort, but I think it's the last such change that I'll need to make. I don't have an estimate for when that will be done, but I'm hoping to have it done before the end of next week. After that change I think it will be much easier to have multiple people working on code completion at the same time and I'd be happy to explain the new framework so that you can work on this change there, if you want to wait that long.

**Comment by DanTup** [comment]
sgtm. This definitely isn't pressing, everything is fine if you trigger completion by typing the first character (which I suspect is by far the most common case). Thanks!

**Comment by DanTup** [comment]
This has been fixed by other changes (possibly the completion refactor) - hitting Ctrl+Space before a member or at the end of a class without having partially typed the identifier still suggests overridable members:

https://github.com/Dart-Code/Dart-Code/assets/1078012/a1554f85-a935-4044-a919-317d5f031c73

https://github.com/Dart-Code/Dart-Code/assets/1078012/01f627d7-1e8f-49bb-8ca5-e6c9cbbeb97c

Additionally, you can now start typing `@override` to see just the overridable members:


https://github.com/Dart-Code/Dart-Code/assets/1078012/71c42043-90c9-4fd3-b925-cb0e7e100872
