### ISSUE TITLE
Failed to Hot Reload: DebugAdapterException: app 'null' not found

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4542]
Happened while saving when an app was being launched:

<img width="545" alt="Screenshot 2023-05-15 at 16 49 06" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/7313d2bb-21e1-4f7c-81ef-742aafff464c">

**Comment by DanTup** [comment]
Fix landed in Flutter.

**Comment by merouane-tazeka** [comment]
@DanTup in which version was it fixed.
I am running 3.16.1 and I can't upgrade right now because it would bring breaking changes on my projects.
I encounter that issue only when trying to debug a web app on my Linux server, but I don't get it when using my Mac, so I am not sure if the issue is related to Flutter or my Linux Server development environment.
