### ISSUE TITLE
Provide fix for line length exceeds the 80-char limit for strings.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#4548]
the following code generates a warning

`The line length exceeds the 80-character limit.\nTry breaking the line across multiple lines.`

```dart
final addressLines =
        'gcloud beta compute  --project=$project  addresses list --format="csv(name, address, region, subnet, status, labels, networkTier, addressType, purpose)"'
            .toList();
```

 
Manually splitting the line can be dangerous.
The best fix is to change the outer quotes from ' to '''.

This appears to be a good candidate for an auto fix in vs-code.

Vs code should change the code to:

```dart
final addressLines =
       '''gcloud beta compute  --project=$project  addresses list --format="csv(name, address, region, subnet, status, labels, networkTier, addressType, purpose)"'''
            .toList();
```
Note the change from single quote to triple quotes at the start and end of the line.

**Comment by DanTup** [comment]
Also a fair request. I did open a VS Code issue to try and make breaking strings manually easier (eg. you click in a string and press `<enter>` and we add the extra quotes for you) - see https://github.com/microsoft/vscode/issues/164469.

However, that would be quite limited because of how `onEnterRules` work in VS Code, so a server fix could do more.

Please file at https://github.com/dart-lang/sdk/issues where the work for fixes would be and post a link back here (unfortunately we can't move issues across organizations, and if I create it there you won't be the author). Thanks!
