### ISSUE TITLE
auto fix unnecessary duplication of receiver

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#4550]
The following code generates a warning:

`cascade_invocations`

`Unnecessary duplication of receiver.\nTry using a cascade to avoid the duplication.`

```dart
      final subnet = Subnet();
      subnet.name = parts[0];
      subnet.zone = parts[1];
      subnet.network = parts[2];
      subnet.range = parts[3];
      subnets.add(subnet);
```

It would be useful to have an auto fix which changes the code to:

```dart
     final subnet = Subnet()
        ..name = parts[0]
        ..zone = parts[1]
        ..network = parts[2]
        ..range = parts[3];
      subnets.add(subnet);
```

**Comment by DanTup** [comment]
Sounds like a fair request to me. There is an existing fix, but it only works one at a time (and doesn't appear enabled for fix-all). I'm not sure what's involved in handle this (since it's essentially one fix that would fix multiple diagnostics - something I don't think other fixes do).

Could you re-raise this at https://github.com/dart-lang/sdk/issues (and post a link back here)?

Thanks!
