### ISSUE TITLE
VSCode Extension is showing in correct status of sync settings in GUI

### ISSUE THREAD

**Issue by burhankhanzada** [Dart-Code/Dart-Code#4560]
**Describe the bug**
Showing the incorrect status of setting async as you can see i have defined it in the settings json but its saying the setting is not synced

**To Reproduce**
1. Go to 'GUI Settings'
2. Enable 'Flutter SDK Paths'

**Expected behavior**

this should say setting syn and when i tap to syn setting it adds that setting to ignore the settings list

**Screenshots**
![Screenshot](https://github.com/flutter/flutter/assets/18241005/59d9f2f8-d239-4762-8acf-aec67e65ac7b)
![Screenshot 1](https://github.com/flutter/flutter/assets/18241005/c9709b57-c3e7-4cb0-9798-492da98de7d2)

**Please complete the following information:**
 - Operating System and version: MacOS Ventura 13.3.1
 - VS Code version: 1.78.2
 - Dart extension version: 3.64.0
 - Dart/Flutter SDK version: 3.10.1
 - Target device (if the issue relates to Flutter debugging): na

**Comment by DanTup** [comment]
I'm not very familiar with settings sync, but according to [this page](https://code.visualstudio.com/docs/editor/settings-sync#:~:text=one%20by%20one.-,Configuring%20synced%20data,-Machine%20settings%20(with) settings defined as machine-overridable (which `dart.flutterSdkPaths` is) are not synced by default.

I don't know why this doesn't show up in the UI though, but it's something that would need to be handled by VS Code (https://github.com/microsoft/vscode) because extensions have no influence over the UI status you see here, that's all rendered by VS Code and the settings sync. We only tell VS Code what settings we have, and are not involved in any sync behaviour.

**Comment by DanTup** [comment]
Closing this because I don't think there's anything here for us, but post back if you think that isn't the case of I may have misunderstood. Thanks!
