### ISSUE TITLE
Root package should not be required for root analysis_options.yaml

### ISSUE THREAD

**Issue by polina-c** [Dart-Code/Dart-Code#4574]
PR: https://github.com/dart-lang/leak_tracker/pull/80

Discussion: https://github.com/dart-lang/leak_tracker/pull/80#discussion_r1218959705

**Comment by polina-c** [comment]
<img width="797" alt="Screenshot 2023-06-06 at 5 05 34 PM" src="https://github.com/Dart-Code/Dart-Code/assets/12115586/940624dc-f94d-4653-9ad0-71e31af51dbb">

**Comment by DanTup** [comment]
If there's work to be done we might want to move this to dart-lang/sdk as it's the analysis server handling this.

I'm not sure what the correct behaviour is here though. @bwilkerson @devoncarew interested in your thoughts.

What's happening here is that there is an `analysis_options.yaml` in the root of the repository, but there is no project there. The `analysis_options.yaml` is there only to be included by packages in child folders.

However, the server creates a context for the root folder (because of the `analysis_options.yaml`) and can't resolve the `package:flutter_lints` reference).

I don't know if the server ignoring this file here is reasonable, because there could be `.dart` also alongside this file that you would assume would be linted based on the settings of that file (I don't know if that's useful, but presume this is the behaviour today).

Some possible fixes/workarounds:

- Move the file into the "main" package folder and include it as "../main_package/analysis_options.yaml" from the other packages
- Remove flutter_lints from here and include it directly in the other analysis options (although I'm not sure if multiple includes are supported?)

**Comment by polina-c** [comment]
I created workaround to reference side instead of root.

If i face this again, i will reopen the bag.
