### ISSUE TITLE
Add option to set a delay to when the language server should receive a file update event

### ISSUE THREAD

**Issue by jellynoone** [Dart-Code/Dart-Code#4575]
**Describe the solution you'd like**
If possible, I would like to be able to set a duration after which the language server would be informed of file changes.

I don't know if this is possible or how the updates are handled by the plugin, but my guess is that when a file is changes, the language server is informed of changes, and I also guess this is happening in realtime as we type.

If this is the case, I would like to suggest a solution where the user of the plugin could set a delay from when they change the file to when the language server would receive the update.

This way, for instance, the user would be able to type without the analysis being run until they actually stop for the set duration. My assumption here is that this might mildly increase the performance on older devices for a user while they are typing.

So in a way, what I'm suggesting is if the update events can be buffered for a user determined duration and then sent to the language server after some duration.

**Additional context**
Previously, I suggested #3068 , where the analysis would be run onSave, however, looking backing, I think the solution here is more reasonable and practical.

I mean how many times do you need up to date analysis information directly while typing. And with this setting if you need it, you would just wait for the set amount of time, which I think for most, would be a second or two.

Would something like this be possible to implement?

**Comment by DanTup** [comment]
It's not possible to implement this here as the interaction between VS Code and the LSP server is done by the VS Code LSP client. This would either need to be implemented by VS Code, or the LSP client (which lives at https://github.com/microsoft/vscode-languageserver-node/).


> I mean how many times do you need up to date analysis information directly while typing. 

I think this is more than you'd think. All of the language features like code completion and semantic tokens (syntax highlighting) rely on having parsed/resolved results. If the analysis was delayed, these features wouldn't work correctly - code would be highlighted incorrectly for much longer and code completion wouldn't be able to provide the correct options.


I think it would be better to start from the problem rather than propose a solution. What's the issue you're seeing that makes it seem like this is a good idea? Perhaps there is another fix for the issue?

**Comment by jellynoone** [comment]
Thanks for the information.

Honestly, there is nothing out of the ordinary and everything is working as expected.
I'm currently editing a large project, and running on a 8GB of ram device, so in my eyes the analyser is doing a stellar job.

It's just my personal preference to not get immediate updates while typing.

I used to use a PHP plugin a few years ago, which performed or at least reported errors on save rather than while typing and I just really liked that feature. However, there the highlighting and type information was still correct. I also don't think it used the LSP, so its probably not comparable.

So to iterate, there are no obvious issues I'm experiencing based on the work I'm doing. I just thought if this were possible, it would be a feature some users would find useful.

Thank you for a quick response and awesome work!!!

**Comment by DanTup** [comment]
> It's just my personal preference to not get immediate updates while typing.

Do you mean you'd prefer to not have the diagnostics updating visibly so frequently, and this isn't about reducing the work the server does / improving performance?

**Comment by jellynoone** [comment]
That's correct.
I'm not going to lie the potential performance aspect is also in the back of my mind, but its not the main driver for this issue.

Additionally, after making the previous comment I checked out the repository you linked and it turns out the lsp is already debouncing / delaying updates.

And after that, I also took another look at the settings, and it turns out the natively provided: `editor.quickSuggestionsDelay` actually does a lot of what I wanted to achieve.

Of course, it doesn't visually delay error informing, but at least the suggestions come up with a more favourable, to me, delay.

**Comment by DanTup** [comment]
I think if the visible updating is an issue it's worth filing this with VS Code (I do also find it a distraction, and not only in Dart - in TypeScript too). While the language server could delay these updates, that could impact other things (for example CodeAction requests sent diagnostics with them, so delaying diagnostics will change the data they send). If the issue is purely visible, I think it should be handled by VS Code in the UI.

That said, if you're seeing performance issues then they should be investigated as performance issues and not necessarily be solved by reducing the frequency of analysis. There have been several performance improvements made in the last few weeks and with good reports and repros there may be more that can be improved. If you feel that things aren't as fast as they should be, please file issues specifically about them and we can try to dig into them.

Thanks!
