### ISSUE TITLE
Is DartCode the same as the debug adapter that ships with dart/flutter?

### ISSUE THREAD

**Issue by joshpetit** [Dart-Code/Dart-Code#4578]
I see this repo and also the debug adapter available for dart installs. Is this a project that supplements that or the same project. Neither?

**Comment by DanTup** [comment]
This project is the VS Code extension. It does contain implementations of the debug adapter protocol in TypeScript, but these are being replaced by the ones shipping in the Dart/Flutter SDKs.

Today, most people are still using the legacy (TypeScript) adapters because we're still in the process of migrating over (we've hit a few bumps that have delayed the rollout), but I'm hopeful soon everyone will be on the SDK adapters.

If you're using VS Code and want to force use of the new adapters, you can set `"dart.previewSdkDaps": true` in your user settings.

If you're using another editor and trying to figure out which debug adapters to use, definitely use the SDK ones. There's info on using them here:

- https://github.com/dart-lang/sdk/blob/master/pkg/dds/tool/dap/README.md
- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/debug_adapters/README.md

If you have any questions (or problems) using them, please let me know!

**Comment by joshpetit** [comment]
Awesome sounds good! Is anything missing from the sdks that might warrant waiting till the migration is over? I saw an issue related to web, but that's not a real concern for me.

**Comment by DanTup** [comment]
Do you mean for VS Code or another editor?

If you're using another editor, you should definitely use the SDK DAPs. If you mean in VS Code, then if you're on stable SDKs the things I know about are:

- `vmServiceInfoFile` doesn't work for Flutter (unlikely this will matter to you) - https://github.com/Dart-Code/Dart-Code/issues/4577
- Structured Errors are not rendered as well as with the legacy DAPs - https://github.com/Dart-Code/Dart-Code/issues/4571
- there are some crashes reported by flutter_tools reporting, but I think they're all weird edge cases (during shutdown, and/or caused by having multiple debuggers attached)

My suggestion would probably be to use the new SDK DAPs. If there are any other remaining issues we don't already know about, the sooner they are found the better :-)

**Comment by joshpetit** [comment]
Sounds good that's reason enough for me to use the sdk daps, thanks a lot
