### ISSUE TITLE
feat: provide option to exclude path for "run pub get" on outdated packages

### ISSUE THREAD

**Issue by Luckey-Elijah** [Dart-Code/Dart-Code#4581]
**Is your feature request related to a problem? Please describe.**
When opening VS Code in a multi-package workspace, I **do not** want the message

> Some packages are missing or out of date, would you like to get them now?

to appear for a specified path or glob.

**Additional context**
I use `mason` for generating dart packages in my workspace, but the package template is in the workspace so it is evaluated in the check for 

```
[ ... ] [General] [Info] Found 1 folders requiring "pub get" or "pub upgrade":
````
 But this is an issue since the package template itself is an invalid dart package. It might include characters like `{`, `}`, `(`, and `)` in the `pubspec.yaml`'s `name`and in the package's path.

In my project I would specifically like the ability to exclude a glob like `bricks/*/__brick__/**` to align with my analysis file.

**Comment by DanTup** [comment]
I've pushed a change so that paths containing `__` or `{` are excluded from this check. We can consider adding config if it turns out there are more complex requirements, but for now I think this is simplest and should cover most of this kind.

Flutter has its own templates but actually renames the files (`pubspec.yaml.tmpl`) which doesn't trigger the check because there's no `pubspec.yaml`, so that's also a possibility for templating projects.

**Comment by Luckey-Elijah** [comment]
The template syntax for my use case is mustache (leverages `{` and `}`) so I believe your changes will work. Thank you
