### ISSUE TITLE
Add type annotation quickfix should appear anywhere on the line

### ISSUE THREAD

**Issue by Merrit** [Dart-Code/Dart-Code#4601]
**Is your feature request related to a problem? Please describe.**
The quickfix for "Add type annotation" only appears if the cursor is near the variable name, and not further along or at the end of the line.

**Describe the solution you'd like**
The quickfix should be available no matter where on the line the cursor is, if the fix is available.

**Additional context**
I often find myself having to move the cursor to the start of the line to add a type annotation, which seems unnecessary when I am looking for an action related to a spot earlier in the focused line.

Example:

```dart
void main() {
  final one = 1;
}
```

With the cursor at the beginning of the line, or nearly anywhere before the `=`, the quick fix offers to add a type annotation:

![image](https://github.com/Dart-Code/Dart-Code/assets/9575627/fcb20120-0240-4387-8174-4aace8bd67c0)

With the cursor after the variable name or at the end of the line, no quickfix is offered for type annotations:

![image](https://github.com/Dart-Code/Dart-Code/assets/9575627/793b8d93-9a1f-4cc3-93ef-481ff06d6bd2)

**Comment by DanTup** [comment]
What's shown in your screenshot is not actually a fix, it's what the server calls an "assist". Only fixes appear for the whole line of a diagnostic, assists and refactors show only for the specific locations where they are valid.

If you enable the `always_specify_types` lint, then that will produce a diagnostic which means you'll get the _fix_ version of this action. It would be in the Quick Fix section at the top, and it would show up anywhere on the line:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/b94e1bff-a05a-428a-b9b2-2d0d8b230c7e)

This distinction is perhaps not immediately obvious, but I think the list could get confusing if non-fix actions showed up the whole line in any location - it might not be obvious which part of the code they are going to affect. It's a little more relaxed for fixes because there's always visible squiggles that will make it clearer where the issue is.

**Comment by Merrit** [comment]
It is a shame that an assist can't be configured to show for the whole line, as I don't necessarily want to always enforce specifying types.

I will keep that linter rule in mind though, thank you! 💙

**Comment by DanTup** [comment]
> as I don't necessarily want to always enforce specifying types.

If you mostly want to enforce them, you could enable the lint and use the "Ignore" options shown in my screenshot above to mark where you don't want to (either by line, or for the whole file). I don't know if that helps though.
