### ISSUE TITLE
Add a command to "Add SDK to Path" and offer to invoke it automatically after downloading an SDK [Windows]

### ISSUE THREAD

**Issue by polina-c** [Dart-Code/Dart-Code#4604]
[go/setup-path-with-flutter-extension](https://goto.google.com/setup-path-with-flutter-extension)

- [x] Get URL to open instructions on Flutter website
- [x] Offer this flow after cloning SDK

**Comment by DanTup** [comment]
@polina-c is this doc public? Does it have a public URL? go / goto.google.com links don't work for non-Googlers (they require logging in with an @google account)

**Comment by polina-c** [comment]
Will we have telemetry for ratio of successful cases?

**Comment by DanTup** [comment]
I'd like to record the number of successful/unsuccessful attempts for both git clone and adding to path (for opted-in users).

**Comment by polina-c** [comment]
> @polina-c is this doc public? Does it have a public URL? go / goto.google.com links don't work for non-Googlers (they require logging in with an @google account)

It is not public. Yes, it works just for googlers. And it is ok for this case. 
Feel free to create public copy, if you feel it is right thing to do.

**Comment by DanTup** [comment]
I've merged in some changes for this:

- New "Flutter: Add SDK to Path" and "Dart: Add SDK to Path" commands in the command palette
- For Windows, these will automatically add to Path if able to run the PowerShell script
- For other platforms (or if the PS script fails), prompt user to add manually
- When cloning Flutter via Git, automatically ask if we should add to PATH (for Windows, otherwise just prompt to show instructions and skip the initial prompt)

I've included this in a pre-release version today (v3.67.20230626), though the "git clone" flow is still behind the "dart.experimentalFlutterGitClone" flag because I'd like some additional testing/feedback of that before I remove the flag.

**Comment by DanTup** [comment]
I'm making this issue Windows-specific (and closing because it's merged) and have opened https://github.com/Dart-Code/Dart-Code/issues/4612 to track macOS, since I suspect there may be more discussion (and complications). I don't want to hold up the current work (which should work for Windows, and can also open instructions for other platforms) if we don't get a Mac solution before the next release.

@polina-c btw, if we can't add automatically, these are the URLs I'm currently linking to for manual instructions - we can tweak these if required:

https://github.com/Dart-Code/Dart-Code/blob/3d3238d11289ee7b2e78b5d9167c34699d48ec51/src/shared/constants.ts#L90-L96

**Comment by wildsylvan** [comment]
@DanTup
the path is added to the windows path env var as a quoted string (with `"`) and unless i remove the quotes, it's not working.

see [this](https://serverfault.com/questions/349179/path-variable-and-quotation-marks-windows).

**Comment by DanTup** [comment]
@wildsylvan can you file a new issue for this, and include steps/screenshots showing how you're checking this?

We do add quotes here:

https://github.com/Dart-Code/Dart-Code/blob/9a21d26228bdc4ecee5c24b264103e5c2b8fd9aa/src/extension/commands/add_sdk_to_path.ts#L97

But the comment suggests that it didn't work without them so it might need some more testing. Please also include your version of Windows and PowerShell in the new issue. Thanks!

**Comment by wildsylvan** [comment]
@DanTup done 👍🏾
