### ISSUE TITLE
Support variables for `flutterAdditionalArgs`, `flutterRunAdditionalArgs` and `flutterTestAdditionalArgs`

### ISSUE THREAD

**Issue by jkoenig134** [Dart-Code/Dart-Code#4613]
**Is your feature request related to a problem? Please describe.**
I have a monorepo and some of the libraries and all of the apps are based on the same secrets file that I want to load using the `flutterAdditionalArgs`, `flutterRunAdditionalArgs` and `flutterTestAdditionalArgs` settings.json options.

VSCode is currently not supporting variables like `${workspaceFolder}` in the settings.json file (see https://github.com/microsoft/vscode/issues/2809 and https://github.com/microsoft/vscode/issues/3759).

**Describe the solution you'd like**
The best option would be to substitute `${workspaceFolder}` for these settings like the [go extension did it for the go path](https://github.com/microsoft/vscode-go/issues/343).

```json
{
  "dart.flutterTestAdditionalArgs": ["--dart-define-from-file=${workspaceFolder}/secrets.json"],
  "dart.flutterRunAdditionalArgs": ["--dart-define-from-file=${workspaceFolder}/secrets.json"]
}
```

**Describe alternatives you've considered**

I currently use two alternatives. The following is dangerous, and will only work for projects that are in `apps/app_name` or `packages/package_name`. "Run" buttons for example apps for packages like `packages/package_name/example` will crash (file not found).

```json
{
  "dart.flutterTestAdditionalArgs": ["--dart-define-from-file=../../secrets.json"],
  "dart.flutterRunAdditionalArgs": ["--dart-define-from-file=../../secrets.json"]
}
```

Additionally I am using a launch configuration that supports launching the current dart file with my secrets json:

```json
{
  "name": "Launch current dart file",
  "request": "launch",
  "type": "dart",
  "toolArgs": ["--dart-define-from-file=${workspaceFolder}/secrets.json"]
}
```

Edit: `--dart-define-from-file=../../secrets.json` in settings.json also breaks my launch configuration for `packages/package_name/example` because it is also used when launching with it.

**Comment by DanTup** [comment]
I'm not sure doing this here is a good solution. VS Code has a [large number of variables](https://code.visualstudio.com/docs/editor/variables-reference) and they can even be workspaceFolder-specific. VS Code provides no APIs to resolve variables so we would have to handle each of these individually.

VS Code already substitutes variables in `launch.json` so I think that should be used until VS Code supports this properly.

Can you clarify what problems you have when doing this inside `launch.json`? (I'm not sure if the edit at the bottom is related to that or not, since it says `"../../"` and not `$workspaceFolder`.

**Comment by jkoenig134** [comment]
Hi @DanTup! Thanks for the answer.

As said doing the `launch.json` approach is working out - but the `Run | Debug | Profile` buttons doesn't seem to use the `launch.json`.

My Edit was about combining the `launch.json` approach with the settings.json approach, as the launch configuration will use the settings defined in the `settings.json`.

Regarding the large number of variables, I'd suggest to only support the workspace related ones as the settings.json is workspace-related, maybe only the workspaceFolder. It should also be easily accessible using the [VSCode API](https://code.visualstudio.com/api/references/vscode-api#workspace).

**Comment by DanTup** [comment]
> the `launch.json` approach is working out - but the `Run | Debug | Profile` buttons doesn't seem to use the `launch.json`.

You can handle this by making the config a template - see https://dartcode.org/docs/launch-configuration/#:~:text=Setting%20%22templateFor%22%20to%20a%20relative%20path.

For example:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Dart",
			"request": "launch",
			"type": "dart",
			"templateFor": "" // empty string matches whole workspace
		}
	]
}
```

I'm not sure if this covers Profile, but if not (and assuming the setting works there), we could fix that.

> Regarding the large number of variables, I'd suggest to only support the workspace related ones as the `settings.json` is workspace-related, maybe only the `workspaceFolder`

It's certainly possible, though it's not a simple replacement - workspace can have multiple workspace folders so we'd have to select the correct one based on where the launch configuration comes from (or the entry point we infer, or the context if it's a launch we've triggered programmatically). It feels clunky to support just this one variable, and to do so because VS Code doesn't yet support this (and there's much less motivation for VS Code to implement it if extensions all put their own hacks in for it).

Could you first try using `templateFor` to see whether that does what you need?

**Comment by jkoenig134** [comment]
Oh, thank you so much! `templateFor` works like a charm! I totally missed that in the docs.

**Comment by DanTup** [comment]
Great! If you do hit any issues using this, please let me know.
