### ISSUE TITLE
Switch case auto-completion no longer works

### ISSUE THREAD

**Issue by ZacharyBohn** [Dart-Code/Dart-Code#4616]
## Bug

Auto-completion to fill out each case for a switch statement no longer works in VS Code.  The only option that appears is "Convert to switch expression".  After selecting that option, it just adds a return statement.

Initial code before auto complete:
```dart
main() {
  final x = ExampleEnum.foo;
  switch (x) // attempt auto complete on this line
}

enum ExampleEnum {
  foo,
  bar;
}
```

Code after auto complete:
```dart
main() {
  final x = ExampleEnum.foo;
  return switch (x)
;}

enum ExampleEnum {
  foo,
  bar;
}
```

Expected output:
```dart
main() {
  final x = ExampleEnum.foo;
  switch (x) {
    case ExampleEnum.foo:
      break;
    case ExampleEnum.bar:
      break;
  }
}

enum ExampleEnum {
  foo,
  bar;
}
```

**Please complete the following information:**
 - Operating System and version: Tested on MacOS 13 & Windows 11
 - VS Code version: May 2023 (version 1.79)
 - Dart extension version: v3.66.0
 - Dart/Flutter SDK version: Flutter 3.10.5; Dart 3.0.5

**Comment by DanTup** [comment]
This is unfortunately a known issue with the initial release of Dart 3. Switch statements are parsed differently since patterns support was added, and all of the quick fixes do not work yet.

Some improvements have been made since Dart 3 (so will show up in a future SDK release), and there are some additional open issues here:

- https://github.com/dart-lang/sdk/issues/52180
- https://github.com/dart-lang/sdk/issues/51985

The quick fixes come from the analysis server that ships in the SDK, so once fixed there, it won't require any changes to the VS Code extension.
