### ISSUE TITLE
Hovering over a for loop variable does not show its type

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4627]
**Describe the bug**

https://github.com/Dart-Code/Dart-Code/assets/21116742/2747b83d-63e9-4fa6-ac6e-539cbc4783ef

**Please complete the following information:**
 - Operating System and version: macOS
 - VS Code version: 1.79.2
 - Dart extension version: 3.66.0
 - Dart/Flutter SDK version: Dart SDK version: 3.1.0-163.1.beta (beta)

**Comment by incendial** [comment]
Feels like it's related to https://github.com/Dart-Code/Dart-Code/issues/4626

**Comment by DanTup** [comment]
I suspect same cause, but different code. Opened a fix for this one at https://dart-review.googlesource.com/c/sdk/+/312441

**Comment by incendial** [comment]
Ah, these `DeclaredIdentifiers`... 🥲
Recently discovered that several rules in DCM were not covering them at all. Honestly, I'm really surprised it's a separate type of node (and not a variable declaration or it's variance).

**Comment by DanTup** [comment]
I don't know all the details, but there seem to be some differences between the classes (for ex. `VariableDeclaration` has things like an initializer and is documented as always being a child of `VariableDeclarationList`, so it doesn't have `keyword` because that's on the list).

I don't know if something changed here recently though, I feel like I've seen a few issues related to this recently (such as the one you linked above - which had a similar fix) - although for loops are definitely not new!

**Comment by DanTup** [comment]
This is fixed by https://github.com/dart-lang/sdk/commit/28ea45c05c78e045e92743221a2171be11425654. It's in the server so will show up in a future SDK release.
