### ISSUE TITLE
[iOS] Wirelessly Debug stuck at Installing and launching

### ISSUE THREAD

**Issue by CodeEagle** [Dart-Code/Dart-Code#4638]
as mention above,
It  works fine when use  command`flutter run --device-timeout 5`

**Comment by DanTup** [comment]
Can you provide some more detailed steps to help me reproduce this? How are you setting this up, and exactly what do you see when it gets stuck? Thanks!

**Comment by CodeEagle** [comment]
using vscode run, iphone show white screen and keep waiting
<img width="1222" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/2311352/70bb69cd-329c-43cd-a231-49414b82ed4e">

using `flutter run --device-timeout`, connect and show ui

<img width="796" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/2311352/57934f8a-f60a-42ab-bded-e5bcd43bb8f7">


flutter: 3.10.4
vscode extensions:
dart: v3.68.1
flutter: v3.68.0


[stuck_demo.zip](https://github.com/Dart-Code/Dart-Code/files/12029111/stuck_demo.zip)

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this here on my iPad, the app launches normally.

Could you:

1. Create a new project with the **Flutter: New Project** command and check whether it happens with that (that's the project I'm testing with)
2. Try capturing debug logs while testing with the new project above:
  - Open the new counter app project
  - Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
  - Press `F5` to try running the app
  - Wait until the white screen appears on the device then wait for 30 seconds (just to ensure the log doesn't truncate anything that might still be happening)
  - Click **Cancel** on the logging notification to stop logging and open the log
  - Remove anything sensitive from the log
  - Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!

**Comment by CodeEagle** [comment]
demo code is uploaded at first comment 
[code](https://github.com/Dart-Code/Dart-Code/files/12029111/stuck_demo.zip)

and here's the log 
[Dart-Code-Log-2023-06-04 21-07-24.txt](https://github.com/Dart-Code/Dart-Code/files/12039675/Dart-Code-Log-2023-06-04.21-07-24.txt)

**Comment by CodeEagle** [comment]
run via terminal or  vscode 
connect to vm Service is failed at all time. no matter how many times it gonna retry
but run with command will successfully show the ui view

**Comment by DanTup** [comment]
Do you see the app if you use `Run Without Debugging` / `Ctrl+F5`?

If so, I don't think there's anything wrong with the VS Code extension. The reason you see a white screen when using Debug, is that the app starts paused (to avoid race conditions when setting up breakpoints), but because the VM Service never connects, VS Code can never unpause the app.

So if running from terminal shows the same errors connecting to the VM Service, that's the issue that needs resolving. Once that is fixed, Debug from VS Code will also work.

You might need to raise an issue at https://github.com/flutter/flutter/ to get help debugging the VM Service connectivity issue. I'm not familiar with things that might cause the installation to work, but connection to the VM Service to fail.

**Comment by CodeEagle** [comment]
I see， thanks
