### ISSUE TITLE
Could TODOs be a filter category?

### ISSUE THREAD

**Issue by matanlurey** [Dart-Code/Dart-Code#4648]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2023-07-17 at 5 18 04 PM](https://github.com/Dart-Code/Dart-Code/assets/168174/4ecdaecf-1db0-46ee-80fd-1667b7086566)

Typically TODOs are longer-lasting than other forms of diagnostics (I don't typically check-in code with info/warnings/errors). It would be nice to be able to hide TODOs but show the others.

**Describe the solution you'd like**
Add "Show TODOs" and let me uncheck it.

**Describe alternatives you've considered**
I can use `!TODO` in the filter bar manually, but it's slightly more annoying to do so I often don't.

**Comment by DanTup** [comment]
We can't add anything to that filter list, it just shows the severities defined by VS Code:

https://github.com/microsoft/vscode/blob/41ef82075cd61e60498b9724425034a57cd2d46a/src/vscode-dts/vscode.d.ts#L6068

(Hints don't show in the Problems list, they're a bit of a hack for triggering code actions/refactors without squiggles).

But, we do have an existing setting that lets you control whether TODOs show up here:

<img width="1008" alt="Screenshot 2023-07-18 at 13 17 22" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/11e979ca-dc63-4872-9083-d99be53104ea">

You can set it to `true` (default), `false`, or an array of values from `"TODO", "FIXME", "HACK", "UNDONE"` to include them selectively.

Does that do what you need?

(I do wonder if `true` is the right default.. however changing it now feels complicated since 99% of people are using the default)

**Comment by DanTup** [comment]
@matanlurey did the above solve your problem?
