### ISSUE TITLE
Create doc page that describes all possible ways to set path to flutter.

### ISSUE THREAD

**Issue by polina-c** [Dart-Code/Dart-Code#4665]
Now, when there are so many ways to set SDK in VSCode, including hidden way to build project and thus set flutter path to what was used for the build, a page that describes all of them and their priorities for VSCode, would really help.

**Comment by incendial** [comment]
@DanTup you don't have a first-class support for fvm, why?

**Comment by DanTup** [comment]
There's already support for switching of SDKs here and it works with both Dart and Flutter (and doesn't require installing additional tools). It's been a while since I looked at it, but I believe fvm requires (or required) running everything through it (`fvm flutter run`) and since we spawn lots of the SDK tools for different purposes, having to plumb all that through didn't seem worth it (I'm not really sure what benefit there would be over what we already have).

**Comment by incendial** [comment]
> It's been a while since I looked at it, but I believe fvm requires (or required) running everything through it (fvm flutter run)

Interesting, was not aware of that.

> (We also need to locate files inside the SDK, so we need to know the path, not just that we can run fvm to get the right version)

This one is doable, I supported both fvm and fvm default in DCM.

**Comment by DanTup** [comment]
Looks like FVM already has docs for working with VS Code's built-in switcher at  https://fvm.app/docs/getting_started/configuration/#vs-code (for both detecting the current SDK, and using the switcher to switch between FVM versions). I don't use it so I don't know if there are things that don't work this way though.

I'm open to improving support for other version managers if there's demand, but I'd rather do that in ways that are open to all version managers and don't require specific coding for individual apps because it's not very scalable to build them all in (for ex. https://puro.dev/ is another popular one).

**Comment by DanTup** [comment]
I added a new page here:

https://dartcode.org/docs/sdk-locating/
