### ISSUE TITLE
VS Code Temporary file garbage by flutter_tool.xxx on Windows machine

### ISSUE THREAD

**Issue by btechtutor** [Dart-Code/Dart-Code#4674]
**Describe the bug**
VS Code Flutter-Extension creates garbage file which quickly rises upto 50GB in size because of not deleting flutter_tool.xxx file in AppData/../temp folder on exiting the debug or run mode. Runnig/debugging by using the command prompt the garbage file gets deleted after quitting on cmd by pressing the `q` (quit) argument. VS Code Flutter-Extension does not conduct the correct signal to the Flutter SDK.

**To Reproduce**
Windows users goto Appdata->Local->Temp->>> flutter_tools.xxx

**Expected behavior**
After Starting Run/Debug mode on VSCode if clicked on Stop button flutter_tools.xxx file should be deleted in AppData/..temp file as alike pressing `q` on cmd.

**Please complete the following information:**
 - Operating System and version:
 - VS Code version:1.47.0
 - Dart extension version:2.19.2
 - Dart/Flutter SDK version:3.7.5
 - Target device (if the issue relates to Flutter debugging): Chrome

**Comment by DanTup** [comment]
@btechtutor can you reliably reproduce this? When I click the Stop button on the VS Code debug toolbar, the temporary `flutter_tool*` folder seems to be deleted.

Do you know if there are any specific steps that lead to the folder being left behind? One thing I can think of is if you click the stop button _twice_ - since a second click with forcefully terminate the debugger and not allow it to clean up. VS Code's UI doesn't make this very clear (sometimes it just looks like the first click didn't work if the app doesn't quite fast enough).
