### ISSUE TITLE
refactor: decouple Flutter related logic from Dart extension

### ISSUE THREAD

**Issue by alestiago** [Dart-Code/Dart-Code#4689]
**Is your feature request related to a problem? Please describe.**
I would like the Flutter related code to be decoupled from the Dart code extension. Users can be using Dart without using Flutter. I would like Dart users of the extension to not have unnecessary Flutter related logic bundled in the Dart extension.

**Describe the solution you'd like**
- Decouple Flutter related logic outside the Dart extension (probably sensible to move it to the [Flutter](https://github.com/Dart-Code/Flutter) extension)

**Comment by DanTup** [comment]
There's an existing issue for this at https://github.com/Dart-Code/Dart-Code/issues/1404.

I've had this goal for a long time, but it's always been fairly low priority (and the migration of commands is tricky, because if people don't update Dart+Flutter extensions together, they may end up with duplicate or missing commands).

Out of interest - why are you interested in this? There are a few reasons I'd like to do it but I don't know if they align with yours:

- No Flutter commands should appear in the palette if you didn't install the Flutter extension
- The Dart extension shouldn't be large because it contains Flutter icon previews if they could go in Flutter (although, I hope we can change how this works in future so neither extension needs several MB of icon previews)
- No Flutter settings should show in the settings UI
- No Flutter tasks should show up in the tasks list 

(closing this as a dupe - we can follow up on https://github.com/Dart-Code/Dart-Code/issues/1404)
