### ISSUE TITLE
"Convert to expression body" can lose comment

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4715]
**Describe the bug**

"Convert to expression body" can lose an associated comment.

**To Reproduce**

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/c6842567-b2aa-4628-81ba-d121d6b032ae)

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/2c8e5634-8262-4cce-9318-faae6b22136b)

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/000d156b-589e-4d76-a897-74307134a8ee)

**Expected behavior**

Comments should never be lost when code is being transformed.

Dart-Code should make a best-faith effort to preserve comments, even if it puts them in a non-optimal place after a transformation.

**Please complete the following information:**
 - Operating System and version: Linux
 - VS Code version: Latest released version
 - Dart extension version: Latest released version
 - Dart/Flutter SDK version: Latest released version
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
> I never know where to file Dart bugs :-D

Yeah, it's not always obvious. _Generally_ things that involve parsing/understanding Dart source code itself live in the language server. If issues belong in the SDK but are fairly small and I can fix them quickly I'll often just leave them here, but for things more involved it's better to have them over there.

It's easy to move/re-raise issues though, I'd rather they were raised in the wrong repo than not raised (because it's not clear where to raise them) though :-)
