### ISSUE TITLE
Saving `pubspec.yaml` in a flutter project runs `pub get`

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#472]
I know in the past this wasn't the case, and ran `flutter packages get` instead.

My project is definitely detected as a Flutter project, and my Pubspec gives me the "Get Flutter Packages" button, which works correctly. Something is probably going screwy with the on-save logic.

I'll look into it myself this evening if you don't beat me to it.

**Comment by DanTup** [comment]
Ugh!

This was introduced in 4e62139eb81ac19d5a0fd0e70e3f15faea75f734. I thought the code inside the pub get commands that bounced to flutter was only there for legacy/keybinding reasons and no longer needed. I forgot about the automatic running of it!

To keep the commands cleaner, probably it should be fixed here:

https://github.com/Dart-Code/Dart-Code/blob/ec9b298dc2fc199655cbef1ad0475d4f567fa21a/src/commands/sdk.ts#L48

It should probably check `util.sdks.projectType` to use `pub` for Dart and `flutter` for Flutter + Fuchsia (doesn't really matter which way around the condition is, if we ever get an additional project type there will be a lot of code to review to check it falls into the right category for all conditionals).

Haven't had much time on this lately (got a terrible cold) so if you want to fix, go for it (otherwise I'll try next week) :-)
