### ISSUE TITLE
Should core refactors have default keybinds?

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#4738]
Related to: https://github.com/Dart-Code/Dart-Code/issues/4490

I believe that assists like "wrap with widget / remove widget" are very commonly used. While developpers can opt-in to define a keybinding on their own, many probably don't even think about it.

Would it make sense to have a shortcut for those core refactors?

**Comment by DanTup** [comment]
I've generally avoided adding keybindings because it's difficult to find reasonable keybindings (there are already so many and you can't tell which may be bound by other extensions), and I feel like they're the sort of thing people would want to choose themselves for them to be likely to remember/use them.

I suspect the people that "don't even think about it" would probably also not discover any default bindings we added, so they might not provide much value.

I think it might be better to just make sure people know how to quickly add keybindings (and if there are things that make this complicated - for example needing to know the IDs is a barrier, we should see if we can improve that).

**Comment by DanTup** [comment]
> Assists with keybinds could show the keybind.

Unfortunately we don't have any control of this, VS Code renders the lightbulb menu, we just provide the list of items.


> Folks are also more likely to use an existing keybind than to define their own

I'm not sure if I totally agree with this. Providing a default is certainly convenient, but if it's a bad binding, I think people won't use it and they'll bind their own (or just use the cursor keys or filter in the quick-fix menu). We already have a few keybindings and picking them was difficult, because all of the good ones are taken. Users can bind over things they don't use, but we can't so we have to scrape the barrel for what's left (and the differences between mac/non-mac mean we often can't have the same on all platforms).

I really think the [upcoming filtering of the lightbulb menu](https://github.com/microsoft/vscode/issues/157719#issuecomment-1671986314) will work great for the majority of users (and the others probably already know how to add bindings).

That said, this is only my opinion and it's frequently wrong 😄 We can collect some proposals on what items we would keybind, what those keybindings would be (for mac + non-mac), and opinions to see if people would use them if they were provided (but don't know how or wouldn't bother to bind them themselves).

There's a list of fixes at https://dartcode.org/docs/refactorings-and-code-fixes/ if you want to pick some out and suggest some bindings. Please check they're not already in use, I definitely don't want to override any built-in VS Code bindings.

**Comment by rrousselGit** [comment]
TIL about the upcoming filtering menu. I guess we can temporarily close this while evaluating if that solves the issue.

But for what it's worth, I was thinking about giving keybings exclusively to "wrap with widget" and "remove widget".
