### ISSUE TITLE
"UnimplementedError: Global evaluation not currently supported"

### ISSUE THREAD

**Issue by antoniafb** [Dart-Code/Dart-Code#4751]
UnimplementedError: Global evaluation not currently supported
#0      DartDebugAdapter.evaluateRequest (package:dds/src/dap/adapters/dart.dart:949:7)
#1      BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:20)
#2      BaseDebugAdapter.handleIncomingRequest (package:dds/src/dap/base_debug_adapter.dart:447:7)
#3      BaseDebugAdapter._handleIncomingMessage (package:dds/src/dap/base_debug_adapter.dart:295:7)
#4      ByteStreamServerChannel._readMessage (package:dds/src/dap/protocol_stream.dart:82:18)
#5      ByteStreamServerChannel.listen.<anonymous closure> (package:dds/src/dap/protocol_stream.dart:53:24)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)

**Comment by DanTup** [comment]
Can you provide some more detail about when you get this?

I suspect it is resolved by https://github.com/Dart-Code/Dart-Code/issues/4636 / https://github.com/dart-lang/sdk/issues/52574, but those changes will ship in a future SDK release as they missed the previous release.

**Comment by s-a-y-o-n** [comment]
I got this error while giving an input

**Comment by DanTup** [comment]
@s-a-y-o-n are you trying to use something like `stdin.readLine()`? If so, you need to have the script run inside a terminal, not the Debug Console. The Debug Console is a REPL for evaluating expressions.

To run in the terminal, you can use the [`dart.cliConsole` setting](https://dartcode.org/docs/settings/#dartcliconsole) or [`"console": "terminal",` in a launch configuration](https://dartcode.org/docs/running-in-terminal/).

**Comment by asc0910** [comment]
I got the same issue. Hope it can be fixed soon

**Comment by DanTup** [comment]
There are two different issues that often get confused here and it's not obvious which applies to some of the comments above.

If you're running a Flutter app and trying to evaluate _expressions_ in the Debug Console when you are not at a breakpoint and seeing this message, that issue is fixed via https://github.com/dart-lang/sdk/issues/52574 and will be available in the next Dart/Flutter SDK releases.

If you are writing a command line application and using something like `stdin.readLine()` to read user input, then you need to run your app in a terminal (see my last comment above), not the Debug Console. The Debug Console always functions as a REPL for evaluating expressions and never passes user input to the program.

I'm going to close this because the OP never responded and I believe the issues are covered by the above.

If you're seeing this message and don't believe it falls into one of the descriptions above, please file a new issue and include details about exactly what you're doing to trigger the error (code samples, screenshots and/or a video are always super helpful).

Thanks!
