### ISSUE TITLE
"Source not available" on assertion failures in Flutter when debugging SDK code

### ISSUE THREAD

**Issue by pattobrien** [Dart-Code/Dart-Code#4759]
## Undebuggable Stack Frame Popup Bug

see reproducible example here: https://github.com/pattobrien/undebuggable_stack_frame#undebuggable-stack-frame-popup-bug

### Steps to Reproduce

1. Create a Dart package with Flutter SDK as a dependency.
2. Set Dart Code debug option to 'debug my code + packages + SDK'.
3. Run a test that fails an assertion.

### Expected Behavior

The assertion stack frame should appear in the source view.

### Actual Behavior

The assertion appears as a file in a new VSCode tab titled `errors_patch.dart` with the following content:

```
Could not load source 'dart:core-patch/errors_patch.dart': <source not available>.
```

### Screenshots
![Screenshot 2023-09-25 at 4 32 45 PM](https://github.com/Dart-Code/Dart-Code/assets/12474318/309d6c7b-4e32-421f-a2aa-ddc06b1dbd3b)

Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (3 months ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

as discussed with @DanTup

**Comment by DanTup** [comment]
Turns out this is Flutter specific and happens because of https://github.com/flutter/flutter/issues/128880 (it's Flutter-specific). In Dart, you'd see the source of the assert functions:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/921c964b-4b30-4b8e-824e-d0fc4c7fdd68)

I'm working on a fix so we'll just not try to present any source here (so you'll instead just focus on the user code frame) but it's inconsistent with Dart so will be better if we can get the Flutter issue fixed.

**Comment by DanTup** [comment]
This is mostly fixed by https://github.com/dart-lang/sdk/commit/c5f60241a81bf713a9f9612b17d409cf2f6cc471. The behaviour between Dart and Flutter will be slightly different until https://github.com/flutter/flutter/issues/128880 is solved, but you won't get these errors about no source.

The change is in DDS which needs to roll into Flutter, and then it'll ship in a future release of the Flutter SDK.

**Comment by DanTup** [comment]
A proper fix for this landed via https://github.com/flutter/flutter/issues/128880, so now the behaviour should be the same :-)
