### ISSUE TITLE
Debug Console location metadata doesn't appear when not running in debug mode

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4768]
**Describe the bug**

Issue 1: The URI on the right hand side of the Debug Console doesn't work (screenshot 1)
Issue 2: The URIs printed in the Debug Console and Test Results work but the line number isn't a part of the URI -- i.e. cannot jump to the line using the URIs (screen shot 1 & 2)

Please see the screenshots below:

1- Screenshot 1
<p align="center"><img width="654" alt="Screen Shot 2023-10-03 at 3 35 41 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/a3d99953-8689-4e1d-b125-a7c101de87c5"></p>
2- Screenshot 2
<p align="center"><img width="659" alt="Screen Shot 2023-10-03 at 3 36 03 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/aa95bbf7-78f0-4128-bdc3-2c5d58e348ce"></p>

**To Reproduce**
1. create `test/some_test.dart`
2. add the following snippet:
```dart
import 'package:test/test.dart';
void main() {

    void failure() => throw UnimplementedError();
    test('fail', () {
      failure();
    });
}
```

**Please complete the following information:**

 - Operating System and version: 12.6 (21G115) 
 - VS Code version:  1.82.2
 - Dart extension version: v3.74.0
 - Dart/Flutter SDK version: Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "macos_x64"

> sorry if this is already reported or should be filed elsewhere -- please let me know

**Comment by DanTup** [comment]
The links on the right not working looks like the issue in https://github.com/Dart-Code/Dart-Code/issues/4573 which should be fixed in the latest builds/betas (works for me on a 3.2 build).

I think the second one is because VS Code doesn't handle links very well in Test Results (maybe slightly related to https://github.com/microsoft/vscode/issues/150702, as the Peek Error window and Test Results both use terminals). The reason you can click on it when you hold Ctrl, is that that basically lets you click anything (for ex. `UnimplementedError` gets underlined when you hold Ctrl and hover it) and will try to open it. I think once they implement link providers there, we can contribute scanning for paths/lines in there.

**Comment by osaxma** [comment]
> The links on the right not working looks like the issue in #4573 which should be fixed in the latest builds/betas (works for me on a 3.2 build).

I am mainly on stable now... so I will just wait until it gets there... 

Feel free to close the issue unless you'd like to track it 

Cheers

**Comment by DanTup** [comment]
Will close as I don't think there's anything to do, but do shout if you see issues after you get the fix for #4573.

If https://github.com/microsoft/vscode/issues/157500 gets implemented in VS Code, I'll add support for the other part - though it's probably not worth tracking in an open issue until that happens since sometimes things don't 🙃

**Comment by osaxma** [comment]
Hi @DanTup 

I just tried at a recent main ([`96ae2c3`](https://github.com/dart-lang/sdk/tree/96ae2c3cadea68bf904e6da83d70453786025d2a)) in my local build and I noticed that it works for `Debug`

<p align="center"><img width="645" alt="Screen Shot 2023-10-11 at 2 05 48 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/ee113fa8-2498-47ef-ae1b-c5345a3afd93"></p>

... But the links are not available anymore when I do `Run without Debugging` which seemes like a regression .. 

<p align="center"><img width="645" alt="Screen Shot 2023-10-11 at 2 06 03 PM" src="https://github.com/Dart-Code/Dart-Code/assets/46427323/a4a6a468-1ace-4247-a9ac-d9437ee2324d"></p>

**Comment by DanTup** [comment]
Hmm, on the surface that doesn't feel right. I would expect we might fail to map `package:` URIs when not running under the debugger (because we use the debugger to map them), but it doesn't _seem_ like these would be packages.

I presume you're testing with a simple Dart test, no Flutter involved?

**Comment by osaxma** [comment]
> I presume you're testing with a simple Dart test, no Flutter involved?

Yeah, just Dart. 

The screenshot is from a scratch project where the test file is exactly as the sample code in the original issue.

**Comment by DanTup** [comment]
Thanks - I can repro and have found the issue. Working on a fix :-)

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/b706bfcd1f26b1321f1fe7967665ab27c88ac5e7. The fix ships in the SDK debug adapter, so it'll show up in a future SDK release.
