### ISSUE TITLE
add a keybinding for organize imports

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#478]
I use the `organize imports` analyzer command frequently enough, I think it could use it's own keybinding:

<img width="763" alt="screen shot 2017-12-21 at 1 02 33 am" src="https://user-images.githubusercontent.com/1269969/34248516-4477728a-e5eb-11e7-8e8a-af36a6eff138.png">

When developing with IntelliJ, I have the two keybindings - organize imports and format - on muscle memory :)

**Comment by DanTup** [comment]
We did have this (#254) but the default keybinding caused warnings in Code that we shouldn't use it. I look at some other extensions to see if they have similar functionality we could copy the binding for (to try and be consistent with other Code plugins, which I think makes more sense than other IDEs) but didn't find any.

That said, I believe you should be able to bind this yourself in Code in the Keybindings editor, since it's just a command, see:

https://code.visualstudio.com/docs/getstarted/keybindings

Let me know whether this works and you think it's reasonable to leave this one to the user.

**Comment by devoncarew** [comment]
This may be one of the top few that we would want keybindings for. Saying that, I know that keybindings can be a bit of a minefield in terms of finding a non-conflicting one, esp. across platforms, so if there's no clear best keybinding for this, we should likely just close.

**Comment by DanTup** [comment]
I think my plan was to wait until C# had it (an MS extension) and copy theirs if they added a default! It's not done yet though (https://github.com/OmniSharp/omnisharp-vscode/issues/788).

I do also have #96 open where I wanted to tie it into the format (so if you format doc, or format-on-save it'd happen automatically), but that was tricky. If we can make that work; do you think that would be a better fix?

**Comment by DanTup** [comment]
We have something from MS to copy now 😆

https://twitter.com/mattbierner/status/976548673457856512
