### ISSUE TITLE
Dart run menu icons broken

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4801]
Hot reload and performance page icons are broken: 
![Screenshot 2023-10-17 at 11 00 46 AM](https://github.com/Dart-Code/Dart-Code/assets/43759233/f16a2640-24b2-47de-a8eb-253f5692e9c0)

```text
Dart Code extension: 3.75.20231009
Flutter extension: 3.74.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.83.0

Workspace type: Dart, Flutter (LSP)

Dart (3.3.0-14.0.dev): /Users/kenzieschmoll/develop/flutter/bin/cache/dart-sdk
Flutter (3.16.0-10.0.pre): /Users/kenzieschmoll/develop/flutter (iPhone 14 Pro Max (ios/ios))

```

**Comment by DanTup** [comment]
This was a VS Code bug (see https://github.com/Dart-Code/Dart-Code/issues/4782 / https://github.com/microsoft/vscode/issues/194710). They shipped a patch release with the fix for it though (1.83.1) so if you update/restart VS Code it should be solved.

Let me know if you still see it after updating!
