### ISSUE TITLE
External Library Viewer Tab (Similar to Intellij/Android Studio)

### ISSUE THREAD

**Issue by buruc002** [Dart-Code/Dart-Code#4804]
**Describe the solution you'd like**
It would be great if visual-studio code supported an external libraries section similar to what we have available in Android Studio.
It helps developers quickly look into the source of what was pulled via the pubspec.yaml without having to dig into the pub cache or have to search for the specific symbol by name.

Example of Android Studio's External Library Panel
![Screenshot 2023-10-19 at 12 56 07 PM](https://github.com/Dart-Code/Dart-Code/assets/123694496/6a13124f-84b1-4844-8799-396c6a825281)

**Comment by DanTup** [comment]
@buruc002 there is a Dependencies section in the editor sidebar:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/f570193d-5b5e-40f3-aada-b9b81be0ec82)

I don't know how it compares to IntelliJ's (I haven't used IntelliJ much), but I'd be interested to know if it provides what you're after (and if not, what you'd like to see added).

**Comment by buruc002** [comment]
@DanTup thanks for the quick reply on this. 
To be honest, I didn't realize the dependencies section there. I did a comparison of Android Studio vs Visual Studio, and I found this feature to be exactly what I was looking for, so I will close this issue. 

Thanks again.

**Comment by DanTup** [comment]
Great, thanks for confirming. If you do find anything missing, please let me know!

Unfortunately it does seem quite common to not know about this section. I don't currently have many good ideas for improving the discoverability. Some possibilities:

- perhaps have it start expanded instead of collapsed, although we don't have any control over what portion of the sidebar it would take up (because we don't own this whole sidebar section)
- consider a Dart sidebar section (instead of putting it into the Explorer section)

(@jacob314 @jwren FYI)
