### ISSUE TITLE
Newly created breakpoint gets created with a condition when on pause 

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4816]
**Describe the bug**
Maybe there can be a better title 😅.

So, when the debugger pauses on a conditional breakpoint, any new breakpoint gets created with the "conditional breakpoint" icon and an ability to change its condition. But when the debugging session ends, the same breakpoint looks as regular breakpoint.

https://github.com/Dart-Code/Dart-Code/assets/21116742/f225d5f5-c212-4ddb-a896-ed59bbc87473

Before:
<img width="663" alt="Screenshot 2023-10-27 at 11 53 24" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/e3c620f7-1085-41cd-a4ff-b9d1c25dc955">

After:
<img width="624" alt="Screenshot 2023-10-27 at 11 53 15" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/a234bd9f-457a-4e2b-be8e-5f961916f1e4">

**Please complete the following information:**

Dart Code extension: 3.74.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.83.1

Workspace type: Dart (LSP)

Dart (3.2.0-210.1.beta): /Users/dimannich/Desktop/flutter/bin/cache/dart-sdk
Flutter (3.16.0-0.1.pre): /Users/dimannich/Desktop/flutter

**Comment by incendial** [comment]
Plus, if I try to remove the newly created one, the existing breakpoint gets removed instead.

**Comment by DanTup** [comment]
Can you provide detailed steps to reproduce and a log (captured with **Capture Debugging Logs**)? So far I haven't been able to reproduce this:

https://github.com/Dart-Code/Dart-Code/assets/1078012/1259c579-719e-41de-a045-3ce07b235b0c

I can't think of a reason this would occur (since we don't really track any global state of conditions) so I wonder if it could be a VS Code issue. I can't find any other reports in their tracker though.
