### ISSUE TITLE
plugin crashed  day and day  om my windows platform

### ISSUE THREAD

**Issue by xiyionxiong** [Dart-Code/Dart-Code#4829]
**Describe the bug**
plugin crashed  and logs here 

```
[17:48:37] [Analyzer] [Info] <== {"id":"99","result":{"assists":[{"message":"Remove type annotation","edits":[{"file":"D:\\Projects\\Flutter\\PCMaster\\lib\\main_mobile.dart","fileStamp":0,"edits":[{"offset":171,"length":13,"replacement":""}]}],"linkedEditGroups":[],"id":"dart.assist.remove.typeAnnotation"}]}}
[17:48:42] [Analyzer] [Error] Unhandled exception:
Invalid argument (string): Contains invalid characters.: "ClientException with SocketException: 信号灯超时时间已到\r\n (OS Error: 信号灯超时时间已到\r\n, errno = 121), address = www.google-analytics.com, port = 51756, uri=https://www.google-analytics.com/mp/collect?measurement_id=G-04BXPVBCWJ&api_secret=Ka1jc8tZSzWc_GXMWHfPHA"
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      new Response (package:http/…
[17:48:42] [Analyzer] [Info] Process C:\Users\camch\.flutter\bin\cache\dart-sdk\bin\dart.exe terminated! 255, null
```

 

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/14977994/f41f90a5-b6e6-4774-b372-fbfe9a1bf4d8)
![image](https://github.com/Dart-Code/Dart-Code/assets/14977994/e0b5012e-696d-4e88-a487-d635076d0a20)

**Comment by DanTup** [comment]
@xiyionxiong thanks for the report! It appears this issue may have already been fixed by https://github.com/dart-lang/tools/issues/131 and the fix will ship in a future Flutter SDK release.

In the meantime, I think disabling analytics (by running `dart --disable-analytics`) would avoid the problem if it's preventing you from working.

@eliasyishak @bwilkerson I wonder if analytics should be run in a `Zone` or something so that any unhandled exceptions with analytics (I suspect there are many different ways people might block these that might result in exceptions we haven't considered) would not bring down the process like this (it might mean less reports about the issues, but perhaps that's better than appearing to be completely broken)?

**Comment by eliasyishak** [comment]
I'm also interested to see what version for flutter and dart @xiyionxiong is running. I thought that was already released in a stable version.

But good point @DanTup, I'll look into handling errors

**Comment by xiyionxiong** [comment]
@eliasyishak  the version for flutter and dart 
```
[✓] Flutter (Channel stable, 3.13.9, on Microsoft Windows [版本 10.0.22631.2506], locale zh-CN)
    • Flutter version 3.13.9 on channel stable at C:\Users\camch\.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

```
