### ISSUE TITLE
Launching Flutter app from VSCode fails, but succeeds from terminal

### ISSUE THREAD

**Issue by solita-esatikka** [Dart-Code/Dart-Code#4830]
**Describe the bug**
When launching (both running and debugging fail) the app from VSCode, after a successful gradle build I get error "Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\esa.tikka\prj\redacted-app-name\build, but the tool couldn't find it."

However, I do get freshly built .apk under `C:\Users\esa.tikka\prj\redacted-app-name\build\app\outputs`

I suspect this might have something to do with recently upgraded dependencies (including Flutter), and/or the fact that I'm using FVM, and there's something in the project config that is messing things up. I'm not the main mobile developer in the project and the last time I tried to do this was months ago.

Originally I had `dart.flutterSdkPath` set in `.vscode\settings.json` but I've deleted that (and reopened the project).
I don't know if it makes a difference here, but I do have `flutter.sdk=C:\\Users\\esa.tikka\\fvm\\versions\\3.13.9` in `android\local.properties`.

**To Reproduce**
1. Open the project in VSCode
2. Start Android emulator
3. Hit F5 in VSCode

Debug console results:
```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\esa.tikka\prj\redacted-app-name\build, but the tool couldn't find it.

Exited (1).
```

Unfortunately I cannot reproduce this with a new Flutter project, only with our project's app.

**Expected behavior**
```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
```
...and the app launches in the emulator.

**Logs**
[flutter_diagnostic_info.txt](https://github.com/Dart-Code/Dart-Code/files/13296510/flutter_diagnostic_info.txt)
[dart_debugging_log.txt](https://github.com/Dart-Code/Dart-Code/files/13296511/dart_debugging_log.txt)

**Comment by DanTup** [comment]
Just to clarify, is the issue here only present _for a specific project_ **and** _when running from VS Code_? Eg.:

- this specific project runs correctly from the terminal with `flutter run`
- this specific project fails to run from VS Code
- all other projects work **both** from VS Code and from the terminal

If so, could you attach the following:

1. The full output of running the **Dart: Collect Diagnostic Info** command _with only the problematic project open_
2. The full output of running the **Dart: Collect Diagnostic Info** command _with only a working project open_
3. The full output of running `flutter doctor -v` in a terminal where launching the problematic project works

It's possible the log you already attached is either 1 or 2, but it's not clear to me which.

Thanks!

**Comment by solita-esatikka** [comment]
The issue only affects a specific project **and** when running from VSCode.
I've now collected diag info with just one project open (probably had both open earlier)...

**However**...
While doing this I realised that even though running/debugging from the editor window or with hotkeys did fail, going to "Run and Debug" view, selecting a proper launch config and clicking "Start Debugging" did actually work. From which I start to wonder if it all was just due to having the auto-generated (??? it's not in launch.json anyway) "Flutter (pixel4)" option selected there instead of what was supposed to be selected - because now I am able to successfully start debugging the app with the exactly same ways it earlier failed. I feel somewhat stupid now 😳 but as I said I'm not really a mobile dev and I do this rather rarely.

Anyway, thanks for being there 😃

**Comment by solita-esatikka** [comment]
As you wish...
The cause of the failure seems to have been that I had a bogus launch configuration selected here (the highlighted option):
![image](https://github.com/Dart-Code/Dart-Code/assets/88656993/a5cee40d-e299-45bb-97ba-0448f92b07d4)
I didn't figure out how to find out what actually went wrong when launching with that config, but I think I figured out where the config originated: 
1. Expand the launch configuration dropdown
2. Select Dart & Flutter...
3. Select "Flutter" (or possibly any of the other presented options) from "Select Launch Configuration" (see pic below) but do NOT click on the edit icon.
![image](https://github.com/Dart-Code/Dart-Code/assets/88656993/6b34f6f0-a1df-475d-a28a-8338d4c7688f)
(I didn't have any device or emulator connected now which I guess is why there's no device name mentioned in parentheses).
4. New config added to the list of launch configurations, but it does not appear in launch.json.

Looks like deleting the one directory in %APPDATA%\Code\User\workspaceStorage which contains workspace.json with the path of my mobile app project resets things and makes those "extra" launch configs get cleared (i.e. now I only have those which are set in launch.json). For me that's all I need for now.

**Comment by DanTup** [comment]
@solita-esatikka can you check whether the "Flutter (pixel 4)" config has been added to your `launch.json` and if so, see what's different between it and the configuration that works?

If it was not added, could you try clicking the Dart&Flutter option as you did, but this time click the cog icon next to "Flutter (pixel 4)" which should force it to be added to your launch.json, and then see what's different between it and the working one?

I wonder if the automatic configs are being configured incorrectly (for example having the wrong `program`/`cwd` or something).

Thanks!

**Comment by DanTup** [comment]
> The one issue with those configs I have is that they are not editable after creation, and also they are not deletable (except by wiping the workspace storage or some more fine-grained such method)

Yeah, this seems really confusing to me too. It seems that VS Code is keeping track of decent automatic configurations you selected. You can delete them via the **Debug: Select and Start Debugging** command (which is what the "Dart & Flutter" option at the bottom of the drop-down essentially triggers). I've opened https://github.com/microsoft/vscode/issues/197821 about this because I think it could be improved.




That aside, are you able to choose "Dart & Flutter" and then click the cog next to "Flutter (pixel4)" so that it's added to your `launch.json` explicitly to see what's being generated that is incorrect that prevents the app from launching? It's very possible our automatic configs aren't being created correctly and I'd like to fix that. You can delete the launch.json entry afterwards, ofcourse :-)

Thanks!

**Comment by solita-esatikka** [comment]
> You can delete them via the Debug: Select and Start Debugging command
Thanks for the tip! My use of VSCode is more on the level of "its a really good editor" and I have not really been using any of the run/debug stuff at all.

The generated config differs only for `"program": "lib/main.dart"` (which is not present in our custom configs, but I guess it is the default anyway), and the `toolArgs` which I mentioned already above. I think the config autogeneration is ok for generic needs.

Thanks!

**Comment by DanTup** [comment]
Oh, I see - so the missing flavour was the cause of the error? In that case, I agree everything is working correctly (and hopefully VS Code might make it a little clearer where that launch config option comes from, and allows deleting it from here).

Thanks!
