### ISSUE TITLE
switch expression snippet does not show after "return" and "=>"

### ISSUE THREAD

**Issue by simphotonics** [Dart-Code/Dart-Code#4843]
**In Dart Code `v3.76.1`, the auto-completion menu shows the entry `switch expression` when defining a variable:**
```Dart
final String message = swi
```

**It would be useful, if the entry `switch expression` is presented whenever an expression is expected.**

For example in the following circumstances: 

```Dart
// After the symbol =>
String message() => swi

// After the keyword return
String message(){
  return swi
}
```

**Comment by DanTup** [comment]
Ignore that - my bug was caused by another existing known issue and unrelated to this.

With that resolved, using the latest SDKs I can only reproduce your second issue (in the return statement). The first example seems to work fine:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/2343a2bc-de20-48a8-a571-384e9b7bb5d3)

Can you confirm your Dart/Flutter SDK version? (and I'll look into the `return` one).

**Comment by simphotonics** [comment]
Just updated my Dart SDK from version 3.1.5 to 3.2.0
```Term
$ dart --version
Dart SDK version: 3.2.0 (stable) (Tue Nov 14 18:26:59 2023 +0000) on "linux_x64"
```
With version 3.2.0 the `switch expression` entry is indeed shown after `=>` and not shown after `return`.

**Comment by DanTup** [comment]
Great, thanks for confirming. I have a fix open for the return issue at https://dart-review.googlesource.com/c/sdk/+/338401.
