### ISSUE TITLE
Cannot run CLI script located in another package from a Flutter project's launch configuration since version 3.78.0

### ISSUE THREAD

**Issue by krispypen** [Dart-Code/Dart-Code#4867]
## Describe the bug:
Since version 3.78.0 ([commit](https://github.com/Dart-Code/Dart-Code/commit/74fd1ff0b6968cd59d3a03d2472897c25de482de)) it is not possible anymore to run dart scripts from another package because the path has to start with bin/

We have a monorepo setup and one of the packages contains multiple cli scripts (for syncing the styleguide, syncing translations, exporting translations, ...) The way we do that is running the cli script but the cwd is actually the other package. Maybe a better approach would be to make it possible to debug cli scripts defined by the package, so for example `dart pub run tools:toolX`.

## To Reproduce:
I created a demo project https://github.com/krispypen/dart_extension_bin_issue
if you open the workspace file in vscode and then try to run "Run toolX" it will not run because it is not recognized as a dart script. On version 3.76.1 and lower it works.

## Expected behavior:
until version 3.76.1 it was possible to run dart cli scripts where the path contains bin

## Screenshots:
<img width="1141" alt="Screenshot 2023-12-01 at 10 47 21" src="https://github.com/Dart-Code/Dart-Code/assets/156955/6a8f4b40-9521-477b-8b88-3e20ff5ba499">

##Version info:
 - Operating System and version: MacOS Sonoma
 - VS Code version: 1.84.2
 - Dart extension version: 3.78.0
 - Dart/Flutter SDK version: 3.13.6
 - Target device (if the issue relates to Flutter debugging): running dart script so no device

**Comment by DanTup** [comment]
Thank you for providing the simple repro!

I need to convince myself whether this is a bug or desired functionality (we try to infer a lot of things when starting the debugger, and some of them are circular - like the script being run can influence the cwd and the cwd can influence which scripts we try to run). This does work:

```
"program": "bin/toolX.dart",
"cwd": "../tools",
```

Because it tells us to treat `../tools` as the project root, so we then realise the path starts with `bin`.

However, I'm not sure this is perfect, because if you had a tool where you need the cwd to be another folder (for example where it's supposed to operate), then you wouldn't be able to do this.

I'll think a bit more about this and see if we can solve both this and the original issue together.

**Comment by DanTup** [comment]
btw - I'm curious why you have this in the launch.json of the Flutter app, and not in the CLI project itself (or in the `code-workspace`)?

**Comment by DanTup** [comment]
> However, I'm not sure this is perfect, because if you had a tool where you need the cwd to be another folder (for example where it's supposed to operate), then you wouldn't be able to do this.

This exact situation came up at https://github.com/Dart-Code/Dart-Code/issues/4894#issuecomment-1854196172, so it definitely needs a solution.

**Comment by DanTup** [comment]
@akemimadoka - could you try switching to the pre-release extension (v3.79.20231214 or newer) and test that my fix covers the setup you have?

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />

Thanks!

**Comment by krispypen** [comment]
My use-case works again with the pre-release version v3.79.20231214! 🎉 👍

**Comment by akemimadoka** [comment]
It works like a charm! 🎉
