### ISSUE TITLE
[BUG] Dark theme changes color

### ISSUE THREAD

**Issue by zs-dima** [Dart-Code/Dart-Code#4869]
This issue had been already described, but wrongly closed https://github.com/primer/github-vscode-theme/issues/183

Reproduced for Dart and Flutter code highlighting.

Turning off Semantic highlighting will disable very useful highlighting features, that make code badly readable.

When using your dark theme with dart or flutter in VSCode, it originally looks like this
![image](https://user-images.githubusercontent.com/25195453/204899001-259bfd1f-343f-4e88-9ab6-fb2ea88bbc78.png)

but then after a minute switches to this:
![image](https://user-images.githubusercontent.com/25195453/204899120-8cbcd5b7-ab7b-4865-9764-2d3db6bf49a0.png)

0.1. Install Flutter and Dart VSCode plugins
0.2. Install GitHub theme VSCode plugin
0.3. Select GitHub theme for the VSCode

Dart Code extension: 3.79.20231130
Flutter extension: 3.79.20231130 (activated)
App: Visual Studio Code - Insiders win 1.85.0-insider
Workspace type: Dart, Flutter (LSP)
Dart (3.2.0)
Flutter (3.16.0)
Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.2715]
Framework revision db7ef5bf9f (2 weeks ago), 2023-11-15 11:25:44 -0800
Engine revision 74d16627b9
Dart version 3.2.0
DevTools version 2.28.2

**Comment by DanTup** [comment]
I just tried this theme with TypeScript, and it looks very similar (with lots of orange) to me:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/5b75409c-9c7b-41c4-89de-27afd259402a)

TypeScript doesn't have named arguments so those look a little different (because they're considered property declarations by TypeScript), but otherwise it seems to me like things are the same.

Although, it's not completely clear to me which of the colours you're seeing you disagree with.
