### ISSUE TITLE
StackTrace in vs code not clickable 

### ISSUE THREAD

**Issue by heshesh2010** [Dart-Code/Dart-Code#4872]
**Describe the bug**
When any exception occure in flutter i got stacktrace but without any clickable link to line code . 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2023-12-02 at 11 24 24 PM](https://github.com/Dart-Code/Dart-Code/assets/16393042/6f5f9661-0f34-4463-b4cb-28da30f89f56)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version: 
 -  Version: VS Code (version 1.84.2)
 - Dart extension version:  v3.78.0 

 - Dart/Flutter SDK version:  3.13.9,
 - Target device (if the issue relates to Flutter debugging): ios

**Comment by DanTup** [comment]
@heshesh2010 can you try upgrading to the latest version of Flutter and let me know if you see the same? There were changes in Flutter 3.16 that improved linking of stack traces in the Debug Console. If it still occurs there, can you provide a code sample that fails in this way?

@nehal076 

> And also the `log()` for `dart:developer` won't show me logs.

Are you running with "Run" and not "Debug"? Some functionality (such as `log()`) is only available in debug mode. In the past we sometimes connected the debugger in Run mode but it was inconsistent (and different to Dart, where we never did) so that has been changed.

**Comment by nehal076** [comment]
I'm running in debug mode itself

**Comment by heshesh2010** [comment]
> @heshesh2010 can you try upgrading to the latest version of Flutter and let me know if you see the same? There were changes in Flutter 3.16 that improved linking of stack traces in the Debug Console. If it still occurs there, can you provide a code sample that fails in this way?
> 
> @nehal076
> 
> > And also the `log()` for `dart:developer` won't show me logs.
> 
> Are you running with "Run" and not "Debug"? Some functionality (such as `log()`) is only available in debug mode. In the past we sometimes connected the debugger in Run mode but it was inconsistent (and different to Dart, where we never did) so that has been changed.

updated to latest flutter version and here is screen shot 

![Screenshot 2023-12-04 at 11 51 19 PM](https://github.com/Dart-Code/Dart-Code/assets/16393042/56d1e2c9-13a1-4b6d-b5b1-da1c1a410a19)

**Comment by heshesh2010** [comment]
> @heshesh2010 can you try upgrading to the latest version of Flutter and let me know if you see the same? There were changes in Flutter 3.16 that improved linking of stack traces in the Debug Console. If it still occurs there, can you provide a code sample that fails in this way?
> 
> @nehal076
> 
> > And also the `log()` for `dart:developer` won't show me logs.
> 
> Are you running with "Run" and not "Debug"? Some functionality (such as `log()`) is only available in debug mode. In the past we sometimes connected the debugger in Run mode but it was inconsistent (and different to Dart, where we never did) so that has been changed.

i upgraded to latest version 3.16.2 and still there is no link to error in debug console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.2 23B92 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources


![Screenshot 2023-12-06 at 10 37 41 PM](https://github.com/Dart-Code/Dart-Code/assets/16393042/b9f3eff3-76e5-4ef6-a48e-884a9e21d78b)

**Comment by nehal076** [comment]
Hi @heshesh2010, 

I'm using

```
Flutter 3.16.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9e1c857886 (6 days ago) • 2023-11-30 11:51:18 -0600
Engine • revision cf7a9d0800
Tools • Dart 3.2.2 • DevTools 2.28.3
```

And I see nothing on my debug console when I use `log()`

**Comment by heshesh2010** [comment]
> Hi @heshesh2010,
> 
> I'm using
> 
> ```
> Flutter 3.16.2 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 9e1c857886 (6 days ago) • 2023-11-30 11:51:18 -0600
> Engine • revision cf7a9d0800
> Tools • Dart 3.2.2 • DevTools 2.28.3
> ```
> 
> And I see nothing on my debug console when I use `log()`

Yes i'm just mention @DanTup

**Comment by DanTup** [comment]
@nehal076 the issue you're seeing is https://github.com/Dart-Code/Dart-Code/issues/4875 and is unrelated to this one. That's been fixed in the pre-release extension if you want to try it out. I'm planning to patch it into the stable extension next week if no issues come up.

@heshesh2010 are you able to share any code that triggers this? If something is catching and printing the exceptions then this is probably a duplicate of https://github.com/Dart-Code/Dart-Code/issues/4711, but otherwise I'd need to do some more debugging.
