### ISSUE TITLE
Developer logs not showing up on the debug console anymore while running using the 'Run Without Debugging' option

### ISSUE THREAD

**Issue by rasitayaz** [Dart-Code/Dart-Code#4875]
**Describe the bug**
Outputs of the `log()` function from `dart:developer` import is not showing up at the debug console anymore unless you run the app using "Run > Start Debugging". This was not the case before, I was able to see the logs on my console using "Run > Run Without Debugging" option.

I sometimes need to output long data on my console but this is not seem to be possible using `print()` since it truncates the text. I also don't want to use debugging mode while developing my application because the app runs too slow and it gets interrupted for every exception.

https://github.com/flutter/flutter/issues/135445

**To Reproduce**
1. Import `dart:developer` into your dart code
2. Log something using `log()` function
3. Run the app using "Run > Run Without Debugging"

**Expected behavior**
Log output to be displayed on debug console.

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: macOS Sonoma 14.1.2
 - VS Code version: 1.84.2
 - Dart extension version: v3.78.0
 - Dart/Flutter SDK version: 3.16.2
 - Target device (if the issue relates to Flutter debugging): iOS Simulator, macOS, Android Emulator, Web

**Comment by DanTup** [comment]
Since this issue (and a related issue with Widget Inspector navigation #4878) came up a few times, we've decided to apply a patch that resolves this by making the "Start without Debugging" option work more like "Start with Debugging" (that is, it will always connect to the VM Service).

The fix is already included in the pre-release version of the extension and I'll push later this week or early next week if nothing comes up.

If you want to try it out, you can switch to the pre-release versions with these button in VS Code:

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />
