### ISSUE TITLE
Misleading `Enum.values` type hint

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4877]
**Describe the bug**
Hovering over the `values` getter currently shows the enum type, but is actually a list of values.

```dart
enum MyEnum {
  first,
  second,
}

void main() {
  print(MyEnum.values);
}
```

<img width="449" alt="Screenshot 2023-12-04 at 21 18 53" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/455b33ee-34c4-4b4d-9e3a-e16ffba144de">

\
Given how code navigation works I assume it's all by design, but just in case it's not.

**Please complete the following information:**

Dart Code extension: 3.78.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.84.2

Workspace type: Dart (LSP)

Dart (3.3.0-91.0.dev): /Users/dimannich/Desktop/flutter/bin/cache/dart-sdk
Flutter (3.17.0-0.0.pre): /Users/dimannich/Desktop/flutter (No device)

**Comment by DanTup** [comment]
Feels like a bug to me. Code completion shows it as a `List`, so I don't see why we shouldn't here:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/af9e233d-08da-43f2-9f10-c784b5ebdfc8)

Possibly there's something slightly weird because it's synthetic and navigating will go to the enum itself.

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/bdf45288715dc354842f34090f3313fc1f10859e, ships in the SDK!
