### ISSUE TITLE
[web] How to add args for webdev ?

### ISSUE THREAD

**Issue by woprandi** [Dart-Code/Dart-Code#4884]
I develop remotely web app and I have this issue when accessing the app through proxy : 
![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/faeb086b-b52b-46b6-a26b-094d9b89bb98)

I know it's because the reverse proxy is not well configured but I'd like to keep a identical proxy configuration between development and production. 
I'd like to try the specified flag `--no-injected-client` to webdev but I didn't find how to do that with vscode.

**Comment by DanTup** [comment]
How are you starting the app from VS Code?

You could try setting `toolArgs` in your `launch.json` if you're running through a debug session (see https://dartcode.org/docs/launch-configuration/), but it's not clear to me if you are (or what kind of remote workspace you're using).

**Comment by DanTup** [comment]
Oh sorry, I thought you were using the `webdev` tool for serving a non-Flutter backend. I think there is some confusion because DWDS (which Flutter web uses) lives in the webdev project, but it doesn't use `webdev`.

I'm not sure if you can pass that flag to Flutter web, but you should be able to use "Start Without Debugging" (or add `"noDebug": true` to your launch config) to start in a way that doesn't require the injected client.

Note: Due to a workaround for a different bug, you may need to add `"dart.allowFlutterForcedDebugMode": false` to your VS Code workspace settings for this project for the next few releases, because Flutter apps will soon be forced through debug mode with breakpoints/exceptions disabled while we fix an issue in the debug adapters).

**Comment by woprandi** [comment]
I tried `"noDebug": true` to my `launch.json` without any effect : 

![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/72ec4f77-7f37-474e-8f87-eeae36a84c8c)
![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/88653eaa-54a8-4748-8c11-e675e248198a)

**Comment by DanTup** [comment]
Ah, looks like maybe Flutter web apps won't load without the dwds handler. I don't think there's currently a way to disable that.

Do you know why the WebSocket request is failing? I presume it's related to the proxy - is it possible to allow WebSockets through?

**Comment by DanTup** [comment]
I just tested this and actually don't see the WebSocket request in `noDebug` mode. Can you confirm you tried adding `"dart.allowFlutterForcedDebugMode": false` to your VS Code settings?

**Comment by DanTup** [comment]
Sorry, I missed this in your original message:

> and `"dart.allowFlutterForcedDebugMode"` is currently unknown

This is a hidden setting so VS Code will report it that way - you should ignore the warning but keep the option.

**Comment by woprandi** [comment]
I did :

![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/ff8a6ced-d90b-4853-8110-cac94e2c136a)

Chrome : 
![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/d0ec931d-5df4-4568-8ffb-79ae174463ab)

**Comment by DanTup** [comment]
@woprandi how are you starting the app, with `F5`? I tested again but couldn't repro. Could you test this in a new test app (if you're not already using one) and capture a debug log?

- Run **Dart: Capture Debugging Logs**
- Start the app with `F5`
- Wait for the app to open in the browser and see the WS request
- Click **Cancel** on the logging notification to stop logging

Attach the log here, or email to me at logs@dartcode.org

Thanks!

**Comment by woprandi** [comment]
Ok I found. Apparently on devcontainer I have to specify vscode settings in `devcontainer.json` and rebuild the container. I think `"dart.allowFlutterForcedDebugMode"` was ignored before. Now it is working without WS. Thank you for your help

**Comment by DanTup** [comment]
Odd - I can't think of why either the setting or noDebug flag should require rebuilding the container, but I'm glad you have it working anyway. Let me know if any issues come up.

**Comment by woprandi** [comment]
I checked once again to be sure to not make wrong conclusions, I need both : 

- `"noDebug": true` in `launch.json`
-  `"dart.allowFlutterForcedDebugMode": false` setting (in devcontainer.json or settings.json)

I also upgraded Flutter from 3.3 to current stable which can explain why it didn't work before

**Comment by DanTup** [comment]
Ah, using an older Flutter could be different because we have been migrating the debug adapters and you may have been on the old ones (which behaved a little differently). Rebuilding the devcontainer could have changed which debug adapter you get (because we assign a random number the first time, then choose based on the % rollout for that feature).

Sounds like all is working as expected now on the latest version anyway :-)
