### ISSUE TITLE
Hover and Suggest Widget: Show Tags

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4942]
## The Issue

To find out detailed information about a symbol, the best approach is to navigate to the source code, which is cumbersome.

For example, if you wanted to find out whether a `getter-setter` was `read-only`, (and therefore technically a `getter`), you would have to navigate to the source code by using the `Go To Definition` command.

---

## Describe the solution you'd like

Dart online documentation has `tags` (I'm not too sure what they're called, please correct me if I got it wrong), like below:

<img width="121" alt="Image of Tags in Dart" src="https://github.com/Dart-Code/Dart-Code/assets/115815794/e292f846-f798-4265-862e-22702b5a5ff2">

It would be very useful if these tags were reproduced in the editor suggest and hover widgets, to give more information about a symbol.
---

### Options / Settings

- There should ideally be an option to opt-in to this feature, e.g. `showTagsInSuggest` and `showTagsInHover`.
- Also, there could be another option to make the tags appear in a separate suggest / hover widget, e.g. `showTagsInSeparateWidget`
- Finally, there should ideally be an option to show the tags:
  - `immediate` (before name)
  - `first` (after the name and before the documentation)
  - `last` (after name and documentation)

Thanks!

**Comment by DanTup** [comment]
I don't know if we could render tags like this in the hovers (because we can only supply Markdown to VS Code and it handles the rendering), but we might be able to display the same information in another form. The modifiers are probably easy, but I'm not sure how Dartdoc computes things like `inherited`.

Could you file this at https://github.com/dart-lang/sdk/issues and CC me? The hover markdown comes from the Dart analysis server so we'd need to change it there. Thanks!

**Comment by Number-3434** [comment]
Transferred to https://github.com/dart-lang/sdk/issues/54705.
