### ISSUE TITLE
Support the -e flag for Flutter project creation

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#4944]
It is possible since a while to create an "empty" Flutter project with the -e option: flutter create -e test_app

See https://stackoverflow.com/questions/47804637/how-do-you-create-a-flutter-app-without-the-counter-myapp-boilerplate-code-being

Would be very nice to have this option also in VScode for project creation.

**Comment by DanTup** [comment]
The empty template is already available in the **Flutter: New Project** list:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/25866f94-c075-4c37-834a-3077d8d99184)

It was folded into the main list here because it felt more natural to me than having an option that applied only to a specific template.

Let me know if this isn't what you were looking for.

**Comment by vogella** [comment]
Thanks @DanTup for information and sorry for the noise.

**Comment by DanTup** [comment]
np, I'd rather have some dupes/requests for existing functionality than people not file requests for good ideas :-)

(and it's also a good indicator that discoverability might be bad if the same existing requests come up many times!)
