### ISSUE TITLE
[EXPERIMENTAL] CodeLens for Widget Refactorings

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4962]
## Proposal

Add a CodeLens on eligible widgets to refactor the widget.

Specifically, only refactorings that wrap, move, or remove the widget should be included.

For example, the following:
```dart
SizedBox();
```

could have a CodeLens above it like:

<samp>Wrap | Stack | Remove</samp>

- `Wrap`: `Wrap with Widget`
- `Stack`: Custom Refactoring that essentially resembles `Wrap with Row`, but instead wraps with a `Stack`, and selects the `Stack` word.
- 

Furthermore, if the widget is in an array in a `children` argument, there should also be options to move it up or down.

### Arrow Mode

This mode will use arrows to indicate refactorings as follows:

- →: Wrap Widget
- ←: Remove Widget
- ↑: Move Widget Up
- ↓: Move Widget Down

**Comment by DanTup** [comment]
I'm not sure I understand the value in having these as CodeLens when they're already on the menu. I feel like it would add a lot of noise to the editor and what things are useful there is very subjective.

It would also be much more expensive to do this for CodeLens because we have to provide CodeLens for the whole file up-front, whereas for the lightbulb/refactor menu, we only need to compute them for one specific location at a time.

**Comment by Number-3434** [comment]
Okay, yeah I suppose so.
