### ISSUE TITLE
Documentation Missing in Compound Declaration

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#4970]
## The Issue

The documentation for symbols after the first in a compound declaration lack documentation.

## To Reproduce

Copy the following:

```dart
/// Documentation for [a]
var a = 0,

    /// Documentation for [b]
    b = 0;
```

Then, hover over `b`, and there won't be any documentation.

**Comment by DanTup** [comment]
@bwilkerson @srawlins is it valid to put doc comments on individual variables like this? My feeling is that it should be, but I thought I'd test what DartDoc does first and given:

```dart
/// var list
var
    /// test a
    a = 1,
    /// test b
    b = 2;
```

In the DartDoc output both items also show the doc from the list and not the individual variable:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/b05b19da-a4fd-4436-9119-5cb1c34c966c)

I suspect it's expected, because it seems similar to doing this:

```dart
/// this is f
void f(
  /// this is a
  int a
) {}
```

Hovering `a` here shows `"this is f"`.

**Comment by bwilkerson** [comment]
> ... is it valid to put doc comments on individual variables like this?

I'm not sure what 'valid' means here :-), but we don't currently support doing that.

I'd recommend writing that as
```
/// test a
var a = 1;

/// test b
var b = 2;
```

> Hovering `a` here shows "this is f".

We don't support putting docs on parameters either.

**Comment by DanTup** [comment]
Sorry, by "valid" I meant "considered the documentation for this variable". As in, is there a bug here, or is it not supported (eg. is it the same as putting doc comments on the parameter... something that is valid to do, but will be ignored).

So I'll close this as not-a-bug. Perhaps it's a valid feature request but probably belongs in the dartdoc or SDK repos (seems there's an existing issue for parameters at https://github.com/dart-lang/sdk/issues/43185 with some discussion).

**Comment by Number-3434** [comment]
How would that work?

In your example of no doc comments on parameters, the preferred solution is to instead embed the documentation for the parameters into the method description itself.

In the case of compound declarations, would that mean you would put all the documentation on the first member?

**Comment by DanTup** [comment]
> In your example of no doc comments on parameters, the preferred solution is to instead embed the documentation for the parameters into the method description itself.

Sorry, I wasn't suggesting the solution was the same. I'd noted that this issue was similar to parameters in that there are locations where you can write triple-slash comments that are not considered documentation. I linked to that issue just because I thought it had interesting discussion for the (slightly related, but perhaps not all that relevant) issue.

I think the best current solution is as Brian noted above, which is to split the declarations up. Because they're already on their own lines, hopefully this is a minor change without any drawbacks.

**Comment by Number-3434** [comment]
Okay 👌 thanks for the clarification
