### ISSUE TITLE
ThemeData

### ISSUE THREAD

**Issue by yafranck** [Dart-Code/Dart-Code#4972]
/AppData/Local/Pub/Cache/hosted/pub.dev/fab_circular_menu-1.0.2/lib/fab_circular_menu.dart:240:56: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/C:/flutter/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
    _ringColor = widget.ringColor ?? Theme.of(context).accentColor;

**Comment by DanTup** [comment]
Hi,

It appears that you're using `package:fab_circular_menu` which was discontinued and [last published almost 3 years ago](https://pub.dev/packages/fab_circular_menu/versions).

There have been breaking changes in Flutter since then (such as [removing the accent properties from ThemeData](https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties)) so this package will not work with recent versions of Flutter.

You should stop using `package:fab_circular_menu` or fork the code and update it to work with newer versions of Flutter.
