### ISSUE TITLE
Completion overwrites

### ISSUE THREAD

**Issue by UglyBob79** [Dart-Code/Dart-Code#4979]
I feel that the completion works slightly different than with other extensions and/or editors. If I for instance have this code:

`preferences.saveEmail(email);`

and I want to add another parameter before email, I might put the cursor in front of email and start writing the name of the other parameter. A list of options will appear and when selecting it, it will overwrite email (if you dont put a comma in advance). Other extensions, for instance python, will just insert the completion and leave 'email' intact. I think this is the expected behavior.

**Comment by DanTup** [comment]
There's a setting `"editor.suggest.insertMode"` that lets you control the default insertion mode:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/7e031f54-7c82-46cf-96fd-ac1ed9ab8c31)

For Dart, we default to replace. You can change it in VS Code, but you must set it in the `"[dart]"` section (the Dart default will override the global setting).

Regardless of the default, you can also always `Shift+Enter` to complete the opposite way (insert if default is replace, or replace if default is insert).

Replace has always been Dart's default (since before VS code had a setting to control it, and always assumed replace), which matched some other languages I'd used (like C# in Visual Studio). I don't know whether it was the right call (other languages are inconsistent), but it's not feasible to change the default now and so it's something you'd need to set yourself.

Hope this helps!
