### ISSUE TITLE
Strings in debugger are truncated in fields but not in the parent objects toString() representation

### ISSUE THREAD

**Issue by BenjiFarquhar** [Dart-Code/Dart-Code#4986]
The image shows the variable in watch, console, local debugger, and tooltip. 

<img width="1725" alt="Screenshot 2024-02-15 at 07 56 55" src="https://github.com/Dart-Code/Dart-Code/assets/26356162/0bd520f3-6699-4091-9119-541f8dff74bb">

"Copy value" shows:

"/Users/benjaminfarquhar/Library/Developer/CoreSimulator/Devices/F56DA440-80AE-494E-A141-4EB263A9FF4F/data/Containers/Data/Applic…"

Interestingly, the grey text in the debug variables is not truncated. So you can see the whole value if you hover over `file.value`, it shows the `File` which seems to contain the path inline inside the `File`. But I think if the variable was a primitive `String` (not a `String` within a `File`) it would be impossible to see the whole value.

**Comment by DanTup** [comment]
Turns out, this was fixed more recently than I remembered and hasn't made it to a stable release yet:

https://github.com/dart-lang/sdk/commit/59294606cf8c5d07d98c9beac4eff43dbf609f11

I tested on Flutter stable and it's truncated, but on beta it's not.

> Interestingly, the grey text in the debug variables is not truncated.

Hmm, that might be a bug. Generally in this view we are given truncated strings by the VM Service. We don't normally expand them except in the REPL/Debug Console and Copy Value because in a large object, there could be a lot of large strings.

However, we to (by default) call `toString()` on complex objects, and I wonder if that's bypassing the truncation. I'll take a look because this should be consistent.

When the current beta goes stable, Copy Value should work as you expect though.

**Comment by DanTup** [comment]
I've renamed this issue and will use it to track the inconsistency noted above (the fix may be for the grey text to also be truncated).

**Comment by DanTup** [comment]
This is fixed (that is, we will consistently use truncated values unless you're in the REPL or using "Copy Value") by https://github.com/dart-lang/sdk/commit/2f2564c99f97dbea5c010f704e9b0583e122917f. The fix is in the SDK debug adapters so will ship in a future SDK release.
