### ISSUE TITLE
Markdown decorations for the simple `//` comments

### ISSUE THREAD

**Issue by pouyakary** [Dart-Code/Dart-Code#4993]
**Is your feature request related to a problem? Please describe.**

When writing documentation comments, the decorations make it very readable, but there are places that I want to highlight a portion of a comment within the code and not for the documentation reader. In this places I must use the `///` comment instead of `//` comment:

<img width="581"  src="https://github.com/Dart-Code/Dart-Code/assets/2157285/fed01aa1-2320-4350-ad3c-255319fbf006">

And if I use the `//` comment, the decorations are lost:

<img width="629" src="https://github.com/Dart-Code/Dart-Code/assets/2157285/7606bd36-7b5e-4cf8-89ed-040508387cfc">

**Describe the solution you'd like**

I wished this coloring of markdown elements were also available for the `//` comments.

**Describe alternatives you've considered**

I can use the `///` comments (as seen in the screen shot), but then that is problematic since they are for documentation and not hints and usual comments.

**Additional context**

I'm afraid that's it.

**Comment by DanTup** [comment]
Today, I think only `///` comments are treated as Markdown, so other comments are just text without any formatting.

I'm not sure about Markdown, but I think I have often tried to write `[ClassReference]`s in comments (because referencing a class was a useful thing to do in an explanatory comment) but it also doesn't work.

@bwilkerson @srawlins have there been any discussions around this before? I can't find any existing issues in the SDK (I guess it's not so much a dartdoc request because presumably dartdoc never looks at these kinds of comments).

**Comment by pouyakary** [comment]
I agree, but having the formatting is such a huge tool. Imagine just scrolling on the comments and you see a `CAUTION` like that. It catches your eye and is really helpful.

**Comment by bwilkerson** [comment]
I'm confused. I don't see any highlighting of code blocks in documentation comments in my IDE. To the best of my knowledge we only highlight comment references. Where is this highlighting coming from?

**Comment by bwilkerson** [comment]
I'm not necessarily opposed to either of those ideas, but there are some issues we probably need to think about first. I think we need a design doc where we can address these questions.

Are we specifically interested in end-of-line comments or would we want to handle block comments as well?

For (1), we have not treated ordinary comments as markdown in the past, so I don't know how common it is for users to have written them as if they were. If users have written comments containing characters with special meaning to markdown but not intended it to be interpreted that way, then this change could be fairly disruptive.

Maybe even more to the point, we haven't treated ordinary comments as the extended form of markdown that we use for documentation comments, which might lead to an even bigger discrepancy between the user's intent and our interpretation.

And for both suggestions, we don't keep any data around to represent ordinary comments, so we'd have to traverse the token stream to find them. That's additional processing, which might have a performance impact. I don't know how many ordinary comments there are in most code, so I don't know the potential impact.

For (2), we also don't resolve those references in ordinary comments the way we do for documentation comments. The impact is primarily that we would need to re-build the name scope (and define what the name scope is in some cases) for every comment that includes a reference.

In a world where we have documentation imports (which seems likely to happen at this point), do we support doc imports in ordinary comments?

Either way, do ordinary comments include doc imports in their scope?

**Comment by DanTup** [comment]
Seems like this is more complicated than I thought.

I decided to have a quick scan through the analyzer/server code for these comments that include square brackets to see if _trying_ to use references was common. It turns out it is, however it also highlights another problem that I think might make this a non-starter:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/4d2fffd3-6f57-410b-9543-0a3bce8438b1)

The issue is commented out code... With dartdoc comments code is surrounded with triple-backticks we so know that the rest is comment text and can handle references. double-slash comments have no such rule and can often contain code so I think trying to parse them to find markdown or references might be an impossible task 🤔

**Comment by bwilkerson** [comment]
Yes. Commented out source code is one common example of what I was referring to when I wrote:

> If users have written comments containing characters with special meaning to markdown but not intended it to be interpreted that way, then this change could be fairly disruptive.

I suspect that we'd end up highlighting any identifiers within square brackets as a reference and try to resolve it. If we couldn't resolve it we could use that as a signal to not highlight it that way, but I suspect that the overall effect would be a net negative in some code bases.

**Comment by DanTup** [comment]
I wonder if it'd be better to just advise using `///` if you want this behaviour. I suspect in most locations where this is desired (such as function bodies) it's not a valid location for documentation so it wouldn't show up anywhere but would signal the intention for the comment to be parsed this way.

**Comment by pouyakary** [comment]
I have not disabled the semantic tokens, but I have added the support for the TextMate grammar that is accessible to my theme. One thing is that you don't have to parse everything yourselves. You have access to the TextMate grammar which is the foundation for everything else and it doesn't impose the same performance weight on the system. In a TextMate grammar you have a language stack, and you can say when I encounter the sign A, pause parsing as dart and start parsing as markdown and once I encountered B, pop the markdown and go back to dart. This way without paying any tax on the performance the whole of markdown becomes available. You can then only add the class references as you do now with the semantic tokens.

**Comment by bwilkerson** [comment]
> I wonder if it'd be better to just advise using `///` if you want this behaviour.

Yes. Having a clear indication that the comment is intended to be markdown would definitely improve the situation.

We'd still need to look through all the comments in the file to see whether any of them are `///` (and not already handled as documentation comments) and then parse those and resolve any such references. So it wouldn't solve all of the implementation problems, but it would solve the UX problem.

**Comment by DanTup** [comment]
@pouyakary 

> I have not disabled the semantic tokens, but I have added the support for the TextMate grammar that is accessible to my theme.

I'm not sure I understand. When semantic tokens are enabled / supported by the theme, they usually override the textmate grammar. Unfortunately when using semantic tokens, VS Code does not support nested grammars (see https://github.com/microsoft/vscode/issues/163292).

>  You have access to the TextMate grammar which is the foundation for everything else and it doesn't impose the same performance weight on the system.

The textmate grammar for Dart is quite simple compared to the real language parser so it doesn't provide the same quality of colouring as the semantic tokens. While I'd like them to be closer than they currently are, I don't think the grammar will ever give as good (or better) results as the semantic tokens. It's certainly faster (both because it's simpler, and because VS Code uses it directly and it doesn't need to go across processes, wait for analysis, and encoding/decoding of JSON), but I don't think it's overall better.

> You can then only add the class references as you do now with the semantic tokens.

If you know how we can apply the markdown grammar when using semantic tokens I'd love to know more. I think it would help with https://github.com/Dart-Code/Dart-Code/issues/4925. However, the issue here (relating to `//`) is less about the mechanics of doing the highlighting, and more about whether it's _reasonable_ to treat normal comments as markdown. Based on the examples above (in particular that they can include commented out code), I think trying to parse as markdown could result in bad colouring in a significant number of places because the comments were not just natural language comments with a few markdown markers.

**Comment by DanTup** [comment]
Just tidying up issues... Based on discussions above, it sounds like we don't want to try and parse markdown in double-slash comments, because there could be a lot of false-positive markup. If there are other things we should consider, we should open new issues (here or in the SDK) with more specific details.
