### ISSUE TITLE
Add pub commands

### ISSUE THREAD

**Issue by jacehensley-wf** [Dart-Code/Dart-Code#50]
It would be nice to have the ability to run pub commands in the editor.

The Atom plugin has the following:
- `pub run`
- `pub get`
- `pub upgrade`
- `pub global run`
- `pub global activate`

**Comment by DanTup** [comment]
Presumably you need to pass arguments/filenames to some of these - how does Atom handle that? Does it give you a file selector or something?

Do you think it'd make sense to automatically run `pub run` on a change/save to `pubspec.yaml`?

**Comment by jacehensley-wf** [comment]
Do you mean `pub get`? I think it would be nice. IIRC the Atom plugin shows an alert when `pubspec.yaml` changes asking if you want to run pub get. 

I'm not really sure how the atom plugin handles these commands, I would assume most of them just to need to be told which directory to run on, the current directory. But I believe you can only run them when you are in the editor view.

**Comment by DanTup** [comment]
Whoops, I did mean `pub get` (commented edited for clarity).

I'm not all that familiar with Dart but I figured if you have two files in `./bin` and wanted to run, you'd need to say which one?

I should review the APIs for tasks and commands in Code and see what the options are.

**Comment by jacehensley-wf** [comment]
Yeah, I think with `pub run`, `pub global run`, and `pub global activate` I think you do need to pass in the file you want.

**Comment by devoncarew** [comment]
`pub get` and `pub upgrade` are now exposed -

**Comment by DanTup** [comment]
I think `pub run` might sit well with (or after) #56.

The other two seem to me more like things you're want to just run in a shell (Code has an integrated shell, though I've not use it much yet) rather than relate to the project you're editing - is that correct? If not, could you add some more info on the use cases?

**Comment by DanTup** [comment]
I don't think adding the remaining commands here would be all that useful - Code has a builtin terminal where you can run whatever you want and I think that would be a better user experience than us having to prompt the user with some file picker (and figure out how to filter it).

I also think in most cases for running your app you'd be better doing it via the `launch.json` stuff and hitting `F5` to run?

Let me know if anyone thinks there's still value in what's left here and how they think it should work; otherwise I may close this.

**Comment by DanTup** [comment]
See above comment - closing this due to no input. I don't think there's value in the remaining commands (get/upgrade are already done).
