### ISSUE TITLE
Shortcut to fold asserts 

### ISSUE THREAD

**Issue by davidhicks980** [Dart-Code/Dart-Code#5007]
**Is your feature request related to a problem? Please describe.**
Not a problem, aside from legibility

Give a key binding/option to hide assert statements while browsing dart files. 
See [here](https://stackoverflow.com/questions/44060551/how-do-you-hide-arbitrary-section-of-code-in-vs-code#:~:text=Create%20Manual%20Folding%20Range%20from%20Selection%0Aeditor.createFoldingRangeFromSelection) for an example.

**Describe the solution you'd like**
I'd like a keybinding to visually hide assert statements. No code changes, just visual folding. The accessibility of Flutter's source code is an amazing feature, but it can be a bit overwhelming to read code with long assert statements.

**Describe alternatives you've considered**
I've considered writing my own plugin.

**Additional context**

Make this: 
<img width="500" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/59215665/bb1a3eb1-9381-4dd6-8a12-3bc2c9601740">

Look like this:
<img width="500" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/59215665/06ed207d-dbf2-4a2a-90b3-cb7829cae796">

If you all are too busy, let me know if there are any major flaws to this proposal. If not, I may write an extension.

**Comment by DanTup** [comment]
I don't think there's a good way to do this. The command noted above works on the current selection, so you'd have to change the selection in the editor to each assert, execute the command, and then move it back to the original position. I think this will look odd (and might scroll the editor up and down in front of the user).

I think it would be better to try and get APIs from VS Code to allow extensions to fold a set of ranges in a single operation first and then use that.

**Comment by davidhicks980** [comment]
@DanTup Thanks Dan -- I figured there may be a major issue with this proposal. Before we close this issue and I file one with the VSCode team, I took a look at the hide comments extension (https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-hide-comments), which [references](https://github.com/estruyf/vscode-hide-comments/blob/main/src/utils/triggerCommentsHide.ts) this action from the VSCode repo: https://github.com/microsoft/vscode/blob/a389ff1c805a8cb4b8044a5d88a24323ae268ecd/src/vs/editor/contrib/folding/browser/folding.ts#L812. I'm guessing these actions are baked-in or there may be another issue, but I'm curious if you'd suggest that I ask the VSCode team to allow this action for an arbitrary RegExp, or if that would be a non-starter.

**Comment by DanTup** [comment]
There are first-class commands for some types of folding regions (like comments). There are only a very limited set of well-known folding range kinds though (Comment, Import, Region):

https://code.visualstudio.com/api/references/vscode-api#FoldingRangeKind


>  I'm curious if you'd suggest that I ask the VSCode team to allow this action for an arbitrary RegExp

I think a regex is probably unlikely to be accepted because it's not _sound_. If you use regex and there happens to be a match inside something like a string or a comment, it might fold there too. Ranges should really be computed by a real parser that understands the language.

The best options are probably to allow folding a set of arbitrary ranges without needing to select them (this allows extensions to do whatever they want... if they want to use regex fine, but it's not built-in to VS Code encouraging potentially unsound use), or to allow language servers/extensions to provide more folding range kinds (or custom kinds) that could then be folded via command that takes the kind as an argument.

**Comment by DanTup** [comment]
> Update: I just read closer and apparently the hide-comments extension allows for [arbitrary line hiding](https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-hide-comments#:~:text=Hide%20additional%20lines%20by%20regex)? I'll read into it.

I had a quick look at this, and it looks like it's basically using a CSS hack to hide these comments, and not using the built-in folding:

https://github.com/estruyf/vscode-hide-comments/blob/7be127dce5b2b4889c9ffc4878c3966b199d964d/src/utils/setRegexLines.ts#L7

This means the experience is likely different to built-in folding, and it's taking advantage of Code not escaping CSS properly (you can add a semicolon to inject your own rules) that is a bug and could be corrected in a future release and would break this functionality.

**Comment by davidhicks980** [comment]
Interesting! Thank you Dan. That makes sense. I'll close and file some issues!
