### ISSUE TITLE
Move the "Reload recommended" hint to the status bar

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#502]
Using a large modal dialog, which hides the main tool bar, seems a bit invasive
![screen shot 2018-01-18 at 10 10 23](https://user-images.githubusercontent.com/13644170/35089678-f1f290b8-fc37-11e7-9748-837668e574f0.png)

cc @devoncarew @DanTup

**Comment by DanTup** [comment]
I wanted to discuss this one; I wasn't sure what portion of the time people are likely to perform a full restart when this happens (I assumed it would be high, since the user changed code and it didn't run - presumably they want it to, but I haven't done any Flutter dev to this to be well-founded)!

We can move it to the status bar if it's not going to be used so much. I really wanted to make it easy to perform the full restart, though I think even from the status bar we could probably make it clickable.

That said; if we do think the use is likely to be high and we're just concerned about this toast blocking other parts of the UI, maybe this is something we can raise with VS Code to improve.

Lmk what you think!

**Comment by devoncarew** [comment]
The 'reload recommended' message won't always be correct, so a dialog seem slightly more invasive then we'd want. In IntelliJ, we're able to do a slightly smaller decoration at the bottom of the window:

<img width="603" alt="screen shot 2018-01-17 at 3 55 37 pm" src="https://user-images.githubusercontent.com/1269969/35103269-3c11e16c-fc1a-11e7-9192-1faf363553b1.png">

> We can move it to the status bar 

The status bar seems like the right level of notice, and we can revisit as the false positive rate of 'reload recommended' decreases.

**Comment by DanTup** [comment]
Ok cool, I'll move it 🙂

@mit-mit if this is a real annoyance lmk and I can try to fix tonight and push a patch out just with this changed.

**Comment by mit-mit** [comment]
No, not urgent

**Comment by DanTup** [comment]
Any suggestions for the text in the status bar? Here's how it looks atm:

<img width="490" alt="screen shot 2018-02-02 at 11 05 17" src="https://user-images.githubusercontent.com/1078012/35730200-12be0e8a-0809-11e8-8781-4121c175be11.png">

Not sure if "Some elements not reloaded" is the best text. Clicking on the status bar will cause a full restart (not sure if we should describe that in the text, or the tooltip?). Note: you do get the full output from Flutter in the debug window, the main reason for this is for a one-click full restart.

Some thoughts:

- "Full restart?"
- "Full restart recommended"
- "Hot reload completed (partial)"

Any other ideas? The status bar item will disappear if you stop debugging, perform a full restart (either by clicking it or executing the command) or to another hot reload (either via save, or the restart button on the debugger toolbar).

Note: Other "hints" that come back will still appear in the form shown at the top of this issue by default until we specifically code a better way to handle them (it's hard to move them to somewhere like the status bar by default without having a shorter one-line summary).

**Comment by devoncarew** [comment]
It's tough because there's not much space, and it's a complicated message to get across. `Some elements not reloaded` is short and useful, but not technically correct (but may still be a good tradeoff).

`Not all reloaded elements were re-run`? 

`Restart may be required` (w/ a tooltip including more details)?

I like that last one - it tells them what they may have to do, and more info is available about why, if they're curious.

Note that longer term we want to explore using code coverage markers to help give users feedback about what reloaded, what ran after a reload, and what didn't. It'll hopefully require less explicit messaging to the user.

**Comment by DanTup** [comment]
I like `Restart may be required` though should it say `Full Restart`? I've actually been a little confused by the terminology here in the past because I've seen people using lots of different terms (hot reload, hot restart, stateful reload, full restart, cold restart, etc.) - if there's a good definition of what we should be using that'd help (it still slightly confuses me that a "Full Restart" in Dart Code is < 1 sec.. very different to stopping and starting again - it can't really be a *full* restart, right?).

Btw, we do actually have a reasonable amount of space here if the user is at a decent res - I was mostly trying to keep it short because status bars tend to not have such long text; but if you think something longer would be more helpful, we could try that.

**Comment by DanTup** [comment]
I've changed the text to "Full restart may be required" and appended "Click to restart" to the end of the message:

<img width="441" alt="screen shot 2018-02-04 at 11 36 20" src="https://user-images.githubusercontent.com/1078012/35777094-b51d10e4-099f-11e8-9ae4-48f8c83bb1f9.png">

I'm not sure if the "Click to restart" is obvious enough that it refers to clicking the status bar item (and not the tooltip!) but I can tweak if anyone has better ideas.

**Comment by DanTup** [comment]
Also added an icon to the text now [as suggested](https://github.com/Dart-Code/Dart-Code/commit/ec64708b5b00283c8366429baa2b1f22baedf953#r27330562) by Devon :)

<img width="238" alt="screen shot 2018-02-04 at 18 03 31" src="https://user-images.githubusercontent.com/1078012/35780659-a835e1e4-09d6-11e8-8cb4-eb194e8fc3ff.png">
