### ISSUE TITLE
Editor Suggest Widget - Preview Colors

### ISSUE THREAD

**Issue by Number-3434** [Dart-Code/Dart-Code#5032]
Preview colors in the suggest widget, like in CSS:

![VSCode Editor Suggest Widget Showing Color Suggestion In CSS](https://github.com/Dart-Code/Dart-Code/assets/115815794/3e246e4b-6d17-4c31-af0c-fc7b6de04d07)

**Comment by DanTup** [comment]
There's an existing issue for this at https://github.com/Dart-Code/Dart-Code/issues/3941. Unfortunately, the way VS Code implements colours is a hack and the request for a better way to do it was rejected (https://github.com/microsoft/vscode/issues/66606).

The only way we can do this is to basically replace the documentation on a field with a hex code, which would prevent you seeing all of the documentation on the field (which IMO is much more useful, because it often has colour previews in addition to explanatory text).
