### ISSUE TITLE
final class - no suggestion

### ISSUE THREAD

**Issue by TomaszCz** [Dart-Code/Dart-Code#5038]
**Describe the bug**
A quick fix options are missing if you prefix class with final

**To Reproduce**
Create any class and prefix it with final

**Expected behavior**
A suggestion to e.g. generate constructor should be visible

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/20865719/ed018343-2238-4094-92b2-f8357bf3da08)

https://github.com/Dart-Code/Dart-Code/assets/20865719/d516836d-23d7-4616-965e-12cd2858bc3f

Dart Code extension: 3.84.0
Flutter extension: 3.84.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.87.2

Workspace type: Flutter (LSP)

Dart (3.3.0): C:\flutter\bin\cache\dart-sdk
Flutter (3.19.2): C:\flutter (Windows (windows-x64/windows))

**Comment by DanTup** [comment]
>  e.g. generate constructor should be visible

As far as I can tell, the missing fixes are from another extension (https://marketplace.visualstudio.com/items?itemName=dotup.dart-data-class-generator) and not this one, so this would need to be filed and fixed at https://github.com/dotupNET/dart_data_class_generator.

My guess is it's because it parses the code itself and expects the line to start with `class` or `abstract class`:

https://github.com/dotupNET/dart_data_class_generator/blob/a0729d66adb29f6cd36c90d47a4bb90a198aaabf/src/extension.js#L1495
