### ISSUE TITLE
add sdk to path on windows not working cause the path is quoted

### ISSUE THREAD

**Issue by wildsylvan** [Dart-Code/Dart-Code#5051]
**Describe the bug**
dart and flutter cli cannot be found by windows powershell

**To Reproduce**
1. install the flutter sdk through the vscode flutter extension
2. click on add sdk to path

**Expected behavior**
after restarting vscode, windows powershell should be able to find the dart and flutter cli

**To Resolve**
removing the quotes (`"`) around the path added by the extension inside the path env variable fixes the issue. according to [this](https://serverfault.com/a/349216), paths inside the windows path env var shouldn't be quoted. they should instead use semicolons as delimiters. i can confirm that among all paths present on my machine (including ones with spaces), the dart/flutter's was the only quoted one

**Please complete the following information:**

 - Operating System and version: Windows 11 Pro 10.0.22631 Build 22631
 - VS Code version: 1.87.2
 - Dart extension version:  3.84.0
 - Dart/Flutter SDK version: Dart (3.3.2) / Flutter (3.19.4)
 - PowerShell version: 7.4.1

**Comment by wildsylvan** [comment]
see also: https://github.com/Dart-Code/Dart-Code/issues/4604#issuecomment-2020507722

**Comment by wildsylvan** [comment]
btw `dart collect diagnostic information` reports my windows version as: `on windows / "Windows 10 Pro" 10.0 (Build 22631)`, while it's `Windows 11 Pro 10.0.22631 Build 22631`. is it normal?

**Comment by DanTup** [comment]
> btw `dart collect diagnostic information` reports my windows version as: `on windows / "Windows 10 Pro" 10.0 (Build 22631)`, while it's `Windows 11 Pro 10.0.22631 Build 22631`. is it normal?

I see this too... The version nubmer for Windows 11 _is_ still 10, but I think this is a bit misleading. I've opened https://github.com/dart-lang/sdk/issues/55351 (that info comes from running `dart info` internally).

**Comment by DanTup** [comment]
@wildsylvan can you confirm exactly where you're seeing these quotes? I just used this command but the path looks correct both in Windows env variables dialog and in the terminal in VS Code:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/f6edfafb-aa33-471d-8863-bcc63905e72b)

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/e4cfad69-a5f6-4af1-8c15-b4c5d1e409a6)

**Comment by wildsylvan** [comment]
![image](https://github.com/Dart-Code/Dart-Code/assets/19886441/e2d76f88-8777-4114-9baa-3ada65851e64)
---
![image](https://github.com/Dart-Code/Dart-Code/assets/19886441/2b523402-4a95-4848-958f-d350f4854e11)
---
![image](https://github.com/Dart-Code/Dart-Code/assets/19886441/1714b948-cb25-42fb-8e40-750904a0d3c8)
---
![image](https://github.com/Dart-Code/Dart-Code/assets/19886441/3423c4db-ca1f-425f-b8e6-538bea8b0fb2)
---
### to see it from the dialog u have to click on edit text
![image](https://github.com/Dart-Code/Dart-Code/assets/19886441/1f27dab8-f5c4-4e62-830c-dd635cb7a7f5)
---
![image](https://github.com/Dart-Code/Dart-Code/assets/19886441/593dd4d8-703c-4f4b-9665-df275a4b9d87)

**Comment by DanTup** [comment]
Thanks, I can repro. We were deliberately adding extra quotes and I had a comment that it didn't work without them:

https://github.com/Dart-Code/Dart-Code/blob/b21778207141acd92b26703b942c639c3e18f36e/src/extension/commands/add_sdk_to_path.ts#L96-L97

However, I just removed them and it's working fine. Maybe something changed in newer versions of PoSh, I'm not sure - but I'm going to remove them since everything seems fine (even with spaces in the path) for me now.

**Comment by wassila2008** [comment]
Is it the same problem? ![IMG_20240901_195400.jpg](https://github.com/user-attachments/assets/848b6d59-e360-489c-b9ca-73a7367b3b5f)

**Comment by wassila2008** [comment]
The extension has been disabled

**Comment by DanTup** [comment]
@wassila2008 if your question is about "This extension has been disabled because the current workspace is not trusted" then no, that's unrelated to the issue described here.

The issue there is that the current workspace/folder you have open in VS Code is not marked as trusted (that is, you have not told VS Code that you trust the open folder), and the Dart extension is marked such that it will not load in an untrusted workspace because it may result in code from the workspace being executed.

To use the Dart extension you must be in a workspace that you trust. I think usually in an untrusted workspace there will be a notification or message in the status bar from where you can choose to trust the workspace. Alternatively, you can press F1 to open the command palette and run the "Workspaces: Manage Workspace Trust" command.

For more information on VS Code's workspace trust, see https://code.visualstudio.com/docs/editor/workspace-trust
