### ISSUE TITLE
Add support for "Go to Augmented" and "Go to Augmentation" commands + CodeLenses

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#5063]
(placeholder for release notes)

**Comment by DanTup** [comment]
This was added in ff99a8c6 but only shows up when the analysis server supports `dart/textDocument/augmented` and `dart/textDocument/augmentation`.

The commands are client-side, but the CodeLenses are added by the server (if we pass that we support these commands in the experimental initialization data).

**Comment by DanTup** [comment]
When adding an augmentation, a "Go to Augmented" CodeLens will appear that jumps to the symbol being augmented. A similar "Go to Augmentation" CodeLens will appear to navigate in the opposite direction.

When there are multiple levels of augmentation, you will see both CodeLenses on any intermediate definition as you can navigate in both directions.

https://github.com/Dart-Code/Dart-Code/assets/1078012/be038fba-5a64-4a96-b1ff-88d4ec032aa7

**Comment by jacob314** [comment]
Would be interesting to see this for the output of the json macro to make this even more concrete.

Fyi @jwren for visibility. Would be good for IntelliJ and VSCode to be consistent on this. High level I think using codelens for this is very useful and will make the macros feature much less magical to users.

I like that there is only a single "Go to Augmentation" link rather than multiple links one for each augmentation. That makes this less busy. 

Bikeshed topic: the "go to augmentation" and "go to augmented" links look self explanatory to me if somewhat verbose (although I am too familiar with the feature to be a good judge). 
Perhaps "Go to Augmentation" can just be "go to augment" to align with the `augment` keyword? Writing "go to" is a also a bit like writing "click here" so would be nice to avoid if it can be avoided without too much of a reduction in clarity.
Here is an example of how this is avoided in a somewhat similar case for an existing vscode extension:
![image](https://github.com/Dart-Code/Dart-Code/assets/1226812/14c03f30-234f-47ac-b9b7-8453ff65fd14)
My opinion on this is weakly held and it could also be reasonable to start with "Go to" and remove it once users become used to these being links.

We might also consider having the links say `1 augments` or `2 augments` if the common case is methods and classes have multiple augmentations. That is currently the case due to not merging the augmentation methods from multiple phases. 

Screenshot showing what happens today for the typical case of multiple augments for a method.
<img width="1614" alt="Screenshot 2024-04-11 at 8 40 21 AM" src="https://github.com/Dart-Code/Dart-Code/assets/1226812/a920b7db-ed02-46dc-88ef-cbcefdc34133">
This isn't quite the same as the common case as the common case for this is when `class Foo` doesn't define bar itself but there are multiple augmentations defining it.

**Comment by DanTup** [comment]
I also think they're a bit verbose, but I wasn't able to come up with something that seemed better.

> Perhaps "Go to Augmentation" can just be "go to augment" to align with the augment keyword? 

I feel like "augment" could be a bit ambiguous (does it go to the augmentation of us, or the thing we are augmenting?).

>  Writing "go to" is a also a bit like writing "click here" so would be nice to avoid if it can be avoided without too much of a reduction in clarity.

I also don't like the "Go to", but on its own "Augmented | Augment(ation)" don't seem very clear. Is this an indicator telling me that this thing is augmented? A label like "4 references" is more obvious, it's telling you that there are 4 references and you can assume if you click you might see them. But "augmented" doesn't tell you that this item is augmented, it tells you that this is an augmentation and it navigates you to the augmented definition.


> We might also consider having the links say `1 augments` or `2 augments` if the common case is methods and classes have multiple augmentations.

This is what we tried first (maybe you were out when we discussed). The problem with this was that in the search results VS Code would show the target lines without any context so it wasn't very clear what you were looking at (every target line basically looks the same). There's a video showing this at https://github.com/dart-lang/sdk/issues/54742#issuecomment-1983687148

**Comment by anderdobo** [comment]
On balance, as discussed and given previous explorations, I think the "Go to Augmented" and "Go to Augmentation" as implemented here are clear and specific. So this LGTM.

**Comment by jayoung-lee** [comment]
I like 'go to', as it clearly states the action and is consistent other actions like 'go to definition', 'go to declaration'. 

However, I think 'augmentation | augmented' could create ambiguity about the direction of navigation, especially for non-native English speakers.. Although it is already quite verbose, can we consider supplementing it with symbols like arrows?

**Comment by DanTup** [comment]
Here are some screenshots with various kinds of arrows ([from here](https://en.wikipedia.org/wiki/Arrows_%28Unicode_block%29)):

![Screenshot 2024-04-15 144930](https://github.com/Dart-Code/Dart-Code/assets/1078012/7bbe7e59-3aaf-439a-abf7-6404b0b4db86)
![Screenshot 2024-04-15 145022](https://github.com/Dart-Code/Dart-Code/assets/1078012/8a9df177-76c6-436c-b75a-7af635e17b71)
![Screenshot 2024-04-15 145052](https://github.com/Dart-Code/Dart-Code/assets/1078012/b047b257-8890-47ba-b045-777f170007b8)
![Screenshot 2024-04-15 145137](https://github.com/Dart-Code/Dart-Code/assets/1078012/d707113a-fc87-41d3-adfe-ad0c798d2d47)

I'm not sure how I feel about them (in particularly, the ones that are up against the pipe `|` that separates the CodeLenses (which we can't influence) look a little odd.

Any opinions?

**Comment by bwilkerson** [comment]
I'm not sure how much value they add. I think that would largely depend on the mental model the user has about augmentations and overrides, which might depend at least to some extent how we present the concept of augmentation in the documentation. If we draw diagrams showing augmentations in a chain (using arrows to represent the chain), then the arrows might seem more obvious. (That's my mental model; I just don't know how universal it will be.)

If we do keep the arrows, I'd prefer for us to use the left and right pointing arrows for augmentations, and to reserve the up and down arrows for override relationships. I always think of the inheritance structure as going up and down, and I like thinking of the augmentation structure going left and right in order to differentiate them.

**Comment by jayoung-lee** [comment]
Thanks for prototyping it!

I have to admit, the arrows make the code line look more cluttered than I expected. And because the arrowheads are small, the directionality can still be a little ambiguous..

> I'm not sure how much value they add. I think that would largely depend on the mental model the user has about augmentations and overrides, which might depend at least to some extent how we present the concept of augmentation in the documentation. If we draw diagrams showing augmentations in a chain (using arrows to represent the chain), then the arrows might seem more obvious. (That's my mental model; I just don't know how universal it will be.)

I agree with this now. Clear documentation that includes a visual diagram and an explanation of the terms 'augmented' and 'augmentation' would be sufficient to build the correct mental model :) Thank you!

**Comment by bwilkerson** [comment]
@MaryaBelanger

**Comment by DanTup** [comment]
Thanks for the feedback - I'll leave as-is (just "Go to ...") for now then :)

btw one thing that has slightly confused me is where we use `augment` vs `augmentation`. I've been using `augmentation` (as has much of the analyzer code) to mean the new definition being applied to the "augmented" entity. However for imports we use `import augment` and I feel like I always want to write `import augmentation`.

(slightly related, maybe with these new concepts it would be a good opportunity to decide on a way to define some descriptive hovers we could apply to keywords? - https://github.com/dart-lang/sdk/issues/50085)
