### ISSUE TITLE
"Find all references" on invocation of a getter/setter only returns other references as a get (or set)

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#5065]
**Describe the bug**
If you take this example:

```dart
  void markDirty() {
    _needsRefreshFromBackend = true;
  }

  bool _needsRefreshFromBackend = false;
```

and you select "Find all References" on the definition of the property `_needsRefreshFromBackend` you get all usages of this property using it as a setter or a getter. 
If you do the same on its usage inside `markDirty` you only get locations where the property is used as a setter.

if you do the same at a place where it is used as a getter you only get the locations where it is used as a getter.

This might be semantically be correct but probably not what the user wants or expects as normally they want to see really all places where a property is used.

Something similar can be observed if you use "Find all references" on methods in abstract classes vs where they are implemented/extended although there it might make some sense. However, I recall having had situations where I wondered why certain places were sometimes shown and otherwise not.

**Comment by DanTup** [comment]
I can see an argument for both ways here. I think the ideal would be that in the results we can group together read and writes so if you wanted to see all the places calling a setter, you can. However, LSP/VS Code APIs don't allow for any kind of grouping like that.

So, we need to decide whether to group together getters/setters for "Find References" (and perhaps whether that changes for explicit getter/setter versus implicit getter/setter and/or getter/setter that just directly access a field versus being completely unrelated code).

I did some testing with TypeScript to see how that behaves, and it does lump them together, even for explicit getter/setters:

```ts
class Person {
	public get age() { return 1; }
	public set age(_: number) { }
}

const p = new Person();
p.age = 1;
console.log(p.age);
p.age = 2;
console.log(p.age);
```

Find References here on a call to the setter includes everything:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/e3ca4f80-6e40-4c42-8478-8dc2786b9d86)

@bwilkerson any opinions on this? My feeling is that we should probably include both and if you really want to search for calls to a setter, you can make it an explicit getter and Find References on that. That would be less convenient than it is today, although it also makes general search for all uses of a field more convenient.

**Comment by escamoteur** [comment]
My point for grouping them is that only if a property is used in really many places a separation might help and because you always see a small extract in the result it is easy to spot which is which. maybe we could order the getter usages before the setters if we can't group them?
IMHO overlooking a usage is far more dangerous

**Comment by DanTup** [comment]
I don't think we have any control over the ordering - it seems like VS Code groups them by file, and then orders them by the order they are in the file.

I agree that missing usages is bad. You can currently use F12/Go-to-Definition to jump to the field and then find references there, but I'm not sure if that distinction is obvious/expected.

**Comment by bwilkerson** [comment]
> My feeling is that we should probably include both ...

Agreed. Dart has been moving, for some time, toward a view of 'properties' rather than getters, setters, and fields. I believe that's been the approach we've taken everywhere in the tooling as well.

I also agree, though, that it would be useful for the IDE to be able to show references grouped in other ways. Perhaps we should open an issue with VS Code asking for some kind of affordance in the UI for being able to switch the way these lists are shown. If LSP allowed for a 'reference kind' (such as [getter, setter, direct field access], or even [invocation, tear off] for methods), then I think it might well benefit more languages than just Dart.

**Comment by DanTup** [comment]
I've opened https://github.com/microsoft/vscode/issues/210084 about improving the APIs in VS Code.

While looking through the code I realised that this was already handled, but the LSP handler was missing some code that the legacy protocol had to go from `PropertyAccessorElement`s to the `variable` before finding references, so the fix is trivial :-)

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/ea830ef8be221a8b3b8d5901d50d0d4dbaecb0e4. The fix is in the analysis server so will show up in a future SDK release.
