### ISSUE TITLE
Unable to add debug breakpoints in class extensions.

### ISSUE THREAD

**Issue by mathr13** [Dart-Code/Dart-Code#5074]
**Describe the bug**
Not able to add a debug breakpoint in any of the methods defined inside an extension of a class. However, the methods that are defined in the original class are accepting breakpoints.
Also, Adding a breakpoint at a certain line does add the breakpoint there, but on the UI it is shown as added on some other random line number.

**To Reproduce**
1. Run any Flutter application i debug mode.
2. Try to add a breakpoint in any of the methods defined inside of a class extension.

**Expected behavior**
Breakpoint should pause the running code at that very point/line.

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: MacOS Sonoma (14.4.1)
 - VS Code version: 1.88.1
 - Dart extension version: v3.86.0
 - Dart/Flutter SDK version: 3.16.9

**Comment by mathr13** [comment]
What I've observed is that this issue has only started to come after updating to latest macOS. Never faced this issue before that.

**Comment by DanTup** [comment]
Are you able to provide a sample project that you have confirmed this occurs in (ideally create a new project with `flutter create` and then provide the exact change you made to add the extension). Can you also include a log file captured with this project:

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Start the debug session
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Please be sure to capture the log using the code you share, so that the source in your log file matches up the version I can debug with.

Thanks!
