### ISSUE TITLE
Include lint documentation in completion in analysis_options.yaml

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5086]
**Is your feature request related to a problem? Please describe.**
I have a relatively big `analysis_options` file in my company. And when managing it I always have to open a browser to see what some specific lints are and copy the right name.

**Describe the solution you'd like**
I'd like for the `analysis_options.yaml` file to have an autocomplete for `rules` under `linter`, and possibly to look for active `rules` to suggest under `analyzer -> errors` and maybe `analyzer -> language`.

As well as possibly a hint on what the rule is about with maybe the link to the docs.

**Comment by DanTup** [comment]
There already is completion for lint names:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/f0665810-1113-4210-990e-3d74485ac50d)

However because of some quirks with the yaml parser, in some cases it won't show up. It seems to work reliably for me if there are already some items listed though.


> As well as possibly a hint on what the rule is about with maybe the link to the docs.

Agreed - it'd be nice to see the docs here like we do with other completions. This shouldn't be difficult.


> and possibly to look for active rules to suggest under `analyzer -> errors` and maybe `analyzer -> language`.

That sounds reasonable to me too - could you file a separate issue for that? (actually at https://github.com/dart-lang/sdk would be better, since it's analysis server work). I'll rename this one for the dartdocs and leave it here as that's a quick fix.

Thanks!

**Comment by DanTup** [comment]
https://github.com/Dart-Code/Dart-Code/assets/1078012/62425e52-ff99-4d10-a7ca-52b02c4830b1

**Comment by DanTup** [comment]
Docs in completion is done in https://github.com/dart-lang/sdk/commit/6127f10c228a904a949b43df3cdf4b2053d16ad9, which ships in a Dart/Flutter SDK release.

The other issues here now have their own SDK issues at https://github.com/dart-lang/sdk/issues/55592 and https://github.com/dart-lang/sdk/issues/55593.
