### ISSUE TITLE
An unexpected behavior in the analyzer (I think) - Provider FAILED

### ISSUE THREAD

**Issue by diegocatalao** [Dart-Code/Dart-Code#5088]
**Describe the bug**
My VSCode can no longer parse my Dart code. It looks like something is blocking the task. When I try to save a dart file I get the following error: `Error running Organize Imports: File is not analyzed`.

Extension Host Output:
```
2024-05-02 11:27:57.067 [error] [Dart-Code.dart-code] provider FAILED
2024-05-02 11:27:57.068 [error] {"code":"GET_FIXES_INVALID_FILE","message":"Error during `edit.getFixes`: invalid file."}
2024-05-02 11:27:58.062 [error] {"code":"UNKNOWN_REQUEST","message":"Unknown request"}
```

I checked the memory and CPU used and they are high: CPU: 147.4%, Memory: 444 MB

**To Reproduce**
Using the VSCode latest Version: 1.88.1 (Universal), Commit: e170252f762678dec6ca2cc69aba1570769a5d39 and Dart Analyzer `1.33.4`.

**Expected behavior**
The analyzer should be fast enough to analyze the code but it doesn't.

**Screenshots**
<img width="1313" alt="Screenshot 2024-05-02 at 11 17 49" src="https://github.com/Dart-Code/Dart-Code/assets/81654879/c099fd11-68cf-4dbd-9bcb-f875afa49804">
<img width="1334" alt="Screenshot 2024-05-02 at 11 18 26" src="https://github.com/Dart-Code/Dart-Code/assets/81654879/0a1f221b-7e57-442b-b1a7-996adfaae520">

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
MacOS M1 14.4.1

 - VS Code version:
Version: Mac 1.88.1.

 - Dart extension version:
 1.33.4

 - Dart/Flutter SDK version:
Dart: 3.2.3
Flutter: 3.7.11

 - Target device (if the issue relates to Flutter debugging):
MacOS

**Comment by DanTup** [comment]
@diegocatalao was this a one-off, or does it reproduce after restarting VS Code?

If you can reproduce, is it only for this project or all?

It appears you're currently using the legacy analyzer protocol - is this deliberate? If not, I would ensure this option is unticked:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/308d9532-0e85-483a-9521-3dea2e43559b)

If there's a reason you're using this, I'd be interested in the details (it's not longer supported in the latest Dart extension when using the latest SDKs because of breaking changes). Thanks!

**Comment by diegocatalao** [comment]
Olá, @DanTup!

I changed the flag as you said and I still have the same error. I have enabled the legacy parser in an attempt to resolve this issue. Disabling it was also unsuccessful in returning normality. If you need more information, let me know.

Many thanks for the reply.
