### ISSUE TITLE
The SDK configured in dart.flutterSdkPath is not a valid SDK folder.

### ISSUE THREAD

**Issue by hyufdd** [Dart-Code/Dart-Code#5115]
I just opened up my first flutter project on VSC and a box popped up in the corner. It read "The SDK configured in dart.flutterSdkPath is not a valid SDK folder." How do I fix this?

**To Reproduce**
1. Open new flutter project

**Expected behavior**
No messages

 - Operating System and version: macOS Sonoma
 - VS Code version: Mac 1.89.0
 - Dart extension version: v3.88.1
 - Dart/Flutter SDK version: I think 3.4.0

<img width="1440" alt="SCR-20240521-jkjz" src="https://github.com/Dart-Code/Dart-Code/assets/142684056/20139554-6df1-40f0-8a4a-52c78101585f">

**Comment by DanTup** [comment]
If you click the "Open Settings File" button on the message, it should take you to your settings where you can see what `dart.flutterSdkPath` is set to and either update it, or remove it.

If you only have one Flutter SDK, then I would suggest just deleting the setting, since it appears from your screenshot that we located the Flutter SDK automatically, despite the incorrect path there.
