### ISSUE TITLE
Debug breakpoints not triggering on iOS devices

### ISSUE THREAD

**Issue by chrisdrobison** [Dart-Code/Dart-Code#5132]
**Describe the bug**
Setting debug breakpoint in either VSCode or IntelliJ doesn't get triggered during a debug session.

**To Reproduce**
1. Set a debug breakpoint
2. Debug the project

**Expected behavior**
The debug breakpoint breaks at the specified spots.

**Please complete the following information:**
[debug.log](https://github.com/user-attachments/files/15516281/debug.log)

 - Operating System and version: MacOS Sonoma 14.5
 - VS Code version: 1.89.1
 - Dart extension version: 3.90.0
 - Dart/Flutter SDK version: 3.22.1
 - Target device (if the issue relates to Flutter debugging): iPad Pro 11" 4th gen, iOS 17.5.1

**Comment by chrisdrobison** [comment]
Here are the logs with the debugger statement: https://drive.google.com/file/d/1hAOd7JPh_RIXXLB1GdcT0iiCW0dMa6tv/view?usp=sharing

That interesting thing I noticed with this session is that it started out showing that the breakpoint couldn't be found. But, somehow, in the middle of the session, either because I added the debugger(); statement or something, the breakpoint indicator turned red indicating I could break there now. I'll see if I can reproduce this with a sample project.

**Comment by chrisdrobison** [comment]
I was able to reproduce this issue from a the base `flutter create` app. The issue does seem a bit inconsistent. Sometimes it breaks, sometimes it doesn't depending on the session.

**Comment by DanTup** [comment]
> But, somehow, in the middle of the session, either because I added the debugger(); statement or something, the breakpoint indicator turned red indicating I could break there now. I'll see if I can reproduce this with a sample project.

Right now, breakpoints may appear grey ("unverified") until the script/function they are in is compiled. There are ongoing discussions about forcing compilation of scripts/functions when breakpoints are added to change this (because it can be confusing), but in general, a grey breakpoint does not mean "will not be hit", it can also mean "the location is not yet verified because the script has not been compiled".

@chrisdrobison are you able to capture a recording showing the issue (while capturing logs, so the log/video match)? Looking at the latest log you sent, the pause event from the VM appears to be attached to the breakpoint you set (and not the `debugger()` statement).

Is it possible that the breakpoints are working, but them being grey just makes it seem like they're not going to work?

**Comment by chrisdrobison** [comment]
Yeah, so I can't reproduce this any more. Must have been some weird fluke.
