### ISSUE TITLE
Reload the Flutter sidebar from VS Code when the Flutter version changes

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#5138]
I was on an older version of Flutter (stable) and noticed that the sidebar did not reload when I switched to the latest Flutter main branch. I noticed because there are flutter sidebar features on Flutter main that are not present on the current stable. If VS Code knows when we get a new flutter version (does it?) we should reload the sidebar.

**Comment by DanTup** [comment]
>  If VS Code knows when we get a new flutter version (does it?) we should reload the sidebar.

When the version changes, there should be a toast notification pop up in the bottom right saying something like "Your SDK has been updated" and a **[Reload]** button. Pressing that will reload everything (because we need to restart the analysis server, DevTools server, DTD etc. when the SDK changes).

Do you know if you got that prompt?

**Comment by kenzieschmoll** [comment]
I do get a prompt, I see it now. It isn't super discoverable - I wonder if we could do something to prompt inside the sidebar? Although that has its own discoverability issues too. Closing this issue then.

**Comment by DanTup** [comment]
Yeah, unfortunately the toast notifications aren't always noticed, but I don't think we have any significantly better options right now. The issue of reloading isn't isolated to the sidebar, lots of things could be broken until you reload, but I don't want to do it automatically because it's quite disruptive (you might be typing in the editor while `flutter upgrade` was running for example).
