### ISSUE TITLE
Workspace name/folder as macro for log

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5154]
**Is your feature request related to a problem? Please describe.**
I received instructions to set the extension to save log files. E.g.:

```json
"dart.flutterRunLogFile": "C:\\Dev\\Logs\\flutter_run.txt",
"dart.vmServiceLogFile": "C:\\Dev\\Logs\\vm_service.txt",
"dart.dapLogFile": "C:\\Dev\\Logs\\dap.txt",
```

When looking for these in VSCode settings, I found out about `${name}` being supported inside the path as a macro for the debug session name.

However, I was also instructed to set these settings for each workspace so that different workspaces don't conflict with each other. Which is a little too verbose when having lots of projects that you'd like to log.

**Describe the solution you'd like**
I'd like for the extension to support `${folder}` or `${workspace}` or similar so that I can create a path like `~/dev/logs/${workspace}/${name}`.

**Describe alternatives you've considered**
Manually creating an inner folder for each workspace and defining it to the workspace settings.

**Additional context**
I was also reminded that some workspaces in VSCode can be unnamed. So in this case _I believe_ the files could be simply left under `~/dev/logs/${name}` as for my example.

**Comment by DanTup** [comment]
In the next version you can use `${workspaceName}` and we'll insert the value from `vscode.workspace.name` (or if that's not set, `"unnamed-workspace"` - although I think that only happens if you have no folders open).

The values VS Code gives us are:

- The name (without the extension) of the current `.code-workspace` file (if there is one)
- The name of the folder that's open (if not a workspace)
- "untitled workspace" when you have multiple folders open but not saved as a workspace file

Here's an example from my logs folder after opening a few projects (some of which are code-workspaces):

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/162f72a6-e4a3-49e8-9e04-70ac97049cc6)

**Comment by FMorschel** [comment]
Hi! Not sure if I'm doing something wrong, but I tested with:

```
[...]\\logs\\${workspaceName}\\${name}\\file.txt
```

And got:

```
[...]\logs\entrega_sunsoft\${name}\file.txt
```

Like, it didn't replace `${name}` with anything.

## Separate

Also, here are all the files I'm setting:

![image](https://github.com/user-attachments/assets/01a4ef54-dc0a-4249-bbd8-787566c5a283)

Although some of the markdown hints you changed it so it would show that `${workspaceName}` would work only `flutterTestLogFile` does show that we can also use `${name}`:

![image](https://github.com/user-attachments/assets/f72b3112-55f4-4bbe-8e15-52f88409d126)

And the `extensionLogFile` shows neither.

![image](https://github.com/user-attachments/assets/fa63a05e-9bea-46fb-a396-0e49503f02d5)

I would be willing to fix these markdowns with a PR but again, I'm not sure I could fix the `${name}` since I'm not even sure what it would show in my case. I guess that this would show, but maybe I don't get it:

![image](https://github.com/user-attachments/assets/353f845d-b80c-4339-8095-e6dda0683ea0)

**Comment by FMorschel** [comment]
I saw you created https://github.com/Dart-Code/Dart-Code/issues/5184 relating to the first part of my last comment here. I created #5185 to fix the descriptions I also mentioned above.
