### ISSUE TITLE
Unable to debug android app with remote devices

### ISSUE THREAD

**Issue by emircanerkul** [Dart-Code/Dart-Code#5161]
Hi, I was using remote ssh as my dev environment and using devices via ssh port forwarding.

I able to connect my devices also flutter run -d {id}, also works good installs android apps to my emulator but i can not debug flutter apps via extension. It does not show these devices.

<img width="898" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/11430795/cb533571-4dd4-4d37-baed-0568682bd900">

**Comment by emircanerkul** [comment]
<img width="1158" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/11430795/8ee61943-5a34-4ac7-9476-9556577df146">

**Comment by DanTup** [comment]
Can you confirm that the devices show up when running `flutter devices`, and that your project is set up for Android (has an `android` folder)? Thanks!

**Comment by emircanerkul** [comment]
Hi @DanTup thank you for the tip.

Indeed there was problem with flutter daemon. I was missing one step regarding port forwarding. Tools are really incredible btw, thank you for all dart/flutter community.

What i achieved with ssh port forwarding is, using vscode in my mac device to connect virtual machine linux dev env within windows device that able to access emulator in host machine. Just WOW!

Vscode automatically forward flutter devtools into my mac and when i hover or select element in the mac browser it immediately highlight the element in android emulator without any delay.

> Here is the how to: https://stackoverflow.com/questions/72954102/developing-flutter-apps-using-vscode-remote-development

BTW I can see and use all adb devices with adb port forwarding but now i wonder how can i see/forward windows desktop emulator?

**Comment by DanTup** [comment]
Great, glad to hear it's working now!


> how can i see/forward windows desktop emulator?

I'm not sure I understand the question. When you run apps on a desktop, it's not an emulator but just a native app. Are you trying to see the desktop version of an app from another machine? If so, I don't know of a way to do that without using some kind of remote desktop app.

**Comment by emircanerkul** [comment]
I see, yea looks that is a bit more complicated/different scenario than using adb.

Basically currently,
Linux VM (compiles android via cli) -> sends apk/make connection -> emulator via adb port forwarding

Why not
Linux VM (compile windows app via c++) -> sends compiled exe/make connection -> windows machine via ???
or
Linux VM (compile mac app via ???) -> sends compiled pkg/make connection -> mac machine via ???

??? are big questions/efforts.

**Comment by DanTup** [comment]
I don't think it's possible to build a Windows Flutter app from Linux, because it uses a lot of the Visual Studio/Windows SDK tools (and the same goes for Mac - I don't think you can build Mac apps from your Linux machine).

It would certainly be nice to be able to work from one machine and run an app on different desktop platforms, but I do think that would be a huge effort - and something that would likely involve changes to Flutter tooling (not just something here in the VS Code extension).

There's an existing feature request in Flutter which I think is essentially for this (it talks about using a remote Mac for iOS dev, but I think it's largely the same request, which is to support building on a remote device): https://github.com/flutter/flutter/issues/33037

I think the original issue here was solved so will close this, but let me know if that's not the case. Thanks!
