### ISSUE TITLE
Breakpoint Line Numbers incorrect/changing/been added several times

### ISSUE THREAD

**Issue by theSonGoku1991** [Dart-Code/Dart-Code#5193]
**Describe the bug**
I mistakenly posted this bug here https://github.com/microsoft/vscode/issues/220550 before, in which you can find all needed information, but feel free to ask further in case you want everything to be documented here as well.

**To Reproduce**
For me, it happens while "just" adding breakpoints, but usually after the emulator aleady runs for some time.

**Expected behavior**
- Add the exact number the breakpoint has been added to ONCE (currently occasionally happens twice/three times)
- Do not change the number the breakpoint is on when removing and re-adding them
- Add the breakpoint to the correct line (happens that the breakpoint will be added to totally random other lines)

**Screenshots**
You find an example video covering some of these issues in the linked issue.

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Windows_NT x64 10.0.19045 (running Windows 10)
 - VS Code version: win 1.91.1
 - Dart extension version: 3.92.0
 - Dart/Flutter SDK version: 3.92.0
 - Target device (if the issue relates to Flutter debugging): Android Emulator
 
 In case you need further information, just let me know!

**Comment by DanTup** [comment]
Based on the report and the video, my feeling is that this issue is one that was described at https://github.com/dart-lang/sdk/issues/55268#issuecomment-2084925837 and fixed by https://github.com/dart-lang/sdk/commit/5ed21576fecd39cb83811bd8191ac23c07e02490.

The fix is in the debug adapters that live in the SDK, so will show up in a future Dart/Flutter SDK release. The fix is already in the beta branches, but has not yet made a stable release.

If you're able to test with the beta branch, I would be interested to know if you still see any problems. Thanks!

**Comment by theSonGoku1991** [comment]
@DanTup I switched to the beta channel and did not encounter any of the issues I mentioned before anymore, so I think this one is done! :) It is so great I can finally rely on the debugger again.

**Comment by theSonGoku1991** [comment]
@DanTup I switched to the beta channel and did not encounter any of the issues I mentioned before anymore, so I think this one is done! :) It is so great I can finally rely on the debugger again.

**Comment by DanTup** [comment]
Great, thank you for testing and letting me know! :)
