### ISSUE TITLE
Refine:  make the running panic stops at user code zone but not SDK/system code zone

### ISSUE THREAD

**Issue by dbsxdbsx** [Dart-Code/Dart-Code#5222]
### Env
Win10, VscodeV1.92 ,Dart V3.94.0

### Issue
The running panic would inevitably occur when debugging a dart/flutter project code. And usually, as in the below image, the panic err msg is not readable, and not easy to find the real issued code place:
![image](https://github.com/user-attachments/assets/2bff2993-5bb3-4c81-8bf6-0ad0f8dba470)

And you see that I am using `Debug my code+ packages +SDK` mode, because for the other modes, they would not even stop at any issued place but only pause the app.  And under `Debug my code+ packages +SDK` mode,  I found it still can't jump back to the user code zone after pressing `step out` for over 10+times.

In addition, this issue would make debugging more exhausted if the err came from FFI through anthor language, say Rust as in my case.

In fact, I've seen this behavior for a long time, I wonder why no one has ever mentioned or why it is not refined to make it more coder-friendly.

My vscode  `launch.json` is like this:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "proxy",
            "request": "launch",
            "type": "dart"
        },
        {
            "name": "proxy (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile"
        },
        {
            "name": "proxy (release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release"
        }
    ]
}
```

**Comment by DanTup** [comment]
It looks like there is no "user code" in the call stack here:

![image](https://github.com/user-attachments/assets/653738d3-8fbf-44b5-af21-7216b06ea03f)

So I don't think this is something that can be improved here in the VS Code extension, I think the VM/debugger would need to provide the original frames (although I don't know whether it could, it may depend on exactly what's going on here).

Could you re-file this at https://github.com/dart-lang/sdk and include a code sample that triggers this exception? And post the link back here.

Thanks!

**Comment by DanTup** [comment]
When I test with your example and have "Debug my code", it correctly breaks in my user code:

![image](https://github.com/user-attachments/assets/758c6cb6-802d-4ead-9893-d5e0e4ae0bef)

However if I enabled "Debug my code + packages + sdk" then it breaks at the source of the assertion like in your screenshot.

This is the expected behaviour but I'm not sure if it matches what you see. When you enable debugging in packages+sdk, you are choosing for the debugger to break inside non-user code.

If enabling just "Debug my code" does not break you in your user code (like in my screenshot), there may be a bug. Can you confirm if that's the case, and if so the precise steps to reproduce that? What I did was:

- `flutter create dartcode_5222`
- `cd dartcode_5222`
- `code .`
- Paste your content over `lib/main.dart`
- Run the app (on Windows device)

My debug settings were already set to "Debug my code", but if yours are not you might need to change, and then restart the debug session.

**Comment by dbsxdbsx** [comment]
I got the same expected result as you did when `Debug my Code` is turned on for this simple example.
I think it is time to close this issue temporarily,  but I would reopen it if a similar issue occurs but not as complex as I stated in the very 1st thread.

**Comment by DanTup** [comment]
I think the difference in your first example is that there is no user code in the stack at all, however I don't know what the original code was to reproduce this. If you're able to provide a code sample that recreates that situation, I could see if there's anything obvious - but otherwise it may be a question for the Dart VM team.

**Comment by dbsxdbsx** [comment]
> I think the difference in your first example is that there is no user code in the stack at all, however I don't know what the original code was to reproduce this.
Thanks your effort.

Indeed, it is also an issue, though the core code is due to the rust code through FFI. I would reopen it if I found one that is not complex(The FFI code is generally hard to understand, which is not a typical case to show here (I take Flutter_rust_bridge v2 package to generate the FFI code).
