### ISSUE TITLE
DevTools Performance page fails to load + other issues on Flutter master when 'version' file is missing

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#5226]
![Screenshot 2024-08-20 at 12 23 38 PM](https://github.com/user-attachments/assets/a5251f1f-64a4-418a-86bd-9f08c13c604c)

Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.6.0

Dart extension: v3.95.20240801
Flutter extension: v3.95.20240801

**Comment by DanTup** [comment]
I'm not able to reproduce this:

![image](https://github.com/user-attachments/assets/2eb53468-2f2c-428b-b5c5-d8d18a441766)

Looking at the code, the only place that ID appears is here:

https://github.com/Dart-Code/Dart-Code/blob/cecd4b51e2276b0877cbed29e62b088fff04eae9/src/shared/constants.ts#L176

That ID is used only when there is no Flutter SDK version, or it is less than 2.3.1. This makes me think we've failed to get your Flutter SDK version (which actually will probably affect many things, because we'll treat it like the oldest version of Flutter).

Which branch of Flutter are you on? I filed https://github.com/flutter/flutter/issues/142521 a while back that sometimes Flutter's main/master branch deletes the `version` file and it leads to issues like this. I did some digging into why it happens (and only for main/master) and noted them in the issue, although I don't know enough to know what the correct fix is.

If you're _not_ on `master`/`main` and still seeing this and have confirmed there is a `version` file in your repo, then it may be something else.

**Comment by kenzieschmoll** [comment]
This was likely the issue. I have the version file now, but when I pulled from master again and then ran `cat version` the version file was missing. 

Instead of defaulting to 'legacy-performance' when the version is not found, can we revert to 'performance' instead? It seems enough time has gone by that it would be better to break people on a really old version of Flutter rather than people on the bleeding edge.

**Comment by DanTup** [comment]
> Instead of defaulting to 'legacy-performance' when the version is not found, can we revert to 'performance' instead?

We can, although a lot of stuff is broken in this mode (the sidebar won't be shown, we'll use the legacy DAPs that aren't being maintained, we won't start DTD). Maybe treating a missing / 0.0.0 version as 999.999.999 would actually be the best option (it's most likely Flutter master, which probably has all of the newest stuff), although I feel like we really need to fix that issue too 😄

I'll do some testing - if we're going to do _something_ here in the meantime, it would be best to handle more than just this page.

**Comment by DanTup** [comment]
I pushed two fixes for this:

The first will use a magic version number (999.999.888) when a Flutter version file is missing so that we default to enabling new functionality instead of disabling.

The second is when we force Flutter to initialize by calling `flutter doctor` (because - for example - the Dart SDK is missing), we will now run `flutter --help` immediately afterwards, since in my testing, `flutter doctor` can cause the `version` file to be deleted, and `flutter --help` causes it to come back. This is a hack until https://github.com/flutter/flutter/issues/142521 is fixed, but I think it will reduce the chances of hitting this (and this fix results in the _correct_ version number, rather than us using the magic version number).
