### ISSUE TITLE
DevTools is blank when several tools are open

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#5229]
Repro steps:
1. Open the Flutter sidebar in VS Code. You do not need to be connected to a debug session.
2. Open all of the available DevTools screens. Both times, when I opened the 5th screen, it just showed a blank page. It did not matter what order I opened the screens in.

![Screenshot 2024-08-22 at 1 23 19 PM](https://github.com/user-attachments/assets/101f405c-364d-4e6e-94db-688e34f9ef22)

**Comment by elliette** [comment]
Didn't see this had already been filed! If it's any help, here is a recording I took of the same issue:

![devtools_panels](https://github.com/user-attachments/assets/38e3abb4-680d-415f-97e2-bf4f9392861d)


I'm on Dart-Code v3.95.20240821 (pre-release)
Flutter version: 3.25.0-1.0.pre.94 • channel master

**Comment by DanTup** [comment]
I can repro this, but also outside of VS Code... If I open 5 DevTools windows in the browser, the next one just stalls. If I close an existing one, then it continues to load.

So I think this is a DevTools (or DevTools server) issue. Is there some restriction in incoming requests to the server or something? 🤔

**Comment by DanTup** [comment]
Or is this a client limit - Chrome restricting the number of open connections to a single host, and maybe our WS/SSE connections are tying them up?

https://issues.chromium.org/issues/40180988

**Comment by DanTup** [comment]
I did some more testing of this, and I think it's the SSE causing it. I think WebSockets might not count towards the limit (at least, I can open 10+ web socket example pages and they all connect), but SSE is tying up connections while it sits waiting for messages from the server.

An answer on SO suggests that using HTTP2 may avoid the issue (since many requests can be multiplexed over a single connection), however it's not clear to me what's involved in making the DevTools server use that.

I suspect the easiest option may be to switch from SSE to WS (and this may also solve issues for some web hosts like IDX), but I don't know the scale of that.

I've refiled this at https://github.com/flutter/devtools/issues/8298 since I think the work here will all be in DevTools.
