### ISSUE TITLE
Dart language server crashes on startup

### ISSUE THREAD

**Issue by cvharris** [Dart-Code/Dart-Code#5234]
Hoping I can get some clues on what might be the issue or new ways to troubleshoot this. Unable to reproduce on another computer but after recently running `flutter pub get` the Dart language server no longer boots up and always crashes with the same error:

```
Socket error: NoSuchMethodError: Class 'WillRenameFilesRegistrations' has no instance getter 'options'. Receiver: Instance of 'WillRenameFilesRegistrations' Tried calling: options
```

The same code and dependencies on other computers with the same versions of OS and VSCode works just fine. Tried upgrading VSCode, turning off all other extensions, upgrading MacOS, restarting the computer, reloading the window, etc. It just always crashes immediately when enabling or starting the extension. This kills all intellisense and typeahead features.

In the DevTools there's no stacktrace that points to a file from the extension, though the notification clearly says the error is coming from Dart.

<img width="478" alt="Screenshot 2024-08-26 at 12 17 49 PM" src="https://github.com/user-attachments/assets/9f298c25-2e56-4a0d-864a-aba47d86df79">

 - Operating System and version: 2019 Intel MacOS Sonoma 14.6.1
 - VS Code version: 1.92.2
 - Dart extension version: 3.94.0
 - Dart/Flutter SDK version: 3.5.1/3.24.1

**Comment by DanTup** [comment]
@cvharris are you just running a standard version of the server from the SDK? The error looks quite strange, that class is defined here and certainly has an `options` getter:

https://github.com/dart-lang/sdk/blob/3.5.1/pkg/analysis_server/lib/src/lsp/handlers/handler_will_rename_files.dart#L94-L100

I would try enabling the [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) to see if there is any more info or a stack trace that might help. Otherwise, anything you can do to help me reproduce the issue here would help.

Does it occur only on a specific project, or on all?

**Comment by cvharris** [comment]
Yeah it was an error from the SDK and it occurred in all projects on this device. The issue must have come up from the flutter upgrade process, not `pub get` as I thought.

I was able to fix the issue by simply deleting the `flutter` directory with the SDKs in it and reinstall it from scratch.

**Comment by DanTup** [comment]
It's definitely odd. If you see it again, please try to get an instrumentation log as noted above - that might help understand what's wrong. I don't currently have any plausible explanations for the error. Thanks!
