### ISSUE TITLE
"Performing refactor..." toast for "Move class to file"

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5235]
**Is your feature request related to a problem? Please describe.**
When using the "Move class to file" refactor I see no indication that it is running even when it takes some seconds to finish (probably figuring out dependencies for imports and such).

**Describe the solution you'd like**
I'd like a toast to show the user something is happening and if something went wrong.

**Additional context**
See https://github.com/Dart-Code/Dart-Code/issues/5218.

**Comment by FMorschel** [comment]
Do you believe that this issue is related to the experimental refactor not showing progress indication as well (coming from https://github.com/dart-lang/sdk/issues/56855)?

**Comment by DanTup** [comment]
Yeah, probably. For reasons I don't yet understand, it seems like the progress notifications just aren't showing.

**Comment by DanTup** [comment]
Turns out, they do show. But as status bar notifications:

![image](https://github.com/user-attachments/assets/d1b59b73-34b0-4901-8876-068841ad8d91)

I've opened https://github.com/microsoft/vscode-languageserver-node/issues/1567 about supporting toast notifications, and I will add support for the status bar notification for these new refactors in the meantime.
