### ISSUE TITLE
Improve error message for Linter warning: lower_case_with_underscores / dart(file_names)

### ISSUE THREAD

**Issue by Yegair** [Dart-Code/Dart-Code#5270]
**Is your feature request related to a problem? Please describe.**
The problem is that sometimes when creating a new file, one might type in an uppercase character by accident. Dart-Code then immediately shows the `lower_case_with_underscores` warning. However, fixing the issue can be rather tricky, because VSCode doesn't want to change its internal cache of file names, when the only thing that changes about the file name is the casing.

For example create a new file `test.dart` with the following contents:

```dart
// test.dart

part 'test_part.dart`;
```

Then create another file `test_Part.dart` (intentionally using an uppercase `P`):

```dart
// test_Part.dart

part of 'test.dart';
```

The linter will immediatly recognize the problem and highlight it:

```dart
// test_Part.dart

part of 'test.dart';
^^^^
The file name 'test_Part.dart' isn't a lower_case_with_underscores identifier.
Try changing the name to follow the lower_case_with_underscores style.
```

Now change the file name in VSCode to `test_part.dart` to fix the problem.
Notice how Dart-Code still highlights the problem, although it should be fixed.

```dart
// test_part.dart

part of 'test.dart';
^^^^
The file name 'test_Part.dart' isn't a lower_case_with_underscores identifier.
Try changing the name to follow the lower_case_with_underscores style.
```

The problem has been analyzed thoroughly in https://github.com/Dart-Code/Dart-Code/issues/3236 and the issue seems to be the internal file-name cache of VSCode. Also a solution that works reliably has been found: https://github.com/Dart-Code/Dart-Code/issues/3236#issuecomment-1407740775

> I managed to fix the issue by inserting an underscore at a random location in the file name, like button_s.dart. After this the warning disappeared. I then closed VSC, then reopened it, and renamed the file again back to buttons.dart. And the warning did not come back.

So the fix is for example to rename `test_part.dart` -> `test_p_art.dart` and then close/restart VSCode and again rename it back `test_p_art.dart` -> `test_part.dart`. Now VSCode has updated its internal cache, because a change was made that was not just an uppercase -> lowercase change.

**Describe the solution you'd like**

It would be great to have a hint in the error message that shows up, that helps to fix the issue. Maybe a link to some small documentation snippet or something in this direction.

It took me 30 minutes to figure out what the problem was and how to fix it, because the solution that I have linked did not show up at the top of the Google search results and when I found it, it took a while to read through the comments to find the solution.

**Describe alternatives you've considered**
I don't think there is a good alternative, besides VSCode changing its weird behaviour regarding file name caching. For example offering a quick fix will probably not work, since one has to restart VSCode to make the fix work.

**Additional context**

<img width="718" alt="Screenshot 2024-09-16 at 17 01 17" src="https://github.com/user-attachments/assets/d786bd89-8c2f-4d73-9c41-c8773d56f08f">

**Comment by DanTup** [comment]
Unfortunately there isn't a good fix here. The underlying issue is that VS Code doesn't tell us when the casing changes, it continues to use the original case in the API (see https://github.com/microsoft/vscode/issues/137256). We do have a workaround in the `dart.normalizeFileCasing` setting, but it comes with a small performance penalty (we have to check the disk for the real casing on every LSP request that contains a filename).

The error message comes from the Dart analysis server which doesn't really know about this issue (since it's VS Code specific), so changing the message would be difficult. We'd probably have to use middleware to notice this message, and then append some additional text to the end (this would require some testing).

**Comment by DanTup** [comment]
@Yegair understood, thanks!

I was just doing some testing of this to see if I could easily tag something on to the end of the message, but in my testing I noticed that restarting VS Code (or running the **Developer: Reload Window** command) also fixed the issue. I just wanted to check if that's the same behaviour you see (since it might be easier to suggest restarting rather than renaming the file again twice).

**Comment by DanTup** [comment]
This text is now tagged onto the end of `file_names` diagnostics:

![image](https://github.com/user-attachments/assets/9cd3f3c9-998e-40ce-a503-ab745d91f998)
