### ISSUE TITLE
Auto imports broken on third party packages

### ISSUE THREAD

**Issue by milesegan** [Dart-Code/Dart-Code#5273]
**Describe the bug**
Auto complete suggests import completion from files in the project instead of from third party packages.

**To Reproduce**
1. Create a new flutter project.
2. Add the dartx package to the project.
3. Open the project in vscode.
4. Create a new file and try to auto-complete on the `firstOrNullWhere` function from dartx.
5. This will fail, so manually import dartx.
6. Create another new file, try again to auto-complete on `firstOrNullWhere`. 
7. VSCode will suggests imports from other files in the project, not dartx as it should.

**Expected behavior**
VSCode should suggest an import of the third party package, not a import from within the project, which is invalid.

This was working until recently.

**Screenshots**
<img width="627" alt="Screenshot 2024-09-17 at 9 31 55 AM" src="https://github.com/user-attachments/assets/2602ec02-cdcc-4d04-b6ca-f696084df62a">

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.96.0
Flutter extension: 3.96.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.93.1

Workspace type: Flutter (LSP)
Workspace name: flutter_import_bug

Dart (3.5.3): /Users/miles/c/flutter/bin/cache/dart-sdk
Flutter (3.24.3): /Users/miles/c/flutter (Gordo (ios/ios))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/miles/c/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "macos_arm64"
- on macos / Version 15.0 (Build 24A335)
- locale is en-US

#### Project info

- sdk constraint: '^3.5.3'
- dependencies: cupertino_icons, dartx, flutter
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  82 MB | 0.0% |        05:03 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/WHWQcuziboumqKwf  |
| 652 MB | 0.0% |        05:03 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0 |
|  82 MB | 0.0% |        05:03 | dart tooling-daemon --machine                                                   |
| 112 MB | 0.4% |        05:03 | flutter_tools.snapshot daemon                                                   |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/miles/c/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /Users/miles/c/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/miles/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • Gordo (mobile)                  • 00008120-000C75643A87C01E • ios            • iOS 18.0 22A3354
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment]
Thanks for the report! I believe the main issue here is something I fixed fairly recently (see https://github.com/dart-lang/sdk/issues/56320), although it's a Dart SDK fix so the fix will ship in an upcoming SDK release (not a Dart-Code extension release). The issue was that the server was including extensions for any file that _imported_ them, rather than only those that declared/_exported_ them.

However, I can't reproduce your issue exactly, in particular:

> 5. This will fail, so manually import dartx

For me, this bit works as expected:

https://github.com/user-attachments/assets/3e1aaee7-23df-427a-8185-85840424eda6

Could you verify whether you have this setting disabled?

![image](https://github.com/user-attachments/assets/5dfe43a4-9645-43ef-989c-d5a2de98d245)

That would explain why that first bit doesn't work. However the other part of the issue I believe is the issue that's now been fixed (and the fix is probably in Flutter's `master` channel by now).

**Comment by milesegan** [comment]
Thanks for your response. I do have that setting enabled but VSCode won't suggest dartx as an import for me on the first try still.

The issue you linked at https://github.com/dart-lang/sdk/issues/56320 does sound like exactly what I'm seeing though.

**Comment by DanTup** [comment]
> but VSCode won't suggest dartx as an import for me on the first try still

Can you clarify what you mean by "first try"? If you've just added the package, to pubspec and run "pub get" then there can be a small delay before the server would know about it (modifying the `.dart_tool/package_config.json` file - as Pub does - will trigger a rebuild of the analysis contexts).

Can you provide a screenshot of what you see in the completion when trying to complete `firstOrNullWhere` (and confirm whether just re-invoking completion 5-10s later gives the same result or not)? Thanks!

**Comment by milesegan** [comment]
Here's a screen recording:

https://github.com/user-attachments/assets/494f388a-4124-460f-8765-79f73463ac4a

<img width="941" alt="Screenshot 2024-09-20 at 7 53 31 AM" src="https://github.com/user-attachments/assets/f3a12368-f45d-4669-81ba-4425d315ae3e">

**Comment by DanTup** [comment]
Thanks - I don't seem to be able to repro this. Is it possible you could enable the [analyzer instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) by adding this to your `.vscode/settings.json` for this project:

```js
"dart.analyzerInstrumentationLogFile": "logs/analyzer.instrum.txt",
```

And then reproduce the issue (you'll need to first remove the package and then re-add it once the log file is active).

Thanks!

**Comment by milesegan** [comment]
This is from a fresh vscode project:

[analyzer.instrum.txt.zip](https://github.com/user-attachments/files/17095538/analyzer.instrum.txt.zip)

**Comment by DanTup** [comment]
Thanks! Unfortunately there wasn't much in the log (although it allowed me to verify I was performing exactly the same steps, though I still can't repro).

Could you reproduce this so the completion is missing and then:

- Press `F1` to open the command palette
- Run the **Dart: Open Analyzer Diagnostics** command
- Click the "Contexts" link on the left
- Take a screenshot of the top half of this page - it should look something like this:
    ![image](https://github.com/user-attachments/assets/1cc2febe-2b9e-4324-b61f-4414477fe3f5)
- Scroll down to the `PackageConfigPackageUriResolver` section
- See whether `dartx` is listed (you may need to scroll within the small scrollable box):
    ![image](https://github.com/user-attachments/assets/7ecbd73a-f7e7-47b5-802f-c9aecaee227e)
- Assuming `dartx` _is_ listed, go back to the editor and test completion again to see whether it shows up now (in case it was just a delay)

Thanks!

**Comment by DanTup** [comment]
Ah, that's probably because of an issue I found and fixed recently in https://github.com/dart-lang/sdk/commit/0bb52d321ac880717b4b2550806ad9232891a9e4 - it's not in the current stable SDKs. If you're able to easily test using Flutter `master`, that should include it.

Could you also provide a copy of the file at `.dart_tool/package_config.json` and see if you have any `pubspec.yaml` or `.dart_tool/`s in the parent folders of this (`/Users`, `/Users/miles`, `/Users/miles/tmp`)?

Thanks!

**Comment by milesegan** [comment]
I switched to flutter master channel and restarted vscode and now it does suggest completions from dartx. So it sounds like it is the same issue and can be closed in favor of the dart-lang ticket.

Thanks for your help pinning this down!

**Comment by DanTup** [comment]
Great, thanks for testing! I'm not sure why you see the original issue on current stable though - I tested with that and couldn't repro (and I don't know of any fixes in that area). However, if it's not occurring on master then it's probably not worth sinking too much time into it, as it's probably not the sort of thing that would be hotfixed, and it'll be resolved in the next release anyway.

Thanks!

**Comment by Reprevise** [comment]
I have a similar issue where the autocomplete suggestions looks like this:
![image](https://github.com/user-attachments/assets/608d7cbf-6354-4a40-8df3-8c025801be5b)
However, the only import that would actually work (from package `collection` in my case) is missing. It's present when I press Ctrl+. though
![image](https://github.com/user-attachments/assets/27efa2e8-b412-47f2-8864-7b11eb74e3fa)

@DanTup Is this a new issue or something that's getting fixed in an upcoming Dart SDK build?

**Comment by DanTup** [comment]
@Reprevise yes, that looks like the same issue reported here. The duplication is the issue I fixed, although I'm not sure why the correct option isn't showing up at all (that's the same issue reported here that I was unable to reproduce). @milesegan reported that on bleeding-edge SDKs that issue is also resolved though, so I would expect the same is true for you. If you're able to easily test on Flutter `master` to confirm though, it would be good to know it you still see an issue (so we can try to track it down before the next release instead of after).
