### ISSUE TITLE
Quick open files in package dependencies

### ISSUE THREAD

**Issue by briblanch** [Dart-Code/Dart-Code#528]
I was curious if it was possible to allow quick open to search package dependency files and potentially allow them to be edited. Back when I used IntelliJ to write Dart I noticed this functionality in the quick open menu. Once the menu popped up you could also search package dependency files if specified. I have attached a screenshot of the behavior in IntelliJ.

![screen shot 2018-02-05 at 9 48 59 am](https://user-images.githubusercontent.com/1821610/35817348-5b9261d0-0a5a-11e8-9d7f-e124d67f730d.png)

Thanks for an awesome extension and congrats on the new gig! 😄

**Comment by DanTup** [comment]
I think this probably used to work in Dart Code because of the packages symlinks; but now as far as Code is concerned these files are just unrelated. I'll see if I can find any existing functionality we could use to support this, or raise a request against Code to see if they'd be open to adding something.

**Comment by DanTup** [comment]
I've raised https://github.com/Microsoft/vscode/issues/43505

By the way, I think currently the symbol search (Ctrl+T?) might search dependencies (though this may change in future). It might help in the meantime.

**Comment by DanTup** [comment]
Sine https://github.com/microsoft/vscode/issues/43505 has been closed as out-of-scope, unfortunately there will not be a way to provide this.

That said, the Workspace Symbol list (Cmd+T) does include symbols from dependencies, so that might be a reasonable alternative way to jump to things in the dependencies.
