### ISSUE TITLE
Analysis Sever Crashing or Stops working

### ISSUE THREAD

**Issue by gachuigachui** [Dart-Code/Dart-Code#5306]
Type: <b>Bug</b>

I have been having a very bad experience with this for months now I am depressed I even think the devil is after my work sometimes wondering why I suffer such hinderances. Release after release, even with clean  a clean Windows 10 installation the debugger always crashes repeatedly. Is this the normal life of developers? BTW today I just copied the output of the extension host. 

2024-10-08 22:26:12.832 [error] Error: Pending response rejected since connection got disposed
	at Object.dispose (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:34411:27)
	at Object.dispose (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:38163:35)
	at LanguageClient.handleConnectionClosed (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:37754:34)
	at LanguageClient.handleConnectionClosed (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:46543:22)
	at closeHandler (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:37741:18)
	at CallbackList.invoke (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:34543:39)
	at Emitter.fire (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:34605:36)
	at closeHandler (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:33558:26)
	at CallbackList.invoke (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:34543:39)
	at Emitter.fire (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:34605:36)
	at StreamMessageReader.fireClose (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:35274:27)
	at LoggingTransform.<anonymous> (c:\Users\gachui\.vscode\extensions\dart-code.dart-code-3.99.20241007\out\dist\extension.js:35359:42)
	at LoggingTransform.emit (node:events:519:28)
	at emitCloseNT (node:internal/streams/destroy:147:10)
	at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Extension version: 3.99.20241007
VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.29GB free)|
|Process Argv|--crash-reporter-id 9f22883a-354d-4425-9462-9007bb0f27cd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
showbadge:31153266
5fd0e150:31146321

```

</details>

**Comment by DanTup** [comment]
Sorry you're having trouble. This definitely isn't normal.

Can you confirm when you're seeing this error? The error is from the analysis server shutting down, but you mentioned the debugger crashing - is this error happening when you debug your app, or just while editing code? Can you reliably reproduce the issue?

**Comment by Ldev007** [comment]
Hi @DanTup ,
I have been facing a similar situation for past couple of months and it has started to get really frustrating to be honest. Can you please tell me what shall I do to provide you with specific logs so that you can help me in debugging this issue soon ?

I used the "Dart: Open Analyzer Diagnostics" and found some very brief insights :
![image](https://github.com/user-attachments/assets/985df04c-706c-4057-a726-5b54828587f9)

![image](https://github.com/user-attachments/assets/7e997e0a-85e0-4e6d-9cb0-357ab8a01067)

Aren't these crazy slow timings ?

**Comment by DanTup** [comment]
@Ldev007 yes, these timings look bad. I don't think this is the same issue described here though, so please file a separate issue with the details - it's difficult to track multiple problems in a single issue and may lead to things being missed.

The fastest way to get to the bottom of this is if I can reproduce it, so if you're able to share a project that triggers this issue, that would help. Please also include a screenshot of the main request timings (the screenshot above is only the _slow_ requests, which means there is missing context of the requests that may have occurred prior to them).

>  Just a brief description of what happens for me is that the analyzer would take ages to save the file

It's not clear to me what this means, since the analyzer doesn't save files - do you mean you're seeing delays because of some action like formatting or running code actions on save?).

**Comment by Ldev007** [comment]
Ohk @DanTup I will create a separate issue for this. Just one thing, it is happening for any project tbh

**Comment by Ldev007** [comment]
Hi @DanTup , I was just wondering that is there any possibility or chances if the analyser crashes or lags might be caused due to a presence of HDD ? Because I think it can be a possibility smh. But, first I will wait to know you answer and then I will elaborate why do I think so.

**Comment by DanTup** [comment]
@Ldev007 

> I was just wondering that is there any possibility or chances if the analyser crashes or lags might be caused due to a presence of HDD ?

I'm not sure exactly what you mean by "presence of HDD". Do you mean using a mechanical disk drive instead of some kind of SSD? If so, the performance could certainly be worse than an SSD, but I wouldn't expect it to crash.

If you're having issues, please open a new issue with the details so we can avoid confusing this one with something that might be a different issue. Thanks!

**Comment by Ldev007** [comment]
Hey @DanTup the reason why I didn't open a separate issue is cuz I suspected maybe my issue could be resolved without even needing to open a separate one. But sure if you suggest to keep the contexts separate I'll create a separate issue.

**Comment by DanTup** [comment]
Yes please - it avoids discussion of multiple issues being mixed together, and we can easily close the issue if it turns out to be something simple. Thanks!
