### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ZiadElgaraihe** [Dart-Code/Dart-Code#5330]
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.100.0`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.95.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/NEWFOL~1/AppData/Local/Temp/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ZiadElgaraihe** [comment]
[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/user-attachments/files/17591928/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment]
Thank you!

Unfortunately there's not a lot in this trace. There's only around 40ms of profiling information, and nothing in there is particularly long. It's possible that whatever triggered VS Code to show this warning and start profiling completed just as profiling started.

![image](https://github.com/user-attachments/assets/79e14197-4d9f-4765-9771-57a1479f1495)

Do you see this message frequently? If so, have you noticed any pattern to it? If you can reproduce it on-demand, you could manually capturing a profiling trace that wouldn't miss the beginning due to having to meet some threshold to trigger the automatic profiling.

Thanks!
