### ISSUE TITLE
Code hints?

### ISSUE THREAD

**Issue by uu759** [Dart-Code/Dart-Code#5333]
![image](https://github.com/user-attachments/assets/47120e1d-90cf-48b5-82d9-d00490511749)
![image](https://github.com/user-attachments/assets/88331696-6fca-465a-a012-d41f2b9d297f)

I'm studying Dart, and these gray labels saying "String" and "object:" are appearing in VSCode. I didn't add them, but they're showing up like that. When I go into VSCode settings, they disappear, but when I restart the VSCode, they come back again.

What are these, and how can I turn them off?

**Comment by DanTup** [comment]
These are called "Inlay Hints". They should only be shown when you hold down Ctrl+Alt. However, there is a bug in VS Code that they sometimes appear when they should not:

https://github.com/microsoft/vscode/issues/230498

You can add a 👍  to that issue and subscribe there for updates. Once fixed in VS Code, it shouldn't need any changes here. Thanks!

**Comment by FMorschel** [comment]
The VSCode issue was closed today and the latest Insiders build has the fix. Should probably be fixed on the next stable release too.
