### ISSUE TITLE
Flutter: Waiting for connection from debug service on Chrome...

### ISSUE THREAD

**Issue by Triple0g12828** [Dart-Code/Dart-Code#5335]
Flutter: Waiting for connection from debug service on Chrome... for 5 hours this what i have been getting i can't view my codes in any browser

**Comment by DanTup** [comment]
Please complete the bug report template which requests some information that may help troubleshoot (see below). Please also confirm whether running from a terminal outside of VS Code (with `flutter run -d chrome`) reproduces the same issue. Thanks!

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version:
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:
 - Target device (if the issue relates to Flutter debugging):
