### ISSUE TITLE
Treat "<" and ">" like other types of brackets when used in generic type declarations

### ISSUE THREAD

**Issue by pulyaevskiy** [Dart-Code/Dart-Code#568]
**Updated to only cover following issue:** 

- Auto-complete `<>` when typing `<` and when I delete in the middle of `<>` then delete both.

Below is original content of this issue for history:

---

As promised, first set of little things which would be nice to have. 
I'm putting everything in one issue for now, if any of items in my list are accepted we can create separate issue for those.

- [ ] Symbol search is very slow. This is what I used a lot in Intellij. in Code it takes a few seconds to resolve my request which makes it a lot less helpful.
- [ ] A way to re-run last Debug session without having to switch files. Usually when I run tests and switch between files to fix things I need to re-run last session. Currently I have to go back to the test file to re-run it.
- [ ] Jump to source (in the ancestor) for overridden method/field.
- [ ] Auto-complete `<>` when typing `<` and when I delete in the middle of `<>` then delete both.

Before adding something to this list I first tried to google if there is a solution, only items with no answer ended up in the list, though I might have missed something still.

**Comment by DanTup** [comment]
1. Slow symbol search is #283 / https://github.com/Dart-Code/Dart-Code/issues/568
2. Not entirely sure what you mean here, since you normally set the path in the `launch.json`. What does your launch.json look like? (Incidentally, there are changes in this area coming - worth scanning through #538 and adding your thoughts as it seems very related)
3. Is this the same as #505?
4. Do you mean that `<` should be treated more like other types of brackets? I think we could do this, but I think it would negatively affect `if (a < 1)`. Not sure if we could handle it well.

It's better to have an "issue" per issue - if the first three are covered by the issues linked above, add notes to them and we can use this issue to discuss the last point.

**Comment by DanTup** [comment]
@pulyaevskiy Ping!

**Comment by pulyaevskiy** [comment]
Sorry,

What you said makes sense (though I tried searching for related issue before adding above to the list and apparently my search skills are not good enough).

> Do you mean that < should be treated more like other types of brackets?

Correct. I think it could be triggered in cases when there is no whitespace characters before and after current cursor position. 

I'll update this issue to only refer to this case.

**Comment by DanTup** [comment]
I'm not sure how well we could do this - the normal behaviour with brackets is handled by Code and it has no context of where it is. We don't want to try and re-implement the behaviour ourselves as it might not feel the same (and we'd have to respect all options that affect it, etc.).

**Comment by DanTup** [comment]
I don't think it's likely we'll ever have the ability to implement this in a way that wouldn't falsely trigger for things like `x < 1` because this config is all declarative - we can't decide to do it based on the surrounding code. As such, an an attempt to prune the backlog a little, I'm going to close this.

If it ever becomes possible, I'm happy to revisit.
