### ISSUE TITLE
add the ability to debug dart cli apps

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#57]

**Comment by devoncarew** [comment]
I'd like to take a stab at this; targeted for 1.0? post 1.0?

**Comment by DanTup** [comment]
I put it in post-v1 because I don't know how big a job it is or when we'd start but it'd be neat to have for v1. The future milestones are a bit wolly (just goals, but I'll shuffle things around that are done/not done nearing a release).

I'll move to v1 if you think it's reasonable to do (there's no real plan for when v1 should be, other than it should have at least all the basics and not feel unfinished) :)

**Comment by DanTup** [comment]
This is now in master and will be in 0.10. Thanks!
