### ISSUE TITLE
Let imported files be editable

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#582]
I remember it used to be possible. 

ctrl/cmd+click into an imported class outside of the current workspace. The file (likely from .pub-cache ...) is not editable. 

Would be nice to show a warning banner saying you're editing things that are not in your code with a hint on how to restore it later on but still let you edit.

**Comment by DanTup** [comment]
Yeah, it used to work because they're just files. I figured it made sense for them to be read-only, so I implemented that. However it's kinda quirky for a couple of reasons so I've been thinking of removing it for a while.

The prompt about editing an external file sounds good and probably wouldn't be too hard (probably we'd only want to do it once per session or something, or a "Never show me again"); though I'm not sure what the process of restoring it would be!

**Comment by xster** [comment]
@devoncarew probably knows better. I would assume a `pub get` / `flutter packages get` would check for the hash of the cache?

**Comment by DanTup** [comment]
Ah ok, that's easy then. I figured they might just see the package there and skip over it. I'll try it out when I do this, and if it works I'll include that in the message if it fits.

**Comment by DanTup** [comment]
I've created #592 for the warning (not sure how easy it'll be), so this case is just removing the read-only stuff.

**Comment by devoncarew** [comment]
> I would assume a pub get / flutter packages get would check for the hash of the cache?

No, you're if they're in your pub cache, you're editing files that will not be restored by pub. Other local projects will see these changes - things will only be fixed when pub brings down a newer version, and the local projects version resolve against that version.

I think we should make it hard to edit these files - the barrier to doing it will prevent people from making inadvertent modification to their pub cache.

**Comment by DanTup** [comment]
Ah, that doesn't sound so great - especially since I've removed the readonly-ness because of breakpoint bugs etc.

I've pinged some cases in Code about better support for readonly files and will investigate a warning in #592.
