### ISSUE TITLE
Class properties do not appear when using Dart 2 option + syntax

### ISSUE THREAD

**Issue by lukef** [Dart-Code/Dart-Code#589]
Dart-Code: 2.9.0-beta.1
Code: 1.20.1 (1.20.1)

When using the new Dart 2 style class definitions it will attempt to match the class property autocomplete to other class definitions:

<img width="410" alt="screen shot 2018-02-18 at 8 14 53 am" src="https://user-images.githubusercontent.com/37941/36354097-fe3f9b7c-1483-11e8-80b1-90fb9baf0b7c.png">

If using a `new` keyword then it works correctly:

<img width="382" alt="screen shot 2018-02-18 at 8 14 40 am" src="https://user-images.githubusercontent.com/37941/36354104-0fa1b5bc-1484-11e8-815e-01322c8bcf56.png">

**Comment by DanTup** [comment]
@lukef What version of the Dart SDK shows in the status bar? (actually, maybe the output from `flutter --version` is better, it includes more info).

**Comment by DanTup** [comment]
Cool, thanks. The one in the status bar is the one we'll be using for the analyzer. I'll dig into this tomorrow.

**Comment by DanTup** [comment]
Looks like this has already been fixed - I tested:

- `dev24`: good
- `2.0.0-edge.06439147c4af03fa0edcbee7e325e8b04ff151cb`: bad
- `2.0.0-edge.00225dedfead37ae670bddca9b15509401844b3b`: good

The bottom one is last night's nightly. Possibly the fix is https://github.com/dart-lang/sdk/commit/188697d6e1e0cac71e652da934c2751816d47a8b?

Pointing at last nights nightly for production work probably isn't a great idea so you might need to wait until Flutter rolls the engine.
