### ISSUE TITLE
Tab stops too sticky or indentation not applying

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#635]
![](https://media.giphy.com/media/c6Wtvs3WHt4CpAwGZd/giphy.gif)

Seems like a recent regression but is adding some friction. 

Here when I start moving the cursor outside the tabstops, it doesn't cancel the tabstop. Going back inside the tabstop doesn't put the cursor to the right indentation and pressing tab ends up interpreting it as a tabstop advance so I can't tab into the right indentation. 

Maybe let the final tab stop just be inside the () in the new autocompleted widget or somehow let the cursor inside the tabstop always have the formatted indentation.

**Comment by DanTup** [comment]
Hmmm that does look wonky, I'll see what I can do. I would've expected the indent to remain!

**Comment by DanTup** [comment]
The reason this probably wasn't happening before is that we didn't support tab-stops here, so you were just getting a basic text insertion whereas now we build tab stops from the data from the server.

**Comment by DanTup** [comment]
This is what the completion snippet is for this case:

```
"Container(${1:})${2:}"
```

The indentation is provided by VS Code when you press `<enter>` (our completion had nothing between the parens). It's auto-indenting (reasonably well) but then when you move away with the cursor keys I guess it's deciding that you wanted a blank line there and therefore wiping out the trailing whitespace.

I'll have a play around though I'm not sure if we can easily fix it. I wonder if we could somewhat sidestep it if we could get the trailing comma to be inserted automatically?

@bwilkerson What do you think? Given the following code:

```
var x = <Widget>[
  new Widget(),
  new Wi^
  new Widget(),
];
```

Could/should the completions include the comma on the end? We already have these in some places (parameters?) so it might not be totally unusual?

**Comment by bwilkerson** [comment]
Interesting question. I don't have an answer (yet), but I'll share some initial thoughts.

I'm not sure how we'd decide (correctly) when to insert a comma and when not to. Consider:
```
var x = <int>[
  rect.top,
  off^ rect.left,
];
```
It seems just as likely that the user is modifying the last element as it is that they're inserting a new element into the list.

Maybe it's because the text is on the same line. Maybe it's because it isn't an instance creation expression.

And would we do something similar when completing within a map literal (auto inserting a colon and comma)?

**Comment by DanTup** [comment]
> It seems just as likely that the user is modifying the last element as it is that they're inserting a new element into the list.
> 
> Maybe it's because the text is on the same line. Maybe it's because it isn't an instance creation expression.

Yeah, I had these thoughts and hoped you'd have already a plan 😆

My initial thoughts (for the original example) were that we're completing a constructor invocation and the next item is also a constructor invocation so it's reasonably certain there should be a comma there (not having it wouldn't produce useful code).

Of course, things are more complicated if the next item no longer has new/const (they could be trying to overtype a function name, variable name, or even another constructors name)!.

> And would we do something similar when completing within a map literal (auto inserting a colon and comma)?

¯\_(ツ)_/¯

It seemed like such an obvious idea when I made it but now I'm not so sure. On the plus side, I just realised I can repro @xster's issue with plain typing and no completion, so I think I might be able to raise this as a bug with Code to at least fix the original issue.

If you think there's merit in the comma thing and want me to raise @ sdk, let me know. But it sounds like we might struggle to come up with rules that'd make it work reasonably.

**Comment by DanTup** [comment]
Actually, this totally happens because of the tab-stop. You can seemingly repo without because if you type the whole item from the completion manually it still triggers the completion. Eg. if you type the exact same code as in the sample but where the constructor name is invalid (so there's no completion) you don't see the issue.

I'm curious about why this seems new though; I expected tabstops to be in the same positions as pre-v2.9.0. I'll take a look.

**Comment by DanTup** [comment]
Actually, I could repro/. Raised https://github.com/Microsoft/vscode/issues/45149.

**Comment by DanTup** [comment]
I don't think there's anything to do here - there's an open issue in VS Code about this (https://github.com/microsoft/vscode/issues/40115) and if that's fixed, it shouldn't need any further changes here.
