### ISSUE TITLE
Show icon preview in doc snippet

### ISSUE THREAD

**Issue by fabiorogeriosj** [Dart-Code/Dart-Code#638]
![image](https://user-images.githubusercontent.com/1442874/36900652-e4859276-1e02-11e8-940f-4428b0b17e3b.png)

**Comment by DanTup** [comment]
@devoncarew It'd be really nice to make this work - currently the dartdocs are HTML chunks that won't work here (it's very unlikely we'd ever be able to pull random CSS in to make this work).

Colours do something similar but they use images:

<img width="710" alt="screen shot 2018-03-02 at 18 06 10" src="https://user-images.githubusercontent.com/1078012/36914211-6ba3b9ae-1e44-11e8-82fa-25dba168a139.png">

Is it likely we could do the same here? I don't know how the colour images were generated and whether we could do the same for these icons (or maybe they're already in a form that can be used directly). WDYT?

**Comment by devoncarew** [comment]
We generate the material icons and the color information from some scripts in the flutter/flutter-intellij repo. If the color info (or some generates icons) and the material design icons would be useful to you, we can generalize those scripts.

**Comment by DanTup** [comment]
@devoncarew I was curious how you were handling this in IntelliJ, but I just installed it and I'm not sure it works either.

Here's help for colours - it includes the image:

![intellij color](https://user-images.githubusercontent.com/1078012/37088340-eaedaba8-21f4-11e8-8af0-f028acf004ff.png)

And here's icon:

![intellij icon](https://user-images.githubusercontent.com/1078012/37088348-f3a99c48-21f4-11e8-940d-b7ae254601e0.png)

So in IntelliJ for icons you just see the text out of the HTML (but no icon). If the Flutter class dartdocs had image references (like colours) then these would display there.

The downside, is that the Icons page on the Flutter website would render a lot of images (whereas currently it uses the material icons loaded), but I guess it's already doing that for colours and I think help in the IDE is at least as important as help on the website.

WDYT? Shall I raise @flutter?

**Comment by devoncarew** [comment]
Ah, we don't handle for tooltips, but we do show previews of the colors and material icons in the editor's gutter to the left. If you reference something like `Icons.info_outline` in your code you'll see an icon on the left.

**Comment by DanTup** [comment]
Aha, gotcha :)

Possibly we could do that in Code if we can get the right info, though I still think we should do something about tooltips (they look bad in both editors, but particularly in Code because the HTML gets rendered verbatim).

There's an open issue with Code about HTML in hovers not being supported (https://github.com/Microsoft/vscode/issues/40607) but I think even when (if) that gets fixed, it'll just become like IntelliJ's with text rendering instead of an icon. It feels a little weird to require custom CSS to render the docs correctly.

WDYT?

**Comment by DanTup** [comment]
I've made this work be regexing the HTML out for an image tag. I'm hot-linking for now to:

https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_$1_white_36px.svg

It's possible they'll break in future, but I don't think the missing image is any worse than a big chunk of HTML so we'll just update it if it does (though it seems unlikely those files will disappear IMO).

Currently it'll always show the white icon; it looks poor on the Light theme but I'll fix it up if/when https://github.com/Microsoft/vscode/issues/46940 gets addressed.

**Comment by ffeu** [comment]
@DanTup 
Hi, I can no longer see the icons preview in VS Code.  Is it just me?

**Comment by DanTup** [comment]
@ffeu I don't know if it's just you, but it does seem ok here:

<img width="547" alt="screen shot 2018-09-18 at 19 00 40" src="https://user-images.githubusercontent.com/1078012/45706869-464fc200-bb75-11e8-8f8f-4b09fa94470d.png">

Can you open a new issue include a screenshot, whether there are any errors in the console (Help -> Toggle Dev Tools) and also a [log captured](https://dartcode.org/docs/logging/#capture-logs-command) while you're viewing the help?

Thanks!

**Comment by 3141bishwa** [comment]
Hi there. Is there any way to get preview working for [Cupertino Icons](https://github.com/flutter/cupertino_icons) too? Right now, it seems to work for Material Icons only.

**Material Icon Preview**
![material icons](https://user-images.githubusercontent.com/9397236/69057402-e2a37c00-0a39-11ea-9ffa-781f38524088.png)

**Cupertino Icon Preview**
![cupertino](https://user-images.githubusercontent.com/9397236/69057421-f222c500-0a39-11ea-947f-30aaa198e32d.png)

**Comment by DanTup** [comment]
@3141bishwa it looks like the documentation for that class does not include previews, see:

https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html
vs
https://api.flutter.dev/flutter/material/Icons-class.html

For VS Code, we rely on the documentation and perform a simple regex replace in order to get the icons to work in the tooltips, but there isn't enough info for this in the current ones.

I opened an issue in the Flutter repo about adding previews there (which we could then use to provide here). I don't know if there's a technical reason it isn't done or not (the Material one uses a font, I'm not sure if that's available in the site for Cupertino):

https://github.com/flutter/flutter/issues/45097
