### ISSUE TITLE
Use type information when ranking/sorting code completion items

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#640]
```dart
typedef X FunctionTypeY(
  Z z,
  A a,
  B b,
  C c,
);
```

Then trying to call said function type instances later with 
```dart
y([cursor]
```

Doesn't seem to autocomplete with any instances of z in scope automatically.

**Comment by DanTup** [comment]
Are you able to give a more complete sample that I can copy/paste? I tried what I think you meant, but the auto-complete includes everything in scope (regardless of type) which seems to be the same as for other methods:

<img width="415" alt="screen shot 2018-03-03 at 10 45 00" src="https://user-images.githubusercontent.com/1078012/36933406-0753ad7e-1ed0-11e8-9394-4e45e2e1093e.png">

**Comment by DanTup** [comment]
@xster Ping! :)

**Comment by DanTup** [comment]
There's probably not anything to do in the extension here - the ranking is done by the server initially and then overriden by VS Code once you start typing (since it's filtered re-ranked client-side).

I believe there have been improvements made to the ranking recently that may have improved this, but if not it's worth filing suggestions/issue at https://github.com/dart-lang/sdk. With the move to LSP, the little client-side code we do have for completion will disappear (and instead exist inside the LSP interface in the analysis server), and VS Code and the server will talk directly.
