### ISSUE TITLE
Provide the ability to disable Dart Code for a workspace

### ISSUE THREAD

**Issue by sclee15** [Dart-Code/Dart-Code#658]
I sometimes put compiled dart code into a serverside project that made of another language.

And dart code claims there is error for dart files.

I tried to hide those help but i can't do it.

Please consider the honor the vs code exclude file setting.

**Comment by DanTup** [comment]
I don't believe the `files.exclude` property in VS Code settings is intended for extensions to use for their own exclusions. The TypeScript extension, for example, does not honour it (it has its own settings). There's also a danger that people might want to exclude generated files from their explorer tree but not then get a bunch of warnings as a result.

I think there are a couple of options:

1. Provide the ability to disable Dart Code functionality for a given workspace (a big kill-switch)
2. Fix whatever is causing this code to return errors (I presume the code is normally valid?)

I actually have this issue right now in the Dart Code codebase, because we have nested Dart projects for testing - the cause is that we don't support Flutter projects in sub-folders and one of my test projects is Flutter (see #493).

Is your project also Flutter? If not, can you provide some information on what the errors are so I can understand why they're happening?

**Comment by sclee15** [comment]
Hello.

I use Dart Angular App along with Elixir Serverside codes.
At that workspace, I mainly use Elixir. Therefore I prefer the solution number 1

**Comment by DanTup** [comment]
@sclee15 Understood. Out of interest, could you give details of why the analysis fails? Even if I implement 1 I'd like to try and fix 2 as it may affect others.

**Comment by sclee15** [comment]
Because, the build folder (the one produced by Dart2JS) does not contains  pubspec.yaml. Therefore the linter gives error for missing packages

**Comment by DanTup** [comment]
Turns out, VS Code already has this functionality :)

If you open extensions list and click the drop-down on the Disable button, you can disable for a workspace:

![disable](https://user-images.githubusercontent.com/1078012/37161582-0020414c-22eb-11e8-85a1-fb68b97e3d2d.png)

Let me know if you have any problems with it!
