### ISSUE TITLE
Expose common actions as editor tool buttons

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#662]
VS Code supports adding editor specific actions on the right-hand side of the editor pane. For example, for markup files it has:
https://github.com/Microsoft/vscode/blob/3f4df74ec7ad4b94365c78b11f26b3a1bd87e028/extensions/markdown/package.json#L42
![screen shot 2018-03-08 at 13 06 31](https://user-images.githubusercontent.com/13644170/37150310-8bc902c0-22d1-11e8-8356-af6a9ab1ce61.png)

It would be interesting to explore using that to expose some common Dart/Flutter actions (for example 'Format Document' and perhaps 'Show Fixes'.

**Comment by DanTup** [comment]
We do use these buttons in some places (like pub commands in a pubspec). However, it feels a bit redundant to me using them for non-Dart specific actions. Having buttons for Format/Quickfixes might seem strange to Code users since they only appear in Dart files and not others? It feels like it goes against how Code wants to work (if most people wanted a toolbar with these buttons on, I suspect it'd be built-in).

There are also a extensions that allow the user to customise things like this themselves (for ex [this status bar one](https://marketplace.visualstudio.com/items?itemName=gsppvo.vscode-commandbar))) which apply generically.

Slight tangent, but I also think we could do a better job of helping people with Code config and highlighting features. There's a lot of stuff that's not Dart-specific so we don't really draw much attention to it (I originally figured that people should learn Code from Code and not us). For example people don't know they can enable `formatOnSave`/`formatOnType`, press `Ctrl+.` to open quickfixes, press `F5` to just launch the debugger (I've seen several video tutorials that tell people to switch to the debug sidebar then click the cog to create launch.json and then set all this stuff up - even before v2.9 you could just press F5 twice). Same for other useful key-binds.

**Comment by DanTup** [comment]
@mit-mit Any thoughts on the above? I'm still of the opinion that we shouldn't add buttons for features that aren't Dart-specific (it'd be strange to have a Format button on the toolbar when editing a Dart file, but not a JS file, for example) and we should be mindful of Code's (probably unrealistic!) desire to be an editor and not an IDE.

If we think there are things that aren't discoverable though, we should definitely try and work on that.

**Comment by mit-mit** [comment]
Do we have any usage data we can look at to see if Flutter developers generally look aware of core features such as hot reload, reformat, etc.?

**Comment by DanTup** [comment]
Dart Code and Flutter have stats on hot reloads (though until vNext of Dart Code, we don't distinguish those triggered by Save and those triggered explicitly be the user separately) but I don't know if anyone is logging formatting events (it's possible the analysis server does, I've not seen any of it's analytics).

Although I have no data to back it up, I do think users will be aware of those two at least - Format is on the context menu and the palette (and I get a fair few complaints about not supporting tabs) and hot-reload-on-save is triggered on save by default (and somewhat of a headline feature of Flutter).

(I wonder if @InMatrix has any more insight on this?)

**Comment by DanTup** [comment]
@mit-mit just tidying up and re-discovered this. It's been a while(!).

> Do we have any usage data we can look at to see if Flutter developers generally look aware of core features such as hot reload, reformat, etc.?

Hot reload is invoked millions of times per week and now has its own button on the debug toolbar, so I think that one is very discoverable.

I don't have stats on formatting (though in vNext I'd like to log whether formatting is Disabled/Enabled/Enabled-with-format-on-save), but as mentioned above I'm fairly sure that's discoverable (it's on context menus, in the palette and lots of people express opinions on dartfmt). It's fairly code functionality for VS Code.

Is there anything concrete you think might be missing? We can always add buttons and track their use if there are specific things we think might benefit from it. Otherwise, I think we can probably close this?

**Comment by mit-mit** [comment]
Yeah, I think we can close this now
