### ISSUE TITLE
Offer a list of potential overridable methods when typing @override

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#736]
It would be very comfortable if when overriding a method in an extended class if DartCode could offer a list of potential candidates via intellisense and completes after selection of one of them the whole method.

**Comment by bkbonner** [comment]
Hi @DanTup.   What is involved in adding this to Dart-Code?   This feature seems like it would be *really* useful for folks newer to Dart and Flutter.

**Comment by DanTup** [comment]
This needs implementing in the Dart analysis server. The related issue (https://github.com/dart-lang/sdk/issues/32677) was mistakenly closed - only failing tests were added. I've reopened that issue and asked for some pointers - though it's unlikely I'll have time to look at it this month due to a lot of other things on.

**Comment by bkbonner** [comment]
Thanks.   I saw that was closed so it prompted me to ask the question.
Hopefully if they give pointers others might help.

Brian

from my phone

**Comment by FMorschel** [comment]
@DanTup I think this issue you mentioned has now actually been completed so maybe this can be closed as well?

**Comment by DanTup** [comment]
Yep, this has been implemented via https://github.com/dart-lang/sdk/issues/32677. Thanks!
