### ISSUE TITLE
Automatically add .dart_tool to the watch exclusion list

### ISSUE THREAD

**Issue by natebosch** [Dart-Code/Dart-Code#742]
Does a VS code plugin have the ability to update the workspace watch exclusion list? As more users migrate to `build_runner` we'll have more occurrences of this directory with lots of files and excluding it can prevent the editor from picking up too many file watchers which are a limited resource.

See https://gitter.im/dart-lang/angular?at=5aba15b9e4ff28713a7aeb6e

If we can't do it automatically should we document it somewhere?

**Comment by DanTup** [comment]
I'm not sure if we could contribute it without overwriting anything they've set themselves, but I'll take a look (and if we can't do it, I'll raise a feature request with Code to see if they can support it somehow).

**Comment by DanTup** [comment]
Can't find a way to do this, so I've opened https://github.com/Microsoft/vscode/issues/46851.

**Comment by kevmoo** [comment]
Also: `.dart_tool` is also used by pub in Dart v2. So *most* projects will want this ignored.

**Comment by DanTup** [comment]
It's not just the watchers that cause issues here, seems like the analyzer reports issues here too:

<img width="591" alt="screenshot 2019-01-30 at 4 59 50 pm" src="https://user-images.githubusercontent.com/1078012/51998483-ad30a080-24b0-11e9-8d93-27456cb857db.png">

@bwilkerson could/should we automatically exclude these in the analyzer? Otherwise in the editor we'll need to walk the tree looking for `.dart-tool` folders to exclude them (and watch for new ones being added, and exclude them).

**Comment by DanTup** [comment]
The latest VS Code lets us contribute these exclusions without overwriting them all so I've added `.dart_tool` to the watcher exclusions (I didn't add it to `files.exclude` so it'll still show in the explorer - I thought it may be odd to hide it by default without being obvious to users).

If there are any other folders we should consider adding (I did wonder about `build`, `ios`, `android` etc. for Flutter, but I'm not certain that's sound or the full implications of doing so).
