### ISSUE TITLE
Dart Analyzer fails when there are spaces in the Flutter path

### ISSUE THREAD

**Issue by bramvbilsen** [Dart-Code/Dart-Code#743]
I'm getting the following error:
```
The Dart Analyzer has terminated,
```
Here is some log output:
```
[8:36:19 PM]: Spawning C:\Users\bramv\Documents\Flutter SDK\flutter\bin\cache\dart-sdk\bin\dart.exe with args ["C:\\Users\\bramv\\Documents\\Flutter SDK\\flutter\\bin\\cache\\dart-sdk\\bin\\snapshots\\analysis_server.dart.snapshot","--client-id=Dart-Code.dart-code","--client-version=2.11.0","--no-preview-dart-2"]
Could not load "file:///C:/Users/bramv/Documents/Flutter": FileSystemException: Cannot open file, path = 'C:\Users\bramv\Documents\Flutter' (OS Error: The system cannot find the file specified.

, errno = 2)
null
```
I'm running Dart Code version 2.11.0

**Comment by DanTup** [comment]
This is caused by this:

https://github.com/nodejs/node/issues/7367

When both the executable and arguments contain spaces, everything needs wrapping with additional quotes.

I made the CI builds have spaces in the SDKs and they fail:

https://ci.appveyor.com/project/DanTup/dart-code/build/0.0.1517
https://travis-ci.org/Dart-Code/Dart-Code/builds/359049598

It manifests as a timeout in `before` because we're waiting for first analysis to complete and it never does.

Pushing a fix to see if it fixes them all...
