### ISSUE TITLE
How to do full reload? 

### ISSUE THREAD

**Issue by alvinkonda** [Dart-Code/Dart-Code#754]
Hi,
I know i can do reload but i cant find the command to do a full reload like Command + capital "R" on terminal 

Thanx
Alvin

**Comment by DanTup** [comment]
Hello! This is a common question because we can't currently show two buttons on the toolbar (Please 👍 on https://github.com/Microsoft/vscode/issues/45116 to support this!).

It's bound to `Ctrl`+`F5` by default (though you can modify this in the VS Code settings and also in the command palette as `Flutter: Full Restart`. Some more info here:

- https://dartcode.org/docs/key-bindings/
- https://dartcode.org/docs/debugging-commands/#flutter-full-restart

**Comment by DanTup** [comment]
I've also added this to the FAQ, thanks!

https://dartcode.org/faq/#how-do-i-perform-a-full-restart

**Comment by alvinkonda** [comment]
`Ctrl+F5 `- Full Restart (when debugging Flutter apps and in a debug session)

... was the answer, thnx

**Comment by Dhana-Krishnasamy** [comment]
> Full Restart

 not in the key bindings anymore and 

> Hot Restart 

doesn't even update the button colour change :( ( Fullter version 1.0.0,  iPhone X Simulator, Mac OS )

**Comment by DanTup** [comment]
@Dhana-Krishnasamy Looks like you found your issue (an extra slash) and an issue has been opened for improving that (https://github.com/dart-lang/sdk/issues/35645). I presume this means you're unblocked for now but let me know if you're still stuck!

**Comment by Dhana-Krishnasamy** [comment]
yes, its solved now, thanks
