### ISSUE TITLE
after updating vscode. dart syntax highlighting is not working. Also auto pretiffy is also not working.

### ISSUE THREAD

**Issue by Pushkar98** [Dart-Code/Dart-Code#773]

**Comment by DanTup** [comment]
Can you check whether Dart Code is listed in your extensions tab? There has been a bug in VS Code that resulted in extensions disappearing if VS Code updated at the same time as the extension was updated.

Otherwise, please open dev tools with `Help -> Toggle Dev Tools` and then open a Dart project to see whether any errors are listed.

**Comment by DanTup** [comment]
I suspect this may be related to the VS Code bug that was deleting extensions that were updated while it was updating itself. Please shout if anything is still experiencing issues like this.
