### ISSUE TITLE
From the Stacktrace view opening a file does not work

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#783]
![image](https://user-images.githubusercontent.com/16635729/38301250-5242595a-37ff-11e8-945c-a2f0ebc10bb9.png)

although the correct path is visible in the StackView

![image](https://user-images.githubusercontent.com/16635729/38301291-6b1f5586-37ff-11e8-85d4-dedc28b4d6fb.png)

**Comment by DanTup** [comment]
This is because `flutter test` formats (and expects) `package:` uris with the wrong slashes on Windows - see https://github.com/flutter/flutter/issues/15513.

I think we'll probably put a workaround in for now, but I'm hoping we can have the paths documented to make it clearer when they're wrong on the VM side.

**Comment by DanTup** [comment]
Can't repro this even on Windows now, can you? Can you give me the exact steps?

![slashes](https://user-images.githubusercontent.com/1078012/38817842-24c85362-4191-11e8-8ac3-4319a28ed1d2.png)

**Comment by DanTup** [comment]
I tried switching to the beta and also cannot repro this :(

I checked your log again, and there's a mix of slashes going the right way and wrong way! Can you try to repro this again, and let me know which versions of Dart Code and Flutter you're using, and if you're able to provide the exact code so I can easily repro?

**Comment by escamoteur** [comment]
I can no longer reproduce it either maybe the last Beta 2 update solved the problem
