### ISSUE TITLE
Breakpoints aren't  working

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#784]
Somehow in this project breakpoints inside a package project  don't work when running tests.

Dart Code Version: 2.11.2

attached is the Log file
[FlutterObserve1.log](https://github.com/Dart-Code/Dart-Code/files/1875242/FlutterObserve1.log)

**Comment by DanTup** [comment]
This is because `flutter test` formats (and expects) `package:` uris with the wrong slashes on Windows - see https://github.com/flutter/flutter/issues/15513.

I think we'll probably put a workaround in for now, but I'm hoping we can have the paths documented to make it clearer when they're wrong on the VM side.

**Comment by DanTup** [comment]
I tried switching to the beta and also cannot repro this :(

I checked your log again, and there's a mix of slashes going the right way and wrong way! Can you try to repro this again, and let me know which versions of Dart Code and Flutter you're using, and if you're able to provide the exact code so I can easily repro?

**Comment by escamoteur** [comment]
I can no longer reproduce it either maybe the last Beta 2 update solved the problem
