### ISSUE TITLE
High CPU of analysis server when moving cursor

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#786]
Analysis log: https://pastebin.com/Sm7Jjjnk

**Comment by LorenVS** [comment]
I believe I'm seeing the same behavior

**Comment by DanTup** [comment]
Weird - something is triggering us to send empty edits:

```
[12:56:02 PM]: ==> {"id":"24","method":"analysis.updateContent","params":{"files":{"/home/herman/repos/qedb/expr/lib/src/misc/detect.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}}}
```

We have this as a workaround for some places where we need data from the analysis server but there's no request/response API, so we have to ping the server.

If you're not doing anything other than moving the mouse around, I can't see why we'd need to be doing this. I'll see if I can repro shortly.

I've already changed outlines to be cached locally for some other features, so we may be able to do the same for these and just get rid of empty requests entirely.

**Comment by bergwerf** [comment]
To be specific, I'm navigating with the input cursor (with the arrowkeys in
this case)

**Comment by DanTup** [comment]
Ok, it's likely this:

https://github.com/Dart-Code/Dart-Code/blob/adfd7fb831dfcbe37dee6d98ae825f8754b19e3b/src/providers/dart_highlighting_provider.ts

When Code asks us for "highlights" (that is, it wants to highlight other occurrences of what you have selected), we force a request to the server for this data. This is because we've generally kept no state in the editor and requested it when needed.

This has changed recently and outline info is now stashed in some local state, so I suggest we do the same for this and that will eliminate all of these cases.

**Comment by DanTup** [comment]
Ok, this is solved in v2.12. We keep occurrences locally and never hit the server for them anymore. This will hopefully make a difference :)

Depending on the state of it, I may build a beta version today that you could try out.

**Comment by DanTup** [comment]
There's a vsix build (called alpha 1, since it's still a way off feature complete for v2.12) here if anyone wants to try it, should solve this issue:

https://github.com/Dart-Code/Dart-Code/releases/tag/v2.12.0-alpha.1

I'm not around much next week so if you hit issues you may have to just uninstall and go back to the marketplace one, but hopefully you won't and it'll be a good improvement!

**Comment by bergwerf** [comment]
I believe this is improving performance for me. From working with atom with the recommended dart plugin I am pretty sure much more performance improvement can be gained (looking forward to the update buffering :D, I believe the linter in atom uses a 300ms interval)

**Comment by DanTup** [comment]
Yeah, the buffer should make a big difference since many updates will be folded together. I'm slightly concerned about the risk though - for ex. everything is async, and if we have changes in memory in Code that we did not send to the server, the information it sends back could be bad, which for edits, like code-completion, formatting, etc, could be significant. I'll have to do some testing (afraid it won't be for v2.12 though).
