### ISSUE TITLE
Mismatched type errors when casing in paths differs (eg. starting from console with different casing to actual folder)

### ISSUE THREAD

**Issue by kentcb** [Dart-Code/Dart-Code#798]
Using this extension I am getting incorrect analysis reports such as:

```
The return type
'TimesheetDto (C:\\Users\\kent\\Repository\\<<redacted>>\\Src\\lib\\features\\timesheet\\dtos.dart)'
isn't a
'TimesheetDto (c:\\Users\\Kent\\Repository\\<<redacted>>\\Src\\lib\\features\\timesheet\\dtos.dart)'
, as defined by the method 'fromAppState'.
```

Neither `flutter analyze` nor IntelliJ report the same problems. I see no errors in the developer tooling (console).

My analysis log is [here](https://gist.github.com/kentcb/c08501c2bb0f9d350284e9ef78e56380).

**Comment by DanTup** [comment]
This is unfortunately a bug in the SDK:

https://github.com/dart-lang/sdk/issues/28895

Paths are case-sensitive and on Windows if the drive letter casing that the VM thinks is correct for `package:` uris and those it's using for relative files do not match, this happens (note the difference in casing of the drive letter in your error message).

For IntelliJ and `flutter analyze` I guess they're working out the same. The fix is sadly quite complicated (whether it's done in the analyzer or Dart Code - though in the analyzer all editors benefit from the fix).

You might be able to avoid it by changing how you're importing the files (like always using `package:` imports from outside the package and relative paths from inside it) but it's hard to say for sure without seeing the source code.

**Comment by kentcb** [comment]
I tried the new `dart.previewExperimentalWindowsDriveLetterHandling` setting just now, but I am unfortunately still getting this problem because it's not just the drive that is mismatching in casing:
```
The argument type 'AllowanceDto (C:\Users\kent\Repository\<<redacted>>\Src\lib\features\technician\timesheet\dtos.dart)' can't be assigned to the parameter type 'AllowanceDto (C:\Users\Kent\Repository\<<redacted>>\Src\lib\features\technician\timesheet\dtos.dart)'.
```
Note the "Kent" versus "kent".

**Comment by DanTup** [comment]
@kentcb Ugh! I was worried this might happen, but had only noticed drive letters causing issues. Looks like I should've spotted this in your original report though.

I'm not sure if we can fix this one from Dart Code; the drive letter we had a reasonable idea that it'd always be uppercase in the analysis server; however we can't really guess which other parts of a path might be cased differently.

That said, there must be a reason for mismatched casing here. In the drive letter case, VS Code's API lowercases the drive letter which is why things didn't match. I'm wondering where your difference is coming from...

Could you check some things, like:

1. What's the actual casing of the folder "Kent" on the disk
2. Do you have the opposite casing in your `PATH`, `APPDATA` or `PUB_CACHE` environment variables?

**Comment by kentcb** [comment]
OK, thanks for the guidance here - I think I've sorted this out. Here's the deal...

* The _actual_ casing is `C:\Users\kent`
* I use [ConsoleZ](https://github.com/cbucher/console/wiki)
* I had copied my ConsoleZ settings from a previous machine. The settings include various environments that I can quickly start in separate tabs inside ConsoleZ (e.g. development, admin, blog). One of the settings is the path to start up in
* The path casing on my other machine is `C:\Users\Kent`. You can see where this is going...
* Powershell is...well...a bit dumb here. If I type `cd Ke` and press `tab`, it autocompletes as `kent`. But if I type `cd Kent` and hit `enter`, it shows my path as `C:\Users\Kent` without correcting it :/ So when ConsoleZ asks it to start up in `C:\Users\Kent\Whatever\`, it just does it without correcting the casing
* This, in turn, flows through to VSCode (which I start via my console) and the analyzer

I'm not sure what the ultimate solution is here (seems like case insensitivity on Windows is required somewhere) but I'm very happy to have moved past this particular problem!

Thanks again

**Comment by DanTup** [comment]
Thanks for digging! I suspected something like this. I'm not really sure if we can fix in Dart Code though - even if we could normalise all paths to what the underlying file-system is, I don't think Code would then accept those paths and match them up to the existing editors.

Maybe we could at least detect it and show a warning though? I'll re-open this and have a play around.

**Comment by DanTup** [comment]
v2.13 has a warning when you open a folder that has a mismatched path like this.

**Comment by DanTup** [comment]
I tried fixing it up automatically, but it needs doing in both directions (if Code gets an error for a mismatched path, it'll open "another copy" of the file); so the warning is the best we can do.
