### ISSUE TITLE
How will DDC integration work?

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#80]
Some thoughts:
- Entry points (HTML files in web folder) will be added to `launch.json`
- Pressing F5 will compile and launch browser
- Compiler should stay alive (like tsc) and recompile on file changes, so you can just reload the browser

Questions:
- What does a Hello World web app look like using DDC?
- What does the script tag in the HTML file look like?
- Where do we dump the compiled JS (inside web folder?)
- If DDC can output "compile errors" and we're also getting them from the Analyser, do we display them all? Do we hold off running DDC until Analyzer reports no errors (not possible if DDC runs in its own watch mode?)
- Does this mean we won't support non-strong-mode?
- Will people still want to use dart2js and/or Dartium far into the future such that we need to support them?
- Where is the web server? `pub serve`? If so, will this all play nice together?

**Comment by DanTup** [comment]
Found [this](https://github.com/dart-lang/dev_compiler/blame/15f19aab3674915942b02f120f111c9c5c32815c/web/main.dart#L11) (added 15 days ago):

/// Additionally, these commands are being considered
///   * link:  combines several JS modules into a single JS file
///   * build: compiles & links a set of code, automatically determining
///            appropriate groupings of libraries to combine into JS modules
///   * watch: watch a directory and recompile build units automatically
///   * serve: uses `watch` to recompile and exposes a simple static file server
///            for local development

though I'm confused by the commit message "Working compiler in browser.". WAT?

@devoncarew Is there a good place for info on how these things might hang together (other than grepping through the repo?)

**Comment by devoncarew** [comment]
That bit of code you found in DDC is for when it's running in the browser as part of devtools. I'm not sure it would be re-usable for a CLI tool but can't say for sure.

My 0.02 is that most efforts should be concentrated on DDC; dart2js or Dartium should be more targets of opportunity (or if people have strong interest there) rather than strategic targets.

This [guy](https://github.com/dart-lang/dev_compiler/blob/master/USAGE.md) was recently updated and has some info about using DDC. I believe the net-net is that DDC is largely a dart => ES6 module compiler, and something else will need to drive it to have a holistic build system for an app (the `build` package, bazel, grunt/gulp, ...). It should be possible to write a dev server that uses the DDC API and can re-compile sources on the fly.

The DDC team (via the dev_compiler repo?) is the best source of info here -

**Comment by DanTup** [comment]
> That bit of code you found in DDC is for when it's running in the browser as part of devtools.

Before I read the bit about the browser is sounded good, but then I got confused. I think you're right, probably of limited use. I asked a couple more questions in [Gitter](https://gitter.im/dart-lang/dev_compiler) that might help get me started.

**Comment by DanTup** [comment]
Some more notes from Gitter:

- No watch mode or http server, we'll need to provide them
- Suggestion is to compile a whole Dart package together (this probably means the whole `lib` folder in one go); should be fast if SDK and other lib summaries are available
- Code has a method for creating a FS watcher, we should probably use that to avoid missing changes outside the editor (probably only care about `.dart` files?)

I guess Node has stuff for simple http hosting; we should see if we can make it block during compilers in case the user hits refresh too quick after a save. We **must** make sure a local server doesn't expose users files ([see here](http://blog.saynotolinux.com/blog/2016/08/15/jetbrains-ide-remote-code-execution-and-local-file-disclosure-vulnerability-analysis/)).

**Comment by DanTup** [comment]
DDC works with `pub serve` now so I think this is all resolved. I've opened #386 to try and collect some more info while working on web stuff.
