### ISSUE TITLE
setBreakPointsRequest can send multiple responses

### ISSUE THREAD

**Issue by stuartmorgan** [Dart-Code/Dart-Code#868]
If getPossibleSourceUris in setBreakPointsRequest (in dart_debug_impl.ts) returns multiple URIs, then the loop that calls threadManager.setBreakpoints multiple times will result in sendResponse being called more than once.

While debugging the extension, this results in:
"attempt to send more than one response for command setBreakpoints"
being logged as an error to the console each time a breakpoint is set (at least while debugging the extension).

**Comment by DanTup** [comment]
Yeah :(

I started trying to fix this on a branch but it's kinda complicated. We currently can send multiple breakpoints to Observatory for a single breakpoint from Code. This is an attempt to make sure we don't miss them because of differences in `package:` and `file:`uris and because after a hot reload we need to use device-local paths (or at least did, it may have changed now - @devoncarew?)

Slightly related, is that when we send a breakpoint to Observatory we always tell VS Code that is resolved, even when it wasn't.

I'd like to fix all of these together; but it will be simplest when we have a one-to-one mapping between VS Code breakpoints and what we send to Observatory. I don't know if this is realistic but I hope so. If not, we'll just need to fix this in a way that allows us to maintain a one-to-many mapping for the breakpoints.

**Comment by DanTup** [comment]
#529 is related; sometimes we send two breakpoints and Observatory decides they're the same, so just sends back the same breakpoint as it did previously; and we don't expect that.

**Comment by DanTup** [comment]
Now that `package:` URIs work for scripts started with filenames, we just always send `package:` URIs if we can resolve them, and otherwise send paths. All integration tests are passing with this and the warning is finally gone :-)
