### ISSUE TITLE
Keyword highlighted as functions

### ISSUE THREAD

**Issue by KevinShiCA** [Dart-Code/Dart-Code#895]
Keywords that are immediately followed by parentheses are highlighted as functions if there isn't a space between the keyword and the parenthesis (see screenshot). They are correctly highlighted if there is a space.

The same happens for loops and switch statements.

<img width="213" alt="screen shot 2018-05-13 at 10 21 10 pm" src="https://user-images.githubusercontent.com/24703965/39975397-349cef7a-56fc-11e8-96f5-219edee4d6f2.png">

**Comment by DanTup** [comment]
Thanks; the syntax highlighting is a bit wonky right now because it's all regex based (for example it assumed anything that's PascalCase is a type!). The proper fix requires VS Code to allow us to provide colours based on the syntax tree (https://github.com/Microsoft/vscode/issues/585). However, this specific issue might be an easy fix; I'll take a look.
