### ISSUE TITLE
Recover from Flutter daemon quitting (eg. during flutter upgrade)

### ISSUE THREAD

**Issue by shaktiprakash099** [Dart-Code/Dart-Code#931]
![screen shot 2018-05-23 at 1 26 51 pm](https://user-images.githubusercontent.com/31213820/40411065-fde6a654-5e8c-11e8-9514-4220111fc951.png)

**Comment by DanTup** [comment]
I can't reproduce this :(

Is it possible you did something with flutter (like upgrading it) while you had Code running? I tried with an old version that didn't have the emulator stuff, but it just reports the error and does not terminate (so the first error is logged, as expected, but the second is not, and the daemon keeps running).

**Comment by shaktiprakash099** [comment]
yes i tried to upgrade flutter in VScode terminal

**Comment by DanTup** [comment]
Ah, that's probably what caused it to terminate then. I don't think this is a bug then, but since people may start upgrading from inside the IDE I think we should probably have a nice way to handle restarting the daemon if it quits. I'll re-purpose this issue for that.

**Comment by DanTup** [comment]
I believe this is actually working as intended. If you upgrade Flutter from within VS Code, the daemon may be terminated. When it does, you'll get a prompt like this:

![screen shot 2018-08-27 at 11 22 00 am](https://user-images.githubusercontent.com/1078012/44655066-bee6b700-a9eb-11e8-8380-b02bbb37178c.png)

The `Restart` button will perform a silent extension reload, restarting the daemon. We surface the error to the console (by re-throwing it) to aid debugging, since this is not a case we expect often (if you're seeing it when you're not upgrading, for ex, then we need to figure out why).

If you think there is still something wrong here or my explanation doesn't make sense, just shout!

**Comment by SuitMonkeyB** [comment]
I had this issue yesterday seemingly after an update. Invalidate Caches and Restart did the trick for me. See if it helps.

**Comment by DanTup** [comment]
Did you try clicking the `Restart` button on the prompt? It should work - if it doesn't it'd be good to know why not (does it give an error? what's still wrong afterwards?) to try and improve it.

**Comment by hemabhravee** [comment]
Clicking the  restart button on the prompt doesn't do anything for me. It doesn't give an error either. And when i try to run the app again i get the same prompt saying "The Flutter Daemon has terminated"

**Comment by DanTup** [comment]
@hemabhravee could you open a new issue with details, including the output of clicking the Show Log button?
