### ISSUE TITLE
Version 1.13.0 is missing a changelog in VS Code and repo

### ISSUE THREAD

**Issue by levrik** [Dart-Code/Dart-Code#971]
Please add a changelog so I can update the extension. I usually don't update extensions without a changelog.

_Edit:_ Just found the changelog on your homepage. Would be nice to also have in in VS Code.

**Comment by DanTup** [comment]
Ugh, yeah this is a mistake. The changelog.md file is supposed to be the most recent version, and a link at the bottom to the full list of versions on the website. I'm not sure I can fix it now (not sure if Code reads it from the package, or pulls live from the repo), but I'll try to avoid this in future!

The full release notes, as you probably found are here:

https://dartcode.org/releases/v2-13/

**Comment by DanTup** [comment]
I've replaced the changelog in the repo with a link to the website so that we never show stale changelogs (the website will always be updated, as it's where we link to in announcements). This might not be quite as convenient as having them inside Code, but it's only a click and guaranteed to be available :-)
